### ISSUE TITLE
__DEPLOY_VERSION__ for since tags in staging

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#10034]
#### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/search?utf8=%E2%9C%93&q=__DEPLOY_VERSION__

Is there a reason for not using 3.5.2 for the since tags there?

**Comment by brianteeman** [comment]
user error

**Comment by zero-24** [comment]
Ok i can send a pr tomorrow than if you are not faster than me ;)

**Comment by brianteeman** [comment]
you can do it ;)

On 21 April 2016 at 21:37, zero-24 <notifications@github.com> wrote:

> Ok i can send a pr tomorrow than if you are not faster than me ;)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10034#issuecomment-213104155>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by richard67** [comment]
@andrepereiradasilva Wasn't it you?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10034">issues.joomla.org/joomla-cms/10034</a>.</sub>

**Comment by richard67** [comment]
As far as I remember @andrepereiradasilva made this by purpose because he did not know the milestone yet for some recent PR(s), and he wanted to change that when it is clear if it will be 3.5.2 or 3.6. But I don't find that comment anymore now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10034">issues.joomla.org/joomla-cms/10034</a>.</sub>

**Comment by zero-24** [comment]
see #10037
