### ISSUE TITLE
Slow javascript processing of permission tab (Global configuration)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#10556]
#### Steps to reproduce the issue

Global configurarion Yes/No, showon and chosen styles are rendering to slow, originating Flash of Unstyled Content (FOUC).

#### Expected result

Render normally.

#### Actual result

Some 500ms where the Yes/No, showon and chosen are not properly renderend originating Flash of Unstyled Content (FOUC).

#### System information (as much as possible)

Latest staging.

#### Additional comments

Something to do with the permissions tab part.

All work fine (just an expected small delay due to showon hiding fields) if for testing proposes the permissions actions are removed (some or all) in https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/form/application.xml#L1007-L1046.

**Comment by Bakual** [comment]
The permission tab doesn't use chosen for exact that reason.
If chosen is loaded in your case for that tab, then something else loads it.

**Comment by andrepereiradasilva** [comment]
"My case" in Joomla staging clean with sample data.

**Comment by andrepereiradasilva** [comment]
Also chsen is not loaded for in the permission tab as you can see.
![image](https://cloud.githubusercontent.com/assets/9630530/15393316/9135b780-1dc4-11e6-9b23-1778ccd821aa.png)

**Comment by Bakual** [comment]
Yeah that's what I mean, chosen isn't loaded in the permission tab. Those are regular select boxes.
I understood your issue description that you blame chosen for it, but it shouldn't be the case since it isn't active on that tab. Also there is no `showon` on this tab.

There is however some JavaScript doing some ajax stuff on this tab. Thus it may be related to that?

**Comment by andrepereiradasilva** [comment]
>Yeah that's what I mean, chosen isn't loaded in the permission tab. Those are regular select boxes.
I understood your issue description that you blame chosen for it, but it shouldn't be the case since it isn't active on that tab. Also there is no showon on this tab.

i didn't blame chosen. i blamed javascript processing :wink: 

All javascript inside all global configuration tabs are processed on page load (or document ready).

> There is however some JavaScript doing some ajax stuff on this tab. Thus it may be related to that?

Very probably. I will disable the permission js to see what happens.

**Comment by andrepereiradasilva** [comment]
just tested. no, not related to permissions.js

**Comment by ggppdk** [comment]
@andrepereiradasilva 

I can reproduce this (FOUC) delay  (Flash of Unstyled Content)
about 0.3 - 0.6 seconds depening on the browser
on a new installation of staging (on localhost)
- **when "Debug System" parameter is enabled**

and it is because, **some styling is JS based** (e.g. bootstraps styling on radios and ...)
- thus if the bootstrap styling (and its event attaching) runs after some other heavy JS, e.g. the JS of the DEBUG information

then you get the above effect,

Also other things that contribute a little more to the effect:
- attachForm of html5fallback.js **adds a little more to it**, 
- also in real installations with more HTML and larger forms, the effect is made even more noticeable

i think this is not the first time that this is discussed, there was an issue about sidebar jumping when "System debug" parameter is ON

how much time the browser waits to make a non-forced refresh depends on the browser, so you can also experience a "freeze" effect instead of the FOUC delay

If you don't have Joomla System debug ON then the effect could be by some browser plugin ?
like skype-click-to-call that examine and modify the HTML ... then also test with your browsers in safe mode

**Comment by andrepereiradasilva** [comment]
i have no debug plugin ativated. I have no browser plugin. clean joomla staging with sample data.

**Comment by ggppdk** [comment]
I don't know then,
i was only guessing above,

maybe chrome console is better for profiling this, than console of other browsers ? (i need to check if edge is good / easy at profiling)

But can you also check, if you have configured your webserver to always send no-cache headers to the browser ?
and thus browser is never caching CSS / JS files ?

If you open browser tools and go to the network TAB,
then most browsers would have a column to report what happens with file retrieval

that if CSS / JS / HTML file was 
- downloaded --- or retrieved from cache --- or if server was ask if it was modified
- if web-server was asked ... answer would for re-downloading (HTTP 200 OK), or if it was not re-downloaded, response would be "HTTP 304 not modified"

**Comment by Fedik** [comment]
@andrepereiradasilva why do you think it just permission tab? it just a tab :wink: 
other parts of the form just hidden, but it does not means that they not affect whole page rendering.

as you already wrote, there 2 recourse eaters showon (1 place) and chosen (2 place),
`showon` need to optimise, and `chosen` just drop (old topic) :smile:

**Comment by andrepereiradasilva** [comment]
> @andrepereiradasilva why do you think it just permission tab? it just a tab :wink: 

because when remove some (or all) permission select fields all work without any FOUC

**Comment by Fedik** [comment]
ah, right :smile:  

well, but still, it is problem in amount of the fields on the page, and permission field can include a looooot of them, due its logic. And because of this the `showon` need more time to set up.

Same can happen in any other form with huge amount of the fields, without permission field.

**Comment by andrepereiradasilva** [comment]
yes, for sure it has to do with the quantity of fields in a page.

Not 100% sure the problem origin is chosen or showon ... need to test without chosen and showon js behaviours.
