### ISSUE TITLE
Batchprocess of menu module into new menus with language setting fails

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-cms#10554]
#### Steps to reproduce the issue
Create different language menus for different languages in a multi language site. 

Have about 30 different menus in 3-4 languages for different menu modules. 

Take one menu that you try to batch process into another one language menu with its menus into a new menu structure ie 30 menus. You make all settings and choose copy and to one selected new language instead of all languages where the module setting is now.

#### Expected result
The menu copy all menus to the new menu with the new preferred selected language ie "All" --> fr-FR for the menus

#### Actual result
The menus got copied correctly b u t with language setting to "All" instead of the setting to the selected language "All" --> fr-FR when you did when doing the batch process. Seems that the selection can not process the language correctly to be set up for each menu languages

#### System information (as much as possible)
Joomla 3.5.1 php 7.0.6

**Comment by ssnobben** [comment]
Hmm this suddenly worked after I tried several times dont know why this suddenly start working. So can close this one..rgds<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10554">issues.joomla.org/joomla-cms/10554</a>.</sub>

**Comment by infograf768** [comment]
Ths is a bit confusing.

First, modules have nothing to do with batch processing menu items (NOT menus).

So, I tested.
1. I have a menutype (also called "Menu"), for example "mymenu_all", where all menu ITEMS are tagged to Language "All".
2. I created a new menutype "mymenu_fr".
3. I select all items of mymenu_all and use batch copy (changing language to fr-FR in the batch) to the "mymenu_fr" menutype.

All works fine. "mymenu_fr" is now populated with all items from "mymenu_all" and tagged to fr-FR instead of "All"

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10554">issues.joomla.org/joomla-cms/10554</a>

**Comment by infograf768** [comment]
Closed per request<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10554">issues.joomla.org/joomla-cms/10554</a>.</sub>
