### ISSUE TITLE
Unused method?

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10629]
Looks like the method `sendAdminMail`
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/mail/mail.php#L738-L768
is not used in core at all.

The lang strings are not even present.

Looks like it has been replaced at one point with a message sent to admin (see `COM_CONTENT_ON_NEW_CONTENT`

Shall we just delete it, or at least mark it as deprecated (I looked at 2.5 and the strings are also absent from there).?
Or, else, use it again to also send a mail to admin when a new article submission ?

**Comment by brianteeman** [comment]
Definitely mark it as deprecated if the core isnt using it but as its a library who knows who/what else will be using it so i doubt it can be removed with 100% safety

**Comment by sovainfo** [comment]
Suggest to fix the regression caused by https://github.com/joomla/joomla-cms/commit/7fcf7f6d0327976e49704e1f25fc9da2a8f199b7#diff-98e863dabf8033c2313bc92e9c99cc2f before it hits the streets in J3.6. If not, you'll find out who uses it the hard way. It doesn't work when not fixed.

Agree with mbabker about the poor implementation, would be useful to set the recipient, but unfortunately that requires a change in the API.
Surely extensions implementing desired functionality considered the provided functionality too limited and created their own.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10629">issues.joomla.org/joomla-cms/10629</a>.</sub>

**Comment by mbabker** [comment]
Err what regression?  Actually raising errors in JMail and catching
phpmailerExceptions instead of letting them bubble up the stack?  Or is my
mobile just not linking to a good spot on that diff?

**Comment by sovainfo** [comment]
Maybe you forgot to change $email into $recipient.

**Comment by infograf768** [comment]
folks, looks like this is not related to my report. the method concerned exists for long without any language strings which makes me think it was never used.

**Comment by sovainfo** [comment]
Those strings would have to be provided by extensions/overrides wanting to use this function.
Considering you can't just remove it before J4, suggest to fix it.

**Comment by mbabker** [comment]
Oh, whoops.  Too much copy/paste.

**Comment by sovainfo** [comment]
In J351 it sends to the site admin email address. Guessing users would want it to go to $email or $recipient as a better name..
