### ISSUE TITLE
Unable to update Joomla from 2.5.9 to 3

### ISSUE THREAD

**Issue by raviaonhewitt** [joomla/joomla-cms#10635]
Hello Team,

Currently I am using 2.5.9 Joomla version and I want to upgrade it to 3.
But in the administrator window it shows, "Joomla! is up-to-date" and that we are on the latest version (which is clearly not true).
I have tried the most of the solutions which are available on net, but unable to upgrade it.
Please advice ASAP.
Please see attachment.![screen shot 2016-05-26 at 09 32 08](https://issues.joomla.org/uploads/1/f3dbc036ec7f4d20573f305d2677da0d.jpg)

**Comment by kalemanzi** [comment]
Hi raviaonhewitt. You don't need to open an issue on the tracker for this, rather ask a question in the forum or do a google. The tracker is where issues are tracked for the development versions of Joomla to iron out issues so they can be merged into the next release. Development on Joomla 2.5.x has stopped. Head over to https://docs.joomla.org/Joomla_2.5_to_3.x_Step_by_Step_Migration for instructions how to do that upgrade. You will see there it says you must  _Select Short Term Support (This is the current text - it may be different in the future) from the drop-down for Update server._ otherwise it will not prompt you to upgrade to 3.x from 2.x.x Hope this helps. You are welcome to contact me if you run into any further issues. gfx(at)kalemanzi.com ;-)

**Comment by Bakual** [comment]
Closing as not an issue with the code but a support request which should be handled in the forums.
