### ISSUE TITLE
Feature request: Allow overriding view.*.php

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#10650]
It would be helpful if one can override the `view.html.php`, `view.feed.php` etc. in the template.

[This plugin](https://github.com/juliopontes/joomla-override) allows that, but this could be part of the core.

See also https://docs.joomla.org/How_to_override_the_component_mvc_from_the_Joomla!_core

**Comment by brianteeman** [comment]
Personally speaking as a free extension exists to do what you ant I dont see the benefit of adding it to the core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10650">issues.joomla.org/joomla-cms/10650</a>.</sub>

**Comment by smehrbrodt** [comment]
Well the extension is unmaintained and buggy. I tried it and could override my rss feed, but it broke the other view (view.html.php).

**Comment by chrisdavenport** [comment]
Overriding in the way suggested in architecturally unsound and likely to lead to fragile code and broken sites.

**Comment by smehrbrodt** [comment]
Ok, then maybe you have another suggestion.

My usecase is the following:
I have an extension (event management) that offers me an RSS feed in view.feed.php.
I want to modify the content of the RSS feed (e.g. not show the date + time in the content).

How can I override the default output? There are no layouts involved.

**Comment by JoomliC** [comment]
@smehrbrodt Did you ask first to the extension's developer ?
As it could be a feature request for this extension ;-)

About Joomla, what could be a feature request, would be the creation of a jlayout for rss feeds maybe ?...

**Comment by Bakual** [comment]
The way the feed works, it doesn't need or support a layout.
Maybe it makes sense to add options to it, but I don't think overriding the view file is the answer.
Or maybe just create your own view instead (may need an own extension of course).

**Comment by mbabker** [comment]
If you get access to the controller singleton instance you can add paths to the internal lookup via `JControllerLegacy::addViewPath()`.  The problem is because `JControllerLegacy::getInstance()` only supports a single singleton instance for the entire request (as in you can't use it to get instances of multiple controllers, major MVC layer flaw) in your plugin where you set this additional path lookup (because you'll have to do it before the component is triggered because the next plugin event is going to be after the view is loaded and being rendered generally, if not after the view is rendered) you need to ensure you're doing the right checks to not cause the wrong controller to be loaded in first.

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10650">issues.joomla.org/joomla-cms/10650</a>.</sub>

**Comment by smehrbrodt** [comment]
> Closed

Why? This is a feature request.

**Comment by brianteeman** [comment]
For the reasons stated by @bakual and @mbabker
