### ISSUE TITLE
[Regression] Unable to install with multilanguage

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#10696]
#### Steps to reproduce the issue
try to fresh install with some languages

#### Expected result

you are able to install with more than the en-gb

#### Actual result

you are stuck on multilaguage selection page

#### System information (as much as possible)
current staging

**Comment by andrepereiradasilva** [comment]
Confirmed. Just go to `/installation/index.php?view=languages` and try to install. No install, no error nothing.

Further info:

Adding `console.log(xhr.responseText);` in the installation js catch exception (the exception catch is empty?)
https://github.com/joomla/joomla-cms/blob/staging/installation/template/js/installation.js#L66

Returns "The file Cache Storage is not supported on this platform."

**Comment by mbabker** [comment]
What's trying to use `JCache` in the install app!?  That shouldn't be getting used at all...

**Comment by brianteeman** [comment]
Probably @mbabker recent pr then

**Comment by andrepereiradasilva** [comment]
and why there is no error messages in installation?  `catch (e) { }` ?

**Comment by mbabker** [comment]
If you value your sanity don't get me started on the state of the install app 😉

**Comment by andrepereiradasilva** [comment]
ok i value my sanity a lot!!

**Comment by alikon** [comment]
we all love our in-sanity ;)

**Comment by mbabker** [comment]
Well I have one reason why the file cache adapter would be throwing an error.  `JPATH_CACHE = JPATH_ROOT . '/installation/cache'` in the install app, the `cache_path` param doesn't get set in the installation, so `JCacheStorageFile::isSupported()` rightfully returns false because the param isn't set and the directory being defined doesn't exist.

I'm still curious why the cache API is being used though...

**Comment by andrepereiradasilva** [comment]
i can install languages in the admin so is only a install problem

**Comment by mbabker** [comment]
I found my answer.  `JInstallerHelper::downloadPackage()` tries to import the installer plugin group, importing plugins triggers a call to the ACL API to get the user's view levels, that has a call to get the `com_users` params via `JComponentHelper`, and that uses the cache API.  So that's why `JCache` gets called.

A few possible fixes.  Including setting a default `cache_path` param value of `JPATH_ROOT . '/cache'` so that the param is defined and correctly used and adding a cache directory to the install app so uses of `JPATH_CACHE` work in that context.

**Comment by andrepereiradasilva** [comment]
> I found my answer. JInstallerHelper::downloadPackage() tries to import the installer plugin group, importing plugins triggers a call to the ACL API to get the user's view levels, that has a call to get the com_users params via JComponentHelper, and that uses the cache API. So that's why JCache gets called.

that was fast :wink: 

> A few possible fixes. Including setting a default cache_path param value of JPATH_ROOT . '/cache' so that the param is defined and correctly used and adding a cache directory to the install app so uses of JPATH_CACHE work in that context.

seems good

**Comment by alikon** [comment]
close cause #10699 solved this issue
