### ISSUE TITLE
No option to select multiple plugins and Publsih/Unpublish

### ISSUE THREAD

**Issue by Bodge-IT** [joomla/joomla-cms#10726]
#### Steps to reproduce the issue
Goto Plugins Manager

Select multiple plugins
#### Expected result

Publish/ Unpublish buttons to be present as with all Joomla "elements".

#### Actual result

No standard options to Publish / Unpublish buttons are present at all.
You can only use the tick box in the list to unpublish/publish a single plugin.

#### System information (as much as possible)

Goes back to at least 3.4.8

**Comment by brianteeman** [comment]
That is because plugins are enabled/disabled and not published/unpublished.
 ![screen shot 2016-06-04 at 21 18 06](https://issues.joomla.org/uploads/1/c7f6aff7249782a10a156d2c71d4e3fc.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10726">issues.joomla.org/joomla-cms/10726</a>.</sub>

**Comment by Bodge-IT** [comment]
Ahh...Cannot believe I misunderstood that...I'll get my coat.
