### ISSUE TITLE
Use JForm and formfields for batch modals

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#10805]
First a comment to #10237
@JoomliC 
Is it possible to avoid conflict between the new class "modalTooltip" and the formfields "hasTooltip". I have that problem.

Is it a B/C issue to use JForm and formfields for the batch modals? i.e. the same handling as for the filter form. The following image shows a test with the articles. The fields used are standard and nothing new. The texts are the same - no new textstrings. As far as I understand there have allready bin changes that left some "orphans" in the tmpl folder.

![artikel_batch](https://cloud.githubusercontent.com/assets/956537/16006194/f8707f10-316b-11e6-8da8-9722f2ed3452.jpg)

I used a xml description:
batch_articles.xml,

A new method;
getBatchForm($data = array(), $loadData = false),

The same code in default.php:
JHtml::_('bootstrap.renderModal' ...

Except that I replaced the footer and the body with direct calls to new JLayouts,
JLayoutHelper::render('joomla.batchtools.footer',...
JLayoutHelper::render('joomla.batchtools.body',...

Advantage - I can use the formfields and do not need the JHtml::_('batch.language') things.
At least it helped me to run other batch methods on item lists. I have the fields needed anyway.

What do you think?

**Comment by schnuti** [comment]
@JoomliC 
More to explain the conflict.  I add the new class in the form with labelclass="modalTooltip". The "hasTooltip" is added by the formfield code. i.e. I have 2 classes for the label. 
For this test I changed the core code to add "hasTooltip" only if it's emty. That is not B/C!

**Comment by JoomliC** [comment]
@schnuti All i can answer for now is that i didn't have yet redo the batch fields. ;-)
And the <code>modalTooltip</code> class is not new, and not added by me, but added 2 years ago by this PR https://github.com/joomla/joomla-cms/pull/3149 (to use a dedicated class to fix Bootstrap tooltip when inside a modal)
And those ones are not well generated using standard BS HTML structure as used in other forms.
The reason you have classes tooltip conflict is because you try to generate the batch content in a different way (in core, no classes conflict) and it is due to the "forced" hasTooltip class in label render jlayout, which is not used to generate core batch form field labels (in the improvement i've planned for batch modals, this won't be the case if you want to propose to use jform xml for batch.).

About using a xml files to generate the batch form fields, well maybe it's possible, as batch fields are generated from a view layout, but not sure it could add a benefit somewhere as if you want to change articles batch modal, you can use an override of the view... (but maybe i miss your intention ?)

**Comment by brianteeman** [comment]
Is this still an issue. I think the batch modals have been updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10805">issues.joomla.org/joomla-cms/10805</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as stated above. It can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10805">issues.joomla.org/joomla-cms/10805</a>.</sub>
