### ISSUE TITLE
Session registry for userState failes to initiate

### ISSUE THREAD

**Issue by molteber** [joomla/joomla-cms#10820]
#### Steps to reproduce the issue
Log in, do something which will save something on the user state `setUserState`
Log out, log in to a new user. Try doing the same. When loading the page again the userstate will not be set

#### Expected result
Expected result would be that the session `registry` would be set and contain the user states.

#### Actual result
When reading the session, getting `registry` will return null.
This happens when you log out.

#### System information (as much as possible)
Windows 7 - dev
CentOS
Joomla 3.5.1

#### Additional comments
As a temporary fix I override the `setUserState` method in `libraries\cms\application\cms.php` to set the registry if it was null.
Not sure where to put the actual fix, but there could be some checks on the method `afterSessionStart` to create the registry if it's null instead of only `isNew()`

**Comment by sovainfo** [comment]
Can't consider that a fix. Current behaviour is as expected. The user state is private for each user. It doesn't effect different users. So, it works as designed!

**Comment by molteber** [comment]
The problem isn't that it's private for each user. The problem it that after you log out, it won't recreate the registry for the possible new user who logs in. So everytime you try to `setUserState` after a logout, nothing will work because the session registry is null.

I can't believe that THAT is the expected behavior.

**Comment by sovainfo** [comment]
Don't have this issue on 3.6.0 Beta !

**Comment by molteber** [comment]
Hmm, I will do some more research and come back to the issue

**Comment by sovainfo** [comment]
Tested in the backend using the submenu on Articles. Switched between SU and an administrator. Setting the submenu to hide on SU, switch to other component and return to Articles. Log out, log in as administrator. State by default is Show, set it to Hide, go to different component and return to Articles: submenu is hidden. Log out, login as SU, state submenu is still as set just before log out. Same thing when logging back in to administrator. UserState works for submenu of Articles.

**Comment by brianteeman** [comment]
Closed based on the comments above. If it is still an issue it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10820">issues.joomla.org/joomla-cms/10820</a>.</sub>

**Comment by sarduk** [comment]
I'm getting the same problem on joomla3.6.2
after you log out, and then login, it won't recreate the registry into the session, so that setUserState and getUserState dont work.
My a temporary fix/workaround is to override setUserState and getUserState to avoid use registry.
someone found how to fix?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10820">issues.joomla.org/joomla-cms/10820</a>.</sub>

**Comment by sovainfo** [comment]
Confirm the issue in j362, request for reopening!

**Comment by brianteeman** [comment]
Reopened as requested

**Comment by rbnevins** [comment]
I am having this same problem.  Works correctly on joomla 3.5.1 but on 3.6.2 it behaves exactly as molteber and sarduk described.  However I found that if I clear cookies in the browser then it fixes the problem.  Of course that isn't something I can expect our users to do every time if fails but it may provide some insight into the problem.

**Comment by rbnevins** [comment]
I did some comparing for changes in the session handler between 3.6.0 and 3.6.2 and I found that in libraries/joomla/session/session.php, in the fork() method, there was this statement in 3.6.0:

                // Kill session
		$this->_handler->clear();

This is at approx. line 772 in the file.  This statement was removed in 3.6.2.  When I put that statement back in, it fixes the problem for me.  Now I can log out and log back in again and the setUserState method now works as it should.

Now since I really don't understand the details here, I'm not advocating this as the "fix".  However I am going to use it on my test system as at least a temporary work around until the final fix is provided.

**Comment by franz-wohlkoenig** [comment]
@molteber is the Issue also on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10820">issues.joomla.org/tracker/joomla-cms/10820</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
