### ISSUE TITLE
Update package installer

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#10965]
#### Steps to reproduce the issue
Is it to update older version for test because it is named update installer package?
It is not installable as update. Seems to be a full package for full install from scratch.

#### Expected result
Update installed

#### Actual result
cannot find xml file. Cannot find installer package

#### System information (as much as possible)
J 3.5.1

**Comment by brianteeman** [comment]
You cannot use the joomla extension installer to update joomla

**Comment by zero-24** [comment]
Please see also: https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5 The correct way to update Joomla is the com_joomlaupadate component.

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10965">issues.joomla.org/joomla-cms/10965</a>

**Comment by zero-24** [comment]
Closing as `Expected behaviour`. In 3.6 you will get some more stuff for com:joomlaupdate where you can upload a package again. but it is not possible anymore to do this via the extension update :smile: Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10965">issues.joomla.org/joomla-cms/10965</a>.</sub>
