### ISSUE TITLE
Cannot find installer in 3.6.0RC1

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#11034]
#### Steps to reproduce the issue
Go to Extensions > Manage > Install

#### Expected result
The installer that lets you select the installable file

#### Actual result
![admin_installer](https://cloud.githubusercontent.com/assets/1838041/16612453/b6f25534-436f-11e6-8ca6-ad1d4535b1b3.png)

#### System information (as much as possible)
Joomla 3.6.0RC
PHP 5.5.9

#### Additional comments
Not sure if it's related with any ACL stuff. 
I am logged in as super admin and it was working before updating to J3.6.0RC

**Comment by brianteeman** [comment]
Was this an upgrade from a beta or early 3.6 release? If so then there is no upgrade path from them. Can you please confirm if this is an issue when upgrading from 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11034">issues.joomla.org/joomla-cms/11034</a>.</sub>

**Comment by sakiss** [comment]
I upgraded from 3.5.1 stable

**Comment by ggppdk** [comment]
@sakiss 

Reading your text, i have a question, do you mean

- that the installer plugins **should be by default enabled**  ??
- or you **have not noticed the message** that asks you to go to plugin manager and asks you to **enable the installer plugins** ??

(J3.6 converts the 3 installation methods, into installer plugins, (the install from web was already a plugin))

so if you click on the link inside the message, then you will go to plugin manager with type filter set to:
"installer", thus you will see all plugins, and you can enabled them

**Question**: 
Since using installer plugins is new feature, are the plugins supposed to be automatically enabled when upgrading , thus making installation page be same as before ?

Are they by defaut disabled on upgrade ?

i ll checked the SQL files
- on new joomla installation , i see that joomla.sql file gets them enabled
https://github.com/joomla/joomla-cms/blob/53aad6f251d13257d58ca3e7b8317a7de576b2b2/installation/sql/mysql/joomla.sql#L614-L616

on upgrading, is there something similar ?

**Comment by brianteeman** [comment]
Thank you for confirming that - I will see if I can replicate it

Can you click on the link at the top to the plugin manager and check if the
install plugins are enabled or disabled. (based on your screenshot I am
assuming they are disabled) and then enable them and make sure it looks as
it should

On 6 July 2016 at 10:13, Sakis <notifications@github.com> wrote:

> I upgraded from 3.5.1 stable
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/11034#issuecomment-230719700>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8UJ4xNhrhSx6iwtPxw5C1ypoebwGks5qS3GzgaJpZM4JF3-e>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sakiss** [comment]
The installer plugins are enabled as well and the message is not valid. 
Moreover, these regard 3rd party extensions and not the core installer.

**Comment by sakiss** [comment]
Indeed they were the installer plugins.

Seems like Joomla! 3.6 is introducing 3 new plugins related with the installation process (Install from Upload, Install from Folder, Install from URL). Each 1 corresponds to a relative installation process.

So anyone who is not upgrading joomla using the joomla's upgrade process should have this in mind.

**Comment by brianteeman** [comment]
Oh so you were not using the Joomla upgrade component - then it is expected
that things will not work

I just tested an upgrade from 3.5 to 3.6 with the upgrade component and it
works as expected

On 6 July 2016 at 10:36, Sakis <notifications@github.com> wrote:

> Indeed they were the installer plugins.
>
> Seems like Joomla! 3.6 is introducing 3 new plugins related with the
> installation process (Install from Upload, Install from Folder, Install
> from URL). Each 1 corresponds to a relative installation process.
>
> So anyone who is not upgrading joomla using the joomla's upgrade process
> should have this in mind.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/11034#issuecomment-230724899>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8crx9fBgJOOk1Cc7YsVWEzhKAJDAks5qS3cNgaJpZM4JF3-e>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closing as it is expected that an update performed without using the update component will not be 100%<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11034">issues.joomla.org/joomla-cms/11034</a>.</sub>
