### ISSUE TITLE
jce,akeeba,acymailing update is no longer available via joomla updater

### ISSUE THREAD

**Issue by fabioassenzio** [joomla/joomla-cms#11104]
#### Steps to reproduce the issue

Install an older version of the ext mentioned in title
Delete cache (site, admin)
Delete cache (update cache)
Delete and generate again update site
Try to use updater, no new versions of any ext is displayed

or

go to updater with joomla version 3.5.1
see new versions of ext mentioned are present
update joomla to 3.6
Delete cache (site, admin)
Delete cache (update cache)
Delete and generate again update site
Try to use updater, no new versions of any ext is displayed

#### Expected result

New versions of ext displayed in joomla updater

#### Actual result

No new versions displayed in joomla updater

#### System information (as much as possible)

Joomla 3.6
php 5.6
Mysql 5.6
Apache 2.4

**Comment by OctavianC** [comment]
Because their XML file is not reflecting 3.6 as a supported version:
`http://cdn.akeebabackup.com/updates/pkgakeebacore.xml`
Look for `targetplatform` and you'll see 3.5 as the newest supported version of Joomla! - they probably need a heads up to update the XML file.

So, not an issue with Joomla! 3.6

**Comment by fabioassenzio** [comment]
right!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11104">issues.joomla.org/joomla-cms/11104</a>.</sub>
