### ISSUE TITLE
Backend: Articles -> Options -> Show Icons does not disable Email/Print if set to No

### ISSUE THREAD

**Issue by hdouglassmith** [joomla/joomla-cms#11126]
#### Steps to reproduce the issue
In adminstrator go to the Article Manager
Click Options (top right)
Scroll down to 'Show Icons' make sure 'Show print icon' and 'Show email icon' are both set to 'Show' (Default)
Now set 'Show Icons' to Hide. This causes 'Show email icon' and 'Show print icon' options to disappear which suggests they are both disabled.
Now save
Create an article
Create a menu item to point to this article (can be single article or category blog etc).

#### Expected result
Viewing article in front end should show no icons

#### Actual result
View article in front end. Print and Email icons are visible. 
If the 'Show Icons' is temporarily turned on to reveal the 'Show Print Icon' and 'Show Email Icon' options and these are manually turned off, then they are not shown.

#### System information (as much as possible)
Joomla 3.6.0
PHP 7.0.8
Firefox browser on OSX
Tested with Protostar template and with Yootheme Edge, both exhibit similar issues.

**Comment by APD183** [comment]
I think everything in the article options that has an equivalent in the menu item options behaves this way (the one we noticed was the 'Show Title' setting): Menu item setting overrides article setting. Based on some quick searches, this is "expected behavior", but I'd like it to be talked about because it is not intuitive to have a list of settings that gets overridden without at least a notice somewhere.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11126">issues.joomla.org/joomla-cms/11126</a>.</sub>

**Comment by RonakParmar** [comment]
I have checked, Article individual settings are not working at front-end,but global option settings working fine at front-end. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11126">issues.joomla.org/joomla-cms/11126</a>.</sub>

**Comment by hdouglassmith** [comment]
Further checking on this. In 3.5.1 the issue is the same. However the tooltip on Show/Hide Icons states "Print and Email icons will utilise icons or text". Therefore the issue is that the new and seemingly intuitive hiding of the print/email options when Show Icons is set to Hide, is actually wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11126">issues.joomla.org/joomla-cms/11126</a>.</sub>

**Comment by brianteeman** [comment]
Closed please see #11261 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11126">issues.joomla.org/joomla-cms/11126</a>.</sub>
