### ISSUE TITLE
Redirect after Logout don't work in Login Module

### ISSUE THREAD

**Issue by hacki65** [joomla/joomla-cms#11149]
#### Steps to reproduce the issue
Login and than logout with a module in a menu

#### Expected result
Redirecting to the specified page e.g. Homepage

#### Actual result
Stay at the last site and this site is then blank because logout :)

#### System information (as much as possible)
Joomla 3.6, PHP 7.08

#### Additional comments
Can anybody confirm this?

**Comment by justinherrin** [comment]
It's an issue with Joomla 3.6.0... Should be fixed in 3.6.1

See this PR for it: #11093

**Comment by hacki65** [comment]
Thanks for Info

**Comment by brianteeman** [comment]
Closing

**Comment by ddonpainuly** [comment]
This issue is not just the redirect problem, i am using joomla 3.6 with VirtueMart 3.0.14, when user logout along with the wrong redirection the session of the user is also removed which causes the cart data of the user to be lost.
The redirection issue is due to the UsersControllerUser line 165
`if (is_numeric($return))
{
- - - -
- - - -
}`
$return is string URL so the condition is false
you can  add a else condition  like
`else
	$app->redirect(JRoute::_($return, true));`
This will fix the redirection issue but the session management is still a problem.
Please fix the issue in J3.6.1.

**Comment by infograf768** [comment]
You better talk with Virtuemart.
Since the correction brought to `JUri::isInternal()`, $return has to obey to some strict formatting.
The correction was done for security reasons.

The else condition is
```
		else
		{
			// Don't redirect to an external URL.
			if (!JUri::isInternal($data['return']))
			{
				$data['return'] = '';
			}
		}
```
