### ISSUE TITLE
Update 3.6.0: Exception xyz Cache Storage is not supported on this platform blocks login in backend

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#11150]
It was reported in a forum and e.g. here
http://www.itoctopus.com/the-file-cache-storage-is-not-supported-on-this-platform-error-after-updating-to-joomla-3-6
that backend was not usable anymore after update to 3.6.0 because of a thrown exception introduced here:
https://github.com/joomla/joomla-cms/pull/10339/files

also with
`public $caching = '0';`

> The file Cache Storage is not supported on this platform

Reason was that cache and/or administrator/cache are not writeable.

I know that's a misconfiguration but question is now if the message should be more detailed concerning the real problem or if a more user friendly error handling (enqueueMessage(...) or something) is possible in this case to make login in backend possible like in Joomla 3.5.

Test instructions:
Delete folder administrator/cache or make it unwriteable. Then try to login in backend.
=> Exception

Open configuration.php and change `public $cache_handler = '';`

Now login is possible without errors.

In some cases changing `public $cache_handler = 'cachelite';` worked, too. But looked like not always.

**Comment by mbabker** [comment]
It is as friendly as can be.  JCache is not the place to make "user
friendly" error handling happen.  The API is reporting a critical error.

It happens even with cache turned off because Joomla's API is too eager and
tries to load the storage adapters then checks if caching is even enabled.
I have one PR open that tries to address this eagerness.

The reported error is right, as is the manner in which its reported (the
same as how other fatal errors are caught in that method).  The possible
TODO items are to address the over eager loading of resources (started) and
making anything consuming from the cache API error aware and able to deal
with issues like this.

Look, I'm sorry sites go "down" because of added error checks for possible
issues, but everyone who has suggested that the fix is for Joomla to
silently absorb errors and keep functioning is wrong.  Yes, things can be
made more fault tolerant and graceful fallbacks added as able, but that's
an implementation detail to be handled by the cache consuming service (i.e.
JComponentHelper or JPluginHelper which cache the respective extension
data), not inside the cache service API.

**Comment by bertmert** [comment]
Thanks for this lucid explanation. Now we have a further reference for the next few days for endlessly discussing guys.
Closing.
