### ISSUE TITLE
Tag routing is broken on multilingual sites

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#11163]
#### Steps to reproduce the issue
Create Articles with tags on a multilingual site.
Create Menuitems with a link to the specific tag
Create Menuitems to all tags.

#### Expected result
If you click on a tag below an article the adress should be something like
www.yourdomain.com/tag/tagname

#### Actual result
If you click on a tag below an article you are forwarded to:
component/tags/tag/tagname

#### Additional comments
There seems to be a check missing for multilang... because for one language it´s working perfectly...

**Comment by mbabker** [comment]
It's not just multilingual.  Routing between components is broken in general.  Install Joomla's sample testing data and compare the links for the tags from the homepage "Joomla! Testing" article item versus when you're on the `/all-tags` page (the "All Tags" item at the bottom of the "All Front End Views" list).

**Comment by designbengel** [comment]
Just tested and: Yes i confirm! I thought it has something to do with multilingual because before implementing the other languages on 3.6 page the routing looked nice...

**Comment by yvesh** [comment]
@mbabker Yes, but it is also a tags specific problem in that case:

`TagsHelperRoute::getTagRoute`

Defines only the id as needle in search for the itemId, language is this way always (hardcoded) to *. 

The URL could look like that else-wise

domain.com/aliasTags/tag/tagname, better then component/.. imo

See this [line](https://github.com/joomla/joomla-cms/blob/staging/components/com_tags/helpers/route.php#L115)

**Comment by mbabker** [comment]
The tags helper also doesn't account for the fact that a tag view may have its URL based on a parent tags view's menu item; it only looks for a tag view and that's in part where the inconsistent routing comes from.  It is not just a language issue.  Although that part could probably be fixed by applying the same logic as used for the com_content route helper.

**Comment by csthomas** [comment]
@designbengel If you require real fast patch you can test #11166.

**Comment by proweb** [comment]
It problem not multilang. It's problem since the day of tags was added to core.

**Comment by ymages** [comment]
Same issue here , since Joomla 3.6 tags links return nothing
example here http://www.dpm-images.fr/component/tags/tag/31-aspherique <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11163">issues.joomla.org/joomla-cms/11163</a>.</sub>

**Comment by csthomas** [comment]
Is it still up to date? How can I repeat the issue on Joomla RC4?

**Comment by csthomas** [comment]
> Is it still up to date? How can I repeat the issue on Joomla RC4?

Ok, I find a way to repeat this issue.

**Comment by zero-24** [comment]
ca we close this as there is a PR @csthomas ?

**Comment by franz-wohlkoenig** [comment]
closed as having PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11163">issues.joomla.org/tracker/joomla-cms/11163</a>.</sub>
