### ISSUE TITLE
Alert message "Core"-Template Protostar after "Compile LESS" and "Save & close"

### ISSUE THREAD

**Issue by knewbeee** [joomla/joomla-cms#11201]
#### Steps to reproduce the issue

S1: Create a user.less file in the Protostar. 
S2: Insert some rules. 
S3: Save the file. 
S4: Compile LESS.

Alert: Message Successfully compiled LESS. -> OK

S5: Save & close

Alert: 
Message
_You should compile /less/user.less to generate a CSS file._
File successfully saved.

#### Expected result

_You should compile /less/user.less to generate a CSS file._ should **_NOT_** appear.
Because the file was already compiled.

#### Actual result

_You should compile /less/user.less to generate a CSS file._ appears.

#### System information (as much as possible)

Database Version 	5.5.49-0ubuntu0.12.04.1
PHP Version 	5.6.23
Web Server 	Apache/2.2.22 (Ubuntu)
Joomla! Version 	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT 

#### Additional comments

Only a small notice.

**Comment by brianteeman** [comment]
I would say that it is the expected behaviour that EVERY time you save the less file you get a message that you need to compile it. How is Joomla to know if you have made a change or not. If you have not made a change then you would normally only close the file not save and close<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11201">issues.joomla.org/joomla-cms/11201</a>.</sub>

**Comment by conconnl** [comment]
I totally agree with Brian.
This is expected behavior for a Save & Close button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11201">issues.joomla.org/joomla-cms/11201</a>.</sub>

**Comment by brianteeman** [comment]
Close as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11201">issues.joomla.org/joomla-cms/11201</a>.</sub>
