### ISSUE TITLE
"Go to site home page" and "Preview" llinks do not add https

### ISSUE THREAD

**Issue by kenleegit** [joomla/joomla-cms#11213]
#### Steps to reproduce the issue
Install fresh 3.6.0.
Change apache to listen to higher port e.g. 63000 and configure the virtual host to use SSL.
Restart apache httpd.
I can access front and back ends by https://mysite:63000 and https://mysite:63000/administrator/index.php

#### Expected result
The "Go to site home page" on administrator login page should link to https://mysite:63000
After administrator login, the Preview link at top right corner should link to https://mysite:63000

#### Actual result
Both links are linked to http://mysite:63000 only.
(HTTP, rather than HTTPS)

#### System information (as much as possible)
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16
Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64

**Comment by andrepereiradasilva** [comment]
what do you have configured in "Force HTTPS"?

**Comment by jo-sf** [comment]
please take a look at PR #8619, this PR (or a newer version of it still to be developed - I'm sorry it's not yet complete) will hopefully handle this accordingly:

- configuration of HTTP and HTTPS ports
- switching between HTTP and HTTPS according to "Force HTTPS" setting and "usesecure" setting<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11213">issues.joomla.org/joomla-cms/11213</a>.</sub>

**Comment by kenleegit** [comment]
I am afraid it is nothing to do with Force HTTPS setting. Speaking of "Force HTTPS". I find 3.6.0 recognize only port 443 is valid HTTPS port. If my site other than 443, I could not event set "Force HTTPS" to other than "None". It gives me the misleading message:
_Warning
HTTPS has not been enabled as it is not available on this server.
Message
Configuration successfully saved._
And the setting falls back to "None".

I had an older Joomla 3.4.5 running on high port number and its "Go to site home page" and "Preview" links simply follow my current URL and my Force HTTPS there was simply None. I really want that feature back.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11213">issues.joomla.org/joomla-cms/11213</a>.</sub>

**Comment by jo-sf** [comment]
There was a change in 3.6.0 when you try to set "Force HTTPS" from None to anything else. The check implemented shall prevent you from locking out of your Joomla installation if you cannot connect to your server using HTTPS. You're right that currently HTTPS is only supported via port 443 but even that shall be changed by means of #8619 (two new fields holding the HTTP and the HTTPS port numbers you use, if empty the defaults - ports 80 and 443 - will be used).

But I tink that even before 3.6.0 it was tricky to set "Force HTTPS" to e.g. "Administrator Only" if you're using non-standard ports. After saving this setting and opening the next backend page Joomla automatically tried (and tries) to switch to HTTPS protocol unless you manually opened the backend via HTTPS. And with any HTTPS port other than 443 that would fail.

There was a change in 3.6.0 that causes all links from the backend to the frontend (preview links) to be converted to HTTP if "Force HTTPS" is not set to "Entire Site". But if you set "Force HTTPS" to "Entire Site" your preview links from the backend to the frontend should again work, even if you use a non-standard port. Yes I know you currently cannot change this setting via the global configuration since the HTTPS check fails but you might modify the configuration.php file directly (this is not the desired solution but only a workaround until you can configure the HTTP and HTTPS ports to use).

**Comment by brianteeman** [comment]
@kenleegit does the answer above solve your issue with using non-standard ports etc.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11213">issues.joomla.org/joomla-cms/11213</a>.</sub>

**Comment by kenleegit** [comment]
Dear @jo-sf,
Thank you for your advice. I got it working. I can live with that.

Dear @brianteeman,
Thank you for your follow-up.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11213">issues.joomla.org/joomla-cms/11213</a>.</sub>

**Comment by brianteeman** [comment]
Closing <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11213">issues.joomla.org/joomla-cms/11213</a>.</sub>
