### ISSUE TITLE
Display of new tooltips hidden

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11268]
If there is a long tooltip (popover) at the bottom of the screen then it cannot be read - possibly a z-index issue ?

![egtr](https://cloud.githubusercontent.com/assets/1296369/17078371/e63f2ba2-50f1-11e6-9d2f-a12b61e1d479.png)

**Comment by ggppdk** [comment]
At least z-index it can be fixed easily,
- because the pop-over is placed under body, thus is under the same parent as navbar

thus can gain more available screen, and improve this issue

the popover z-index (-es) are here:
https://github.com/joomla/joomla-cms/blob/staging/media/jui/less/variables.less#L144-L149

we could change them (adding +100 or +1000 to them),

isis and other templates have same variables in their variable.less,
but they are overriden by the media/jui/less/variables.less, because of the order of import

**Comment by brianteeman** [comment]
Closed as we have a PR #11276
