### ISSUE TITLE
Notice: Undefined offset: 1 in \libraries\joomla\database\query\sqlsrv.php

### ISSUE THREAD

**Issue by rudisten1** [joomla/joomla-cms#11279]
#### Steps to reproduce the issue
install joomla using a SQL Server db as the main database
go to "components - banners" in the administration site

#### Expected result
banners management console

#### Actual result
php notice error as follow:

Notice: Undefined offset: 1 in C:\inetpub\wwwroot\joomla7sqlsrv\libraries\joomla\database\query\sqlsrv.php on line 382

#### System information (as much as possible)
php 7
sqlsrv extension 4.0 non thread safe
IIS 7
joomla 3.6
SQL Server 2014

**Comment by williamsandy** [comment]
This is because the group function in the JDatabaseQuerySqlsrv class always assumes two things:

1. You always alias every table in your query
2. You always use the keyword 'AS' when you are doing a table alias.

In fact you don't necessary have to use the 'AS' keyword when defining alias [although this is good practice]  so this can lead to problems with the JDatabaseQuerySqlsrv group function which always assumes you do!

If you  are doing a group by on a single table you are not necessarily going to use a table alias and that is what the getCategoryOrders function does in the banners component, leading to the  PHP notice you are seeing in this issue.

**Comment by rudisten1** [comment]
Ok, but this is not my custom component. It's the default banner component. Should we expect this to be fixed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11279">issues.joomla.org/joomla-cms/11279</a>.</sub>

**Comment by pocketpc** [comment]
I have the same issue, you can mitigate by setting System>Global Configuration>Server>Error Reporting to None.

As for fixing, I might be able to get a pull request assembled at some point, but it's just a notice, so it's not particularly high priority.

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11938
