### ISSUE TITLE
Fatal error: Class 'stdclass' not found

### ISSUE THREAD

**Issue by rudisten1** [joomla/joomla-cms#11311]
#### Steps to reproduce the issue
use a different db driver (SQL Server) for a list view

#### Expected result
displaying the list view 

#### Actual result

Fatal error: Class 'stdclass' not found in C:\inetpub\wwwroot\joomla7mysql\libraries\joomla\database\driver\mysqli.php on line 886

#### System information (as much as possible)
php 7
 sqlsrv extension 4.0 non thread safe
 IIS 7
 joomla 3.6
 SQL Server 2014

#### Additional comments
the issue doesn't arise using php 5.6 instead of php 7

**Comment by mbabker** [comment]
I would suggest you've got a PHP issue then because `stdClass` is a part of the base PHP API and class names in PHP are case insensitive (only autoloaders seem to enforce a case sensitivity).

**Comment by rudisten1** [comment]
php issue only for newly php 7?

**Comment by brianteeman** [comment]
why is it even looking in the mysqli.php file if this is a sql server install

**Comment by rudisten1** [comment]
a complete mystery

**Comment by blakekidney** [comment]
I ran into the same issue. The problem is that 'stdclass' is being passed as a parameter to the mysqli_fetch_object() which is then causing an error because it should be 'stdClass' and not 'stdclass'. To fix the issue, I did added a line of code in the /libraries/joomla/database/driver/mysqli.php file on line 886 that corrects the issue. 

```php
protected function fetchObject($cursor = null, $class = 'stdClass')
{
   if($class = 'stdclass') $class = 'stdClass';
   return mysqli_fetch_object($cursor ? $cursor : $this->cursor, $class);
}
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11311">issues.joomla.org/tracker/joomla-cms/11311</a>.</sub>

**Comment by mbabker** [comment]
That really shouldn't be necessary.  Class names in PHP are case insensitive.  I honestly suspect there is some environmental issue at play here and that there isn't something that could be patched in core to fix.

**Comment by csthomas** [comment]
I can not replicate it.

1. On which version (full) of php the error occurs?
2. Which extension generate that error?
3. Can you replicate it in a simple script as below?
4. Does the error occur if you replace 'stclass' with '\stdclass'?

Example:
```php
// Load necessary libs
require 'console.php';

$db = JFactory::getDbo();

$db->setQuery('SELECT * FROM #__users');
$row = $db->loadObject('stdclass');

print_r($row);
```

**Comment by blakekidney** [comment]
We ran into some other issues. We thought these issues were related to PHP 7, so we moved back to PHP 5.6. We then setup the same site in a dev environment and could not replicate the issue. We then upgraded the site back to PHP 7 and all works well. The issue is not arising. I am not sure why. I wonder if something in the opcache was causing a conflict that stopped once cleared.

**Comment by brianteeman** [comment]
OK - closed

**Comment by blakekidney** [comment]
Unfortunately, this error surfaced again. This time, I used opcache_reset() to clear the opcache and the error was resolved. This would indicate the problem exists within the opcache.

**Comment by csthomas** [comment]
It may solve your problem #14137
