### ISSUE TITLE
Menu Item Alias doesn't put date in alias field Joomla 3.6

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#11372]
#### Steps to reproduce the issue
After update Joomla 3.6, when I make a Menu Item Alias 
Put in the name
Select the Menu item
Save
Get error 
Save failed with the following error: Another menu item has the same alias in Root (remember it may be a trashed item). Root is the top level parent.

#### Expected result
Should save and put a date in the Alias field like it did in 3.5.1
If I put in a date and then save, it will save properly

#### Actual result
Error Save failed with the following error: Another menu item has the same alias in Root (remember it may be a trashed item). Root is the top level parent.

#### System information (as much as possible)
Joomla 3.6
PHP 7.0.9 
Database Version  5.1.73 
Browser FireFox

**Comment by brianteeman** [comment]
This is not a bug it is a change made in 3.6 after user requests. See #10756

**Comment by brianteeman** [comment]
IIRC the problem with the date is if you have a submenu of an alias.

**Comment by visualtribe** [comment]
So if I have a menu alias with a date, and have a submenu of that alias with a date, it wouldn't work. Is that the issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11372">issues.joomla.org/joomla-cms/11372</a>.</sub>

**Comment by brianteeman** [comment]
The issue is that people didn't like URLs with meaningless dates

**Comment by bertmert** [comment]
@visualtribe 
See https://github.com/bertmert/plg_system_backtodatealias
Please read "How to install:" and restrictions. We hadn't time yet to release an install. package and things.

**Comment by visualtribe** [comment]
Thanks

**Comment by brianteeman** [comment]
I am closing this as expected behaviour 

(It is beyond me why someone would ever create an alias with the same name as another menu item on the exact same level)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11372">issues.joomla.org/joomla-cms/11372</a>.</sub>

**Comment by brianteeman** [comment]
The issue is this. Before 3.6 when you created a menu typw alias then it was always given an alias of the date. This was a problem when you had a submenu or breadcrumbs and this date was in the url. Now the alias is generated just as it would for any other menu item.

You cannot have two items with the same alias at the same level. Thats what the error message is saying (at least it is in english I hope the italian is not a bad translation).

If the menu type alias is not at the same level or does not have the same title then there is no problem

The only scenario that you will ever see that error message is if you are creating a menu alias to a menu item called Contact at the same level.

I cannot see why you would ever have two menu items with the same name at the same level

(Note this restriction applies to all menu items not just alias)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11372">issues.joomla.org/joomla-cms/11372</a>.</sub>

**Comment by bertmert** [comment]
> I cannot see why you would ever have two menu items with the same name at the same level

1) If you have a hidden menu that contains the basic structure of your real URLs (see it like a master) and then create menus that only use menu items of type Menu Alias pointing to the hidden menu then you now have too often the conflict described above while saving. I always build a hidden menu that displays the structure of "good URLs". Let's say "the allowed ones".

2) In menu selections (associtations) "you don't have to think". You see which menu named "Impressum" is the correct one and which one has to be checked (most people also check the alias or only the alias...).

**It depends on your personal workflow and the environment which behavior you prefer.** I prefer current date.

![01-08-_2016_11-24-32](https://cloud.githubusercontent.com/assets/11038612/17290112/1eab23c8-57dd-11e6-8aa3-4c4004dc99a7.jpg)

![01-08-_2016_11-38-42](https://cloud.githubusercontent.com/assets/11038612/17290116/230bc31e-57dd-11e6-8da3-45e92a43956a.jpg)

**Comment by helvecio** [comment]
I have two different menu items in my **Main Menu** that take the visitor to different contents. 
Both **must** have the same name
- Projects > **Central Bank**
- Restore > Architecture > **Central Bank**

I need to create two different menu modules with aliases to these items. Both look the same in each menu.

Menu 1: 
- Central Bank _linking to_ Projects > **Central Bank**

Menu 2: 
- Central Bank _linking to_ Restore > Architecture > **Central Bank**

Previously it would be able to save them with no hassle and would get the same URLs with the aliases:

- www.site.com/projects/central-bank.html
- www.site.com/restore/architecture/central-bank.html

Now, it seems Joomla cannot differentiate that I am pointing to different menu items, then it returns the error when I attempt to create the second alias because it sees two menu items with the same name on the same level. My only choice is to change the menu item alias, which is not what I want.

`Error Save failed with the following error: Another menu item has the same alias in Root (remember it may be a trashed item). Root is the top level parent.`

System aliases should be able to be created based on their source menu item, not where they are "physically".

**Comment by bertmert** [comment]
@helvecio 
You should open an new issue because yours is not related to this one and this one is closed already. Most people only read open issues.

**Comment by Bodge-IT** [comment]
@ghost Thanks for the plugin.  Any chance you could repost it?  I use the alias feature all the time.

The issue of adding submenus to aliases only applies to real menu items as sub items to an alias.  I often create new menus created soley with aliases to the core structure, when designing "simplified/bespoke menus" for use elsewhere in site.  When it is just aliases in the structure, the urls behave as they would when real menus being used...i.e. no dates present.

> (It is beyond me why someone would ever create an alias with the same name as another menu item on the exact same level)

@brianteeman 
One simple, useful requirement for this is when submenus are revealed by hovering rather than clicking.  I usually add an alias to the parent item so that it also appears in the submenu, otherwise the parent menu item is often ignored or missed.
Someone might suggest to use a "#" in the parent menu but then you don't get the same structural benefits of say a category view as the parent.

**Comment by brianteeman** [comment]
@Bodge-IT I dont understand how your comment is related to this issue of using real names instead of dates for a menu alias. 
Re my comment
> (It is beyond me why someone would ever create an alias with the same name as another menu item on the **_exact same level_**)

Note the highlighted phrase

**Comment by Bodge-IT** [comment]
@brianteeman Aha devil is always in the detail!

**Comment by guardsol** [comment]
I understand this issue is closed.  I understand the software no longer creates the datestamp as the URL.  But now, my menu alias pages are coming up as having duplicate metadescriptions.  For SEO purposes, how do I get around this?

**Comment by ghost** [comment]
@guardsol have you asked for help on the [forums](https://forum.joomla.org/)? This repository concerns in first Place Joomla-Core coding.

**Comment by guardsol** [comment]
I have not because I was researching this issue and it is related.  I will ask on the forums but my understanding based on an article by Cliff Pfeiffer is that the menu item alias using the date was specifically so you didn't end up with duplicate content.  Since that functionality was taken away, I am at a loss for how to handle this.
