### ISSUE TITLE
Keep getting from admin page Fatal Error:  Cannot redeclare ad1c8a0() 

### ISSUE THREAD

**Issue by gypsychiq** [joomla/joomla-cms#11392]
#### Steps to reproduce the issue

trying to get to any tab from admin page

#### Expected result
Sends me to articles

#### Actual result

get
 Fatal error: Cannot redeclare ad1c8a0() (previously declared in /home/rhondadonahue/public_html/layouts/joomla/toolbar/base.php:1) in /home/rhondadonahue/public_html/layouts/joomla/toolbar/base.php on line 1 

#### System information (as much as possible)
I haven't backed up my site 
and I updated all extensions (still need to update one) and Joomla is up to date 

#### Additional comments
Obviously I'm not very informed with most of this but if you explain to me with thorough instruction I can figure it out. Thanks!

**Comment by mbabker** [comment]
Unfortunately it would appear your site's files have been edited.  The
folks on the forum, http://forum.joomla.org can help you through this.

**Comment by ggppdk** [comment]
If you 
- extract the full joomla ZIP package into your site root ... and overwrite all files (and then you do the same thing for all 3rd party apps too)

Then it  **should fix** the issue ... **temporarily** ... maybe for minutes or for hours,
as there will be left-over "bad" files in your system

If it does 
- install some apps from here: http://extensions.joomla.org/tags/security-tools
- and change passwords

If you are on a self-managed server (you update server software your self), then issue may be because of old insecure PHP version or insecure server configuration, (if you do not have a self-managed server, then you do not need to care about this)

**Also you may ask your web-host to run some cleaning tools for free or for a fee**,
and then you update every 3rd party app ... in your web-site

In any case post here: http://forum.joomla.org
as this issue tracker is for different purposes

**Comment by jeckodevelopment** [comment]
Closing because that's not the right place to post help request.
As said, please submit a post in the Joomla! Forum: http://forum.joomla.org
