### ISSUE TITLE
Can not upgrade to J3.6.1 if FTP layer is active

### ISSUE THREAD

**Issue by jojo12** [joomla/joomla-cms#11432]
#### Steps to reproduce the issue
I repared the database

trying to update via joomla actualisation

So I am not able to update

#### Expected result
Should be updated

#### Actual result
via akeeba: I get "Unerwarteter HTTP-Statuscode 404"
via direct-hybrid and direct: I get:
0 Argument 3 passed to JClientFtp::getInstance() must be of the type array, null given, called in /srv/www/vhosts/mysite.ch/httpdocs/libraries/joomla/filesystem/file.php on line 488 

#### System information (as much as possible)

 
PHP erstellt für 	Linux server46.hostfactory.ch 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64
Datenbankversion 	5.5.5-10.0.25-MariaDB-0+deb8u1
Datenbankzeichensatz 	utf8_general_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	7.0.7
Webserver 	Apache
PHP-Interface für den Webserver 	fpm-fcgi
Joomla!-Version 	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by ggppdk** [comment]
This and 2 more cases
- were fixed in J3.6.1

See here:
https://github.com/joomla/joomla-cms/commit/b7b37ce9dfe5334cbf555836061dbcb206be95a5
https://github.com/joomla/joomla-cms/pull/11325

So you should be able to update from J3.6.1 to a later version
but it seems that you can not update with FTP active from J3.6.0 to J3.6.1  ?

Maybe apply the patches manually ?

**Comment by jojo12** [comment]
thanks, I changed the first one, now I get:
35 JFTP: :append: Unerwartete Antwort

**Comment by ggppdk** [comment]
Try getting new **Joomla Update Component**
(click in the description)
https://github.com/joomla/joomla-cms/releases/tag/3.6.1

**Comment by jojo12** [comment]
this I uploaded and installed before my problems

**Comment by ggppdk** [comment]
So you 
- need FTP layer to be active 
- and you have configured it properly ?

Can you change title of this thread to ?:

Can not upgrade to J3.6.1 if FTP layer is active

**Comment by brianteeman** [comment]
Edited title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11432">issues.joomla.org/joomla-cms/11432</a>.</sub>

**Comment by mbabker** [comment]
> Can not upgrade to J3.6.1 if FTP layer is active

There isn't anything that can be done at a code level without providing something installable via the extension manager.  The bug blocking this was fixed in 3.6.1, yes, but the only way to get there if you need to use the FTP layer would be to manual update or install a special package into the extension manager (assuming that's actually functional with the FTP layer enabled) with the needed revisions to make an update possible.

**Comment by brianteeman** [comment]
I am going to close this based on the comments above - nothing we can do <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11432">issues.joomla.org/joomla-cms/11432</a>.</sub>
