### ISSUE TITLE
database is up to date but upgrade joomla 3.6.1failure PHP 7.0

### ISSUE THREAD

**Issue by sindb1** [joomla/joomla-cms#11447]
Dear,

I follow this FIX:
**https://docs.joomla.org/J3.x:Update_fails_with_an_error_message**
_Go back to your administration panel example.com/administrator
Then go to Extensions  →  Manage  →  Database
You should see a message that the dababase is out of date
Click on the Fix button in the toolbar._
but I see Database table structure is up to date.

#### System information:
Joomla 3.6.0
PHP 7.0
Akeeba Backup Core 5.1.3

Is there a FIX for Database table structure who are up to date please ?

TIA

Regards,
Thierry

**Comment by ggppdk** [comment]
**You do not need to click fix if your DB shows: up-to-date**

About Akeeba Backup Core 5.1.3
- 5.1.4 was released, update it , before upgrading to J3.6.1, and you should not get any errors

But if during upgrade from J3.6.0 to J3.6.1 you an error message after file extraction progress finishes:

"The most recent request was denied because it contained an invalid security token. Please refresh the page and try again."

Then go to Extensions / Manage / database / Fix

**Comment by sindb1** [comment]
Thanks, the update of Akeeba 5.1.4 did succeeded the joomla update 3.6.1.

A database Fix wasn't needed.

:+1:
