### ISSUE TITLE
SQL Error after update 3.6.1

### ISSUE THREAD

**Issue by drwebbe** [joomla/joomla-cms#11448]
#### Steps to reproduce the issue
1. Updating from Joomla 3.6.0 to 3.6.1
2. Under Extensions->Manage->Database you can see 3 errors:
Warning: Database is not up to date!
- Table 'lfkex_menu' does not have index 'idx_client_id_parent_id_alias_language'. (From file 2.5.0-2011-12-24.sql.)
- Table 'lfkex_redirect_links' does not have index 'idx_old_url'. (From file 3.5.0-2016-03-01.sql.)
- The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).
3. Under 'Other information' :
- Database schema version (in #__schemas): 3.6.0-2016-06-05.
- Update version (in #__extensions): 3.6.1.
- Database driver: mysql.
- 94 database changes were checked successfully.
- 156 database changes did not alter table structure and were skipped.
4 . Click on 'Fix'

#### Expected result
Database updated

#### Actual result
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

#### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64
Database Version 	5.5.49-0+deb7u1-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.4.45-0+deb7u3
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.1 Stable [ Noether ] 2-August-2016 22:59 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

Relevant PHP Settings
Setting 	Value
Safe Mode 	Off
Open basedir 	None
Display Errors 	On
Short Open Tags 	On
File Uploads 	On
Magic Quotes 	Off
Register Globals 	Off
Output Buffering 	On
Session Save Path 	/var/lib/php5
Session Auto Start 	0
XML Enabled 	Yes
Zlib Enabled 	Yes
Native ZIP Enabled 	Yes
Disabled Functions 	None
Multibyte String (mbstring) Enabled 	Yes
Iconv Available 	Yes
Mcrypt Enabled 	Yes
Maximum Input Variables 	4000

**Comment by PhilETaylor** [comment]
How many rows do you have in the redirect links table

I bet 100% this is a time out on the adding of the index, and that you have millions of rows in the redirect links table.

**Comment by drwebbe** [comment]
Hi Phil,
There are only 4500 rows in the redirect links table.
I'll try out your suggestion this afternoon.
Is there a way to convert the tables to utf8mb4 through phpmyadmin ?

**Comment by PhilETaylor** [comment]
> Is there a way to convert the tables to utf8mb4 through phpmyadmin ?

Yes but you would not want to do it ;-) unless you have a few days of time on your hands... especially if the automated way of doing it is failing :) 

Just keep using the fix button and it will churn through until it errors part way or completes, in my (considerable) experience with this issue, this always works and gets to the end "eventually" 

Joomla "could" handle this better, but there is no point in making further changes to Joomla to split up the utf8mb4 upgrade into smaller chunks of sql because this is a one off change.

As this is also not a "bug" but more a "server timeout" this issue on github could be closed.

**Comment by RefreshMyMind** [comment]
After click on the link of update from my email, I got an error, a lof of tables were droped, and can't understand why! I got a lot of sql queries problems because tables aren't available.
example:

Error displaying the error page: Table 'xxx.#__template_styles' doesn't exist SQL=SELECT id, home, template, s.params FROM #__template_styles as s LEFT JOIN #__extensions as e ON e.element=s.template AND e.type='template' AND e.client_id=s.client_id WHERE s.client_id = 0 AND e.enabled = 1: Table 'xxx.#__usergroups' doesn't exist SQL=SELECT b.id FROM #__usergroups AS a LEFT JOIN #__usergroups AS b ON b.lft <= a.lft AND b.rgt >= a.rgt WHERE a.id = 1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11448">issues.joomla.org/joomla-cms/11448</a>.</sub>

**Comment by brianteeman** [comment]
Hi guys the best place for support questions is the forum http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11448">issues.joomla.org/joomla-cms/11448</a>.</sub>
