### ISSUE TITLE
Articles Not Showing Up Since 3.6.0 Upgrade, Still Broken Under 3.6.2

### ISSUE THREAD

**Issue by UsYrIllus** [joomla/joomla-cms#11536]
When an article is created or edited under 3.6, the article will not appear on the main page. Nor will it appear in the category filtered listing on the site. The only way to access the article is via a direct link.

#### Steps to reproduce the issue

Create Or Edit an article.

#### Expected result

Article to be displayed on main page, with the rest.

#### Actual result

Article does not appear.

**Comment by ggppdk** [comment]
what is "main page" ?

i will guess that your page is an article listing
e.g. featured articles

and you also have pagination OFF ?

Question do you order them by "ordering" property ?

- since J3.6.0 the new article is positioned last

In articles manager and in featured manager
- order by ordering column and check the position of the new article

you need to drag it to the top

**Comment by jolliemar** [comment]
Hi ggppdk,

I have encountered related issue to this, hope these details would help.

I have a Joomla v3.6.2.
I have set my home page to display featured articles only.
So in menu items, this is the layout settings:

Category Order: **No Order**
Article Order: **Featured Articles Order**
Date for Ordering: **Created**

Currently, this setting already displays the featured articles in descending order.

"Since J3.6.0 the new article is positioned last"
Does this also include the  ordering of featured articles?

**Comment by Sieger66** [comment]
This is a Issue see also:

https://issues.joomla.org/tracker/joomla-cms/11103

https://issues.joomla.org/tracker/joomla-cms/11200

https://issues.joomla.org/tracker/joomla-cms/11139<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11536">issues.joomla.org/joomla-cms/11536</a>.</sub>

**Comment by brianteeman** [comment]
As the issues referred to above how now been reverted to 3.6.3 I am going to close this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11536">issues.joomla.org/joomla-cms/11536</a>.</sub>

**Comment by UsYrIllus** [comment]
Hey! 


There is  something really  surprising I wanted to show  you, just take a look at it <http://gewaspecu.rbaharlaw.com/e7vdvgc>

Sincerely yours, usyr_illus
