### ISSUE TITLE
Automatic unattended update function needed for joomla

### ISSUE THREAD

**Issue by RichardEb** [joomla/joomla-cms#11937]
I'd like to have a function/extension that can automatically and unattended update/upgrade my joomla installation to the latest release. (and optional also the extensions that are auto update capable)

Here is a little FAQ to push the discussion a little bit forward:

Q: Why should this be usefull? There is already an update notification.
A: I'm a Web developer and I'm creating websites for customers. Many of my customers don't want to pay me for a service and update agreement. But they don't now much about computers so they also can't update on their own. So no one will do it and some weeks/months later they get hacked. This always a bad reputation for me and for joomla. (Yes I told them the risks if they don't pay me for service. But they forget the warnings as soon as I leave the room) I think the risk of getting hacked with an outdated page is higher then a malfunction of an update.

Q: People who don't update are lazzy
A: No. They just can't operate joomla and they also don't want too. This is not their business. They just want this working by themself. They also don't want to spent money for maintenance service. Anyway a hacked page is a bad reputation for me.

Q: This is to risky an update could fail.
A: Yes it can. But a normal update will also fail in this case. Related to #11931 there aren't big problems with minor updates so there is no need to check all extensions before every update. I think the risk of getting hacked with an outdated page is higher then a malfunction of an update. And you could also add a warning next to the option so everyone can decide by himself if he wants to take the risk. There was the same discussion with the popular AVM fritzbox router. AVM added an unattended  auto update function some months ago. I never heard about a single problem.
And in the worst case there should also be an backup of the page.

Q: No other CMS has this function
A: So why shouldn't joomla be innovative?

**Comment by brianteeman** [comment]
> Q: No other CMS has this function
A: So why shouldn't joomla be innovative?

Um wordpress

**Comment by RichardEb** [comment]
@brianteeman 

Maybe. I discussed this at the joomla forum and this was one of the arguments. So I wanted to place it here.

If worpress has this function it's one more argument to also have it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11937">issues.joomla.org/joomla-cms/11937</a>.</sub>

**Comment by mbabker** [comment]
1) Joomla core update handling needs to be rewritten.  Joomla core updates
are processed in the same manner as extensions.  This causes a lot of
issues IMO.  As an example we cannot distinguish between "security", "bug",
or "feature" related packages, or label if they fall under multiple
categories.  Instead of core updates reading an XML file and trying to
decide based on a version compare function's results if an update can be
applied (which means all features need to be in the core CMS and new
features can only be relied on at the version they are introduced), the
"phone home" update check needs to send the server specs (the same data
used in the stats collection plugin, there isn't a need for anything
additional here) and the user's update configuration (are you interested in
only current version (3.x) notifications, want to be prompted for 4.0 when
it happens, or if an automated system comes into play do you want only
security patches to auto apply or other release types) to a joomla.org
server and we run an application there that reads your data and gives back
the right update data.  This decouples the requirement that the core CMS
has all of the update logic self contained, if we need to add additional
checks it's done in the remote application and applies to all Joomla
releases reading from it.

2) Liability issues.  Implementing an unattended update system exposes the
project to new liabilities if an update crashes a site (one we pushed to
users versus something a user optionally installed) or heaven forbid the
Joomla hosting architecture were hacked.  There would need to be a lot of
legalese in place to protect our volunteers because at least in the lawsuit
happy USA people WILL come after us.

3) It won't happen overnight.  Drupal has been working on something similar
for close to two years, ref: https://www.drupal.org/node/2367319 and they
are still nowhere near a working solution.

4) Security of the whole system.  See the Drupal issue.  It's a lot more
than saying "hey, Joomla core has an update available, download it now".

**Comment by RichardEb** [comment]
> Joomla core update handling needs to be rewritten.  Joomla core updates
are processed in the same manner as extensions.  This causes a lot of
issues IMO. 

Sounds like the update-code has to be rewritten in the near future anyway. So this may be a good opportunity to also implement an auto updater.

> Liability issues.
This is really a big problem especially in the US. But maybe you can build the unattended updater as an opt-in with a disclaimer that has to be accepted before.

> 3/4)
I'm aware that this will be a hard piece of work and I don't expect it to be done within the next week. But maybe it's still worth the work and a good long term goal.

If drupal is also working on this problem maybe joomla and drupal can work together in this case. Especially the liability problems only have to be resolved once.

**Comment by RichardEb** [comment]
Many hosters offer free cronjob tasks and there are also external cronjob providers. So I could even live with this solution: To update joomla I only have to press the "update" button manually. Making it "clickable" by a cronjob, would also help me a bit. We only have  to consider the max 
php execution time. I'm not sure if cronjobs allow header redirects. I would guess no and most hosters don't allow to set the max php execution.

Note: This is just a quick and dirty solution. I more propery and better supported solution would be still nice.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11937">issues.joomla.org/joomla-cms/11937</a>.</sub>

**Comment by rdeutz** [comment]
You can do a lot today, we have build a script that "can" do the job under some circumstances. It is a proof of concept but if you like to life dangerously check this out: https://github.com/joomla-projects/cli-update/tree/develop

**Comment by RichardEb** [comment]
I will have a look. Thanks. A proof of concept is maybe a little bit to less for a solution and the long term goal should be an official Updater IMO. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11937">issues.joomla.org/joomla-cms/11937</a>.</sub>

**Comment by brianteeman** [comment]
You have to start somewhere

**Comment by RichardEb** [comment]
I don't say that having this is bad. It is indeed a good start. I only Wanted to say that it doesn't solve my Problem right now. ;)

**Comment by rdeutz** [comment]
It solves your problem, setup a cronjob calling the cli script and updates running without anything you have to do

**Comment by RichardEb** [comment]
As this is only a proof of concept it's a bit to risky to use it for customers right now. I'll do some tests and maybe it'll work so well that I'll deploy it to my customers or maybe it won't.

Anyway I'd like to have an official implemented update function in joomla. And I'm sure I'm not the only one who needs this feature.

**Comment by RichardEb** [comment]
Every important thing should be said but the issue is still in Discussion state. What should happen next?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11937">issues.joomla.org/joomla-cms/11937</a>.</sub>

**Comment by rdeutz** [comment]
This is something we will re-evaluate for 4.0
