### ISSUE TITLE
Duplicated user queries when user is loggeed (JSession?)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12107]
### Steps to reproduce the issue

Enable debug and system debug plugin.
Login in the frontend and check the Database queries in system debug plugin info.

![image](https://cloud.githubusercontent.com/assets/9630530/18669548/6fd4c0ec-7f33-11e6-9838-411644d4870c.png)

![image](https://cloud.githubusercontent.com/assets/9630530/18669563/85ed0f10-7f33-11e6-948a-ff5ab9a1fc74.png)

Call stack for both
![image](https://cloud.githubusercontent.com/assets/9630530/18669589/a1181cf8-7f33-11e6-9839-50c0ec388572.png)

### Expected result

Just two DB queries.

### Actual result

Four DB queries.

### System information (as much as possible)

Latest staging

### Additional comments

@mbabker i don't really know how joomla sessions work. is there a particular reason for this?

**Comment by mbabker** [comment]
If the call stack for the 31st and 32nd queries (which should be the end of the application cycle) is the exact same as the 3rd and 4th queries at the beginning of the application cycle, I'd say there are a lot of bigger issues here.  Instead of just raising a flag because the debug console says the queries are duplicated, you'll have to dig into the call stacks and figure out what's triggering the code on each side.  The first two are definitely because the user data is unserialized out of the session, but I haven't a clue what the last two are for.

**Comment by andrepereiradasilva** [comment]
> Instead of just raising a flag because the debug console says the queries are duplicated

😉 is a nice way to found issues
Hmm just making sure there wasn't some known session process or something. that's way i asked.

> you'll have to dig into the call stacks and figure out what's triggering the code on each side.

> The first two are definitely because the user data is unserialized out of the session, but I haven't a clue what the last two are for.

First ones:
![image](https://cloud.githubusercontent.com/assets/9630530/18670973/26cc2488-7f3a-11e6-911c-b4c097536575.png)

Last ones:
![image](https://cloud.githubusercontent.com/assets/9630530/18670980/2bc6c1a0-7f3a-11e6-9062-bdeea2d67833.png)

if i'm reading the call stack correctly it seems is the system debug plugin that does the two extra queries...

**Comment by mbabker** [comment]
Yep.  After the issues at the end of 3.4, `JSession` was changed so that when you request all data from the store it returns a clone of the internal data object (the Registry).  IIRC the unserialized `JUser` object is never directly stored back to the data object (or if it is it's through some wizardry of PHP) so the clone has a serialized version of the object that needs unserialized again.

**Comment by mbabker** [comment]
At the end of the day context is important.  I could have three modules all executing the same query:

```sql
SELECT * FROM jos_content WHERE id = 1;
```

The console would report duplicate queries but in context the only data source the modules are sharing is the database driver so it'd give a "valid" reason for the duplication.  If they were going through the article model there'd only be one query because the MVC layer has data caching in front of it.

**Comment by andrepereiradasilva** [comment]
ok i understand now. closing.
thanks again for your explanation.
