### ISSUE TITLE
Saving new Article on large category

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#12552]
### Steps to reproduce the issue

Creat an new article on a category with 1000s or more articles, first saving time takes about 10 sec. 
### Expected result

2-3 sec for saving an article. It was fixed on j3.6.1 (or 3.6.2, don't remember) but now it's back. 
### System information (as much as possible)

j3.6.4 php 5.x on NGINX server

**Comment by ggppdk** [comment]
This was discussed here: #10567 **Save new article (create a new ID) very slow in category with many articles**
- it is the performance of JTable::reorder()

A patch was made to use last ordering:  #8576 **Performance gain - new featured article** 
- that (partially) fixed the performance issue (it fixed it for new articles only, **but it did not fix in the general re-order case**)
- at the same time this was problematic , since users with many articles will have to manually move the new articles many positions to place them to the top

Then it was reverted here: #11581 **Revert "Performance gain - new featured article"**

The revert was supposed (?) to be made together with a performance fix like for example this one: #11184 **Reorder tables with single SQL query (all DBs compatible), greatly improving reorder performance** 
(other performance fixes (PRs) were proposed too) 

But only a revert was made in J3.6.3+ without adding any fix for JTable::reorder()

**Comment by franz-wohlkoenig** [comment]
@ch2856 ist this Issue solved?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12552">issues.joomla.org/tracker/joomla-cms/12552</a>.</sub>

**Comment by ch2856** [comment]
Nope, it's not solved yet. It takes about 30 second to save an article. I solved it with saving to other category and then save it again to the right one. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12552">issues.joomla.org/tracker/joomla-cms/12552</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
thanks for Info. Set Status "Needs Review" on Issue Tracker.

**Comment by mbabker** [comment]
@ch2856 Was your last test against the (at the time) 3.6.5 stable or 3.7 beta/RC releases?  Presumably this should have been addressed in 3.7.

**Comment by Quy** [comment]
@ch2856 Please advise if this is still an issue with the latest version.

**Comment by Quy** [comment]
@franz-wohlkoenig Close due to no response?

**Comment by ggppdk** [comment]
@Quy, i think close because it was fixed,
the reorder performance issue was fixed by @csthomas PR #13505

**Comment by Quy** [comment]
Closed as stated and no followup response by OP.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12552">issues.joomla.org/tracker/joomla-cms/12552</a>.</sub>
