### ISSUE TITLE
Sometimes Articles can´t be edited by clicking the link... (direct access not allowed)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#12581]
### Steps to reproduce the issue
It´s not easy to reproduce the issue as it happens on different sites, different environments and different articles. Sometimes when i click on a title of an Article (I´m Super Admin) the error message appears that the direct access is not allowed.

![image](https://cloud.githubusercontent.com/assets/828371/19734897/ac2f73a6-9ba9-11e6-8ddd-0524a4fdc129.png)

So at first sight there seems to be an permission issue, but not. Because if i click the checkbox in front of the Article and click on the Edit button the article opens as expected.

I think @rdeutz you also spoke about this issue before?

### System information (as much as possible)
Joomla 3.6.4

**Comment by ggppdk** [comment]
It is "race" condition, between 2 or more updates of the session data

> So at first sight there seems to be an permission issue, but not. 

Exactly it is not the ACL permission is calculated correctly, but the calculation is lost by another operation that tries to save the array with editable article IDs (or tries to save other session data ?)

An easy way to reproduce this,
- is to go to articles manager and quickly middle click (=open in new TAB) on about 20 article edit links, and you will see that several of them will fail

There has been many reports about this, and discussed has been very extensively,
it is minor, 
only becomes a big problem when it is persistent due to a website trying to use browser caching

you can read more here: https://github.com/joomla/joomla-cms/pull/10753

**Comment by PhilETaylor** [comment]
@brianteeman please close this - duplicate of many

**Comment by coolcat-creations** [comment]
closing didnt know it was already reported thanks
