### ISSUE TITLE
Installation is not adding media version in js

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12711]
### Steps to reproduce the issue

Go to `/installation/index.php?view=languages`
Check source code.

### Expected result

All js files with media version.
example:
```html
<script src="/media/jui/js/jquery.min.js?345kjh345j3h4k34h5k35k34"></script>
```

### Actual result

```html
<script src="/media/jui/js/jquery.min.js?"></script>
<script src="/media/jui/js/jquery-noconflict.js?"></script>
<script src="/media/jui/js/jquery-migrate.min.js?"></script>
<script src="/media/jui/js/bootstrap.min.js?"></script>
<script src="/media/jui/js/chosen.jquery.min.js?"></script>
<script src="/media/system/js/core.js?"></script>
<!--[if lt IE 9]><script src="/media/system/js/polyfill.event.js"></script><![endif]-->
<script src="/media/system/js/keepalive.js?"></script>
<script src="/media/system/js/punycode.js?"></script>
<script src="/media/system/js/validate.js?"></script>
<script src="/installation/template/js/installation.js?"></script>
```

### System information (as much as possible)

Latest staging

### Additional comments

Happens in all installation pages.
It seems installation app does not have media version? @mbabker any clue?

**Comment by mbabker** [comment]
The install web app uses its own code to load in the JDocument instance because there isn't exactly a parameter that can be loaded from the database like the default behavior does in the install app.

Default uses come from [JFactory::createDocument()](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/factory.php#L740-L759) while the install app builds it with [InstallationApplicationWeb::loadDocument()](https://github.com/joomla/joomla-cms/blob/staging/installation/application/web.php#L463-L488) and injects into `JFactory::$document`

**Comment by andrepereiradasilva** [comment]
hum ... so install cannot use media version ... ?

**Comment by mbabker** [comment]
It can if you can come up with a way to give it a value that changes appropriately, then you just set the `mediaversion` attribute in the array that's passed into the `JDocument` factory.  For production releases, `md5_file(JPATH_LIBRARIES . '/cms/version/version.php');` would be enough, but since the version file doesn't change during development until explicit version bumps are made, it's not so simple in between.

**Comment by andrepereiradasilva** [comment]
ok will check what can be done, anyway we shouldn't also allow an empty media version, so i will fix that too.

**Comment by brianteeman** [comment]
For install how about a string that is equal to today. ?02112017

Nice and simple and should solve any issues. It does not need to be version
specific

**Comment by andrepereiradasilva** [comment]
Good idea! Thinking outside the box Brian!. Maybe with your and minutes since install shouldnt take more than 1 minute anyway

**Comment by brianteeman** [comment]
Kiss always wins

**Comment by andrepereiradasilva** [comment]
solve by https://github.com/joomla/joomla-cms/pull/12713

quick test, please test
