### ISSUE TITLE
[com_fields]Gallery dropdown folder path is not relative

### ISSUE THREAD

**Issue by vishalCTUK** [joomla/joomla-cms#12866]
### Steps to reproduce the issue
Created a Custom field > Gallery and the default folder is '/images/projects' and added 2 folders to load from the article to chose from which are inside projects.

### Expected result

/laine
/ctuk

### Actual result

**Drop down values:**
C:\BitNami\wampstack-7.0.12-0\apache2\htdocs\joomla\dev\37\images\projects\/ctuk
C:\BitNami\wampstack-7.0.12-0\apache2\htdocs\joomla\dev\37\images\projects\/laine

**Front end error on page :**
JFolder: :files: Path is not a folder. Path: C:\BitNami\wampstack-7.0.12-0\apache2\htdocs\joomla\dev\37\images\projects\C:\BitNami\wampstack-7.0.12-0\apache2\htdocs\joomla\dev\37\images\projects\laine

### System information (as much as possible)
Local install on BitNami
Apache 2.
PHP Version	7.0.12
MySQL	5.5.40
Joomla! 3.7.0-dev
### Additional comments

The path should be relative to the root of the installation

**Comment by ggppdk** [comment]
This bug is in windows server specific, broken in both
-- the form element , and when displaying the field

It is fixed by this PR:  #12844 **[custom fields] Fix gallery field in windows installations** 
Please test

**Comment by vishalCTUK** [comment]
Thank you. I have changes updated the galley files and all works on that side. 
Does the same thing apply to the image custom field as I've selected the folder and on my article its an empty drop down?

Regards

**Comment by ggppdk** [comment]
So you tested, the PR #12844 that fixes **gallery field** in **windows**,
- Please visit this URL: https://issues.joomla.org/tracker/joomla-cms/12844

Near the top left, there is a button "Test this", 
Click it and the select "Tested successfully" and the "Submit test result"

----

About the **custom image field** being broken in **windows**
- it needs "**folderlist**" form element to be fixed in windows,

There is already a good PR for this here: https://github.com/joomla/joomla-cms/pull/11288
**folderlist form field returning full paths on Windows (issue 11102)**

**Comment by brianteeman** [comment]
I am closing this as a duplicate report as it is being handled elsewhere as referenced above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12866">issues.joomla.org/tracker/joomla-cms/12866</a>.</sub>
