### ISSUE TITLE
[com_fields] Global Options show global

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#13062]
com fields has one field defined in the plugin which in the field has a Show global value but we dont have the ability to show what the global value is as we do with othr fields now

![screen shot 2016-12-02 at 11 22 21](https://issues.joomla.org/uploads/1/4842a9ee8a2975e9e9883b854f57ab79.png)

**Comment by Bakual** [comment]
Yep, I saw that as well. That's because the parameter is specified in the plugin and not the component.
One solution would be to move the parameter to the component instead of the plugin. Another would be to make the field a custom extension specific field where we then can adjust the global lookup to fetch the plugin parameters.

**Comment by tonypartridge** [comment]
so @Bakual does that mean you propose to have a config option on each component since com_fields doesn't have a component config area? 

I actually think it should have it's own area, and you should be able to manage all other fields from all components in here.

**Comment by Bakual** [comment]
I just said the two ways I see to add that lookup. Actually I think the parameter makes sense in the plugin, since the plugin will do the rendering mostly. Though not sure if users will find the parameter there :)

**If** we add a config to com_fields, then I think it should also have its own menu item and not just be accessible by the links from the sidebar.

> you should be able to manage all other fields from all components in here.

I originally had this in my PR but it didn't get a lot of support because it was more confusing than helping.

**Comment by laoneo** [comment]
Keep in mind that it would be possible to have multiple contextes in a component where the setting can be inherited from. So for me the right place in com_content would be the article options.

Why is it in the system plugin right now? Answer is, this is a historical setting from DPFields which was not migrated properly.

**Comment by brianteeman** [comment]
(Note I do not see this as a major issue)

**Comment by brianteeman** [comment]
So long and farewell
