### ISSUE TITLE
hhvm tests take more than double time of php tests.

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#13168]
### Steps to reproduce the issue

Check any travis build. hhvm tests are significally slower than php tests.

At 77% of unit tests it takes a long time (something is strange here).
This is then reflected in hhvm total test time
![image](https://cloud.githubusercontent.com/assets/9630530/21080008/d1fa9bd6-bf9b-11e6-9cf3-35fd8a79558b.png)

Example: https://travis-ci.org/joomla/joomla-cms

### Expected result

hhvm tests takes more or less the same time as php unit tests

### Actual result

More than double time.

### System information (as much as possible)

N/A

### Additional comments

N/A

**Comment by photodude** [comment]
There are 2 factors in the total time for the HHVM tests
1. HHVM is running on the slower sudo required infrastructure not much we can do until after 1Q17 when the Trusty container comes out of beta (the Trusty beta container is currently broken due to a few  mysql socket issues)
2. Some of the tests run slow on HHVM. This could be an issue with the tests, PHPunit, HHVM, or even with Joomla's code.

You can use --debug to see what tests are running at the moment things slow down (unfortunately it's spending about 5 minutes watching the tests then trying to write down which ones are slow)

**Comment by csthomas** [comment]
I have prepared a PR #13169.

@photodude If you are interest in speed up unit tests take a look at #11872.

**Comment by andrepereiradasilva** [comment]
clesed as we have a PR to test
