### ISSUE TITLE
security vulnerability 3.6.4

### ISSUE THREAD

**Issue by road2one** [joomla/joomla-cms#13178]
### Steps to reproduce the issue
security vulnerability 

The file scanning mechanism of JFilterInput::isFileSafe() in Joomla! CMS does not consider alternative PHP file extensions when checking uploaded files for PHP content, which enables a user to upload and execute files with the `.php6`, `.php7`, `.phtml`, and `.phpt` extensions. Additionally, JHelperMedia::canUpload() did not blacklist these file extensions as uploadable file types.

**Comment by road2one** [comment]
Did you updated the cms to take care of the vulnerability. 
Pedro Yadaicela
917-977-0935

**Comment by Bakual** [comment]
See the CVE report: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-9836

**Comment by ggppdk** [comment]
This particular one , is 2nd in the list security issues fixed list, and is of "low severity", see here:

https://www.joomla.org/announcements/release-news/5693-joomla-3-6-5-released.html

"low severity", due to the fact that media manager, and other extensions are also using "allowed" file extensions to check which files are allowed to be uploaded, see my answer here
https://forum.joomla.org/viewtopic.php?f=714&t=941908#p3449503
