### ISSUE TITLE
joomla notification didn't come

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#13203]
### Steps to reproduce the issue
Check your inbox and see the email from your site that needs update.

### Expected result
Email should have come

### Actual result
Email didn't come until i updated 3 hours ago.

### System information (as much as possible)
joomla 3.6.4
Apache/2.4.7 
php:	5.5.9-1ubuntu4.20
Database Version	5.5.53-0ubuntu0.14.04.1

### Additional comments

It was working at previous updates.
I 'm not sure about he exact time the update came out to count the hours that have passed and if others have recieved the email feel free to close this issue. Just thought to report it cause i found it weird that i learned about the update cause i visited joomla github :)

**Comment by zero-24** [comment]
> Email didn't come until i updated 3 hours ago.

The default cache time in com_joomlaupdate is 6h can you double check that?

**Comment by peteruoi** [comment]
Sorry i guess my title was misleading. I mean the plugin for update notification the sends email didn't worked (System - Joomla! Update Notification)
I didn't find any option there for cache time neither in com-joomla-update options.
Anyway if all the others took the email then it must be something i did wrong. Dont pay attention and close it if all the other tok the email :)

**Comment by hacki65** [comment]
I can confirm that. No notification per email for 3.6.5. But it seems to be that this function never had always working. We have 10+ Websites running with Joomla! and sometimes it comes an email, sometimes not.

**Comment by mbabker** [comment]
The plugin isn't 100% reliable.

First, update caching.  This parameter is defined in your extension manager (this cache does affect Joomla update checking because it rides on the same system, just displayed in another area).  By default this is set to six hours, but IIRC the UI allows for up to 24 hours.

Second, the plugin is actually only triggered on visits to your site.  If you've got a low traffic site, you may not get visits often enough for the plugin to actually be triggered.

Then it comes down to the mail system.  Are the user accounts all configured with valid addresses and the site able to send email?  Because if this process breaks you'll never get the notification either.

Beyond that, you'd need individual support to troubleshoot site specific issues.

**Comment by peteruoi** [comment]
thanks mbabker for your time.
I was aware of this sequence and the update email notification had been coming. I first visited www.examplesite.com and then examplesite.com/administrator so i should have trigerred it.
If anybody has recieved such a email then this is my personal problem and i 'll find it so you can close this :)

**Comment by franz-wohlkoenig** [comment]
@peteruoi as this is no Issue more for you can you please close?
