### ISSUE TITLE
[3.7] Help buttons linking to runtime error

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#13237]
### Steps to reproduce the issue

All help buttons (article manager etc.)..

![help](https://cloud.githubusercontent.com/assets/2803503/21245944/7d3b81ca-c31d-11e6-921d-e535c456fc5d.png)

**Comment by mbabker** [comment]
If running from staging or the 4.0 branch, this would be expected behavior.

As an example, com_content categories will resolve a URL similar to https://help.joomla.org/proxy?option=com_help&keyref=Help37:Components_Content_Categories which points to https://docs.joomla.org/Help37:Components_Content_Categories (replace Help37 with Help40 if referring to the 4.0 branch).

A `Help40` or `Help37` namespace hasn't been established yet on the docs wiki, so the help pages do not exist.  When the docs namespaces are established and the content set up it will all be fine.

**Comment by ciar4n** [comment]
Ah ok.. only after submitting did it dawn on me that it could be something like that. Thank you for clarifying!
