### ISSUE TITLE
[com_fields] 0 Invalid controller: name='article', format='' 

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13267]
### Steps to reproduce the issue
With current staging I added two field groups with a text field assigned to each group. I also added a  category that I assigned to both fields.

Then I added an article and assigned it the newly created category. That went fine but when I added another article with the newly created category I got this error:

0 Invalid controller: name='article', format='' 

Tested with mysql.

**Comment by Bakual** [comment]
Can you tell us what URL you had in the browser when that error occured? Sounds unrelated to fields to me because com_fields doesn't deal with URLs but this error comes from a wrong URL.

**Comment by waader** [comment]
Today I tried to reproduce the error which proved to be not an easy task. Finally I succeeded. When adding an article I selected a category and I had to hit immediatly the "Save & Close" Button afterwards. Now the error is thrown. And the URL is ...

http://xyz/joomla37/administrator/index.php?return=aHR0cDovL2xvY2FsaG9zdC9qb29tbGEzNy9hZG1pbmlzdHJhdG9yL2luZGV4LnBocD9vcHRpb249Y29tX2NvbnRlbnQmdmlldz1hcnRpY2xlJmxheW91dD1lZGl0&option=com_fields&task=field.storeform&context=com_content.article&formcontrol=jform

**Comment by Bakual** [comment]
Ah, if you select a category, I think com_field does a reload because the available fields may have changed. You interefered with that reload and got stuck between chair and table.
@laoneo Do you think that is correct?
We could maybe add the "loading spinner" so it is apparent that something is happening?

**Comment by laoneo** [comment]
Yes it is correct, when you hit the save button before the page got reloaded, then you can land it that error.

**Comment by tonypartridge** [comment]
I Suggest we disable save button on category change and enable on category change finished?

**Comment by ggppdk** [comment]
> I Suggest we disable save button on category change and enable on category change finished?

About disabling save, or hidding the toolbar agreed it is an option
but there is no "category change finished", 

because **the form submits** 
and a new page is loaded by the browser, old page is gone

It appears as if the page remains the same, but actually it is a new page a new form that loads the values that had been entered by the user

----

Solution, just hide the outer form container and append a div under body with a loading message
then continue with the form submission

Or just add an grayed overlay over the form with a centered loading message

![loading_please_wait](https://cloud.githubusercontent.com/assets/5092940/21401891/af4e85e0-c7be-11e6-8322-f49f7383d3db.png)

**Comment by tonypartridge** [comment]
Clearly in had not tested it fully, in which case we should prompt a
loading screen in a modal with a grey out background it will be cleared on
the new page load

**Comment by laoneo** [comment]
Can we add a UX label here that they can come up with a proper solution?

**Comment by ggppdk** [comment]
I have made a PR please click on it to see the picture and comment on it

e.g. 
comment about 
-- place to add styles, or tell me if an overlay class already exists in Joomla
-- better message text

**Comment by zero-24** [comment]
Closing as we have Code to comment on. Thanks!
