### ISSUE TITLE
Some errors in the new plugin Editor - TinyMCE

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#13344]
1) In “**Editor - TinyMCE**” plugin initially appears the editor's interface from which you can drag and drop the buttons in the respective TAB to customize it. his vision is confusing. It could be better to put this example interface under a parameter  "View customization interface (drag & drop)" and make sure that it appears only when the user/administrator wants to customize the editor interface. #13367 
![hide it](http://www.alexred.com/joomla/img-issues/da%20togliere.png "hide it")

2) In **Advanced** options there are the parameters HTML Height and **HTML Width** with default px values, but only the height is taken into account, the width adapts automatically. The tooltip of the width parameter still refers to the old editor types (Advanced and Extended mode).

3) **Multilanguage** (the language of editor’s buttons) no longer works after you save for the first time the editor plugin settings. After saving the setting the language of the editor is English. https://github.com/joomla/joomla-cms/issues/13343  and #13366  #13368 [**Merged**]

4) Opening the "Editor - TinyMCE" plugin, the first **TAB** on the left side opens by default and it groups all the settings below (which is not clear). But the first TAB has no effect on the editor settings used by the super user, which is likely to make changes that will not find using the editor.
Only the last hidden TAB Set on the right side has effects for the user Super User. 
If the first TAB Set  is also set to **Access → Super User** it has no effect, but it continues to have effect the last TAB Set 0 on the right with **Access → Special**.

5) It should not be possible to set new or other existing TAB with the same type of **Access level**. #13387

6) In Joomla 3.6.5 and lower the various types of editor were: **Simple**, **Advanced**, **Extended**. Now they seem to be **Simple**, **Medium**, **Extended**. Perhaps it is better to avoid confusion calling the Medium → Advanced as before.

7) The tooltip of the “**Images Directory**”  parameter does not explain that you need only to indicate the name of the folder. This will be automatically generated by the system on the first dragging of an image. The folder will be created as a subfolder of the one set in the media manager settings as “**Path to Files Folder**”.
Since they are image files, I think it would be better to set that it is created as a subfolder of the one set in the media manager settings as “**Path to Images Folder**”.

8) If in version 3.6.5 or lower I set the TinyMCE editor in "**Simple**" mode then upgrading to Joomla 3.7.0 I find the editor in **Extended** mode and all plugin settings are lost and reset to new default value (Mobile Mode, Images Drag & Drop, Text Direction, Custom CSS Classes, New Lines, Use Joomla Text Filter, ecc..). (breaking backward compatibility ?)  #13387

9) I suggest to turn on a Set for the Super User access and by default activate also the "**Advanced Image**" parameter to ensure that at least  the administrator is able to insert the margins of the images. And also enable the parameter "**Use Joomla Text Filter**" so that the administrator can freely insert script in contents.

10) Installing a Joomla 3.7.0 in the **database** remained the default settings of the old editor management, these are then overwritten at the first save of the editor plugin settings. #13387

11) There are two parameters with the same identical name: **Access**
One in the right column for the classic plugin “Access Levels” and one under the Set TAB to select the Access Levels to be assigned to each Set TAB. I suggest to rename the second in: “**Access Level for this Set of options**” ...or something similar, to explain that all of the options below are associated to this single Set with the appropriate access level. #13367

![double access](http://www.alexred.com/joomla/img-issues/double-access.png "double access")

12) Context menus are messed up

**Comment by infograf768** [comment]
See also
https://github.com/joomla/joomla-cms/issues/13343

**Comment by AlexRed** [comment]
For point 3 see: https://github.com/joomla/joomla-cms/issues/13343<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13344">issues.joomla.org/tracker/joomla-cms/13344</a>.</sub>

**Comment by jeckodevelopment** [comment]
Sorry, closed by error.

@cpfeifer can you please look at the UX aspects of this?

**Comment by dgt41** [comment]
@AlexRed can you add one more point in the description: context menus are messed up

**Comment by alkarana** [comment]
have you fixed the error[](http://breakingnewstoday.in/natural-red-lips/ "") till now?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13344">issues.joomla.org/tracker/joomla-cms/13344</a>.</sub>

**Comment by cpfeifer** [comment]
I'm just seeing this for the first time and I agree it is confusing. I wasn't entirely sure what was going on until I fiddled around with it for a few minutes. 

I agree the editor drag & drop interface / preset builder needs to be separated in some way, maybe a "Configure Editor Layout" tab or something like that. 

I'm not entirely sure why the toolbar needs to be seen twice, that really threw me off. There could be a "default" tab in with the presets display, then it only needs to appear once, and the tab labels don't provide much direction. Something like "Preset 1" is much more descriptive. 

And I'm also not sure we need all of these options to be selectable via presets, I doubt any of my front end editing clients will ever need to adjust Entity Encoding settings for example. I'd say a handful of the design options should be included, but most of them should remain global.

Aside from the technical issues, I also agree there needs to be consistency from 3.6 and BW compatibility could be an issue. I'd keep the simple, advanced, extended terminology as is.

I'm seeing this for the first time and my first impression is it's more confusing than before. I appreciate the thought put into making the editor interface more flexible, but it will all get lost if no one understands how to use it quickly. I'll dig through the code a bit more and see what I can come up with over the weekend. Happy holidays :)

**Comment by Fedik** [comment]
I feel like I need to answer something, also 😄 

1. Nope. It is **NOT example**, it should NOT be hidden. It is a **list of available buttons**. But YES, would be more helpful to add some Label over that pane, something like *"Here is the list of available editor buttons. You can drag&drop them to build your own custom panel"*. Or even more detailed description, that would be even better. It is an easy change, anyone can do that 😉 

2. It is old behavior, I cannot comment here.

3. Please test the fix #13366

4. It made with purpose. Check that comment [11926#issuecomment-246171868](https://github.com/joomla/joomla-cms/pull/11926#issuecomment-246171868) . It is bad if all your users are superusers 😄  

5. I agree, but it hard to implement.

6. I am not sure. For me "Simple, Advanced, Extended" always was confusing. And "Simple, Medium, Extended" more clear, like 1, 2, 3.

7. It is old behavior, I cannot comment here.

8. Yes it is BC break, but not critical for me.  I have noted it in #11926. There no easy way to make FULL migration. 

9. Feel free to make the pull request :wink:

10. Yes, but I think it is not a problem, because see point (8). 

11. For me it is fine as it is. 

12. This is unclear what did you meant. Can you explain more?

**Comment by AlexRed** [comment]
1. add some Label is important also for me
2. where we can comment the old behavior?
3. test ok for me
4. then set by default only one set to Access → Super User 
5. :(
7. where we can comment the old behavior?
8. this BC break is critical for me because delete all the previous settings by the user, like also Text Filter. To solve it I suggest to not overwrite the actual tinymce plugin but make a new tinymce editor plugin (TinyMCE2 or TinyMCEb or TinyMCEa ecc..) and set it default in the new installation but in the upgrade the user can continue to use the old with all the setting ok.
9. can you help me to do the PR ? Please contact me on Glip
11. two parameters with the same identical name is a problem for me. In the documentation is a problem, to help user in the forum is a problem ecc...
12. Please @dgt41 Can you explain more?

**Comment by Fedik** [comment]
> where we can comment the old behavior?

I just meant, that I have no idea why it was made like that, so I cannot make comment on these points 😉

**Comment by Fedik** [comment]
for point 1, please see #13367

**Comment by ggppdk** [comment]
@  everybody
Please scroll below to see a screen that i think it is more easy to understand and configure (please notice the border / padding on the TABs ... and the text ... i kept it to minimal)

@Fedik 
About keeping tinyMCE setting of previous Joomla versions,
what about (if it is not too much work ...)

1. A tab "**Default layout**" (=default set) to load the old configuration
2. And the **Custom layouts** (=sets) are assigned by default to **access "none"**

**Thus they are not activated / used**, even if user clicks save,
that is unless user ACTIVELY sets an access level** after understanding that something will be effected

This way the **"default layout**  (=old configuration) is **both**
- continues to be used without discarding configuration of existing sites
- and also acts as a **fallback** for access levels that do not have a custom layout assigned to them yet

![customize_tinymce](https://cloud.githubusercontent.com/assets/5092940/21473012/b14009ae-cafd-11e6-8a70-c2a916dd55eb.png)

**Comment by Fedik** [comment]
> what about (if it is not too much work ...)

It huge amount of work 😉 
Very hard to make migration of the old toolbar (with all that fancy access check) to new.
But some options can be migrated, like the image path, skin and so on.
This need to think, maybe I do some PR later, but cannot promise much.

About the panels label/description please see #13367.

**Comment by infograf768** [comment]
see https://github.com/joomla/joomla-cms/pull/13367 concerning some changes in this new feature which i think are necessary: b/c and sets used depending on user groups and not access levels.

**Comment by Fedik** [comment]
for BC and access fix please test #13387

**Comment by Fedik** [comment]
**5,8,10** fixed in #13387

**Comment by AlexRed** [comment]
After the merge: 
- The warning message: "The TinyMCE Editor Plugin has been updated. At the moment, it uses your legacy configuration. By editing the plugin, you can now assign various layouts to specific user groups." is visible also in the new installation, i think this message is only for the upgrade.

- If I add a new Set and save it is another "public" access and after "save & close" and re-edit the plugin lost the formatting and the "advanced" TAB.

- for me "Set 0" (Super user) need to be the first TAB (to avoid confusion)

- where can I edit the default "Set 0" setting? I like by default activate also the "Advanced Image" parameter to ensure that at least the administrator is able to insert the margins of the images. And also enable the parameter "Use Joomla Text Filter" so that the administrator can freely insert script in contents.

**Comment by infograf768** [comment]
> The warning message: "The TinyMCE Editor Plugin has been updated. At the moment, it uses your legacy configuration. By editing the plugin, you can now assign various layouts to specific user groups." is visible also in the new installation, i think this message is only for the upgrade.

I confirm. The issue comes from the fact that some TinyMCE legacy parameters are set in joomla.sql

`(412, 0, 'plg_editors_tinymce', 'plugin', 'tinymce', 'editors', 0, 1, 1, 0, '', '{"mode":"1","skin":"0","mobile":"0","entity_encoding":"raw","lang_mode":"1","text_direction":"ltr","content_css":"1","content_css_custom":"","relative_urls":"1","newlines":"0","invalid_elements":"script,applet,iframe","extended_elements":"","html_height":"550","html_width":"750","resizing":"1","element_path":"1","fonts":"1","paste":"1","searchreplace":"1","insertdate":"1","colors":"1","table":"1","smilies":"1","hr":"1","link":"1","media":"1","print":"1","directionality":"1","fullscreen":"1","alignment":"1","visualchars":"1","visualblocks":"1","nonbreaking":"1","template":"1","blockquote":"1","wordcount":"1","advlist":"1","autosave":"1","contextmenu":"1","inlinepopups":"1","custom_plugin":"","custom_button":""}', '', '', 0, '0000-00-00 00:00:00', 3, 0),` 

we just need to update the various joomla.sql with the default params.
`{"configuration":{"toolbars":{"2":{"toolbar1":["bold","underline","strikethrough","|","undo","redo","|","bullist","numlist","|","pastetext"]},"1":{"menu":["edit","insert","view","format","table","tools"],"toolbar1":["bold","italic","underline","strikethrough","|","alignleft","aligncenter","alignright","alignjustify","|","formatselect","|","bullist","numlist","|","outdent","indent","|","undo","redo","|","link","unlink","anchor","code","|","hr","table","|","subscript","superscript","|","charmap","pastetext","preview"]},"0":{"menu":["edit","insert","view","format","table","tools"],"toolbar1":["bold","italic","underline","strikethrough","|","alignleft","aligncenter","alignright","alignjustify","|","styleselect","|","formatselect","fontselect","fontsizeselect","|","searchreplace","|","bullist","numlist","|","outdent","indent","|","undo","redo","|","link","unlink","anchor","image","|","code","|","forecolor","backcolor","|","fullscreen","|","table","|","subscript","superscript","|","charmap","emoticons","media","hr","ltr","rtl","|","cut","copy","paste","pastetext","|","visualchars","visualblocks","nonbreaking","blockquote","template","|","print","preview","codesample","insertdatetime","removeformat"]}},"setoptions":{"2":{"access":["1"],"skin":"0","skin_admin":"0","mobile":"0","drag_drop":"1","path":"","entity_encoding":"raw","lang_mode":"1","text_direction":"ltr","content_css":"1","content_css_custom":"","relative_urls":"1","newlines":"0","use_config_textfilters":"0","invalid_elements":"script,applet,iframe","valid_elements":"","extended_elements":"","resizing":"1","resize_horizontal":"1","element_path":"1","wordcount":"1","image_advtab":"0","advlist":"1","autosave":"1","contextmenu":"1","custom_plugin":"","custom_button":""},"1":{"access":["6","2"],"skin":"0","skin_admin":"0","mobile":"0","drag_drop":"1","path":"","entity_encoding":"raw","lang_mode":"1","text_direction":"ltr","content_css":"1","content_css_custom":"","relative_urls":"1","newlines":"0","use_config_textfilters":"0","invalid_elements":"script,applet,iframe","valid_elements":"","extended_elements":"","resizing":"1","resize_horizontal":"1","element_path":"1","wordcount":"1","image_advtab":"0","advlist":"1","autosave":"1","contextmenu":"1","custom_plugin":"","custom_button":""},"0":{"access":["7","4","8"],"skin":"0","skin_admin":"0","mobile":"0","drag_drop":"1","path":"","entity_encoding":"raw","lang_mode":"1","text_direction":"ltr","content_css":"1","content_css_custom":"","relative_urls":"1","newlines":"0","use_config_textfilters":"0","invalid_elements":"script,applet,iframe","valid_elements":"","extended_elements":"","resizing":"1","resize_horizontal":"1","element_path":"1","wordcount":"1","image_advtab":"0","advlist":"1","autosave":"1","contextmenu":"1","custom_plugin":"","custom_button":""}}},"sets_amount":3,"html_height":"550","html_width":"750"}`

Please test https://github.com/joomla/joomla-cms/pull/13431

**Comment by infograf768** [comment]
> If I add a new Set and save it is another "public" access and after "save & close" and re-edit the plugin lost the formatting and the "advanced" TAB.

I confirm. This is a bug.
@Fedik Can you look into this?

**Comment by Fedik** [comment]
> The issue comes from the fact that some TinyMCE legacy parameters are set in joomla.sql

I think we can remove the default parameters from SQL, it already handled by the code https://github.com/joomla/joomla-cms/blob/staging/plugins/editors/tinymce/tinymce.php#L402 and in other places eg `$levelParams->get('content_css', 1)` and so on.

And about another bug I will check

**Comment by Fedik** [comment]
> If I add a new Set and save it is another "public" access and after "save & close" and re-edit the plugin lost the formatting and the "advanced" TAB.

please test #13434

**Comment by AlexRed** [comment]
#13431   #13434  Tested successfully

**Comment by gwsdesk** [comment]
Can we change the warning message? It is not clear that all your 'legacy settings" will be lost the moment you change settings. We might have a warning such as

The TinyMCE Editor Plugin has been updated. At the moment, it uses your legacy configuration. By editing **the sets of the TinyMCE panel plugin**, you can now assign various layouts to specific user groups **but be aware that with editing you will need to redo all settings in the plugin**

**Comment by AlexRed** [comment]
I agree

**Comment by AlexRed** [comment]
In Joomla 3.6.5 if the editor TinyMCE is set "Functionality"-->"Extended" in the TinyMCE “Insert/Edit Image” Dialogue you can see the "Advanced" tab and set the image margin. In Joomla 3.7.0 the TinyMCE editor is set by default in "Extended" mode but the "Advanced Image" parameter is set "Off" by default for the administrator and the TAB "Advanced" is not visible. 
![http://alexred.com/joomla/2017/insert-edit.png](http://alexred.com/joomla/2017/insert-edit.png "http://alexred.com/joomla/2017/insert-edit.png")

Please, please, please also enable by default "Advanced Image" parameter for Administrator, to set the margin in the image in TinyMCE “Insert/Edit Image” Dialogue
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13344">issues.joomla.org/tracker/joomla-cms/13344</a>.</sub>

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/13897
