### ISSUE TITLE
new feature: Sitemap default component for Joomla?

### ISSUE THREAD

**Issue by cedricwalter** [joomla/joomla-cms#13543]
Just found that wordpress offer a sitemap plugins out of the box, is there any interest for Joomla to have also one? i forked XMAP, and was asking myself if it would not make sense to try to meet Joomla quality code standard for a future inclusion in the CMS....

**Comment by brianpeat** [comment]
I personally just keep an active subscription to JSiteMap Pro, but I can see it being beneficial. It would have to be well thought out as that sort of thing can get complicated. I mean JSite Map has a bunch of source options (including 3rd party), so you have menus, content, all the core components, etc.

**Comment by Bakual** [comment]
I think OSMap is more or less the successor of XMap

I am always a bit undecided when it comes to including a feature into core which is available using 3rd party extensions. I usually think if it's already possible to install such an extension when needed, why does it have to be in core?

**Comment by andrepereiradasilva** [comment]
just my 2 cents. a sitemap nowadays is part of any site, if a site does not have it, it should.
if is part of any site shouldn't joomla have it in the core. i see more use for it than com_banners for instance.

**Comment by mbabker** [comment]
WordPress doesn't offer a sitemap in the core distro, the functionality is available as a plugin (the same as installing a component in Joomla).  So by that comparison the two platforms since everyone loves to compare them even though they are in the same market space by name only are on a level playing field.

As for adding one to core, does the core package that gets built and shipped from this repository really need every possible tool one might need for a website to be functional "out-of-the-box"?  This is a feature that is rightfully not in core.  Same with ecommerce, CCK, and a plethora of other borderline enterprise level features (since people seem insistent on keeping Joomla in the low- to just-below-medium- website size market space).

Joomla hasn't done anything good for architecture or user experience in years.  I honestly think the code needs a good cleaning before looking at any more features.  There is a lot of stuff that is either inconsistent or just doesn't work well.  Especially since a lot of the "major" code based stuff has been received so poorly and has been an architectural nightmare to deal with (multi-database support, tags, Smart Search, the UCM framework, routing has been controversial to some and taken an excessive amount of time for review/merge and some still say it's not production suitable, now there have a modified build of DPFields in core and still in a state of flux...).

**Comment by dgt41** [comment]
I am on the `lean Joomla!` side

**Comment by andrepereiradasilva** [comment]
i understand and agree with you michael, not now, clean joomla first.
but i still think sitemap (xml and html) is a essencial funcionality of sites nowadays.

**Comment by Bakual** [comment]
> ut i still think sitemap (xml and html) is a essencial funcionality of sites nowadays.

Actually it's not needed at all for most sites. Google does a nice job indexing the site without it.
If you ask Google (https://support.google.com/webmasters/answer/156184?hl=en), they say you need a sitemap if
* site is really large
* site has large archive that isn't well linked
* site is new
* sitemap offers additional information (which usually isn't the case for automatical created sitemaps)

So for most sites it's not needed.

**Comment by joeforjoomla** [comment]
I agree with you guys. Including a sitemap component in the Joomla core simply makes no sense.

**Comment by franz-wohlkoenig** [comment]
looks like can be closed.

**Comment by B3nito** [comment]
Can I ask again for this feature is it obligation for search engines

**Comment by brianteeman** [comment]
it is not an obligation as explained above
