### ISSUE TITLE
Helix Framework uses http calls to "fonts.googleapis.com" which prevents full https validation for website

### ISSUE THREAD

**Issue by Mika83AC** [joomla/joomla-cms#13634]
Hello everyone,

as we switched our websites to HTTPS, we stumbled over an issue with a template which makes use of the helix framework.

Helix makes hard coded calls to http://font.googleapis.com/... . This is no problem until you're not using your website with HTTPS. But if you use it with HTTPS, you get an insecure resources issue which can easily prevented by calling httpS://fonts.googleapis.com insead of the HTTP version. 

So i'd like to request this change in the helix plugin in the core/helix.php file in function "public static function GoogleFont($name, $field)".

Thx.

Regards,
Michael

**Comment by alikon** [comment]
Should be reported to the helix developer not here

On 18 Jan 2017 1:04 pm, "Michael H." <notifications@github.com> wrote:

Hello everyone,

as we switched our websites to HTTPS, we stumbled over an issue with a
template which makes use of the helix framework.

Helix makes hard coded calls to http://font.googleapis.com/... . This is no
problem until you're not using your website with HTTPS. But if you use it
with HTTPS, you get an insecure resources issue which can easily prevented
by calling httpS://fonts.googleapis.com insead of the HTTP version.

So i'd like to request this change in the helix plugin in the
core/helix.php file in function "public static function GoogleFont($name,
$field)".

Thx.

Regards,
Michael

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/13634>, or mute the thread

**Comment by Mika83AC** [comment]
As the plugin is located under "system" it's not obvious that it's not part of joomla iself.

How to report an issue to the helix devs?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13634">issues.joomla.org/tracker/joomla-cms/13634</a>.</sub>

**Comment by joomdonation** [comment]
I think you can go to https://github.com/JoomShaper/Helix3/issues to report it to the developer. Please close this issue, too, as it is not related to Joomla core
