### ISSUE TITLE
Issue with Joomla Session Lifetime - Or at least it's mis-leading

### ISSUE THREAD

**Issue by sajalaspl** [joomla/joomla-cms#13657]
Under Global Configuration settings > System > Session Lifetime, you could set the number of minutes. I've set it to 3600 (1 Hour). So, the expected behavior of this setting should be:

--Expected Behavior--
- User have logged in at 9:00 AM
- User closed his browser
- User opened his browser at 9:30 AM
- He should be logged in, irrespective of the remember me checkbox selection

--Current Behavior--
- User have logged in at 9:00 AM
- User closed his browser
- User opened his browser at 9:30 AM
- He is logged out

Any help greatly appreciated.

**Comment by mbabker** [comment]
If you completely close your browser, it will remove many session related cookies which is why you typically have to log into sites again if you aren't using a remember me functionality.  If your just close the tab for that website without completely closing the browser, the cookie should stay in the browser so when you come back later it would work as you expect.

Also, a value of 3600 for your session lifetime would result in a 60 hour session.  The code converts the value of the `$lifetime` variable in `configuration.php` (the session lifetime option in the global config) from minutes to seconds.

**Comment by sajalaspl** [comment]
Thanks @mbabker for your reply, I appreciate it.

But, then what exactly is the purpose of "Session Lifetime" variable in Global Configuration?

**Comment by franz-wohlkoenig** [comment]
@sajalaspl Tooltip "Auto log out a User after they have been inactive for the entered number of minutes." Close this Issue as Discussion ended. Please reopen in case of further Discussions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13657">issues.joomla.org/tracker/joomla-cms/13657</a>.</sub>
