### ISSUE TITLE
Joomla can't use Html5 banner

### ISSUE THREAD

**Issue by qrem** [joomla/joomla-cms#13792]
### Steps to reproduce the issue

Can't show, use, insert Html5 banner

### Expected result
show Html5 banner

### Actual result

no Html5 banner

### System information (as much as possible)

Joomla 3.6.5

**Comment by C-Lodder** [comment]
Could you please describe your issue in more detail so that we can try to replicate it?

**Comment by qrem** [comment]
Go to Components > Banners > New > Type > 

There is no Html5 type banner in Joomla!

Joomla can't insert Html5 banner in Image or Custom type

**Comment by Fedik** [comment]
> Html5 banner

what is it, have an example? (code or something)

> Joomla can't insert Html5 banner

cannot insert, where? where do you tried to insert it?

**Comment by C-Lodder** [comment]
Currently, to insert HTML5 banners, you'll need to use a 3rd party extension, however I do believe that Joomla should support HTML5 banners in their shipped component

**Comment by qrem** [comment]
What still needs to be done for Joomla 3.6.5 or Joomla 3.7 support HTML5 banners in their shipped component?

**Comment by utkarshshukla2912** [comment]
show one start working on this feature @C-Lodder

**Comment by C-Lodder** [comment]
This would need to be seriously thought out first before just "developing it". There's a new Media Manager going into J4.0, so perhaps it would be best to utilise this in `com_banners`, so that you can upload your HTML banner zip file, it then gets extracted into a folder, and it then pushed into a iframe. Either way, I dont think something like this would make it into the 3.x series, so it would probably be 4.0

I'll have a chat with the media manager guys and see if something like this would be viable

**Comment by ghost** [comment]
Currently, no insert of HTML5 banners in Joomla 3.9.1 and 4,0.?

@C-Lodder can Joomla support HTML5 banners in their shipped component ?

Any update  on a chat with the media manager guys?

**Comment by C-Lodder** [comment]
@Milgius, yes it is possible. Whether ot not the powers want to support it is another story.

Tagging @wilsonge

**Comment by ssnobben** [comment]
so whats the status of support for HTML5 banners for Joomla now?

**Comment by HLeithner** [comment]
pretty sure we want to support it but I think there is no one that want's or has the knowledge to implement it.

**Comment by brianteeman** [comment]
Please can someone change the tag to J4 Issue

**Comment by zero-24** [comment]
Done

**Comment by wilsonge** [comment]
What is the actual ask here. Obviously I understand a HTML5 banner is made up of html5/css/js but what's the user going to do? We can't allow uploading unlimited javascript here because that's just asking for XSS attacks from under priv'd users. Is the idea the 3 parts have already been uploaded through (e.g. template manager by a super admin) and then just need to be used or something else?

**Comment by brianteeman** [comment]
I suspect that the request is so that an advert created by a 3rd party design tool can be managed by com_banners so you would need to be able to point to a folder and select a file and then embed that as an iframe. Then it could be managed and tracker by com_banners.

Personally I would say that this is "not for core"

**Comment by Hackwar** [comment]
I agree with @brianteeman here. This is not something we are going to support in Joomla. I'm closing this feature request.
