### ISSUE TITLE
[Admin Menu] "List All Categories" show Error on ACL or improperly structure

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13793]
### Steps to reproduce the issue
Create Menu Item Type `List All Categories` in Custom Adminmenu.
### Actual result
`Error: The com_admin component's ACL configuration file is either missing or improperly structured.`
![screen shot 2017-01-29 at 8 51 35 am](https://cloud.githubusercontent.com/assets/8235763/22402685/e6b53136-e600-11e6-9ffd-56beb5fe386a.JPG)
### System information (as much as possible)
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by infograf768** [comment]
The issue is that you have chosen as component which does not have categories in the menu item.
It would be good to limit indeed the list displayed to the components which do.

For articles, I do not have any issue

![screen shot 2017-01-29 at 09 29 18](https://cloud.githubusercontent.com/assets/869724/22402852/82b0d122-e605-11e6-8e79-69af721b2404.png)

@izharaazmi

**Comment by izharaazmi** [comment]
I could not find a way to tell which components have categories, so I
displayed all. Do you have any suggestions?

**Comment by franz-wohlkoenig** [comment]
@infograf768 Haven't looked at `Choose a Component`, so first one (Administrator - System Information" was taken. Now it works as i have chose an Component which have Caegories.

**Comment by infograf768** [comment]
@izharaazmi 
The only clear difference I think of is in the access.xml (first check if it exists for the component) where one will have
`<section name="category">`

It anyway would need a new field type. I guess it should be based on the code from
/administrator/components/com_users/helpers/debug.php

**Comment by izharaazmi** [comment]
@infograf768 <https://github.com/infograf768> Ok, I'll look into that.

PS: Is it possible that I be "assigned" all those issues where a work from
me is expected or I've promised? I tend to request this so that I don't
lose track of any.

**Comment by mbabker** [comment]
I wouldn't rely on the ACL for a component, what if someone builds a categories implementation but doesn't include ACL?

If I'm not mistaken though, it is basically a requirement to have a `JCategories` subclass if the component is using the core categories system.  So that would probably be a more accurate check.

**Comment by Bakual** [comment]
That likely will not be enough as well, since the extension may even consist of multiple parts. So if an extension uses multiple categories, it may have an extension parameter like "&extension="com_foo.bar".
The only reliable ways to detect valid extensions would be to have either a helper function returning them or quering the database to get the existing ones (assuming there is at least one category created for each type, which may not be the case)

The same issue would exist for com_fields, but that one for some reason isn't shown in the list of available menuitems. However there we would already have a helper method returning the valid contexts which could be used for that.

**Comment by infograf768** [comment]
In any case, to avoid the problem of the default top component being chosen (original report above), we should at least add an option select.
```xml
		<fields name="request">
			<field
				name="extension"
				type="components"
				label="COM_CATEGORIES_CHOOSE_COMPONENT_LABEL"
				description="COM_CATEGORIES_CHOOSE_COMPONENT_DESC"
				required="true"
			>
				<option value="">COM_MENUS_OPTION_SELECT_COMPONENT</option>
			</field>
		</fields>
```
with a new string
`COM_MENUS_OPTION_SELECT_COMPONENT="- Select Component -"`

@Bakual
> quering the database to get the existing ones (assuming there is at least one category created for each type, which may not be the case)

If no category is created, then the menu item would be no use anyway. This looks like the easiest solution.

**Comment by izharaazmi** [comment]
>> quering the database to get the existing ones (assuming there is at least one category created for each type, which may not be the case)

> If no category is created, then the menu item would be no use anyway. This looks like the easiest solution.

Doesn't that leads to not allowing users to create any category for that extension too?

**Comment by infograf768** [comment]
> doesn't that leads to not allowing users to create any category for that extension too?

I don't think so. The component would only display in the dropdown when there is a category.
testing some code now.

But I think the priority is really the component container for now. This one is not urgent.

**Comment by infograf768** [comment]
@Bakual @mbabker @izharaazmi @franz-wohlkoenig
https://github.com/joomla/joomla-cms/issues/13808
Here is a possible patch. Yes, if no category is created, it will not show the component in the dropdown. Not a big deal imho.

**Comment by franz-wohlkoenig** [comment]
Closing as we have #13808
