### ISSUE TITLE
Multilingual Associations bugs

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#13812]
## Issue 1.
The content window looks odd because on the left we have the associations tab but on the right we dont

Screenshot https://www.dropbox.com/s/9icin9l4x8dtd3f/Screen%20Shot%202017-01-30%20at%2011.51.43.png?dl=0

## Issue 2.
Open an article that has an association and select the associated language
Now select the button Copy Reference To Target

### Expected behaviour
Article content is copied from reference to target

### Actual behaviour
A NEW article is created AND the new article does not have the same status as the reference article

Video https://www.dropbox.com/s/552tdob1v7wuyyb/multilingual.mp4?dl=0

As reported but Brian Teeman over twitter...

**Comment by infograf768** [comment]
Issue 1: This looks OK to me. After saving Reference the article will be associated (if it was not already).
Improvement could be to display its Associations tab as readonly.

I confirm issue 2:
The issue comes imho from the fact that Copy Reference to Target ALSO copies (with increment) the title and the alias and the category, therefore it saves a new article.
In fact it always uses `save2copy`
See https://github.com/joomla/joomla-cms/blob/staging/media/com_associations/js/sidebyside-uncompressed.js#L20

**Comment by Bakual** [comment]
Maybe copy to target shouldn't be there if you have selected already an existing item. It doesn't make that much sense to me to overwrite an already existing item with an existing one. But maybe I miss the obvious.

**Comment by infograf768** [comment]
You are correct. Let's work on this.

**Comment by infograf768** [comment]
Here is a patch for Issue2
https://github.com/joomla/joomla-cms/issues/13819

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/13855 for Issue 1

**Comment by infograf768** [comment]
Closing as issue2 is now fixed in codebase and issue 1 has now a patch ready to test: https://github.com/joomla/joomla-cms/pull/13855



Thanks for the report.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13812">issues.joomla.org/tracker/joomla-cms/13812</a>.</sub>
