### ISSUE TITLE
[com_content] J 3.7. Browser Page Title (location of the field in article edit)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13826]
In 3.7 there is a new Field Browser Page Title in the article options, which i really appreciate.
However i think this field is better Placed at page 1 in the main options or in the Meta Tab which could be renamed to "SEO"...

For content editors this field is very important and the need to scroll down always is not a good UX...

![image](https://cloud.githubusercontent.com/assets/828371/22470114/861d2480-e7ce-11e6-9172-c3c99da41bbc.png)

**Comment by SemaphoreOxalis** [comment]
imho : this fields is only used when not using menu link and if you want an laternative title. Putting this on first tab will induce that this field is a required field which is really not the reallity in most of the case.

**Comment by mbabker** [comment]
Exactly that, see https://github.com/joomla/joomla-cms/pull/10838 for full context.

The field does not override the menu item parameter if you've got an article set as the menu item.  It will override the menu item parameter if the article is inheriting from another menu item like a category.

**Comment by coolcat-creations** [comment]
Is this consistent to the other settings? I mean when and how something overrules the menu?

**Comment by mbabker** [comment]
My use case which caused the PR was we were looking for a way to change the page title without renaming the article.  The article inherited from a menu item and based on the way the article view was coded and the way parameters merge, it was impossible to set a custom page title without making the article a menu item of its own.  So this adds a semi-clean override to the parameter inheritance for this specific use case.

I tried going the plugin route for this, but again, because of the way the view was coded you could not change the page title without essentially hooking into both `onContentPrepare` and `onAfterDispatch` during the rendering process (as well as the hooks required to add the form field) to make it all work.

So just as the tooltip explains, the field is only applicable when the article is viewed and does not have a corresponding menu item of a `com_content.article` type.

**Comment by coolcat-creations** [comment]
Ok fair enough, thanks!

**Comment by franz-wohlkoenig** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13826">issues.joomla.org/tracker/joomla-cms/13826</a>.</sub>
