### ISSUE TITLE
[3.7.0beta1] Params Alignment

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13862]
### Steps to reproduce the issue

install [3.7.0beta1] 
Go to /administrator/index.php?option=com_tags&view=tag&layout=edit&id=2

### Expected result

Nice alignment

### Actual result

<img width="440" alt="screen shot 2017-02-02 at 21 20 18" src="https://cloud.githubusercontent.com/assets/400092/22568898/70c8d186-e98d-11e6-967b-630bba99eafe.png">

### System information (as much as possible)

Google Chrome

**Comment by PhilETaylor** [comment]
This is happening all over the admin console - especially with "Note" field on the right

**Comment by Bakual** [comment]
I think that's like this for quite some time already (before 3.3.0 for sure). I always thought it was to give more space for those fields. Solution would be to remove the `span12` class from those fields in the XML.

**Comment by franz-wohlkoenig** [comment]
@Bakual a resizeable Textfield for `Note` and `Version Note` starting with same Length as above Fields?

**Comment by Bakual** [comment]
Don't ask me. I'm not an UX guy. :)
I agree with Phil that it looks bad to have them not aligned. Maybe they are also in the wrong place.

**Comment by franz-wohlkoenig** [comment]
i'm asking @cpfeifer

**Comment by cpfeifer** [comment]
I really never noticed this before, thanks for pointing it out.

I took a quick look is a more inconsistency in the CSS than meets the eye. Basically, the select inputs and yes/no input have max-width:220px, the tag select input has max-width:440px which is why it hangs over the side and fills out the container, and the text inputs have no defined width.

If all the inputs have a consistent width defined, they will line up. It's not difficult to change the numbers in the CSS, but the major concern with a CSS adjustment to core fields which are being used across the entire interface is it will change everywhere. I'm guessing those specific pixels values were used for a reason, maybe not here, but probably elsewhere. 

This seems like a relatively simple fix if: we can isolate the adjustment to fix the issue where it needs to be fixed and doesn't negatively impact other areas of the interface. That might a big "if" or maybe not. Adjusting the CSS to fix this issue may cause even more problems. I can give it a try and see what happens.

**Comment by Bakual** [comment]
@cpfeifer Try removing this class: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L23
For the version notes field that solved it for me. The tags needs some additional change I haven't figured out yet. There is some chosen stuff and inline styles happening there as well.

**Comment by cpfeifer** [comment]
That definitely solves the text input. 

The tags have a width of 440px in the CSS and I don't know why. In this context it doesn't make sense, but I'm wondering if it's like this to accommodate another area of the interface, or if it's like this because it's never been addressed previously or it's a library default. Either one is a possibility, but if it's the later, it's much easier to deal with. I'm digging through everything to find out.

**Comment by cpfeifer** [comment]
The tag container is only used in 5 places in the backend from what I can tell. I think it's just a matter of removing or adjusting one line of CSS, and it shouldn't have any negative consequences. I'll get a PR up shortly so we can test.

**Comment by cpfeifer** [comment]
Here's a PR, I actually found a few more issues in the process that I added in. The module manager publish/unpublish select dates were hanging out there too.

Instead of changing the grid12 across all the components, I targeted the right sidebar (aka form-vertical) and applied CSS to the inputs inside. Simple enough. Please test :)

**Comment by zero-24** [comment]
So this one can be closed @cpfeifer ?

**Comment by cpfeifer** [comment]
PR exists, close it up.
