### ISSUE TITLE
[3.7.0b1] [com_fields] Usergroup field doesnt render on the frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13874]
# Steps to reproduce the issue

install 3.7.0b1
create User Groups (usergrouplist) custom field
edit content on **FRONTEND**

# Expected result

Expect to see a selector to select a user object

# Actual result

Nothing rendered for this custom field

**Comment by Bakual** [comment]
Confirmed, only seems to work in backend forms.

**Comment by laoneo** [comment]
Yes, the user field doesn't work on the front end, probably that's why the filter is set to "unset" on the front https://github.com/joomla/joomla-cms/blob/staging/components/com_content/models/forms/article.xml#L112. In one of my extensions I'v made a workaround that I set the created_by on the front to type sql and make query against the users. But honestly the user field shouldn't show up at all on the front end.

**Comment by laoneo** [comment]
It was a misunderstanding with the user field. The groups field should work on the front end. Please test pr #14498 which should fix it.

**Comment by brianteeman** [comment]
As we have a pr now then this can be closed @zero-24
