### ISSUE TITLE
Ordering field in module's settings

### ISSUE THREAD

**Issue by shur** [joomla/joomla-cms#13904]
### Steps to reproduce the issue
Extensions > Modules > Go to any module's settings
Module ordering field looks different.

### Expected result
All select fields must looks the same.

### Actual result
![module-settings-ordering](https://cloud.githubusercontent.com/assets/1245155/22618818/9c8a2dd6-eaf7-11e6-8cc8-06a9ae610849.png)

### System information (as much as possible)
Joomla 3.7.0 beta1
file: layouts/joomla/form/field/moduleorder.php

**Comment by franz-wohlkoenig** [comment]
@ciar4n something for you?

**Comment by ciar4n** [comment]
Confirmed. Looks like chosen is not been applied. 

@dgt41 could you take a look?

**Comment by franz-wohlkoenig** [comment]
reminder at @dgt41 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13904">issues.joomla.org/tracker/joomla-cms/13904</a>.</sub>

**Comment by shur** [comment]
It is very difficult to work with this **module ordering field** on the mobiles, because this field options/items are very narrow (line-height only 16px, when other select items have 25px height).

I believe that this must be fixed before Joomla 3.7 is released.

**Comment by ryancom2190** [comment]
The ordering field in plugins seems to be working correctly so that may be a good place to start looking.

I personally would love if the module ordering field could also have the first and last options as well. It becomes kind of a pain to have to close out of the module just to move it to the first position.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13904">issues.joomla.org/tracker/joomla-cms/13904</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #21692
