### ISSUE TITLE
[4.0] Alerts Too In Your Face

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13907]
See screenshot from patch tester.

<img width="1440" alt="screen shot 2017-02-04 at 11 50 08 am" src="https://cloud.githubusercontent.com/assets/368545/22620374/310320c6-ead0-11e6-86e1-eef10fa85173.png">

**Comment by ciar4n** [comment]
The original idea was to move the alerts outside (absolute) of the flow of the content. Bottom right was considered to far away from the users focus hence the current position. I agree that currently they are much to obtrusive.

**Comment by mbabker** [comment]
I don't mind the concept so much, but the execution leaves a lot to be desired, especially with multiple alerts at once.  Right now it feels like the page is unusable if there's two or more alerts over it.

**Comment by ciar4n** [comment]
Although I do like the original idea, with hindsight I feel this concept works best with minimal alerts or if the majority of them can be hidden after a few seconds. For us neither case is really true.

One alternative is to have these alerts float up from the bottom and given a wider width so they intrude less on the page.

**Comment by dgt41** [comment]
let's not forget that the new approach got some extra features that are not used ATM:
- expiration: the message will disappear after the given time (in s)
- Option to set the container of the alerts (you can have multiple alerts rendered in different divs)

**Comment by dneukirchen** [comment]
As mentioned on glip i dont agree with those saying notifications in a corner are too far away from the user.

Users are used to notifications in the corners of apps. Even os and default browser push notifications are in the upper right corner. If we keep it like this, users will complain about the position. And they are right. They block the app from being usable. 

Tbh bootstrap alerts are conspicuous enough and if we make important messages sticky - so that the user has to interact with the notification to hide it - i see no problem at all. 

An app-wide timeout should be set by default. Additionally the notification should not disappear, when the user hovers it. 
Only important messages should be sticky.

**Comment by brianteeman** [comment]
Interesting read https://inclusive-components.design/notifications/

Specifically that it is ok for the notices to disappear after a defined time AND that you shouldnt have to close the alert by pressing on an X as that breaks your workflow.

**Comment by mbabker** [comment]
What is the design of alerts in the proposed final version of the template?  At this point I'm tempted to mark as "won't fix" as this seems to be the preferred design and no effort has gone into any form of adjustment/improvement in the last 19 months.

**Comment by brianteeman** [comment]
There is no design for hem as far as i am aware. The current code for them doesnt work anyway as reported elsewhere.
