### ISSUE TITLE
Namespace is not loaded in the component installer script

### ISSUE THREAD

**Issue by inf3rno** [joomla/joomla-cms#13969]
### Steps to reproduce the issue

Create a component with something like this in the installer script:

```php
JLoader::registerNamespace('Example', JPATH_COMPONENT);

use Example\aClass;

aClass::getInstance();

class Com_ExampleInstallerScript
{
	...
}
```

### Expected result

The `aClass` is instantiated.

### Actual result

```
Fatal error: Class 'Example\aClass' not found in C:\server\www\tmp\install_589ac57e8c134\com_example\installer.php on line 6
```

### System information (as much as possible)

Joomla 3.4.3, Win7x64, nginx, php 5.4

### Additional comments

It would be nice to load some utility classes for the installer.

**Comment by inf3rno** [comment]
It works using the `JLoader::registerNamespace('Example', __DIR__);`. It would be nice to use the same JPATH_COMPONENT constant in the installer script, if possible.

**Comment by joomdonation** [comment]
In Joomla, JPATH_COMPONENT always point to the folder of the component being executed which is administrator/components/com_installer in this case 

To be safe, you can use JPATH_ROOT . '/components/com_yourcom' or  JPATH_ADMINISTRATOR . '/components/com_yourcom' instead of JPATH_COMPONENT 

For now, this issue can be closed.

**Comment by mbabker** [comment]
Closing as expected behavior.  `JPATH_COMPONENT` is a relative constant and should not be relied on as an absolute path declaration.
