### ISSUE TITLE
[com_fields] Categories support - user navigation

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#14120]
Side bar menu always goes to article fields, it is bit confusing. You click fields in sidebar menu, change to Categories in dropdown, add your fields, and when you come back, it again shows Article fields. Maybe dropdown selection should be remembered in user state (like in modules manager for admin vs. site modules), or separate sidebar menu items should be present.

**Comment by laoneo** [comment]
Can you post a screenshot where exactly this happens?

**Comment by n3t** [comment]
I am not sure if sceenshot make it more clear, just follow these steps:

1. Go to Content - Fields
2. In the filter change to Category (see screenshot)
3. Go to Content - Categories (by main menu, or by side menu)
4. Go back to Content - Fields (by main menu, or by side menu)

I would expect, that filter for Category will remain, but its lost. Same for Content - Field Groups.

![categories-fields](https://cloud.githubusercontent.com/assets/979699/23133668/35c03f8a-f792-11e6-8a9b-b5804f3837b5.png)

**Comment by Bakual** [comment]
That's because the link in the sidebar is hardcoded to a specific context. Changing the link so it only points to com_content doesn't really work since it's not a valid context, we would have to guess the remaining part if not set already for com_content.

What could be done as well is to have an own UI for com_fields with a dropdown selector where the contexts for each extension could be listed, the we could just point to index.php?option=com_fields&view=fields. But it was decided to not go that route.

**Comment by Bakual** [comment]
That works because in those views, the dropdown has a default value that is used when nothin is set in userstate yet. However in case of fields there is no default value and thus it will fail with the first click.
It could have one (eg com_content.article) if there was a cross-extension "Fields" UI. With a dropdown where you can select from all contexts from all extensions. This would be simple to do actually, but it was decided to not do as it was a bit confusing for the user.

Adding links for each context gets out of hand fast if the extension has multiple contexts. If you have more links for fields in the sidebar than for the extension itself, then something is wrong :smile:
