### ISSUE TITLE
Admin Menu Manager: Can't create admin menu items using the normal workflow

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#14159]
### Steps to reproduce the issue

- Install beta2
- see this screen:
![adminmenu2](https://cloud.githubusercontent.com/assets/2596554/23146138/6c61c936-f7d4-11e6-8751-5e74b6a479d1.gif)

### Expected result

You can create admin menu entrys

### Actual result

You can only see frontend entrys

### Additional comments

It works if you using the following way:
![adminmenu gif](https://cloud.githubusercontent.com/assets/2596554/23146049/a4b67378-f7d3-11e6-9c8d-4413a497f7f0.gif)

**Comment by franz-wohlkoenig** [comment]
looks similar to [comment](https://github.com/joomla/joomla-cms/pull/13830#issuecomment-276905616)

**Comment by astridx** [comment]
I can confirm this behavior.

**Comment by infograf768** [comment]
@izharaazmi 

Please look at this.

**Comment by izharaazmi** [comment]
Sure.

**Comment by infograf768** [comment]
btw, I do not get this behaviour using staging.
Screenshot coming

**Comment by infograf768** [comment]
![adminmenu2](https://cloud.githubusercontent.com/assets/869724/23155086/52a6fad8-f811-11e6-8882-e39fa09a9e10.gif)

as you can see the Select Menu box is present before the Search Tools one.

**Comment by izharaazmi** [comment]
![image](https://cloud.githubusercontent.com/assets/6706189/23155051/ea04741c-f836-11e6-9c90-0f2a74f8c839.png)

On staging its ok. However, I likely know why it would happen. Some other PR that I do not remember right now, has moved all searchtools layout overrides centrally. However, not being comprehensive enough (it assumes we can only have one dropdown beside the search box) does not help com_menus. 

Please make sure your installation has `administrator/components/com_menus/layouts/joomla/searchtools/default.php` and `administrator/components/com_menus/layouts/joomla/searchtools/default/bar.php` 

Removing these would fallback to default layout and result in the said issue.

Hope this helps. I guess nothing to fix here. Do let me know if otherwise.

**Comment by infograf768** [comment]
Ok, found out

script.php deletes these files.

see https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1720

and
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1850

**Comment by izharaazmi** [comment]
Ok. So the fix is simple now.

However this makes me wonder if we have something to prevent such mistakes
in future. Like what if a file that was marked for deletion in 3.0, and
later another file with same pathname is created in 3.8 that should not be
deleted. Are we ready to tackle this situation by any means?

**Comment by infograf768** [comment]
only by tests I'am afraid.
Do you make the PR or shall I?

**Comment by infograf768** [comment]
FYI, this error was done with https://github.com/joomla/joomla-cms/commit/4e3a4aa32f1661a821ff59ddcec46c423b79ed6d#diff-e3c745afdbb43914c4f183a8c1587346

**Comment by izharaazmi** [comment]
If you have the file open nearby and if you'd like to... then please. Or
let me know... its all the same :)

**Comment by infograf768** [comment]
Ok, doing it now

**Comment by izharaazmi** [comment]
If I do any PR to tackle such situation, would that go in 3.7? If so I'd
hurry. Otherwise I'd do leisurely with 3.7.1 or 3.8 whatever fits.

**Comment by infograf768** [comment]
Let's first correct script.php 
Then a PR dealing for such situations in the future is welcome, and if working I see no problem merging it asap.

**Comment by izharaazmi** [comment]
Yes, thats perfectly fine. I'd look at this asap.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/14160

**Comment by infograf768** [comment]
Closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14159">issues.joomla.org/tracker/joomla-cms/14159</a>.</sub>
