### ISSUE TITLE
[4.0] Notices in fof when displaying Post-installation Messages

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#14171]
Notice: Undefined property: JVersion::$RELEASE in /Applications/MAMP/htdocs/joomla_400/libraries/fof/integration/joomla/platform.php on line 268

Notice: Undefined property: JVersion::$RELEASE in /Applications/MAMP/htdocs/joomla_400/libraries/fof/render/joomla3.php on line 73

Notice: Undefined property: JVersion::$RELEASE in /Applications/MAMP/htdocs/joomla_400/libraries/fof/render/joomla3.php on line 74

**Comment by dgt41** [comment]
FOF will be removed from core in J4. There are couple of instances in the core that is still be used and those need to be converted to vanilla joomla code (I think there are relative PR's in the staging branch)

**Comment by wilsonge** [comment]
What @dgt41 said. Basically we're going to use this. But rather than some of the complexities of registering a controller here https://github.com/joomla/joomla-cms/pull/11546 we need namespaces so we don't need to manually require the controller path (or additions to the dispatcher concept that we've got a first draft of)

**Comment by C-Lodder** [comment]
Anyone know when FOF will be removed?

**Comment by wilsonge** [comment]
When we get to the point where we fully support namespaced and autoloaded components

**Comment by wilsonge** [comment]
Hacked a fix in for now. But we are going to be removing FOF
