### ISSUE TITLE
Reinstall the core dublicate the com_associations menu entry in the admin menu

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#14190]
### Steps to reproduce the issue

Install 3.7.0b3 -> hit the reinstall button.

### Expected result

Just reinstall

### Actual result

![image](https://cloud.githubusercontent.com/assets/2596554/23226864/6afd6fbe-f937-11e6-9ea4-e42754c937ee.png)

![image](https://cloud.githubusercontent.com/assets/2596554/23226914/959a5d72-f937-11e6-825e-c06b62fb52f6.png)

**Comment by franz-wohlkoenig** [comment]
can confirm issue.

**Comment by infograf768** [comment]
This happens because this menu is added as postflight in script.php.
@rdeutz  Any way to check in the code if the menu item already exists or not?

**Comment by rdeutz** [comment]
as far as I remember than this should only run when you come from a version less than 3.7.0, not sure what is different with reinstall, will have a look

**Comment by infograf768** [comment]
Maybe because of the `beta#` added?

**Comment by mbabker** [comment]
The `preflight` hook in the core `script.php` file runs after the package has been extracted by `restore.php`.  So at that point it is already going to have the new version number, so `$this->fromVersion` is unreliable (it will always be the version you've upgraded to at least with the "normal" path and I sure hope the manual upload steps do things in the same order).

The core update system doesn't follow the same order of operations as an extension update, basically everything in `script.php` is a post filesystem update operation instead of having hook points before the filesystem updates are performed.  You would have to add hooks into other parts of `com_joomlaupdate` if you really wanted to have a pre-filesystem operation.

Your `postflight` check will need to be a query to determine if the item exists first then create one if one isn't found.

**Comment by rdeutz** [comment]
Last time as I checked it, the formVersion was the old version because it comes from the manifest cache and the preflight runs before the manifest cache gets updated. Only looking if the item exists doesn't work because someone could delete the extension (direct road to hell), but that's the reason I did it this way. I'll add the check if the menu item exists. Than we are save

**Comment by mbabker** [comment]
Oh, I missed the manifest cache part.  In that case you should be fine.

**Comment by rdeutz** [comment]
fixed with 19e415d2d82975e1a4a978c3eb5fab8d6eaa9cae
