### ISSUE TITLE
[com_fields] Deleted Gallery Field asignment comes back after saving

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14202]
When i remove banners from the gallery field it comes back after saving.

https://gyazo.com/16c4062535b987c7af70fcf8c9bbbcc5

**Comment by dgt41** [comment]
Can we just delete the gallery altogether, I mean there are a gazillion of these at the JED (and I really hate the javascript used there)???
Please...

**Comment by Bakual** [comment]
@dgt41 Do a PR and see where it goes 😄

**Comment by coolcat-creations** [comment]
i think a lot of people like the gallery, but maybe it should be happy with boorstrap and jQuery instead of a new css and js...

**Comment by franz-wohlkoenig** [comment]
A working Gallery should come by Core, if Target are also User without CSS-, Bootstrap-, ... Knowledge.

**Comment by Bakual** [comment]
The thing is that quite sure a lot of custom fields will pop up on JED rather soon, including galleries.

Personally, I would just do a Bootstrap slider type gallery, using the JS and CSS from Bootstrap like @coolcat-creations mentioned. Something very basic.

But then I also wouldn't miss the whole plugin much. Originally it made sense because it was the only custom field provided by a plugin, It was a nice showcase to have. But now all fields are provieded by plugins and we don't really need the gallery one as an example, so we could as well ditch it.

**Comment by ufuk-avcu** [comment]
I love to see the gallery inside the Joomla Core.

**Comment by franz-wohlkoenig** [comment]
if Plugin Gallery is skipped (#14238 ), this Issue can be closed.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/14309

**Comment by zero-24** [comment]
Field is removed from the core now.
