### ISSUE TITLE
In Private Messages mail subject is not same as what we written.

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#14245]
### Steps to reproduce the issue
Create New Private Message at backend side.
Goto->Components->Messaging->New Private Message
Subject: write whatever subject you want to send.

### Expected result
The mail which user received, its subject text should be same as whatever subject text we set in our private message.

### Actual result
Got subject text as follow:
subject:A new private message has arrived from joomlacmsstaging

### System information (as much as possible)
PHP Version : 5.6.30-1+deb.sury.org~precise+1 
Web Server : Apache/2.4.25 (Ubuntu) 
Joomla! Version : Joomla! 3.7.0-rc1 dev [ Amani ] 21-February-2017 15:03 GMT 

### Additional comments
Please confirm that Is it a bug? or default subject text set by Joomla?
Please see attached screen dumps.
![screen shot 2017-02-25 at 07 09 07](https://issues.joomla.org/uploads/1/291ec3ac6693981f097e8adc6c335404.png)

![screen shot 2017-02-25 at 07 09 13](https://issues.joomla.org/uploads/1/49c64bfc2db0a6411c04b5bd44aef997.png)

**Comment by zero-24** [comment]
I would call that expected behavior as the subject you set is not the email subject it is the Private Message subject.

If you go to the backend you should see the subject you set there. But this is a notification mail about a new private message so i think the subject looks for me like expected.

**Comment by richard67** [comment]
@RonakParmar  I agree with @zero-24. A private message is private, inlcuding the subject, and so it should not be exposed on a non-private communication media like email, where smtp servers on the way hand-over (and possibly even store) emails in clear text, i.e. unencrypted. And so for me it is expected behavior not to mengtion the subject in the notification email.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14245">issues.joomla.org/tracker/joomla-cms/14245</a>.</sub>

**Comment by RonakParmar** [comment]
@zero-24  and @richard67 Thank you for your reply.
But I have question, First of all I am not able to see sent private messages, and if we use predefined subject for private messages then what is the use of "Subject" field in new private message page? It is a mandatory field.
I have attached screen dumps for better understanding, please have a look, and correct me If I am doing anything wrong.
![screen shot 2017-02-25 at 11 01 02](https://issues.joomla.org/uploads/1/dbeef6727d094f109008191ab0f207b5.png)
![screen shot 2017-02-25 at 11 01 12](https://issues.joomla.org/uploads/1/935e8c5c3ba052416f1c500a85664abf.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14245">issues.joomla.org/tracker/joomla-cms/14245</a>.</sub>

**Comment by richard67** [comment]
Why cou can't see any private messages I cannot tell from here. Ask support questions in the support forum. But if you would seee any private messages in the list, I assume there would also be shown the subject in a column, so that's the use of it.

**Comment by RonakParmar** [comment]
@richard67  Thank you for increasing my knowledge in Joomla.
We can see only those emails which are being received by us. I am using wrong user to see the sent messages, I have to use that user to whom I have sent messages, now I am able to see sent messages and subject which I have used. 
Once again thank you.
![screen shot 2017-02-25 at 11 15 50](https://issues.joomla.org/uploads/1/91209ae4194f4d8eeeba164e9b4a1699.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14245">issues.joomla.org/tracker/joomla-cms/14245</a>.</sub>

**Comment by zero-24** [comment]
So we can close here @RonakParmar as expeced behavior ?

**Comment by RonakParmar** [comment]
Yes, Now It's clear to me.
Thanks.

**Comment by zero-24** [comment]
Done 👍

**Comment by richard67** [comment]
@RonakParmar I just tested with Joomla! 3.6.5, created as backend super user 1 a PM for backend super user 2 and then logged in as super user 2, selecting "Components -> Messaging" in the menu bar:
![screen shot 2017-02-25 at 11 28 00](https://issues.joomla.org/uploads/1/dc42d7d6f6302199c163671346e74a2a.png)

You can see the subject is shown in the list, so that's what it's good for.

Maybe it is a matter of permissions that you can't see your PM? Maybe the receipant user lacks the permissions to read PM?

I found a tutorial on Joomla! backend PMS here:

https://www.youtube.com/watch?v=T2C5UIUJ38I

Maybe that helps?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14245">issues.joomla.org/tracker/joomla-cms/14245</a>.</sub>

**Comment by RonakParmar** [comment]
@richard67  Thank you so much for the information, I got it and now able to see use of subject and PM in my local setup.
Thank you so much for assist.
