### ISSUE TITLE
cmd-Click open new Tab and chance also current Tab – sometimes

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14317]
#### The Result of cmd-click in Backend is different:
Starting Point is "Control Panel"
- cmd-click on "Users>Manage" or "Menus>Manage" or "Content>Articles" ... shows in both tabs same Screen,
- cmd-click on "System>Global Configuration" or "System>Global Check-in" shows only new Screen in new Tab.
### Test on
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by PhilETaylor** [comment]
I bet this is a firebox trigger bug... can you try in Chrome?

**Comment by franz-wohlkoenig** [comment]
Chrome Version 56.0.2924.87 (64-bit): got it at `Components > Contacts`, "Extensions > Manage`

**Comment by PhilETaylor** [comment]
Yes, because that is a menu item that has children. Same with Components -> Newsfeeds

The problem here is that `Components >Contacts` should not have a link, because `Components > Contacts > Contacts` is the link that should be used (and currently goes to the same place) 

There are many examples of this behaviour, newsfeeds, and the ones you have already mentioned - basically anything that currently has children menu items, when cmd+clicked will trigger the page navigation as well as launch a popup tab with the navigation.

**Comment by franz-wohlkoenig** [comment]
@PhilETaylor i tried it now for a few Days and its as you wrote. Is it possible to change this?
