### ISSUE TITLE
Trash button directly trashes articles categories fields or featured article.

### ISSUE THREAD

**Issue by tuts-22** [joomla/joomla-cms#14320]
### Steps to reproduce the issue

Select any article field or category and click on the trash icon.

### Expected result

It is better if a pop-up window opens asking to confirm if user is sure to trash the selected article field or category.

### Actual result
The item is directly trashed.

### System information (as much as possible)
PHP 7.0.15
MySQLi 5.7.17
Joomla! 3.7.0-alpha2 dev

### Additional comments
Although the file can be republished after visiting the trashed section.I think having a pop up window to confirm is a better idea.

**Comment by Bakual** [comment]
Why do you want a confirmation box when the action is fully reversible? Doesn't make much sense to me.
What are you going to ask the user? And why only for trashing then, why not for unpublishing? It's the exact same thing (changing a state).

**Comment by tuts-22** [comment]
I agree the action is reversible but for that you have to go to trashed folder then find your article and publish. I think for a better user experience a confirmation for trashing the article or unpublish (as you say) can be done.Just a pop up window ask for confirmation if user wants to trash the item just like the delete in window. Let me know if I am wrong somwewhere.!!

**Comment by franz-wohlkoenig** [comment]
@tuts-22 pop-up is risky, what if user have a blocker?

**Comment by rdeutz** [comment]
Don't see the advantage in having a nagging popup, people should learn to know what they are doing.

**Comment by Bakual** [comment]
>  just like deleting something in windows

In Windows, you could accidentally delete a file just by pressing a button on the keyboard and it could have devastating impact depending which file you're going to trash. And it could even be deleted directly depeneding on size and location. So in Windows this makes sense to a degree.
However Joomla will still be functional even if you're going to trash all articles. The website will be broken of course, but it's only a few clicks and everything is fine again. Unlike Windows.

I don't see us adding JavaScript popups for reversible actions. That actually very bad UX since it raises clicks for no reason.

I'm going to close this issue.
