### ISSUE TITLE
Class 'JToolBarHelper' not found

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#14330]
### Steps to reproduce the issue
Install some extension, in my case it was Phoca Photo. After installing it and going to the extension I get this error:
**Class 'JToolBarHelper' not found**

### Expected result
JToolbar classes will be automatically loaded

### Actual result
JToolbar classes are not automatically loaded, they must be individually loaded, e.g. by:

```
if(!class_exists('JToolbar')) {
   require_once JPATH_SITE . '/libraries/cms/toolbar/toolbar.php';
}
if(!class_exists('JToolbarHelper')) {
   require_once JPATH_SITE . '/libraries/cms/toolbar/helper.php';
}
```

### System information (as much as possible)
Joomla! 4, PHP 7, MySQL 5

**Comment by mbabker** [comment]
The class' correct cased name is `JToolbarHelper`, not `JToolBarHelper`, and has been such since 3.0.0 (same applies to all `JToolbar*` classes).  The casing is important with our autoloader because it will split the class name based on CamelCasing if it needs to try and load a file that hasn't yet been loaded.

`JToolBarHelper` will try to find a file at `libraries/(cms|joomla|legacy)/tool/bar/helper.php` whereas `JToolbarHelper` will use `libraries/(cms|joomla|legacy)/toolbar/helper.php`.

Closing as a non-issue.

**Comment by PhocaCz** [comment]
Ok, thank you for the info.
