### ISSUE TITLE
[4.0] Change Color of Active and Inactive Tabs

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14431]
### Steps to reproduce the issue
Looks like active Tab (Module) is inactive and vice versa, blue Line under active Tab isn't enough:
![bildschirmfoto 2017-03-09 um 09 36 41](https://cloud.githubusercontent.com/assets/8235763/23742211/49b34600-04ac-11e7-8822-6d151278c0bb.JPG)

### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
doesn't look inactive to me (personally).

Blue underline, well that's pretty straight forward. And then the darker background to show it has been clicked on.

**Comment by franz-wohlkoenig** [comment]
@C-Lodder its also my personal Feeling, cause i have to "think" what is active. Lok at Tabs in Firefox:
![bildschirmfoto 2017-03-09 um 11 18 15](https://cloud.githubusercontent.com/assets/8235763/23745865/22c2e02e-04ba-11e7-98bf-4a5e203e2eec.JPG)

**Comment by C-Lodder** [comment]
@ciar4n thoughts?

**Comment by ciar4n** [comment]
The current design is influenced by Googles tabs... http://materializecss.com/tabs.html

It does go away from the traditional tabs which everyone is familiar with however the current (Google influenced) is increasingly becoming an accepted alternative.

**Comment by franz-wohlkoenig** [comment]
@ciar4n Tabs-Color look all same, Difference is Line under active Tab. That looks clear.

**Comment by ciar4n** [comment]
@franz-wohlkoenig Presuming I understand you correctly do you think this would be better....

![tabs](https://cloud.githubusercontent.com/assets/2803503/23751268/745c6f46-04c8-11e7-9a0c-5fdedf6c7603.png)

**Comment by ciar4n** [comment]
Or simply...

![tabs2](https://cloud.githubusercontent.com/assets/2803503/23751455/57ed566c-04c9-11e7-9cd0-dace125086a6.png)

**Comment by franz-wohlkoenig** [comment]
if you go with http://materializecss.com/tabs.html then:
![57ed566c-04c9-11e7-9cd0-dace125086a6](https://cloud.githubusercontent.com/assets/8235763/23751520/08515f5a-04d2-11e7-9b59-990ddf45583c.png)

**Comment by C-Lodder** [comment]
As the tabs are in a header, with a background, they're more boxed in, therefore using a line only won't be as visible. The "line only" will only work well when the tabs are more free:

UIKit 3.0 example: https://getuikit.com/docs/tab

**Comment by franz-wohlkoenig** [comment]
@C-Lodder so inactive Tabs should have darker Background.

**Comment by C-Lodder** [comment]
not necessarily "*should*" :) Different software/sites will vary. 

cc'ing UX team to see what they have to say:

@cpfeifer @artisanwebandprint @BrittaStender

**Comment by cpfeifer** [comment]
The difference is subtle. In 3.x the active tab has a white or transparent border which blends with the content background, giving it the appearance of being part of the active content window while the others have a bottom border. That's what makes it pop out a bit more.

I do like the blue highlight border, but a border creates separation between the content and the active tab, and that's why the "active tab" effect seems diminished here. 

We could tinker with this. I don't think it needs a major adjustment, but a subtle accent of some kind could help. Just thinking out loud, maybe the blue goes to the top and the tab is white while the others are darker, or maybe a shadow or border highlight around the active tab to help it stand out. I think it's okay, but a simple touch of some kind could make a difference.

**Comment by tonypartridge** [comment]
I see no issue with this at all. 

The active tabs are slightly greyed with a nice underline of blue which shows it is active and the line shows there is more content below which as it's completely new content it is. Thus being perfectly valid.

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - what's happening with this? Still an issue for you? If so, would you be able to make a PR?

**Comment by franz-wohlkoenig** [comment]
not an Issue if for others okay.
