### ISSUE TITLE
List All Categories - Pagination 

### ISSUE THREAD

**Issue by gocha-gochitashvili** [joomla/joomla-cms#14475]
### Steps to reproduce the issue

1) Install fresh joomla 3.6.5
2) Go to admin and create 10 sample category (cat1, cat2, cat3)
3) Go to menu manager and create List All Categories menu
3) Shared tab > set pagination to show

### Expected result

Must show pagination on live site eg after 5 category

### Actual result

Pagination not working

### System information (as much as possible)

Joomla 3.6.5 stable
PHP 7.0.10

### Additional comments

I see in categoryes model or in categoryes controller no pagination code implemented, or in view there is no any pagination code.

**Comment by franz-wohlkoenig** [comment]
known Issue #14393

**Comment by huynhkhanhduc** [comment]
I fixed by using: new JPagination(); 
Here are what I did:
`<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;

JHtml::_('bootstrap.tooltip');

$lang  = JFactory::getLanguage();
$limit = 10;
if (count($this->items[$this->parent->id]) > 0 && $this->maxLevelcat != 0) :
	$start =  0;
if(isset($_GET['start'])&&$_GET['start']){
	$start = $_GET['start'];
}
foreach($this->items[$this->parent->id] as $id => $item) : ?>
	<?php
	if($start == 0){

		if($id >= $numberItem){
			continue;
		}
	}else{
		if($id < ($start)|| $id >= ($start+$limit)){
			continue;
		}
	}


	// HTML FOR EACH ITEM HERE  
endforeach; 

$pagination =  new JPagination(count($this->items[$this->parent->id]), $start, $limit); 
echo $pagination->getPagesLinks(); 
endif; 

?>
`

**Comment by franz-wohlkoenig** [comment]
@huynhkhanhduc can you make a PR for this Issue?

**Comment by huynhkhanhduc** [comment]
This was just a hard fixed.
Here are the steps:

**Comment by franz-wohlkoenig** [comment]
@huynhkhanhduc this is a closed Issue, please write on at #14393

**Comment by huynhkhanhduc** [comment]
Ok, Got it

**Comment by huynhkhanhduc** [comment]
@franz-wohlkoenig you can see my comment here: #14393
