### ISSUE TITLE
mod_custom only one tab (module)

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#14559]
### Steps to reproduce the issue
open custom module in modules manager

### Expected result
all tabs should be visible:
[Module] [Menu Assignment] [Module Permissions] [Options] [Advanced]

### Actual result
Only one tab shown (and configuarble):
[Module]

### System information (as much as possible)
Joomla! 3.7.0-beta3 Beta [ Amani ] 21-February-2017 15:03 GMT
MySQL: 5.7.17-0ubuntu0.16.04.1
PHP: 5.6.30-7+deb.sury.org~xenial+1
Apache: Apache/2.4.18 (Ubuntu)

### Additional comments

![screen shot 2017-03-13 at 09 05 36](https://issues.joomla.org/uploads/1/bba7b631f106c06c909116f6d7a11543.jpg)

**Comment by franz-wohlkoenig** [comment]
Can't confirm: 
![bildschirmfoto 2017-03-13 um 10 11 39](https://cloud.githubusercontent.com/assets/8235763/23848035/7a06e97a-07d5-11e7-86cc-c934605bc16f.JPG)
### System information (as much as possible)
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by infograf768** [comment]
Can't confirm either. Looks like you have customised your site (looking at the editor buttons)

**Comment by Ruud68** [comment]
Thnx @infograf768 started switching off editorxtd plugins and it turned out that the culprit was in the advpoll plugin.
Will take this up with the developer of this component.
Sorry for the 'false-positive'.
Keep up the good work!

**Comment by tgarzon** [comment]
Hi Ruud, 

Your help has been magnificent. The problem was caused by the "ADVPoll" plugin. I have disabled this plugin and the problem has been resolved.

Thank you very much.
Regards.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14559">issues.joomla.org/tracker/joomla-cms/14559</a>.</sub>

**Comment by Ruud68** [comment]
Your welcome :)
