### ISSUE TITLE
Media Manager : Root

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14597]
### Steps to reproduce the issue
<img width="242" alt="screenshotr10-09-05" src="https://cloud.githubusercontent.com/assets/1296369/23895622/4de1c65c-089e-11e7-99ca-fdc8c4f79927.png">

In media manager the path is prefixed wth the word **Root:** Is that needed? It doesnt provide any information and is confusing.

This came up in a training session where the user was looking for a folder called root

**Comment by ciar4n** [comment]
I would say remove it or replace with ../

**Comment by brianteeman** [comment]
Replace with ../ would not always be correct

**Comment by bertmert** [comment]
Because Joomla and most extensions normally are saving paths in DB like this: `images/sampledata/parks/animals/example.jpg` and also display paths accordingly in inputs (e.g. Article > Images and Links) my preference is to remove `Root:`.

![15-03-_2017_22-21-54](https://cloud.githubusercontent.com/assets/11038612/23971397/1945a932-09ce-11e7-94a4-9605168faa26.jpg)

**Comment by brianteeman** [comment]
closed see #14656
