### ISSUE TITLE
Database install error

### ISSUE THREAD

**Issue by tvoeten** [joomla/joomla-cms#14590]
### Steps to reproduce the issue
Install Joomla 3.7.0 Beta 3
After filling tabs: configuration and tab: database, tab: total
next step results in error message:
"Fout
Index column size too large. The maximum column size is 767 bytes."

### Expected result
correct installation

### Actual result
error message:
"Fout
Index column size too large. The maximum column size is 767 bytes."

**Comment by csthomas** [comment]
Which mysql version do you have? < 5.7

I assumed that the problem lies in  `#__session` table.
Before installation you can change file installation/sql/mysql/joomla.sql

from:
```sql
CREATE TABLE IF NOT EXISTS `#__session` (
  `session_id` varchar(191) NOT NULL DEFAULT '',
  `client_id` tinyint(3) unsigned DEFAULT NULL,
  `guest` tinyint(4) unsigned DEFAULT 1,
  `time` varchar(14) DEFAULT '',
  `data` mediumtext,
  `userid` int(11) DEFAULT 0,
  `username` varchar(150) DEFAULT '',
  PRIMARY KEY (`session_id`),
  KEY `userid` (`userid`),
  KEY `time` (`time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
```

to

```sql
CREATE TABLE IF NOT EXISTS `#__session` (
  `session_id` varchar(191) NOT NULL DEFAULT '',
  `client_id` tinyint(3) unsigned DEFAULT NULL,
  `guest` tinyint(4) unsigned DEFAULT 1,
  `time` varchar(14) DEFAULT '',
  `data` mediumtext,
  `userid` int(11) DEFAULT 0,
  `username` varchar(150) DEFAULT '',
  PRIMARY KEY (`session_id`),
  KEY `userid` (`userid`),
  KEY `time` (`time`)
) ROW_FORMAT=DYNAMIC ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
```

In above I only added ` ROW_FORMAT=DYNAMIC`.

There is a lot of more fields which could be better designed:
* `session_id` does not need to be utf8, ASCII will be enough
* `time` should be  int(10) unsigned
* `guest`, `username`, `userid`, `time` should be NOT NULL

I may find a little time to fix it.

For J4 there may be is an option to shrink session id by using hash functions:
```php
echo strlen(base64_encode(hash('tiger192,4', 'session_id', true))); // 32 chars
// or
echo strlen(base64_encode(hash('sha256', 'session_id', true))); // 44 chars
```

Or use binary column and store binary version without using `base64_encode`.

**Comment by gwsdesk** [comment]
I cannot replicate this. I was able to install 3.7.0-Beta3 and RC1 (nightly) without issues. (5.5.5-10.1.13-MariaDB-cll-lve)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14590">issues.joomla.org/tracker/joomla-cms/14590</a>.</sub>

**Comment by csthomas** [comment]
I'm wrong about `#__session` index but error may be related to other table.

Important may be old value for `innodb_file_format`. 
On `barracuda` error does not exists.

Joomla uses a long index for ex. on `#__extensions`:

```sql
KEY `element_folder_clientid` (`element`,`folder`,`client_id`),
  KEY `extension` (`type`,`element`,`folder`,`client_id`)
```

I have not tested it yet.

**Comment by zero-24** [comment]
closing as there is a PR by @csthomas Thanks 👍
