### ISSUE TITLE
[4.0] Content is lost after save Article

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14760]
### Steps to reproduce the issue
Create new Article and append Text in `Content`. After `Save` Content is empty.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
TinyMCE, Codemirror or no editor?

**Comment by franz-wohlkoenig** [comment]
Default-Installation: TinyMCE

**Comment by dgt41** [comment]
We fixed that yesterday, not?

**Comment by wilsonge** [comment]
We did and apparently it broke again. i'm looking now :)

**Comment by franz-wohlkoenig** [comment]
its on a fresh Installtion mightly build today.

**Comment by franz-wohlkoenig** [comment]
@wilsonge in "Joomla Update: Options" Update Channel and Custom Url is also not saved > same Reason or open new issue?

**Comment by wilsonge** [comment]
New issue

**Comment by infograf768** [comment]
Changed title to reflect the issue is for TinyMCE

@dgt41 Had a chance to look at this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14760">issues.joomla.org/tracker/joomla-cms/14760</a>.</sub>

**Comment by dgt41** [comment]
please test: https://github.com/joomla/joomla-cms/pull/15371

**Comment by franz-wohlkoenig** [comment]
closed as having PR.
