### ISSUE TITLE
Profile Plugin labels fields as "(optional)" at registration when required

### ISSUE THREAD

**Issue by blanderson22** [joomla/joomla-cms#14804]
### Steps to reproduce the issue
Enable profile plugin. Set profile plugin fields to required for registration and site and admin edit. We used Phone, Company, and website in our scenario.

### Expected result
Profile plugin fields should be labeled as required ("*") during registration.

### Actual result
On the frontend registration the profile plugin fields are labeled as "(optional)". 

### System information (as much as possible)
Joomla 3.6.5

**Comment by brianteeman** [comment]
Thank you for reporting this. It is a known issue and ia fixed for the next release

**Comment by blanderson22** [comment]
Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14804">issues.joomla.org/tracker/joomla-cms/14804</a>.</sub>

**Comment by Spudley** [comment]
@blanderson22: if you're comfortable making code changes to your Joomla installation, the fix for this is a one-liner. You can find the relevant change here: https://github.com/joomla/joomla-cms/pull/13254 (click on the 'files' tab to see the code).

You'll also see links in that pull request to the two original bug reports for the issue (https://github.com/joomla/joomla-cms/issues/13231 and https://github.com/joomla/joomla-cms/issues/13218).

**Comment by brianteeman** [comment]
Closed as it has been resolved for 3.7
