### ISSUE TITLE
[3.7] [4.0] Help: Decoupled "Web Links" shown

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14815]
### Steps to reproduce the issue
Click "Help > Joomla! Help", at Bottom decoupled "Web Links" is shown (they are not installed):
![bildschirmfoto 2017-03-20 um 20 06 37](https://cloud.githubusercontent.com/assets/8235763/24117030/dda28f60-0da8-11e7-8b78-ed0fc0863377.JPG)
Same in 4.0.
### System information
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
The list is in essence auto-generated based on the pages in the help screen category on the docs wiki plus the availability of corresponding language strings in the right places.  We haven't been allowed to remove any weblinks related language from the core repository due to nobody taking any time or effort to figure out how to properly manage all aspects of decoupled extension releases.

**Comment by franz-wohlkoenig** [comment]
Thanks for Info @mbabker Close as knowing Issue?

**Comment by brianteeman** [comment]
Yes - closed
