### ISSUE TITLE
[tinymce] drag and drop images folder

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14906]
### Steps to reproduce the issue
in the tinymce plugin config set a folder for the images
In an article upload an image using drag and drop 
Save the article and then check the location of the uploaded image in media manager AND check the source of the article for the image location

### Expected result
Image will be uploaded to the specified folder

### Actual result
image is always uploaded to /images

### Additional comments
I tried the following in the field
/media
images/media
/images/media

Yes the folder media does exist 

_Even when this bug is fixed I would suggest that the field is changed from text to folderlist_

@dgt41

**Comment by AlexRed** [comment]
I can confirm the problem.

In 3.6.5 you can use the "Images Directory" parameter in the TinyMCE plugin to insert a folder name (not a path). This will be automatically generated by the system on the first dragging of an image. The folder will be created as a subfolder of the one set in the media manager settings as “Path to Files Folder”. Since they are image files, I think it would be better to set that it is created as a subfolder of the one set in the media manager settings as “Path to Images Folder”.

Also now you can set a folder for the drag and drop images in media manager settings as “Path to Files Folder”.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14906">issues.joomla.org/tracker/joomla-cms/14906</a>.</sub>

**Comment by dgt41** [comment]
I kinda suspect why this is happening, but I have to debug this, if no PR the next few days ping me again

**Comment by franz-wohlkoenig** [comment]
pinging @dgt41

**Comment by dgt41** [comment]
Th problem is that this code:
```js
			$doc->addScriptDeclaration(
				"
		var setCustomDir    = '" . $isSubDir . "';
		var mediaUploadPath = '" . $tempPath . "';
		var uploadUri       = '" . $uploadUrl . "';
			"
			);
		}
```
Is not respected or is overridden, the solution is to bound these settings to the proper settings array. Since the introduction of the customisable settings, tinyMCE by default has 2 pairs of settings, but those variables are defined once, I hope this explains the problem. Anyhow let me debug this and make a PR and move the discussion there

**Comment by dgt41** [comment]
Please test: #15057
