### ISSUE TITLE
[4.0] com_users: Buttons not working in Edit Profile view

### ISSUE THREAD

**Issue by rjcf18** [joomla/joomla-cms#14914]
### Steps to reproduce the issue

Go to Users, Manage, select a user and when on the Edit Profile for a user click the close button.

![deepinscreenshot20170327043503](https://cloud.githubusercontent.com/assets/6710380/24339995/0fc0278e-12a7-11e7-9b0f-935f8fe2d58c.png)

### Expected result

Clicking in the close button shouldn't produce errors and go back to the previous view.

### Actual result

Clicking the close button produces an error and doesn't exit Edit Profile to return to the previous view.

![deepinscreenshot20170327031344](https://cloud.githubusercontent.com/assets/6710380/24340105/afba9e68-12a7-11e7-8069-70ed63d02a1e.png)

![deepinscreenshot20170327030153](https://cloud.githubusercontent.com/assets/6710380/24340115/bd0a3c90-12a7-11e7-98ee-cb0b6ff09110.png)

### System information (as much as possible)

Joomla! 4.0.0-dev
OS: Linux Deepin 15.3
Kernel: 4.4.0-3-deepin-amd64
Google Chrome: 56.0.2924.76 (64 bit)
PHP: 7.0.12-2 

### Additional comments

**Comment by marcochirienti** [comment]
Actually none of the buttons in the edit view is working (exception made for the help button).
This is also true for the other edit views of the component:

administrator/components/com_users/views/group/tmpl/edit.php
administrator/components/com_users/views/level/tmpl/edit.php
administrator/components/com_users/views/note/tmpl/edit.php
administrator/components/com_users/views/user/tmpl/edit.php

The problem is that the form id has been changed.
The buttons call the Joomla.submitbutton() function and the Joomla.submitbutton() calls the Joomla.submitform() function.

```
	/**
	 * Default function. Usually would be overriden by the component
	 */
	Joomla.submitbutton = function( pressbutton ) {
		Joomla.submitform( pressbutton );
	};
```
    
The Joomla.submitform() function is looking for the form id "adminForm".

```
	/**
	 * Generic submit form
	 */
	Joomla.submitform = function(task, form, validate) {

		if (!form) {
			form = document.getElementById('adminForm');
		}
```

If this is not intentional and is not part of a planned development process, we need to revert the form id to "adminForm".

**Comment by rjcf18** [comment]
Yes that's it. I've tried placing the form-validate class in the form html and it worked.

**Comment by marcochirienti** [comment]
Changed a few days ago with this PR [#14710](https://github.com/joomla/joomla-cms/pull/14710).

**Comment by dgt41** [comment]
Check #14931

**Comment by rjcf18** [comment]
Ah ok right ;)  I was going to make a PR to fix that.

**Comment by dgt41** [comment]
@rjcf18 please make a PR for all the rest forms that are missing the form-validate class

**Comment by marcochirienti** [comment]
Thanks @dgt41

**Comment by rjcf18** [comment]
Sure will do that @dgt41 .
