### ISSUE TITLE
TinyMCE plugin Advanced Options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14917]
### Steps to reproduce the issue
<img width="416" alt="screenshotr10-16-24" src="https://cloud.githubusercontent.com/assets/1296369/24349303/7ebe5014-12d6-11e7-9874-460f9f346970.png">

in the advanced options tab for tinymce are two options for HTML Height and Width
As can be seen from the screenshot above the tooltip refers to them only working in Advanced and Extended mode. But we no longer have either of those modes.

**Comment by brianteeman** [comment]
If someone can work out when they are used i can update the strings

**Comment by joomdonation** [comment]
As I understand, It supposes to be used as Default Height and Default Width of the editor  when no width and height is provided on editor form field type https://docs.joomla.org/Editor_form_field_type

However, due to a bug in the current code, that Width and Height is always use even the width and height provided in field definition (that bug should be fixed)

**Comment by brianteeman** [comment]
My comment is that it states 

> Only applies in Advanced and Extended mode.

We dont have those modes anymore.

**Comment by schnuti** [comment]
I had a short look and I would say those parameters should be removed.
width and height are set in the editor form field with defaults: width= 100%, height=500  (px)
That is used in the article text edit.

**Comment by brianteeman** [comment]
Closed see #15059
