### ISSUE TITLE
[com_fields] Is there a "file" type ?

### ISSUE THREAD

**Issue by philmarty** [joomla/joomla-cms#15015]
### Additional comments

Maybe I'm wrong, but I can't find a _File_ type for custom field.
For a upcoming project, I need that kind of field in order to add easily a link to a pdf or doc file for example to a Joomla article. 
It could have options like automatic icon display, size file display, open file in a new tab... (like the [file manager plugin](https://www.joomlacontenteditor.net/support/documentation/26-file-manager/176-inserting-editing-a-file) from JCE)

Did I miss something in the custom fields options ?

Thanks for your help

**Comment by brianteeman** [comment]
no you didnt miss anything - see https://gist.github.com/brianteeman/569cb12243b9dc13706ffb8495e888e1

**Comment by Bakual** [comment]
There isn't. https://github.com/joomla/joomla-cms/tree/staging/plugins/fields gives you the list of fields.
The closest is the media field, but it is hardcoded to images only.

I'm quite sure, after 3.7.0 is released there will be additional such custom fields surfacing in JED.

**Comment by philmarty** [comment]
OK Brian, so there's a hope to add full file types management, if I understood your "update 1" at the end of your linked page?
I'm sorry not to be a developer, to work on that part :/

**Comment by GCLW** [comment]
We are in July now, I just hope since this is set with a priority level of "Very Low" that it gets better attention than that.
And thank you brianteeman for the write-up on it. I'm actually stunned more people are not asking for this feature.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15015">issues.joomla.org/tracker/joomla-cms/15015</a>.</sub>

**Comment by Quy** [comment]
I assume this is the same request as #17936.

**Comment by ghost** [comment]
closed in Favor of #17936. 

Thanks for Hint @Quy.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15015">issues.joomla.org/tracker/joomla-cms/15015</a>.</sub>
