### ISSUE TITLE
[4.0] namespace mvc

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15175]
as we changed Cms to CMS can we change Mvc to MVC

I want to scream USE UPPERCASE
`Use all capitals if an abbreviation is pronounced as the individual letters (an initialism): HTML, CSS`

**Comment by franz-wohlkoenig** [comment]
@brianteeman i suppose Issue is about 4.0, so i changed Title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15175">issues.joomla.org/tracker/joomla-cms/15175</a>.</sub>

**Comment by mbabker** [comment]
To the extent practical, we should use "proper" English for namespaces.  Acronyms in all caps, proper title and/or camel casing (i.e. GitHub's name).  The exceptions will probably be the HTTP adapters and URI stuff since we've already in some ways set precedent for that with the Framework, but anything in the CMS that's being newly namespaced we should do it.

**Comment by brianteeman** [comment]
Closed as there is now a pr
