### ISSUE TITLE
file appveyor-phpunit.xml is present in nightly version in the root folder

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#15278]
### Steps to reproduce the issue
Download the 3.7 nightly version or update to nightly version and the file appveyor-phpunit.xml is present in the Joomla root folder. Ii is not present in build Joomla distribution archive packages beta, RC or stable.
https://github.com/joomla/joomla-cms/blob/staging/build/build.php#L109

### Expected result
no appveyor-phpunit.xml

**Comment by brianteeman** [comment]
expected behaviour

**Comment by zero-24** [comment]
@brianteeman this is not expected ;)

The problem is that the nightly build don't use the core packing script. see:

https://gist.github.com/mbabker/5b0ac0bba72caade4029

> build.php cannot be used for anything but building releases from a git tag as explained in  https://github.com/joomla/joomla-cms/issues/14263 so it requires a custom build script

This is the response i got from @mbabker a few days ;)

You are correct it is expected to be there if you download staging or using git pull ;)

**Comment by AlexRed** [comment]
thanks @zero-24

**Comment by mbabker** [comment]
Script updated.

**Comment by zero-24** [comment]
Thanks @mbabker !
