### ISSUE TITLE
[3.7 RC3] Input fields layout issue

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#15398]
### Steps to reproduce the issue
From the main menu go to Menus -> All Menu items . 
Select on of the menu items listed in the table. A new window will open up.

### Expected result
Layout of the input fields must have a proper alignment even the screen size is changed.

### Actual result
At 991px*662px and below
![667](https://cloud.githubusercontent.com/assets/9814784/25160910/90b1a8c2-24d6-11e7-8e9b-bfbdd37f9ab3.PNG)

At 1360px*315px
![666](https://cloud.githubusercontent.com/assets/9814784/25160952/d124a5bc-24d6-11e7-8247-718217c5a63b.PNG)

### System information (as much as possible)
Joomla! 3.7 RC 3
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15398">issues.joomla.org/tracker/joomla-cms/15398</a>.</sub>

**Comment by ChathuraT** [comment]
As you have mentioned when the screen resizes the alias label and the text box jumps down.
What would be the expected behavior in a screen resize? Does it need to be inline as in  991px*662px case or,
does it needs to be aligned with the Menu Title text box after jumping down?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15398">issues.joomla.org/tracker/joomla-cms/15398</a>.</sub>

**Comment by brianteeman** [comment]
Closed as there is a PR
