### ISSUE TITLE
New button max width breaks b/c with 3pd

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15578]
### Steps to reproduce the issue

Install Admin Tools Professional 
Go to HTAccess Maker view

or

As a developer, create a toolbar button with a lot of text in

### Expected result

Buttons can be any width the developer wants

### Actual result

Long buttons wrap

<img width="706" alt="screen shot 2017-04-26 at 11 54 09" src="https://cloud.githubusercontent.com/assets/400092/25433478/612799f4-2a80-11e7-8b90-307e30cb121d.png">

### Additional comments

b/c break introduced in Joomla 3.7.0
@nikosdion

**Comment by mbabker** [comment]
While it's definitely changed, I don't think I'd call this a B/C break.  Otherwise you could argue the entire template refresh falls into that category too.  Honestly, I think this boils down to what gives better UX; the ability for a dev to create a toolbar button that can go pretty wide (let's say 250-300px for the sake of argument) or the template locking a max width and creating a multi-row appearance like this one does.

**Comment by PhilETaylor** [comment]
> I don't think I'd call this a B/C break

Shhh someone might hear you ;-)

**Comment by ciar4n** [comment]
The issue here as I see it is the max width was not set on purpose. It is only been applied to `#toolbar .btn-success` which is a bit random (myself to blame).

If a max-width is to be applied it is probably best set to all buttons rather than just `.btn-success`. Would also need to be set a good bit wider to avoid every second button's text wrapping.

Alternatively we can just apply this width to where it was originally intended (New) with not max width.

**Comment by infograf768** [comment]
No max-width is good for other languages than English

**Comment by ciar4n** [comment]
PR created...  #15760

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15760<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15578">issues.joomla.org/tracker/joomla-cms/15578</a>.</sub>
