### ISSUE TITLE
Language constants error in Joomla 3.7

### ISSUE THREAD

**Issue by Vadimes89** [joomla/joomla-cms#15608]
After installing new version of Joomla (3.7) I have a bug - both, in frontend and backend, there are no any language labels, all text labels are displaying like COM_ADMIN. 
I thought that its a bug only of full installing new Joomla, but bug there and after CMS update to 3.7 version.
PHP version is 5.6.13, all checks during installation were green, so I have not idea how to fix this problem. What kind of language system modifications are in 3.7? Maybe it is need to use something like new PHP module for normal work of 3.7?

**Comment by oliver-74** [comment]
I wanted to add a comment here as I also have problems with a bilingual site and I had to revert back from 3.7.0 to my 3.6.5 backup because there I have no problems:

Under 3.7.0 suddenly the categories of my site which point from German -> English are not linking to the English category anymore but to an article. It is a different article for each category and this does NOT happen if I first switch my site to English on the start page and then try to switch from the same category from English -> German. Then I end up in the correct category. So the bug only occurs on category switches from German -> English.

When I enter the category manager and check the association links for the category which link incorrectly then the association links are correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15608">issues.joomla.org/tracker/joomla-cms/15608</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@oliver-74 can you please open an new Issue cause the Issue of @Vadimes89 is another Topic. Please search before if the Issue is also reported. Thanks.

**Comment by oliver-74** [comment]
ok will do<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15608">issues.joomla.org/tracker/joomla-cms/15608</a>.</sub>

**Comment by AlexRed** [comment]
Hello @Vadimes89 ,
your problem seems related to https://github.com/joomla/joomla-cms/issues/15587

**Comment by franz-wohlkoenig** [comment]
thanks @oliver-74

**Comment by franz-wohlkoenig** [comment]
@Vadimes89 if you see your Issue related to #15587 like @AlexRed suggested please close your Issue.
