### ISSUE TITLE
[com_fields] Lacks functionality 

### ISSUE THREAD

**Issue by rigin** [joomla/joomla-cms#15604]
### Steps to reproduce the issue
1. It is necessary to connect additional fields to categories, not just to materials.
2. For the textarea field, you need to connect the html editor

### Expected result
1.

**Comment by Bakual** [comment]
1.a) You can assign categories to fields so they only show for items of those specific categories.
1.b) You can assign fields to the category itself (just change the context to category)
2. There is a field called "editor" which will show an editor. The textarea shows a textarea. Quite straight forward I think :smile: 

Closing as expected behavior.

**Comment by rigin** [comment]
2 - thank you, I did not understand this right away, because I have problems with English. )))

1 - I mean not linking additional fields of materials according to the conditions of their belonging to certain categories, but attaching additional fields directly to categories.

At the moment, I use the content designer fieldsattach [http://www.fieldsattach.com/index.php](http://www.fieldsattach.com/index.php) - it has additional fields for materials and for categories - this allows you to make listing of category materials much more flexible.

**Comment by rigin** [comment]
Sorry, I figured it out. Looked at the component code))
