### ISSUE TITLE
request to add option to add info when registration is disabled

### ISSUE THREAD

**Issue by c3ph3us** [joomla/joomla-cms#15636]
i didn't found nothing in current joomla options that can be setup to allow such scenario:

1) create  menu entry - registration 
2) disable registration ( for example temporary  )
3) user click on register link and is redirected to login page 

- i don't want remove registration link or substitute link with article
- instead that i  want the user be informed that registration is temporary suspended when i disable registration in settings 
- so i request a feature to add place to setup  link / article  with info for user in such case

**Comment by richard67** [comment]
1. Create the article which tells that registry is temporarily disabled.
2. If you do not have such yet, create a hidden menu, means a menu not shown anywhere on the site.
3. Create a single article menu item in this hidden menu which points to the article created in step 1.
4. Use the redirect component to redirect from your register link's URL to the IRL of that single article menu. You can disable this redirect if no longer needed.

That's what I would try, I have not tested that yet. And maybe there is an easier way doing that without the hidden menu.

But I think that should work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15636">issues.joomla.org/tracker/joomla-cms/15636</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@richard67 "Feature request" is set on Issue Tracker.

**Comment by franz-wohlkoenig** [comment]
A hidden Menu isn't necessary, set "Display in Menu" on "No":

![bildschirmfoto 2017-04-28 um 07 46 06](https://cloud.githubusercontent.com/assets/8235763/25515772/0c6f322e-2be7-11e7-9a93-c47d7bbcd9ae.JPG)

**Comment by brianteeman** [comment]
In addition to @richard67 suggestion you could also do a template override for the login module and add a link to your article explaining that registration is temp unavailable in there.

This is not something suitable for inclusion in the core of Joomla.

**Comment by richard67** [comment]
@brianteeman well, the override he can't enable or disable from backend, with the redirect he can, that's why I proposed my solution. But with that solution it still requires 2 steps to disable registration: 1. disable registration, and 2. enable my redirect. So I think in fact it could be a useful feature to have a functionality similar to the offline message also for disabled registration, having a redirect from registration link URL to the disabled registration message only in case of disabled registration, being enabled or disabled by enable or disable registration. I just wanted to provide a workaround and think this here is a valid feature request.

@c3ph3us So the workaround is to add the article with the message text, then create a menu item for that, then add that menu item to an existing menu with option"display in menu" = No in the menu item, then add a redirect from registration URL to article URL in the redirect component, and then always when you disable registration you als enable that redirect.

**Comment by richard67** [comment]
@c3ph3us  ah, well, @brianteeman is right, an override is the better solution: you can check with PHP code if registration is enabled or disabled in the overridden PHP script of the login module (or wherever your registration link appears), and depending on the result of that check let the URL of the registration link be the one of the registration page or the registration disabled message article. All done in that PHP code. The you have a 1 click solution: Disable or enable registration, no further action necessary in opposite to my (too complicated) workaround.
