### ISSUE TITLE
Caching Issues in Joomla 3.7.0

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15674]
Im receiving multiple reports of caching issues in Joomla 3.7.0 - this one ticket hopes to capture people with these issues,

If you have a cache issue in 3.7.0 that was not there in 3.6.5 then report it here with your full details and system information please.

**Comment by PhilETaylor** [comment]
> Hi, I know this is not related to MyJoomla, so I understand if you reply with a simple 'No I haven't seen this' answer as you have no obligstion to give me any time on this and I know you are really busy, but I rate your Joomla experience and I've used your service for years and it is ace. I have upgraded a lot of my sites to 3.7.0 already but I have 3 or 4 where as soon as I have system cache set to On - conservative or On - progressive I seem to lose all 'Component' content on page refresh, i.e. it loads ok then when it reads it back form the cache the page comes up with the template and menus etc.. but not main articles, content or whatever the components content is on that page. I have lots of sites working ok with the cache and I've tested it with the out of the box templates and I can't find any pattern as to what might be causing (or is common) to these few sites. So strange, I've left caching off for the moment but want to get it back on. Just wondered if in your knowledge of new 3.7.0 whether you've seen this. I've hunted on the web but cant find much apart from language issues and admin cache. Are you still advising to upgrade from 3.6.5 to 3.7.0 and are they working on 3.7.1 to fix any bugs? Thanks for your time. Dave

**Comment by PhilETaylor** [comment]
> Hi Phil
> 
> Post 3.7.0 upgrade, I am wondering if anyone else has noticed sites that will load the home page featured articles on the first load, but when refreshed the "featured articles" do not display.
> 
> Turning off caching in the system prefs certainly cures the issue, but it's probably not a real fix.
> 
> I can't see any reports of it in issue tracking at Joomla, or other searches.
> 
> I'm not sure it happens on all sites, but I have spotted it on 3 of mine so far.
> 
> Any ideas, or others you know who have seen this behaviour?
> 
> Cheers
> 
> ian

**Comment by bertmert** [comment]
I've read a forum post today, sorry, that I forgot where: After upgrading to 3.7.0 and switching to PHP 7 I had to deactivate Joomla Cache Plugin....

Reason was PHP 7 with OpCache active at hoster 1&1.

**Comment by webdoor** [comment]
I have this issue, but on php 5.6.30
---


    Hi Phil

    Post 3.7.0 upgrade, I am wondering if anyone else has noticed sites that will load the home page featured articles on the first load, but when refreshed the "featured articles" do not display.

    Turning off caching in the system prefs certainly cures the issue, but it's probably not a real fix.

    I can't see any reports of it in issue tracking at Joomla, or other searches.

    I'm not sure it happens on all sites, but I have spotted it on 3 of mine so far.

    Any ideas, or others you know who have seen this behaviour?

    Cheers

    ian

**Comment by richard67** [comment]
On my multilingual test site which I updated to Jommla 3.7.0 I get an empty page with the base URL instead of being redirected to the last active site language's home page when clicking the site tile link (which points to the base URL, I use an override of Protostar).
The http status is 304 (not modified).
Both module caching and the "System - Page Cache" plugin are used.
PHP version is 7.1, opcache is enabled.
As soon as I disable the "System - Page Cache" plugin, all is OK and redirect to language's home page works well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by Bakual** [comment]
There was a PR merged a few days ago which seems to be at least similar: https://github.com/joomla/joomla-cms/pull/15592

Can you check if that fixes the issue? Else we have yet  a different one to fix.

**Comment by richard67** [comment]
Additional info to my post just above: I get followint error in my PHP error log file:
[29-Apr-2017 13:43:26 Europe/Berlin] PHP Warning:  preg_match(): Unknown modifier '/' in /path_to_joomla/plugins/system/cache/cache.php on line 162

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by richard67** [comment]
@Bakual Did you mean me? My issue seems to be related to the page cache plugin and not the file cache, and the comment in the code change tells about a workaround for php 5.3, while I was testing with php 7.1, so I think this does not apply to my problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by richard67** [comment]
@Bakual You are right, my problem is solved with #15592 . It seems it contains beside the workaround for php 5.3 also another change (test for empty cache file) which is also good for php 7.1.

So everybody forget about my posts here - my problem is solved in staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by Twincarb** [comment]
@Bakual @richard67 
I am experiencing similar issues on several sites, I have just applied #15592 and it appears to clear up the issues. This is on a new J3.7 site and PHP 7.1

I have seen different symptoms across several sites, one which only uses Joomla articles a page would open once then when the cache for that page was filled the content was blank, modules etc showed correctly.

Current site I am testing has K2 and SH404SEF and there were strange instances of an item which is several categories in would show a blank page no information saved to the server logs that I would interpret as responsible. This is the site that the PR appears so far to clear.

PHP Built On	Linux server 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64
Database Version	5.5.52-MariaDB
PHP Version	7.1.4
Web Server	Apache
WebServer to PHP Interface	fpm-fcgi<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by springob** [comment]
Same issue on bi-lingual site (en/de, de is default site language) after updating joomla to version 3.7.0:
* first access to url '/' will redirect to url '/de' (OK)
* next access to url '/' will deliver a zero byte webpage... (Error)
happens when
* System - Language Filter -> Remove Language Code -> OFF
* System - Page Cache -> Enabled<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by richard67** [comment]
@springob Is it in your case also solved when applying #15592 and clearing browser cache and then testing again?

**Comment by springob** [comment]
applying #15592 seems to help! Thanks a lot!
BTW: I am using PHP Version 5.6.21...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by Bakual** [comment]
I'm closing this then as it seems to be solved with #15592 already (and thus with 3.7.1 once released).

**Comment by PhilETaylor** [comment]
Please reopen and leave open for a few days so those coming to check don't raise duplicate issues - please also update https://docs.joomla.org/Category:Version_3.7.0_FAQ for those that go there. 

I don't expect Joomla 3.7.1 will be long :-(

**Comment by Bakual** [comment]
@zero-24 Can you write something in the FAQ?

> Please reopen and leave open for a few days so those coming to check don't raise duplicate issues

If they do a proper search before opening a new issue, they will find this one regardless if it's open or closed. If tehy don't search, they open one regardless 😄 
Imho it doesn't make sense to leave resolved issues open.

**Comment by AlexRed** [comment]
Hello @PhilETaylor, 
FAQ: https://docs.joomla.org/J3.x:Caching_Issues   
please fix the text, my english is very bad.
But in the 3.7 news no more link to the faq page as in the past  :( 
https://www.joomla.org/announcements/release-news/5703-joomla-3-7-is-here.html

**Comment by richard67** [comment]
@AlexRed You can find it below the download link buttons, see attached screen shot:
![screen shot 2017-04-30 at 09 24 27](https://issues.joomla.org/uploads/1/0f6e18407fdcc02d9656ffeb709f34c7.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by AlexRed** [comment]
yes, Sandra Thevenet add it now, I ask for it in Glip

**Comment by richard67** [comment]
Ah, ok, thanks for that 👍

**Comment by Twincarb** [comment]
@AlexRed 
The issues I had were also present with Conservative Caching applied without System - Page Cache applied. The fix is to disable all caching until 3.7.1 is released.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by AlexRed** [comment]
thanks for the info @Twincarb, please update the info in the faq

**Comment by Twincarb** [comment]
@AlexRed I tried to update the faq, but the systems believes I am trying to spam it edits are shown below. I am guilty of Spam without links - common keywords. No idea whats wrong with what I edited but am giving up now.

'Several cache issues are known. As a temporary fix, please disable <tt>Global Configuration - System Cache</tt> and the plugin <tt>System - Page Cache</tt>.'

'You may need to apply one or both of the fixes below.<br />
Disable the plugin <tt>System - Page Cache</tt><br />
Disable the <tt>Global Configuration - System Cache</tt><br />'<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by AlexRed** [comment]
Done :)

**Comment by cmirnow** [comment]
> @Bakual @richard67
> I am experiencing similar issues on several sites, I have just applied #15592 and it appears to clear up the issues. This is on a new J3.7 site and PHP 7.1


php 7.0, Joomla 3.7.
I have known this problem for about three years. From time to time, HTML of my website is not displayed in a browser. At this moment I see this:


![spectacle tj9967](https://cloud.githubusercontent.com/assets/10660173/25573568/4efafbd6-2e4f-11e7-9b66-0b7173976891.png)



Hard to believe? I understand. But it's true.
This collision occurs if "Conservative caching" (in global configuration) is enabled. Clearing a cache solves this problem... for a while. I have to disable the cache plugin. I'm trying to use GotCache, it helps. But the problem sometimes happens, though infrequently. Help me please. I talk with support at the forum JSN-templates, but they shrug. What is the reason for this collision? Thanks for you answer.

**Comment by jimhill10** [comment]
Here is what began happening to one of my sites since I updated to Joomla 3.70. The page content is blank except all the menus and template styling. This site is on SiteGround and uses the JSGCache plugin. This happens when global configuration is set to Conservative Caching (type = file not memcached). System - Page Cache plugin is disabled. Using shlib - Db query cache and programming library plugin with memcached. Using SH404SEF and this is ordered just before the JSGCache supercacher plugin. To replicate just turn the Global Config cache to Conservative. Load a few pages, eventually the content will go blank.  Turn the cache off in global config, clear the Joomla cache (not touching Siteground supercacher), isssue goes away.  This site is using a Yootheme template and it is completely up to date. PHP7.1, everything up to date.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15674">issues.joomla.org/tracker/joomla-cms/15674</a>.</sub>

**Comment by Freewindrider** [comment]
Joomla 3.7, PHP 7.1.4, MySQLi 5.5.5-10.0.29-MariaDB

We've experienced the same issue: a click on 'login' _sometimes_ showed a blank page. 

**Solution in our case:**
Just had to deactivate the plugin system-page cache in order to avoid this wrong feature behaviour. 

Tested before deactivation: Cache cleared, plugin-order, exclusion of certain menu items/urls in the plugin settings, incompatibilities with JCH Optimize, etc.

**Comment by BlackSquirrel9** [comment]
Same problems with me.

I Disable the plugin System - Page Cache
& Disable the Global Configuration - System Cache
-> Blank redirection and false translating of the menu are resolved. 

But the language switcher link on the home page still redirects to a wrong page.

**Comment by Bakual** [comment]
Guys, this issue is closed and already fixed in staging. There is no point adding comments "happens for me as well".
