### ISSUE TITLE
Error:"A session is active. You cannot change the session module's ini settings at this time"

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#15680]
I reopen this issue here because it still exists in 3.7:
Joomla! Issue Tracker | Joomla! CMS #12153 - E_WARNING in libraries/joomla/session/handler/joomla.php - J3.6.2  https://issues.joomla.org/tracker/joomla-cms/12153

### Steps to reproduce the issue
After an update to 3.7

Error message :
"A session is active. You cannot change the session module's ini settings at this time"

Various unsatisfying solutions have been found, like:
comment out: ini_set('session.use_trans_sid', '0');

Could Cavo789's be doable ?

**Comment by PhilETaylor** [comment]
What is the FULL error message, including the line and file that raises this warning?

**Comment by ghazal** [comment]
`Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/clients/XXXXX.com/http/libraries/joomla/session/handler/joomla.php on line 4`

**Comment by PhilETaylor** [comment]
Please test https://github.com/joomla/joomla-cms/pull/15742

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15742<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15680">issues.joomla.org/tracker/joomla-cms/15680</a>.</sub>

**Comment by wetken** [comment]
I have this issue using Joomla 3.7.5. Is there anything I can do to resolve it until the next release?
(I'm using an unconventional setup, I accept that, but I'm also fighting a time constraint.)

Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /home/.../libraries/joomla/session/handler/joomla.php on line 46

Warning: Cannot modify header information - headers already sent by (output started at /home/.../libraries/joomla/session/handler/joomla.php:46) in /home/.../libraries/joomla/session/handler/joomla.php on line 104
Error displaying the error page: Application Instantiation Error: Failed to start the session because headers have already been sent by "/home/.../libraries/joomla/session/handler/joomla.php" at line 46.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15680">issues.joomla.org/tracker/joomla-cms/15680</a>.</sub>

**Comment by ghost** [comment]
@wetken can you please open a new Issue as comment on closed Issues didn't get much Notice.
