### ISSUE TITLE
[4.0] Tags links in default content 404 errors

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15766]
### Steps to reproduce the issue

install Joomla 4
Go to http://joomla4/index.php/all-tags
see: 

<img width="757" alt="screen shot 2017-05-03 at 13 09 34" src="https://cloud.githubusercontent.com/assets/400092/25659887/c5317592-3001-11e7-95e2-903ddbec8433.png">

### Expected result

Clicking ANY of these tags takes me to a `200 OK` type page. 

### Actual result

Green - http://joomla4/index.php/all-tags/green - 404 URL invalid
Lime - http://joomla4/index.php/all-tags/lime - 404 URL invalid
Red  - http://joomla4/index.php/tagged-items - Probably not the right url to go to? 
Yellow - http://joomla4/index.php/compact-tagged - surely yellow should be in the url ?

**Comment by brianteeman** [comment]
This is because of a small confusion/bug in the installer. (I will address this in a PR)

Joomla 4. currently only has one sample data set and this is the old sample_testing.sql file which is never shipped in Joomla so the report here while  valid is probably down to incorrect testing data and not a j4 bug itself

**Comment by wilsonge** [comment]
I think I have fixed this - this was an error in the tags router
