### ISSUE TITLE
[4.0][Security] Remove Statistics from default install on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15769]
### Steps to reproduce the issue

Install Joomla 4 
go to http://joomla4/index.php/statistics

### Expected result

that I am not telling the world - by default - my version numbers, how many users my site has and how popular Im not. 

### Actual result

<img width="879" alt="screen shot 2017-05-03 at 13 21 28" src="https://cloud.githubusercontent.com/assets/400092/25660276/6e4a08f0-3003-11e7-9747-574f866d5d8a.png">

**Comment by bembelimen** [comment]
Perhaps the statistic module should be removed (or excluded like the weblinks) at all?
I do not see any purpose in a module where I can fake my clicks and show my server information in the frontend...

**Comment by brianteeman** [comment]
This is because of a small confusion/bug in the installer. (I will address this in a PR)

Joomla 4. currently only has one sample data set and this is the old sample_testing.sql file which is never shipped in Joomla so the report here is not exactly as described. 

The statistics module is never created on a live install of Joomla.

There is however a valid issue that it might be considered a security information disclosure if a site owner does publish the module but that would probably go into the "hack yourself" category.

**Comment by brianteeman** [comment]
> The current Joomla 4 installer - accepting all the defaults - installs this module with public access.

yes thats what I said

See #15811

**Comment by brianteeman** [comment]
I am going to close this. Joomla 4 should not be installed on a live server and this module is only published with the test data that is never distributed
