### ISSUE TITLE
Random Image Module not random when cache on

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15793]
### Steps to reproduce the issue

Enable cache in Joomla
refresh http://joomla4/index.php/random-image page (from default content) 

### Expected result

The image should still be random - even though the cache is enabled

### Actual result

Same image loads each page load

**Comment by mbabker** [comment]
This would require hardcoding the module to not allow caching.  Cache and the intent of this module are kind of at odds with one another here.

**Comment by PhilETaylor** [comment]
Welcome to hell...

**Comment by Fedik** [comment]
It is a random but in a bigger time span :neckbeard:

**Comment by brianteeman** [comment]
When you say enable cache - do you mean the cache option in the global config or the system cache

The random image module by default is set to no caching 

iirc that means it wont be cached with conservative or progressive cache but would still be cached with the system page cache - an option which really is not suitable for any type of dynamic site

**Comment by andrepereiradasilva** [comment]
Disabling the cache option in module doesn't means it works in page cache or even in webserver/proxy/CDN cache scenarios.

IMHO this type of random behaviour should always be done in client side, ie, javascript, not server side exactly because of server cache issues. 

Moving to a js random could solve this issue.

**Comment by mbabker** [comment]
For what it is it's random enough.
