### ISSUE TITLE
CacheLite test throws intermittent failure on windows

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#16039]
### Steps to reproduce the issue

random failure occurring in cachelite test usually with php 7.1 on windows
https://ci.appveyor.com/project/rdeutz/joomla-cms/build/1.0.4240/job/r3ms19arudrf3rtw

### Expected result
no failure

### Actual result
```php
There was 1 failure:
1) JCacheStorageCacheliteTest::testCacheTimeout
Some data should be available in lifetime.
Failed asserting that false matches expected 'testData'.
tests\unit\core\case\cache.php:121
tests\unit\suites\libraries\joomla\cache\storage\JCacheStorageCacheliteTest.php:66
```

### System information (as much as possible)
php 7.1 windows (appveyor)

//cc @mbabker

**Comment by mbabker** [comment]
Following the question everything mentality that seems to be recently popular, I'm wondering what value there is to still support Cache_Lite in 4.0.  It's in essence an alternative to our filesystem cache adapter, and since we don't even ship it with core (we could thanks to Composer), it's only available on servers where the PEAR package is installed.

**Comment by photodude** [comment]
I see no reason to support it. I have never seen anyone actually using it.

**Comment by mbabker** [comment]
Would you mind doing a PR for 3.8 to deprecate the Cache_Lite cache adapter?  Then we can drop support in 4.0.  If there are any issues, we can discuss them in the deprecation PR and issues like this can either be addressed at low priority or closed in full.

**Comment by brianteeman** [comment]
see #16575

**Comment by photodude** [comment]
closing via PR #16575
