### ISSUE TITLE
What is Language Default?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16045]
### Steps to reproduce the issue
Install more than one language and then logout and load the admin login screen

### Expected result
An indication of what the default is. Not much point in stating you can select the default if you dont know what it is.
<img width="260" alt="screenshotr10-40-25" src="https://cloud.githubusercontent.com/assets/1296369/26099922/2955afc6-3a24-11e7-8eb0-64a087cd391b.png">

### Actual result
No indication what the default language is
<img width="279" alt="screenshotr10-37-12" src="https://cloud.githubusercontent.com/assets/1296369/26099798/c9257f3c-3a23-11e7-891b-ef51dd2ccdf1.png">

**Comment by SharkyKZ** [comment]
This refers to user's default language.

**Comment by brianteeman** [comment]
Or to the site default language and you have no way of knowing what it is when you select it. Thats the point I am trying to make.

**Comment by infograf768** [comment]
> This refers to user's default language. Can't state it because it differs depending on user.

it can't be as the user has not yet logged in.

**Comment by infograf768** [comment]
> Or to the site default language

it is in fact the admin default language. agree would be nice to display instead the language + default

**Comment by infograf768** [comment]
my mistake: it may be the admin default labguage before login, but it would load the user default language after login. so hard to decide what to do

**Comment by alikon** [comment]
It should be the default administration language, isn't it?

**Comment by infograf768** [comment]
an admin user may have a default admin language which would override the default admin language used for the login page.

**Comment by alikon** [comment]
Ummh but at that point you don't know which is the user so you don't know
his/her language hence default admin should be correct in this situation or
I:m wrong

On 16 May 2017 2:11 pm, "infograf768" <notifications@github.com> wrote:

an admin user may have a default admin language which would override the
default admin language used for the login page.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/16045#issuecomment-301762567>,
or mute the thread

**Comment by ot2sen** [comment]
Doesn´t look like a cookie is set for chosen admin language in user settings.
So the admin default language will show on login page until logged in.

Would make sense to show which language is in fact the default as Brian says. And also not double list it in the select list. As it is now default is shown with no indication of which it is and at same time this language is listed below in the select list. Once should do.

**Comment by Bakual** [comment]
> And also not double list it in the select list. As it is now default is shown with no indication of which it is and at same time this language is listed below in the select list. Once should do.

If you have a different language set for your user, then this "double" entry allows you to login with the "default" language instead of your preferred one.

**Comment by ot2sen** [comment]
True. You really can´t tell at the login page which is default when everything happens after login.
A site having for example 5 admin languages and 5 admin with each their preferred language would get to ->their<- default language after login.
So current way seems good because all 5 could be valid defaults.
