### ISSUE TITLE
[4.0] menubar  not fixed and position to top?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16058]
## Steps to reproduce the issue
Observe the steps in 3.x and 4.x videos below
in 3.x the menubar and toolbar are fixed to the top but only the toolbar on 4.x (maybe thats a design choice) but more importantly see how when you switch to a new tab you dont scroll 100% to the top of the screen - partially obscuring the title

## 3.7
![37](https://cloud.githubusercontent.com/assets/1296369/26119691/03d63d8c-3a66-11e7-90fa-0a82024221b4.gif)

## 4.0
![40](https://cloud.githubusercontent.com/assets/1296369/26119700/0a714506-3a66-11e7-9c25-19a03c5c8539.gif)

**Comment by C-Lodder** [comment]
Have you fetched the latest code? Just want to be sure whether or not https://github.com/joomla/joomla-cms/pull/16018 fixed it

**Comment by brianteeman** [comment]
Yes it was latest as of the time of posting

**Comment by ciar4n** [comment]
I don't think this is related to #16018 

There is nothing specific in 3.7 that makes the page jump to the title when clicking through the tabs. The reason is does is only when navigating to a tab with no scroll bar which is normal browser behavior. Try navigating between 2 tabs that both require a scroll in 3.7 and it will not jump to the title. Having said that 4.0 does not act exactly the same. Navigate to a page without a scroll in 4.0 leaves it 30px short of the title (top). The reason strangely enough appears to be due to the bottom padding on the body tag... https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_global.scss#L9

**Comment by brianteeman** [comment]
>  Navigate to a page without a scroll in 4.0 leaves it 30px short of the title (top).
thats exactly the issue to resolve

**Comment by ciar4n** [comment]
PR created.. #16078

**Comment by brianteeman** [comment]
closing as we have a PR
