### ISSUE TITLE
Alias menu item issue after update from 3.6.5 to 3.7.1

### ISSUE THREAD

**Issue by kat05** [joomla/joomla-cms#16113]
### Steps to reproduce the issue

Updated a Joomla 3.6.5 site to Joomla 3.7.1.
Please note this did not happen on several installations I tried, but on one particular install, so at the moment I can't give a proper way to replicate the issue every time.

### Expected result

Alias menu items still work after the update.

### Actual result

Alias menu items show 404 - Component not found on frontend.
In the menu item editor there is some issue with the 'Edit'/'Select' button as seen in the screenshot.

### System information (as much as possible)

php 7.0

![joomla_371_alias](https://cloud.githubusercontent.com/assets/5719486/26211692/65938758-3bf3-11e7-8ee4-e155243bb769.jpg)

**Comment by PhilETaylor** [comment]
I think this might be related to https://docs.joomla.org/J3.7.1:Non_SEF_Urls_Broken

**Comment by tonypartridge** [comment]
I have noticed this once, but also agree it shouldn't be an edit button since you cannot edit it, only select another.

Really it should just be a single select to select another item.

**Comment by kat05** [comment]
Just noticed this on a 2nd site, after the Update the wrong URL looked something like
/?Itemid=169
After fixing it manually the URL was a SEF URL such as
/tutorials
for example.

**Comment by andrepereiradasilva** [comment]
> I have noticed this once, but also agree it shouldn't be an edit button since you cannot edit it, only select another.

The "Edit" button should only appear when there is a menu item selected (ie, with the id in `jform_id` form field).
See https://github.com/joomla/joomla-cms/blob/staging/media/system/js/modal-fields-uncompressed.js#L36

So that means that in that particular case that `jform_id` form field (hidden field) must have a menu item id and that's why you have the "Edit" button.

Now, why the title of the menu item is not displayed as is displayed "Select a Menu item"...

Could it be possible that you have a menu item alias to a menu item that existed in the past but doesn't exist now?

To help anyone further debbuging this issue, the menu item title is fetched here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/fields/modal/menu.php#L201

**Comment by brianteeman** [comment]
It has been several months since this issue was created without confirmation of the issue. I am closing it at this time but it can always be reopened
