### ISSUE TITLE
Preflight and Postflight are not called during extension uninstall

### ISSUE THREAD

**Issue by izharaazmi** [joomla/joomla-cms#16166]
### Steps to reproduce the issue
Create a simple component with the given script file.
Perform Install, update, uninstall.

### Expected result
On each action the script file should be able to do the processing via preflight and postflight.

### Actual result
On uninstall, the preflight and postflight are not called.

### System information (as much as possible)
Joomla 3.7 (I know this was same earlier)

### Additional comments
Why it was decided to do it that way?

[script.php.txt](https://github.com/joomla/joomla-cms/files/1016996/script.php.txt) Remove `.txt`

**Comment by Bakual** [comment]
preflight might work on uninstall, postflight gets tricky because at that point the file would already be deleted 😄 
However I'm not sure what you would want to do in preflight? During installation, this allows to check if we can install the package and abort if some requirements aren't met. During uninstallation I can't see why we should abort an uninstallation. That should always be possible.

**Comment by mbabker** [comment]
> postflight gets tricky because at that point the file would already be deleted

As long as the file is loaded into memory before deleted, the class and its methods will be available.  So that's not an issue.

**Comment by Bakual** [comment]
True enough :)

**Comment by eorisis** [comment]
I see at least one reason for preflight to fire on component uninstall. Currently if you install a package with say a component and 2, 3 plugins in it, you can the go on and uninstall one of them without uninstalling the whole package. But if the developer wants to "lock" this, say because they do not want extra checks in their plugins like "if the component exists" etc, they can setup preflight in such a way that it will abort the uninstall process with a warning in case you try to uninstall one of the extensions of that package. But in any case, you can never know what one may want to execute in preflight. In my tests preflight does not fire on component uninstall till J3.7.2.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/16343 is the starting point for standardizing things.  It will only be 4.0 due to the required B/C breaks.

**Comment by brianteeman** [comment]
Closed so we just have one place see #16343
