### ISSUE TITLE
if (!is_int($status) || is_int($status) && !isset($this->responseMap[$status]))

### ISSUE THREAD

**Issue by rumours86** [joomla/joomla-cms#16202]
if (!is_int($status) || is_int($status) && !isset($this->responseMap[$status]))

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/web.php#L562

maybe
if (!is_int($status) && !isset($this->responseMap[$status]))
or
if (!is_int($status) || (is_int($status) && !isset($this->responseMap[$status])))
or
if (!is_int($status) && !isset($this->responseMap[$status]))

**Comment by PhilETaylor** [comment]
That is 3 year old code from @wilsonge  https://github.com/joomla/joomla-cms/commit/a322a43ae96992ca506f899c7294181e0efbc08e

**Comment by wilsonge** [comment]
The first one fails because your starting to check for non-integer keys in the responseMap array which starts to lead to odd behaviour.

The third one is the same as the first one. 

The second one is fine - but honestly this code is likely about to get refactored with https://github.com/joomla/joomla-cms/pull/16040 anyhow. So not sure how relevant this is

**Comment by rumours86** [comment]
if (is_int($status) && !isset($this->responseMap[$status]))
or
if (!isset($this->responseMap[$status]))

because (!is_int($status) || is_int($status)) === true

**Comment by richard67** [comment]
@rumours86 You are wrong because of operator precedence: && comes before ||. Same as in maths with multiplication coming before sum

**Comment by richard67** [comment]
@rumours86 See [http://php.net/manual/en/language.operators.precedence.php](http://php.net/manual/en/language.operators.precedence.php "http://php.net/manual/en/language.operators.precedence.php")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16202">issues.joomla.org/tracker/joomla-cms/16202</a>.</sub>

**Comment by richard67** [comment]
Does anybody agree with me that we can close this issue? It seems @rumours86 does not reply.
As I have shown in my previous 2 posts, this issue here is caused by a misunderstanding of operators precedence in PHP.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16202">issues.joomla.org/tracker/joomla-cms/16202</a>.</sub>

**Comment by rumours86** [comment]
@richard67 i think you right
example https://middle.valyaev.su/1.php

**Comment by richard67** [comment]
@rumours86 Could you close this issue in the issue tracker or on github then?

**Comment by rumours86** [comment]
@richard67 Thanks for clarifying
