### ISSUE TITLE
ISIS template needs CSS for text separator in mobile view

### ISSUE THREAD

**Issue by ZoFx** [joomla/joomla-cms#16267]
### Steps to reproduce the issue
- Set the admin template to "ISIS"
- Open the Joomla backend in the mobile view (smartphone or small device emulator)
- Open the main menu > submenu _Menus_
- Look at the text separators

### Expected result
Should be styled and well readable.

### Actual result
Currently, lack of styling makes it almost unreadable:

![joomla_text_separators](https://cloud.githubusercontent.com/assets/12634312/26466005/81ff6e1c-418d-11e7-9aa2-d889e6b766c1.PNG)

### System information (as much as possible)
Joomla 3.7.2

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
3.7.3-dev
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
Why don't we just make that use Bootstrap's `nav-header` class for the `<li>` element instead of custom designing it?  Seems to work just fine.

<img width="378" alt="screen shot 2017-05-27 at 11 52 03 am" src="https://cloud.githubusercontent.com/assets/368545/26523034/02769818-42d3-11e7-9cd1-aa7a6a737d55.png">

<img width="248" alt="screen shot 2017-05-27 at 11 52 19 am" src="https://cloud.githubusercontent.com/assets/368545/26523035/048bc1aa-42d3-11e7-9ce7-d8d7287d7e95.png">

**Comment by ZoFx** [comment]
Looks like a brilliant solution! I just think we should get rid of the left padding on these items, as otherwise it looks akward IMHO. Unfortunately I'm not sure about how to change this without breaking anything else ...

**Comment by Quy** [comment]
Related #15093

**Comment by franz-wohlkoenig** [comment]
thanks @Quy, set related in Tracker.

**Comment by tonypartridge** [comment]
+1 for @mbabkers solution, waiting on the or ;)

**Comment by ghost** [comment]
closed as having Pull Request #18225<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16267">issues.joomla.org/tracker/joomla-cms/16267</a>.</sub>
