### ISSUE TITLE
[4.0] Trashed and archived articles show by default

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16366]
### Steps to reproduce the issue
Trash or archive an article

### Expected result
Trashed and archived articles don't show in the list expect when search filter is set to show them.

### Actual result
All articles show.

### Additional comments
After clearing the search filters with the button, the list filters as expected until you log out and in again.

**Comment by brianteeman** [comment]
this is the same as in J3

**Comment by Bakual** [comment]
> this is the same as in J3

Can't reproduce it in current staging. By default, trashed and archived articles aren't shown in the manager. You need to either filter by that state or set it to "All"
I'm talking about the admin manager list, just in case you were looking somewhere else (I wasn't clear in the issue).

**Comment by brianteeman** [comment]
now i am very confused what you are talking about

**Comment by Bakual** [comment]
Article Manager after being freshly logged in. Note that articles of all states are shown with no filter active.
![all](https://cloud.githubusercontent.com/assets/1018684/26591744/e6254cb6-455e-11e7-8afd-7371ac57ca31.PNG)
After clicking "clear", it now only shows published and unpublished articles. That's the expected behavior and is also the behavior in J3.
![clear](https://cloud.githubusercontent.com/assets/1018684/26591747/e87d8c44-455e-11e7-92b1-41b41328417c.PNG)
Hope that helps.

**Comment by brianteeman** [comment]
ah - now I understand what you are saying

**Comment by esedic** [comment]
These are my findings (tested on sample data of 4.0-dev branch on PHP 5.6.24):
login to administration, go to article manager, you see a list of articles.
Check an article, click on Trash button in toolbar. Article will stay on the list, same goes for Archived articles.
Till now expected behavior was that after that trashed/archived article was no longer visibile on the list of articles.
If you use filters in Search tools, for example to filter trashed articles only and after that select  -Select status- in dropdown and reset filter, you will get a list without trashed/archived articles.
If you have trashed/archived articles from before, they will be visible when you visit Article manager.

**Comment by brianteeman** [comment]
I can confirm this - see movie - helps others

![thomas](https://cloud.githubusercontent.com/assets/1296369/26592036/73893250-4557-11e7-9a67-9637d76f4127.gif)

**Comment by joomdonation** [comment]
This issue is related to the change in my PR https://github.com/joomla/joomla-cms/pull/15455

Now, the first time you visit the page, the $published value has value null instead of '' (empty string) like before. There are different ways to fix it:

1. Change this line of code https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Model/Articles.php#L243 to 

```php
$published = (string) $this->getState('filter.published');
```

2. Modify populateState method in the Articles model, add this line of code to setup default value for filter.published

$this->setState('filter.published', '');

Do you think which one is best @Bakual?

**Comment by Bakual** [comment]
I came to same conclusion (null vs '') but couldn't figure out which PR was responsible :smile: 
My solution would be to just loosen the comparision like this `elseif ($published == '')`, but casting to string would work as well. I wouldn't add something to the populateState method thought.

**Comment by Bakual** [comment]
Closing as we have a PR
