### ISSUE TITLE
[com_fields] Wrong List of Images (imagelist) Directory

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#16413]
### Steps to reproduce the issue
1) change Content > Media > Options > Path to Images Folder default to another
2) make a List of images (imagelist) custom field

### Expected result
Imagelist from directory which set in Media options

### Actual result
The Directory still show the original Images folder content not what you set in Media options

### System information (as much as possible)
DB: 5.5.5-10.1.19-MariaDB 
PHP: 7.0.7
Apache, Joomla! 3.7.2 Stable

**Comment by AlexRed** [comment]
I can confirm the problem.
Also edit the "Path to Files Folder" but the field imagelist still show the original Images folder <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16413">issues.joomla.org/tracker/joomla-cms/16413</a>.</sub>

**Comment by bertmert** [comment]
Yes, custom imagelist field should support the feature of [Joomla form field imagelist](https://docs.joomla.org/Imagelist_form_field_type). It should be possible to set any path to images below JPATH_ROOT you want. And it should take over the filter option from Joomla form field.

Otherwise it's not really helpful and you could use media field instead.

**Comment by ghost** [comment]
@laoneo can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16413">issues.joomla.org/tracker/joomla-cms/16413</a>.</sub>

**Comment by laoneo** [comment]
Yes I will, but not before JWC.

**Comment by laoneo** [comment]
Had a look on it and the problem is that we need a default directory which is hardcoded in the XML file where I guess can't be made dependant on the global configuration setting. Here is the line of code https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/imagelist/params/imagelist.xml#L10. The would include that we default the directory parameter to the root dir which I think is bad.

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by ghost** [comment]
This has been closed as stated above – it can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16413">issues.joomla.org/tracker/joomla-cms/16413</a>.</sub>
