### ISSUE TITLE
3.7.2 "current" menu option missing on default Joomla menu module

### ISSUE THREAD

**Issue by epidote** [joomla/joomla-cms#16421]
### Steps to reproduce the issue
Upgrade from 3.7.1 to 3.7.2

### Expected result
"current" menu option available to default Joomla menu module 

### Actual result
"current" menu option missing from default Joomla menu module 

### System information (as much as possible)
3.7.2

### Additional comments
discussed here
https://forum.joomla.org/viewtopic.php?f=708&t=951300&p=3477349#p3477349

![screen shot 2017-06-01 at 09 50 31](https://issues.joomla.org/uploads/1/e147d4190e6af64dd1241047dc170dd9.jpg)

**Comment by infograf768** [comment]
Hmm, this has already been the case in 3.7.0
See PR https://github.com/joomla/joomla-cms/pull/11694

It indeed has not been proposing "Current" since we implemented the modal_menu

**Comment by infograf768** [comment]
ok, iguess that, for that, we have to revert that one to use the other menu type

**Comment by infograf768** [comment]
Afterthought: 
We just have to change the Tip as, basically, not selecting a menu item for that field (therefore displaying `Select a Menu Item` ) is equal to the former `Current`.
Will make PR.

**Comment by infograf768** [comment]
Well, again some new thought:

the issue is larger than that in fact.
 We have multiple modal_menu types in xmls where we have also the option Default (all the redirects for example) 
These Options are not taken into account in the UI. We have everywhere 'Select a Menu Item' instead. 
Therefore, if we just take care of the tips, my guess is we should also take off from the xmls these now useless options, i.e. delete `<option value="">JDEFAULT</option>` 

Obviously, the nicest solution would be to reinstate the use of the possible Option and leave the tips and xmls alone. 

I tried to do that by reinstating some of my original code in the modal_menu type, but I have some issues in the sense that the option displays nicely when opening an item to edit, but we lose it if we select a menu item, then clear.

@Bakual @dgt41 
What do you think/can do?

**Comment by infograf768** [comment]
Note: the issue is not new to 3.7.2 vs 3.7.1. It was present since 3.7. imho

**Comment by infograf768** [comment]
Please test this patch where we do respect the Option placeholder.
https://github.com/joomla/joomla-cms/pull/16459
