### ISSUE TITLE
Joomla administrator menu redirection

### ISSUE THREAD

**Issue by gocha-gochitashvili** [joomla/joomla-cms#16492]
### Steps to reproduce the issue
1) Go to administrator and create new menu (eg:hidden menu)
2) Create any menu (eg: single article)
3) Click Save close button

### Expected result
Must close and stay in same menu (hidden menu)

### Actual result
After Save close redirects on Main Menu not on same (eg: Hidden menu)

### System information (as much as possible)
Fresh Joomla installation 3.7.2
Php 7

**Comment by franz-wohlkoenig** [comment]
Thanks for reporting, its a duplicate Report. This Issue is solved in 3.7.3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16492">issues.joomla.org/tracker/joomla-cms/16492</a>.</sub>
