### ISSUE TITLE
[4.0] Session count?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16569]
Spotted by @coolcat-creations at jab17 and confirmed now by me

After some time working on testing j4 which might include closing and reopening the browser and/or having a session timeout and being forced to llog back in the count of the number of admins just keeps increasing

See below for the screenshots of a few hours using both J3 and J4 - the count only goes up in 4

(personally I am convinced there is some bug in 4 as i am being logged out much more often than i was in 3 but @wilsonge said there was no issue)
<img width="336" alt="screenshotr16-56-15" src="https://user-images.githubusercontent.com/1296369/26885315-3ca123ee-4b9a-11e7-9c47-c91c40dfa60a.png">
<img width="260" alt="screenshotr16-56-23" src="https://user-images.githubusercontent.com/1296369/26885317-3cc7c878-4b9a-11e7-883d-e19c58522471.png">

**Comment by mbabker** [comment]
There's probably something to dig into, I've noticed some quirks as well but hadn't thought twice about it.

**Comment by wilsonge** [comment]
Just to add I'm not saying for sure there is not a bug in 4 - just with limited testing I couldn't easily reproduce one. I'm busy tonight but can look into it thursday night all being well.

**Comment by brianteeman** [comment]
coming back to the test site in the morning I see that the count has not reset and its still increasing

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/CMS/Application/CMSApplication.php#L173

In 3.x we are arbitrarily running garbage collection on the session database table because we log the extra metadata as well, whereas the 4.0 code right now won't do it in favor of allowing PHP's session extension to handle garbage collection (which is how all the other handlers have to work, we don't have code arbitrarily flushing expired session data on the filesystem path or in Memcached).  My guess is all of us who are seeing this type of behavior aren't getting the PHP cleanup to happen very often (some of it is explained in https://secure.php.net/manual/en/session.configuration.php#ini.session.gc-probability and linked references).

**Comment by brianteeman** [comment]
I am going to close this at this time as I see there have been updates to session
