### ISSUE TITLE
[4.0] Can't install a clean version of 4.0

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16616]
### Steps to reproduce the issue

Try to install

[Joomla_4.0.0-dev-Development-Full_Package.zip](https://github.com/joomla/joomla-cms/files/1065967/Joomla_4.0.0-dev-Development-Full_Package.zip)

### Expected result

Joomla installs

### Actual result

`Error displaying the error page: Application Instantiation Error: No database selected`

### Additional comments

This https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/namespacemap.php#L143 requires a database connection which is not there at the installer time.

**Comment by zero-24** [comment]
@yvesh @wilsonge you have created and edited that file and my can help out here.

**Comment by wilsonge** [comment]
OK - tell me how in the installer you can make a database connection when you haven't entered database credentials yet :)

Seriously tho it works fine for me. I think it's related to when your database credentials are the default credentials (i.e. it is root and empty password) and so the database can make a connection before it should actually be connected

**Comment by joomdonation** [comment]
@zero-24 For the time being, move this line https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/CMS/Application/CMSApplication.php#L144 to execute method, before this line https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/CMS/Application/CMSApplication.php#L321 to get it installed

@wilsonge We should fix it, please. I use Xamp, default username is root and password is empty, I got this issue, too as reported before. Since it is default username and password of Xamp, I think many users will get this same issue (at least when they try to install Joomla 4 on their local computer for testing)

**Comment by joeforjoomla** [comment]
You right @joomdonation i got the same issue trying to install Joomla 4 on my localhost

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/pull/16680
