### ISSUE TITLE
[com_fields] Render Class does not work on single field in content

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#16672]
### Steps to reproduce the issue
load one field into an article using the tag {field xx}
set a Render Class into the field option

### Expected result
the field shall have the css class applied

### Actual result
the css class does not apply

### System information (as much as possible)
J! 3.7.2

### Additional comments
The problem is that the Render Class option is used into the fields layout and if you call only one field with the tag, it calls the field layout (single)

<?php $class = $field->params->get('render_class'); ?>
	<dd class="field-entry <?php echo $class; ?>">

shall be loaded into the field layout and not the fields layout as it an option of the field itself

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16672">issues.joomla.org/tracker/joomla-cms/16672</a>.</sub>

**Comment by ghost** [comment]
@coolcat-creations can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16672">issues.joomla.org/tracker/joomla-cms/16672</a>.</sub>

**Comment by AndySDH** [comment]
If i recall correctly, this part
`<dd class="field-entry <?php echo $class; ?>">`
originally, this indeed was inside the field layout instead of the fields layout, but it was then decided to move it inside the fields layout (found it: #15013), because users expect to be able to use {field xx} as part of the text when embedding it in an article.

That means being able to do something like: Mark was born on {field xx} in {field xx}.

If you put the "dd" in the field layout, that is not possible anymore, and it's the reason why it was changed in the first place.

It's probably better to keep the "dd" in the fields layout, and possibly add the class inside the span of the field layout.

**Comment by laoneo** [comment]
The field accepets alternative layouts, so you can create one which fits your needs.

**Comment by ghost** [comment]
closed on given Answer above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16672">issues.joomla.org/tracker/joomla-cms/16672</a>.</sub>
