### ISSUE TITLE
Possible ACL for creating new menu item

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#16703]
### Steps for the feature
Go to menu-items and create new one
There you get all possible options of menu items
If you ask a customer with no knowledge to add a menu item they get allot of options and do not know what to do.
90% of the time my customer only needs 1/2 or 3 options there.
To reduce the options i can disable a fully component and it disappears.
If i want to use the component but i do not want my customer to create menu items with lets say Tags or contacts i can't disable that option.

So new feature could be:
New ACL option to enable disable the possibility to show component in the new menu-item selection.

It would even better like to have the possibility to not show anything but just select what you want, even choosing the views. Some components have already 20 different options.
But i think this would be more difficult.

**Comment by franz-wohlkoenig** [comment]
I guess you talk about Backend: What about Custom Admin-menu, setting Menu to hidden?

**Comment by anabarcellos** [comment]
I understood that he wants the client to add menus, so it couldn't be hidden.  

When the client is creating the menu, he will not see all options of menu type to select.
For instance: (backend) Menus > Menu items > "New"

"Menu Item Type" SELECT
- Single article
- External URL
[and nothing more] 
The client doesn't see all the options of all components, but just the ones that the developer selected to be displayed. 

It makes sense to me since many of the options are not so intuitive to inexperienced users. It would be much easier for them to create menus.      
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16703">issues.joomla.org/tracker/joomla-cms/16703</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
misunderstood opening Comment as no "Menu" should be shown.

**Comment by joris85** [comment]
Annabarcello's 

Thats exact what i Mean (: 
I im now on a camping and wil take a look if i am back if that is possible wit new feature Admin Menu.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16703">issues.joomla.org/tracker/joomla-cms/16703</a>.</sub>

**Comment by gwsdesk** [comment]
This is a functionality that is provided in ACLmanager form Sander Potjer "aclmanager.net" No need to add this extensive development to the core imho since it is available as an (very good and versatile) extension<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16703">issues.joomla.org/tracker/joomla-cms/16703</a>.</sub>

**Comment by brianteeman** [comment]
Sounds a good idea to the core to me - you shouldnt have to spend money to enjoy joomla

**Comment by sanderpotjer** [comment]
I do think there is a little confusion here, @joris85, your request is for when your users creating a new menu item right? So when you want someone to only be able to create menu-items for com_content they should see, with only Article Manager and the System links for example:
<img width="1464" alt="screen shot 2017-08-30 at 23 36 41" src="https://user-images.githubusercontent.com/522834/29896193-4744aada-8ddc-11e7-9d8f-d4becfdc91d9.png">

There are a couple solutions for this. One of them is to introduce a new action in the component settings that allow you to set permission to create menu-items for that component or not. This is useful for cases when your user can access the Article Manager and Menu Manager, but you don't want them to create menu items for the Article Manager component. 

As I am not sure how often this setup is needed, a possible easier solution without introducing a new action for the components is to make use of the current `core.manage` action of the components. Right now it is indeed a kind of strange that when your user doesn't have permissions to access components in the backend, but does have permissions for the menu manager that they can create menu items for the components without access. So it is an option to only show the menu-item type options for the components the user is granted access to in the backend. 

@joris85 Would that already solve a bit of the issue for you?

@gwsdesk sorry to disappoint you, but this is not a feature in my extension already ;-)

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 22th October 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
