### ISSUE TITLE
Media manager (com_media-Override, Isis). No image names.

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#16710]
See image please. There are no image names displayed in media manager. Current staging, 3.7.2 and earlier.

![15-06-_2017_20-12-00](https://user-images.githubusercontent.com/11038612/27195480-38633cd6-5207-11e7-81fb-132abb821433.jpg)

If you remove the template override `..../templates/isis/html/com_media/medialist/thumbs_imgs.php` names are displayed.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16710">issues.joomla.org/tracker/joomla-cms/16710</a>.</sub>

**Comment by infograf768** [comment]
I confirm.
The problem is that if we delete the file in the Isis override (or change it to the same content as the component), we lose the magnifying glass . 
![screen shot 2017-06-17 at 07 41 56](https://user-images.githubusercontent.com/869724/27250453-8279f560-5330-11e7-84e6-961c985a8808.png)

Though, when hovering the magnifying glass, we can see the name
![imagename](https://user-images.githubusercontent.com/869724/27250700-ddb52ce2-5335-11e7-99fa-409758981e14.gif)

With small changes in code and CSS, I could get this
![screen shot 2017-06-17 at 08 18 35](https://user-images.githubusercontent.com/869724/27250696-bfdff774-5335-11e7-8829-2c639c69fc0a.png)

@Bakual @rdeutz 
What do you think? Is it worth I make the patch?

**Comment by infograf768** [comment]
for RTL, would not be easy though.

**Comment by Bakual** [comment]
Sure, it's better than no filename for sure.

**Comment by bertmert** [comment]
Just an additional feature request: The preview modal should show the name, too(?)

> we lose the magnifying glass

Do we really need it? I know it's nice... ;-)

**Comment by rdeutz** [comment]
looks good

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/16769
