### ISSUE TITLE
Menu disappears after joomla update

### ISSUE THREAD

**Issue by scottm74** [joomla/joomla-cms#16732]
### joomla update from 3.6.5 to joomla 3.7 and up

PHP Built On 	Linux s32.web-servers.com.au 2.6.32-673.8.1.lve1.4.3.el6.x86_64 #1 SMP Wed Feb 10 08:57:30 EST 2016 x86_64
Database Version 	10.0.31-MariaDB
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.20
Web Server 	LiteSpeed
WebServer to PHP Interface 	litespeed
Joomla! Version 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by franz-wohlkoenig** [comment]
thanks for report, @scottm74, this Issue is closed as duplicate Report (please search if an Issue is reported before report). Please test #16577<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16732">issues.joomla.org/tracker/joomla-cms/16732</a>.</sub>

**Comment by richard67** [comment]
@scottm74 Please test #16577 ([issue tracker link see here](https://issues.joomla.org/tracker/joomla-cms/16577)).
