### ISSUE TITLE
Setup error: Step 1 fails because of HTTP instead of HTTPS

### ISSUE THREAD

**Issue by mariusa** [joomla/joomla-cms#16767]
### Steps to reproduce the issue
Install on Heroku
https://github.com/technomile/Heroku-Joomla-PostgreSQL

Using Chrome: Complete step 1 setup, click Next
console error:
Mixed Content: The page at 'https://app.herokuapp.com/installation/index.php' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://app.herokuapp.com/installation/index.php'. This request has been blocked; the content must be served over HTTPS.

### Expected result
use relative paths on AJAX requests, so it just uses the current protocol/site

**Comment by zero-24** [comment]
Can you reproduce this using the core pack too?

**Comment by zero-24** [comment]
As it looks like a over 1 year old version on a quick view?

**Comment by mariusa** [comment]
I can only try the Heroku pack, sorry. Feel free to close if not applicable anymore

**Comment by zero-24** [comment]
Can you confirm that you get a Joomla 3.4.4 after you have installed it? As this is the version in that repo.

**Comment by mariusa** [comment]
Yes Joomla 3.4.4

**Comment by zero-24** [comment]
> Yes Joomla 3.4.4

So it is a issue in a very old version that was released nearly two years ago (08.09.2015).
The last released version is 3.7.2.

I have just tested 3.7.2 and cannot confirm any problem.

But anyway even if there would be a issue any fix we would deploy would not reflect to your repo as that was not updated since more than two years.

Please contact the owner of that repo so you can try the last version of joomla and report back here. Thanks.

**Comment by brianteeman** [comment]
This really isnt an issue for the Joomla Issue tracker
