### ISSUE TITLE
Tagged Item menu. Don't show Browser Page Title.

### ISSUE THREAD

**Issue by cs100675jvv** [joomla/joomla-cms#16770]
Joomla 3.7.2
### Steps to reproduce the issue
In different menu was created menu items - Tagged Items http://prntscr.com/flie05
Browser Page Title and Page Heading are filled.

### Expected result
Browser Page Title should be as in the proper field in Menu Iten - Page Display tab.

### Actual result
It shows jush tag's name http://prntscr.com/fligkz

### System information (as much as possible)
Clear installation with protostar default tamplate
Database Version	5.5.48
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.4.45
Web Server	Apache
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by franz-wohlkoenig** [comment]
Thanks for Report, this Issue is known, please see #13365. So this Issue will be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16770">issues.joomla.org/tracker/joomla-cms/16770</a>.</sub>
