### ISSUE TITLE
global settings error

### ISSUE THREAD

**Issue by maxyy88** [joomla/joomla-cms#16782]
I have a problem with joomla 3.7.2.
When I enter global settings and change settings and press save, it redirects to the website and it does on several other pages within the admin page.
What could be wrong has tried to reinstall Joomla a number of times but does not know what the error is

**Comment by PhilETaylor** [comment]
2 things cause this

 - A crap webhost with over protective mod_security settings and bad handling of 403 forbidden messages created by mod_security, the save hits a mod_security rule and silently redirects to your home page

 - Exceeding your `max_input_vars` which has a default like 1000 and can be exceeded if you have many many ACL Groups.

Neither are something to be fixed in Joomla.

**Comment by franz-wohlkoenig** [comment]
closed as no Core-Issue. @maxyy88 Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16782">issues.joomla.org/tracker/joomla-cms/16782</a>.</sub>
