### ISSUE TITLE
Messages showed on extensions update

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#16815]
### Steps to reproduce the issue
Not sure if this is intentional or not, however until Joomla 3.6 no output from the installscript 'install' and 'update' methods was showed during an extension update using the Joomla updater.

As of Joomla 3.7, the output messages if provided by various vendors, are showed even in the Joomla updater page after an extension update. 

Self explaining screenshot, i don't think that this is so nice, especially when you update multiple extensions at once:
![messages_installation](https://user-images.githubusercontent.com/17835460/27439998-a983048e-5769-11e7-8560-a94ca83914b2.PNG)

**Comment by tonypartridge** [comment]
So a message should always be output when updating this is standard postindall functionality.

The only issue I see in the above is that notice before updating message is still shown, is that right?

**Comment by joeforjoomla** [comment]
Yes you are right @tonypartridge 
The 'notice' is still shown.

**Comment by brianteeman** [comment]
The notice is still shown because you have other extensions still to update- they are further down the screen and not shown on your screenshot. The length of the JCE message just pushes it far down. Other extensions dont do that.

So I am closing this because it is correct to display the notice in this case. It will not be shown if there are no other updates  available
