### ISSUE TITLE
[3.7.3 RC] [manifest] MINOR: Should not be pkg_weblink.xml remove from joomla-cms staging repository?

### ISSUE THREAD

**Issue by Quibi** [joomla/joomla-cms#16859]
The file  joomla-cms/administrator/manifests/packages/pkg_weblinks.xml belonging to the weblink packages is still in the staging repository.

Should not be this file removed from the joomla-cms staging repository since the package weblinks is not currently in the default installation?

I am aware that this this clearly a minor (and possibly annoying) quirk. Sorry for the inconvenience.

**Comment by franz-wohlkoenig** [comment]
thanks for reporting. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16859">issues.joomla.org/tracker/joomla-cms/16859</a>.</sub>

**Comment by richard67** [comment]
As far as I remember, this has been discussed here several times before, and there was some reason why it has not been removed. I think it was related to update containers for Joomla versions where it is installed and has not been decoupled yet. Please correct me if I remember wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16859">issues.joomla.org/tracker/joomla-cms/16859</a>.</sub>

**Comment by richard67** [comment]
See [https://issues.joomla.org/tracker/joomla-cms/16723](https://issues.joomla.org/tracker/joomla-cms/16723 "https://issues.joomla.org/tracker/joomla-cms/16723"): For 3.x it is still required because there is a special handling for updating site which have it installed, and with 4.0 it will be removed then by the PR of the link.

So @franz-wohlkoenig this issue here can be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16859">issues.joomla.org/tracker/joomla-cms/16859</a>.</sub>

**Comment by Quibi** [comment]
That is right, @richard67. I have not found this. Sorry.
