### ISSUE TITLE
[Shown on] showon does not accept the AND and OR options at the same time.

### ISSUE THREAD

**Issue by angelovianajr** [joomla/joomla-cms#16954]
When using multiple fields on showon that use complex options, they does not recognize simultaneous use of OR e AND. 

`field1:1[AND]field2:1[OR]field3:0`

In this case, they consider only the last comparison, `field2:1[OR]field3:0`

I'm testing this in joomla 3.7.2

**Comment by franz-wohlkoenig** [comment]
@laoneo can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16954">issues.joomla.org/tracker/joomla-cms/16954</a>.</sub>

**Comment by laoneo** [comment]
This issue is not related to custom fields as we do not support the showon setting by now.

**Comment by ghost** [comment]
thanks for Info, @laoneo.

**Comment by ghost** [comment]
~~@angelovianajr can you please close this issue because of comment above?~~<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16954">issues.joomla.org/tracker/joomla-cms/16954</a>.</sub>

**Comment by laoneo** [comment]
I didn't say that the issue itself is wrong, just said that the issue is not related to custom fields.

**Comment by ghost** [comment]
sorry, missunderstood, @laoneo

**Comment by ghost** [comment]
set Category "Feature Request" for "Shown on" in "com_fields".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16954">issues.joomla.org/tracker/joomla-cms/16954</a>.</sub>

**Comment by chrisdavenport** [comment]
Confirmed this bug is still present in Joomla 3.9.4 as I've just been bitten by it.  The two cases that are incorrect are
`field1:1[AND]field2:1[OR]field3:0`
and
`field1:1[OR]field2:1[AND]field3:0`
both of which completely ignore the first comparison.
What is needed is proper left-right precedence and, ideally, brackets to override left-right precedence when required.

**Comment by ghost** [comment]
closed as having Pull Request #24197
