### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by caprom** [joomla/joomla-cms#16969]
deleted.

**Comment by franz-wohlkoenig** [comment]
Can't confirm.

Logged in at Backend, logged out and refreshed Login-Screen is showed as expected.

**Comment by flyingwombats** [comment]
Much to my surprise I can confirm that this odd behaviour is happening.
Its only happening in firefox ( Im using 54.0.1 (32-bit)) and after the update to 3.7.3

I have tried it on 5 sites now and will continue testing but each did not display the behaviour described at all before the upgrade in any browser.
After updating to 3.7.3 if I log out. Wait for logged out so admin login screen showing, then hit refresh and sometimes first time, sometimes after 3rd of 4th click I got it to just log back in to the admin area. It was not consistent and as I have tried other sites I have now got to a point it wont happen on a few but still does on others.
It has to be https otherwise the login box on firefox shows a message and the reload does not work.
Weird
Video of it shared on vimeo [https://vimeo.com/224300902](https://vimeo.com/224300902 "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16969">issues.joomla.org/tracker/joomla-cms/16969</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@flyingwombats i have added my Techn-Infos above (also Firefox 54).

**Comment by flyingwombats** [comment]
PHP Built On	Linux server5.softforge.co.uk 2.6.32-696.3.2.el6.x86_64 #1 SMP Tue Jun 20 01:26:55 UTC 2017 x86_64
Database Version	5.5.5-10.1.24-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.19
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
@franz-wohlkoenig Notice in the video I had to do it several times... Also I got to the point where it would not, closed all instances of firefox down and reopened and behaviour returned<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16969">issues.joomla.org/tracker/joomla-cms/16969</a>.</sub>

**Comment by SniperSister** [comment]
Thanks for your report, as this has some security implications, we will handle it within the security team. Feel free to reach out to us a security@joomla.org for more details.

**Comment by zero-24** [comment]
I have just removed all comments and contens as we moved this too the JSST. Thanks!
