### ISSUE TITLE
[Update] Changes in the scrip.php file && JExtensionHelper

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16985]
### Steps to reproduce the issue

We know that in some cases the new integrated classes are not loaded on update. https://github.com/joomla/joomla-cms/pull/16724

### Expected result

script run

### Actual result

script does break

### Additional comments

Maybe we should better do a if class exists check before the call to `JExtensionHelper::getCoreExtensions();` in that spezific file? Expecialy as that manifest thing is not that critical when it does not run.

**Comment by richard67** [comment]
Hmm, good thought.

But I did not experience since long time that problem with new classes coming with the update not being loaded on update.

So I am curious on feedback here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16985">issues.joomla.org/tracker/joomla-cms/16985</a>.</sub>

**Comment by mbabker** [comment]
It was only a problem historically when supporting core updates through the extension manager.  We aren't doing that anymore.

By the time we get to a point where that class gets called for the first time in an update, either the system will be correctly updated and there will be nothing to worry about or there was an issue unpacking the update and the user is going to have other problems anyway.

**Comment by zero-24** [comment]
Ok, i just want to be sure, closing than based on Michaels info. Thanks.

**Comment by richard67** [comment]
That's what I had in my memory, too, that the problem was from extension installer being used for core update.

Thanks for confirm.
