### ISSUE TITLE
[com_fields] wrapping media data in markup by default

### ISSUE THREAD

**Issue by rotanadan** [joomla/joomla-cms#17007]
plugins\fields\media\tmpl\media.php
line 34

There is no logic that I see to stop this from happening, I want to set a background image with a media field in custom fields, but when I retrieve the data it comes with the <img src= markup around it.

**Comment by franz-wohlkoenig** [comment]
@laoneo can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17007">issues.joomla.org/tracker/joomla-cms/17007</a>.</sub>

**Comment by laoneo** [comment]
You need to use the rawvalue of the field.

**Comment by ghost** [comment]
@laoneo that i should have known by myself too.

@rotanadan can you please close Issue? More about com_fields: https://docs.joomla.org/J3.x:Adding_custom_fields/Parameters_for_all_Custom_Fields

**Comment by mbabker** [comment]
... and that is documented where?  Joe's sitting right next to me and we've wasted more time than we should have to figure out the raw value exists.  AFAIK the only reference to it is essentially buried in a var_dump output on https://docs.joomla.org/J3.x:Adding_custom_fields/Overrides meaning this is yet another thing in Joomla that to figure out you have to reverse engineer the code for instead of being any type of user friendly.

**Comment by brianteeman** [comment]
Well thats a wiki so anyone can update it ;)

**Comment by jwaisner** [comment]
Closing as issue is not a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17007">issues.joomla.org/tracker/joomla-cms/17007</a>.</sub>
