### ISSUE TITLE
Where are menu item's Globals Parameters in Joomla 3.7.x ?

### ISSUE THREAD

**Issue by gaetzone** [joomla/joomla-cms#17135]
### Steps to reproduce the issue
Since I have updated from Joomla 3.6 to 3.7.3, the menu items parameters options look different.

### Expected result
With Joomla 3.6, in Menu->Menu Item-> Parameters, I could choose between : Globals Parameters, Show and Hide.

### Actual result
With Joomla 3.7.3, I can only choose between Show and Hide. 
Why the Globals Parameters option disappear ?
Where can I define the Globals Parameters for menu links ?

### System information (as much as possible)
I have done/modify/change nothing else than updated the core.

**Comment by AMurray2016** [comment]
Not quite sure I understand the question but this is best(in my opinion....) directed to the help forums rather than reporting it as an "issue" on GITHUB.   The forum is https://forum.joomla.org.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17135">issues.joomla.org/tracker/joomla-cms/17135</a>.</sub>

**Comment by gaetzone** [comment]
Thanks for your reply AMurray.
Maybe it is not an issue but please find the 2 screens captures below. 

Here it is the menu item parameters in Joomla 3.6 :
![joomla-3 6-menu-link-parameters](https://user-images.githubusercontent.com/8244094/28247555-06a5394e-6a33-11e7-8e31-c36534e1f17a.png)

And here, it is the menu item parameters I got in Joomla 3.7.3 just after upgrading from 3.6 :
![joomla-3 7 3-menu-link-parameters](https://user-images.githubusercontent.com/8244094/28247557-0beb0988-6a33-11e7-929d-25f323d7f97e.png)

You can see that I can not select "Global Parameters" in Joomla 3.7.3

**Comment by brianteeman** [comment]
Going to guess it is an issue with the plugin you have installed that's
doing the "exposed" tab

On 16 Jul 2017 1:35 p.m., "gaetan" <notifications@github.com> wrote:

Thanks for your reply AMurray.
Maybe it is not an issue but please find the 2 screens captures below.

Here it is the menu item parameters in Joomla 3.6 :
[image: joomla-3 6-menu-link-parameters]
<https://user-images.githubusercontent.com/8244094/28247555-06a5394e-6a33-11e7-8e31-c36534e1f17a.png>

And here, it is the menu item parameters I got in Joomla 3.7.3 just after
upgrading from 3.6 :
[image: joomla-3 7 3-menu-link-parameters]
<https://user-images.githubusercontent.com/8244094/28247557-0beb0988-6a33-11e7-929d-25f323d7f97e.png>

You can see that I can not select "Global Parameters" in Joomla 3.7.3

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/17135#issuecomment-315606421>,
or mute the thread

**Comment by gaetzone** [comment]
You are right !
After disabling the "Expose System Plugin", I can choose again between "Use global", "Show" or "Hide".
Note that the plugin is mentionned as "for Joomla 2.5". But it was working with Joomla 3.6. Seemingly not with 3.7.x

Would you like to keep the issue opened ?

**Comment by brianteeman** [comment]
Closed as not a core issue

**Comment by gaetzone** [comment]
Thanks a lot for your help.
Best regards
