### ISSUE TITLE
The problem that paging URL does not go through router build

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#17149]
The following content comes from software translation!

Today, when analyzing Joomla class JPagination, it is found that the JPagination produced by link has not been built by router's build; This resulted in my custom router plug-in unable to process the path of Pagination, The paging path is not up to expectations; Has it been improved here to allow paging URL to be built by build?

The path I want:
http://domain/alias/16.html
http://domain/alias/16.html?start=10

Present path:
http://domain/alias/16.html
http://domain/alias.html?id=16&start=10

https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/pagination/pagination.php line 825
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/route.php line 56

The above translation may not be accurate, please forgive me.

**Comment by ztj1993** [comment]
Because of the complexity and variety of development, the routing definition uses plug-ins and does not use components.

**Comment by ggppdk** [comment]
Yes, but it does not need to go through router build,
since Jroute will use current URL

You should check how the
&id=16

gets added to the URL, e.g.

-- you maybe using
$pageNav->setAdditionalUrlParam('id', 16);

-- or your current URL is 
http://domain/alias.html?id=16

Please note that other components do not suffer from this issue,
so you should think what you are doing differently
