### ISSUE TITLE
[4.0] Request: On Collapsing Backend Mainmenu

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#17220]
I know that J!4 is still all in development but would like to suggest to consider to make the backend menu more useable that it is now.

Maybe something like this:

http://demos.getbootstrapkit.com/dynamic/portlets.html

Submenus expands down instead of sidebar offset. Especially when the mainmenu is collapsed.

**Comment by Shazrina1994** [comment]
as i am new to Joomla may I know what is J!4 stated there? is it new version?

**Comment by ghost** [comment]
@Shazrina1994 please look at https://developer.joomla.org/roadmap.html#4, thanks.

**Comment by frogydiak** [comment]
Brian, why close without even commenting? I'll take a comment No if you think you already love Atum as it is now, but closing it without saying anything?

**Comment by brianteeman** [comment]
Sorry I closed the wrong issue.

**Comment by C-Lodder** [comment]
@frogydiak we're still investigating/discussing the backend sidebar menu. It was originally a collapsible menu but has now been revamped 3 times since then. Every approach we go use has some form of a downside unfortunately, such as accessibility, mobile experience, or general UX.

We did discuss reverting back to the collapsible menu, however a final decision wasn't made.

@ciar4n What are you thoughts on this? As you know, I was always a fan of the accordion as it was easy to make accessible and didn't require any changes for mobile.

**Comment by ciar4n** [comment]
@C-Lodder At this stage I'm ok with that. Accordion is the more common and probably more widely accepted behavior for the sidebar.

**Comment by brianteeman** [comment]
I am going to close this for now. Lets wait until the new admin template being developed here https://github.com/joomla/40-backend-template has been merged
