### ISSUE TITLE
[4.0] Offline page a little broken

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17426]
### Steps to reproduce the issue

In the Global Configuration, set the site to `offline`

### Screenshot

![screeny](https://user-images.githubusercontent.com/2019801/29003263-685b2c7e-7aab-11e7-8241-b3f0b7c7d6bc.png)

### Additional comments

When fixing, the `offline.css` needs to be made a SCSS file and compiled properly through grunt.

**Comment by C-Lodder** [comment]
@ciar4n do you want me to center this with flex?

**Comment by ciar4n** [comment]
@C-Lodder The issue here is this... https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/aurora/scss/blocks/_css-grid.scss#L6

Rather than applying display:grid to the `body` tag, I probably should have targeted a class instead. We can then just add the class to body tags that use CSS grid (https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/aurora/index.php#L79). No reason to use CSS grid for the offline page.

**Comment by ciar4n** [comment]
Pr created... #17453
