### ISSUE TITLE
Update Joomla! 3.6.5 to 3.7.4 with a postgresql database

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#17473]
### Steps to reproduce the issue
Update Joomla! 3.6.5 to 3.7.4 with a postgresql database.

### Expected result

* administrator/components/com_admin/sql/updates/postgresql/3.7.0-2016-11-21.sql
ALTER TABLE "#__languages" DROP CONSTRAINT "#__languages_idx_image";

* administrator/components/com_admin/sql/updates/postgresql/3.7.0-2016-11-19.sql
ALTER TABLE "#__menu_types" ADD COLUMN "client_id" int DEFAULT 0 NOT NULL;

* Execute manually administrator/components/com_admin/sql/updates/postgresql/3.7.0-2017-01-17.sql
with the correct prefix of your tables.

### Actual result

* administrator/components/com_admin/sql/updates/postgresql/3.7.0-2016-11-21.sql
ALTER TABLE "#__languages" DROP CONSTRAINT "#__idx_image";

* administrator/components/com_admin/sql/updates/postgresql/3.7.0-2016-11-19.sql
ALTER TABLE "#__menu_types" ADD "client_id" int DEFAULT 0 NOT NULL;

* administrator/components/com_admin/sql/updates/postgresql/3.7.0-2017-01-17.sql doesn't execute during the update process.

**Comment by alikon** [comment]
this pr  #17499 fix the issues described here 
i've found just one more  upgrading fixed with #17505

**Comment by ghost** [comment]
closed as having Pull Request #17499<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17473">issues.joomla.org/tracker/joomla-cms/17473</a>.</sub>

**Comment by twister65** [comment]
administrator/components/com_admin/sql/updates/postgresql/3.7.0-2017-01-17.sql is not yet launched during the upgrade process. Therefore, you don't have the complete component menu in the administration panel.
You have to resolve this bug, before closing the issue.
Thanks.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17473">issues.joomla.org/tracker/joomla-cms/17473</a>.</sub>

**Comment by wojsmol** [comment]
@richard67 Please look at https://github.com/joomla/joomla-cms/issues/17473#issuecomment-321987509

**Comment by richard67** [comment]
@twister65 What means "is not yet launched"? Does it mean the script is not executed because the update breaks with the SQL errors in the scripts being executed before it? Or does it mean the postgresql/3.7.0-2017-01-17.sql is being executed but fails because of errors in this script? You can easily find out by checking the SQL statements being logged in administrator/logs/joomla_update.php. And have you tested both PRs mentioned in @alikon 's [comment above](https://github.com/joomla/joomla-cms/issues/17473#issuecomment-321968497) together?

@wojsmol Why do you ask me? Do you think the postgresql/3.7.0-2017-01-17.sql which I once had modified has an error?

**Comment by richard67** [comment]
I just checked: The script postgresql/3.7.0-2017-01-17.sql fails if the column client_id in table #__menu_types does not exist yet. This is the case if the script postgresql/3.7.0-2016-11-19.sql has failed to run before. But with PR #17499 this should be fixed and both should run.

**Comment by richard67** [comment]
With PR #17499 this **is** fixed and both **do** run, I just tested.

**Comment by richard67** [comment]
@twister65 Or did you maybe expect the statements in 3.7.0-2017-01-17.sql to be run by the database fixer after a failed update? That will not be the case because the database fixer does not handle INSERT, UPDATE or DELETE statements, that's a known problem. So for a test you have to download a 3.7.4 update package, unzip it, exchange the files modified by PR #17499 by those from the PR, then zip it again and do the Joomla Update on the "Upload & Update" tab of the Joomla Update view. You will then find that there is another SQL error happening in a script after 3.7.0-2017-01-17.sql, see PR #17505 . But the 3.7.0-2017-01-17.sql will have executed in that test. In the same way you then can test PR #17505 .

**Comment by twister65** [comment]
Your are right, Richard67, the tree of my archive file was incorrect.
I've tested it again with the PR #17505 and  #17499, and It's working now.
Therefore, you can close this issue.
Regards.

**Comment by brianteeman** [comment]
Closed as requested

**Comment by richard67** [comment]
@twister65 If you have tested with PR #17505 , could you set the test result to success using the "test this" button in the issue tracker [https://issues.joomla.org/tracker/joomla-cms/17505](https://issues.joomla.org/tracker/joomla-cms/17505 "https://issues.joomla.org/tracker/joomla-cms/17505") ?

@alikon Do you think you find time to you test @twister65 ' s PR #17499 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17473">issues.joomla.org/tracker/joomla-cms/17473</a>.</sub>

**Comment by wojsmol** [comment]
@richard67 Thanks for checking this 😄
