### ISSUE TITLE
[4.0] Minify some calendar files

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17554]
The following files need to be minified and committed to the CMS:

> media/system/js/fields/calendar-locales/date/jalali/date-helper.js
> media/system/js/fields/calendar.js

**Comment by brianteeman** [comment]
They are in staging so maybe these just need to be merged into j4 by @wilsonge

**Comment by C-Lodder** [comment]
we use Grunt to minify them as the naming conventions differ from J3. Perhaps the uncompressed files got merged a while back and nobody has minified them since

**Comment by dgrammatiko** [comment]
@C-Lodder @brianteeman should be grunt, because these files are in a deeper directory

**Comment by wilsonge** [comment]
Just bear with me. It's just an intermediate state whilst I'm merging staging into 4 (I did it in two parts starting with the 3.7.4 tag). Will be fixed with the next round of merging in staging, where I've already fixed this by updating the media resources which I forgot to do last time before I pushed it up

**Comment by C-Lodder** [comment]
Closing as duplicate of: https://github.com/joomla/joomla-cms/issues/17550
