### ISSUE TITLE
Joomla 3.7.5 configuration file not created

### ISSUE THREAD

**Issue by clx81** [joomla/joomla-cms#17590]
### Steps to reproduce the issue
Install on a server with NGINX 1.11 - PHP 7.0.16 & MARIABD10 (port 3307). Joomla 3.7.5 accept now the database 127.0..0.1:3307 and create the tables. After that come back to the step 3 (overview), the configuration file is not created !

### System information (as much as possible)
Synology DS3612

**Comment by pe7er** [comment]
I have a feeling that this issue is not Joomla related but Linux permissions (owner/group) related.

Under what user does Nginx run? Is it "www-data"?

How did you upload the Joomla files? What Linux permissions (owner/group) do the Joomla files/directories have?

Could you test this issue with an older Joomla version?

**Comment by brianteeman** [comment]
I am closing this at this time - if you still have problems then please use the forum for support https://forum.joomla.org
