### ISSUE TITLE
Joomla update reminder points to previous version

### ISSUE THREAD

**Issue by nfhopmike** [joomla/joomla-cms#17605]
Today I received an update reminder generated by the Joomla Update plugin which points to a previous version - 
see text from email:

Your site has discovered that there is an updated version of Joomla! available for download.

Joomla! version currently installed:        3.7.5
Joomla! version available for installation: 3.7.4

This email is sent to you by your site to remind you of this fact

This would appear to be a bug in Joomla Update plugin

**Comment by SactoBob** [comment]
I think this happens when Joomla is updated via 3rd party auto-updaters. IE, softaculous updated about 30 of my Joomla sites. I've gotten emails like this for just about every one of them over the past 8 hrs. The 4 or 5 I manually did while in the back-end did not send anything. Is softaculous missing something I wonder? Even so, com_joomlaupdate should be smart enough to recognize this. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17605">issues.joomla.org/tracker/joomla-cms/17605</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
