### ISSUE TITLE
[4.0] Dropdown in different positions

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17633]
On `com_menus` and `com_modules`, the dropdown to switch client is in different positions:

- `com_menus`: next to search input
- `com_modules`: floated to the left

The markup seems to be a little different

**Comment by C-Lodder** [comment]
com_menus has a layout override for the search tools, which can probably be removed.

**Comment by wilsonge** [comment]
Fixed with b2de61d45ba6d208168d43d41526bf3676f28b77

**Comment by C-Lodder** [comment]
Not, it wasn't, hence the issue.

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/commit/b2de61d45ba6d208168d43d41526bf3676f28b77
solves the styling issue properly. :)


In fact I had found out where the issue came from.
I could solve it easily when we have only one `selectorFieldName` as used in modules and templates.
I.e. I could solve it for Menus Manager by simplifying the override and using
`				<?php echo JLayoutHelper::render('joomla.searchtools.default', array('view' => $this, 'options' => array('filterButton' => false,'showSelector' => true, 'selectorFieldName' => 'client_id'))); ?>`
in the default view.
Screenshot taken before @wilsonge commit
![screen shot 2017-08-20 at 12 35 16](https://user-images.githubusercontent.com/869724/29494144-120e6f3a-85a4-11e7-8e39-b83732690195.png)

But for menu items we have 2 filters: `menutype` and `client_id` and I don't see how we can have multiple `selectorFieldName` in searchtools selector.

If someone has an idea for the future, that would be nice.
