### ISSUE TITLE
Feature Request: Filter for costumizable system plugins

### ISSUE THREAD

**Issue by hacki65** [joomla/joomla-cms#17704]
Some plugins has internal settings e.g. TinyMCE Editor, other plugins like "Button Readmore" has no settings available.

My request is a filter for the plugin list where it is possible only these plugins with setups to display.
Another way would be component that can manage all customizable plugins.

Greetz hacki65

**Comment by ghost** [comment]
can someone please answer on this Feature Request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17704">issues.joomla.org/tracker/joomla-cms/17704</a>.</sub>

**Comment by brianteeman** [comment]
The only way I can think of to do this would be to query the db to see if the params field was empty. However that wont always work on a new plugin that has not had any settings configured yet. There isnt any other way to determine if a plugin has settings

**Comment by mbabker** [comment]
A database query wouldn't be reliable for exactly the reasons you've said.  The only way to really do this efficiently is to parse the XML manifests of the plugins at runtime.  But then we run into a problem of being able to build the database queries and associated UI display (especially as it relates to filters and pagination) so that everything displays correctly as you try to merge filesystem and database data together.  So there's a part of me that leans toward "won't fix" on this just because the logistics behind it might be too complex to do efficiently without some other API changes.

**Comment by brianteeman** [comment]
I am with the wont fix view. Parsing the manifests at runtime could be a performance nightmare as well. Have you seen how many plugins you end up with if you install hikashop, acymailing and seblod
