### ISSUE TITLE
[3.9] Pre Update Checker why using hardcoded database version check?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#17871]
### Steps to reproduce the issue

The pre Update checker uses a hardcoded database (version) check?
https://github.com/joomla/joomla-cms/blob/3.9-dev/administrator/components/com_joomlaupdate/models/default.php#L1215

### Expected result

Uses the `supported_databases` feature of the joomla update definitions. see: https://github.com/joomla/joomla-cms/pull/12355

### Actual result

users a hardcoded database (version) check
https://github.com/joomla/joomla-cms/blob/3.9-dev/administrator/components/com_joomlaupdate/models/default.php#L1215

### Additional comments

cc @SamuelSchepp, @Kev1n337, @DrDreave @wilsonge

**Comment by SamuelSchepp** [comment]
We had to hardcode this special case to be able to deliver a custom error message in case the old database version are not compatible with J! 4. (#17849). The current architecture of JUpdate does not allow us to retrieve the reason for "We can't find a download URL".

We can't use <code>supported_databases</code>, because we can't get this information in case of non-compatibility.

My suggestion: Revert #17849 and remove the databasechecks from #17742. Then re-structure JUpdate to allow more than one error case.

@roland-d @icampus @brianteeman

**Comment by roland-d** [comment]
@zero-24 I think to have this hardcoded isn't a problem because we don't remove database support so often. This is rather a unique case. To go through the hassle of making it dynamic for what purpose? That one day we may remove PostgreSQL?

I think we shouldn't spend time more time on this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17871">issues.joomla.org/tracker/joomla-cms/17871</a>.</sub>
