### ISSUE TITLE
Uninitialized string offset: 0 in  ./libraries/joomla/application/web.php

### ISSUE THREAD

**Issue by Quadratica** [joomla/joomla-cms#17959]
### Steps to reproduce the issue

1. Active SEO Settings, only "SEF" & "Use URL Rewriting" option.

2. Disable plugin "System - Language Filter"

3. Install and enable (Artio) JoomSEF 

### Expected result
Page is displayed correctly

### Actual result
I get this error:
Notice: Uninitialized string offset: 0 in ".../libraries/joomla/application/web.php"

### System information (as much as possible)
Joomla! 3.7.5
PHP 5.6
MySql 5.7.19

### Additional comments

![30552447-40ef7608-9c9e-11e7-947b-278b53f4b864](https://user-images.githubusercontent.com/1607696/30553364-5076eb3a-9ca1-11e7-8de0-e28abd707c7c.png)

**Comment by Quadratica** [comment]
I propose this simple fix.

web.php, Line 520

NOW
```
// We just need the prefix since we have a path relative to the root.	
if ($url[0] == '/')
{
    $url = $prefix . $url;
}
```

AFTER
```
// We just need the prefix since we have a path relative to the root.
if( isset($url[0])  && ($url[0] == '/') )
{
	$url = $prefix . $url;
}
```

**Comment by Quadratica** [comment]
Are you ok for a pull request ? (See code Above)

**Comment by ggppdk** [comment]
The fact that an error is thrown there
does not mean that the code has some bug
(unless you can prove that a valid usage of the API is made)

Possibly (Artio) JoomSEF is overriding JUri class or something similar

Try using latest version of the extension, if you are doing this already,
- then report this issue to the author of the extension

Also possibly this notice can be safely ignored,
-- i say the above since the author of the extension has not made a fix for it
and since author claims extension is compatible with J3.7.5

so can try to set error_reporting in Joomla global configuration to "system default" (it is recommeded not to print notices/warnings/errors in live sites)

**Comment by Quadratica** [comment]
@ ggppdk

Thx, i've already reported the issue to the owner.

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17959">issues.joomla.org/tracker/joomla-cms/17959</a>.</sub>
