### ISSUE TITLE
Application Instantiation Error in src/Factory.php 3.8

### ISSUE THREAD

**Issue by nnerijuss** [joomla/joomla-cms#17990]
# Steps to reproduce the issue
Project moved from dev to production server

# Actual result
Message: Application Instantiation Error
File: /mnt/c/local-dev/public_html/itsolutions/euroguidance_network/web/libraries/src/Factory.php
Line: 137

# System information (as much as possible)
apache2, php 7.1.9, ubuntu16.04.1

**Comment by mbabker** [comment]
Unfortunately that's not going to be enough to see why you're getting that message.

All it's telling us is that a call to `Joomla\CMS\Factory::getApplication()` is failing because `Joomla\CMS\Factory::$application` hasn't been set (or someone unset it in a really odd twist) and the call to `getApplication()` doesn't have a parameter to attempt to load an application subclass.

**Comment by nnerijuss** [comment]
It is totally fresh joomla 3.7 updated to 3.8 and moved to production. Very strange...

**Comment by FabriceFRANK** [comment]
Same issue, got a website working on a local server, and once uploaded, got the same error, on site and admin, tried to change template, disabled extensions, still got it anyhow<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17990">issues.joomla.org/tracker/joomla-cms/17990</a>.</sub>

**Comment by ghost** [comment]
@FabriceFRANK Please ask help on the [forums](https://forum.joomla.org). This repository concerns in first Place Joomla coding.
