### ISSUE TITLE
update github.com/joomla/joomla-cms/releases ?

### ISSUE THREAD

**Issue by CEWebDesign** [joomla/joomla-cms#18051]
### Steps to reproduce the issue
Just asking if https://github.com/joomla/joomla-cms/releases is up to date?

### Expected result
Latest release Joomla 3.8.0

### Actual result
Latest release Joomla 3.7.5

**Comment by wojsmol** [comment]
pinging @mbabker on this.

**Comment by PhilETaylor** [comment]
> Just asking if https://github.com/joomla/joomla-cms/releases is up to date?

No its not, and its not the official place to be downloading anymore - try https://downloads.joomla.org/

Im sure @mbabker will update it once he gets a moment

**Comment by mbabker** [comment]
I don't have the source packages on my workstation at the office and I've stayed kind of distracted the last couple of days after getting home from work, so I just keep forgetting to publish it here on GitHub (and update the Docker image, and finish the API site updates, and who knows what else).

So if I remember, I'll do it tonight.  Otherwise, just keep nudging and I'll get to it eventually.

FWIW, if you're doing something where you programmatically need release information, use the downloads site's API (documented at https://downloads.joomla.org/api-docs/).

**Comment by mbabker** [comment]
Added.
