### ISSUE TITLE
System ignores 'joomla.form.renderfield' layout on override in a template

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#18084]
### Steps to reproduce the issue
- Create in your default template a file '/templates/YOURTEMPLATE/html/layouts/joomla/form/renderfield.php'
- Remove anything in that file and put word "TEST"
- Open any front-end form using Joomla\CMS\Form\Form (for example contact form in com_contact)

### Expected result
Form inputs replaced with word TEST

### Actual result
Nothing changed. Even changing the content of default layout (/layouts/joomla/form/renderfield.php) does nothing.

### System information (as much as possible)
Joomla 3.8, PHP 7

**Comment by eshiol** [comment]
That because the include paths array is:
```
templates/<template>/html/layouts/<component>
components/<component>/layouts
templates/<template>/html/layouts
layouts
```
and `com_contact` has the own `renderfield.php` file
`components/com_contact/layouts/joomla/form/renderfield.php`

if you want to overrire the renderfield of the component com_contact you have to put the file  renderfield.php into the folder
`templates/<template>/html/layouts/com_contact/joomla/form`

**Comment by artur-stepien** [comment]
And why it is separated? It looks like a dirty fix for something that core would also be affected (or would need). Its against DRY principle in my opinion.

**Comment by brianteeman** [comment]
As it says in the code this is the reason why com-contact has a custom renderfield https://github.com/joomla/joomla-cms/pull/8473

I am closing this as the reported issue has been answered by @eshiol
