### ISSUE TITLE
Broken channel link in Tagged Items RSS feed

### ISSUE THREAD

**Issue by dBarboni** [joomla/joomla-cms#18249]
### Steps to reproduce the issue
1. Create an article. Give it a Tag.
2. Create a menu item of type Tags->Tagged Items. Select the tag you added in step 1.
3. Navigate to your new menu item and add ?format=feed&type=rss to the end of the URL to view the RSS feed.
4. Look at the value of the channel->link element. Note that "/Array" has been added to the URL. The channel link results in a 404 if accessed.

### Expected result
The link should point back to your menu item.

### Actual result
The link points back to the menu item but with "/Array" appended to the URL.

### System information (as much as possible)
Joomla 3.8.1
PHP 5.6.31

### Additional comments
Occurs on a clean install of 3.8.1.

**Comment by brianteeman** [comment]
I can confirm this

**Comment by EmilMassey** [comment]
Tagged items' links are incorrect too. They point to 404 page. For example when site's default view is the category, the link looks like: http://example.com/?id=218:some-alias.

The problem is in the way we create link to an item in tag model. For com_content this won't work, because the router (legacy, I didn't check the new advanced router) requires  `catid` parameter and we don't know article's category ID.

https://github.com/joomla/joomla-cms/blob/20e0335f2c02ac2e34a7e5a3180ab523a43137a9/components/com_tags/models/tag.php#L92-L94

As the Tags Component is supposed to work with any component, it is not possible to create link the same way for every item type. I think we should somehow allow developers to implement their own method to create items' links.

At the moment, tag feed is broken and useless. :( I hope we'll fix this ASAP, because this functionality is quite important on website I develop.

**Comment by ghost** [comment]
@EmilMassey can you provide a Pull Request so we can Test and fix ASAP?

**Comment by EmilMassey** [comment]
@franz-wohlkoenig Unfortunately, right now I don't even know where to begin. To be honest this is the first time I saw Tag Component's code and I need some time to get to know it before I change anything in it.

**Comment by alschaeffer** [comment]
I have the same problem. I don't understand, why you have to edit the category in the link.

Instead of 
http://example.com/?id=218:some-alias
this link would work for me
http://example.com/218-some-alias

**Comment by SharkyKZ** [comment]
@EmilMassey @alschaeffer for your issue see #20723.

**Comment by ghost** [comment]
closed as having Pull Request #20723

**Comment by SharkyKZ** [comment]
@franz-wohlkoenig reopen this please. #20723 only solves the issue described in the comments.

**Comment by ghost** [comment]
Reopened as stated above.

**Comment by wilsonge** [comment]
Closed as we have a PR with #21690
