### ISSUE TITLE
Duplicate tags at joomla 3.8.1

### ISSUE THREAD

**Issue by niaziblog** [joomla/joomla-cms#18363]
### Steps to reproduce the issue
i create menu for tag 
menu url for tag is : yoursite.com/tag/tag-name
but every tag show with 2 url
yoursite.com/tag/tagname
yoursite.com/tag/id

### Expected result
video for this problem link
http://bit.ly/2yxTjxE

### System information (as much as possible)
Joomla! Version | Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
-- | --
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
### Additional comments
please fix this problem

**Comment by csthomas** [comment]
The version with `yoursite.com/tag/id-tagname` (or unofficial `yoursite.com/tag/id`) comes from "old routing" before PR https://github.com/joomla/joomla-cms/pull/11166, which was added in Joomla 3.7.0.

`yoursite.com/tag/tagname` is supported from J3.7.0.

1. Joomla could add a button in component tags to disable "old routing" and returns 404, 
    * maybe modern routing could be implemented
2. Or someone can add canonical URLs as similar as in #18341

**Comment by eSilverStrike** [comment]
We should be adding canonical URLs for tags (and for most content Joomla displays). Joomla has created a big SEO mess by allowing the same content to be accessed by different URLs.

I was hoping this would be fixed with the new routing system and of course it was not. It's nice they added the ability to remove ids from URLs but for existing sites to enable this feature, it creates duplicate content. Google does not like duplicate content and may rank the pages lower. For more information see: https://support.google.com/webmasters/answer/139066?hl=en

**Comment by ghost** [comment]
closed as having Pull Request #18407
