### ISSUE TITLE
Add SVG support by default in Media Manager.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#18373]
### Steps to reproduce the issue
Try uploading a SVG file via Media Manager

### Expected result
Uploads Fails even after adding SVG MIME type and extension under options.

### Actual result
"Possible IE XSS Attack found."

### System information (as much as possible)
Joomla 3.8.1 + PHP 7.0

**Comment by mbabker** [comment]
Already open/discussed in several other items - https://github.com/joomla/joomla-cms/issues?utf8=%E2%9C%93&q=svg%20

Long and short though is because of the nature of SVG files there are additional security precautions that have to be taken to safely allow those files to be uploaded/used and that's why the support is not there at this time.

**Comment by chetanmadaan** [comment]
My apologies for not searching for posting.

Thank you.
