### ISSUE TITLE
Joomla Latest Zip Link

### ISSUE THREAD

**Issue by dieskim** [joomla/joomla-cms#18401]
Hi,

It would be great if we could have a URL location that has the LATEST ZIP file.

For example wordpress does this at https://wordpress.org/latest.zip

When writing scripts to install Joomla on a new server there is no easy way to get the latest package 

What we have had to do for now is highlighted here

https://stackoverflow.com/questions/46844122/joomla-get-latest-version-zip-link-scrip-install/46906676#46906676

Is there any way Joomla.org could do this? 

If not we might be able to do this on a server of our own and provide the link to users but that seems silly as this should really be something Joomla should do?

**Comment by brianteeman** [comment]
Probably the easiest way to script this would be http://www.starkandwayne.com/blog/how-to-download-the-latest-release-from-github/

Sorry I dont know ansible

**Comment by dieskim** [comment]
Yes this was suggested to get the latest via https://github.com/joomla/joomla-cms/archive/staging.zip - but this gets the latest staging zip and not the stable release zip. That would be good if we could make use of the built in git way of doing this.

We could then just make joomla.org/latest.zip point to the git latest zip

**Comment by ghost** [comment]
@dieskim you really mean "Build 3.4"?

**Comment by dieskim** [comment]
Another good read on how to do this - https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo

**Comment by mbabker** [comment]
We wouldn't want to do a `https://www.joomla.org/latest.zip` as that involves redirects across subdomains and it would actually require updating said redirect manually with each release unless we just want to serve the ZIP package direct from the main domain without using our AWS resources and inherently losing some of the analytics we can gather by serving through the downloads site.

You can scrape https://downloads.joomla.org/latest to grab package URLs.  Another option is making use of the downloads site API to grab the latest version number for a branch and our use of predictable URLs for each release/package (i.e. translate the data from https://downloads.joomla.org/api/v1/latest/cms to be able to fetch a package through either https://downloads.joomla.org/cms/joomla3/3-8-1/joomla_3-8-1-stable-full_package-zip?format=zip or https://downloads.joomla.org/cms/joomla3/3-8-1/Joomla_3.8.1-Stable-Full_Package.zip as we've modified the router to allow either the Joomla generated URIs or the raw file names to work; https://github.com/joomla/docker-joomla/blob/master/update.php actually does something like this for our Docker image).

And of course there's using the GitHub API to fetch the latest release and parsing out that response to grab the desired package.

In general, a `latest.zip` URL really only helps ease of scripting a download and doesn't have much practical benefit the way we've crafted our site structures, but there are options to get the data since everything is predictable and consistent.

**Comment by brianteeman** [comment]
I am closing this here as it doesnt relate to the core code and is more an infrastructure question which you can raise if you want at https://github.com/joomla/joomla-websites/issues/new?title=[jdown]%20&body=Please%20describe%20the%20problem%20or%20your%20issue
