### ISSUE TITLE
[4.0] Cannot Send Test Mail

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18596]
### Steps to reproduce the issue

Global Config -> Server -> Click Send Test Mail

### Expected result

Test Mail sent (or at least attempted) 

### Actual result

JS Error
![screen shot 2017-11-17 at 18 57 12](https://user-images.githubusercontent.com/400092/32963835-2591e4e0-cbc9-11e7-9723-741d10f0c1b9.png)

### System information (as much as possible)

Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by brianteeman** [comment]
iirc that flying-focus error is everywhere not just on this screen

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/commit/c50e9458ea196423a5f048d1ba903addde7491c4 may have fixed this. Please check again

**Comment by PhilETaylor** [comment]
button still does nothing in Alpha2

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/18722

**Comment by wilsonge** [comment]
This is still not fixed completely. The button now always gives a Session error. I think there's something wrong in the `Joomla.request` method, because despite options holding a valid json string, chrome see's the request data as being malformed in some way (note it's displayed as a bold string rather than as a nice request data variable like it is in 3.x - note i removed my email that whitespace is ok ;) )

<img width="987" alt="screen shot 2017-11-19 at 23 34 01" src="https://user-images.githubusercontent.com/1986000/32997268-5abf7340-cd85-11e7-8681-e828acd05f77.png">

**Comment by C-Lodder** [comment]
The hidden token input is being rendered, however `\JSession::checkToken('get')` is always returning false for some reason.

**Comment by C-Lodder** [comment]
Here is a PR: https://github.com/joomla/joomla-cms/pull/18779

However not sure if it's the correct approach.

**Comment by ghost** [comment]
closed as having Pull Request #18779
