### ISSUE TITLE
[4.0] Call me thick but what the heck... Advanced Permissions Report

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18686]
### Steps to reproduce the issue

Click Advanced Permissions Report  next to a user group

### Expected result

Something that is understandable to the average Joomla Super Admin

### Actual result

WTF is This - is this really what it should be like?

Is is missing somehting? 

There is a Legend at the bottom but none of those icons are displayed anywhere else.

![screen shot 2017-11-18 at 20 46 34](https://user-images.githubusercontent.com/400092/32984592-957e3c08-cca1-11e7-95e0-ca5ceed27e7f.png)

### Additional comments
@brianteeman

**Comment by brianteeman** [comment]
the answers to all your comments are yes something is missing and its blindingly obvious when you compare it to 3.x

**Comment by PhilETaylor** [comment]
ok so thats a bug in 4 then... :)

**Comment by wilsonge** [comment]
OK So I've added the columns back with https://github.com/joomla/joomla-cms/commit/7af4a1d31f3deba5c906d02632dcf4a4d049ab36 - that part was easy. However apparently this view is totally foobar'd because we are matching up the com_config descriptions with the permissions levels here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/models/debuguser.php#L85 we are now comparing integers (because there's some change in the db code somewhere) with empty strings (sometimes php notices depending as brian removed the description properties of all the actions).

So improvements but some major fixes to be done in develop and then merged through i think

**Comment by mbabker** [comment]
> we are now comparing integers (because there's some change in the db code somewhere) with empty strings

It's a side effect of the prepared statement support.  [`mysqli_stmt::bind_result`](https://secure.php.net/manual/en/mysqli-stmt.bind-result.php) can silently typecast bound variables, and the way our code is structured all query results will go through that method (because of the old mysqlnd problem).

**Comment by wilsonge** [comment]
> It's a side effect of the prepared statement support. mysqli_stmt::bind_result can silently typecast bound variables, and the way our code is structured all query results will go through that method (because of the old mysqlnd problem).

Cool. That needs documenting then

https://github.com/joomla/joomla-cms/pull/21188 Will fix the issue reported here (although will needing merging through 3.x to 4 once it's merged. So I'm going to close this as we have a PR
