### ISSUE TITLE
[4.0] Offsets separated by white space(s) are deprecated, use a comma (,) instead.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18724]
### Steps to reproduce the issue

Joomla 4 Alpha 2
Mouseover a popover e.g:

![screen recording 2017-11-19 at 07 29 pm](https://user-images.githubusercontent.com/400092/32994495-0b92df70-cd60-11e7-9fde-9779899507a3.gif)

### Expected result

No console messages

### Actual result

repeatedly
![screen shot 2017-11-19 at 19 30 17](https://user-images.githubusercontent.com/400092/32994497-17224a88-cd60-11e7-9c93-557ae5fbf0e0.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18724">issues.joomla.org/tracker/joomla-cms/18724</a>.</sub>

**Comment by amone4** [comment]
the error is generated because of the following line of code in bootstrap.bundle.js
`console.warn("Offsets separated by white space(s) are deprecated, use a comma (,) instead.")`

I don't really find any use of this line of code or any important error that this code might signify.
And removing it does solve the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18724">issues.joomla.org/tracker/joomla-cms/18724</a>.</sub>

**Comment by brianteeman** [comment]
deleting an error message is not a fix for removing the error - ever

**Comment by amone4** [comment]
Alright. A small change in bootstrap.php at line 259 solved it.

earlier:
	`$opt['offset']      = isset($params['offset']) ? $params['offset'] : '0 0';`
now:
	`$opt['offset']      = isset($params['offset']) ? $params['offset'] : '0,0';`
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18724">issues.joomla.org/tracker/joomla-cms/18724</a>.</sub>

**Comment by brianteeman** [comment]
Are you going to submit a pull request or do you expect someone else to do it (because thats not how it works)

**Comment by amone4** [comment]
I was waiting for a confirmation. Anyway, I've made a PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18724">issues.joomla.org/tracker/joomla-cms/18724</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #19975
