### ISSUE TITLE
[4.0] Idea: Force HTTPS Improvement "Change option to Yes/No"

### ISSUE THREAD

**Issue by conconnl** [joomla/joomla-cms#18758]
Nowadays there is no reason anymore to have a option to only force HTTPS on the Administrator or the entire site.
Especially with all the changes going on in the browsers; Warning if you don't use HTTPS, internet speed improvements (HTTP/2), free certificates and all the other things.

I want to suggest to change the current feature to a Yes and No option, which simply Force HTTPS for everything or nothing.

![function improvement](https://user-images.githubusercontent.com/11913918/33029077-f16f9fa8-ce17-11e7-941b-a16cc666f051.png)

**Comment by PhilETaylor** [comment]
Whats worse is that you can enable this, then if you dont have a SSL cert installed it will warn you, but still have the configuration enabled.. and just ignored...

**Comment by conconnl** [comment]
I can't code....., Do you have a code fix proposal for this?
I agree that it's needs to be fixed

**Comment by brianteeman** [comment]
@philetaylor I was checking your comment and its a bit weird. If you enabled the force option when you dont have a cert then you get the warning and you are correct the global config doesnt change. BUT after loading the front end of the site and then opening the config it has been corrected to say disabled

**Comment by Scrabble96** [comment]
Following on from @conconnl 's first comment, is there any reason not to have the default to https rather than non-https as surely the majority of sites must now run on SSL. With Let's Encrypt and others available free and perfectly suitable for smaller, non-ecommerce sites, there's no reason not to have even a basic SSL certificate installed.

**Comment by alikon** [comment]
maybe intranet sites  running under a firewall i guess

**Comment by HLeithner** [comment]
Normally you don't create a website in a public space instead many people use xmpp (or similar) for bootstrapping there sites. That means they use localhost for 127.0.0.1 as server name. You can't create an official certificate for this names, you would need to create you own certificate and allow it in the browser.

In my experience that will not be done my people setting up a website and move it later to a public webspace. Also you don't get no gain from it for localhost.

What maybe makes sense is to inform people on backend login that the site is not tls encrypted and they should find a way to do this.

But a default activation is a no go.

**Comment by brianteeman** [comment]
If a site is installed directly on a web server either by our install or the webhosts install then we can detect if the site is already running https

**Comment by HLeithner** [comment]
that's partly true because we can't guarantee that the certificate is valid for example.

But yes could be considered in the installer.

**Comment by brianteeman** [comment]
If its not valid and the site is being accessed by https then the validity of the certificate is not our issue.

This can not be done in the installer as many hosts have their own one click installer

**Comment by HLeithner** [comment]
then it's the job of the one click installer

**Comment by mbabker** [comment]
The Joomla installer should only be the minimum necessary to get the software running, putting feature configurations into the installer is problematic because of third party software like Softaculous which do not install Joomla using the core provided interface.

If you want something done after installation, adding some kind of "after install at first login" step is your most reliable option.  Otherwise, don't stuff things into the installation app that can't be relied on to always be available.

> then it's the job of the one click installer

Have a little respect for the ecosystem and understand that not every Joomla user installs Joomla the same way and that Joomla doesn't have the influence to force these vendors to change how they work.

**Comment by HLeithner** [comment]
that's the reason I wrote it could be mentioned on login, the installer or if you like a post installation notice would at least make sense. But doing it automatically/default is a bad idea, that's what I wanted to say.

**Comment by sjehuda** [comment]
> Normally you don't create a website in a public space instead many people use xmpp (or similar) for bootstrapping there sites. That means they use localhost for 127.0.0.1 as server name. You can't create an official certificate for this names, you would need to create you own certificate and allow it in the browser.

@HLeithner I am not sure I understand. May you elaborate on it?
