### ISSUE TITLE
[4.0] enhanced media manager

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#18763]
The new media manager is great !!!!!
i think we need 2 features
- "save as copy" button : when we rezize image we need to keep original image ... a simple save as copy can be good
- thumbmail generator after upload : it will be good if we can create thumbs / medium / small image after all upload ! like 
name_image.jpg,   
name_image_m.jpg 
name_image_t.jpg 
name_image_s.jpg
=> user can set image size in media manager options

**Comment by dgrammatiko** [comment]
@micker here is my personal opinion on your suggestions:

> "save as copy"

That should be the **default and only option** due to the fact that apache/nginx/whatever might heavily cache the static files (remote files are a different story...)

> thumbmail generator after upload

So I've created a free plugin (https://extensions.joomla.org/extensions/extension/photos-a-images/images/responsive-content-images/) to showcase my idea for image sizes/srcset etc...
I think something like that should be part of J4

And finally, since I'm part of the media manager group, I can reassure you that these two requests are on the radar of the team but the team is still considering all possible options...

PS there is a dedicated repo for the media manager: https://github.com/joomla-projects/media-manager-improvement so would be cool if you can close the issue here and open it (copy/paste) there

**Comment by micker** [comment]
ok here
https://github.com/joomla-projects/media-manager-improvement/issues/476

**Comment by dgrammatiko** [comment]
Thanks!
