### ISSUE TITLE
[4.0] Installation instructions don't exist.

### ISSUE THREAD

**Issue by Kevinjohn** [joomla/joomla-cms#18772]
### Steps to reproduce the issue
Readme.md Link to How to Install Joomla!4 gives a 404.

https://docs.joomla.org/J4.x:Installing_Joomla does not exist.
![screen shot 2017-11-21 at 08 37 05](https://user-images.githubusercontent.com/338422/33062434-35b24204-ce97-11e7-9603-378f1c0daaf5.png)

**Comment by brianteeman** [comment]
Thank you for your first issue report. :)

**Comment by ghost** [comment]
Good catch @Kevinjohn !
I think these pages will be created once the stable version is ready. At this point, there are no links from the Joomla.org website, since it links directly to the Github repository. I asked the Documentation team how this is handled, and if a temporary text is desirable.
https://www.joomla.org/announcements/release-news/5718-joomla-4-0-alpha-1-release.html

**Comment by MartijnMaandag** [comment]
I created a temporary page.

**Comment by ghost** [comment]
Thanks Martijn!

**Comment by brianteeman** [comment]
Closed
