### ISSUE TITLE
calendar.dateClicked param not found after Joomla 3.8.2 update

### ISSUE THREAD

**Issue by 80sPop** [joomla/joomla-cms#18978]
### Steps to reproduce the issue

for date picker pop-up, calendar.dateClicked no longer defined in javascript after Joomla 3.8.2 upgrade

### Expected result

calendar.dateClicked is true or false after clicking on date in pop-up.

### Actual result

ReferenceError: Calendar is not defined in Web Console

### System information (as much as possible)

Joomla 3.8.2

### Additional comments

calendar.js and calendar-setup.js no longer load on startup, and are replaced with calendar.min.js

**Comment by dgrammatiko** [comment]
Please share the code you are using!

**Comment by 80sPop** [comment]
The date picker displays fine, but calendar.dateClicked is undefined.

echo JHTML::calendar($pandate, 'pandate', 'pandateId', '%a, %b %e, %Y', array('onChange' => "onCalendarClick4()",'class' => 'calendar-less' ) );

<script type="text/javascript">

Calendar.setup({
   inputField  : "pandateId",			// ID of the input field
   ifFormat    : "%a, %b %e, %Y",		// the date format
   button      : "calendarImg",		// ID of the button
});

function onCalendarClick() {
   if ( calendar.dateClicked == true )
       /* do something */
} <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18978">issues.joomla.org/tracker/joomla-cms/18978</a>.</sub>

**Comment by Quy** [comment]
@videoCodec Try `cal.dateClicked`.

**Comment by Quy** [comment]
This is a coding error by the user and not in the core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18978">issues.joomla.org/tracker/joomla-cms/18978</a>.</sub>

**Comment by 80sPop** [comment]
@Quy cal.dateClicked is also undefined. So, I modified calendar.min.js (core hack) to keep the desired functionality my website had before the 3.8.2 update.

**Comment by chavab1** [comment]
I landed on here from this link [https://issues.joomla.org/tracker/joomla-cms/18469](url) because I'm having the same problem. The link points to this issue but I don't see how it's referencing anything about the original problem.

I'm running version 3.9.10 with the default template and I'm still getting the same results. The calendar popup is partially hidden below the browser bar. I fixed it by adding the margin-top style declaration, but I was wondering if this is going to be addressed.

Thanx

**Comment by drmenzelit** [comment]
@chavab1 this issue is closed. Can you please open a new issue and share code / screenshots with us?
You are using an oudated Joomla version, you should update to 3.9.24

**Comment by chavab1** [comment]
@drmenzelit Sorry about that. I thought of that but first I wanted to see if I missed something. Because it says that it's closed but I can't find where it mentions the fix. So I didn't want to open a new issue if in fact it has been take care of, and I just missed it.

BTW: I just updated to 3.9.24 and I still have the same issue.

I'll go ahead and open the new issue.

Thanx
