### ISSUE TITLE
[4.0] Edit menus on the front end

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#18989]
Enable the option in global config to enable editing modules AND menus in the front end on hover

Modules works but menus doesnt as no icon is shown

**Comment by C-Lodder** [comment]
Note to self - finish this: https://github.com/joomla/joomla-cms/pull/18786

**Comment by C-Lodder** [comment]
@brianteeman - I've just finished rewriting this script and it's ready to commit. Whilst I'm at it, in the Global Config, there are currently 3 options for **Mouse-over Edit Icons for**

1. Modules & Menus
2. Modules
3. None

I was thinking to change this to:

**Front-end module editing** (switcher)
- Off
- On

Simply because the menu IS a module and I can't see any reason to have modules but not menus. Would be nice to just simplify this too.

thoughts?

**Comment by brianteeman** [comment]
the menus option is very different to the modules option

**Comment by C-Lodder** [comment]
Is there anywhere where I can get more info on that?

**Comment by brianteeman** [comment]
You can try it in J3 ;)
or watch this video https://developer.joomla.org/cms/user-experience/610-jux-code-sprint-report.html

(note that was when there was only backend module editing - front end editing came later)

**Comment by brianteeman** [comment]
The reason why it doesnt work is in the frontediting.js
It is trying to
> // Get menu ItemId from the item-nnn class of the li element of the menu:

but it cant as in j4 the li element doesnt have that class
in fact it doesnt have a unique class which might be a problem if someone wants to target a link for additional styling etc which was no problem at all in j3
