### ISSUE TITLE
Feature request: Start Joomla in Safe Mode

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18990]
Is it possible to implement a function in Joomla, that disables EVERY 3rd party extension temporary to give the user the possibility to login in backend and check the issue / Update and enable again?

Something like safe mode on a mac?

**Comment by stutteringp0et** [comment]
The problem with that request is that in order to turn on a setting like that - you would have to be able to log into the site.

The only thing that could prevent login like that would be a plugin.  If you could log into your server with something like SSH or manipulate files via SFTP - you could do some directory swapping and achieve what you're asking for.

The only plugin you need to log into your site is the Authentication - Joomla plugin.  That means you could (temporarily) move every directory (except the authentication directory) out of the plugins directory to somewhere else.  When Joomla can't find a plugin - it just doesn't load it.  It's a silent operation.

If it turns out that the cause of your issue is an authentication plugin, you could further move (again, temporarily) all of the directories out of /plugins/authentication EXCEPT the joomla directory.  You would have, at that point, no plugins running except the Authentication - Joomla plugin.

**Comment by coolcat-creations** [comment]
Yes you would need to login, but you could have something like a checkmark or special login page to enable this function before loading the backend. I mean just like in a desktop operating system - there you need to login too. I don't mean only plugins but also extensions. 
Another approach would be to add an underscore in front of each 3rd party folder to temporary disable it. Then you don't have to move directories...

**Comment by simbus82** [comment]
Nice idea, many times i go to phpmyadmin to disable extensions (switching enabled value from 1 to 0) to see if all is ok. Maybe we need a particular custom backend url that let the core loads only "core plugin, module and extension", ignoring all others "enabled" extensions.

**Comment by brianteeman** [comment]
The only safe and secure method I can think of to enable such a mode would be similar to the root user option that can be added temporarily to the global config file

**Comment by mbabker** [comment]
This again requires a tracking functionality with a list of core extensions and IMO there is still no need to introduce this type of list.

**Comment by coolcat-creations** [comment]
Really? But we know what core is, no?

**Comment by mbabker** [comment]
We do when working from this repository.  An installed site has no knowledge of what is core and what is third party, and there really is no need for there to be this awareness.

**Comment by simbus82** [comment]
Uhm... so "padlock =! core extensions"?
![image](https://user-images.githubusercontent.com/1375730/33680576-5b1511e8-dac2-11e7-9c2c-041996a7b308.png)

**Comment by coolcat-creations** [comment]
It could be a lifesaver for a lot of siteowners when for example accidently upgrading Joomla with outdated extensions that break the backend. Then they could start in safemode, disable it, start in normal mode, update the stuff and be fine. Otherwise they have to go through a whole restoration process.

**Comment by mbabker** [comment]
No, "padlock is not core extensions".  That padlock indicates an extension is protected, basically meaning an extension cannot be disabled or uninstalled.

Even if you could boot into a safe mode, it would only be reliable for the backend.  The frontend would be terribly screwed over because that is going to be very coupled to the chosen template and a safe mode would disable that.

**Comment by brianteeman** [comment]
An extension can (and many do) set the padlock

**Comment by tonypartridge** [comment]
I actually think this is a good idea, all we need is a list of all core extensions, modules and plugins. Disable all which are none core when entering safe mode. Once finished you can click disable Debug mode which enables all which were disabled. Any which no longer exist are skipped.

**Comment by tonypartridge** [comment]
Disable safe mode* sorry was reading something else at the same time.

**Comment by andrepereiradasilva** [comment]
This? https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Extension/ExtensionHelper.php#L30

**Comment by andrepereiradasilva** [comment]
And reggarding locked extensions see this PR https://github.com/joomla/joomla-cms/pull/17219

**Comment by brianteeman** [comment]
This is not going to be possible. Well it is possible but it wont achieve what you are looking to achieve.

Let me give a simple example of why "safe mode" will actually kill your site instead of helping you to debug it. 

I have a site that uses a non core authorisation plugin. I start in safe mode so that only core extensions are used (if they are enabled) and now I can not log in at all to even see what the issue was that I was trying to fix.

That's just a really simple example of why this can never work
