### ISSUE TITLE
Cookie Control

### ISSUE THREAD

**Issue by ozipom** [joomla/joomla-cms#19011]
Joomla 4 and Joomla 3.8.3 dont have Cookie Alert Module, compoment or plugin!

This type of module should be as a core module or official extension

**Comment by C-Lodder** [comment]
Why should it be part of core when there are 3rd party extensions that already do the job very well?

**Comment by rdeutz** [comment]
Our goal is to keep the core light, this seems to be something that doesn't need to be a core extension

**Comment by ozipom** [comment]
If we think that Joomla should not be used in Europe then we should follow @rdeutz advise

**Comment by ozipom** [comment]
@C-Lodder which extension can do cookie comtrol very well? As far as I see these extensions are outdated or aren't available.

@rdeutz the issue is not soved, please reopen it

**Comment by Bakual** [comment]
There is a category named "Cookie Control" on JED: https://extensions.joomla.org/category/site-management/cookie-control/
Pick one from the 35 available extensions.

**Comment by ozipom** [comment]
@Bakual As far as I see these Joomla extensions are outdated or aren't available. Thats why I asked @C-Lodder which Joomla extension can do cookie control very well?

**Comment by rdeutz** [comment]
How many did you check? This one https://extensions.joomla.org/extensions/extension/site-management/cookie-control/eu-e-privacy-directive/ looks good to me.

**Comment by Bakual** [comment]
What do you mean with "outdated"? Last updated a year ago doesn't mean it is outdated. It just means Joomla held its B/C promise and the plugin/module still works fine.

**Comment by alikon** [comment]
> European laws require that digital publishers give visitors to their sites information about their use of cookies and other forms of local storage. In many cases these laws also require that consent be obtained. 

despite we have 3dp extensions for that, IMHO should be provided by core

**Comment by ozipom** [comment]
@Bakual These 35 Joomla extensions are 2 years old and unsuported or unawailable.

**Comment by ozipom** [comment]
@rdeutz this extension discloses Joomla version, it was good, but now seems unsuported

**Comment by rdeutz** [comment]
Installed it, worked. You might be confused with the message "This extension does NOT implement the Joomla! Update System". This means that you have to do updates of the extension different, it doesn't mean it is "unsupported". There is also documentation here: https://www.richeyweb.com/documentation/10-eu-e-privacy-directive

Anyway, as I said our goal is a lighter core and this will not be something we will include in core. People can have another optinion on the matter but we follow the light core strategy now for years and till we change the strategy this will not be included.

Please use a forum for support, I will lock the conversation because there isn't more to discuss.
