### ISSUE TITLE
Main Joomla issue in Europe 

### ISSUE THREAD

**Issue by ozipom** [joomla/joomla-cms#19021]
Main Joomla issues in Europe and @rdeutz in my opinion tries to hide it seems strange to me but if majority of joomla developers thinks that jooma should not be used in Europe thats ok

I won't rise this issue anymore, but better use another cms if thats the case

if joomla policy is to ignore and hide major issues , I hope this is @rdeutz personal issue

https://github.com/joomla/joomla-cms/issues/19011

https://github.com/joomla/joomla-cms/issues/19020

**Comment by rdeutz** [comment]
We are not hiding something, Joomla is used on tausends of sites in the EU and this doesn't seems to be a problem. I already said that our goal is to have a light core. There are many options and if you followed the advice we have given, you cloud have asked in a forum of your choice and the problem would haven been sorted out.

This is only a major issue for you and the reason is that you are not following the advice you got. 

As promised I have blocked you from the repo, this gives you time to find a solution or a different CMS.
