### ISSUE TITLE
subs.php has 3 missing final class

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#19139]
### Steps to reproduce the issue
php build/stubGenerator.php

then open: stubs.php

class japplicationsite extends \Joomla\CMS\Application\SiteApplication {}
class jhelperusergroups extends \Joomla\CMS\Helper\UserGroupsHelper {}
class jversion extends \Joomla\CMS\Version {}

### Expected result

No errors

### Actual result

Class may not inherit from final class.

### Additional comments

cc @mbabker

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/19138 adds the final keywords for those classes.

FWIW, that IDE error is going to always exist in the stubs file because we have to extend the final classes to make the alias mapping work.  No real way around it except excluding final classes from the stubs, which kind of defeats the point of having it to begin with.
