### ISSUE TITLE
[4.0] Use namespaced classes

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19298]
Use the namespaced classes throughout the rest of the CMS

**Directories:**
- [ ] installation
- [x] libraries
- [x] libraries/fields
- [x] components
- [x] plugins
- [x] modules
- [x] layouts
- [x] administrator/components
- [x] administrator/modules

@mbabker do we need to do the `tests` directory too?

**Comment by anuragteapot** [comment]
@C-Lodder can I do this for plugins.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19298">issues.joomla.org/tracker/joomla-cms/19298</a>.</sub>

**Comment by C-Lodder** [comment]
@Anu1601CS sure feel free

**Comment by anuragteapot** [comment]
@C-Lodder please mark plugins done! 
Next, I am working with administrator/components :)

**Comment by C-Lodder** [comment]
Please hold off on that for now. Lets wait till staging has been merged into 4.0-dev. Because it's a big task, we'll separate it and I'll take half of it to take some of the work load from you

**Comment by anuragteapot** [comment]
Ok, Thanks

**Comment by dgrammatiko** [comment]
@C-Lodder can you add the fields in this list? PR: https://github.com/joomla/joomla-cms/pull/19297

**Comment by dgrammatiko** [comment]
I mean break down Libraries to it's individual packages, will be easier for anyone to pick any one and do it, otherwise this folder is huge and will be quite a big PR to review or create it in the first place

**Comment by KarstenFrostholm** [comment]
Hi

I have written a code that can change class names and find namespace.

I have attached the code, a log file, and an example of a migration. (code from sonday)

Use php version 7.1 or newer.

In ConvertClassAndNamespaceJoomla.php find:
$basePathSource = "C:\\xampp72\\joomla4alfa\\htdocs";
$basePathConverted = "C:\\xampp72\\joomla4alfa\\converted";
and adapt as needed

A clean of $basePathConverted path will only be performed if it is not the same as $basePathSource.

Use $basePathConverted with the same value as $basePathSource, and $basePathSource will update.
 
run: php ConvertClassAndNamespaceJoomla.php> Migration.log
The program can be run several times if you wish.

I have not worked with liberies since I'm not sure what is wanted here.
Come up with an explanation and I will try.

Should there be any need for customization or more micration features, say to.
Hope that the program is som thing Joomla can benefit from.

with best regards
Karsten F.


[Migration.zip](https://github.com/joomla/joomla-cms/files/1682624/Migration.zip) (2MByte)

**Comment by KarstenFrostholm** [comment]
Sorry I do not write clearer.

This code can correct / modify all code included in joomla 4, minus libaryes.

It can be used to perform a quick shift or customization of * .PHP and installation.xml on components.
I deliver this program, in this way, as I'm not sure of the sequence that you would like this change to be done in.

It is performed on a local copy of the development branch of joomla 4.

A copy of all the changed files is created in a folder of the same structure.
A log file with a list is written the changed files along with the number of changes per file.

Hope this created some clarity about what I'm trying to contribute.

I am unfortunately not used to working with git as software reposotory.
I also realize that I do not just make 1200 files in a comit.

It can then be used by those who are deeply involved.

It is meant as a fellowship help. I'm working on this kind of migration for the last many years. One is to write this kind of code, another is to know when you're ready to use.

Yours sincerely
Karsten

**Comment by brianteeman** [comment]
@wilsonge is this meta issue being updated and is it still relevant

**Comment by laoneo** [comment]
Yes, it is, as long as we have code like [\JFactory::](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Access/Access.php#L300) in our code base.

**Comment by brianteeman** [comment]
Closed as the specific task is completed - the installer is still a general wip
