### ISSUE TITLE
[4.0] Webcomponents don't work in IE11

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#19329]
### Steps to reproduce the issue
Switcher elements as well as alerts don't work in IE11

### Expected result
Working CEs

### Actual result
![image](https://user-images.githubusercontent.com/1018684/34665381-3b9a9b3c-f460-11e7-9836-88ede3748a02.png)

![image](https://user-images.githubusercontent.com/1018684/34665392-4a27274c-f460-11e7-84cc-e03f5f0664a0.png)

### System information (as much as possible)
Internet Explorer 11 on Windows 7 Enterprise

### Additional comments
@dgt41 I thought we have a polyfill for browsers who don't support webcomponents (eg IE11)?

**Comment by dgrammatiko** [comment]
It's the `CustomEvent` that needs patching for IE11, the code is simple like 3 lines (I thought I did that already, maybe on the other repo, the Joomla-projects/custom-elelements).

**Comment by C-Lodder** [comment]
This is what I use for IE11 on my project:

```
var event = document.createEvent('Event');
event.initEvent('onFooBar', true, false);
window.dispatchEvent(event);

window.addEventListener('onFooBar', function() {
   /// something here
}, false);
```

**Comment by brianteeman** [comment]
@dgt41 has this been fixed?

**Comment by Bakual** [comment]
@brianteeman Seems to be. The switcher works now in IE11.
I only get a JS error for the tab-state script (tabs-state.min.js (1,563) object doesn't support "evaluate" or so).

**Comment by dgrammatiko** [comment]
@Bakual about tabs-state.js: this script won't be used in J4 at all since the stageful functionality of tabs is already integrated in our new tabs component (which is fully accessible compared to the foo-bar BS). There is already a PR for showcasing the changes needed in the layouts (just change the
```php
JHtml::_('bootstrap.startTabSet', ...)

// New code:
JHtml::_('uitab.startTabSet', ...)
```

This is already merged in the template repo, but will be good to also have it merged in the main repo and do the monkey work to change all the JHtml parts in the layouts


PS. The tab-state.js script has already been moved to the media/legacy folder, although I would suggest to just drop it as you already found out that it's not working in IE11

**Comment by Bakual** [comment]
I assumed as such since it seems to have a requirement to JQuery and I know you don't like that 😄
