### ISSUE TITLE
Label shown as "(optional)" for required user profile field.

### ISSUE THREAD

**Issue by Sophist-UK** [joomla/joomla-cms#19506]
### Steps to reproduce the issue

In the "User - Profile" plugin set Country to Required.

Log out and go to the registration form. 

### Expected result

Country field label does not say (optional).

### Actual result

Country field label says "(optional)"

### System information (as much as possible)

J3.8.4

### Additional comments

Country field is correctly validated as required, but even though label says "(optional)".

**Comment by brianteeman** [comment]
i recall this issue occurring before , or somethng similar

**Comment by brianteeman** [comment]
see https://docs.joomla.org/J3.x:Update_from_3.6.x_to_3.6.5_Profile_fields

**Comment by Sophist-UK** [comment]
The code is back where it was before the fix referred to in that document. I have tried applying the same fix, but it has not made a difference,

**Comment by brianteeman** [comment]
Guess I will have to dig into this one myself as its effecting one of my sites too

**Comment by Sophist-UK** [comment]
Thanks.

**Comment by brianteeman** [comment]
Wow - took me ages to track this one down - this has been such a longstanding bug that keeps getting fixed and then reappearing with other changes - see #19614

**Comment by panta7** [comment]
Same problem here in joomla 3.8.5: required "User - Profile plugin" fields are optional, and the label "terms of conditions" doesn't link to article.

**Comment by florahwilliams** [comment]
Psychology coursework writing services are essential and they have become very popular for those seeking psychology research writing help services since most of them seek [Psychology Research Writing Services](https://topessaywriting.com/psychology-research-writing-services/ "Psychology Research Writing Services").  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19506">issues.joomla.org/tracker/joomla-cms/19506</a>.</sub>
