### ISSUE TITLE
While trying to Edit Template JOOMLA 2.5 mail page its showing no direct access defined ( '_JEXEC' ) or die ( 'Restricted access' ); 

### ISSUE THREAD

**Issue by nikiromy007** [joomla/joomla-cms#19564]
### Steps to reproduce the issue

![joomla error](https://user-images.githubusercontent.com/32074602/35781505-e6cd0ed4-0a10-11e8-8b2e-544444c919b1.PNG)

### Additional comments
Please help me to solve the issue

**Comment by mbabker** [comment]
1) You are looking at the template file contents itself, the `defined('_JEXEC') or die;` check is pretty standard in all Joomla code.

2) Joomla 2.5 has not been supported since December 31, 2014; if you have not already you need to be looking into upgrading your site.

3) This platform is only for bugs regarding currently supported Joomla versions, for further help please use the forums at https://forum.joomla.org.

**Comment by nikiromy007** [comment]
Hi Mbabker, Thanks for your reply, can i do something without upgrading the version if possible plz let me know.
