### ISSUE TITLE
[4.0] RFC: Drop username, use email instead

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#19785]
As users tend to forget their username, and we already have an unique indentifier for each user with their email address, I suggest to drop the username field for Joomla 4.0.

Users could then register and login just with their email address. Existing users could still log in by just entering their email address instead of their username.

**Comment by Bakual** [comment]
I find it highly annoying to enter an email as username. I always prefer a username.
Beside that, if people forget their usernames, they also forget their emailadresses. That's not really an argument :smile: 

Imho, we can make it configurable to allow emails as usernames, but I certainly wouldn't drop the username.

**Comment by C-Lodder** [comment]
+1 to give the user the ability to use their email

Agree with @Bakual though. Dont drop the username

**Comment by brianteeman** [comment]
There is nothing stopping you from using your email address as a username right now

**Comment by mbabker** [comment]
> Existing users could still log in by just entering their email address instead of their username.

That'd be a major B/C break as effectively all users would have to know the email address they registered with when the site upgrades.  One minute you use username, the next minute you use email address.

There are already plugins out there that "hide" the username field and use email addresses, and there is no restriction on the username field to prevent using email addresses.

So IMO there is no action required and taking action is probably a bigger inconvenience than not.

**Comment by N6REJ** [comment]
The default should be the choice the admin makes in the users plugin with "username" being the default.  I seriously hate having to use email address all the time.

**Comment by brianteeman** [comment]
Only fair to also point out that you don't really want usernames to change over time and if you use emails them as the username them they will need to

**Comment by tonypartridge** [comment]
Also, there are plugins in the JED which allow the same email per account because J! Isn’t using the email as the unique identifier. Whilst I appreciate these are plugins, there any many sites out their using them. To force email by login as the default it would destroy these sites. 

I think native email login would be a good idea to support as a config option though.

**Comment by brianteeman** [comment]
you would also need to disable the "username reminder" functionality for very obvious reasons

**Comment by laoneo** [comment]
Some sites do offer to log in with username or password.

**Comment by tonypartridge** [comment]
I think you mean username or email 😉

**Comment by smehrbrodt** [comment]
Sure there are plugins which allow to login with the email address instead of the username.
However, when registering, you still need to enter a username.

But anyway, didn't expect that so many folks actually like this username thing. Maybe adding an option to chose between username and email would lead to even more complicated code.

So not sure what's the best thing to do here.

**Comment by brianteeman** [comment]
Look again. There are extensions that do everything you want. It's not hard but it is stupid

**Comment by laoneo** [comment]
What is stupid?

**Comment by schultz-it-solutions** [comment]
if "email address" is the identifier of users on a system, then for example large forum sites where posts show "who wrote this" may be a nice resource for real-live email addresses to spammers.

**Comment by tonypartridge** [comment]
No, because I’m that scenario you would display the name of the user opposed to username if it was removed which I am still very against.

**Comment by rdeutz** [comment]
This was already done (https://github.com/joomla/joomla-cms/pull/10347) a while ago and it was rejected because there are plugins the can do all what is need. In fact this was not 100% true because you couldn't hide the username fields consistent for all forms. Over the discussion we agreed on adding some plugin events to fill the gap and allow to hide the username fields consistently. Someone could do a follow up on the plugin, I lost interest in it because I did it for a client project and with the events I don't need more to make it happen.

**Comment by Bakual** [comment]
I'm closing as there is no broader interest and it is already possible with 3rd party plugins.
