### ISSUE TITLE
Editor: Insert button add an extra \ for article title containing a single quote '

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#19823]
### Steps to reproduce the issue
- Create a new article with Title "L'association A & L'association B" 
- Edit another article , use ![image](https://user-images.githubusercontent.com/5349333/36937679-54748e9c-1f17-11e8-8ec1-7269a46c5b64.png) to insert the link of the newly created article.

### Expected result
`"L'association A & L'association B"`

### Actual result
`"L\'association A & L\'association B"`

### System information (as much as possible)
3.8.5 using either MCE or CodeMirror.
PHP 5.x, windows and Linux.

### Additional comments

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/articles/tmpl/modal.php#L133

**Comment by infograf768** [comment]
Confirmed. Trying to understand why we add slashes there

**Comment by infograf768** [comment]
They are not necessary here as they are not part of a js onclick.
Will make patch.

**Comment by ggppdk** [comment]
It is as you said:

> They are not necessary here as they are not part of a js onclick.

Old code need it double esacaping because it was passing the data via parameter of JS method, whose code was inside an onclick Tag parameter

https://github.com/joomla/joomla-cms/commit/a4b880b09b3d92e26da446fc1d4ebba7112d28a8#diff-f0f22e7238611f9f5d7ea24bb92099d6L113

but then data were
moved to
'data-*' HTML Tag attributes, and the values were copied without considering that the double escaping was no longer needed

**Comment by ggppdk** [comment]
For menus it is without double escaping
`data-title="<?php echo $this->escape($item->title); ?>"`

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/items/tmpl/modal.php#L117

So the above is already proper

----

But there is 1 more modal layout that needs fixing , the contacts selection modal template
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_contact/views/contacts/tmpl/modal.php#L123

since it double escaping too
`data-title="<?php echo $this->escape(addslashes($item->name)); ?>"`

**Comment by infograf768** [comment]
will include both in PR

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/19826
