### ISSUE TITLE
[4.0] Sample data doesn't install

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#19851]
### Steps to reproduce the issue
1. click "Blog Sample data" button in Backend
2. wait

### Expected result
sample data is installed

### Actual result

nothing is installed and the timing image continues endlessly with nothing happening

### System information (as much as possible)

PHP Built On | Windows NT DJ-DESKTOP 10.0 build 16299 (Windows 10) i586
-- | --
Database Version | 5.5.5-10.1.9-MariaDB
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.4
Web Server | Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

### Additional comments

I have installed the Joomla version from today 6th March. I noticed someone else raised this issue previously. Whatever was done then still doesn't seem to work.

**Comment by brianteeman** [comment]
Updated title to show it is J4

**Comment by anuragteapot** [comment]
Can't confirm.  Blog Sample data installed successfully without any issue.
But, the timing image continues endlessly.


Database Version | 5.5.5-10.1.30-MariaDB
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.13

**Comment by ghost** [comment]
Any update @coolman01 as i also cannot confirm this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19851">issues.joomla.org/tracker/joomla-cms/19851</a>.</sub>

**Comment by happy2dev** [comment]
I faced the similar when install Joomla at my local Docker container.
- The first thing, it was because of CHMOD folder. I am in mistake when run git clone source at Host, not inside Container.
- The second thing, my Mysql doesn't support utf8mb, and sql file doesn't get imported.
I will follow this Issue and will check this more.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19851">issues.joomla.org/tracker/joomla-cms/19851</a>.</sub>

**Comment by OptikWebCreative** [comment]
installed fine for me, although doesn't seem to complete, just now on J4a3 although the option was visible but not selectable in the install process

**Comment by brianteeman** [comment]
Closed as not repeatable
