### ISSUE TITLE
Any translation possibilities for groups

### ISSUE THREAD

**Issue by Mausino** [joomla/joomla-cms#19995]
### Steps to reproduce the issue

Created or new one groups like Public, Guests, Registered etc aren't possible translate or add translation in J3

### Expected result
It will possible assign translation for any created group, that if user working with group will understable in their mature language

### Actual result

Default groups are in english.. 

### System information (as much as possible)

J3.8.6

**Comment by ghost** [comment]
Can you please update on latest Release 3.8.6?

**Comment by Mausino** [comment]
@franz-wohlkoenig sorry my issue https://www.screencast.com/t/IB1iCSgEHYL6 i have latest version of joomla! but i updated the ticket.. because it was typo in version name.

**Comment by infograf768** [comment]
The problem here is that one can create as many groups as desired. Same for Access Levels.
The only possibility would be to give as title of a group a lang constant (i.e. our specific format like `MY_GROUP_UNIQUE`) and then modify the code everywhere we display the group titles to use JText::_() in order to translate that title. One would evidently have to create these language strings in overrides.ini for each language as they create groups.

**Comment by brianteeman** [comment]
@infograf768 can the technique used for com_workflows to translate the stages and transitions be used to resolve this?

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

This is however a valid issue for Joomla 4 and is currently prevented by a limitation referred to in #36322. As fixing that will allow you to rename all the groups this will be closed here and you can follow it there.

cc @zero-24

**Comment by brianteeman** [comment]
please test #38592 for joomla4
