### ISSUE TITLE
Joomla 3.8.6 unchecked caching

### ISSUE THREAD

**Issue by Vitaliy214** [joomla/joomla-cms#20014]
### Steps to reproduce the issue

Disable cache

### Expected result

Caching continues to work

### Actual result

On the server in the cache folder, files are created that can not be deleted, in the administrative part
### System information (as much as possible)

Linux 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64
Database Type | mysql
5.5.5-10.1.26-MariaDB-0+deb9u1
utf8_general_ci
utf8mb4_general_ci
PHP | 7.0.19-1
Apache/2.4.25 (Debian)
PHP | apache2handler
Joomla! 3.8.6 Stable [ Amani ] 13-March-2018 14:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by zero-24** [comment]
Hi,

what exact cache did you use and what exact cache did you disable? Do you use 3rd Party cache systems?

Just to clear the expectations. Why do you expect the Caching to still work if you disable it?
How can we reproduce it on a clean install without 3rd party extensions? Please be more clear in your description.

Just form the description above this more sounds like a issue that needs to be addressed on your site so the better place to get support would be the forum: https://forum.joomla.org as this here is the place to handle actual bugs in the software and not possible configuration problems :)

**Comment by Vitaliy214** [comment]
Hello
I'm sure that this is the cache Joomla.
If we go to the configuration file, we have the value public $ caching = '0';
Going into the cache folder, we see a sub-folder of the "page" that constantly creates new files, even after they have been deleted.
Opening the page through Firebog, we see the cache on the disk, and the cache in the memory.

**Comment by brianteeman** [comment]
Do you have the system cache plugin enabled?

**Comment by ggppdk** [comment]
What you see is behaviour by design

- what you have disabled is the view / (module) caching setting

The page folder in the cache directory is the System cache plugin,
which you seem to have enabled,
and it is a different type of caching, which is called page caching, as it caches the full page, and not individual parts of the page

Also the setting of caching in global configuration is not obligatory setting
every individual extension component view, module, plugin,

- can have have a setting to use or not to use Global cache setting 
- and / or may cache some of their data regardless of global setting

**Comment by Vitaliy214** [comment]
Yes, the system cache is enabled, and was enabled earlier, but I did not experience any problems, maybe I'm wrong. thanks for answers

**Comment by brianteeman** [comment]
The system cache plugin is different to the cache set in global configuration. So everything is working as it is supposed to do.
