### ISSUE TITLE
[4.0] Web Installer button not working 

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#20098]
### Steps to reproduce the issue
Step 1: Activate web install if not activated.
Step 2: Click on any extension to install.
Step 3: ![screen shot 2018-04-06 at 16 04 32](https://issues.joomla.org/uploads/1/9869130131b710bfa5715a64c952c971.png)

Click on install

### Expected result
Modal slide-up with install button

### Actual result
Nothing happens

### System information (as much as possible)
Joomla-4.0-dev

### Additional comments
@dgt41 @C-Lodder 
I think we have some work left in web installer Plugin

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/issues/19429

Because the jQuery stuff was commented out of the plugin's JS, all the fancy transitions aren't there right now.  You have to scroll to see the install block.  I'm not doing more work on the plugin in this repo until the ES6 repo work is merged in because I started making changes in the JS over there that would break things here and I don't want to maintain multiple versions of that source.

**Comment by anuragteapot** [comment]
@mbabker Thanks for this information.
