### ISSUE TITLE
No configuration file found and no installation code available. Exiting...

### ISSUE THREAD

**Issue by cloudenv** [joomla/joomla-cms#20106]
### Steps to reproduce the issue
Just followinstallation wizard

### Expected result
Running Joomla

### Actual result
No configuration file found and no installation code available. Exiting...

### System information (as much as possible)
GCP || Win2016 with IIS 7.9.9.fuckee
Tid{ASS} phpsucks

### Additional comments
24h

**Comment by zero-24** [comment]
Well yes this is the expected behavior if no install code is there and no configuration file is found ;) What kind of `installation wizard` did you follow? The stock from joomla core or a custom build by someone else?

Please try the latest Full Package from here: https://downloads.joomla.org/latest and try again. Thanks.

**Comment by cloudenv** [comment]
I followed standard installation wizard from Joomla website (in fact Ive downloaded zip from location you linked)

**Comment by zero-24** [comment]
Yes the only case where such a thing could happen would mean that joomla can't write files to the disc because of permission problems. But that would also mean there is a big message at the end of the prozess that is telling you to create that file your self.

**Comment by cloudenv** [comment]
Both created file by myself and let Joomla do this for me. Both failed. Still this msg is shown.
Permissions are correct

**Comment by zero-24** [comment]
> Both created file by myself and let Joomla do this for me. Both failed. 

What does mean both failed? If there is a configuration file this error message should not come up at all :)

**Comment by ggppdk** [comment]
@cloudenv 

Because your issue description is a very short
> Just followinstallation wizard

do you mean with the above 
- that you completed the installation wizard of Joomla ?
- that you had this error before the installation wizard of Joomla finished ?
- that the installation wizard of Joomla did not start at all ?

**Comment by cloudenv** [comment]
@ggppdk First one......
@zero-24 It means that I tried installing Joomla 2 times, both from scratch (with **full erasure** of Joomla dir), both failed

**Comment by ggppdk** [comment]
> @ggppdk First one......

So the reason must be what @zero-24  said
Joomla could not write the configuration file because of permissions

**Comment by brianteeman** [comment]
Please use the forum for support. HTTPS://forum.joomla.org

**Comment by cloudenv** [comment]
@ggppdk But permissions are correct. Joomla installs just fine (meaning no errors other than this one.).
@brianteeman Use forum, and wait God knows how long? No, thank you!

**Comment by ggppdk** [comment]
@cloudenv 

This is what must be happening in your case (**i am guessing**)
Your web-server **is running under a user** 
- that is be allowed to **delete** files and folders (thus installation folder deleted)
- that is not allowed to **create or modify** files (thus configuration.php was not created ?)

Instead of Joomla forums since this a general issue related to microsft web-server setup
You can google
Required File System Permissions Windows IIS

Same problem you would have with drupal, or any other software that need to write/modify files on the disk
- it is not something that can be fixed inside Joomla

**Comment by wachiuri** [comment]
Have you opened and saved configuration.php with notepad? Check that the file is not saved as configuration.php.txt instead
