### ISSUE TITLE
Feature Request: Using root category in category views

### ISSUE THREAD

**Issue by drtothferenc19** [joomla/joomla-cms#20138]
It would be great to use all of the articles to display from the whole database, from all categories. Like you want to display the latest articles or most popular articles of the site with a blog layout, regardless of the category of the articles.

### Steps to reproduce the issue
When you create a Category Blog menu item, you should choose all or root as category. Now you need to pick a category.

### Expected result
When you don't pick a specific category Joomla shouldn't use the category filter, only if 'include subcategories' param is a specific number. In this case level 1 should be the first level of the categories, where parent_id=0

### Actual result
You're forced to pick a category.

**Comment by tonypartridge** [comment]
Do you mean sub categories of the parent category selected?

**Comment by Bakual** [comment]
You can't set permissions for the root category and that category is shared across all extensions. You would likely get a lot of unforeseen issues with that. I had that behavior in my own component and moved away from it due to the special handling it needed all over the place.

But what exactly do you want to achieve that you currently can't? All you need to do is create a single parent category for the other categories and pick that one as the base.

**Comment by ghost** [comment]
For Example create a Root-Category for Language "en-GB" and all Categories below that; so you are also prepared for a Multilanguage Site.

**Comment by brianteeman** [comment]
I am closing this for the reason mentioned by @bakual
