### ISSUE TITLE
Featured Request [maybe]: Native Joomla Comment System

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#20178]
A native Joomla comment system, is something that the CMS should have? I see this type of request in every corner. And in case it's something of interest to CMS, I'd like to work on it. Just asking before.

**Comment by ghost** [comment]
Similar like Weblinks, not installed by Core.

**Comment by ssnobben** [comment]
You have comment system like Komento https://stackideas.com/komento, Jcomments https://extensions.joomla.org/extension/jcomments/ and review/comment system like Jreviews https://demo.jreviews.com/city-guide/hotels/encore-las-vegas  

You thinking of a comments/reviews system where you can expand this to be used universally for other components and for blogs, users etc too?

**Comment by laoneo** [comment]
If added, then it should be done with the focus that 3rd party can integrate it seamless like com_fields. But honestly I think there are good extensions out there which do the job properly and we do not need that in core.

**Comment by ssnobben** [comment]
"we do not need that in core." I dont think you have done a Joomla user market research about that. Better statement "I do not need that in core."

**Comment by laoneo** [comment]
No I didn't, but I want to keep the core as slim as possible. Additionally when we start to add functionality into the core which can be done by 3rd party extensions then it is bad for the eco system of Joomla.

**Comment by carlitorweb** [comment]
I know out there are good extensions do the job. But are more user asking the reason why Joomla no have a native comment system. And yes, if this feature is added, is like Weblink and focus 3rd party extension can integrate

**Comment by adankupapa** [comment]
A native Joomla comment system is something I have been waiting to see for a very long time and I agree with @carlitorweb . Yes, there are great 3rd party commenting systems out there but I am sure having at least a simple/basic one that can exclude/include some categories, make use of the existing re-capture system and allow blacklisting of words will go a long way to add to the strengths of Joomla anytime it is compared to WP and DP.

**Comment by proweb** [comment]
No, bad idea, not all joomla websites need comments.

**Comment by CB9TOIIIA** [comment]
No no no

**Comment by alikon** [comment]
@proweb no one will force you to use comments

imho, if it will be developed basic, so don't hurt 3dp

> with the focus that 3rd party can integrate it seamless like com_fields

why not, a lot of people don't like to install 3dp for basic tasks

**Comment by brianteeman** [comment]
ironically the reason I found mambo 15 years ago was because it was the only cms that did not have comments

**Comment by Bakual** [comment]
I would not add comments. 
It is certainly not something used on a large scale (it's only useful in blog contexts). And we make a general effort to make core smaller.
Also adding functionality which is already covered by 3rd party doesn't make sense to me.

If anything, we could see if we want to add something which makes it easier for comment extensions to hook into. If that isn't already covered.

**Comment by adankupapa** [comment]
There is a saying that, it is better to have and not need; than need and not
have. If it comes as a plugin, it can be disabled and enabled as and when
needed. I am really struggling to find a site today that does not have a
need for a comment system. People are busy integrating facebook comments
plugin just because they want feedback on their content. Many many
corporate and personal sites have blog sections which will need a
commenting system.  (This is one feature that makes WP a prefered choice
for starter websites and blogs). Yes, it needs to be done in a way that
will not hurt current 3rd party systems but I strongly believe this will be
a pro for Joomla. I personally don't see any downside to a native comment
system for Joomla. Please please consider it.

**Comment by Bakual** [comment]
> There is a saying that, it is better to have a not need; than need and not
have. 

You're aware that "not have" isn't accurate in our case, because actually you can choose from several (3rd party) options already. There is nothing wrong with using 3rd party extensions.

**Comment by adankupapa** [comment]
_please pardon the lengthy response._
Yes there is nothing wrong in using third party extensions. But there is also nothing wrong in getting one built inside Joomla. **My country people say too much meat (assorted protein), does not spoil soup.**  It is understandable that many comments extension devs will have an issue with this feature for obvious reasons but think about these, 

1. Joomla has com_content but some websites use alternatives like K2, FLEXIcontent etc.
2. Joomla has ACL feature, but some websites use 3rd Party extensions.
3. Joomla has pretty great search system but sites can use 3rd parties. 
4. We can continue listing similar ones.
5. Additionally, most 3rd party extensions come at costs that will continue to climb.
6. What if 3rd Party extension devs decide to discontinue projects in the future for various reasons which no one can control? **Recent Experience;** I was using a plugin for some websites and I noticed it hadn't been updated for a long time. I decided to check the developer's site for an update only to be told, they've discontinued the plugin because they cannot make it compliant with Joomla 4. This is a plugin I have depended on for several years and is obvious what this means to my site.  I simply thanked them and tried convincing them to even make it into a commercial plugin but they had a new focus and no one can hold it against them. 

My point is, if a basic form of an extension can be implemented in the core, then it should. The sites that need more advanced features of it can then use 3rd party ones. As to how much extra megabytes this will add to the core, I leave that to the experts.

**Comment by rdeutz** [comment]
We are focused on less core extensions and a good eco system for 3rd part extensions, the chance is zero that we integrate a commenting system as core extension.

I will close this.

**Comment by ot2sen** [comment]
To add a historical perspective this wish was once one of the upcoming new features for the 1.6 release. Must be about 9 years back now and Andrew, Louis and Rob "donated" their own comments extension code to be included in core for 1.6. We, the core team, accepted that "donation" at that time. Had its own branch, see comments branch here http://joomlacode.org/gf/project/joomla/scmsvn/?action=browse&path=%2Fdevelopment%2Fbranches%2F

But other more important features took priority to have finalised for 1.6 stable, like the new ACL, the switch from section/cats to cats/subcats and a simplified multilingual approach, and it meant comments didn´t have time to get properly implemented. Eventually the idea of comments got dropped from the 1.7 release. There was other priorities for features. And there were comments extensions available at that time too.

More of the same comments extensions are actively developed still so many years later. I guess they are still the better choice. Easy to add and quite stable after years of development. Doesn´t have to be a core feature.

**Comment by ssnobben** [comment]
@proweb yes same argument with a strategic priority can be discussed to... not all joomla websites need multilanguage pages, not all joomla websites need banners, not all joomla websites need need weblinks, not all joomla websites need contacts, not all joomla websites need messaging, not all joomla websites need search, not all joomla websites need news feed, not all joomla websites need fields & fields groups, not all joomla websites need notes etc 

So why are these core extensions there if the core should be slimmed down? 

Whats the guideline analysis parameters that set forth what should be in the core or not? 

Maybe I miss that but I dont think that Joomla community have done any type of research what Joomla focused target users want in the core or not? comparing to its competitors and potential users needs/wants

**Comment by mbabker** [comment]
To me, the ship has sailed on having comments in core.  There are better maintained solutions in the ecosystem, and that is perfectly acceptable as not every tool has to be installed with the ZIP package we provide.  Ecommerce is a very common use case for Joomla but nobody suggests that any of those packages or a slimmed down version of those be included in core.

**Comment by proweb** [comment]
as said @Bakual and I agree with him - `we make a general effort to make core smaller`
How many times somebody wishes included in core move as to more errors, more bugs in releases. And release to fix previous release bother people and moves they away from joomla to more stable CMS.
Ad more core extensions is the way to more problems. We are have not so much people who work hard and improve Joomla day by day for free, as volunteer

In our Russian joomla community we have great comments example as JComments.

**Comment by carlitorweb** [comment]
Thank you for all the opinions. I think I have clear now, what means "core smaller".
