### ISSUE TITLE
com redirect collects weird urls

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#20287]
### Steps to reproduce the issue

You have to host 2 sites in the same server

enable system-redirect plugin

- collect urls:enabled

- Include Domain Name in Expired URL:enabled

then go to component redirects after some hours and watch what urls have been collected.

In my case i see urls: 
in the domain 1 site i see
http://domain2.com/somthing-from-domain3 or

in the domain 2 site i see
http://domain1.com/something-from-domain3

etc
 

### Expected result
No urls from other domains

### Actual result
urls with mixed words from different domains

### System information (as much as possible)
joomla 3.8.7.
host with ispconfig platform

### Additional comments
I have observed this for quite a long time so i don't know when it happened and i thought that it maybe was a hosting issue.
However reading this #17349 
and especially @rvalitov comment 

> In my case I use ISPConfig - a well-known hosting panel. It creates symlinks to website's root documents like /var/clients/client1/website3/web, besides they are also accessible with the domain name, for example, /var/www/www.example.com/web. And this causes the JFolder::create hell!

I thought maybe it's a joomla 's issue.

So do you think it's another issue similar or the #20280 should fix my issue too?
In this case you can close this:)

@rvalitov sorry for pinging does my issue makes sense?
It's really weird...

**Comment by rvalitov** [comment]
Hi! I use the latest ISPConfig with latest PHP 7.0.x, and I didn't face this issue. So, I'm not sure if it's related to #20280.

Some ideas:
- Please, check that you use latest Apache and it does not has any errors in its log related to the website configurations. 
- ISPConfig also has _redirect_ options, may be the problem is there? Besides, ISPConfig has _alias_ options, are they enabled?

**Comment by peteruoi** [comment]
I use latest ispconfig with php 7 too. It 's a standard installation nothing fancy. However if you haven't noticed it in your joomla components redirect after enabling collect urls then i guess it 's something with my ispconfig installation.
Thanks for your time!

**Comment by rvalitov** [comment]
Sorry, I didn't completely understand your issue. I was thinking that you mean the URL rewrite options in the settings:

![image](https://user-images.githubusercontent.com/16267156/39569854-1d67d30e-4ecf-11e8-92a5-c637525b5bef.png)

I will test the redirect plugin now, it is disabled on my websites. The settings below are correct?

![image](https://user-images.githubusercontent.com/16267156/39569969-7a1eb554-4ecf-11e8-89f3-9909a4d26fbe.png)

**Comment by rvalitov** [comment]
Should I enable this plugin at least on 2 websites? Does it happen when you use HTTPS (SSL) or only HTTP?

**Comment by peteruoi** [comment]
i have both http:// and https:// sites so i don't think it matters.
Yes these are the right settings to reproduce! Yes enable the redirect plugin at least in two sites!
Thanks again!

**Comment by rvalitov** [comment]
@peteruoi I enabled the plugin on both websites, but the list of links is empty:

![image](https://user-images.githubusercontent.com/16267156/39645910-738891ba-4fe2-11e8-9f6d-b6426bb967cc.png)

I tried to open different web pages at both websites, but the list is still empty. Do you have an idea how to populate it with data?

**Comment by rvalitov** [comment]
I made a few tests. All results in the table are similar to the following 2 fields:

![image](https://user-images.githubusercontent.com/16267156/40295235-51d48c0c-5ce1-11e8-8cd4-60e8937b7006.png)

My conclusions:

- The _Expired URL_ field sometimes contains domain name, sometimes not - even if the _Include Domain Name_ option is enabled. This is a bug?
- If I simply access some arbitrary URL on the website which does not exist in order to populate the table of the Redirects plugin, then in this case the _Expired URL_ always does not include the domain name.
- The _Referring Page_ can be empty or can contain a valid referring page. The referring page can be from another domain which is a correct behavior.

@peteruoi Do you have problems with the _Expired URL_ field or _Referring Page_ field? Did you check that your websites use different databases?
