### ISSUE TITLE
Template Submenu Items

### ISSUE THREAD

**Issue by Dave-LeDev** [joomla/joomla-cms#20309]
It's exceptionally rare that when I go to edit a template or template style that it'll be more than one at a given time. It would save a page load if the Manage>Templates links included another level that shows enabled templates and template styles.

While yes, I can add a manual link, I believe this can be a useful little feature in core.

<img src="https://i.gyazo.com/dc314fcaee0dca4d472a689f23527b55.png"/>

**Comment by ghost** [comment]
Can a more experienced one than me please answer on this issue as its open since 10+ Days having Staus "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20309">issues.joomla.org/tracker/joomla-cms/20309</a>.</sub>

**Comment by infograf768** [comment]
This request is not as easy to implement as it looks (it is not a `little feature` 😺   ) and in any case does not look necessary just to save a click. If a user absolutely needs direct links to various templates, using the URL menu type is enough. 

Can be closed imho.

**Comment by ghost** [comment]
Thanks for Comment @infograf768, this Issue is closed as stated above. It can always reopened for further Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20309">issues.joomla.org/tracker/joomla-cms/20309</a>.</sub>
