### ISSUE TITLE
[4.0] Admin Login eye not styled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20360]
### Steps to reproduce the issue

install Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
Go to admin Login

### Expected result

eye icon correctly styled

### Actual result

<img width="402" alt="screen shot 2018-05-12 at 21 13 06" src="https://user-images.githubusercontent.com/400092/39961206-654808fe-5629-11e8-8322-2b2fc62c23e1.png">

**Comment by Quy** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/19231#issuecomment-375866160<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20360">issues.joomla.org/tracker/joomla-cms/20360</a>.</sub>
