### ISSUE TITLE
[4.0] Not able to open Media-Action tab

### ISSUE THREAD

**Issue by geetanshu-m** [joomla/joomla-cms#20447]
### Steps to reproduce the issue

In *4.0-dev* branch
- Go to Media tab
- Then got to try to edit any image.
![screenshot 196](https://user-images.githubusercontent.com/18314265/40217149-dc0f60d2-5a88-11e8-8f1b-ca4db40508ce.png)

### Expected result

This should redirect you to media action tab

### Actual result

Following screen is being showed

![screenshot 195](https://user-images.githubusercontent.com/18314265/40217021-26178610-5a88-11e8-808f-7f3e9095b612.png)

![40165702-4b4a547a-59da-11e8-9c1d-954023dc99f3](https://user-images.githubusercontent.com/18314265/40217044-4338fada-5a88-11e8-9cd6-41154769d3e8.png)

### System information (as much as possible)

![issue](https://user-images.githubusercontent.com/18314265/40217056-4eabe198-5a88-11e8-8923-fe1016e44561.PNG)

**Comment by geetanshu-m** [comment]
@laoneo @wilsonge Please have a look over this issue

**Comment by Quy** [comment]
Fixed in https://github.com/joomla-projects/media-manager-improvement/pull/546<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20447">issues.joomla.org/tracker/joomla-cms/20447</a>.</sub>
