### ISSUE TITLE
[4.0] Too many warnings out of the box.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20474]
### Steps to reproduce the issue

After installing Joomla 4 - FOUR of the built in extensions all report warnings (3 warnings and 1 error)

This gives the first time user a bad impression I think

### Expected result

Less ....

I dont have all the answers... thoughts?

For example, if the 2FA plugin is not installed then the tab for the 2fa is not shown in edit users... so maybe if these extensions plugins are not enabled, maybe we should not show the extensions in the menu? or at the least allow those dependancies to be enabled with a single click from the extension? 

thoughts?

### Actual result

![screen recording 2018-05-19 at 08 42 pm](https://user-images.githubusercontent.com/400092/40272459-2fa25bba-5ba5-11e8-8c6d-07f2a21d3f03.gif)

**Comment by brianteeman** [comment]
Apparently the silo master says that if you do that - which is very sensible - then no one would ever know they were possible functions

**Comment by Bakual** [comment]
Brian, take it down a few steps. This isn't at all about your vendetta with JM. Three of the four issues mentioned by Phil aren't even tied to languages.
As for the proposed solutions I think we are not able to "hide" components in the component list. It would also become quite complex as it would need custom "dependencies" per component.
One can of course create custom menus or disable the component in the extension manager if someone is bothered by the "useless" entries.

So that leaves us to the other proposed solution:
> or at the least allow those dependancies to be enabled with a single click from the extension?

That one should actually be easy to do. Imho we do something similar in other places already. Eg giving a link directly to the filtered smart search plugins list would be very helpful indeed. 👍
Or maybe even enable some of the plugins (eg enable a Smart Search plugin or the redirect plugin) by default.

**Comment by brianteeman** [comment]
I never said it was anything to do with languages at all - don't assume things - and I have no vendetta

The point is that every time we try to do progressive disclosure it is blocked

**Comment by Hackwar** [comment]
Considering that I can't really see the bugs and lots of it has been fixed in the meantime (and others introduced since), I think this issue is now obsolete and should be closed.

**Comment by PhilETaylor** [comment]
I disagree. The reported issue is that out of the box there are too many warnings/errors being displayed and sane defaults or explanations are not being made in a nice way to the first time user.

As of today there are still popups on accessing

 - Multilingual Associations

![screen shot 2018-08-19 at 22 04 53](https://user-images.githubusercontent.com/400092/44313201-eb06a480-a3fb-11e8-93bf-6f2def11e4a7.png)

 - Redirects

![screen shot 2018-08-19 at 22 05 10](https://user-images.githubusercontent.com/400092/44313206-f659d000-a3fb-11e8-8903-321b0fb8b181.png)

- Search 

![screen shot 2018-08-19 at 22 05 29](https://user-images.githubusercontent.com/400092/44313210-02de2880-a3fc-11e8-90e7-0548a36a08d7.png)

 - Smart search

![screen shot 2018-08-19 at 22 05 45](https://user-images.githubusercontent.com/400092/44313214-0c679080-a3fc-11e8-9148-e765747c6048.png)

**Comment by Hackwar** [comment]
#20904 and #20637 should handle the last two. I did not correctly understand the issue here that you were talking about. I'm not sure if I agree with you. But with that explanation, this should indeed stay open.

**Comment by ghost** [comment]
Added Category "Feature Request" cause of "I think all 4 of these should be replaced with an explanation page with links to the documentation, and "faq" answered right" mentioned in above Comment.

**Comment by ghost** [comment]
Also annoying to get every Time calling com_redirect:
![screen shot 2018-08-21 at 10 16 01](https://user-images.githubusercontent.com/8235763/44389546-703ca700-a52b-11e8-9cb5-803773ae4b7d.jpg)
