### ISSUE TITLE
[com_fields] Changing date format via DATE_FORMAT_CALENDAR_DATE results in incorrect dates after saving

### ISSUE THREAD

**Issue by internetdienstennederland** [joomla/joomla-cms#20526]
### Steps to reproduce the issue
1) Create a custom date field for users
2) Change DATE_FORMAT_CALENDAR_DATE language string to "%d-%m-%Y"
3) Edit user profile
4) Set custom field to 06-06-2006
5) Save user profile

### Expected result
Field value is expected to be 06-06-2006

### Actual result
Field value is 20-06-2006

### System information (as much as possible)
PHP7.1, Joomla 3.8.5

### Additional comments
Changing the date format of custom field via DATE_FORMAT_CALENDAR_DATE to the dutch format (dd-mm-yyyy) results in incorrect dates after saving.

E.g. 06-06-2006 results in 20-06-2006

**Comment by ghost** [comment]
@internetdienstennederland can you please update to latest Version ([3.8.7](https://downloads.joomla.org/)) and test Issue again? 

Hint: For Today next Version 3.8.8 is announced.

**Comment by internetdienstennederland** [comment]
It was fixed by changing all the DATE_FORMAT_* language strings. It is unsure with one actually solved the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20526">issues.joomla.org/tracker/joomla-cms/20526</a>.</sub>

**Comment by Bakual** [comment]
The strings in question are the following
https://github.com/joomla/joomla-cms/blob/c396b5c201aae00add01fe1c5c67fa563e651825/language/en-GB/en-GB.ini#L325-L328
It is mandatory that the CALENDAR one matches the FILTER one. They need to refer to the same format, but with different notations. Otherwise it is expected to fail.

I'm closing this issue since it apparently worked once the corresponding string was changed as well.
