### ISSUE TITLE
[SOLVED] Update to Joomla! 3.8.8 Stable appears to break Random Image module

### ISSUE THREAD

**Issue by slrellison** [joomla/joomla-cms#20541]
### Steps to reproduce the issue
Update to Joomla! 3.8.8 with Random Image module (mod_random_image) showing small image in featured article

### Expected result
Home page displays as normal

### Actual result
Home page returns Joomla! 404 error page with additional error message 
#0 Using $this when not in object context

Replacing the {loadposition} with a static image provides a work-round, allowing home page to load.

### System information (as much as possible)
From System info:
- Joomla! version: Joomla! 3.8.8 Stable [ Amani ] 22-May-2018 14:00 GMT 
- Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux 
- PHP version 7.0.29

**Comment by carlitorweb** [comment]
Duplicated. Fixed on #20533

**Comment by Quy** [comment]
Lets keep this open for now and hopefully will prevent further duplicate reports.

For details: https://docs.joomla.org/J3.x:Module_random_image_PHP_Error_after_3.8.8

**Comment by carlitorweb** [comment]
Good idea

**Comment by slrellison** [comment]
That was a staggeringly fast response!
Many thanks.

**Comment by slrellison** [comment]
[Apologies; wrong 'close/comment' button. Noted request to keep issue open to prevent duplicates - reopened accordingly]

**Comment by AllanThomp** [comment]
Same problem while upgrading from Joomla 3.8.7 to 3.8.8 this morning.  Used usual Joomla Administrator procedure including automatic Akeeba backup.  Restoration to 3.8.7 successful and site OK now.  Fortunately, this was a development site and not live site.

What should I do next?  Any information that I can provide that would be useful to debug or work around this?

Thanks,

**Comment by brianteeman** [comment]
read the comments here in this thread and you will see the answer

**Comment by AllanThomp** [comment]
Thanks for the quick response.  Do you mean this part:
How to fix
Apply this patch https://github.com/joomla/joomla-cms/pull/20533/files

Do I do that after the upgrade to 3.8.8?

Can I just wait and 3.8.8 will be fixed?

Thanks,

**Comment by joomdonation** [comment]
@AllanThomp You can:

- Update to 3.8.8
- Then replace the file **modules/mod_random_image/tmpl/default.php** on your site with this file https://github.com/joomla/joomla-cms/blob/staging/modules/mod_random_image/tmpl/default.php

Or you can just wait for next release 3.8.9 as you said.

**Comment by AllanThomp** [comment]
Thanks!  I think I can do that.  This is a very simple site so I would expect many others to have the same problem.  Do you expect 3.8.9 to be available soon?

**Comment by Quy** [comment]
It is scheduled for June 26.

https://github.com/joomla/joomla-cms/milestones

**Comment by carolmattsson** [comment]
To clarify Allan's description of the fix, the default.php referenced in this step:

Then replace the file modules/mod_random_image/tmpl/default.php on your site with this file https://github.com/joomla/joomla-cms/blob/staging/modules/mod_random_image/tmpl/default.php

... Restores the web pages but has other flaws.  As tried on the development website for https://bikex.org: instead of displaying a photo, the random image module displays some github-themed page.  Also the background color for the website is white instead of "cosmic latte" and the main menu pulldowns are cut off at the right.

Also, the default.php file referenced above, that I swapped in, is about 5 X the size of the original default.php.  So maybe I didn't understand how to apply the fix.

Instead, apply the patch described here: https://github.com/joomla/joomla-cms/pull/20533/files.  Do it by updating your website to Joomla 3.8.8 then editing the default.php file by changing the ONE LINE referenced in the "pull" link.

That worked for me.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20541">issues.joomla.org/tracker/joomla-cms/20541</a>.</sub>

**Comment by Quy** [comment]
You can also do a template override and make the necessary change without having to mess with the file system to replace the file.
