### ISSUE TITLE
Joomla 3.8.8 IFRAME-Problem

### ISSUE THREAD

**Issue by HassbergKliniken** [joomla/joomla-cms#20568]
### Steps to reproduce the issue
Since Joomla 3.8.8 update iframe doesn't display.

### Expected result
display iframe

### Actual result
iframe doesn't display

### System information (as much as possible)
Joomla 3.8.8 (from 3.8.7)

### Additional comments
Side with the problem: https://www.behmnet.de/datenschutz
Codeline: <iframe style="border: 0; height: 220px; width: 100%;" src="http://piwik.behmnet.de/index.php?module=CoreAdminHome&action=optOut&idsite=1&language=de"></iframe>

**Comment by brianteeman** [comment]
This is nothing to do with Joomla. The browser is blocking the iframe content because it is on http and your site is on https

`Mixed Content: The page at 'https://www.behmnet.de/datenschutz' was loaded over HTTPS, but requested an insecure resource 'http://piwik.behmnet.de/index.php?module=CoreAdminHome&action=optOut&idsite=1&language=de'. This request has been blocked; the content must be served over HTTPS.
`
