### ISSUE TITLE
Stats plugin [GDPR]

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#20582]
I'm not too savvy with GDPR so this is purely a question.

In the Joomla backend, we have an alert being displayed asking if the user wants to submit specific site statistics, such as PHP, Joomla and Database types.

The user of course must accept this which is fine, but do we not need a link going to a page on JDocs or j.org telling the user where this info is stored, how it's used, and so on?

I'm aware there's a repo for com_privacy, but just in case this had been forgotten

@brianteeman

**Comment by tonypartridge** [comment]
I don’t think so, this isn’t personal information. It’s technical information about a website.

**Comment by PhilETaylor** [comment]
The current link doesn't even work ;-) https://github.com/joomla/joomla-cms/issues/20557

**Comment by alikon** [comment]
however data sended by the `System - Joomla! Statistics` plugin are anoymized by desing

**Comment by brianteeman** [comment]
We already have the message.

COM_CPANEL_MSG_STATS_COLLECTION_BODY="<p>Since Joomla! 3.5 a statistics plugin will submit anonymous data to the Joomla Project. This will only submit the Joomla version, PHP version, database engine and version, and server operating system.</p><p>This data is collected to ensure that future versions of Joomla can take advantage of the latest database and PHP features without affecting significant numbers of users. The need for this became clear when a minimum of PHP 5.3.10 was required when Joomla! 3.3 implemented the more secure Bcrypt passwords.</p><p>In the interest of full transparency and to help developers <a href="_QQ_"https://developer.joomla.org/about/stats.html"_QQ_">this data is publicly available.</a> An API and graphs will show the Joomla version, PHP versions and database engines in use.</p><p>If you do not wish to provide the Joomla Project with this information you can disable the plugin called System - Joomla Statistics.</p>"

**Comment by brianteeman** [comment]
In addition the data is not personal information as defined by the gdpr

**Comment by C-Lodder** [comment]
Fair play. So this can be closed?
