### ISSUE TITLE
Check the version of the translation and check it is up to date

### ISSUE THREAD

**Issue by bartcz** [joomla/joomla-cms#20628]
Hello,

I have a proposal to check the version of the translation in Joomla! and check it is up to date, , as is the case with checking the current version of Joomla - separately (Maintenance - Control Panel).

**Comment by infograf768** [comment]
Languages are considered as Extensions: "Updates are available" is displayed when one language has a possible Update.
Not sure we can separate languages from the rest of extensions to display them separately in CPanel

**Comment by brianteeman** [comment]
Even if we do separate them - why?

**Comment by richard67** [comment]
I do not see any advantage in doing that.

**Comment by Bakual** [comment]
I'm closing this since I also don't see why we should do that.
If an update is available, it is already shown as @infograf768 explained.
If no update is available, there is no point telling the user that the pack is outdated (which may or may not be true).
Also, it's quite simple already to check the version of the pack in the extension manager.
