### ISSUE TITLE
[4.0] Issue installing Joomla 4 Plesk

### ISSUE THREAD

**Issue by OrgasmicSweets** [joomla/joomla-cms#20821]
### Steps to reproduce the issue
Upload Joomla 4 Install files and navigate to the directory 

### Expected result
Show Install Page

### Actual result
Error `An error has occurred while processing your request.
0 Could not create session directory "/var/lib/php/session"`

### System information (as much as possible)
Plesk Control Panel 
Cento OS 7
PHP 7.1

**Comment by ghost** [comment]
Changed Title to show Issue is about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20821">issues.joomla.org/tracker/joomla-cms/20821</a>.</sub>

**Comment by Twincarb** [comment]
Confirmed issue on my plesk server, the following error is shown in the php error log.

[21-Jun-2018 10:16:12] WARNING: [pool testbed.example.co.uk] child 29054 said into stderr: "NOTICE: PHP message: PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/example.co.uk/:/tmp/) in /var/www/vhosts/example.co.uk/testbed.example.co.uk/libraries/vendor/joomla/session/src/Handler/FilesystemHandler.php on line 53"

[21-Jun-2018 10:16:12] WARNING: [pool testbed.example.co.uk] child 29054 said into stderr: "NOTICE: PHP message: PHP Warning:  mkdir(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/example.co.uk/:/tmp/) in /var/www/vhosts/example.co.uk/testbed.example.co.uk/libraries/vendor/joomla/session/src/Handler/FilesystemHandler.php on line 55"

The value for open_basedir = {WEBSPACEROOT}{/}{:}{TMP}{/}

the exact same webhost has no issues with a J3.8 install<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20821">issues.joomla.org/tracker/joomla-cms/20821</a>.</sub>

**Comment by Twincarb** [comment]
Changing open_basedir = none allows the install to carry on<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20821">issues.joomla.org/tracker/joomla-cms/20821</a>.</sub>

**Comment by brianteeman** [comment]
@Kubik-Rubik could you take a look at this please

**Comment by Kubik-Rubik** [comment]
@brianteeman Yes, I will check tomorrow morning. Thank you for mentioning me!

**Comment by brianteeman** [comment]
if there is a plesk expert then we should take advantage of their expertise - thanks buddy

**Comment by Kubik-Rubik** [comment]
Okay, just analysed it in detail, this happens due to security restrictions in Plesk's PHP handler.

You need to add the path _/var/lib/php/session_ to the **open_basedir** value to be able to start the installation process in Joomla! 4.

Go to the PHP settings and change the **open_basedir** value to:

`{WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php{/}session{/}`

**TODO** We should check why this is required in Joomla! 4 but not in all previous versions!

Before:

![screenshot 2018-07-16 13 07 56](https://user-images.githubusercontent.com/1976103/42755963-6b34bce0-88fa-11e8-81b6-ed65e985cc76.png)

After:

![screenshot 2018-07-16 13 11 40](https://user-images.githubusercontent.com/1976103/42755969-748e199e-88fa-11e8-8c23-3e629dd92a80.png)

See here for more information: https://support.plesk.com/hc/en-us/articles/115000278993-A-website-hosted-in-Plesk-is-not-accessible-open-basedir-restriction-in-effect

**EDIT**

We get the path diretly from the PHP settings (_libraries/vendor/joomla/session/src/Handler/FileSystemHandler.php_):

`$path = $path ?: ini_get('session.save_path');`

and the path is pre-defined to _/var/lib/php/session_ which is not writeable due to the restriction mentioned above.

Hmm, I will report this internally to Plesk's dev team and see what we can do here! Thank you for reporting this.

**Comment by brianteeman** [comment]
@Kubik-Rubik Is there anything "we" need to do

**Comment by Kubik-Rubik** [comment]
@brianteeman Not at the moment, I'm still on this topic internally. I will keep you informed here!

**Comment by brianteeman** [comment]
great - thanks

**Comment by wilsonge** [comment]
Assuming there's not much more to be done here so closing

**Comment by StefanSTS** [comment]
Hello,

I like to reopen this issue, since it is still ongoing in Joomla 4 Alpha 7.

The var/lib/php/sessions directory can be only read by root in Ubuntu 16.04. and Plesk.

A trace of the issue looks like this:

(1/1) RuntimeException
Could not create session directory "/var/lib/php/sessions"

in FilesystemHandler.php line 57
at FilesystemHandler->__construct('/var/lib/php/sessions')
in SessionFactory.php line 80
at SessionFactory->createSessionHandler(array('force_ssl' => false, 'name' => 'ea09bb364ef1bffd889e76b7a59035fc', 'expire' => 900))
in Session.php line 114
at Session->Joomla\CMS\Service\Provider\{closure}(object(Container))
in Resource.php line 175
at Resource->getInstance()
in Container.php line 96
at Container->get('Joomla\\Session\\SessionInterface')
in Application.php line 53
at Application->Joomla\CMS\Installation\Service\Provider\{closure}(object(Container))
in Resource.php line 175
at Resource->getInstance()
in Container.php line 96
at Container->get('Joomla\\CMS\\Installation\\Application\\InstallationApplication')
in app.php line 65
at require_once('/var/www/vhosts/sts-xxxxxx.de/php7x.sts-xxxxxxx.de/j4/installation/includes/app.php')
in index.php line 36

Since this is a standard setting in Plesk that seems to be set for security reasons, I guess another approach is necessary to address this problem. Setting another directory "session" with less secure settings seems like circumventing security.

This issue was not present in J 4 Alpha 4 if I am not mistaken, I happen to install only J 4 Alpha 7 on the same server after Alpha 4. The server is running J 3 versions without any issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20821">issues.joomla.org/tracker/joomla-cms/20821</a>.</sub>

**Comment by Pinkeltje** [comment]
Same here with version alpha 11.
Direct Admin
PHP 7.2.16

**Comment by wilsonge** [comment]
@Kubik-Rubik is there any plans from plesk on this subject?

**Comment by Kubik-Rubik** [comment]
@wilsonge I already discussed this with some core developers. This is not related to Plesk, but a bug in Joomla!'s filesystem handler. This problem will not only occur on Plesk servers but also on other systems (see comment above with Direct Admin). I will provide a fix for it asap!

**Comment by Kubik-Rubik** [comment]
@wilsonge @Pinkeltje @Twincarb @OrgasmicSweets 

Please test this patch: https://github.com/joomla-framework/session/pull/41

**Comment by wilsonge** [comment]
@Kubik-Rubik that makes some sense - i've dropped a comment there for some extra sanity checks however :)

**Comment by Kubik-Rubik** [comment]
@wilsonge Thanks, George. Already replied there! ;-)

**Comment by Kubik-Rubik** [comment]
The fix was merged. Thanks, George!

Issue can be closed. :-)

**Comment by wilsonge** [comment]
Merged over there. can you do a PR here to update composer. `composer update joomla/session`

**Comment by Kubik-Rubik** [comment]
Sure! Give me some minutes, need to update my fork... :-D

**Comment by alikon** [comment]
with #25424 and https://github.com/joomla-framework/session/pull/41
thanks @Kubik-Rubik<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20821">issues.joomla.org/tracker/joomla-cms/20821</a>.</sub>
