### ISSUE TITLE
[3.8] Global `Page Heading` values it is not shown

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#20846]
### Steps to reproduce the issue
- Go to `Menu - Options` and put to `Yes` the option `Show Page Heading` and write a global `Page Heading` in the option below. Save.
- Go to a menu item (preferably one that leads to an article), and check inside the `Page Display` the option `Show Page Heading` is set to `Use Global (Yes)` or simply `Yes`, also check you have the option `Page Heading` empty, in this way, the global value is taken. Save.

### Expected result
In the frontend, the global `Page Heading` values it is shown.

### Actual result
In the frontend, the global `Page Heading` values it is not shown. Instead, the title of the menu item is taken, as a page heading.

![screenshot_20180623095031](https://user-images.githubusercontent.com/3956472/41810328-aafce72c-76ca-11e8-8e02-c7d95337be78.png)
![screenshot_20180623095100](https://user-images.githubusercontent.com/3956472/41810329-ab1b4ad2-76ca-11e8-856a-74868ec688b2.png)

### System information (as much as possible)
Last staging

**Comment by DavidBoggitt** [comment]
There's also a typo with **GLOBLA** HEADING

**Comment by carlitorweb** [comment]
@DavidBoggitt I wrote that wrong when I did in the global option. 

![screenshot_20180623145545](https://user-images.githubusercontent.com/3956472/41812683-331f9da0-76f5-11e8-88dc-d15b655b2164.png)

**Comment by DavidBoggitt** [comment]
Ah, ok :)

**Comment by ReLater** [comment]
> In the frontend, the global Page Heading values it is not shown. Instead, the title of the menu item is taken, as a page heading.

That's the expected behavior. But, you are right! The settings are irritating because very very seldom a situation occurs where the global Page Heading is shown. It's something like a fallback I think.

I think one would need an additional option/parameter "Show always the global Page Heading" to stay B\C. But if the global Page Heading is not filled what then? Show the sitename or the menu title or ....?

Maybe just extending the description for the global  "Page Heading"? At the moment it's described as an "alternative".

**Comment by carlitorweb** [comment]
> That's the expected behavior

I think not @ReLater . If I define a global page heading, that is the one need shown if i leave the page heading of the menu item empty, and no the title of the menu item.

Yes, I know, are minimal cases of use of this option, but we have there, and no work as need work. I'm looking for where this value is overwritten, but still a lot to learning about J . Where do you suggest I look for find this issue?

**Comment by ReLater** [comment]
Ok, maybe it's not the expected behavior but it's the way Joomla is working for a long time now (if we are talking about articles). That's why I've added the B\C remark.

But maybe you're right.

> Where do you suggest I look for find this issue?

Normally the last decision concerning `page_heading` is made in `view.html.php`. E.g. for `com_content`:
https://github.com/joomla/joomla-cms/blob/3.8.8/components/com_content/views/article/view.html.php#L229-L238

Search also for `merge(...)`-calls in the article model and `view.html.php` to find the lines where params are merged (= "overwritten by others")!

During a quick&dirty debug I couldn't find a place where the global `page_heading` occurs in any `params`.

**Comment by carlitorweb** [comment]
Thank @ReLater

**Comment by brianteeman** [comment]
From my perspective the error is that there is the option to set  PAGE HEADING in the global options. That option is only intended to be an override to the default text (if show page heading is on) so you would only ever set it on a menu item and not globally

**Comment by carlitorweb** [comment]
By default, every menu item, come with `Use Global`, so, in terms of saving time, this option can help you. But the reality is this option almost does not have many cases of uses, so I agree, it is unnecessary. But, we can´t remove, because of B/C right?

**Comment by brianteeman** [comment]
If the field "Page Heading" is never used (as opposed to "Show Page Heading") then it probably can be removed. BUT just in case someone was re-purposing that field for something else it would be classed as a B/C break so could only be removed in J4

**Comment by carlitorweb** [comment]
Anyway, is not work now. And i not test on J4 yet, but sure there have same issue

**Comment by brianteeman** [comment]
As I said - its not so much it doesn't work as it shouldnt have been there in the first place. Its a copy&paste bug that it is offered as an option in the xml for the global

**Comment by SharkyKZ** [comment]
Global option is used when accessing components directly (without menu item). The issue is that `Use Global` placeholder was added to menu item form by mistake.

**Comment by SharkyKZ** [comment]
Test PR #21095 please.

**Comment by ghost** [comment]
closed as having Pull Request #21095
