### ISSUE TITLE
Drone failures

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21050]
getting really sick of seeing the following drone failure

>  [ConnectionException] Can't connect to Webdriver at http://127.0.0.1:4444/wd/hub. Please make sure that Selenium Server or PhantomJS is running.

**Comment by zero-24** [comment]
I'm sorry to say but that part it out of my control of drone. In some cases a reboot of the tests help but this is definitely not the final solution.

**Comment by brianteeman** [comment]
Well someone needs to fix it

**Comment by mbabker** [comment]
Same groan as in https://github.com/joomla/joomla-cms/issues/20927#issuecomment-401480129

In general, we're getting way too many false positives on the CI systems.

**Comment by zero-24** [comment]
> In general, we're getting way too many false positives on the CI systems.

Just for the record in general the CI systems works very great ;) Just one part of that test process has problems and this is not a issue about drone. That kind of tests don't run on travis at all when I remember correctly.

**Comment by mbabker** [comment]
I'm not saying the tests are bad.  I'm not saying the systems are bad.  I'm saying that far too frequently Drone and AppVeyor at least are failing for no good reason (AppVeyor timing out on the PHP 5.6 builds for 3.x, the reoccurring JS test failure on 3.x, etc.).  Those are the types of issues that we need to be looking at.  To be frank I'm merging way too many pull requests that have a failing CI pass because I'm not going to sit there and wait for Drone or AppVeyor to redo a build that failed which had no reason to fail.

**Comment by brianteeman** [comment]
it is not a failing test
it is a failure of the architecture

**Comment by brianteeman** [comment]
closing this as no one deems to be interested in looking at it and we will just keep having the same issues
