### ISSUE TITLE
Wrong order in Category Blog

### ISSUE THREAD

**Issue by maxsenft** [joomla/joomla-cms#21135]
### Steps to reproduce the issue
* Create various articles with different publish dates
* Create a Category Blog menu item with the following settings at "Blog Layout":
    * Category Order: No Order
    * Article Order: Most Recent First
    * Date for Ordering: Published

### Expected result
Articles shown sorted from last published (top) to first published (bottom).

### Actual result
Articles in a mixed up order. (At least for me) No pattern recognizable.

### System information (as much as possible)
* Joomla 3.8.10 (was updated from 2.5.x to 3.8.6 end of March)
* Own layout
* Extensions
    * Latest News Enhanced
    * Admiror Gallery
    * jDownloads
    * Cookie Hint

### Additional comments
* Affected website (Category blog website address): https://www.mss-hx.com/news-archive
* Checked SQL query in Debug mode which returns the correct result, see Joomla StackExchange Question: https://joomla.stackexchange.com/q/23120/12694

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org.

On an unrelated issue I can see that gallery you are using is inserting hidden spam links into your ssite which will drastically effect your appearance in search engines and I strongly recommend that you remove that




 
 ```
 | < div style="display:block; font-size:10px; overflow:hidden; height:1px; padding-top:1px;" >< br / >< a href="http://www.admiror-design-studio.com" target="_blank" >AdmirorGallery 5.1.1< /a >, author/s < a href="http://www.vasiljevski.com/" target="_blank" >Vasiljevski< /a > & < a href="http://www.admiror-design-studio.com" target="_blank" >Kekeljevic</a >.< br /> Website security test completed by <a href="https://www.security-audit.com">https://www.security-audit.com< /a >< /div>
  |  
```

**Comment by crystalenka** [comment]
Replying to this old ticket (sorry Brian), because I came across the same issue, and want to explain what's happening for anyone else who runs into it on J 3.x.

If you are using anything other than a core template, and you are not following the exact same display logic as Protostar:

* Go to the menu item (or global configuration) for the blog category.
* Make sure the number of columns is set to 1; or, if you use the columns parameter in your template, set the order to 'across'.
* Otherwise, Joomla rearranges the item list per every nth item before displaying it, resulting in what appears to be a random order.

I believe columns for the blog category have been removed altogether for Joomla 4 for exactly this reason. It definitely _appears_ to be a bug, but it is not.
