### ISSUE TITLE
Multibyte encoding in module params

### ISSUE THREAD

**Issue by humblehumanbeing** [joomla/joomla-cms#21146]
Many third party modules (Rockettheme's Gantry modules or Joomlart's content module, for example) store the values in the field params and those values are encoded as multibyte if they consist non-latin characters.
This naturally makes it hard to manipulate them via database.
Can Joomla devs offer a solution for this issue?

**Comment by ghost** [comment]
Can a Dev please comment on this Issue as it has Status "New" since one Week?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21146">issues.joomla.org/tracker/joomla-cms/21146</a>.</sub>

**Comment by roland-d** [comment]
@humblehumanbeing How 3rd parties store their data is not something Joomla can control. So there is no solution that can be offered from Joomla. If you need to change those settings I guess you would need to change them in the UI or do it programmatically. If you need more help with this please post it on our forum at https://forum.joomla.org

I am going to close this as this is not a Joomla issue.
