### ISSUE TITLE
[3.9] JFilterInput' not found when uploading an image through Media manager

### ISSUE THREAD

**Issue by jamgit** [joomla/joomla-cms#21288]
### Steps to reproduce the issue
1. Going to Content > Media.
2. Uploading new image, opens new area to browse for new image.
3. Find your file on computer and click on upload.

### Expected result
The image uploads and is added to the library.

### Actual result
Error shows up after steps above saying "Class 'Joomla\CMS\Filesystem\JFilterInput' not found"

### System information (as much as possible)
Mac: OS High Sierra
2.5 GHz Intel Core i7

Joomla Build is the 3.9 privacy package full dev version.

**Comment by bayareajenn** [comment]
I can duplicate this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21288">issues.joomla.org/tracker/joomla-cms/21288</a>.</sub>

**Comment by ernienet** [comment]
Duplicated in a live server environment with the 3.9 Privacy Package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21288">issues.joomla.org/tracker/joomla-cms/21288</a>.</sub>

**Comment by wjlorente** [comment]
Found this as part of testing J 3.9 Privacy Tools Suite, with a complete, fresh install from https://developer.joomla.org/privacy-pack/. Tried uploading an image via Content -> Media -> Upload. After I selected an image and clicked on the "Upload" button, Joomla returned a message "Fatal error: Class 'Joomla\CMS\Filesystem\JFilterInput' not found in /home3/nimda/public_html/dev/20180728_pbf/libraries/src/Filesystem/File.php on line 543" on an otherwise blank page.   <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21288">issues.joomla.org/tracker/joomla-cms/21288</a>.</sub>

**Comment by ggppdk** [comment]
Related PR but for J4
https://github.com/joomla/joomla-cms/pull/21174

**Comment by Sandra97** [comment]
I faced the same issue, applied the changes of the PR you're mentioning, now it works as expected.

**Comment by bayareajenn** [comment]
I applied #21174 in 3.9 and it tested successfully. If there's a separate PR for 3.9, let me know so I can update it. OR, if you want all of us to test #21174 and mark it successful, let us know so everyone else that posted in here can test also.

**Comment by wojsmol** [comment]
Please test https://github.com/joomla/joomla-cms/pull/21314

**Comment by bayareajenn** [comment]
Done @wojsmol. 

@jamgit , @ernienet and @wjlorente will you please go apply the patch with the patchtester 2.0.1 (stable) from https://github.com/joomla-extensions/patchtester/releases (install it via the extension manager) and apply the patch for #21314. Then test to see if you can add media. 

Then go to https://issues.joomla.org/tracker/joomla-cms/21314 and login and report whether it tested successfully or not (click the Test this button to do this).

**Comment by ghost** [comment]
closed as having Pull Request #21314.
