### ISSUE TITLE
Article error with TinyMCE

### ISSUE THREAD

**Issue by davidbrooksio** [joomla/joomla-cms#21308]
### Steps to reproduce the issue
Make sure your editor is set to TinyMCE. Create a new article (or edit an existing one) and set the word "Supervisor" (without quotes) as the last word in the article. Save the article.

### Expected result
Article saves as normal.

### Actual result
An error is shown "404 Category not found"

### System information (as much as possible)

PHP Built On | Linux host36.registrar-servers.com 3.10.0-714.10.2.lve1.5.17.1.el6h.x86_64 #1 SMP Tue May 22 11:27:30 EDT 2018 x86_64
-- | --
Database Type | mysql
Database Version | 10.1.31-MariaDB-cll-lve
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.2.8
Web Server | Apache
WebServer to PHP Interface | litespeed
Joomla! Version | Joomla! 3.8.10 Stable [ Amani ] 26-June-2018 15:45 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36

### Additional comments
This is an entirely bizarre error. I have used Google and found [this](https://community.tinymce.com/communityQuestion?id=90661000000QdFAAA0) but it's a year old with no solution. I have also tested this on multiple (similar) Joomla sites and got the same error.

**Comment by brianteeman** [comment]
This error is nothing to do with tinymce or the core of joomla. It is caused by one of two things

1. A security plugin that you have installed in joomla - unlikely but possible
2. the apache web server module mod_security and a faulty rule. There should be a mod_security log on your server to confirm this. If you do not have full control of the server then you will need to speak to your webhosts
3. Some other faulty security rule that your web hosts have enabled that is triggered by this word.

**Comment by davidbrooksio** [comment]
Thanks for the info @brianteeman it's much appreciated.
