### ISSUE TITLE
[4.0] Error Invalid controller class

### ISSUE THREAD

**Issue by victorantoniak** [joomla/joomla-cms#21335]
### Steps to reproduce the issue
1. Logout from admin area
2. Go to 
{YourSite}/administrator/index.php?option=com_test&controller=products

com_test - my test compenent

### Expected result
Display login form

### Actual result
An error has occurred.
0 Invalid controller class: products 

### System information (as much as possible)
Joomla 4 A4

**Comment by ghost** [comment]
Issue confirmed.

**Comment by MonkeyTrainer12** [comment]
I had an issue in Alpha4 which behaved exactly like this (custom component, same error).  For me, it turned out to be a capitalization issue in the namespace. I did not see that happen in Alpha3. I don't have a code fix, but I modified my XML and re-installed the component.

Ex: The namespace declared in the XML document was "Joomla\Component\XXX_Abc", while Joomla's Dispatcher was failing to discover the custom dispatcher in the namespace "Joomla\Component\Xxx_abc".

I hope this helps.

**Comment by laoneo** [comment]
I need something to test with to be able to fix it. If somebody has an example extension to share I will investigate the issue.

**Comment by ghazal** [comment]
Just installed Minitek Faq Book that triggers this error:
https://extensions.joomla.org/extension/minitek-faq-book/

Error : `Invalid controller class: display`

**Comment by phalouvas** [comment]
I also confirm this problem. You must uninstall/install and then problem is solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21335">issues.joomla.org/tracker/joomla-cms/21335</a>.</sub>

**Comment by SharkyKZ** [comment]
Test PR #26072 please.
