### ISSUE TITLE
[4.0] Multiple workflows

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21526]
### Steps to reproduce the issue
Install the blog sample data
Create a new workflow called blog and in the category options set the category to use the blog workflow

### Expected result
Warning before being able to change the workflow for a category that has existing content

### Actual result
No warning

### Expected result
Existing articles will probably display the state from the previous workflow and then I can go to the article and select the correct state from the list of states in the new workflow

### Actual result
Existing articles display the state from the previous workflow but then when i try to change it the dropdown shows a confusing mix of both workflows

Workflows/states/transitions used
<img width="615" alt="chrome_2018-08-10_11-14-12" src="https://user-images.githubusercontent.com/1296369/43953409-c8318b04-9c90-11e8-9de8-cc95662d717a.png">
<img width="712" alt="chrome_2018-08-10_11-14-23" src="https://user-images.githubusercontent.com/1296369/43953410-c86edec8-9c90-11e8-82f8-38f37f53a452.png">

**Comment by bembelimen** [comment]
The category is only the indicator of the starting point for a new article, after that the workflow of an article is completly separated from the selected workflow in the category.

So once assigned the workflow is not changeable for an article*. Otherwise this would make the workflow useless. Once chosen, you (as normal user) have to stick to the workflow. If you change the workflow in an category, it's for future (new) articles. So the category is just the carrier, not the enforcer.

(Writing that, I just got an idea how the sample data can be restructured for a better fit)

* as Super User you can change the workflow for an article via batch.
