### ISSUE TITLE
Search field for 'Images and Links' in administration interface

### ISSUE THREAD

**Issue by kurtroesand** [joomla/joomla-cms#21640]
I have always missed a feature like this in Joomla.

How about letting the user search for images on a server. Surley 'browse' is getting old?

Below is a mock-up.

![243tyj mf](https://user-images.githubusercontent.com/205927/44208808-d0190380-a161-11e8-94cd-b022d4148fef.png)

**Comment by brianteeman** [comment]
If only it was easy as adding a button ;)

**Comment by kurtroesand** [comment]
@brianteeman I'm going to ignore that answer. The graphic is a mock-up, and I know there are mechanics behind such a feature. I've been with this CMS since the Mambo-days. All I wanted to do was suggest a feature. A bad idea on my part apparently. :(

**Comment by ggppdk** [comment]
Here is a related PR already merged to the new media manager
https://github.com/joomla-projects/media-manager-improvement/pull/529

It works as filtering for currently open folder,
it is not as a full search of all directory structure

For such a search you would need to create an index of filenames that is stored in DB
(like how search works in your OS), otherwise you will be having a slow search every time that you search

then for every found filename, you would have a link to its folder, and folder would open in media manager with the filtering implemented by PR 
https://github.com/joomla-projects/media-manager-improvement/pull/529
being set to the specific search term

**Comment by ghost** [comment]
@kurtroesand any Comment on above Comment by @ggppdk?

**Comment by kurtroesand** [comment]
@franz-wohlkoenig The comment by @ggppdk is in the lines of how I was thinking. Ideally there should be some sort of global search.

My reason for putting this request here is that I've been testing Medium.com, and how they have implemented photo search is fantastic. Something in those lines would be amazing for Joomla and would take Joomla to the next level.

I run several news sites on Joomla with thousands of users every day. We have a lot of content and photos every day, the struggle with where to look in the folder structure is very time consuming and tiring, a search feature similar to Medium would be an amazing feature for Joomla.

And while we're on the subject of content. Isn't the `Media manager` and the `editor` more than ready to be upgraded to a 2018 standard? Fighting TinyMCE and the useless Media manager in 2018 is quite something. With Medium and Wordpress Gutenberg in mind, Joomla should really be upgraded to compete with these offerings.

Some rambling and thoughts. Thank you for reading.

**Comment by ghost** [comment]
seen https://github.com/joomla-projects/media-manager-improvement?

**Comment by kurtroesand** [comment]
@franz-wohlkoenig Thank you. Looks promising. Will keep an eye on the project.

**Comment by ghost** [comment]
@kurtroesand can you please close the Issue?
