### ISSUE TITLE
[4.0] [RFC] [Workflow] About re-adding (multi-record) buttons to toolbar based on available workflow transitions

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#21708]
How (multi-record) buttons according to transitions of current workflow like
"Publish"
"Unpublish"
"Trash"
"Needs updating"
"Some transition name 1"
"Some transition name 2"

can be re-added to the toolbar ?

please see a comment here:
https://github.com/joomla/joomla-cms/pull/21247#issuecomment-414000426

@bembelimen 

> ..., perhaps we could implement a in some way "intelligent" dropdown button, which offers transitions depending on the selected articles...

as an idea it seems good, but lets think of it 

it would be a little complex,
i mean,
we do not have such a thing for components that do not implement workflow,
where things are simpler,
and instead we use a general check on component-level ACL to decide showing the buttons

but let's say that by some extra work it is done

and then i want to set 7 items to "Trash" stage,
i select them, but the "Trash" button does not appear,
why it does not appear ?
because 1 out of the 7 does not allow be to set it to "Trash" (for whatever reason either due to ACL or due to its current stage),
do i have to start searching to find it ?, i will think it is a bug that the button is not showing, and i would be frustrated and confused

Maybe it should be just 
-- 1 configuration option at every transition configuration
"Add transition as a toolbar button"

And then also for **both** workflow and non-workflow extensions do this
the "transition execute" task or the "change state task" 
must have some intelligence and some more feedback

1. skip records not possible to change
2. Feedback that on page reload the lines (records) that could not be changed are marked

**Comment by infograf768** [comment]
Very good questions.

**Comment by lavipr** [comment]
I will tackle this task. I am also in conversation with bembelimen. 
What should happen: These four buttons will be re-added: "Publish, Unpublish, Archive, Trash". These are activated each time one or more articles are selected from the list and the corresponding transition options (e.g. set this article to "trashed") are available. When clicking the respective button, the respective transition (from the current stage to the desired stage) should be executed.

That is certainly an important question: What should happen, if several articles have been selected, which e.g. should be set to "trashed" and not all have the corresponding transition?
There are two ways to handle this, as it has been mentioned. 

1. When selecting articles, the buttons are only activated if they have the same condition goals (e.g. that the article can be set to "trashed"). Otherwise, they will be disabled again.  However, if the user is not aware of this behavior, it can be really confusing.

2. The transition should be executed on articles that have this transition to "trashed" as a possibility, otherwise the not corresponding articles should be skipped. The user gets an error message in case of a skip. However, this could also be confusing as it is not possible to see at a glance which articles have common properties in the form of 'they can both be set to trashed'. If the user is unlucky, only one of 10 selected articles will be changed to the desired state.

How do you see this?

**Comment by brianteeman** [comment]
How does it work with the batch change workflow

**Comment by bembelimen** [comment]
The batch functionality is not connected to the buttons. The batch thing was an idea to give Super User a "short cut" for changing workflows/stages on articles.

Ofc it could be used to "publish" a bunch of article, but that's just a side effect.

**Comment by brianteeman** [comment]
I meant how does the batch cope with the scenario described by @lavipr

**Comment by ghost** [comment]
closed as having Pull Request ##22393
