### ISSUE TITLE
Edit state Inherited not allowed  is ignored when an Article is edited

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#21788]
### Steps to reproduce the issue
Create a new user group with Public as parent.
In Global config set Permissions for the group ... edit Allowed
Create a new user and assign to the new user group
Login frontend with the new user
Edit an Article and save
The edited article is Published

### Expected result
The edited Article should remain unpublished until authorised the same as a created Article remains unpublished.

### Actual result
The edited Article should remain unpublished.

### Additional comments
This allows users (who's contributions to be approved) to publish unapproved changes.

**Comment by brianteeman** [comment]
System information (as much as possible)
???

**Comment by Webdongle** [comment]
=============
System Information
=============
php: Windows NT MY-COMPUTER 10.0 build 17134 (Windows 10) AMD64
dbserver: mysql
dbversion: 5.7.19
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 5.6.31
server: Apache/2.4.27 (Win64) PHP/5.6.31
sapi_name: apache2handler
version: Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

(edited to just the useful stuff)

**Comment by brianteeman** [comment]
If I understand you correctly what you are saying is that if an author edits their article after it has been published then it should revert to an unpublished state.

That has always been a limitation of Joomla as otherwise the article will be removed from display on the site.

It is one of the reasons that we have version history and hopefully is something that in a future date will be possible in joomla 4 with workflows. Currently its not as we don't support draft versions of published content

**Comment by Webdongle** [comment]
> If I understand you correctly what you are saying is that if an author edits their article after it has been published then it should revert to an unpublished state

Not exactly.  The approved (published) Article should remain published but the edit (new version) should not replace it until approved.  If a user for whatever reason) can not be trusted to create an Article without approval ... then (for the same reason) they should not be trusted to change the wording without approval.

If it is not possible to prevent the new version (without approval) to replace the approved version then so be it.

**Comment by brianteeman** [comment]
Currently it's not possible as joomla doesn't support draft versions of currently published items

**Comment by ghost** [comment]
closed as expected Behaviour. 

@Webdongle please reopen for further Discussion or open a new Issue for Feature Request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21788">issues.joomla.org/tracker/joomla-cms/21788</a>.</sub>

**Comment by Webdongle** [comment]
It is a pity that it's 'expected behaviour' because it does make the 'Edit state' redundant.  No point checking a persons original wording if they can change it to their preferred wording without approval.
