### ISSUE TITLE
[4.0] Install Languages should show only available Languages: de-DE, fa-IR, fr-FR

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21806]
### Is your feature request related to a problem?
Volunteers didn't know which Language is at this Time to install for a multilanguage Site.

![screen shot 2018-08-22 at 12 32 52](https://user-images.githubusercontent.com/8235763/44458775-8e77d500-a607-11e8-9c73-8a434354c97f.jpg)

### Describe the solution you'd like
Show only available Languages.

At the Moment:

- de-DE
- fa-IR
- fr-FR
### Additional context
If this is not possible Volunteers should get a Notice if they try to install an non-available Language like `it-IT isn't available at the Moment. Please choose de-DE, fa-IR or fr-FR.`

**Comment by mbabker** [comment]
4.0 does not yet have dedicated resources for languages, so the 3.x language list is still shown, with the hack in place to allow some capabilities to work for that list of three languages.

Personally, I wouldn't spend much time on this issue.  It'll address itself as 4.0 moves toward a stable release and dedicated architecture for the language resources is set up.

**Comment by ghost** [comment]
I'm concerning Volunteers to inform which Language is installable at the Moment. If its not possible to inform at Installation of content Languages i will let this Issue open.

**Comment by mbabker** [comment]
We can do something about it, sure.  But my main point is this is one of those things where the time it would take to do something about it is better spent elsewhere.  It is not that German, French, or Persian are the only languages available for 4.0; rather, those three languages have special handling in the 3.x update server files so they show up somewhere (I forget where exactly we needed to add this special handling).  Technically, there are no languages available for 4.0 right now and instead of showing empty or broken screens that prevent being able to test any of the language install functionality we just continue showing the 3.x data until the 4.0 system is set up.

Right now, the actual "bug" is 3.x language data is shown to a 4.0 install.  The fix to that is to set up the 4.0 language system on our `joomla.org` hosting and update 4.0 to read from that.  Until that happens, we either completely turn off the ability to install languages through a Joomla installation, or we continue showing the 3.x data.  I don't think we need to be adding extra code to account specifically for the current development status when everyone's time is better spent on other tasks to get 4.0 in a release ready state.

**Comment by ghost** [comment]
Simple Solution is to let the Info here stay; no Time waste for it.

Days ago a Volunteer asked cause he installed it-IT ... and nothing happens. Next Time Tester can find Info here.

**Comment by zero-24** [comment]
> I forget where exactly we needed to add this special handling

Found it the other day ;)

https://github.com/joomla/update.joomla.org/blob/master/translation-cli/translation_cron.php#L279-L284

**Comment by brianteeman** [comment]
> Right now, the actual "bug" is 3.x language data is shown to a 4.0 install. The fix to that is to set up the 4.0 language system on our joomla.org hosting and update 4.0 to read from that. 

Can someone add the release blocker tag to this please

**Comment by wilsonge** [comment]
Just for the record whilst this is indeed a blocker - I don't intend this to be solved for a bit yet - I'd rather we fix this when we're a bit further into beta. gives people easier capabilities to test things for now

**Comment by wilsonge** [comment]
We’ll swap this over once we launch the ability for new J4 packs to be added on the downloads site

**Comment by brianteeman** [comment]
Until resolved this is still a release blocker.

**Comment by wilsonge** [comment]
Language pack component https://github.com/joomla-extensions/pkg_languagepack has been installed on the downloads site. Currently we're working on the sync mechanism so the update XMLs go to the update.joomla.org site (i.e. a new version of this CRON Job to the GForge SOAP API https://github.com/joomla/update.joomla.org/blob/master/translation-cli/translation_cron.php)

**Comment by wilsonge** [comment]
https://github.com/joomla-extensions/pkg_languagepack/pull/43 Now the XML view exists - just a matter of copying it onto the update site. Closing this as I've build a PR that can be merged as soon as that copy job is up and running https://github.com/joomla/joomla-cms/pull/34302
