### ISSUE TITLE
Feature request: Option to use video as Full Article "image"

### ISSUE THREAD

**Issue by adankupapa** [joomla/joomla-cms#21838]
### Is your feature request related to a problem? Please describe.
With the ever-growing appetite for video content being consumed online, I think it will be an essential feature to have the additional option of using video files as **Full Article Images**. 

### Describe the solution you'd like
Allow the Joomla article image fields under **Images & Links** tab to also accept video file types in addition to the images it currently supports. This can be restricted to only the FULL ARTICLE IMAGE field so the video loads only when an article is in full view and not intro articles. 

### Additional context
The current method to add video to Joomla content is through an extension, by uploading the video on a video sharing site and embedding an iframe or by using the video ICON in TinyMCE. This places the video somewhere inside the body of the content. 

Sometimes, however, on news and tutorial websites, it is important the video is seen first on the main article page in place of **full article images.**

If this feature is implemented I think it will extend the abilities of **com_content** to be used for creating video content sites as well without the need for extra extensions. i.e sites that publish video content like music videos and tutorials. 

For your kind consideration or rejection.

**Comment by ReLater** [comment]
I myself would not like to have a feature like this in the Joomla core because it's relatively easy to implement it (more flexible than core ever could) with custom article fields and template overrides, e.g. for the JLayout full_image.php if you want the video instead of the full image.

At the moment you would need more than one video field for different video formats. Means some more new options in core...

**Comment by brianteeman** [comment]
I agree with @relater that this can be achieved with either custom fields or overrides and doesnt need to be in the core
