### ISSUE TITLE
[3.9][plg_user_terms] Revisions

### ISSUE THREAD

**Issue by Septdir** [joomla/joomla-cms#21911]
The offer is for #20800

For a long time was busy today finally appeared time to test new features 3.9 in the whole everything was very much affected, except for the User - Terms and Conditions  Plugin

1. You can select only the com_content article, it is very uncomfortable and not flexible.  
In my opinion, it would be good to add custom link fields for each language.
2. No Multilanguage field Short Terms & Conditions.
3. This is a **user** plugin that imposes a number of restrictions on the use of the field in other components.
4. I do not really like radio
5. In the plugin, note is displayed via `echo '<div class =" alert alert-info ">'. $ termsnote. '</ div>'; ` which contradicts the use of this plugin in a template written for example on uikit  
I'll have to make a hack in the template to replace the class.
6. Due to lack of layout field it is impossible to override

P.S The plugin somewhere uses namespaces and somewhere not

**Comment by ghost** [comment]
Can a experienced User please answer as this issue has Status "New" since a Week?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21911">issues.joomla.org/tracker/joomla-cms/21911</a>.</sub>

**Comment by brianteeman** [comment]
1. It is designed for com_content so that as per the documentation it can be associated with other languages
2. As per the documentation this field can be multilingual - see https://docs.joomla.org/J3.x:Privacy#User_-_Terms_and_Condition
3. It is designed as a user plugin and that's how it should work
4. Can't please everyone
5. Pull requests welcome - you dont need to hack anything though you can simply add new css to your template
6. Pull requests welcome

**Comment by Septdir** [comment]
Ok

**Comment by ghost** [comment]
@brianteeman thanks for Comment.

**Comment by ghost** [comment]
closed as issue seems answered. Please reopen if needed.
