### ISSUE TITLE
Swapped display of descriptions for optional fields in 'user registration' - frontend

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21924]
### Is your feature request related to a problem? Please describe.
This issue is related to design.

### Describe the solution you'd like
If you hover your mouse over an optional field in 'user registration' the description for every field is "Fill in some data if needed." This is absolutely useless for a regular user in frontend.
After investigating this behavior I found the following.
In file **../plugins/user/profile/profile.php** - line 259 there's an 'IF' clause:
if ($app->isClient('site')... - which I changed to: if **(!$app**->isClient('site')... 
After this the descriptions are displayed correct (separate description for each field) in frontend and one common description in 'user management' ("Fill in some data if needed.") in backend.

### Additional context

**Comment by brianteeman** [comment]
Could you please post some screenshots as I dont understand

> After this the descriptions are displayed correct (separate description for each field) in frontend and one common description in 'user management' ("Fill in some data if needed.") in backend.

**Comment by ReLater** [comment]
#### My interpretation of this issue (not more, because I never use the profile plugin):

It's like this:
If you edit you're profile in frontend, nearly all profile plugin fields get **the SAME** description:
PLG_USER_PROFILE_FILL_FIELD_DESC_SITE
See https://github.com/joomla/joomla-cms/blob/3.8.12/plugins/user/profile/profile.php#L259-L273

![31-08-_2018_20-19-10](https://user-images.githubusercontent.com/20780646/44929511-951af080-ad5b-11e8-933a-33b61ae078ad.jpg)

> This is absolutely useless for a regular user in frontend.

BTW: No way to create a field specific language override.

> which I changed to: if (!$app->isClient('site')
> After this the descriptions are displayed correct (separate description for each field)

Seperate for each field yes but not correct because the descriptions are talking about "option" and in fe these fields aren't list fields.

![31-08-_2018_20-14-07](https://user-images.githubusercontent.com/20780646/44929643-08246700-ad5c-11e8-8563-d1f82d659235.jpg)

Ergo:
It would be nice to have field specific language strings in frontend instead of one.

**Comment by ghost** [comment]
@ReLater 

> Seperate for each field yes but not correct because the descriptions are talking about "option" and in fe these fields aren't list fields.

Sorry but this is not the whole story...
I don't know where the word 'option' comes from, but the language placeholders are:
PLG_USER_PROFILE_FIELD_ABOUT_ME_DESC=
PLG_USER_PROFILE_FIELD_ADDRESS1_DESC=
PLG_USER_PROFILE_FIELD_ADRESS2_DESC=
PLG_USER_PROFILE_FIELD_CITY_DESC=
PLG_USER_PROFILE_FIELD_COUNTRY_DESC=
and so on.
**There is not a single placeholder with the word _'OPTION'_ in it.**
Since I use the German language I never had a look at the English text.
E.g. PLG_USER_PROFILE_FIELD_ABOUT_ME_DESC="Geben Sie hier etwas zu Ihrer Person ein."
As you can see there is no word 'option' (the same word in German) in the text.
Therefore I think I'm on the right track, right?  :-)
Greetz

**Comment by ReLater** [comment]
Here are the language strings that the backend uses ("Choose an option for...")
https://github.com/joomla/joomla-cms/blob/3.8.12/administrator/language/en-GB/en-GB.plg_user_profile.ini#L12-L39

and one expample why the backend form uses them
https://github.com/joomla/joomla-cms/blob/3.8.12/plugins/user/profile/profile.xml#L35

Sorry but de-De language files are not relevant for Joomla **core**.

For that reason you have to find a solution for en-GB first!

> Ergo: It would be nice to have field specific language strings in frontend instead of one.

By the way: The German language strings that you mention are partially wrong in backend

![01-09-_2018_21-06-19](https://user-images.githubusercontent.com/20780646/44949117-22794600-ae2b-11e8-8b68-131327823390.jpg)

Because one can't enter an address in the **backend settings of the plugin**.

**Comment by ReLater** [comment]
And you're right. The whole thing becomes a little bit more irritating in German when I look a these strings (backend user profile) ;-) I would expect the strings of my last image above here:

![01-09-_2018_21-15-11](https://user-images.githubusercontent.com/20780646/44949155-3bcec200-ae2c-11e8-9c05-4553ee831551.jpg)

**Comment by brianteeman** [comment]
I cant comment on the german translation - all I can say is that there is code that changes which strings are displayed depending on the location https://github.com/joomla/joomla-cms/blob/54de7825117de7868ca10ad0553814a9dd6f400e/plugins/user/profile/profile.php#L256

**Comment by ghost** [comment]
@ReLater 

> For that reason you have to find a solution for en-GB first!
**The solution for en-GB is the same as for any other language.**

If you swap the description strings from backend to frontend and vice versa, everything is fine.

Let me say it again: The word 'option' in the English string comes from a guy who obviously didn't know what to fill in there !?
The language placeholder e.g. PLG_USER_PROFILE_FIELD_ABOUT_ME_DESC="" from the original en-GB.plg_user_profile.ini file does NOT contain the word 'option' and so it has not to be part of the text string. (This also applies to the other placeholders in this context.)
In my case I will change the profile.php file with every new release of joomla.
And to say it clear again: These discussions take me a lot of time and I don't see any result.
So please forget it and close it.
Thank you
madmetz

**Comment by ReLater** [comment]
> And to say it clear again: These discussions take me a lot of time and I don't see any result.

The solution is simple. Provide a pr and people can test it! And if it's good it will be merged.
Your proposed solution above is NOT correct. I've tested it in en-GB and de-DE (and wasted MY time in the end).
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests
