### ISSUE TITLE
[4.0] Can't trash articles

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#21959]
### Steps to reproduce the issue
Try to trash an article.

### Actual result
Message Article trashed -> OK
Select : Table Options->Select states->Trashed
Nothing.

Article not removed.

PHP 7.2.5
Built of Sunday, 02 September 2018
Issue close to #21935

**Comment by ghost** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21959">issues.joomla.org/tracker/joomla-cms/21959</a>.</sub>

**Comment by ghazal** [comment]
Ooops. Tks.

**Comment by bembelimen** [comment]
The trash button has to be removed, because that's not the behaviour anymore, how articles will be trashed. Sadly the PR [here](https://github.com/joomla/joomla-cms/pull/21532) was closed, so there is still this useless and confusing button available.

We're working on a new behaviour at the moment (and the buttons will come back with new functionallity), which needs some time. For now (and in the future) you can trash an article with the state/stage-change functionality...

**Comment by brianteeman** [comment]
:(

**Comment by PhilETaylor** [comment]
Confirmed.

**Comment by bembelimen** [comment]
Combine https://github.com/joomla/joomla-cms/pull/22393 and https://github.com/joomla/joomla-cms/pull/21532

**Comment by bembelimen** [comment]
#22393 is merged, now only #21532 is missing to solve this issue.

**Comment by bahl24** [comment]
It has been fixed in recent update, kindly check

**Comment by ghost** [comment]
closed as stated above. Thanks for Info @bahl24
