### ISSUE TITLE
[4.0] Dashboard - Joomla Helpscreen

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21990]
### What needs to be fixed
Migrated issue from
https://github.com/joomla/40-backend-template/issues/419

1) Joomla Helpscreen with space to do a volunteer announcement
![joomla4-dashboard-help](https://user-images.githubusercontent.com/828371/40282758-2f9afb70-5c74-11e8-94b4-ead9b90eb4c9.png)

2) Mobile example (Icons at the bottom not correct yet)
<img width="332" alt="grafik" src="https://user-images.githubusercontent.com/828371/40282763-3fb468ca-5c74-11e8-9a13-f6b29d2eb5e9.png">

**Comment by brianteeman** [comment]
I am against this concept. Most users don't care. It's the same argument used by others against adding notifications about upcoming joomla events.

**Comment by mbabker** [comment]
The Joomla backend is not a place to be advertising for the project, even if it is meant with the best of intentions; not every consumer of the software is interested in contributing to open source software or willing to engage in volunteerism.  FWIW I feel this way about all CMS', it's most assuredly not appropriate to put a half-screen "beta test our software" prompt on the dashboard either.

![screen shot 2018-07-25 at 4 07 20 pm](https://user-images.githubusercontent.com/368545/45031011-4ac39900-b013-11e8-9209-6fa3fe8170b9.png)

**Comment by alikon** [comment]
no please no,  don't spam

**Comment by ghost** [comment]
It's fine if Admin can deactivate volunteer announcement.

**Comment by coolcat-creations** [comment]
This is the help dashboard, not the dashboard where you entry the site

> I am against this concept. Most users don't care. It's the same argument used by others against adding notifications about upcoming joomla events.

@brianteeman strange you did not have the concerns during the last 11 months knowing the draft.

**Comment by zero-24** [comment]
hmm i don't get what is wrong? As far as i can see this is only displayed on the site where you can get help and where we also promote our shop / community sites etc.

The
> "beta test our software" prompt on the dashboard

from the other CMS can't be compared here. As in WP it is thrown at anyone and here it is very decent on the page where you search for help anyway.

> It's fine if Admin can deactivate volunteer announcement.

As far as it looks to me this would be some kind of image we could ship with the CMS Update or load from our servers. Not an announcement like a post install or similiar so what would you like to disable here?

> no please no, don't spam

Where do we spam on that page. As far as i can see it is not planed to be done the WP way but very decent on the page you look when you need help?

**Comment by alikon** [comment]
it is allowed to have an opinion?  even if  is different from the common feeling ? or not 

for example
what is Joomla service providers ??? or Joomla events ???  for me  is spam

**Comment by zero-24** [comment]
> it is allowed to have an opinion? even if is different from the common feeling ? or not

Sorry this wasn't meant to be offensive. I would just know what you mean with spam there.

**Comment by mbabker** [comment]
If we start allowing even static links that are pushing folks to be contributors instead of being OK with them being "only" users, this could be alienating to folks who are really only here to use the software.  They don't care about the community politics, they don't know or care what a "Joomler" is, they don't care about the all volunteer aspect of the software, they just want the software to work.  It also sets precedence to go back and renege on every request we have declined for more marketing in the Joomla backend; live feeds from the volunteer portal, or a category on one of the sites to be able to push articles to the dashboard, or a release status module (all things that have been suggested FWIW).

The Joomla backend should be about use of the software first (dare I say only?).  There should be very little if any engagement points from the project to our userbase regarding getting them to interact with the project in any way.  The stats collection system is about the extent of where I think we should go in that regard, and that is acceptable because it is supposed to help make data driven decisions as it relates to the software project management.

I get people want us to introduce new ways to engage users and potentially encourage new volunteers.  I do not think a website's administration panel is the place to do this.  It is their website, not our marketing or outreach arm.  So it doesn't matter if this type of engagement is the first thing users see or if it's buried on a third level page (and FWIW there is statistical evidence to support that this help section is decently visited by end users), IMO it is just not appropriate to be included at all.

**Comment by zero-24** [comment]
ok fully get your point. Thanks.

**Comment by brianteeman** [comment]
> @brianteeman strange you did not have the concerns during the last 11 months knowing the draft.

Like @mbabker I have always been against this type of thing and have consistently said so on this tracker.

**Comment by coolcat-creations** [comment]
> what is Joomla service providers ??? or Joomla events ??? for me is spam

It's kind of the same contents you have now on the help menu but designed in a overview

**Comment by coolcat-creations** [comment]
![grafik](https://user-images.githubusercontent.com/828371/45053236-aa5c8b80-b089-11e8-8d24-314b4ae95c02.png)
Here you see the Joomla 3.x Help Menu - Also with Resources = Service Providers and the Community Portal which contains the Joomla Events...

**Comment by mbabker** [comment]
Presentation matters here.  The current help menu provides some generic links.  With the design as proposed the page takes on a very pushy "we want you to engage our community" feel.  Not to mention the design as proposed is adding a lot more links, subjectively many could be considered spam if you are in that group of "just give me the software and keep your marketing efforts out of my site" users.

**Comment by alikon** [comment]
please forgive if i can showed myself harsh ,  and don't get me wrong, i'm only expressing my personal feelings
i really appreciate the innovation efforts
again for me this is simply wrong
we should not act like google or apple ect....

a personal/client web site don't need this imho
and if we have done this in the past (3.x) we have done this  wrong
this is for me always wrong  it's a personal site not a damned community site

**Comment by brianteeman** [comment]
Here is an apple. I know we gave you an orange before but I am sure you will agree they are basically the same.

Said no one ever

**Comment by coolcat-creations** [comment]
> Presentation matters here. The current help menu provides some generic links. With the design as proposed the page takes on a very pushy "we want you to engage our community" feel. Not to mention the design as proposed is adding a lot more links, subjectively many could be considered spam if you are in that group of "just give me the software and keep your marketing efforts out of my site" users.

I thought that was one of the marketing objectives and pains in Joomla that there are not enough volunteers... According to what you are saying it seems I misunderstood the briefing and also the people that were approving and coworking with me on all the screens. (@ciar4n, @dgrammatiko, Lukas, @wilsonge and @brianteeman and more )

**Comment by brianteeman** [comment]
I never agreed or approved anything

**Comment by mbabker** [comment]
> I thought that was one of the marketing objectives and pains in Joomla that there are not enough volunteers

That is one of the current pain points.  For years though, as every suggestion has come up regarding adding some kind of outreach platform to the Joomla site backend, I have consistently raised these same issues (they've been raised on this repo and the marketing repo).  There are a few things I believe strongly in when it comes to Joomla:

- The main `www` site should be focused on our software first and community second (keep the advertisements and distractions minimal there as we're trying to sell users on our platform)
- The downloads site should always first steer users toward downloading the software and second toward hosting with a partner (advertisements and distractions should be minimal here too, targeted toward those two main action paths)
- A user's administration panel in Joomla should be about managing their installation, not a marketing or community outreach system (it is "our" software but it is not "our" space to push a message)

Yes, volunteer recruitment and community engagement are important.  No, we shouldn't be pushing (forcing?) that onto end users.  Let those who want to use the software for the software's benefits use the software without being pulled into the community, there is absolutely nothing wrong with that.

Now with all of that said, if someone can provide strong evidence that users and consumers of the software really would not mind this type of outreach and promotional material in the platform (and this would have to be data beyond the usual circle of Joomla friends and contributors), I will gladly change my stance on this matter and support it.  But until then, I stand by my belief that we need to keep marketing of the Joomla community out of the Joomla software.

**Comment by alikon** [comment]
> I thought that was one of the marketing objectives and pains in Joomla that there are not enough volunteers..

this is sadly true,  but  this it is the wrong way to approach this issue imho

**Comment by brianteeman** [comment]
By the same token where is your strong evidence that it would be welcomed

**Comment by coolcat-creations** [comment]
> I never agreed or approved anything

🤔 Very confusing... there was someone with your name in our team

**Comment by alikon** [comment]
if you start an new issue in a public repository, whatever has been discussued on silos/teams/private
have no value now imho

**Comment by coolcat-creations** [comment]
> if you start an new issue in a public repository, whatever has been discussued on silos/teams/private
have no value now imho

Yes, you're right and I'm really open to any opinion, and for me the goal is that something finally moves forward - it can go one way or the other, the main goal is that it will be great. But certain people who speak against literally EVERYTHING that has already been discussed in a team, because they have some personal differences, should just take a deep breath.....

**Comment by mbabker** [comment]
Not all of us can be involved in every team to raise concerns.  Tried it once before.  My life literally became Joomla, paid work, and 2-3 hours of sleep nightly for months on end.  Wouldn't recommend it.

**Comment by coolcat-creations** [comment]
@mbabker wasn't talking about you... But anyway I am surprised the main production team did not look at the prototype which was shared in November 2017 and where the work on the backend team was based on. Lots of people had read the article and made comments. The Joomla40 Backend Issues were mostly unanswered too,... and now suddently this and that is not working for you. 

Whatever... we are here now to talk about it and to solve it.

**Comment by alikon** [comment]
discussed in a team/silos/ doesn't always means that it is the right thing, 
maybe, 
more often it is the wrong thing, at least , this is my personal experience working in a closed source environement, and this is why i like open source

**Comment by coolcat-creations** [comment]
https://magazine.joomla.org/item/3289-episode-iv-a-new-user-interface-for-the-joomla-backend That is not an closed environment and contains a full prototype of all posted screens (and even more)

Just read the first comments to see who liked it... ;)

**Comment by alikon** [comment]
please, the magazine.... is not a place for serious discussion i think, but .....ok
i'm over too much words for nothing...i'll better spent my free time on something more open and constructive

**Comment by coolcat-creations** [comment]
@alikon - I hear you - but that was not my decision ;)

**Comment by Sandra97** [comment]
I am personally against (and I've always been) displaying any "marketing" messages in the backend of Joomla. The backend is not for me a place to display any ads, Joomla events, call for volunteers messages, call for donations or anything of this kind. It's a place of work, which belongs to users and it would be annoying to them to have that kind of messages in their backend. Let them just use the software to create their sites. If they want to get involved, let them take the decision, without, in a way, 'forcing' them.

And yes we lack of volunteers everywhere, we lack of budget and for sure we need solutions, but this is not for me an acceptable solution to achieve that. We're too often applying patch aids to our issues, it solves nothing on the long term.
I know that in J3 backend we already have a link to the shop, it's already not relevant for me to have it in the 'Help Menu'.

Then, if a large survey among users demonstrates that they would be ok to have this kind of messages in their backend, fine, we can do it. Until then, please, no marketing messages in the backend.

**Comment by micker** [comment]
hello against me too .. WP is a nightmare for this message type ....
maybe an other solution create a view for this
-> in mainemenu "About joomla" -> a view with promote message only for joomla! communication (volumnteers, security bug squad, testing message, github working jed etc)

**Comment by jeckodevelopment** [comment]
Personally against this type of "advertising", even if it's done for the good of the project. The intention is great, but the way is a bit invasive.

Regarding:


![](https://user-images.githubusercontent.com/828371/45053236-aa5c8b80-b089-11e8-8d24-314b4ae95c02.png)

Honestly i'd remove:
- Resources
- Stack Exchange
- Joomla Shop

**Comment by coolcat-creations** [comment]
Do you all who are against it click ever on the help menu item to get help?

Most Joomla users even don’t know there is a community. Lots of hosters offer software installation. Or Joomla gets installed by their service providers. A huge amount of users get never in touch with a Joomla property. 

You would never get annoyed by this screen because you don’t use it. When was the last time you clicked on it in J 3.x ? 

I can just offer advise from a professional perspective that this is needed. But if so much are against it - we can close the issue.

Someone needs to design another help dashboard that fits your needs. Maybe someone can write down a briefing.

**Comment by brianteeman** [comment]
> Most Joomla users even don’t know there is a community. Lots of hosters offer software installation. Or Joomla gets installed by their service providers. A huge amount of users get never in touch with a Joomla property.

And why should they? 

> You would never get annoyed by this screen because you don’t use it. When was the last time you clicked on it in J 3.x ?

Because there is no screen in J3 - just a menu - and thee contents of that menu are very  different to the contents of this screen

**Comment by mbabker** [comment]
The help dashboard should be steered toward providing the user assistance with using the software.  The proposal in your screenshot is heavily steered toward the project getting volunteer help from users first, then providing help for using the software second.

The problem isn't in making sure users can find the help they need.  The problem is in presenting this help screen in a way where it has a very heavy push toward engaging in the community and this project's daily activity (volunteer recruitment).  That is the part we are saying needs to be backed down on.  Nobody is saying to not provide a help dashboard, but seriously, how are the "Meet Joomlers" (again, what is a Joomler if you aren't already engaged in the volunteer community?) and "Get Involved" lists doing anything to help end users?

**Comment by fancyFranci** [comment]
Opinion of a noob: It is really not easy finding a way into Joomla and the community. Maybe all the experts forgot that or never had this problem. So you could show the entrance door at least. Just one tiny button. No user will complain about this type of "advertisment" in the goddamn help screen. I have to admit talking about "Joomlers" is a bit too much.
Besides that, the community is a help. The issue tracker is helpful, glip is helpful, the stack exchange is (sometimes really) helpful, even Joomla events are helpful. I know this because I need a lot of help! :smile: 
Maybe the image is too heavy? In relation to the blank design.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21990">issues.joomla.org/tracker/joomla-cms/21990</a>.</sub>

**Comment by mbabker** [comment]
> Opinion of a noob: It is really not easy finding a way into Joomla and the community. [...] So you could show the entrance door at least.

But does that door really belong in our software though?  That's the point some of us are making.  Sure, there are users who may be interested in engaging with the community, but I will suggest (won't guarantee given a massive lack of data) that those individuals are in the very small minority compared to those who just want to use the software.  If you apply the 80/20 rule here, I doubt those who would welcome this kind of onboarding in the software would even fill the 20 side of that measurement.

I'm not opposed to providing help resources in the Joomla backend.  We already do that, and what we have in 3.x is IMO more than enough.  I am opposed though to adding resources that really start screaming "you should volunteer with the community" as if everyone who uses the software should be obligated to contribute to Joomla or the Open Source Software community in some form.  And it's a very thin line deciding what resources apply as help resources and what resources apply as volunteer onboarding resources.  FWIW I'd say Glip (RingCentral) is definitely not a help resource; it's an invite only platform and it is predominantly steered toward project and community management and orchestration, not a user support channel.

**Comment by laoneo** [comment]
People who want to engage with the community, will find their way. There is no need to advertise that in our product. Links which do redirect you to a help site are fine IMO.

**Comment by asika32764** [comment]
+1 for against.

Joomla users will find their local community for help first because they speak different language and not everyone has enough English skill to communicate with global community.

So we can let the local community help us to promote global events and volunteers.

**Comment by brianteeman** [comment]
Bumping this. 
At the time it was posted the production department director, the OSM secretary, the marketing director and several active contributors all said that this should not be done. Yet it was and then was merged :(

**Comment by alikon** [comment]
It's already been reported elsewhere  ?
edit issue
![ezgif-1-9465bee5e08d](https://user-images.githubusercontent.com/181681/63578964-e128fb80-c591-11e9-9ec8-c0f1560afadf.gif)
unpublish issue
![2nd](https://user-images.githubusercontent.com/181681/63579283-8f34a580-c592-11e9-9aa8-f143fcec5650.gif)

**Comment by brianteeman** [comment]
That's a different issue. Please create a new post for it.

**Comment by alikon** [comment]
done #25993

**Comment by Sandra97** [comment]
I haven't changed my mind on this. IMHO, the backend should not be a marketing tool to promote our user groups, community events, or whatever work done by the community. We should be better to focus to have a real marketing, done properly and professionally (I'm dreaming again). Remember that most people are using J! under recommandation of the agency who created the site and they don't care at all about that kind of message. 
Would be better to run a survey asking the users how they feel about having marketing in their Joomla backend, and then, at least you can take a decision relying on data.

It seems explaining why many of us think it's a bad idea has just been ignored...

**Comment by HLeithner** [comment]
I'm not sure why so many people are against this screen, maybe I don't understand there concerns.

But going to the fact that Joomla is 100% community driven we need volunteers, our software is the first place they really interact with us.

In the current implementation we have 4 new points
* Meet Joomlers
* Get Involved
  * Issue Tracker
  * Joomla on Github (Which is basically the same as Issue Tracker)
  * Glip

One concern is that we don't want not help full links in the help dashboard.
In the current help menu we have
* Joomla extensions
* Joomla translations
* Joomla Resources
* Security Centre
* Developer Resources
* Joomla! Shop

All these entries don't help the  user.

Another mention was that the user gets the website from an agency. We have Joomla! Resources in the help menu driving the customer directly to the competition. Not sure if Agencies like this.

Finally the agency can remove any link from this dashboard and add there own resources.

Coming back to the new entries
* Meet Joomlers - Event and Jug
Is the most important step for non company users. People come to the user group and ask for help, they come to the Joomla event and ask for help (for ex. JDay DE has the "Dr. Joomla" multiple community members helping users with Joomla problems on the event)
* Get Involved
if the problem is the wording it can be changed
  * Issue Tracker
  * Joomla on Github (Which is basically the same as Issue Tracker)
Maybe one of them is enough but telling the user where to report a bug shouldn't be a problem
  * Glip
Ok that's really "community" only, but if you look at the d-a-ch chat you see many help queries and answers.

As a non community member several years ago only using joomla the only way to help was joining the jbs and the skype channel and an irc channel everything else was not in my interested or I didn't know that it exists. For example our local usergroup, I joined this group after visiting the 2nd Joomla Day Austria (I didn't noticed that there was a first one). Also I didn't know that there is a usergroup in Vienna. Now I'm one of the organizers for the jday and the jug. 

I simply came late to the party because I didn't know that it exists.

So I see no negative call to action in this screen. If there is something strange then its the resource directory and the shop link.

Anyway thats my personal opinion and has nothing to do with the merge or production.

**Comment by chmst** [comment]
My2Cent: 
The documentation needs some love and effort to show that and how this page can be adapted for individual projects. It is true that agencies should replace the content by their own links and offers.

The possibilites to adapt the menu are a huge improvment and so important for v4.0 but are not presented in announcements.

**Comment by alikon** [comment]
> But going to the fact that Joomla is 100% community driven we need volunteers, our software is the first place they really interact with us.

so a software product is became a recruit medium ? really ?, simply fully  disagree, the fault and countermeasure should be found elsewhere, not in the product
P.S 
Joomla is 100% community driven ? are you sure ? if this was true maybe this should'nt have been merged cause a lot of us disagree

**Comment by bembelimen** [comment]
I personally don't see it as an advertising or recruitment page, but beside as the mentioned links "Shop" and "Ressources" all other links are places where people can get help. That was the main focus when the page was created. Shop + Ressources were taken over from J! 3, but the new links are always in the context of: can a user get help there and does it benefit the user?

But what I would like to see here is that the internal Joomla! help is more highlighted and probably the "get involved" is renamed in a "non-recruitment manner".

**Comment by B3nito** [comment]
I like that you see there what possible in Joomla univers. Maybe make the survey in facebook to see if users like or not like. Github is not place for endusers and so it is not place for ask for right way.

**Comment by mbabker** [comment]
> But going to the fact that Joomla is 100% community driven we need volunteers, our software is the first place they really interact with us.

This operates under the assumption that every user of the software wants to engage with the community.  Please provide data that supports this impression.

An end user of the software should not be put into a marketing pipeline to get them to engage in the community and play into people's altruistic tendencies.  In fact, I would say that this type of engagement is the worst thing that can be added to the software given the state of the community and how toxic it is these days.

Yes, there are some other promotional links already in the backend.  I'd suggest that those be reviewed and limited to links that are actually beneficial to the end user and their use of the software.  I think based on the partial list presented earlier, that would be removing the links to the Shop, links related to events and/or meetups, "Meet Joomlers" (which I assume is the Volunteers Portal which again has nothing to do with the use of the software) and anything related to Glip (since it is an invite only platform for the inner circle); if it is decided to have a link to a chat platform then it should be one that is publicly accessible and not behind some form of gate.

I don't think anyone who disagrees with the introduction of these marketing resources into the software is of the stance that Joomla should not do any outreach to try and engage new volunteers.  But, the software is not the recruiting platform for new free labor on behalf of Open Source Matters, Inc.  The software is a location for end users of the software to conduct their business, they should not feel pressured into giving back.

> Github is not place for endusers and so it is not place for ask for right way.

GitHub is the project's canonical issue tracking platform, wherein bug reports pertaining to the software, feature requests, and feature proposals (pull requests) are to be presented.  This platform is the appropriate place for discussions pertaining to the software.  You must pick one canonical place to coordinate efforts around otherwise you are creating a fragmented community.  The use of social media is going to attract the attention of one segment of the community, the use of GitHub will attract another segment of the community, and the use of the forums will attract another segment of the community; there may be some overlap across those three places (and maybe others) but the point here is it is three fragmented mediums targeting three (mostly) separate groups.

> Joomla is 100% community driven ? are you sure ? if this was true maybe this should'nt have been merged cause a lot of us disagree

I stopped agreeing with this "community driven" approach about 2 years ago when it became crystal clear that the direction of the software was that of a very small group of people operating behind closed doors.

**Comment by mbabker** [comment]
I'm just going to tack something else on here.  It has now been a year since this issue was originally opened and the vocal viewpoints of "please re-think this" expressed.  Yet the team that worked on the template introduced this against all feedback.  The template proposal has existed for over 18 months now.  In that time, has anyone actually thought about ways to solicit feedback on this idea, or other changes in the template or 4.0 in general, or has the operating motive been "this is what was in Elisa's design proposal, minus feedback within our internal template group this is what we are rolling with"?

Part of the problem that is trying to be solved with this screen is engaging new users to contribute to the project and community.  Is that effort ending at "let's put a screen in the admin panel", or is there legitimate interest in engaging people to contribute to the project and community?  Because if there were a legitimate interest, there is a lot more effort that people could put in to solicit feedback (like all the failed attempts at some kind of survey team) to be more proactive and not just hope people flock to the project out of the good will in their hearts.

**Comment by HLeithner** [comment]
In my opinion this is not a recruiting page. Nothing engage you to help Joomla everything helps you to find help.

That the wording of "get involved" maybe is aggressive or goes into the wrong direction is true. Also "Meet Joomlers" could be more "Find local help".

But where do you see an call to action request?

That we use a closed platform to chat is another thing an could truly removed.

So maybe we get a consent what should be in this screen and what should be removed?

But maybe this isn't the correct place to ask because I think none of use needs this page as Benito already stated.

**Comment by chmst** [comment]
Remove the link to the shop and rename "get involved" to "For developers"?

**Comment by mbabker** [comment]
"Meet Joomlers" needs to change to something that does not use inner circle terminology.  Since this box is aimed at helping people find other people to interact with, the links for JUGs and Events are OK in this context.  As much as I think the links in the software should be relevant to the use of the software, I think you can justify the links in this box by helping users to network with one another and share knowledge about working with Joomla.

All links on the page need to be crystal clear what they are linking to, or introduce some kind of short description for the links if you can't make it clear with 2-3 words.  WTF is "Joomla Resources"?  Is it books, training material, marketing material, etc. ("Resources Directory" isn't any better).  It's even worse that there's a "Resources" box right next to it.  And honestly, I'd move the JRD link into "Find help" because that site isn't meant to be a networking site.

The news box should link the release announcements and security center only.  The community blog is not a relevant resource for the use of Joomla, likewise with the newsletter (if you are hell bent and determined to link a newsletter, I would suggest a low volume newsletter specific for releases and use that newsletter as a means to link to other resources periodically, but not turn that into a marketing spam fest like the release announcements are right now).

Drop the shop link from the resources box.  Again, nothing to do with the actual use of the software.  Move either the "Joomla on GitHub" or the "Issue Tracker" link here, there is no harm direct linking end users to this resource as it may encourage them to direct report bugs they encounter or make suggestions for improvements instead of just posting at Facebook or Twitter and hoping someone does something with it.

Add a link to the training section of CJO to the resources box.

I think the get Involved box really just needs to go.  Once you move the issue tracker link to resources, there's nothing really there worth consuming as a user of the software (Glip is invite only, you don't need two links for GitHub/issues, and CJO is again a non-software related thing and with the other links to specific sections of that site users are already finding their way there in ways that are more relevant to them in the context of the CMS backend).  If you're hell bent and determined to keep this box, then link to more direct resources than the vague links that are there now (i.e. "Help Translate" with link to Crowdin), the intent being to put people at spots that they can immediately take action; with Glip being closed off linking to that just gives them marketing exposure without any benefit to the project, and just linking to anything Joomla on GitHub is too vague without better use of features like the default label GitHub suggests for a good first issue, or pinned issues on the repositories, or effective use of projects (both at org and repo levels).  I'd say linking to the roadmap page might be useful here too, but that implies there's an actual roadmap and the data there is actually kept up to date.

**Comment by brianteeman** [comment]
> add a link to the training section of CJO to the resources box.

No point in doing that. The trading videos have never been updated and are very out of date

**Comment by alikon** [comment]
Can we close this ?

**Comment by brianteeman** [comment]
Personally speaking this issue is not resolved

**Comment by brianteeman** [comment]
Looks like everything is now resolved here

**Comment by coolcat-creations** [comment]
closing as not relavant anymore
