### ISSUE TITLE
[4.0] System Settings - Install Extension #431

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#22002]
Migrated Issue from: https://github.com/joomla/40-backend-template/issues/431

![joomla system settings install](https://user-images.githubusercontent.com/828371/40283406-e1676290-5c7d-11e8-8a23-98d76cd17c11.png)

**Comment by brianteeman** [comment]
1. What happens if you don't have one of the install plugins enabled - specifically the install from jed which will be blocked often due to firewalls

2. Discover has been added here. Is that just a link to `administrator/index.php?option=com_installer&view=discover`

**Comment by mbabker** [comment]
Also keep in mind that since 3.6 the ordering of the install options has been based on the plugin ordering (and is true of install from web in the upcoming standalone release for 3.x and the merged version in 4.0).  So we probably can't pull off a layout exactly as this, but the layout components that each plugin produces could be made to lay themselves out this way.

Also keep in mind that install from web is really optimized to be a full screen thing on its own.  Trying to make it a 50% width element would require some drastic rethinking of how its data is conveyed.

**Comment by alikon** [comment]
related to the old template, open a new issue if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22002">issues.joomla.org/tracker/joomla-cms/22002</a>.</sub>
