### ISSUE TITLE
ReCAPTCHA v2

### ISSUE THREAD

**Issue by titanwww** [joomla/joomla-cms#22041]
### Steps to reproduce the issue

on page 2 and more google ReCAPTCHA  v2 (1 key public and 1 key private)

### Expected result
empty page

### Actual result
all page

### System information (as much as possible)

Uncaught Error: ReCAPTCHA placeholder element must be empty

### Additional comments
joomla 3.8.11 work no probleb

**Comment by ghost** [comment]
changed Title to show what this Issue is about. But i didn't understand what is meant, maybe another one get it and if not, @titanwww can you please give more Information, maybe Screenshots to show what you mean?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22041">issues.joomla.org/tracker/joomla-cms/22041</a>.</sub>

**Comment by titanwww** [comment]
![joomla 3 8 11](https://user-images.githubusercontent.com/43069458/45223524-2b04cd00-b2c0-11e8-8c67-287764ef105d.png)
joomla 3.8.11

**Comment by titanwww** [comment]
![joomla 3 8 12](https://user-images.githubusercontent.com/43069458/45223740-bed69900-b2c0-11e8-8db6-6f21a7f52fe4.png)
joomla 3.8.12

**Comment by brianteeman** [comment]
#21979  ??

**Comment by mbabker** [comment]
> #21979 ??

If I'm reading that and its referenced issue right that only affects the 3.9 branch after the invisible captcha merge.

**Comment by titanwww** [comment]
3.8.11 normal work. 3.8.12 - 2 and more capcha on 1 page-  error

**Comment by titanwww** [comment]
component rsform pro 2.0.14 version

**Comment by ghost** [comment]
closed as having Pull Request #22270 
@titanwww please Test PR.

**Comment by titanwww** [comment]
Not 

> closed as having Pull Request #22270
> @titanwww please Test PR.

Not work version 3.9
