### ISSUE TITLE
[3.9] userlog display "registered" message when using "Fogot your password/username"

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#22152]
### Steps to reproduce the issue

3.9 beta, enable actionlog
Use the "Forgot your password?" or ""Forgot your username?" in front-end
The "User Actions Log" reports 
**User ??xyz-user?? registered for an account** 

### Expected result
Not "registered" , ideally would should have a distinct string between "register" , "forgot your password" and "forgot your username"

### Actual result
PLG_ACTIONLOG_JOOMLA_USER_REGISTERED is shown regardless of the action taken.

### System information (as much as possible)
3.9 Beta
PHP 7.1.12

**Comment by ghost** [comment]
@jsubri Thanks for your Report. The Issue is now in Category "com_csp".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22152">issues.joomla.org/tracker/joomla-cms/22152</a>.</sub>

**Comment by alikon** [comment]
@franz-wohlkoenig  don't know if a category about actionlog exists already but this is not com_csp

**Comment by ghost** [comment]
@alikon thanks, will change Category.

**Comment by ghost** [comment]
closed as having Pull Request #22157
