### ISSUE TITLE
Alpha sort order in Menu Item Type is case sensitive.

### ISSUE THREAD

**Issue by ColinM2** [joomla/joomla-cms#22182]
### Steps to reproduce the issue
When creating a new or editing a Menu, the Menu Item Type field is a List in case sensitive alphabetical sequence.  It would be helpful if this was a Case Insensitive sort, often called a true alphabetical sort.
It would also be compatible with other sort lists such as the Component Pulldown, the 'type' field in Extensions - Plugins and so on.  
It is simple to see by installing a component such as jDownloads.  It appears in the natural place in component list but at bottom in Menu Item List.

**Comment by ghost** [comment]
@ColinM2 can you please Update to latest Version as you wrote you use Build 3.8.7?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22182">issues.joomla.org/tracker/joomla-cms/22182</a>.</sub>

**Comment by infograf768** [comment]
@ColinM2 
Can you provide a screenshot of the issue.

**Comment by infograf768** [comment]
I think I understood. The issue is in the modal when one selects a menu item type
I modified here the value of a string in fr-FR
`recherche avancée` is now at the bottom of the list.

![screen shot 2018-09-15 at 08 27 38](https://user-images.githubusercontent.com/869724/45583376-4162e800-b8c1-11e8-99bb-b17aa97a5c67.png)

**Comment by SharkyKZ** [comment]
Test PR #22189 please.

**Comment by brianteeman** [comment]
Closed as we have a Pr for testing
