### ISSUE TITLE
Smart search problem

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22220]
### Steps to reproduce the issue
Indexing 

### Additional comments
Latest version Joomla! 3.8.12
domain name is on https
domain name: https://nieuwsberichten.eu
Reseller hosting

Well the first error message.

**The table '#__finder_tokens' is full**

**The second error message during a website crawl**
303 ---- / component / search /? Searchpharese = alt & searschword-volcanic eruption and of course on several names

Components> Smart Search> Options> Indexing tab

There the Memory Table limit is reduced to 1000 and so on again, error remains.
Memory table limit and Indexing batch size downwards and again increasing, error remains

Perhaps according to RonDeb, it could also be the myisam_max_sort_file_size . This appears to be high from the hosting Vimexx.

Good, Smart Search totally disabled given that the error does not disappear.

**Comment by chrisdavenport** [comment]
What is your _max_heap_table_size_ set to?

The finder_tokens table is a MEMORY table and its size is limited by _max_heap_table_size_.  You need to set **Memory Table Limit** to a number that will ensure that this limit is not exceeded.  Note that _max_heap_table_size_ is in bytes (default is 16777216), but **Memory Table Limit** is a number of records, so the two are not directly comparable.

Try setting **Memory Table Limit** and **Indexer Batch Size** to something very small (like 1 or 5).  The indexer will be very slow, but it should at least run without error.  Once you have it working you can gradually increase these numbers from there.

Note that this is unlikely to be a core Joomla issue and hence this question should be asked and answered on the forum rather than here.

**Comment by ghost** [comment]
Thank you for giving a response.

I made the report in a Joomla forum joomlacommunity.nl, until no response has been received. However, there was 1 person from joomlacommunity, who himself has seen this problem and could not answer that it is a Bug.

**what forum do you have it for?**

Internet search for solution, the problem is that everyone has their own opinion which does not lead to a solution.

Given that the problem, continued to exist and test everything many times, I came to the action to place it here. There is of course an easier solution, just turn off smart search.

**Comment by dagalumin** [comment]
I would like to add some details to this issue I am experiencing too.
- The issue presents just in last release 3.8.12;
- Is caused by indexing bigger-than-normal articles, see issue [#22098](https://github.com/joomla/joomla-cms/issues/22098 "22098") for details on quantity of content text needed to raise the error;
- The issue causes a blank page after saving articles, and an error when launching the indexing function via the Search Engine component: the modal window after a while returns just "null", and the long articles are not indexed: see ![indexing modal windows with the "null" message](https://user-images.githubusercontent.com/35889756/45683057-9feac900-bb42-11e8-858e-67587cbc8cee.png)
- Same behaviour you have with the CLI indexing: _php -d memory_limit=256M finder_indexer.php_ after processing just 3 batches always returns errors like: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 1988399 bytes) in /var/www/vhosts/actingarchives.it/httpdocs/libraries/joomla/database/driver.php on line 2049  - I tried to increase the memory_limit parameter till 2Gb with no success;
- Tried to set both Memory Table Limit and Indexer Batch Size to 5 (minimum possible) with no success;
- On the database, i have increased "myisam max sort file size" till 4Gb and "max heap table size" to 2Gb with no success.

Since this issue is presenting just on the latest 3.8.12, I would assume is a freshly introduced bug that makes indexing impossible with larger article contents. With previous versions I just had to increase the "max heap table size" to 128Mb to not have any issue in indexing the same large article contents.

**Comment by ghost** [comment]
@chrisdavenport

I wrote to the hoster about this and received the following answer

> It is set to max_heap_table_size = 20M. Since it is a temporary table and as explained we want to keep the performance high, we do not have it too high. How much would be needed according to the community?
> 
> Concerns the reports you gave about text too small e.d, these are really website related issues, I can not change anything on the server because this is regulated in the code of the website!

After the change, I have executed your "alleged" solution. However here is a comment on "Indexer Batch Size to something very small (like 1 or 5)." the Indexer Batch Size, lowest setting is 5.

**End result of research and performances at my side as from the hoster side. Has not been removed, the error persists.**

**Comment by Quy** [comment]
Fixed in PR #22599. Please upgrade to the latest version. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22220">issues.joomla.org/tracker/joomla-cms/22220</a>.</sub>
