### ISSUE TITLE
Show all language overrides

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22259]
### Is your feature request related to a problem? Please describe.
I want to show all language overrides in a list, like you can show al menuitems from all languages same with overrides from all languages and Admin and Site

### Describe the solution you'd like
Same like all menu items for example, it is easier to find everything when all is in list with search tools.
And to assign one override to more language. Because it can be that you translate the same.

**Comment by infograf768** [comment]
This requires a full refactoring of the functionnality. Was already dicussed in a recent PR.

**Comment by B3nito** [comment]
can maybe be feature request for next Joomla?

**Comment by brianteeman** [comment]
Does it really need a full refactoring? 
From my "quick" look it just means that you move the "select language and site" for the new override to the  override view instead of the overrides view

**Comment by infograf768** [comment]
That was a "quick" look indeed. 
The whole code is based on the userstate defined in the overrides view which is both used to filter the overrides manager and define the lang and client for a new override. 
It would require preventing the language and client fields from being modified when the override already exist and is edited.
Also, It requires some Ajax magic to take into account a change of lang and client when editing an override as the search for a constant (or value) and client is done depending on the client.

It is possible indeed, but I call this a full refactoring because both models have to be heavily modified, their views, as well as filtering, the cache code, the js file, etc..

**Comment by brianteeman** [comment]
Everything you describe is how all components work so if this doesn't work that way it needs efactoring anyway.

The only thing unique about this component is the searching of keys/constants.

I will work on this at the weekend

**Comment by infograf768** [comment]
...

**Comment by B3nito** [comment]
Thank you @brianteeman

**Comment by alikon** [comment]
closing in favour of discussion going on at #24952  wich is 4.x based<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22259">issues.joomla.org/tracker/joomla-cms/22259</a>.</sub>
