### ISSUE TITLE
Too much languages in language overrides

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22260]
### Steps to reproduce the issue
- Install language on site and setup content language
- Delete everything
### Expected result
- language override show only installed languages

### Actual result
- language override show also not installed languages

### System information (as much as possible)
- Joomla 3.8.12

**Comment by infograf768** [comment]
can you test on staging please

**Comment by B3nito** [comment]
In current nightly build no filter is visible
![grafik](https://user-images.githubusercontent.com/43232309/45776006-d4997600-bc51-11e8-838a-0fc5fc5a9832.png)

**Comment by mbabker** [comment]
That one is a duplicate of https://github.com/joomla/joomla-cms/issues/22261

There are files in `script.php` that are being deleted because they were dropped in older versions but are now back in the package and need to be taken out of that script.

**Comment by B3nito** [comment]
BUt this is issue about too much languages, no duplicate of 22261

**Comment by infograf768** [comment]
> In current nightly build no filter is visible

Last nightly build shows the filter OK if you do not use database fix.
See https://github.com/joomla/joomla-cms/pull/22264

Overrider does not care about Content Languages, just about installed languages when it creates overrides.
If you create a specific xx-XX.override.ini for a language, if then you uninstall the language and reload the Overrides Manager, it may still display the overrides created for the deleted language, even if the filter is not showing the deleted language, because the session still contains the former UserState and the xx-XX.override.ini is NOT deleted when uninstalling a language.
As soon as you filter by another language/client, it will not show anymore the strings concerned by this language as you can't filter anymore by the deleted language.

**Comment by B3nito** [comment]
I have delete the override ini file but the language still are in the list.

**Comment by infograf768** [comment]
Are you using the nightly build?
Have you changed the overrides filter to another language than the deleted language.
Have you deleted the correct override.ini? Does it concern the uninstalled language?
They may have been created in /administrator/language/ or root/language/

Please describe exactly all your actions on a default nightly build with screenshot for each, one after the other.

**Comment by B3nito** [comment]
> Are you using the nightly build?
Yes I did

> Have you changed the overrides filter to another language than the deleted language.
Yes

> Have you deleted the correct override.ini? Does it concern the uninstalled language?
Yes

> They may have been created in /administrator/language/ or root/language/
I deleted all files and folders for this langugae

> Please describe exactly all your actions on a default nightly build with screenshot for each, one after the other.

Ok, I will send

**Comment by infograf768** [comment]
no reply after more than 3 weeks. Closing. May be reopened if desired.
