### ISSUE TITLE
[4.0] Captcha error

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#22266]
### Steps to reproduce the issue
Install on Joomla 4 [fakecaptcha.zip](https://github.com/joomla/joomla-cms/files/2399309/fakecaptcha.zip) plugin. It always fails the captcha test. Enable the plugin and set as default in global configuration. Open frontend registration, fill the data and submit the form.

### Expected result
User is redirect back to form with error message, that captcha test failed.

### Actual result
Error page is displayed - Call to undefined method Joomla\CMS\Captcha\Captcha::getError()

### System information (as much as possible)
Joomla 4 alpha 4

### Additional comments
There seems to be unported code in Joomla\CMS\Captcha\Captcha - its trying to check getError() which does not exists in Joomla 4 anymore. 

Following code in recaptcha plugin (it throws exception on validation failed) will not raise this error, however will show error page to user instead of showing him just error message and giving chance to try the captcha again.

Joomla 3 uses $this->_subject to set those error messages, this is missing in Joomla 4, but can easily be bypassed by directly using Application::enqueueMessage.

**Comment by richard67** [comment]
Could that be related to issue #22041 for staging?

**Comment by n3t** [comment]
No, that is onDisplay event issue, this is onCheckAnswer event issue.
More over this is related just to Joomla 4, not Joomla 3.

**Comment by richard67** [comment]
I know that this here is related to Joomla 4 and the other one to 3. But despite of this it could have been that it was the same issue, that's why I asked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22266">issues.joomla.org/tracker/joomla-cms/22266</a>.</sub>

**Comment by richard67** [comment]
@n3t Is this still an issue with latest 4.0-dev branch or latest 4.0 Alpha 9? I ask because there have been made many changes since you opened this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22266">issues.joomla.org/tracker/joomla-cms/22266</a>.</sub>

**Comment by Quy** [comment]
Closing to due no response and unable to replicate per test instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22266">issues.joomla.org/tracker/joomla-cms/22266</a>.</sub>
