### ISSUE TITLE
Search of archived articles creates weird links

### ISSUE THREAD

**Issue by HerKle** [joomla/joomla-cms#22395]
### Steps to reproduce the issue
1. Create some articles in categories and set their status on "archived"
2. Open search options for archived articles
3. Start search
4. click on a title of the results' list

### Expected result
The archived article, uniquely identified by its article id, should show. ike in this example of published article in search result:
[http://heikkijokinen.info/ay-uutiset-maailmalta/1357-puuseppien-alkupalkkaan-saksassa-korotusta-15-5-prosenttia]

### Actual result
A list appears with all the articles of the same month, but over all years, created by this broken (the year appears without its label before the question mark) link:
[http://heikkijokinen.info/ay-uutiset-maailmalta/arkisto/2015?view=archive&month=6]

### System information (as much as possible)
Joomla 3.8.12
PHP 7.1

### Additional comments
This bug has been reported several times during the last years and been closed as "solved". That seems not to be the case.

**Comment by brianteeman** [comment]
It will be really helpful if you can link to those closed issues where it is marked as solved

**Comment by HerKle** [comment]
[#7084](https://github.com/joomla/joomla-cms/issues/7084)
[#10613](https://github.com/joomla/joomla-cms/pull/10613)

**Comment by brianteeman** [comment]
Thank you

**Comment by beejay41** [comment]
I believe there are two issues here:

1. com_search for archived articles, deliberately creates a link for archived articles in the same year and month as the selected article. In my opinion, it should create the same link as normal articles, ie. the article you just found. Who expects the link to give another list, which you then have to browse to find the article identified in the first place. Using the code for state=1 for both would remove 70+ duplicate lines of code in this plugin.

2. com_content router still produces incorrect URLs and fails to resolve them. This is best demonstrated by the output of the Archived articles  module. That creates links as /menu-entry/2018.html?view=archive&month=4 rather than /menu-entry/2018/4.html. The router then interprets the year as an Id, which might hit a valid article, in which case that is displayed, otherwise it is ignored and the results ignore the year, giving the selected month for all years, as reported.

Both issues have existed since 1.5 and remain in 3.9.1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22395">issues.joomla.org/tracker/joomla-cms/22395</a>.</sub>

**Comment by SharkyKZ** [comment]
Test PR https://github.com/joomla/joomla-cms/pull/24990 please.

**Comment by ghost** [comment]
Closed as having Pull Request #24990
