### ISSUE TITLE
[3.9] Modal hidden by overlay

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22465]
### Steps to reproduce the issue
Go to `Components > Smart Search`
Click the `Index` button

### Actual result
![hidden-modal](https://user-images.githubusercontent.com/368084/46374186-f2e57580-c644-11e8-8c90-4ee2693c62d1.jpg)

### System information (as much as possible)
staging f6c6bf5b232f841e18f46de438f969e4fc434832

**Comment by ciar4n** [comment]
Looks like a duplicate of https://github.com/joomla/joomla-cms/issues/20255

**Comment by ciar4n** [comment]
@Quy Can you re-open this issue. #20255 is only an issue after a user scrolls and the subhead sticks. This issue is always present (confirmed).

As you mentioned in the other issue, this issue is due to #22367. Because we are loading the modal markup inside the button (should be in the root), applying anything other than `position:static` to any outside div of a modal will cause the backdrop to appear above the modal.

I dont think there is any way around this. Same issue with J4.

**Comment by infograf768** [comment]
Issue reopened.

**Comment by infograf768** [comment]
The revert does not solve entirely the issue as we still have the pb after a scroll.

**Comment by ciar4n** [comment]
I guess we can close this issue and leave #20255 open
