### ISSUE TITLE
privacy text COM_PRIVACY_EMAIL_ADMIN_REQUEST_BODY_EXPORT_REQUEST

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#22482]
### Steps to reproduce the issue
COM_PRIVACY_EMAIL_ADMIN_REQUEST_BODY_EXPORT_REQUEST contains this text:
An administrator for [URL] has created a request to export personal information related to this email address. As a security measure, you must confirm that this is a valid request for your personal information from this website.\n\nIn order to confirm this request, **you can complete one of the following tasks**:\n\n1. Visit the following URL: [TOKENURL]\n\n2. Copy your token from this email, visit the referenced URL, and paste your token into the form.\nURL: [FORMURL]\nToken: [TOKEN]\n\nPlease note that this token is only valid for 24 hours from the time this email was sent.

### Expected result
I do think this must be **you must complete the following tasks**
(I markt it bold in the text)

**Comment by MartijnMaandag** [comment]
Nad the same for: COM_PRIVACY_EMAIL_ADMIN_REQUEST_BODY_REMOVE_REQUEST<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22482">issues.joomla.org/tracker/joomla-cms/22482</a>.</sub>

**Comment by mbabker** [comment]
It's right as is.

Item 1 is a shortcut link with the token set as a query string to prefill the form on the page.  But, not all email parsers will correctly link this bit, which is why item 2 exists, which is just a link to that same page without the token query string variable and an explicit note that you must copy/paste the token from the email to the form on the page.

Long and short, both lead to the same place, the difference is one can potentially result in less clicks because it gives a shortcut.

Below is an example of how it looks in the email.

![screen shot 2018-10-03 at 10 27 23 am](https://user-images.githubusercontent.com/368545/46421059-fc2f1a80-c6f6-11e8-8a45-3863afd82f53.png)

**Comment by MartijnMaandag** [comment]
Yes, when it is in the link it is OK.
I am translating and found this ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22482">issues.joomla.org/tracker/joomla-cms/22482</a>.</sub>
