### ISSUE TITLE
throw new \InvalidArgumentException('The image file does not exist.');

### ISSUE THREAD

**Issue by basd82** [joomla/joomla-cms#22550]
When the InvalidArgumentException is throw at you, it would be nice if it includes the path so you can debug ?

**Comment by HLeithner** [comment]
This could lead to an information disclosure you may not want.

**Comment by basd82** [comment]
You could only show if debug mode is on

**Comment by mbabker** [comment]
Exception messages shouldn't change based on whether debug mode is enabled.

You can try/catch this particular exception and log the path if need be as you'll have the path data where you're catching the exception, it doesn't really need to be part of the message.

If the image path really needs to be part of the Exception object, a custom subclass should be added with a `$path` property that can be accessed when catching and processing exceptions, similar to how we have custom exceptions for database level errors where the query is a property on the class and not stuffed into the message.  Personally, I don't think we need this.

So long and short, the data you need is already there, you just need to add some additional error handling to your code to catch and handle this error instead of letting it bubble up past a point where the path info would be accessible.

**Comment by basd82** [comment]
Why is not finding an image an exception at all anway ?

**Comment by mbabker** [comment]
The two uses of that specific message are in the `Image` class.  In both cases, it requires the image file to do what is being instructed.  Failing to load that file is correctly an exception.

**Comment by tonypartridge** [comment]
@mbabker the problem is this now add's a BC break. Components trying to load the image previous now are breaking sites. IF the image doesn't exists yet someone try's to load it the sites an exception with a 'The image file does not exist.' Whilst I agree if it's not their it is an exception, this change shouldn't happen in an incremental release?

**Comment by ghost** [comment]
@basd82 can this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22550">issues.joomla.org/tracker/joomla-cms/22550</a>.</sub>

**Comment by basd82** [comment]
yes

 

Met vriendelijke groet,

 

 

Bas van den Dikkenberg

 

Van: Franz Wohlkönig <notifications@github.com> 
Verzonden: maandag 4 maart 2019 19:05
Aan: joomla/joomla-cms <joomla-cms@noreply.github.com>
CC: Bas van den DIkkenberg <bas@dikkenberg.net>; Mention <mention@noreply.github.com>
Onderwerp: Re: [joomla/joomla-cms] throw new \InvalidArgumentException('The image file does not exist.'); (#22550)

 

@basd82 <https://github.com/basd82>  can this Issue be closed?

  _____  

This comment was created with the J!Tracker Application <https://github.com/joomla/jissues>  at issues.joomla.org/tracker/joomla-cms/22550 <https://issues.joomla.org/tracker/joomla-cms/22550> .

**Comment by ghost** [comment]
closed as stated above, thanks @basd82 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22550">issues.joomla.org/tracker/joomla-cms/22550</a>.</sub>
