### ISSUE TITLE
Shared session doesn't work anymore since 3.8.13

### ISSUE THREAD

**Issue by PascalNetenvie** [joomla/joomla-cms#22591]
### Steps to reproduce the issue
Configuration : Close front office access.
Configuration : Enable shared session.
Connect to backoffice.
Try to go to frontoffice.

### Expected result
Should be auto-connected.

### Actual result
Display login screen.

### System information (as much as possible)
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64
mysql 5.5.5-10.0.36-MariaDB-0+deb8u1 utf8_general_ci utf8mb4_general_ci
PHP 	7.1.22 fpm-fcgi
Apache - 
Joomla! 3.8.13 Stable [ Amani ] 9-October-2018 14:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0 

### Additional comments
It's a regression :/

**Comment by joeforjoomla** [comment]
Can't confirm. Working just fine for me.

**Comment by mbabker** [comment]
Can't confirm against staging (3.9 RC) either.

**Comment by PascalNetenvie** [comment]
Ok. So perhaps it come from an extension i have updated at same time.
I use Rsfirewall and PWT ACL so perhaps one these 2.
I will check, thx for tests.

**Comment by mbabker** [comment]
In theory an extension can't mess this up because sessions are started long before any extension is loaded in and able to interact with core, plus the feature basically relies on a couple of values being set in your `configuration.php` file to work, but crazier things happen.  Hope you do resolve this issue though, and if you do find there is some core bug related to it feel free to come back here with an update.
