### ISSUE TITLE
[RFC] ACL check to admin activate accounts in the frontend

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#22603]
### Steps to reproduce the issue

With 3.8.13 the JSST implemented an ACL check to make sure only logged-in people can activate the accounts. In that process we found out that in order to get the admin account mail you just have to have the permission core.create and enabled "System Mails" in the user profile.

https://github.com/joomla/joomla-cms/blob/staging/components/com_users/models/registration.php#L139-L177

While in theorie this sounds good we have a loop hole here:
![46311386-52e70800-c5c2-11e8-8da7-2d8373ff6a0d](https://user-images.githubusercontent.com/2596554/46915590-e8fd3400-cfad-11e8-8e93-a72378c54f54.png)

As authors (or possible any other group that get core.create as global permission) have the global core.create permission he can get that the activation mail and also activate accounts. In oder to create accounts from the backend you are required to have core.manage for com_users too, which the users does not have.

### Proposal

The proposal would be an core.activate permission which would result into may places where similar things happen we need to create similar new permissions. I'm not sure what is the correct place or if we should accept the current behavior

**Comment by PhilETaylor** [comment]
@joomla/security

**Comment by mbabker** [comment]
To be clear, it's not a loophole.  Rather, to effectively complete this particular task you either need a compound permission set (core.manage + core.create, something that can't be reflected in the UI) or this particular task needs its own permission.  If we had a fixed set of user groups, I would be more inclined to call it a security issue, but because we have customizable groups you do have to focus specifically on the permission(s) required to complete a task.

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/joomla-cms/pull/24738
