### ISSUE TITLE
Admin express, standard and expert mode

### ISSUE THREAD

**Issue by johanpeters** [joomla/joomla-cms#22606]
### Describe the solution you'd like
i love Joomla and for people who know Joomla there is not a issue.. but new users are often switching over to WordPress because of the complexity of the backend (complex in the mean of a lot of options).
Wordpress offers a less option administrator screen... Wordpress is not the same.. and i dont whant a discussion whats the better platform.. 

But i think the install based can easely expand and new users are more willing to choice Joomla if the administrator has les options by default.. 

Joomla express mode: only the necessaire options and settings (other based on best practice)
Joomla Standard mode: only main options and settings
Joomla expert mode: Everything is shown.. (current)

if Joomla offers this option and extention builders work with this princaple also.. 
expert and standard mode more based on installation and configuration wizzards.. stap by stap .

**Comment by mbabker** [comment]
The odds of this ever being pulled off are slim to none because it means essentially maintaining three sets of configurations globally, AND getting all extensions to follow the convention to switch through these "modes" (how is the mode rendered, you're looking at three sets of layouts for everything or three full templates).  As nice as it might be, this honestly is one of those ideas that would create a level of complexity in the code that would make working with the platform too complicated I would suggest.

**Comment by brianteeman** [comment]
Closed for the reason stated above
