### ISSUE TITLE
[4.0] Not Able to open the CMS

### ISSUE THREAD

**Issue by geetanshu-m** [joomla/joomla-cms#22618]
### Steps to reproduce the issue
1. Clone joomla-cms/4.0-dev branch. 
2. ```npm install``` in the CMS directory.
3. ```composer install``` in the CMS directory.

### Expected result

CMS should be accessible through web browser.

### Actual result

CMS is not accessible rather this issue is being showed.
![screen](https://user-images.githubusercontent.com/18314265/46929741-d1ca4f00-d05e-11e8-96fd-a8653153cc11.png)

### System information (as much as possible)

OS : Ubuntu 18.04.1 LTS

### Additional Comments
I have tried this command too but the result remains the same
```alias jinstall="rm -rf administrator/templates/atum/css; rm -rf templates/cassiopeia/css; rm -rf media/; rm -rf node_modules/; rm -rf libraries/vendor/; composer install; npm install; git checkout -- libraries/vendor/.htaccess"```

**Comment by TobsBobs** [comment]
I already had this problem. I just ran npm again and then it worked.

**Comment by brianteeman** [comment]
As per the instructions it is git, composer and then npm. If you still have problems then look in your error log and post back

**Comment by geetanshu-m** [comment]
@TobsBobs I tried ```npm install``` again this log is being popped up in the console, but the status remains the same.
![npm install](https://user-images.githubusercontent.com/18314265/46958657-f6064a00-d0b7-11e8-8c29-980e2bbd6742.png)

**Comment by mbabker** [comment]
You need to check and fix your system permissions.  Generally, you should not be using `sudo` with `npm`.

Just a blind guess, but what is probably happening is the various tasks that are executed with an `npm install` on the repo are failing because those are NOT being executed with `sudo` and it is failing since those are trying to be run as your own user yet the `node_modules` directory is owned by root.

**Comment by geetanshu-m** [comment]
Thank you @mbabker, Problem resolved :-)
