### ISSUE TITLE
Admin Template admin menu links are wrong

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22681]
### What needs to be fixed
If you select in admin menu the item "Templates" you end in "Styles"
If you select in admin menu the item "Extensions » Manage" you end in "Install"

![grafik](https://user-images.githubusercontent.com/43232309/47080594-bac76080-d208-11e8-8fd5-84ce8a44ce06.png)

### Why this should be fixed
Because the link leads you somewhere else then expected

### How would you fix it
Link with the right page

### Side Effects expected
Happy and less confused customers

**Comment by brianteeman** [comment]
Where do you expect them to go?

**Comment by ReLater** [comment]
> Happy and less confused customers

I would be unhappy and more confused if the menu would be changed ;-)
We have the possibility to build our custom administrator menus if we want to.

**Comment by B3nito** [comment]
No the problem is that Templates does not go to Templates but to Stiles, and Manage not going to Manage but to Install.
So solution is: 
Rename **Templates** to **Styles** _or_ Link **Templates** to **Templates**
And Rename **Manage** to **Install** _or_ Link **Manage** to **Manage**.

**Comment by mbabker** [comment]
Except that would create even more confusion.

`Extensions > Templates` takes you to the default view of `com_templates` (presently the "Styles" view), which just so happens to have a secondary view also named "Templates".

`Extensions > Manage` takes you to the default view of `com_installer` (presently the "Install" view), which just so happens to have a secondary view also named "Manage".

By your logic, `Extensions > Language(s)` should also be renamed because that link takes you to the "Installed" view even though there is also a "Languages" view.

Changing the base links has "bad idea" written all over it.  And I dare say changing the text of those items is equally as bad.

**Comment by brianteeman** [comment]
I would not be in favour of this change at this point in the life of joomla 3 and it is not relevant for joomla 4

If you really want you can create your own admin menu with whatever links you want.

**Comment by B3nito** [comment]
This does not make sense....... Joomla is very unlogical and inconsistent ux. Is Joomla 3 not supported at least 2 years + from now?

**Comment by mbabker** [comment]
The base link `Extensions > Manage` points to the Extension Manager as an overall component.  That default view right now is the Install view.  To me, if you're going to replace this with `Extensions > Install`, then you might as well completely eliminate the second level dropdown menu with the links to the other views (because how does `Extensions > Install > Install` or `Extensions > Install > Update Sites` make sense (I'm installing an update site?)).  If you change this link to go to the "Extensions: Manage" view instead of the default "Extensions: Install" view, it is a fundamental change in behavior that is going to introduce a lot of user confusion and complaints because a common link has been changed somewhat inexplicably after being the same for at least 6 years (off hand I don't remember how it was in 2.5 and frankly I don't care enough to look).

The same bit applies to the templates link.

Again, if you really feel like this is excessively problematic, you are free to customize your admin menu structure as you see fit.  But from a core perspective, changing this menu after it has been set up the way it is for as long as it has would be change for the sake of change and not be a UX improvement.

**Comment by B3nito** [comment]
So the error was done in the beginning and no one saw it and because no one saw you say it will not be fix?

**Comment by brianteeman** [comment]
Clearly it is an error in your eye but not in others or we would have had millions of requests for it to be changed.

> Again, if you really feel like this is excessively problematic, you are free to customize your admin menu structure as you see fit. But from a core perspective, changing this menu after it has been set up the way it is for as long as it has would be change for the sake of change and not be a UX improvement.

Therefore I am closing this
