### ISSUE TITLE
[com_privacy] Email export looks very much like spam

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22712]
ok this might be subjective - Im no spam expert

This is what an emailed export looks like:

![screenshot 2018-10-19 at 01 09 57](https://user-images.githubusercontent.com/400092/47190944-3b3aae00-d33c-11e8-85c6-4f7490695512.png)

Mac Mail thinks its spam

If I had not had a coffee in the morning I would think it was spam and delete it to.

It literally calls out "Hey I look like spam, open the attachment and infect your PC"

Its sent in plain text, whereas the com_actionlogs email are sent in HTML mode.

it has a single URL in the email - just like spam does

It makes no reference to me personally... My Name, username or the name of the Joomla site im registered on

There are no pleasantries at the start or the end. 

This email, in my mailbox, would be deleted before I finished reading it... 

Am I alone here?

**Comment by mbabker** [comment]
> Its sent in plain text, whereas the com_actionlogs email are sent in HTML mode.

The particular email you're referencing is the only one with HTML formatting because it actually needs it (try doing a table layout with plain text and not rip what's left of your hair out).  Nothing else in core has a real structure for HTML emails.

> It makes no reference to me personally... My Name, username or the name of the Joomla site im registered on

As requests aren't hard coupled to user accounts, the most identifying thing we can do is say "Hello phil@...".  The site you're registered on is part of the subject (the "joomla-cms" bit).

Anything else, as I always say, feel free to iterate and improve.  Everything I did I screamed out needs some UX attention and that didn't really come in all places.
