### ISSUE TITLE
Username (not) optional on edit profile page frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22716]
### Steps to reproduce the issue

Login to Joomla 3.9 frontend (and maybe earlier, not tested) as a registered user
Go to edit your profile

### Expected result

My username shown, ok so its disabled field, but the expectation is that it should NOT be optional as stated, how can it be optional, I cannot remove my username, a Joomla user requires a username! 

### Actual result

Username (Optional) field label

![screenshot 2018-10-19 at 01 45 28](https://user-images.githubusercontent.com/400092/47191685-ac7c6000-d340-11e8-84e4-d9c1496014a1.png)

**Comment by ggppdk** [comment]
Ok,
the field is not disabled ... it is readonly
so if you allow it to be required ... then Joomla default profile form

-- will succeed to save properly

but
then **any custom template overrides that are now skipping the username field**
(skipping when !JComponentHelper::getParams('com_users')->get('change_login_name'))

-- will fail to save
(i do not know how common this is or even if they hide it instead of skipping it, in which case saving will succeed)

**I do not remember** if there was a bug report for the above in the past
but i think there was

Also making the field both **disabled and required**
will again make the form to fail to save always

so i am afraid the
`$form->setFieldAttribute('username', 'required', 'false');`
inside model's code is deliberate ?

Maybe we need to make a fix / improvement inside JForm validation
to avoid failure when a field is both disabled and required

Also if there is custom code that is using a model instance to save the profile, and is not providing username when `JComponentHelper::getParams('com_users')->get('change_login_name')` is OFF will fail

**Comment by ggppdk** [comment]
a simple fix is to patch the form template file ...

```php
<?php if (!$field->required && $field->type !== 'Spacer') : ?>
	<span class="optional">
		<?php echo JText::_('COM_USERS_OPTIONAL'); ?>
	</span>
<?php endif; ?>
```

i mean maybe it makes sense not add optional / required markings when a field 
- disabled or readonly
