### ISSUE TITLE
Admin user menu incorrect

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#22867]
### Steps to reproduce the issue
Login to admin
Select Users >>> Manage
Select Users >>> Privacy

### Expected result
All of the top menu User item children should display on the lefthand side

### Actual result
The privacy child item does not show on the left hand side when manage is selected
Only the privacy sub menu displays on the left hand menu when privacy is selected.

### Additional comments
This is inconstant behaviour.  either All the items that are in the drop down menu should show on the lefthand side or the Privacy menu item should be Parent item on the top menu.

**Comment by mbabker** [comment]
This is purposeful, otherwise you're going to have one massively long sidebar menu since the expectation seems to be that all of com_users, com_privacy, and com_actionlogs show the sidebar items for each of those separate components since they're grouped under the same header menu (which would result in a 13-item sidebar; the existing 7 for com_users, 4 for com_privacy, the 1 item that com_actionlogs would have to add, and an item for the mass mail view of com_users; plus adding the sidebar to the mail view of com_users and com_actionlogs since those two links don't show one right now).

**Comment by Webdongle** [comment]
The Privacy menu item could display collapsed in the lefthand menu.  Or the Privacy menu item (in the top menu) could be a Parent not a child item.

Don't get me wrong ... I am not knocking the Privacy suite.  After all it is everything that I requested and you and brian (at first) rejected.  But I just think the menu could be more user friendly/intuitive.

**Comment by brianteeman** [comment]
Such a shame that you waited until today to comment. There was a reason for the multiple beta and release candidates

**Comment by mbabker** [comment]
It's a weird thing.  If the expectation is "every top level item from the top bar must be in the sidebar", then a lot of things are wrong because...

- com_content has no link to com_media
- Nothing in the components menu has that type of cross-component linking
- Under the Extensions area each component only has a sidebar for that component's links

As action logs and privacy are separate components, IMO it is right and follows suit with the existing core UI and I'd personally lean toward having links between components in the 3 listed under the Users section would be wrong based on existing practice.

**Comment by Webdongle** [comment]
@brianteeman 

> Such a shame that you waited until today to comment. There was a reason for the multiple beta and release candidates

As you well know ... I resigned from bugsquad because you and mbabker ridiculed my suggestions.  That's why I did not join in the testing because the two of you changed your tune after I resigned.  But like I have said I am not knocking the efforts.  Just suggesting how the admin menu could be more intuitive.

@mbabker 
> As action logs and privacy are separate components, IMO it is right and follows suit with the existing core UI and I'd personally lean toward having links between components in the 3 listed under the Users section would be wrong based on existing practice.

In that case (by the same reasoning) it is wrong to have Privacy menu item as a Child of Users.

**Comment by mbabker** [comment]
It was either there or leave them under the Components menu, more people felt compelled to put them under the Users section than under the catch-all Components menu.  I don't have a strong opinion either way where in the menu they go, I just don't agree that the sidebar for all three components (com_users, com_privacy, and com_actionlogs) needs to contain links (or the whole thing) for the other components with only "it's under Users so the sidebar should match the top menu" as the justification.

**Comment by Webdongle** [comment]
Just seems illogical to have Users sub items and Privacy sub items separate in the side menu but have Privacy as a child in the User menu.  

I understand the reasoning for not having the User items and Privacy items together in the left menu.  But that means that when any of the users sub items are chosen that the Privacy item and it's child items are in (affect) hidden.  So that is why I suggested Privacy should be a Parent item in the top menu raher than a child.

Privacy item (and it's child items) are not sub items in the Users item in the left menu ... therefore they should not be sub items of users in the top.  It is inconsistent.

But why should my opinion mater?  It never has before.

**Comment by mbabker** [comment]
> Just seems illogical to have Users sub items and Privacy sub items separate in the side menu but have Privacy as a child in the User menu.

So by this argument you're saying that it is also wrong that there is no "Media" link in the com_content sidebar or that a sidebar for the Module Manager doesn't have a link to the Plugin or Template Manager (since those components are grouped under the same top level menu).

Privacy isn't a special case here and shouldn't be made out to be one.  What we have now is consistent with how things are done in the rest of the admin app and if we're going to make a change for this one component to show sidebar items because of where in the menu structure it's placed (and that only works if you haven't customized your menus) then IMO it needs to be done across the board.  And no, I don't believe the two new components justify a new top level menu; both of them deal with actions related to your site's users and visitors so grouping them under the Users menu (which should not be looked at as only items for the com_users component) makes sense.

**Comment by brianteeman** [comment]
I am closing this for the reasons stated by @mbabker above
