### ISSUE TITLE
[4.0][RFC] Use consistent capitalisation of folder names

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22990]
Please please please can we decide which we are going to use! I don't care which, but can we make a decision and then switch/stick to it? Unless someone can educate me whay we have chosen this?

This is a mess:

![screenshot 2018-11-09 at 20 31 42](https://user-images.githubusercontent.com/400092/48286776-999c0d80-e45e-11e8-9d89-687408350804.png)

![screenshot 2018-11-12 at 00 56 23](https://user-images.githubusercontent.com/400092/48320848-cfcfbd80-e615-11e8-875c-964eaa72cb97.png)

**Comment by laoneo** [comment]
The folders with upper case do contain namespaced PHP classes. The ones with lower case XML files, templates files, etc. There are a few ones with lower case because of BC like the helpers.

I made last year a proposal to move all the PHP classes into a src folder and some more changes in #15221 to not mix classpaths and have a consistent lookup which reflects nowadays PHP projects. But as you can guess it got shut down. In Media manager, we did it, as we have some more resources, so it is much clearer there
![image](https://user-images.githubusercontent.com/251072/48342903-3b934400-e671-11e8-87e7-a7797873f942.png)
