### ISSUE TITLE
[3.9] Subforms not working properly

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#23022]
### Steps to reproduce the issue
Create a subform in backend of your website, see screenshot below.
Click on + button > not working, no message, nothing.

### Expected result
Clicking on the + button should add entry to form.

### Actual result
Nothing happens when clicking on + button, should add row to form.

### System information (as much as possible)
Joomla 3.9.0, updated from 3.8.13 (where this was still working).

### Additional comments
See screenshot:
+ button does nothing
- button still works properly

![screen shot 2018-11-10 at 02 17 14](https://issues.joomla.org/uploads/1/7b8cb4bd37ee28f352453b2965fccd75.jpg)

**Comment by roland-d** [comment]
@BurtNL This issue is caused by this commit https://github.com/joomla/joomla-cms/pull/17552/files#diff-43fc98bd347d2aeaa1b1628c8fb0829b

I am going to assume you have an override of the `repeatable-table.php` file. The mentioned commit created a B/C break.

The only solution there is, you have to update your override. Here is the code change from my extension:
<img width="989" alt="image" src="https://user-images.githubusercontent.com/359377/48298312-b3b80900-e4bb-11e8-9f66-0d4948dbe3c3.png">

Notice, we add the `-1` everywhere because the new subforms require a unique number per instance of the form.

Here is the second change we had to do:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/359377/48298332-e5c96b00-e4bb-11e8-861f-ff576db0c768.png">

The `tbody` must be changed as well:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/359377/48298338-00034900-e4bc-11e8-9866-6fa522a5799c.png">

You must pass the unique ID as well to the `$this->sublayout()` function:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/359377/48298347-24f7bc00-e4bc-11e8-9b7a-b21445313ba0.png">

Finally you need to replace the script code with a template:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/359377/48298351-3771f580-e4bc-11e8-80dd-83e14b6988a2.png">

Finally you also need to update the `section-by-fieldsets.php` file with the following changes:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/359377/48298372-b109e380-e4bc-11e8-8101-93289b2c8196.png">

Notice we are also adding the `-1` here.

Apologies for the screenprints but I think they are clearer than writing the text. You can contact me if you want the actual code.

**Comment by BurtNL** [comment]
@roland-d I was indeed using an overwrite of the repeatable-table.php and 2 other files: section.php and section-byfieldsets.php. 
Those files had become outdated and were slightly different from the current files in /layouts/joomla/form/field/subform-files.
So I replaced the 3 outdated files with the new files as mentioned before. And the subforms are working properly again.

Thanks for your screenshots, which pointed me in the right direction, much appreciated!

Also, the subforms seems to work just fine, my issue was caused by some outdated overwrites.



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23022">issues.joomla.org/tracker/joomla-cms/23022</a>.</sub>
