### ISSUE TITLE
System - Privacy Consent plugin wysiwyg/bb code

### ISSUE THREAD

**Issue by mandville** [joomla/joomla-cms#23111]
currently entering short policy renders non formatted text.
suggest its formatable either wysiwyg or via bb code to break sentences etc for readability

**Comment by ReLater** [comment]
You can create a language string override for "PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT" under Extensions > Language(s) > Overrides

**Comment by hardik-codes** [comment]
@ReLater and @mandville  what is to be done in this issue precisely?

**Comment by ReLater** [comment]
From my point of view there's nothing to do here because one can create a lnguage string override using HTML code

`
PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT="<h3>Hello aliens!</h3><p>By <strong style=\"color:red\">signing</strong> up to this web site and agreeing to the Privacy Policy you agree to this web site storing your information.</p><p>By <strong style=\"color:red\">signing</strong><br> up to this web site and agreeing to the Privacy Policy <code>you agree to this web</code> site storing your information. <a target=_blank href='https://'>If you love me click here</a></p>"
`

![29-01-_2019_20-59-21](https://user-images.githubusercontent.com/20780646/51937021-ccc0be00-2409-11e9-9f39-8de2fb9802e3.jpg)

**Comment by brianteeman** [comment]
It is working as intended

**Comment by hardik-codes** [comment]
ok
