### ISSUE TITLE
[4.0] Joomla 4.0 multicategories

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#23126]
### Is your feature request related to a problem? Please describe.
On my site there are a lot of articles that need to be displayed in several categories of different sections of the site. This is a big problem as I have to create copies of articles for each individual category. I tried to use additional extensions to solve this problem, but they do not work correctly. I expect that this function will appear in the content management system from version 2.5, but now version 4.0 is on the way, but this necessary function is still not there. 

### Describe the solution you'd like
Add the ability to select for the same article several categories where it will be displayed.

### Additional context
Please realize the possibility of choosing several categories for one article.

**Comment by simbus82** [comment]
Hi @1inkin , i think showing two articles in diffent categories is simply wrong, for SEO for example. Maybe you can use Tag to "group" some type of contents.

**Comment by joeforjoomla** [comment]
Exactly this is highly wrong. It would create a lot of duplicated links, very dangerous feature to have in the core.

**Comment by 1inkin** [comment]
@simbus82, @joeforjoomla, on my site such specific information that sometimes you need to place the same document in different sections of the site. This cannot be done with the help of tags because of the complex structure of the site, which contains information on various areas of the company's activities. I know many Joomla users who also need to post articles in several categories. New functions of content management system appear, but there is still no such necessary one. It is sad.

**Comment by rdeutz** [comment]
This is not going to happen for the reason stated above, use tags or rethink your site structure.

**Comment by adankupapa** [comment]
Yet WP has it and it is not bad for it's SEO? I plead for forgiveness for
saying this because I know WP is different from Joomla, and most people
Joomla lovers don't like hearing WP compared to Joomla. I only bring this
up because SEO was mentioned. How is it that WP permits publishing to
multiple categories and both content open with just one URL instead of two.
Let me guess, the Joomla router wasn't built like that which I believe will
be a better explanation / reason for throwing this idea away than the SEO
angle. @JoeforJoomla Boy.

For starters, Joomla is not only used for building public websites which
rely on SEO. Many people also use Joomla for intranets and may need the
functionality of assigning one item to multiple categories. Lets think
about all the other types of things Joomla is being used for anytime a
feature is suggested. Can this be an optional feature that admins can turn
on in Article Options or Global Configurations?

**Comment by mbabker** [comment]
I've looked at a multi-category system in the past, it is not compatible with Joomla's existing data model and functionality.  Migrating to it would create a catastrophically large B/C break that at best could be mitigated by developing multi-category support inside new content components (so com_content would have to be deprecated and an entirely new content component created built around this type of data model, same goes for any other component you want this capability in).

Core would have to define the canonical (main) category for each item and deal with ensuring the routing only points to that single canonical category (otherwise you get the SEO issues hinted at; WordPress deals with this in part by redirecting to the canonical URL).

Your best bet if you absolutely need this feature is to use a content component designed with this capability already in place.

**Comment by 1inkin** [comment]
@rdeutz, great advice, thanks for the help. I myself could not think of it before. and what if all the same rethink the structure of the core of Joomla? I was thinking about switching to the WP because of this problem, but too big problems would be. in the end, I continue to make copies of documents and post the same articles in different categories. Joomla seems to be designed to create convenience for users, and not to advise using tags or changing the structure that was made before the appearance of tags in Joomla.

**Comment by 1inkin** [comment]
@mbabker, I tried to use the CW Multicategories component to add article to several categories, but it does not work very well, so I refused it. other components to solve this problem i don't know

**Comment by rdeutz** [comment]
> @rdeutz, great advice, thanks for the help.

Always happy to help!

**Comment by 1inkin** [comment]
@rdeutz, it would be sarcasm

**Comment by mbabker** [comment]
CW Multicategories tries to "extend" com_content to add multi-category support.  Which is problematic at best I would suggest.

In some ways, tags CAN be a multi-category system.  It just comes with its own quirks and behavior issues.  If that can't work, I would seriously suggest finding a component that natively supports the feature because as I said I feel like anything trying to "extend" com_content and add the feature is just going to cause problems.

**Comment by Slava287** [comment]
There is an equally serious problem with tags. If you create tag menu items, a lot of duplicates appear. Half a year has passed and the problem remains.

**Comment by chmst** [comment]
@Slava287 You answered here to a very old and closed issue. 
Please open a new issue and give some more information aout your problem and your system environment.
