### ISSUE TITLE
[3.9] Repeatable Media Field

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#23132]
### Steps to reproduce the issue
Use a custom repeatable field and create an element of type media.

This was mentioned in passing by @AndySDH in https://github.com/joomla/joomla-cms/issues/22415#issuecomment-431341399 but wasn't super relevant to that issue so I'm moving it into it's own issue.

To make this work we either need to reload the subform field data out so that we can figure out what the type is and process it in the layout with that meta information. Alternatively we should store it with the field meta information prepended (which would be a b/c break but I'd argue the media field is right now broken as it should behave the same as the existing media field)

### Expected result
In the frontend the image is rendered (like the media custom field)

### Actual result
The image is not rendered (the path to the image is rendered as a string)

**Comment by AndySDH** [comment]
As you might have seen in #22415 that you linked, the repeatable field is getting replaced by the subform field: https://github.com/joomla/joomla-cms/pull/22446

And that already fixed this issue and it does render the media field.

That is if progress on that is made faster haha.

Please help with the testing to speed up the process as well :)

**Comment by ghost** [comment]
@AndySDH so this Issue can be closed?

**Comment by softforge** [comment]
So there is an issue with repeatable fields.
We cannot get subforms into joomla 3.10 because its a new feature and there are no new features in 3.10
BUT.... could subforms be brought in to 3.10 or even 3.9.6 (3.9.5 is about to be packaged) as a bug fix and not a feature? As its replacing one way of doing something with another and fixes a bug, could it not be argued that its a bug/security fix and not a feature?!?
Just saying

**Comment by AndySDH** [comment]
> @AndySDH so this Issue can be closed?

Technically yes... There is no point in fixing this if it's getting deprecated anyway...

But...

> So there is an issue with repeatable fields.
> We cannot get subforms into joomla 3.10 because its a new feature and there are no new features in 3.10
> BUT.... could subforms be brought in to 3.10 or even 3.9.6 (3.9.5 is about to be packaged) as a bug fix and not a feature? As its replacing one way of doing something with another and fixes a bug, could it not be argued that its a bug/security fix and not a feature?!?
> Just saying

You're preaching to the choir... I'm with you, I'd love if that was possible, we tried everything to get #22446 pushed in 3.9.x but they just don't want to do it :( I guess because it's a pretty big revamp and not just a small fix.

**Comment by ghost** [comment]
@HLeithner can you please decide as Release Lead 3.9?

**Comment by HLeithner** [comment]
@wilsonge do you see any bug fix for this in 3.9, else you should close it because we will have a subfields for j4.

**Comment by wilsonge** [comment]
I mean the things unusable. But it makes more sense to do a migration in j4 for subforms than try and fix stuff here
