### ISSUE TITLE
Error LDAP connection version 3.9.0

### ISSUE THREAD

**Issue by jsfernando** [joomla/joomla-cms#23180]
### Steps to reproduce the issue
Happening only to new users on the LDAP Network, when joomla login
Users Already Connected, It's Alright

### Expected result

Access to the user's front end equal to users who have logged in to ldap for a long time

### Actual result
Cookies are not active in your browser. You can not install the application with this feature disabled. There may also be a problem with the session.save_path of the server. If this is a case, even if you are not a candidate to exist or solve the problem on your own.

Could not verify if you are not a robot

### System information (as much as possible)
Joomla 3.9
php 5.6.30
MySQL 5.5.52-MariaDB 

### Additional comments
variable session.save_path = "/ tmp"
in User Options, Captcha - none selected -
Browser made clean cookies and caches
active cookies in browser

Message in pt-BR
Os cookies parecem não estar ativos no seu navegador. Você não poderá instalar o aplicativo com esse recurso desativado. Também, pode haver um problema com o session.save_path do servidor. Se este for o caso, consulte seu provedor de hospedagem se não souber como verificar ou resolver isso por conta própria.

Could not verify that you are not a robot

**Comment by mbabker** [comment]
The only place in core with that message is the install application.  If you are seeing that message, that means Joomla is not installed and cannot be installed correctly because we are unable to create the session cookie in your browser.  LDAP is also not available in the install application.

For the cookie issue, you will need to check and verify your browser settings and ensure cookies are allowed for the domain you have Joomla installed on.

For the session settings issue, if need be you will need to contact your hosting provider to address this.

Closing as this is not a core bug based on the available information.
