### ISSUE TITLE
[4.0] Batch remove tag from articles

### ISSUE THREAD

**Issue by tommy2486** [joomla/joomla-cms#23185]
Batch process the selected articles should have an option to remove a selected tag.

**Comment by richard67** [comment]
If a batch remove tags will be implemented, shouldn't there be then a batch add tags, too, for consistency?

**Comment by infograf768** [comment]
Isn't it what we already have? Taking into account that we first have to create the tag in the component before being able to use it in a batch.

**Comment by richard67** [comment]
@infograf768 I have no idea, am not using tags. Just was wondering why this feature request handles only removal.

**Comment by infograf768** [comment]
<img width="274" alt="screen shot 2018-12-01 at 10 44 52" src="https://user-images.githubusercontent.com/869724/49326681-2dd92c00-f556-11e8-8d58-620fecf971d6.png">

If we were to add a Remove tags, it could be an option in the same dropdown and modifying the title "Add Tag" I guess.

**Comment by richard67** [comment]
And how will then the tag(s) to be removed selected?

I think in that pullown now you can select one or mutliple tags to be added, is that right?

For removal, it would either need 2 submenus in that dropdown, 1 for adding and 1 for removing tags, each of them with a multi-select list for the tags like we have it now for adding.

Or it would need in the existing dropdown for each tag 2 items in the pullown like "add anothertag", "remove anothertag", ..., so you could add and remove tags in the same batch processing step.

But what if someone selects to add and remove the same tag with the 1st or the 2nd way?

So a 3rd way could be to have a list like now, but beside each tag name a toggle button "add / remove". You also could add and remove tags in the same batch processing step. This solution seems to be more idiot safe than the 2nd one. Title of that could be "Change tags" or so.

Or do it like I understand this feature request now, that the "Add tag" option will stay like it is, and a 2nd option "Remove tag" is added which has the same kind of multi-select pulldown list. But then it is also not clear what happens when the user selects to add and to remove the same tag in the same batch processing action.

**Comment by infograf768** [comment]
As I could not really find how to even remove tags in batch (I did not look much for now...) I was just thinking of a global `remove all tags` possibility from the items selected.
I also never use tags 😸

**Comment by richard67** [comment]
Well this feature request ask for an "option to remove a selected tag" (see first comment in github or description in issue tracker). If we were lawyers so we would take that word by word, it wouldn't be a "remove all tags". But it could be a "remove exactly only one selected tag" ;-)

@tommy2486 Would an option "remove all tags" be also ok for you? If not, did you really mean "remove a selected tag", or did you have a "remove selected tags" in mind?

**Comment by infograf768** [comment]
> But it could be a "remove exactly only one selected tag" ;-)

Indeed. Just looked too hard to me as you explained well above.

A solution could have been to have 3 fields:
Add or Remove tags: boolean
Add tags : showon 1
Remove tags: shown 0

Evidently one would not be able to do both at the same time.

**Comment by richard67** [comment]
Sounds good to me.

**Comment by richard67** [comment]
@infograf768 Maybe in addition a field "Remove all tags" in the same way as the existing "Keep original tags", so we have 5 options in the list:
- Keep original tags
- Remove all tags
- Add or remove (= toggle button or so)
- List with tags to add, only shown when "Add or remove" is 1 (= "Add"). This list should show all tags because it shall be possible to add a tag to some of the articles in the batch which do not have that tag assigned yet, while there are other articles in the batch which have that tag already assigned.
- List with tags to remove, only shown when "Add or remove" is 0 (= "Remove"). This list should only contain tags which are assigned to at least 1 article in the batch.

Would that make sense?

**Comment by pnkr** [comment]
Add tag in batch process exists but there is no option for batch removal. So I think it should be implemented. 

The feature should be like selecting some articles, click the batch icon and select which tags to remove.

**Comment by infograf768** [comment]
Good luck to find a volunteer to do that. Looks extremely complex.

**Comment by richard67** [comment]
Maybe it could be done in a more simple way.

**Comment by richard67** [comment]
But I have no idea how.

**Comment by richard67** [comment]
@infograf768 Another idea:
- Title "Modify tags" or just "Tags"
- 1 tristate button with values "No change" (0, which is same as current "Keep existing tags" but a better text, I think), "Add" (1) and "Remove" (2)
- Just 1 list for selecting tags which is shown when button value is not 0 and which contains all tags.
- When button is changed from values 1 or 2 back to 0, selection in list is cleared and list is hidden.

I think in the current implementation of "Add tags" it does not matter if some tag is selected which is already assigned to articles in the batch. The code should handle that. So it should also not matter with the new "Remove tags" if a tag is not assigned to any of the articles. Code of "Remove tags" could handle that in the same way as "Add tags", i. e. it just does not result in any change of that tag for that particular article(s).

**Comment by barraclm** [comment]
I understand that some people may not use tags. However, I for one do, and cannot believe that this is still an "issue" and the feature hasn't been implemented.

**Comment by brianteeman** [comment]
Where do we send your refund?

**Comment by HLeithner** [comment]
> Where do we send your refund?

Not help Brian.

@barraclm joomla is developed by people in their free time and if nobody has the skill and the time to fix an issue it could take some time till it's fixed.

**Comment by alikon** [comment]
please test https://github.com/joomla/joomla-cms/pull/40609
