### ISSUE TITLE
[4.0] Fatal error with getUpdateQueries()

### ISSUE THREAD

**Issue by b2z** [joomla/joomla-cms#23181]
So I am started to test my component on Joomla 4 :smile: 

After installation I cannot access System section anymore because of the fatal error:
`Argument 1 passed to Joomla\CMS\Schema\ChangeSet::getUpdateQueries() must be of the type array, boolean given, called in /var/www/nnt.ncj4/public_html/libraries/src/Schema/ChangeSet.php on line 74`

Additionally I have a warning:
`JFolder: :files: Path is not a folder. Path: /var/www/nnt.ncj4/public_html/administrator/components/com_competition/sql/updates/mysql`

![screen shot 2018-11-27 at 19 42 15](https://issues.joomla.org/uploads/1/289fb95f077f5536c9d94066a362cb9e.png)

Seems that I need to put my update SQLs under /sql/updates/mysql folder, because currently they are under /sql/updates. 

But the question is - should it lead to fatal error and block the access to System section?

**Comment by mbabker** [comment]
Oh the problems here are interesting...

Just looking at [this bit of code](https://github.com/joomla/joomla-cms/blob/7ba8b05c85a46681a26b6e4b6ce083f16c9024bc/administrator/components/com_installer/Model/DatabaseModel.php#L148-L161) tells me:

1) Core is trying to enforce a file path for SQL files; such a standardization does not exist and it should not be assumed the folder's presence actually means update deltas exist here

2) When parsing the XML manifest, the first `<schemapath>` element is used.  This should retrieve the path for the correct database driver from the manifest.  If whomever fixes this isn't copying the logic from [`Joomla\CMS\Installer\Installer::parseSchemaUpdates()`](https://github.com/joomla/joomla-cms/blob/7ba8b05c85a46681a26b6e4b6ce083f16c9024bc/libraries/src/Installer/Installer.php#L1109) (since core doesn't actually have a service layer for tasks like finding an extension's SQL schema files) then they're Doing It Wrong™.

3) There's no check to say "hey, there isn't a directory here, we should abort the task", it's just assumed the directory will always exist.

4) Likewise, the `Joomla\CMS\Schema\ChangeSet` class just arbitrarily assumes the folder it's being given actually exists and that the search for files will always return an array (ignoring it can have a boolean return if the filesystem API has an error)

**Comment by b2z** [comment]
1. Yeap that was working fine on J3.
2. Mine is looking like this now:
```
<install>
		<sql>
			<file driver="mysql" charset="utf8">sql/install.mysql.utf8.sql</file>
		</sql>
	</install>
	<uninstall>
		<sql>
			<file driver="mysql" charset="utf8">sql/uninstall.mysql.utf8.sql</file>
		</sql>
	</uninstall>
	<update>
		<schemas>
			<schemapath type="mysql">sql/updates</schemapath>
		</schemas>
	</update>
```
3 and 4. Well :) There a lot of work should be done ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23181">issues.joomla.org/tracker/joomla-cms/23181</a>.</sub>

**Comment by C-Lodder** [comment]
Having the same issue too.

Messing around with some code and will hopefully submit a worthy PR

**Comment by brianteeman** [comment]
Is this still an issue?

**Comment by b2z** [comment]
Well :) I will check later. Need to install fresh 4.0 to test.

**Comment by Quy** [comment]
Closing for now. You can comment here and we can re-open the issue.

**Comment by b2z** [comment]
I am back. No issue on the latest beta1-dev anymore
