### ISSUE TITLE
Smart Search should index Link [ABC] Text and URLs

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#23270]
### Steps to reproduce the issue
Enter any unique text in Link A, B or C Text to any article and search for it using finder (smart search).

### Expected result
The article is found searching the unique Link text.

### Actual result
The article is not listed in search results, the search does not index the Link text to the ABC urls.

### System information (as much as possible)
Joomla 3.9.1
OS Linux h
PHP 7.2.9
MySQLi 5.5.62-MariaDB

### Additional comments
The Link ABC text are editable in "Images and links" sections to the Article edit window.
A possible solution has been suggested at the forum: https://forum.joomla.org/viewtopic.php?f=708&t=967920

**Comment by ghost** [comment]
@Hackwar  can you please comment?

**Comment by Hackwar** [comment]
Yes, this is indeed true, but I don't see us fixing this in 3.x. Smart Search in 3.x has loads of issues, among them serious performance issues, which we fixed in 4.0. When now all core changes to Smart Search for 4.0 have been made, we should have a look at overhauling the finder plugins to add such features. However we should not automatically add this to 3.x, since there are several side effects, among them maybe unwanted information disclosure. If you want this in 3.x right now, you can create a copy of the content finder plugin, edit that stuff in and disable the core content finder plugin.

**Comment by ghost** [comment]
@Hackwar thanks for Comment.

Closing this for Reasons stated in above Comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23270">issues.joomla.org/tracker/joomla-cms/23270</a>.</sub>
