### ISSUE TITLE
TAGGING not working

### ISSUE THREAD

**Issue by adankupapa** [joomla/joomla-cms#23288]
### Steps to reproduce the issue
I am not sure exactly what i did to introduce this problem. I just noticed that, when I try to add a tag to a new or existing article, i get the error below in pale red background.

`Save failed with the following error: Duplicate entry '1024' for key 'PRIMARY'`

This entry number keeps increasing anytime i try saving again or attempt to add a new tag or even edit existing articles with tags.

The TAG i tried to add, does not get saved in the DB but the new article I tried to add gets saved. I have tried with a new installation and everything works but my current site still has this problem. Hoping I can be directed to some resources to enable be correct this. I have used the fix DB tool, reinstalled Joomla core files, but still have this problem. I have checked the forums for more than 2 weeks now and not found a solution hence my posting it here. 

### System information (as much as possible)
PHP Built On:	Linux #28 SMP Thu Mar 8 11:53:03 EET 2018 x86_64
Database Type:	mysql
Database Version:	5.6.36-82.1-log
Database Collation:	utf8_general_ci
Database Connection Collation:	utf8mb4_general_ci
PHP Version:	7.2.13
Web Server:	Apache/2.4.29 (Unix) mod_hive/6.25 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
WebServer to PHP Interface:	cgi-fcgi
Joomla! Version:	Joomla! 3.9.1 Stable [ Amani ] 27-November-2018 15:00 GMT
Joomla! Platform Version:	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by Quy** [comment]
Sorry this is not the right place to ask help since it is not reproducible with a clean install. Please post the link to your issue that is on Joomla Forum. Enable `System > Global Configuration > Error Reporting` to `Maximum` which should provide further details to which table is affected and post it there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23288">issues.joomla.org/tracker/joomla-cms/23288</a>.</sub>
