### ISSUE TITLE
Back end: custom admin menu: Warning: The administrator menu diler does not have - Menu Manager, Module Manager, Components Container. Select to turn on the menu recovery mode

### ISSUE THREAD

**Issue by helgator** [joomla/joomla-cms#23290]
### Steps to reproduce the issue
back end
set up a menu for administration with one menu item
create a new administrator module of type menu in position "menu" and use the created admin menu

### Expected result
the menu item gets displayed next to the standard Joomla menu items in the top bar

### Actual result
the menu item gets displayed next to the standard Joomla menu items in the top bar
"Warning: The administrator menu xxx does not have - Menu Manager, Module Manager, Components Container. Select to turn on the menu recovery mode."

### System information (as much as possible)
J3.9.1
PHP 7.2
SEBLOD
CB

### Additional comments
see https://github.com/joomla/joomla-cms/pull/13650#issuecomment-447635220

**Comment by brianteeman** [comment]
in the admin module set the Check to now

![image](https://user-images.githubusercontent.com/1296369/50060539-330cbc80-018d-11e9-801c-07e1e229f56a.png)

**Comment by helgator** [comment]
Setting "check Menu" to "No" gets rid of the warning. Thanks

**Comment by chuckscroggs** [comment]
Followed instructions to set check menu to "No" but it does not remove the warning.

**Comment by l-arnold** [comment]
For me, this was caused by trying to add as a Menu Item. to the Admin Menu "Advanced Module Manager" from Regular Labs.
After crashing my system, doing a backup/restore I seem to have been able to remove it now.

The Joomla Admin Menu does not seem to be editable nor have editable Menu Items..  There are 4x Modules of the Menu in the system.

At one Point I was able to get some "intermixing" of the Advanced Module Manager with the rest of the Joomla Menus, but it was giving the Error that the Administrative Menu does not have "Menu Manager, Module Manager, Components Container"...  Then a link for the Restore mode.

I was able to actually fix this without going to Restore mode by removing the Advanced Module Manager from the Admin Menu first, then deleting it second.
