### ISSUE TITLE
Enhancement request - Content - Page Navigation plugin - Below AND Above

### ISSUE THREAD

**Issue by IWOXX** [joomla/joomla-cms#23301]
Hi,
is there a chance for an enhancement to be able to select not only "Below" or "Above" but also "Below & Above" as new selection in dropdown box of Content - Page Navigation plugin. See also attached screenshot.

Reason: On mobile devices someone opens the first page of a menu/category and sees that it is not the right one reading the header there. So he/she could click immediately to the next page from above nav. But keep the below nav, cause if someone reads it, he/she can easily jump to the next page. So satisfaction for both use cases.

Thank you for your support!

BR IWOXX
![screen shot 2018-12-19 at 14 25 49](https://issues.joomla.org/uploads/1/d2d0dd23ad95d9de249f284589a85e22.png)

**Comment by ReLater** [comment]
I think it's better to solve this with a custom template override of the article view. Because it's not sufficient to add an option "Below & Above" to the plugin. The article view must understand this setting. Not that difficult for the core templates but most 3rd-templates will not understand the setting without code updates.

You can display the page navigation in an article view wherever you want with these lines:
```
<?php
if (!empty($this->item->pagination)) :
	echo $this->item->pagination;
?>
<?php endif; ?>
```

**Comment by brianteeman** [comment]
+1 for this being something that you do in a template override and not for the core

**Comment by ghost** [comment]
closed based on Answers above. Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23301">issues.joomla.org/tracker/joomla-cms/23301</a>.</sub>
