### ISSUE TITLE
Back to Top Protostar Joomla default template Do nothing

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23316]
### Steps to reproduce the issue

Click on 'Back to top' link at the bottom in mobile chrome.

### Expected result

The click on the link should result in the page scrolling upwards.

### Actual result

Do nothing

### System information (as much as possible)

Chrome mobile
Joomla 3.9.1
Joomla default protostar template

**Comment by richard67** [comment]
I can't reproduce this for Joomla 3.9.1 with the protostar template, neither with Chrome version 68.0.3440.83 64-Bit on iOS 12.1.2 nor with Chrome version 71.0.3578.99 32-Bit on Android 6.0.1.

@Milglius Could you provide some details about browser version and mobile OS and version?

**Comment by ghost** [comment]
Android 9 Chrome 71.0.3578.99

**Comment by richard67** [comment]
Let's see if someone else can reproduce that.

@Milglius Do you have any footer module enabled for the site?

**Comment by ghost** [comment]
Yes footer module enabled

Strange on main joomla site this feature works ok, maybe its wise to implement similar solution as is implemented on main joomla site? can we make pull request their code in joomla default protostar template?

<div id="scrollToTop" title="" class="scrollToTop" style="display: block;"></div>

**Comment by richard67** [comment]
@Milglius I think it would be better if someone tries to replicate the issue with a footer module enabled, and if so, investigate the error and fix it in the staging branch. I will see if I can find some time for that later.

**Comment by ghost** [comment]
@richard67 thank you

**Comment by mbabker** [comment]
The back to top solution on `joomla.org` is a third party plugin.

**Comment by ghost** [comment]
What is the diference in The back to top solution in your third party plugin and joomla core default protostar template solution that do nothing in Chrome mobile android?

**Comment by mbabker** [comment]
Protostar just uses an anchor tag to mark where the back to top link should take you, the plugin is a JavaScript based solution.

**Comment by ReLater** [comment]
And Protostar uses a short JQuery JS snippet in template.js to let the page scroll smoothly with a `e.preventDefault();`
. @Milglius Maybe that's the resaon that it doesn't work in your environment. Check the JavaScript console for errors. And/Or remove [these lines ](https://github.com/joomla/joomla-cms/blob/3.9.1/templates/protostar/js/template.js#L35-L38) for testing.

**Comment by richard67** [comment]
@Milglius I have tried again to reproduce the error with a standard Joomla footer module enabled at the footer position of Protostar, but I could not get the error, neither with Chrome version 68.0.3440.83 64-Bit on iOS 12.1.2 nor with Chrome version 71.0.3578.99 32-Bit on Android 6.0.1.

Did you use another 3rd party footer module? If so, maybe that one produces some invalid html which breaks the link to top neighbouring that module. What happens if you unpublish that footer module? Does it work then?

And can you provide a link to the website for which you have the error so we (me and others) can try to reproduce that with our mobile devices and Chrome versions and see what we can find out?

And could you test what @ReLater suggested above and let us know here about the result?

**Comment by ghost** [comment]
closed as no Answer was send, but Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23316">issues.joomla.org/tracker/joomla-cms/23316</a>.</sub>

**Comment by ghost** [comment]
how to provide link to you ?

**Comment by ghost** [comment]
> how to provide link to you ?

sorry, don't get what you mean.

**Comment by ghost** [comment]
its for ichard67 not to you franz

**Comment by ReLater** [comment]
@Milglius 

> how to provide link to you ?

> its for ichard67 not to you franz

Click on his avatar or username > There you'll see his website link > There you'll find a contact form.

**Comment by richard67** [comment]
@Milglius you should provide the link here for all. 

I did say:

> And can you provide a link to the website for which you have the error so we (me and others) can try to reproduce that with our mobile devices and Chrome versions and see what we can find out?

"we (me and others)" and not "I" because I think it needs more than 1 tester to be able to reproduce that problem, which seems to be very specific for particular versions of OS or browser, or to be related to some site specific things, since I was not able to reproduce it with a standard Joomla.
