### ISSUE TITLE
Where is the J4.0 dev 'Media' folder in this repository?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23438]
### Steps to reproduce the issue
At the top of this page, click on the <> Code tab, switch the brand to 4.0-dev. 

### Expected result
A top-level folder named 'Media'.

### Actual result
No folder named 'Media'

### System information (as much as possible)
I am using a Alpha 7dev site on CloudAccess.net and on the front end am using Firefox inspector to try to find the location of system messages. According to the inspector the one that tells you that you can't delete a primary template style is in, or initiated by, media/vendor/joomla-custom-elements/js/joomla.alert.min.js Please see screen shot.

![image](https://user-images.githubusercontent.com/36987494/50652012-07574800-0f7d-11e9-90dc-815a6de8a1c9.png)

**Comment by brianteeman** [comment]
https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment

**Comment by Bakual** [comment]
What Brian wanted to say is that the media folder will be populated by the build scripts (composer and npm) dynamically. The released package will contain them as usual, but you will not find it in the git repo. The link Brian posted explains how to use the build scripts yourself if you wish to build your own package based on Git.

Closing this issue as expected behavior.

**Comment by Scrabble96** [comment]
Thank you, @Bakual
