### ISSUE TITLE
Joomla! 4.0 - Is it/will it be possible to add menu items or quick links to main admin menu?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23446]
### Is your feature request related to a problem? Please describe.
Can't see any way to add custom items to admin menus

### Describe the solution you'd like
The option to add quick links to the main, blue admin menu on the left-hand side, for example straight to 'template files' or to 'add new article' or any other function that is going to be used frequently and regularly.

**Comment by ReLater** [comment]
NoYes.

No: At the moment there are some bugs making it unhandy https://github.com/joomla/joomla-cms/issues/23070 to add an additional menu.

Yes: Since Joomla 3.? one can create custom **administrator** menus. And also replace the original "Admin Menu" (see the back-end modules) with a custom one.

Yes: You can manipulate the `$menuTree` in a custom com_menu module override (layout). `myadmin.php` or something like that that you select in `Admin Menu` as `Layout`.

**Comment by Scrabble96** [comment]
Thanks, again, @ReLater

**Comment by ghost** [comment]
@Scrabble96 can you please close this Issue as its answered?

**Comment by brianteeman** [comment]
This should be closed as the question has been answered
