### ISSUE TITLE
RSS FEED does not work correctly

### ISSUE THREAD

**Issue by Chabi01** [joomla/joomla-cms#23473]
### Steps to reproduce the issue
Check this page : https://www.joomla.org/rss-news-feeds.html
Feeds works sometimes, doesnt sometimes.
Seems to be the same with a JEvent feed.

### Expected result
Feed shown in the page, not to dowload !

### Actual result
The browser (Firefox) ask to save "index.php" result. Erratic behavior as some links works, some dont.

### System information (as much as possible)
Last Joomla version, Last Jevent version (in my case)

### Additional comments
JEvents developers are unable to find out why the feeds are not working anymore and the erratic behavior is reproduced on the joomla feed page...

**Comment by brianteeman** [comment]
I cannot replicate that with the feeds on that page. Note those feeds are generated by feedburner and not by joomla

**Comment by Bakual** [comment]
Since this issue is not about the code of the CMS system but about the website, I'm closing it.
You can create a new issue at https://github.com/joomla/joomla-websites where website issues are tracked.

**Comment by GeraintEdwards** [comment]
Can we re-open this please?  This is an issue with that can be demonstrated with Joomla generated feeds - @Chabi01 used the joomla.org feed links in order to make it easy to replicate the issue.

See https://www.joomla.org/announcements.feed?type=rss or https://developer.joomla.org/?format=feed&type=rss

It arises with Firefox 64 and could be browser specific but other feeds work fine with Firefox 64 (e.g. http://feeds.bbci.co.uk/news/rss.xml) - try it with one of your own sites in Firefox 64,

I have done a lot of experimentation with mime types etc. and can't find what is different between the BBC feeds and the Joomla ones.  BBC uses text/xml instead of application/rss+xml but changing that doesn't help in Joomla.

**Comment by ReLater** [comment]
Firefox has removed support for Feeds completely! You need addons, now.
Edge, too. I didn't test other browsers.

> but other feeds work fine with Firefox 64 (e.g. http://feeds.bbci.co.uk/news/rss.xml) 

I don't know what this means. I don't see a feed, just xml source code.

**Comment by brianteeman** [comment]
Official statement

https://www.gijsk.com/blog/2018/10/firefox-removes-core-product-support-for-rss-atom-feeds/

**Comment by mbabker** [comment]
So again, not a core Joomla issue if the selected browser is no longer supporting parsing a RSS or Atom XML document into something user friendly (FWIW Chrome has always required an extension for this).

**Comment by Bakual** [comment]
Closing again then 👍

**Comment by Fedik** [comment]
@GeraintEdwards the difference:
```xml
<?xml-stylesheet title="XSL_formatting" type="text/xsl" href="/shared/bsp/xsl/rss/nolsol.xsl"?>
```

which later load a `<link rel="stylesheet" href="/shared/bsp/xsl/rss/css/nolsol_xsl.css" type="text/css"/>`

BBC RSS It is styled XML document (when you open it in Browser).

**Comment by Chabi01** [comment]
Hi,
I see this : when i save the file, i can see several link to css file on my own site with feed links. If i removed the css style called in the file, i can then open the file in the browser.
Dont know if this is the issue or not.
Xavier
