### ISSUE TITLE
Request a new feature - Social Login via Oauth

### ISSUE THREAD

**Issue by neo191987** [joomla/joomla-cms#23486]
Hi, I do not see where I can request a new feature so I will write here. Is it possible to make a plugin for login via social networks using oauth. I see that there are all available libraries for this. It would be great to have such a built-in feature.

**Comment by Bakual** [comment]
From what I see there are already various extensions on JED (https://extensions.joomla.org) which offer that functionality. So there is no reason to add it to core itself.
Or did you try those and they don't work?

**Comment by neo191987** [comment]
Hi, easier to use the built-in library of Joomla which has several API who can do a great job writing for various applications. If  create a single plug-in for registration and login, then multiple plugins will be easily written. It only needs to  the user's linked and, if desired, unlinked it. The method of authentication itself is very easy.

**Comment by mbabker** [comment]
Not every potential feature needs to be included in the core of your selected CMS.  Features aren't "better" because they are included in core, features aren't more secure because they are included in core.  The core package is really nothing more than an opinionated set of features, and even with those a bulk of people don't use them.

**Comment by Bakual** [comment]
I'm closing this feature request since such 3rd party plugins already exist and thus the feature is already available.
