### ISSUE TITLE
[4.0] XTD plugins broken in frontend

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#23510]
### Steps to reproduce the issue
Install a clean 4.0.dev branch
Install blog
Log in frontend as superuser and edit an article.
Try to use any xtd-editor, for example `Menu`

### Expected result

The modal displays to choose a menu item to insert in the textarea

### Actual result
404 View not found [name, type, prefix]: items, html,

Same for article, contact, module

**Comment by brianteeman** [comment]
See #21208

**Comment by astridx** [comment]
The problem is, that in line https://github.com/joomla/joomla-cms/blob/c17bfc4bfc75847c334176c519a87ba871c401de/plugins/editors-xtd/menu/menu.php#L46 the path 
`$link = 'index.php?option=com_menus&amp;view=items&amp;layout=modal&amp;tmpl=component&amp;' . Session::getFormToken() . '=1&amp;editor=' . $name;
`
is instead of
`$link = 'administrator/index.php?option=com_menus&amp;view=items&amp;layout=modal&amp;tmpl=component&amp;' . Session::getFormToken() . '=1&amp;editor=' . $name;
`

So the `administrator` is missing.

**Comment by Quy** [comment]
Please test PR #23530<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23510">issues.joomla.org/tracker/joomla-cms/23510</a>.</sub>

**Comment by infograf768** [comment]
Maybe we should reopen as #23530 is no good?

**Comment by ghost** [comment]
@infograf768 can i close this Issue having PR #23539?

**Comment by infograf768** [comment]
I would wait as @astridx is not sure yet of her PR

**Comment by ghost** [comment]
Closed as having Pull Request #25367
