### ISSUE TITLE
Privacy Note not translatable 3.9.1 joomla

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23524]
### Steps to reproduce the issue

Try to translate Privacy Note

### Expected result

Privacy Note translated

### Actual result

nothing changes in Privacy Note

### System information (as much as possible)

joomla 3.9.1

**Comment by brianteeman** [comment]
Are you referring to this https://docs.joomla.org/J3.x:Privacy#Short_Privacy_Policy

**Comment by ghost** [comment]
referring to Content - Confirm Consent 
Privacy Note * is in it near required checkbox to a form eg the core contact form.

**Comment by infograf768** [comment]
For the default `Short Privacy Policy`.
The default string should be translated.
For example in French we have in `administrator/language/fr-FR/fr-FR.plg_content_confirmconsent.ini`
PLG_CONTENT_CONFIRMCONSENT_FIELD_NOTE_DEFAULT="En soumettant ce formulaire, vous acceptez la politique de confidentialité de ce site Web et le stockage des informations soumises."


If you want to modify the default text, you have 2 solutions:
1. Via language overrides, create as many overrides as languages for that constant.
2. Also a solution is to enter in the default field a new constant and then create the string via Languages Overrides.
<img width="561" alt="screen shot 2019-01-13 at 12 06 45" src="https://user-images.githubusercontent.com/869724/51084546-e2589700-172b-11e9-83bd-52d069c8424b.png">

<img width="625" alt="screen shot 2019-01-13 at 12 08 16" src="https://user-images.githubusercontent.com/869724/51084553-f1d7e000-172b-11e9-92de-9ffbb01412e2.png">

<img width="647" alt="screen shot 2019-01-13 at 12 11 01" src="https://user-images.githubusercontent.com/869724/51084564-53984a00-172c-11e9-9b80-f2c38a9d291a.png">


result:

<img width="616" alt="screen shot 2019-01-13 at 12 12 31" src="https://user-images.githubusercontent.com/869724/51084576-935f3180-172c-11e9-934e-d6213553017a.png">

For the full policy 
Select a Privacy article containing whatever you want in the language of your choice.
If your site is set as multilingual, you can associate the articles concerned so that will be presented the article in the language of the frontend.

**Comment by ghost** [comment]
The problem is in near required checkbox to a form eg the core contact form.

What you done to make it change from  Privacy Note *  to Note de confidentialite* ? 

How you managed to modify this text **Privacy Note***

**Comment by infograf768** [comment]
The string for that is
`PLG_CONTENT_CONFIRMCONSENT_CONSENTBOX_LABEL`

![screen shot 2019-01-14 at 09 19 54](https://user-images.githubusercontent.com/869724/51102032-9b2ade80-17dd-11e9-94c8-2eaf701bbae6.png)


If you want to modify it, you may (same method as used above) use a language override in the **site** part of the language.

<img width="567" alt="screen shot 2019-01-14 at 09 26 20" src="https://user-images.githubusercontent.com/869724/51102254-8438bc00-17de-11e9-9396-37e5e1bbb38b.png">

**Comment by infograf768** [comment]
As this type of question should have been posted on the forum, I am now closing this issue.
