### ISSUE TITLE
[3.9.2]Login module doesn't work

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#23580]
### Steps to reproduce the issue
use the login module in front

### Expected result

Login and redirection

### Actual result

No login and redirection to index.php

### System information (as much as possible)
PHP exécuté sur | Linux am4.siteground.biz 3.12.18-clouder0 #28 SMP Thu Mar 8 11:53:03 EET 2018 x86_64
Type de la base de données | mysql
Version de la base de données | 5.6.40-84.0-log
Interclassement de la base de données | utf8_general_ci
Collation de la connexion à la base de données | utf8mb4_general_ci
Version de PHP | 7.1.26
Serveur web | Apache
Serveur web pour interface PHP | cgi-fcgi
Version de Joomla | Joomla! 3.9.2 Stable [ Amani ] 15-January-2019 15:00 GMT
Version de la plateforme Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navigateur | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

### Additional comments
no error in console
tested in 2 sites

**Comment by infograf768** [comment]
Can't reproduce the issue here.

**Comment by micker** [comment]
Can i put link for testing ?

**Comment by infograf768** [comment]
I would not do that in public.

**Comment by HLeithner** [comment]
@micker if your site is public you can add it here

**Comment by infograf768** [comment]
imho, it would not help if we do not have credentials...

**Comment by HLeithner** [comment]
yeah thats true...

**Comment by ElephantInTheRoomFirst** [comment]
Did you disable any plugin related to the login or authetication in backend or install new one which can cause conflict?

**Comment by maciej-wol** [comment]
Hello

I have same problem with redirection on component who I write.

In view I have:

if ($user->get('guest')) {
$redirectUrl = urlencode(base64_encode(JRoute::_('index.php?option=com_mwindustries&view=orders',false)));
$url = JRoute::_('index.php?option=com_users&view=login&return='.$redirectUrl,false);
$app->redirect($url);	
}
but after login to site Im redirect do profile page.

I was check code and find that problem is in com_users\models\login.php, line 65
if (!JUri::isInternal($data['return']))
{
    $data['return'] = '';
}

When Im put var_dump($data['return']); in line 64 its return "/joomla/index.php?option=com_mwindustries&view=orders&Itemid=104", but same var_dump in line 69 return -  string(0) ""

So problem is in JUri::isInternal function.

Sins
Mac

**Comment by maciej-wol** [comment]
Due to https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login%3F return address must be non-sef.
So this address works good $redirectUrl = urlencode(base64_encode('index.php?option=com_mwindustries&view=orders')); 
After login user is redirect to good page.

**Comment by ghost** [comment]
can this issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23580">issues.joomla.org/tracker/joomla-cms/23580</a>.</sub>

**Comment by ghost** [comment]
Closed as no Answer; please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23580">issues.joomla.org/tracker/joomla-cms/23580</a>.</sub>

**Comment by ElephantInTheRoomFirst** [comment]
@franz-wohlkoenig 
I have modfied my layout and view class as per ACL, therefore there is no need of separate dashboards for different user groups now. :)
