### ISSUE TITLE
Something wrong in /libraries/cms/application/cms.php

### ISSUE THREAD

**Issue by EMartinezM** [joomla/joomla-cms#23588]
### Steps to reproduce the issue
Warning: count(): Parameter must be an array or an object that implements Countable in /web/htdocs/www.ZZZZZZZZ.com/home/libraries/cms/application/cms.php on line 464

### Expected result
something wrong on lines:
```

`		{
			$session = JFactory::getSession();
			$sessionQueue = $session->get('application.queue');

			if (count($sessionQueue))
			{
				$this->_messageQueue = $sessionQueue;
				$session->set('application.queue', null);
			}
		}`

```

### Actual result

`464 if (count($sessionQueue))`

**Comment by ReLater** [comment]
@EMartinezM 
Please close this issue.

`/libraries/cms/application/cms.php`

This file doesn't exist in that directory anymore since Joomla 3.8.0. https://github.com/joomla/joomla-cms/tree/3.9.2/libraries/cms.

If you're using the current Joomla 3.9.2 go to Extensions > Database > and click on the "Fix" button to remove outdated files.

If you're using an outdated Joomla version you should update your Joomla or [ask in a forum](https://forum.joomla.org/) for help.
