### ISSUE TITLE
[4.0] Can not suppress "server warnings" for long time

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#23623]
### Steps to reproduce the issue
Use "outdated" PHP version. Open `/administrator` homepage

### Expected result
I can suppress the error message for a long time by click.

### Actual result
I can not suppress the error message, each navigation to dashboard page I need to close the popup.

### System information (as much as possible)
Joomla 4.0 alpha-6
PHP 7.0

### Additional comments
![image](https://user-images.githubusercontent.com/18716997/51534610-40d1f380-1e57-11e9-8b7f-874ac016e374.png)

**Comment by mbabker** [comment]
Disable the plugin.  The same as you have to do on 3.x.

**Comment by alex7r** [comment]
Shouldn't this be documented or, even better, have link inside this message like:
`"to disable this notification please disable [linkstart]this plugin[/linkend]"`

**Comment by mbabker** [comment]
It is documented somewhere in the docs wiki, not in the CMS itself.

The only change between 3.x and 4.0 as far as the plugin is concerned is how alerts are rendered.  Otherwise, functionally everything is the same about the PHP plugin's logic.  If you feel something needs to change, propose it against 3.x and sooner or later it'll find its way into 4.0.  Personally, I don't think anything about it needs to change, but I'm also that PITA that makes sure PHP gets updated on the production servers before a version EOL's 😆

**Comment by brianteeman** [comment]
The correct way to remove the message is to update the server. This is completely documented in the notice

**Comment by brianteeman** [comment]
This should be closed. The code is working as intended
