### ISSUE TITLE
bug in menues

### ISSUE THREAD

**Issue by caw67** [joomla/joomla-cms#23646]
### Steps to reproduce the issue

After upgrade to 3.9.2 i cant choose templates in the menues!!!

it hidden in the source code!

**Comment by brianteeman** [comment]
https://docs.joomla.org/J3.x:Template_Style_field_not_shown_in_Menu_Items

**Comment by caw67** [comment]
ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23646">issues.joomla.org/tracker/joomla-cms/23646</a>.</sub>

**Comment by ChristineWk** [comment]
Fixed in: https://docs.joomla.org/J3.x:Template_Style_field_not_shown_in_Menu_Items<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23646">issues.joomla.org/tracker/joomla-cms/23646</a>.</sub>
OK, I was too late :-)
