### ISSUE TITLE
Error when deinstalling joomla standard package components (system components) in Joomla 3.9.2

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#23643]
### Steps to reproduce the issue
I de-installed all banner components/plugins in the manager

### Expected result
component de-installed from Joomla system

### Actual result
de-installed component still accessible from the components menu.
component visible as com_banners_categories instead of "Banners" in the components menu.
when accessing com_banners_categories I get the error:
Fehler
Bei der Erweiterung „com_banners“ fehlt die ACL-Datei oder ist fehlerhaft strukturiert.
in the com_banners_categories page.

### System information (as much as possible)
Joomla 3.9.2
german language in the backend.

### Additional comments
Please fix the error so that com_banners cleanly de-installs on Joomla installations which don't need Banners.

**Comment by infograf768** [comment]
Confirmed. It is not the case for com_contacts.

**Comment by Bakual** [comment]
I'm actually surprised you can uninstall it.
You should not do that since the files will probably come back with one of the next updates.
Instead of uninstalling a core extension, you should just disable it.

**Comment by infograf768** [comment]
Correction: same for com_contacts

**Comment by infograf768** [comment]
@Bakual 
Nevertheless, it is a weird behaviour.

**Comment by infograf768** [comment]
Ok, we found the issue.
In our sql the categories submenu are assigned the component_id of com_categories in the _menu table. That is wrong. It should be the same id as the component.
We have 6 for contacts categories (whch is the com_categories id) instead of 8 which is the com_contact id.
We will make patch (but still, it is really no use to uninstall a core component, as said above)

**Comment by alikon** [comment]
i think that if an extension (mainly core) is `protected` in the #_extensions table then it cannot be unistalled
only disabled if we can agree on this i'll make a PR

**Comment by infograf768** [comment]
I have asked this question to maintainers. Waiting for comments. :)
In any case, we have to patch our install sqls for this component_id as they are damned wrong.
Let's wait for this PR to be merged https://github.com/joomla/joomla-cms/pull/23585 before touching at sqls

**Comment by brianteeman** [comment]
For the original poster - the best and only truly effective thing you can do is to disable the extension in the extension manager. This will remove it from the menus etc and you wont have problems with updates

**Comment by mbabker** [comment]
> i think that if an extension (mainly core) is `protected` in the #_extensions table then it cannot be unistalled

https://github.com/joomla/joomla-cms/pull/17219 was supposed to fix this in an acceptable way, I abandoned it because it became too painful to keep rebasing the PR and not get it tested out and merged.  Long and short though is you can't base whether an extension can be uninstalled on the `protected` column (none of the core extensions should be uninstalled, many of them are not protected because they can be disabled without consequence).

**Comment by alikon** [comment]
yes i quite remember #17219, at least it reached the RTC status :smile:

**Comment by BRoehling** [comment]
ok. I see. And is there a way to bring back com_contact?

**Comment by Bakual** [comment]
> ok. I see. And is there a way to bring back com_contact?

Copy the full Joomla package over your existing installation so you have all files again. Then discover install it and hope for the best.

**Comment by ghost** [comment]
closed as Issue seems resolved; please reopen if its not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23643">issues.joomla.org/tracker/joomla-cms/23643</a>.</sub>
