### ISSUE TITLE
Timezone Errror in JForm layout Repeatable

### ISSUE THREAD

**Issue by thuebschmann** [joomla/joomla-cms#23703]
### Steps to reproduce the issue
Create an componet confìg like this: config.xml
fill in Date with time in Repeat able table (before_save.jpg)
save the form, then the shown time is changed (after_save.jpg)

### Expected result
Show the save Time after saving!

### Actual result
The saved time leave the timezone

### System information (as much as possible)
[systeminfo-2019-01-28T14_21_30+01_00.json.txt](https://issues.joomla.org/uploads/1/b7b051d5553aacf1bdadd1fc1bde6bc3.txt)

### Additional comments
This issue take on both sites (Frontent and Backend(Config))
BeforeSave
![screen shot 2019-01-29 at 10 23 45](https://issues.joomla.org/uploads/1/4677a376bc4b235800f472441c5186a2.jpg)
After Save
![screen shot 2019-01-29 at 10 23 16](https://issues.joomla.org/uploads/1/96288e51f93deeccee9f1a86a3de3f3c.jpg)
Config:
[config.xml.txt](https://issues.joomla.org/uploads/1/d06446aff7f98090ad2e728e8f0339f4.txt)

**Comment by ghost** [comment]
@HLeithner can you please comment?

@thuebschmann changed Status "Urgent" to "Medium" according to https://docs.joomla.org/Bug_and_Issue_Tracker_Priority

**Comment by HLeithner** [comment]
@continga can you check this please?

**Comment by Quy** [comment]
@roland-d

**Comment by Fedik** [comment]
@thuebschmann you should not use `filter="user_utc"` in your `config.xml` for the calendar in the subform field. Because it not applied to subform field while saving, but applied by the calendar field while displaying.

At current point of time the fields in the subform field does not support filtering/validation.

**Comment by thuebschmann** [comment]
@Fedik I have try this option too. but this is no different.

At current point of time the fields in the subform field does not support filtering/validation.
--> thats the reason of this issue report<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23703">issues.joomla.org/tracker/joomla-cms/23703</a>.</sub>

**Comment by Fedik** [comment]
>  I have try this option too. but this is no different.

@thuebschmann I meant, you should remove that attribute  :wink:

**Comment by ghost** [comment]
@thuebschmann any Comment?

**Comment by thuebschmann** [comment]
if I remove the attribute i have the problem too.

In normal field i can User filter="user_utc", but in Repeatable subform isn't work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23703">issues.joomla.org/tracker/joomla-cms/23703</a>.</sub>

**Comment by thuebschmann** [comment]
if i use UTC as Konfig-Time-Zone there is no problem. But I need the Berlin Timezone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23703">issues.joomla.org/tracker/joomla-cms/23703</a>.</sub>

**Comment by Fedik** [comment]
> if I remove the attribute i have the problem too.

Are you sure? because I cannot reproduce it.
if you do not use filter attribute, the time will NOT be modified **after save** as you asked in your first comment, 

The problem remain that the default value in UTC, but after save it stay what was selected.
But again, this is because 'subform' do not support filter/validation at current time.

This is known issue.
There even was a pull request #14189

**Comment by ghost** [comment]
@HLeithner should #14189 reopened and merged?

**Comment by HLeithner** [comment]
@franz-wohlkoenig no, this PR will not be merged, UTC should work and hopefully we get #14189 rewritten for 4.0 @Harmageddon

**Comment by Harmageddon** [comment]
Indeed, #14189 sadly didn't have very high priority, because surprisingly few people noticed / reported that filters and validations don't work in subforms. Right now, it is too late to introduce it to 3.x because of our version roadmap.
I hope I manage to get a new PR for 4.0 ready for testing within the next two weeks. Will inform you then.

**Comment by jwaisner** [comment]
@Harmageddon are you still looking at getting a PR set for this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23703">issues.joomla.org/tracker/joomla-cms/23703</a>.</sub>

**Comment by N6REJ** [comment]
@jwaisner reading #14189 it's already been solved for 4.0

**Comment by jwaisner** [comment]
Closing as [#14189](https://github.com/joomla/joomla-cms/pull/14189 "#14189")has confirmed that previous merges have corrected this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23703">issues.joomla.org/tracker/joomla-cms/23703</a>.</sub>
