### ISSUE TITLE
Joomla 3.9.2 and W3 Validate org

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#23774]
### Steps to reproduce the issue

go to https://validator.w3.org and write your Joomla 3.9.2 site into the validate mask. in "more options" check all checkboxes. finally, click "check".

### Expected result

no errors / warnings

### Actual result

gives me warnings in Joomla's core coding style and sometimes plugins are affected.

### System information (as much as possible)

Joomla 3.9.2

### Additional comments

There shouldn't be any errors / warnings in https://validator.w3.org with Joomla. This way Joomla sites are up to the web standard and runs errorfree with every modern browser.

**Comment by ReLater** [comment]
I ran w3c validator with a 3.9.2 site and couldn't find any <u>serious</u> error that's a drama for modern browsers and ancient ones.

Only Plugin loadmodule creates "No p element in scope but a p end tag seen" because this module doesn't remove the `<p>` tags when inserting `<div>` containers which results in `<p><div>...</div></p>`. (BTW: Not that easy to correct this reliably without additional performance issues.)

If you find serious errors you should post and describe them more precisely here. Otherwise nobody knows what you are talking about and can decide if it's worth to spend time with it.

**Comment by mbabker** [comment]
The bulk of these types of validation errors are going to be template specific, and on the configuration of the validator (it groans about HTML4 compliant structures which is a template level code change, or use of `<meta>` tags to fill in info for Google's structured data).  The odds of there being a core level fix to make that 100% satisfies the W3C validator are slim to none.

**Comment by BRoehling** [comment]
I only encountered warnings with my 3.9.2 site. See images:
It would be wonderful if the checking gives you zero warnings and errors.

![showing results for httpwww lkw-fahrschule-ruch de - nu html checker - google chrome](https://user-images.githubusercontent.com/46946646/52298931-7f51cd00-2984-11e9-9449-5ba138f78244.jpg)

![showing results for httpwww lkw-fahrschule-ruch de - nu html checker - google chrome_2](https://user-images.githubusercontent.com/46946646/52298950-8b3d8f00-2984-11e9-8108-59ce1e3b0db7.jpg)

**Comment by mbabker** [comment]
You need to set your template as a HTML5 template to make the type attribute warnings go away.  The warnings in this specific case mean nothing more than a few extra bytes are being sent with the response by declaring something that is not necessary for an HTML5 document type.

Again, this is a template level change and not one for core to make.

**Comment by BRoehling** [comment]
It's best to contact the template making company. Thanks for pointing that out.

**Comment by Bakual** [comment]
I'm closing the issue as it is not a core issue.
