### ISSUE TITLE
[4.0] tmpl=component lost during navigation in modal

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#23832]
### Steps to reproduce the issue
1. Create new article
2. Select `Image` in `CMS Content` context menu to open com_media modal
3. Open context menu for an image, select edit
4. Click the cancel button in the toolbar at the top

### Expected result
The iframe navigates back to `administrator/index.php?option=com_media&tmpl=component&e_name=jform_articletext&asset=com_content`

### Actual result
The iframe loses the `tmpl=component` parameter, and the iframe now contains full navigation of the backend.
![Modal error](https://imgur.com/Do6Y5QK.png)

### Additional comments
This can be repeated ad infinitum to create modals inside modals inside modals...

**Comment by bahl24** [comment]
@Chaosxmk I was able to successfully reproduce the issue and also noticed some other bugs. I have started working on this

**Comment by bahl24** [comment]
@dgrammatiko @puneet0191 @bembelimen 
The original url params are-
![screenshot from 2019-02-11 20-09-10](https://user-images.githubusercontent.com/36095178/52582602-8af53600-2e53-11e9-9ce7-50af17baa110.png)
which helps to load http://localhost/joomla-cms/administrator/index.php?option=com_media&amp;tmpl=component&amp;e_name=jform_articletext&amp;asset=com_content&amp;author=&path=local-0:/
Notice the absence of styling in this page

> * Open context menu for an image, select edit
> * Click the cancel button in the toolbar at the top

After this the url params become-
![screenshot from 2019-02-11 23-18-28](https://user-images.githubusercontent.com/36095178/52582813-1969b780-2e54-11e9-98e6-0005594d53be.png)
This is because cancel and other buttons redirect back to original page which is diff from `tmpl=component` . I am confused about how to proceed as it is not a typical bug, imho a get variable may be req to control display of nav toolbar. What are your views?

**Comment by dgrammatiko** [comment]
@bahl24 actually it should be quite easy fix:
The media manager has a state store all we need to do is make sure that the data there has also the result of the function isModal() : https://github.com/joomla/joomla-cms/blob/ad2c673ac27c2fd19bbdf6003aee0451d068de16/administrator/components/com_media/resources/scripts/components/browser/browser.vue#L75-L77

So basically move this function to the API: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/resources/scripts/app/Api.js

Make sure that the data returned from this method gets saved in the store or a cookie or localStorage...

Then adjust the fetch urls to always check for this data and append or not the `tmpl=component`

**Comment by dgrammatiko** [comment]
@bahl24 Ignore my comment. This one I cannot reproduce it

**Comment by dgrammatiko** [comment]
@bahl24 there is a PR: #23880 please test it
