### ISSUE TITLE
"SEO Settings" label wrong in português

### ISSUE THREAD

**Issue by dioubernardo** [joomla/joomla-cms#23981]
In /administrator/index.php?option=com_config

- English
![image](https://user-images.githubusercontent.com/3487994/53242758-7bac8e80-3684-11e9-9742-dbb21b8e26f4.png)

- Portuguese
![image](https://user-images.githubusercontent.com/3487994/53242832-b7475880-3684-11e9-8b9e-135abae44747.png)

One possible translation would be "Configurações de SEO", the current translation is "Configuration saved successfully"

### System information (as much as possible)
Joomla version 3.9.3
Português do Brasil (pt-BR) Lang 3.9.3.1

**Comment by brianteeman** [comment]
@bakual

**Comment by Bakual** [comment]
@dioubernardo You need to contact the portuguese translation team as that comes from the language pack. See https://community.joomla.org/translations/joomla-3-translations.html#pt-br
Or you can directly contribute a better translation on Crowdin (https://crowdin.com/project/joomla-cms/pt-BR#) as I think that language team is using Crowdin for their translations.

I'm closing this issue since it isn't a core issue.
