### ISSUE TITLE
frontend create article select category bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23991]
### Steps to reproduce the issue

frontend create article and select category then try to select category one more time if you try to select category you can only do this using search and crate new category

Steps to reproduce the issue

    Install Joomla 3 
    Create an user with group Author
    Log into front-end with this account
    Click on menu item Submit new article
    Create an article, select a category. All categories are selectable in category selection field.
    Save the article
    Publish the article in back-end
    Open the article in front-end as Author and select Edit
    Try to change the category. Not possible! Only the saved category is shown in category selection.

### Expected result

frontend create article and select category

### Actual result

frontend create article and select category if you try to select other category you can only do this using search and crate new category, but cant select category as it is set.

### System information (as much as possible)

joomla 3.9.3

**Comment by ghost** [comment]
so it is fixed now ?

**Comment by infograf768** [comment]
Not sure I understand your problem.
As a superuser, I create an article and select a category for this article (I do not save it yet).
Then I move to another Tab (to set the language if I need it for example).
Then come back to the Category field and select another category in the dropdown.
No issue at all here.

maybe your issue is due to your template?

**Comment by ReLater** [comment]
Tested with an Manager account. I can NOT reproduce this issue, too. I can change the category as often as I want.

Maybe you have set additional settings due to category in the menu item "Submit an Article".

**Comment by ghost** [comment]
closed as unconfirmed Report, it can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23991">issues.joomla.org/tracker/joomla-cms/23991</a>.</sub>

**Comment by ghost** [comment]
@infograf768 you understand problem corectly. Just log in frontend. Tested with an author account from frontend the issue still is. Using default joomla protostar template.

Please reopen this issue

**Comment by ReLater** [comment]
I've tested it again with an Author account and still can't reproduce the issue. Author can change the category without any issues.

**If the Author saves the article and then opens edit again** (after an admin has published it), yes, then the Author cannot select another category from the dropdown but can create a new category (which sounds wrong to me, not only because the redirection after Save leads on a 404 page).

Is it that what you're talking about?

Please provide always a detailled step-by-step instruction. It makes it so much easier to understand issues.

**Comment by ghost** [comment]
@ReLater yes this is what I am talking about. 

> Author cannot select another category from the dropdown but can create a new category

And also as @infograf768  described it but just as author.

**Comment by ReLater** [comment]
Could you then please update your "Steps to reproduce the issue" for others. You forgot to mention the "Save" and "Edit again" steps.

### Steps to reproduce the issue
- Install Joomla3 with testing sample data (See also comment https://github.com/joomla/joomla-cms/issues/23991#issuecomment-469287381)
- Create an user with group `Author`
- Log into front-end with this account
- Click on menu item `Submit new article`
- Create an article, select a category. All categories are selectable in category selection field. 
- Save the article
- Publish the article in back-end
- Open the article in front-end as `Author` and select `Edit`
- Try to change the category. Not possible! Only the saved category is shown in category selection.
- Enter a new category name into the search bar of the category selection and press Enter.

##### Issue 1:
A new category is created. It's strange that I can not select an existing category but can create a new one.

##### Issue 2:
Also strange: Save the article and you will be redirected to a 404 error page <strike>because the form uses the old category in return path</strike> (see https://github.com/joomla/joomla-cms/issues/23991#issuecomment-469287381).

**Comment by ReLater** [comment]
Addition: I've tested with `SEF`, `Use URL Rewriting`, `Modern URL Routing`,  and `Remove IDs from URLs`.
I don't know if that's relevant here.

Edit: Yes, that's relevant for Issue 2 because the new category is created in first level of article categories. Modern Routing needs a menu item where the new category is included. Thus the article lands always on a 404 as long as there's no matching menu item.

**Comment by ghost** [comment]
@ReLater Yes tested with SEF, Use URL Rewriting, Modern URL Routing, and Remove IDs from URLs

**Comment by ReLater** [comment]
@franz-wohlkoenig 
Could you please reopen the issue because we need at least clarifying statements for issues I described in comments https://github.com/joomla/joomla-cms/issues/23991#issuecomment-469283526 and https://github.com/joomla/joomla-cms/issues/23991#issuecomment-469287381
Thank you!

**Comment by ghost** [comment]
confirmed that this issue still not fixed and also exists in joomla 3.9.4

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by infograf768** [comment]
imho, as the article has been approved and already published, changing its category could create issues. It would need re-approving.

**Comment by brianteeman** [comment]
When an article has been approved you can edit the content without any more approval. So restricting a category change for that reason is not logical

**Comment by HLeithner** [comment]
The restriction makes maybe sense, at least in a strange way. If it's this way we can't change it in 3.9 but we should fix the "create" category bug. The category should not be a dropdown if its readonly, which it is in this case.

**Comment by infograf768** [comment]
I will prepare a patch for that (it has still to look like a dropdown but readonly as we do when article is associated)

<img width="585" alt="Screen Shot 2019-03-17 at 10 36 02" src="https://user-images.githubusercontent.com/869724/54488339-da8aaf80-48a0-11e9-9065-15c8cc1663da.png">

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/24216
