### ISSUE TITLE
Upload and Update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24082]
The message on the Upload and update tab of com_joomlaupdate says

` You can use this feature to update Joomla if your server is behind a firewall or otherwise unable to contact the update servers. First download the Joomla Upgrade Package in ZIP format from the official Joomla download page. Then use the fields below to upload and install it.
`

With the link going to https://downloads.joomla.org/latest

There are NO update packages on that page

**Comment by jeckodevelopment** [comment]
There's the button "View all packages" to see all the packages of the latest release.

Do you think that linking to the single release page would be better?
e.g. https://downloads.joomla.org/cms/joomla3/3-9-3 
Otherwise it could go to: https://downloads.joomla.org/cms

**Comment by brianteeman** [comment]
**If** the intention is to use **only** the upgrade package then the link should go to a page with the update packages

**Comment by brianteeman** [comment]
linking directly to a single release specific url is obviously not a viable option

**Comment by hardik-codes** [comment]
I'm working on it and I wanted to know that is this issue for joomla 4.0

**Comment by brianteeman** [comment]
it is for every version of joomla and I dont believe it can be solved in joomla it can only be solved at the download server

**Comment by hardik-codes** [comment]
Ok got it

**Comment by mbabker** [comment]
I would suggest linking to the page for the release the user is running.  The URL structure isn't going to change, so this should be stable code for 3.0 or newer.  The only issue you'll have is for people running git the potential of false reports because the release page for the git versions (presently 3.9.4, 3.10.0, and 4.0.0) won't exist.

```php
use Joomla\CMS\Version;

// Manually build the short version to exclude the stability identifier (i.e. -beta, -rc, etc.); also use dashes for the separator to match the aliases used by the downloads site
$version = Version::MAJOR_VERSION . '-' . Version::MINOR_VERSION . '-' . Version::PATCH_VERSION;

$pageUrl = sprintf('https://downloads.joomla.org/cms/joomla%s/%s', Joomla\CMS\Version::MAJOR_VERSION, $version);
```

**Comment by brianteeman** [comment]
but then it wont be "upload and update" it will just be "upload and reinstall"

**Comment by mbabker** [comment]
Wires crossed then, thought you were referring to the reinstall thing for some reason (need more coffee).

It was an intentional design decision to only list the full install packages on the latest release page as the primary target user for that page is folks newly downloading Joomla.  It'd be a design decision to make to add the full package listing to that page if it were so desired.  Also keep in mind once 4.0 releases then the latest release page will show both 3.x and 4.x until 3.x EOL's, so we should be aware of potential information overload and user confusion.

**Comment by mbabker** [comment]
Considering the component is already going to have the version for the latest release, one potential is that same code snippet I pasted just change it to use the version string from the update server for the new release instead of using the Version class.

**Comment by brianteeman** [comment]
> Wires crossed then, thought you were referring to the reinstall thing for some reason (need more coffee).

I am - its the same thing its just we only call it "upload and install"
