### ISSUE TITLE
[4.0]unacessible calendar in articles/new/publish if width is less than 920 pixel

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24114]
### Steps to reproduce the issue
go to administrator=>content=>articles=>new=>publish tab
set width of tab less than 920 pixel
open the first calender

### Expected result
Full Accessible Calender

### Actual result
Partially accessible calender
![screenshot 7](https://user-images.githubusercontent.com/34083630/53966572-6a9a5d80-4119-11e9-8ba4-3c5f181cb595.png)

**Comment by ghost** [comment]
Please add "[4.0]" at start of Title.

**Comment by ghost** [comment]
@Puneet-Jain-18 Thanks.

**Comment by ghost** [comment]
a Issue for @coolcat-creations ?

**Comment by coolcat-creations** [comment]
The article page seems not to be touched yet at all - any coding volunteer to get with me through this?

**Comment by brianteeman** [comment]
Still not started?

**Comment by coolcat-creations** [comment]
https://github.com/joomla/joomla-cms/issues/21989

This issue is almost uncommented. The comments which have been made are solved in @drmenzelit  great PR... - everything else was still not commented. So I am saying again: If there is a coding volunteer to solve this public issue I am happy to cowork.

**Comment by brianteeman** [comment]
No one commented on #21989 because right after you posted it you made it clear that you had a private team working on it in private. No one wants to waste their time!!

How can we know what needs to be done? You have been developing in private and except for a few rumours no one knows what has been done, what needs to be done etc. You mention a PR from @drmenzelit but where is it?

You can't have it both ways. Working in private and yet expecting people to comment and contribute to things that might not even be current

**Comment by coolcat-creations** [comment]
> How can we know what needs to be done? You have been developing in private and except for a few rumours no one knows what has been done, what needs to be done etc. You mention a PR from @drmenzelit but where is it?

You tested it already and as far as I am concerned its already merged.

This is unrelated to the backend template team. Let's find a solution together here.

**Comment by Puneet-Jain-18** [comment]
There is one another thing i noticed,
if i manually resize the tab after its loaded, the tab are displayed like this
![screenshot 9](https://user-images.githubusercontent.com/34083630/54034695-941cbd00-41dd-11e9-8986-7df58b2980fc.png)

but in reloading the page on same size the responsiveness is lost,this might be a related issue

![screenshot 8](https://user-images.githubusercontent.com/34083630/54034724-a3036f80-41dd-11e9-9672-08646a6457af.png)

**Comment by bahl24** [comment]
> this public issue I am happy to cowork

@coolcat-creations What exactly needs to be done here? Maybe, I can help

**Comment by coolcat-creations** [comment]
@bahl24 please look into my screen at #21989 - best thing is to slice the issue down to small packages of to dos to solve the whole issue. Do you have time for a chat or skype or something?

**Comment by Quy** [comment]
Please test PR #24336<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24114">issues.joomla.org/tracker/joomla-cms/24114</a>.</sub>
