### ISSUE TITLE
[4.0] module positions list not cover all elements that is under it

### ISSUE THREAD

**Issue by hitaly** [joomla/joomla-cms#24127]
### Steps to reproduce the issue
create new or open a module , click on position list to select a position , you will see the calendars of Start Publishing and Finish Publishing .![screen shot 2019-03-08 at 12 56 35](https://issues.joomla.org/uploads/1/e27fef1afad8b74731b900713d2fcfec.jpg)

### System information (as much as possible)
 joomla 4 alpha 6

**Comment by ghost** [comment]
Same using latest nightly build https://developer.joomla.org/nightly-builds.html?

**Comment by Quy** [comment]
Fixed in the [nightly builds ](https://developer.joomla.org/nightly-builds.html).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24127">issues.joomla.org/tracker/joomla-cms/24127</a>.</sub>
