### ISSUE TITLE
[4.0]Preview not working for unpublished articles

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24132]
### Steps to reproduce the issue
go to administrator
Create new article=>save it =>click on preview

### Expected result
article is previewed

### Actual result
![screenshot 11](https://user-images.githubusercontent.com/34083630/54042321-d3eca000-41ef-11e9-82a4-4f73c936742d.png)

### Additional comments
previewing is working correctly for published articles

**Comment by ReLater** [comment]
In title you say "unpublished article", in additional comments "published article".
Could you please show other settings, too. Access level and so on.

**Comment by Puneet-Jain-18** [comment]
PS: I said it was working **correctly** for **published articles**

Here is screeshot for problematic unpublished  article
![screenshot 12](https://user-images.githubusercontent.com/34083630/54047210-7a3ea280-41fc-11e9-845f-939fe5dd5211.png)

**Comment by ggppdk** [comment]
So what is the Expected result if you are not logged ?
- to be redirected to login page ?

And then
if are already logged or you have logged after redirection with an account that cannot preview the content
- then a more helpful message should appear like ?

"You cannot preview this item, please login with a more privileged account"

**Comment by Puneet-Jain-18** [comment]
I think user would not be able to visit this page if he is not logged in with required privileges

**Comment by simbus82** [comment]
@ggppdk  Previewing article must work with or without frontend login, if an user is working in backend. And must work with an published or an unpublished article. There is not much to interpreting...
Otherwise it's not a preview ... That's how it works in the world of content creation.

> **Expected result**
> article is previewed

**Comment by ggppdk** [comment]
@simbus82 

i understand your argument about UX , **yes it would be very nice**

as long as it is not an ugly hack with security concerns,
that also cares to preview with the desired access level

i mean the preview button is a little misleading, which access level do you want to preview ?
public ?
registered ?
other ?

but ok, i understand that most common case of preview is "public" access level ...

- so you would want to preview unpublished content while only having access level public and while you are not logged, and while executing frontend plugins , etc, ok, if this can be done without being hack
- or you get auto-login as the current backend user but your access levels are reduced to public  ?
- or you get auto-login as the current backend user but your access levels do not change ? then there is the case that the backend user is not allowed "site login" but lets handle this case by just forcing a frontend login screen
- other case ? e.g. multiple preview buttons with a drop down , "preview as registered" , "preview as public" ?

**with above i mean**
- **first we need to decide what the preview "thing" will be** 
and then implement

we had this since 9 years ago, and last 7 years we force a login
**but i would love a core paradigm / implementation**
all of 3rd party developers will like and use it too

**Comment by ggppdk** [comment]
I forgot to say a suggestion
maybe auto create temporary "access" coupons that are added to the URL to limit viewing to a specific content with specific access level(s) and for specific short time ...

but the above will need some implementation effort

simplest solution is to auto login backend current user to frontend

**Comment by jwaisner** [comment]
@puneet0191 Please retry with latest J4 build since there has been a lot of work since this issue was reported and let us know the result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24132">issues.joomla.org/tracker/joomla-cms/24132</a>.</sub>

**Comment by brianteeman** [comment]
It still doesnt work

**Comment by adj9** [comment]
Confirmed with  have today's Nightly Builds.

![Schermata 2020-12-05 alle 13 02 43](https://user-images.githubusercontent.com/5918444/101241864-355ddd80-36fa-11eb-9a36-6b66813b7201.png)

**Comment by HLeithner** [comment]
@adj9 what's the url?

**Comment by adj9** [comment]
@HLeithner 
is in the backend. The preview of an article that is not published.

**Comment by alikon** [comment]
please test #35488

**Comment by alikon** [comment]
as #35488 won the prize of the most shit pr's let's reopen this

**Comment by stefanschulz** [comment]
Hi,
This is still not working in the latest release 4.2.6.
There is no point in having a preview, if the article can only be seen when already published.
For Joomla!3 there was a plugin by Regular Labs (Better Preview). Maybe it does provide some idea on how to solve this issue.
Cheers,
Stefan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24132">issues.joomla.org/tracker/joomla-cms/24132</a>.</sub>

**Comment by HLeithner** [comment]
for the moment you have to be logged in also in the frontend or have shared sessions activated.

**Comment by stefanschulz** [comment]
Yes. I activated shared sessions for that purpose, which I see as an acceptable workaround. Unfortunately, it sets the whole frontend in "preview" mode, so it is a bit difficult to see the real website (or requires to open a second (or anonymous) browser.

**Comment by HLeithner** [comment]
that's actually true, I suspect you also have frontend editing active? if you don'T use it you can disable it in the system configuration. then you only see additional content but the website should look the same.

**Comment by stefanschulz** [comment]
I don't need frontend editing. And I did not find any option to turn it off.

**Comment by stefanschulz** [comment]
This is already set to "Keine".

**Comment by HLeithner** [comment]
ok then maybe the template you are using does something special

**Comment by stefanschulz** [comment]
Thanks. I'll check for that.

**Comment by dautrich** [comment]
I ran into the same problem and opened issue #41130. Let me cite one of my comments from a user's point of view:

> Look at the use case: The user is in the backend and has sufficient rights to edit an article. He saves the article and now wants to see the result, because there might be some need for improvement. To be able to preview the article in the backend is a big enhancement over J3. So give him/her the preview regardless of other restrictions like missing user rights or not reached publishing date or expired publishing date! And without the need to login first to preview the article.

**Comment by brianteeman** [comment]
Enable shared sessions in global configuration. Problem solved

**Comment by kkbiswal** [comment]
I have trie with this option still I am getting 404 for an unpublished article on joomla 4.3 .
Is there any other solution present??<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24132">issues.joomla.org/tracker/joomla-cms/24132</a>.</sub>

**Comment by brianteeman** [comment]
The solution exists - enable shared login - this did not exist when the bug report was opened.
