### ISSUE TITLE
[4.0] API Webservices empty folder

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#24140]
### Steps to reproduce the issue
Install an extension without the api part and usage in the XML file

### Expected result
No empty folder is created under /api/components/com_xxx

### Actual result
Empty folder is created under /api/components/com_xxx

### Additional comments
It would be supposed that if an extension does not use the api webservices and has not a tag for that section in the XML manifest no empty folder is created under the /api path

Ping  @wilsonge the author of all this one here.

**Comment by ghost** [comment]
closed as no Content.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24140">issues.joomla.org/tracker/joomla-cms/24140</a>.</sub>

**Comment by joeforjoomla** [comment]
Reopen it @franz-wohlkoenig i was just posting the content

**Comment by wilsonge** [comment]
This is the same behaviour in the site application right? I mean I'm not going to dispute it's odd behaviour but this is how the installer works with existing site and admin components too. https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/Adapter/ComponentAdapter.php#L208-L271

**Comment by mbabker** [comment]
It has earlier been deemed a requirement that components all have an administrative client (in part because of code changes in 4.0 with conventions looking for things in that area).  In theory, it is possible to create an admin only component, and there would definitely be components without an API element.  So, having a cleanup routine to remove the frontend and API directories if unused would be a good idea to entertain.

**Comment by wilsonge** [comment]
I agree. My point is just we should treat the 'optional' directories the same (site and api)

**Comment by joeforjoomla** [comment]
I agree with of you @wilsonge and @mbabker , my idea was just related to the fact that historically Joomla had 2 applications, site and admin one. Now in J4 we introduced a third application.
However supposed that only a few and specialized components will have and will use this API application in the future, i think that it would be better to parse the XML manifest and create an api directory only if really needed by the extension. Obviously the same concept should be applied even to site and admin folders.

**Comment by jwaisner** [comment]
This discussion has ran its course. Closing as it has been many months since anything has been added.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24140">issues.joomla.org/tracker/joomla-cms/24140</a>.</sub>
