### ISSUE TITLE
off line gives as result 503 Service Unavailable

### ISSUE THREAD

**Issue by omd123** [joomla/joomla-cms#24183]
### Steps to reproduce the issue

Global Configuration -> site offline = yes
(joomla 3.9.4 + protostar template, in "configuration.php" is public $offline = '1';)

### Expected result

site off-line

### Actual result

503 Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

### System information (as much as possible)

Database Version: 5.5.5-10.0.38-MariaDB 
Database Collation: utf8_general_ci
Database Connection Collation: utf8mb4_general_ci
PHP Version: 7.2.15
Web Server: Apache/2
WebServer to PHP Interface: fpm-fcgi
Joomla! Version: Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT 

### Additional comments
Issue appers since update to 3.9.2

**Comment by ghost** [comment]
@Quy can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24183">issues.joomla.org/tracker/joomla-cms/24183</a>.</sub>

**Comment by HLeithner** [comment]
@omd123 do you have a error.log?

maybe activate the debug options from joomla.

**Comment by mbabker** [comment]
Joomla intentionally gives a 503 response when offline mode is enabled, as is standard behavior.  See [this code](https://github.com/joomla/joomla-cms/blob/17d84600223c89ab3a5528053f7dd7bd267b1d61/libraries/src/Application/SiteApplication.php#L757-L762).

If you're getting a server level 503 page instead of the Joomla offline template, check to be sure there isn't something happening at the server level to catch 4xx or 5xx responses and post-process them.

**Comment by ghost** [comment]
Closed as expected Behaviour. Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24183">issues.joomla.org/tracker/joomla-cms/24183</a>.</sub>
