### ISSUE TITLE
Manifest refresh fails if beez or hathor is removed

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#24194]
### Steps to reproduce the issue
uninstall beez & hathor
update from 3.9.3 to 3.9.4

### Expected result

no warnings.

### Actual result
Warning
Refresh Manifest Cache failed: beez3 Extension is not currently installed.
Refresh Manifest Cache failed: hathor Extension is not currently installed.

### System information (as much as possible)
[systeminfo-2019-03-15T02_09_56+00_00.txt](https://github.com/joomla/joomla-cms/files/2969161/systeminfo-2019-03-15T02_09_56%2B00_00.txt)

### Additional comments
This is not new to 3.9.4, I've seen it on several of the last updates.

**Comment by ReLater** [comment]
Because this fantastic pr https://github.com/joomla/joomla-cms/pull/17219 didn't find its way into core I think the only solution is not to uninstall extensions that are delivered with the Joomla core but to deactivate them.

You can reinstall these templates with the Extensions Discover functionality after copying the files from a full package if you want to get rid of these harmless warnings.

**Comment by N6REJ** [comment]
> Because this fantastic pr #17219 didn't find its way into core I think the only solution is not to uninstall extensions that are delivered with the Joomla core but to deactivate them.
> 
> You can reinstall these templates with the Extensions Discover functionality after copying the files from a full package if you want to get rid of these harmless warnings.

yeah, not worth the hassle, just wanted it to be brought up.
Thing is though, beez and hathor should NOT be core requirements

**Comment by ghost** [comment]
closed as having (not merged)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24194">issues.joomla.org/tracker/joomla-cms/24194</a>.</sub>
