### ISSUE TITLE
Warning JUser: :_load: Unable to load user with ID: 650

### ISSUE THREAD

**Issue by mohipan** [joomla/joomla-cms#24290]
Hello,
when I open blog page in front end I got message:

Warning
JUser: :_load: Unable to load user with ID: 650

What shoud I do to remove that?

Thank you in advance!

**Comment by brianteeman** [comment]
That is because there is a content item on that page that was created by an author with id:650 and thhat author is no longer on your site.

Go to the article manager in the admin and in the search filter type in
id:650

That will show you the article. Now go to the publishing tab and in the created by field select a valid user.

Any problems please ask on the forum https://forum.joomla.org

**Comment by mohipan** [comment]
can you show a screenshot of it? in order to make it easier for me to solve this problem. thank you :)

**Comment by brianteeman** [comment]
Any problems please ask on the forum https://forum.joomla.org

**Comment by mohipan** [comment]
oke thanks so much Mr. :)
