### ISSUE TITLE
[4.0] Consistent validation of the database name

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#24291]
com_config is looser at validating the database name than the installer (which was patched as part of https://github.com/joomla/joomla-cms/pull/23704). This should be normalised using a standard validation filter for JForm

**Comment by joomdonation** [comment]
From what I see, that kind of validation is nice to have but not needed anymore. The reason is because before the change is saved, we even try to connect to database to see if it works before saving the change.

With that said, I'm closing this issue for now. Please re-open it if you still want to have this validation rule implemented.

**Comment by wilsonge** [comment]
I do want it because it's more about the security of what we are validating before trying to connect than whether it works or not

**Comment by alikon** [comment]
plesase test #39889

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44623 . Thanks in advance.
