### ISSUE TITLE
PHP Warning (open_basedir) when using reCaptcha v2

### ISSUE THREAD

**Issue by solracsf** [joomla/joomla-cms#24402]
Here is the warning:

`Warning: is_file(): open_basedir restriction in effect. File(/home/webapps/nexthttps:/www.google.com/recaptcha/api.js?onload=JoomlaInitReCaptcha2&render=explicit&hl=fr-FR) is not within the allowed path(s): (/home/webapps/next:/var/lib/php/session:/tmp) in /home/next/libraries/src/Filesystem/File.php on line 640`

Don't know if this is core related or not...but testing a URL with `is_file()` seems a nonsense.

**Comment by ghost** [comment]
i guess its about J3 so calling @HLeithner to comment.

**Comment by HLeithner** [comment]
The host has a basedir set and it seams that we test a url if it exists with is_file, that seams wrong to me. I did't checked the codepath but I think checking external files for existence makr no sense.

**Comment by solracsf** [comment]
I didn't test with J4 if this behavior remains the same. It happens on J3.9.5.

**Comment by weg2g** [comment]
One of main reason behind open_basedir error comes from the restrictions that applies by Apache on files path and file opening. In early versions of PHP & Apache, you were able to set it on PHP.ini file alone; however, in latest version of Apache, you just need to set in Apache. In your Apache config file there is a section that have few options like allowing open_basedir, its base directory, etc. 

There are two more reasons:

1- If you using shared hosting, the site admin may have put restrictions on open_basedir

2- Sometimes this error is caused by .htaccess file on your server. Make sure there is no restriction applies there. It is usually located on the main root directory of your site. 

Good luck,

Matt
https://coding-bootcamps.com/
https://myhsts.org/
https://dcwebmakers.com/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24402">issues.joomla.org/tracker/joomla-cms/24402</a>.</sub>

**Comment by solracsf** [comment]
@weg2g please see https://github.com/joomla/joomla-cms/issues/24402#issuecomment-478352569

**Comment by jwaisner** [comment]
@acs-ferreira are you still seeing this issue?

**Comment by solracsf** [comment]
Can't say, not using it anymore, so closing for now.
