### ISSUE TITLE
[4.0] Help button and link at installation J4 Alpha7

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24418]
When I click this button at installation, this link is opened in same window. 

Can this link open in a new window?

```
<div class="j-header-help">
<a href="https://docs.joomla.org/Special:MyLanguage/J4.x:Installing_Joomla">
<span class="fa fa-lightbulb-o" aria-hidden="true"></span>
<span class="sr-only">Help installing Joomla</span>
</a>
</div>
```

```
<div class="j-header-help">
<a href="https://docs.joomla.org/Special:MyLanguage/J4.x:Installing_Joomla" **target="_new"**>
<span class="fa fa-lightbulb-o" aria-hidden="true"></span>
<span class="sr-only">Help installing Joomla</span>
</a>
</div>
```

`

**Comment by ghost** [comment]
As far as i know its about Accessibility to not open in a new Window.

**Comment by jeremysmartin399** [comment]
For what it is worth, W3C had this to say about [opening new tabs and windows from a link](https://www.w3.org/TR/WCAG20-TECHS/G200.html):
"The objective of this technique is to limit the use of links or buttons that open new windows or tabs within Web content. **In general, it is better not to open new windows and tabs since they can be disorienting for people, especially people who have difficulty perceiving visual content.** However there are some situations where it is preferable from an accessibility perspective to open a new window or tab. Here are two such situations:

**Opening a page containing context-sensitive information, such as help instructions,** or an alternate means of completing a form, such as a calendar-based date picker, will significantly disrupt a multi-step workflow, such as filling in and submitting a form, if the page is opened in the same window or tab.

The user is logged into a secured area of a site, and following a link to a page outside of the secured area would terminate the user's logon. In this case opening external links in an external window allows the user to access such references while keeping their login active in the original window.

**It is recommended that when links are opened to a new window, there is advance warning.**

I'm not sure if this "help" button would fall into the "help instructions" exception or if the general rule of not opening a separate window would be best.

Link to W3C article: https://www.w3.org/TR/WCAG20-TECHS/G200.html

**Comment by ghost** [comment]
> For what it is worth, W3C had this to say about [opening new tabs and windows from a link](https://www.w3.org/TR/WCAG20-TECHS/G200.html):
> "The objective of this technique is to limit the use of links or buttons that open new windows or tabs within Web content. **In general, it is better not to open new windows and tabs since they can be disorienting for people, especially people who have difficulty perceiving visual content.** However there are some situations where it is preferable from an accessibility perspective to open a new window or tab. Here are two such situations:
> 
> **Opening a page containing context-sensitive information, such as help instructions,** or an alternate means of completing a form, such as a calendar-based date picker, will significantly disrupt a multi-step workflow, such as filling in and submitting a form, if the page is opened in the same window or tab.
> 
> The user is logged into a secured area of a site, and following a link to a page outside of the secured area would terminate the user's logon. In this case opening external links in an external window allows the user to access such references while keeping their login active in the original window.
> 
> **It is recommended that when links are opened to a new window, there is advance warning.**
> 
> I'm not sure if this "help" button would fall into the "help instructions" exception or if the general rule of not opening a separate window would be best.
> 
> Link to W3C article: https://www.w3.org/TR/WCAG20-TECHS/G200.html

Ok, I read the link and understood the W3C specification. 
Can you close it?

**Comment by ghost** [comment]
I will close it.
