### ISSUE TITLE
AMP format please

### ISSUE THREAD

**Issue by ranggasito** [joomla/joomla-cms#24471]
### Is your feature request related to a problem? Please describe.
I'am trying to remove scriptOptions from JDocument but it's protected property so I can't remove or disable it. I need to build joomla in amp format, so it's not allowed in amp format to add scripts except from amp source.

### Describe the solution you'd like
I think Joomla should support html document type in AMP version 

### Additional context
![image](https://user-images.githubusercontent.com/8582431/55524638-371b0680-56b8-11e9-93e3-195007781d9b.png)

**Comment by mbabker** [comment]
Your template is in the scope of the Document class chain, so you can `$this->scriptOptions = [];` all you want and take the risk of breaking something along the way.  You're right there isn't a setter to just overwrite the property from outside, and making it public isn't the fix for that (it's wrong that there are so many public properties on the class in the first place but the time to fix that was in 2011, trying to fix it in 2019 is API suicide at this point).

**Comment by brianteeman** [comment]
This should be closed. There are extensions available that provide amp support and/or you can use the method described by @mbabker

**Comment by ghost** [comment]
Closed as stated above.
