### ISSUE TITLE
Install from web not connecting

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#24483]
### Steps to reproduce the issue

Navigate to Extensions >>> Manage ... Install from web (tab)

### Expected result
Extensions display

### Actual result
Message says
"Can't connect to the Joomla! server. Please try again later. "

### Additional comments
https://forum.joomla.org/viewtopic.php?f=715&t=971065

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
Please close here and report to https://github.com/joomla/joomla-websites

**Comment by Webdongle** [comment]
https://github.com/joomla/joomla-websites has a list of links none of which can I see 'Install from web'.  Please reopen or give an exact link. Thanks.

**Comment by brianteeman** [comment]
It is nothing to do with the code in joomla. I already gave you the correct link to report this.

**Comment by roland-d** [comment]
@Webdongle I believe it should be this one: https://github.com/joomla/jed-issues/issues/new

**Comment by Webdongle** [comment]
@roland-d 
Thanks.  Done https://github.com/joomla/jed-issues/issues/88

**Comment by mbabker** [comment]
@roland-d IFW isn't maintained by JED.  I posted the right repo links in that issue.

**Comment by mbabker** [comment]
While I'm here, for anyone experiencing any problems please open your browser's developer console and glance at either the JavaScript console for any warnings or errors related to the plugin's JavaScript or at the network requests going out to `https://appscdn.joomla.org`.  Peak into the responses from the install from web server and see what kind of error messages you might be getting (I'm pretty sure thanks to Joomla's error handling being a rigid HTML format if there is a server error the plugin's JavaScript isn't going to be able to parse the response since it only expects JSON, I probably should change the server to avoid this behavior).  The error message should more than likely correspond with one of the Exceptions thrown by a class in https://github.com/joomla/install-from-web-server/tree/master/components/com_apps/models so that helps a little bit in tracing where things may be going wrong on a server-to-server level.

Also, post to either https://github.com/joomla/install-from-web-server/issues or https://github.com/joomla-extensions/install-from-web-client/issues (I'm honestly not picky about which since the two are so closely related) or @ mention me if you're posting on this repo, I've turned off a vast majority of my GitHub notification emails.

**Comment by Webdongle** [comment]
I don't know if if it is a server issue or a plugin issue. It's been reported so it's up to you devs to sort iit out. very time I post an issue I get passive aggressive shite and the bloody run around.

**Comment by ghost** [comment]
please be relaxed, @Webdongle

**Comment by mbabker** [comment]
> It's been reported so it's up to you devs to sort iit out.

With that attitude, there's nothing I can do and I'm going to write this off as a non-confirmed issue.  From my end, everything is working correctly; verified on my local computer, a joomla.org server, a client website, and my personal website (all different servers and a variety of PHP 7.x backends on Joomla 3.9.4).

A forum post with a bunch of "me too" or a GitHub issue with "me too" does not help anything.  If I am going to debug an issue, I need information such as what I asked for in https://github.com/joomla/joomla-cms/issues/24483#issuecomment-479927952.  If nobody is going to help with that, then I'm not going to help identify and resolve an issue.  If that's "passive aggressive shite" then so be it, but I can't magically fix a problem I can't reproduce or am not even aware of because the problem gets posted someplace that I am not watching (and no, I didn't see this issue report come in, I did see the one on the JED repo because apparently I hadn't turned off my notifications there).

**Comment by mbabker** [comment]
Re-open until further details can be provided.  Will be closed in 48 hours if additional debugging information cannot be provided to identify the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24483">issues.joomla.org/tracker/joomla-cms/24483</a>.</sub>

**Comment by felixkat** [comment]
Changing `dataType: 'json',`  to `dataType: 'jsonp',` fixed the issue for me.

\media\js\client.js  -   Line  57<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24483">issues.joomla.org/tracker/joomla-cms/24483</a>.</sub>

**Comment by fontanil** [comment]
Tried to make this changes (in media/plg_installer_webinstaller/js/client.js line 57) but don't work for me.
Needed to do the same change in client.min.js too (dataType:"json" to dataType:"jsonp") and it works now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24483">issues.joomla.org/tracker/joomla-cms/24483</a>.</sub>

**Comment by felixkat** [comment]
> Tried to make this changes (in media/plg_installer_webinstaller/js/client.js line 57) but don't work for me.
> Needed to do the same change in client.min.js too (dataType:"json" to dataType:"jsonp") and it works now.

Sorry, I should have mentioned that.

**Comment by ggppdk** [comment]
Yes changing to jsonp works,

I have updated to the new updated plugin
and then tested 

(the following is already mentioned in the forum thread)
It works with chrome and edge
It fails with Firefox and internet explorer 

WIth Firefox 66 i get

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://appscdn.joomla.org/webapps/index.php?format=json&option=com_apps&view=dashboard&product=Sm9vbWxhIQ==&release=My45&dev_level=NA==&list=grid&pv=Mi4wLjA=. (Reason: missing token ‘x-csrf-token’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).[Learn More]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://appscdn.joomla.org/webapps/index.php?format=json&option=com_apps&view=dashboard&product=Sm9vbWxhIQ==&release=My45&dev_level=NA==&list=grid&pv=Mi4wLjA=. (Reason: CORS request did not succeed).[Learn More]

**Comment by ReLater** [comment]
Older J3.9.5 nightly.

Since I've updated "Installer - Install from Web" from version 1.1.1 (worked without issues) to newest version 2.0.0 I can confirm the issue with Firefox 66.0.2 (64-Bit) 

but not with Vivaldi 2.4.1488.35 (Stable channel) (32-Bit) and not with Chrome Version 73.0.3683.103 (Offizieller Build) (64-Bit).

The messages in FF console
`
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://appscdn.joomla.org/webapps/index.php?format=json&option=com_apps&view=dashboard&product=Sm9vbWxhIQ==&release=My45&dev_level=NS1kZXY=&list=grid&pv=Mi4wLjA=. (Reason: missing token 'x-csrf-token' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).[Learn More]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://appscdn.joomla.org/webapps/index.php?format=json&option=com_apps&view=dashboard&product=Sm9vbWxhIQ==&release=My45&dev_level=NS1kZXY=&list=grid&pv=Mi4wLjA=. (Reason: CORS request did not succeed).[Learn More]
`
https://developer.mozilla.org/de/docs/Web/HTTP/CORS/Errors/CORSMissingAllowHeaderFromPreflight?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

https://developer.mozilla.org/de/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

**Comment by mbabker** [comment]
Apparently something changed between when I pushed joomla-extensions/install-from-web-client@85f87e94ed752eeae53ed241b793daa52095a913 and now because I was trying to break away from needing jsonp support but apparently that's not happening.  Update coming shortly.

**Comment by mbabker** [comment]
https://downloads.joomla.org/extensions/install-from-web/2-0-1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24483">issues.joomla.org/tracker/joomla-cms/24483</a>.</sub>
