### ISSUE TITLE
[4.0] SysInfo system manager icon

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24502]
Placeholder for @wilsonge

**Comment by brianteeman** [comment]
I think this is resolved at https://github.com/joomla/backend-template/pull/138

**Comment by ghost** [comment]
should it be closed or waiting till new backend is merged here?

**Comment by Quy** [comment]
Let's close it since wilsonge mentioned that the backend template will be merged shortly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24502">issues.joomla.org/tracker/joomla-cms/24502</a>.</sub>

**Comment by brianteeman** [comment]
It should stay open until it is merged and confirmed that the issue is solved

**Comment by Quy** [comment]
OK to close now that there is a backend template PR? I can confirm that it is fixed.
