### ISSUE TITLE
[4.0] [RFC] simplify / reduce / remove Workflow impact on queries

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#24536]
### Steps to reproduce the issue
Please read comments

by @csthomas 
https://github.com/joomla/joomla-cms/pull/21702#issuecomment-420209156

by me
https://github.com/joomla/joomla-cms/pull/21702#issuecomment-420423143

### Expected result
Simple queries for viewing

### Actual result
More complex queries for viewing

### System information (as much as possible)
Current J4 status

**Comment by brianteeman** [comment]
can you please post the issue here - not just link to other ones.

**Comment by mbabker** [comment]
Can someone on the bug squad please explain why there are now two RFC labels, and why the existing one wasn't just renamed if you wanted to change from the acronym to the fully spelled out name, and why nothing was posted on the issue tracker repo about this maintenance since there are code level integrations in the tracker regarding this label?  This seems like someone created more work for themselves for the sake of creating more work.

**Comment by ghost** [comment]
i tried to use a short one using a Description if you hover but if i delete the long-named label it is automatic assigend again, i guess by using "[RFC]" in title. I can't tell you why this not works so i gave up and live with this circumstances.

**Comment by mbabker** [comment]
[This method](https://github.com/joomla/jissues/blob/325aff2519a8462ce7413b9621aefc5dfe8e4d4f/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php#L114) in the issue tracker checks the title for "[RFC]" on issues, and [this method](https://github.com/joomla/jissues/blob/325aff2519a8462ce7413b9621aefc5dfe8e4d4f/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php#L473) does the same for pull requests.  The TL;DR is if you change something that has an issue tracker integration, it needs to be changed in the issue tracker as well otherwise it creates problems.

**Comment by ghost** [comment]
Solution is to delete the "RFC"-Label and rename the "Request for Comment" to "RFC"?

**Comment by mbabker** [comment]
If you all want the label to be "RFC" then yes, delete the current "RFC" label, rename the "Request for Comment" label to "RFC", and submit a pull request to the issue tracker changing those files to use the new label name.  Same goes with any other label managed in those two files.

**Comment by ghost** [comment]
thanks @mbabker. @Quy can you create a PR as we talked today about that RFC-Issue?

**Comment by Quy** [comment]
It was mentioned in BS last meeting that there are 2 RFCs. I don't know when the 2nd one got added. If we use `Request for Comment` label, then we don't need to update issue tracker, but it is not up to me to decide.

**Comment by ghost** [comment]
I added the second one "RFC" as its shorter and similar to "RTC" - both have a hover Description. So i like the Solution @mbabker wrote but this needs a PR.

**Comment by Quy** [comment]
PR created https://github.com/joomla/jissues/pull/1060

**Comment by wilsonge** [comment]
All the joins got removed in the Workflow revamp
