### ISSUE TITLE
[4.0] Don't store a null date but instead store the value null

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#24535]
Use the change here https://github.com/joomla/joomla-cms/pull/21901 as a baseline for the other core components.

**Comment by Quy** [comment]
Duplicate #16788?

**Comment by richard67** [comment]
Yes, I think #16788 can be closed because covered by this here.

The issue is not only with null values, it is in general with datetime columns, also those which shall not be nullable. There are several pull requests made for this and a few more to be done. As soon as all work has finished this issue can be closed.

**Comment by Quy** [comment]
OK to close?

**Comment by richard67** [comment]
@Quy Oh, yes, please close. Is all done with the null dates.
