### ISSUE TITLE
[4.0] Interfaces Incomplete

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#24587]
There are a lot of cases where interfaces come across as very incomplete.  With a static analysis tool, there would be loads of errors related to calling methods that do not exist on the documented return type.  When interfaces are in use, it is a best practice to only rely on methods that actually exist as part of the interface as anything else typically points to a dependency on a class implementing that interface.

Examples of current uses in core include:

- ~`Factory::getApplication()->getMenu()` - The `getMenu()` method is not defined in `CMSApplicationInterface`~
- ~`Factory::getApplication()->get()` - The `get()` method is not defined in `CMSApplicationInterface`~
- ~`Factory::getApplication()->triggerEvent()` - The `triggerEvent()` method is not defined in `CMSApplicationInterface`~
- `Factory::getApplication()->bootComponent()->getMVCFactory()` - The `getMVCFactory()` method is not defined in `ComponentInterface`
- CategoryServiceInterface containing a method related to counting tagged items

Valid fixes include changing doc blocks to accurate return types (i.e. classes instead of interfaces), ensuring methods are defined on interfaces as appropriate, adding inline docblocks indicating the return type for that use case, or adding `method_exists()` checks throughout the codebase because "unsafe" use of the interfaces are in use ("unsafe" in this context meaning calling methods not declared on a documented return type, generally an interface).

EDITED: STRIKETHROUGH'S BY @wilsonge AS WE MERGE FIXES

**Comment by wilsonge** [comment]
> Factory::getApplication()->get() - The get() method is not defined in CMSApplicationInterface

We should still probably reintroduce the interfaces we revoked here https://github.com/joomla-framework/application/commit/49d2f199a5576840ee0374664468f5dc40917fab for the `get` method and extend our interface from this

> Factory::getApplication()->triggerEvent() - The triggerEvent() method is not defined in CMSApplicationInterface

This one gets weird. We *probably* want to define a EventInterface . But we also probably want to make some of the applications own exceptions run through the `AbstractApplication`'s dispatch event rather than the `triggerEvent` method

> Factory::getApplication()->bootComponent()->getMVCFactory() - The getMVCFactory() method is not defined in ComponentInterface

We should check the component interface also implements the https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/MVC/Factory/MVCFactoryServiceInterface.php `MVCFactoryServiceInterface` interface where required

> Factory::getApplication()->getMenu() - The getMenu() method is not defined in CMSApplicationInterface

We should add this in - but we'll need to add add an exception it can throw for applications that don't have menus (cli and webservices). I guess we need the same exception/method for `getRouter` too

**Comment by richard67** [comment]
API has to be complete with beta, so changed label from release blocker to beta blocker.

**Comment by richard67** [comment]
@wilsonge Who do you think could be assigned to this? Is above my knowledge of the API.

**Comment by jwaisner** [comment]
Increasing priority as per guidelines for beta-blockers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24587">issues.joomla.org/tracker/joomla-cms/24587</a>.</sub>

**Comment by wilsonge** [comment]
Merging #24486 into here. We need to move `countTagItems` out of the `CategoryServiceInterface` it obviously makes no sense there.

**Comment by wilsonge** [comment]
As far as I can see this is now complete. @mbabker do you have any other places you can find? If not I'm going to mark this as closed

**Comment by jwaisner** [comment]
@mbabker following up on if this has been taken care of and if we can close.

**Comment by jwaisner** [comment]
@mbabker following up on this. Has this been resolved?

**Comment by richard67** [comment]
@wilsonge There hasn't been any reply by @mbabker , so I would assume there are no more open items. Can this be closed?
