### ISSUE TITLE
Can't specify the anchor text for "URL" custom fields.

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#24739]
### Steps to reproduce the issue

1. Create a new field, choose URL type.
2. Create a new article that uses the URL field.
3. Specify the URL address.
4. Open the article in frontend.

### Expected result
You can specify the URL.
You have the opportunity (optional) to specify the Anchor text.

### Actual result
The raw URL is shown as field content.
The "a" tag has as anchor text the URL. 

### System information (as much as possible)
Joomla 3.9.5

**Comment by ghost** [comment]
Looks like expected Behaviour: https://docs.joomla.org/J3.x:Adding_custom_fields/Url_Field

**Comment by rytechsites** [comment]
I created a custom override for URLs, so we could have more control of them...

1. if a 'description' is included in the custom field, that would 'become' the text used with the url
2. if an email is used, the 'mailto' would automatically get stripped.

Not a perfect solution, but it works...

[plg_fields_url.zip](https://github.com/joomla/joomla-cms/files/3129084/plg_fields_url.zip)

**Comment by ghost** [comment]
@HLeithner should @rytechsites make a Pull Request you would merge?

**Comment by HLeithner** [comment]
Could make sense for j4,

**Comment by rytechsites** [comment]
I don't know if my solution is really the 'best' way to go.  it is a great work around for us...but if we were to wait, I would think a better way to go is to include a 2nd field when defining a url, and that field 'can' be used as the 'text' that is displayed instead of the link.

My option of using the 'description' is just 'ok', not ideal, because then you will have multiple 'text links', that are on the same going down the page, even if the urls are different.

For example if you create a field called: 'Faculty Member website', the 'link' will say 'faculty member website' with a link to the url, which is great, but again not 'ideal'... when it could say for example 'John's Faculty Website'...

The 'stripping' of the mailto is probably more important, as I don't know any cases where anyone would want the 'mailto' displayed...

--- Laura

**Comment by jeckodevelopment** [comment]
@rytechsites please check PR #24776 as it implements your suggestion

**Comment by ghost** [comment]
Closed as having Pull Request #24776

**Comment by infograf768** [comment]
IMHO, if we need a different anchor text, we should use a new parameter and make sure it goes through JText.
In any case, this would be a new feature, and therefore for J4

**Comment by jeckodevelopment** [comment]
i agree with your approach @infograf768 
will try to work on that, any help is welcome ;)

**Comment by rytechsites** [comment]
I agree as well... my solution was just as a work around.  This can be donr
better, so languages can be considered...

Laura
