### ISSUE TITLE
[4.0] todo: remove remaining references to jhtmlsidebar

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24859]
As the title says - there is still a lot of code referring to the sidebar in the views that we are not using

**Comment by SharkyKZ** [comment]
Should note that removing these prevents plugins from modifying the sidebar.

**Comment by brianteeman** [comment]
obviously without a sidebar there is nothing for the plugin to modify ;)

**Comment by SharkyKZ** [comment]
After this there won't be. But currently plugins can add entries even if the sidebar is otherwise empty. Isn't that why there is `!empty($this->sidebar)` check in the first place?

**Comment by mbabker** [comment]
Even if plugins can conceptually manipulate these sidebars (hint, you don't really have an event in most admin components between the time they seed the sidebars and the time they are rendered), the fact is the sidebar rendering has been FUBAR since the introduction of customizable admin menus because the sidebar is not in-sync with those menus or user customizable in any way.  Just get rid of the sidebars already and if it is reintroduced it should be done correctly (seeded based on menu settings, proper event for customization, etc. etc.).

**Comment by SharkyKZ** [comment]
OK, just wanted to make sure. I guess it should be removed from `Joomla\CMS\MVC\View\ListView` too?

**Comment by brianteeman** [comment]
There are still some components not yet converted

**Comment by brianteeman** [comment]
closed as there are pr for the outstanding uses in contacts and finder
