### ISSUE TITLE
Install from Web not conncting - new report

### ISSUE THREAD

**Issue by EX34Mush** [joomla/joomla-cms#24914]

**Comment by brianteeman** [comment]
The extensions directory is currently unavailable

**Comment by Quy** [comment]
From Joomla's Twitter:
> Due to an unplanned but urgent maintenance the Joomla Extensions Directory (JED) might be unavailable for a while. We apologize for any inconvenience and will do our best to minimise the disruption caused.

**Comment by alikon** [comment]
then i will suppose that this issue is not strictly related to the cms
p.s.
feel free to correct me if  i'm wrongly closing it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24914">issues.joomla.org/tracker/joomla-cms/24914</a>.</sub>

**Comment by mbabker** [comment]
For the record with a public blog post I've updated the IFW server to have an offline message until things are back to normal.

**Comment by EX34Mush** [comment]
Thanks for letting us know.  It coincided with a totally separate install problem I was having and to begin with I thought it might be related.

Not sure what you mean by ‘offline message’ in this context.  I’m still getting the ‘Can’t connect’ message rather than something to say the Install from Web service is currently down for maintenance.

**Comment by EX34Mush** [comment]
Message has just appeared, thank you!
