### ISSUE TITLE
[4.0] alpha-10-dev  - Class 'JEventDispatcher' not found

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#24953]
After updateing my J4-alpha-9-dev to -10-def I get the following error: "An error has occurred.
0 Class 'JEventDispatcher' not found"

### Steps to reproduce the issue

1. Open system>manage>plugins (or any of the moduls)
2. Select any of the listed plugins an go into it.
3. Do a "save" || "save2exit" || "close"
4  The error-message  occurred.

### Expected result

Return without error-message to the plugins-listview.

### Actual result

5  Error: Class 'JEventDispatcher' not found

### System information (as much as possible)

J4-alpha-10-dev-full: Completely new installed and nothing ever changed.
J4-alpha-10-dev-update from alpha-9: The same error happens.

### Additional comments

When doing a page-reload the listview is shown.

**Comment by roland-d** [comment]
Hello, thank you for your report. This has been fixed with this commit:
https://github.com/joomla/joomla-cms/commit/615242353f9d9e7e008120979115dd00784f9f0d

You can either apply the fix manually or download the nightly build tomorrow from https://developer.joomla.org/nightly-builds.html

Since this has been only merged 7 hours ago, it is not in the nightly build from last night.

**Comment by hgh-esn** [comment]
OK, thanks,

I'll wait until tomorrow, doing an update.
