### ISSUE TITLE
No same alias possible in different language (url building)

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#24981]
### Steps to reproduce the issue
In old installation it was possible have 

menu (FR)
- Features (alias: features) * language french

menu (EN)
- Features (alias:features) * language english

I can prove it was possible, because I have Menuitems with same aliases from different languages. Now big problem because it is not possible anymore and my boss dont want to have features-fr and features-en as url.

I told it's not possible anymore but its still possible for old. Big problem.

### Expected result
Different language have different domain so no problem to have same alias.

### Actual result
Not possible

### System information (as much as possible)
Joomla core and using Plugin to have separate domain each language.

**Comment by ghost** [comment]
Can you give "System information (as much as possible)" like which Joomla-Version you talk about?

**Comment by brianteeman** [comment]
>  using Plugin to have separate domain each language.

I suspect this plugin is the problem and nothing to do with core

**Comment by ghost** [comment]
> I suspect this plugin is the problem and nothing to do with core

guess J3 is meant by @B3nito

**Comment by infograf768** [comment]
I can't reproduce the issue here with core.
<img width="1277" alt="Screen Shot 2019-05-22 at 16 38 38" src="https://user-images.githubusercontent.com/869724/58183817-42e67a80-7cb0-11e9-895f-7b29350ebb33.png">

URLs obtained are:
`mysite.com/en/login-form` for en-GB
and
`mysite.com/login-form` for fr-FR (as fr-FR is default language and `Remove URL Language Code` is set in the languagefilter plugin.)

I think we can safely close this and OP should ask for help in the forum and/or specifically to the developers of the special plugin used.

**Comment by ghost** [comment]
@B3nito please ask on [Forum](https://forum.joomla.org/)

Closed as stated above.

**Comment by B3nito** [comment]
Sorry, ok thank you! I am using plugin for multilanguage domain. Can something like this be part of core and supported. Multidomain is important thing.
https://github.com/YireoJoomla/plg_system_languagedomains

**Comment by infograf768** [comment]
This plugin is not maintained anymore (for 2 years). Look at Jed where there is another one which does not replace the language filter plugin and other core code.
