### ISSUE TITLE
Bug when you hide Author in Blog Article Category but want to show Author when you open single article

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25005]
### Steps to reproduce the issue

Set not show author in category blog layount

### Expected result

Then you hide Author in Blog Article Category you Expected to show Author then you open artile in that category

### Actual result

Author hidden on blog category and also hidden then you open the article

### System information (as much as possible)

J 3.9.6 
protostar
modern sef 
php 7.2.18

**Comment by ghost** [comment]
don't understand the issue, can you please give more details (maybe using screenshots)?

**Comment by infograf768** [comment]
Tested this.

Menu item category blog "Show Author" set to "Hide"
One of the article (belonging to the category displayed by that menu item) "Show Author" set to "Show".
All works fine. The Author displays when loading the article.

But I confirm the issue if the article "Show Author" is set to "Use Global (Show)".
In that case the Author is not displayed.

This is indeed a bug imho.

**Comment by infograf768** [comment]
Looks like the problem comes from the fact that the `Show _author` parameter `=""` when Using Global. This is the same as "0" for the`$displayData['params']->get('show_author')`, because the global setting is not taken care of in the $displayData when the article param is empty.

This is not only touching the author, but all the settings using "Use Global (Show)"

**Comment by infograf768** [comment]
Further look shows that the params of the blog menu item override the `show global` article settings when there is no specific menu item for the article as technically the active menu item is still the blog menu item.

**Comment by infograf768** [comment]
so, not sure anymore if this should be considered as a bug...

**Comment by richard67** [comment]
Am also not sure if a bug or expected behavior when reading all the above.
@infograf768 Do you know who could know?

**Comment by Milglius** [comment]
How to attach screenshots in github @franz-wohlkoenig ?

**Comment by Milglius** [comment]
![jj3c](https://user-images.githubusercontent.com/43875462/58369933-d36bc780-7f09-11e9-821c-6327e3ee7c5c.gif)

Hope this helps

Then you hide Author in Blog Article Category you Expected to show Author then you open artile in that category, but then you open orticle it should show Author

**Comment by ghost** [comment]
![Screen Shot 2019-05-25 at 15 28 44](https://user-images.githubusercontent.com/8235763/58369962-0f9b2a00-7f02-11e9-915e-92ea762072e8.png)

**Comment by SharkyKZ** [comment]
Not a bug. Articles inherit parameters of category menu item.

**Comment by ghost** [comment]
@SharkyKZ  this is real and annoying joomla bug because I want Articles not inherit parameters (show Author) of category menu item.

**Comment by infograf768** [comment]
@SharkyKZ 
It does inherit indeed, but only when its parameters Use Global. Therefore I do understand the questionning.
@Milglius 
As I wrote, setting the article parameter to Show and not Use Global will solve your issue.

**Comment by ghost** [comment]
@infograf768 site has about 2000 articles, setting the article parameter manualy to each article to Show will take a lot of time

**Comment by Bakual** [comment]
@Milglius Set it to "Use Global" (or "Show") in the menu items and use a layout override in that view where you don't display the author name. That's probably the simplest solution.

The inheritance of the parameters isn't a bug and expected behavior. The "Use Global" entry just shows the "wrong" value as it doesn't take into consideration parameters from menu items (eg category views) and other parent elements. It just looks up the component and site settings.
This could be improved of course, but it may get very complicated to look up since you will have to check multiple places and trees.

**Comment by alikon** [comment]
expected behavior<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25005">issues.joomla.org/tracker/joomla-cms/25005</a>.</sub>
