### ISSUE TITLE
Documentation: remove mcrypt PHP extension from requirements

### ISSUE THREAD

**Issue by matjon** [joomla/joomla-cms#25025]
Hello,
On https://downloads.joomla.org/technical-requirements "Mcrypt Support" is listed as one of required PHP extensions. Joomla, however, does not require Mcrypt any more. Checking for Mcrypt was removed via pull request #18334. This extension itself was removed from PHP 7.2 and moved to PECL, so it is not present on many hosting providers.

Greetings,
Mateusz Jończyk

**Comment by matjon** [comment]
This was already requested but overlooked in https://github.com/joomla/joomla-cms/issues/18384#issuecomment-338425288 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25025">issues.joomla.org/tracker/joomla-cms/25025</a>.</sub>

**Comment by HLeithner** [comment]
@Sandra97 can you look at this? 

mcrypt check has been removed in 3.8.2

**Comment by Sandra97** [comment]
PR submitted [#207]( https://github.com/joomla/downloads.joomla.org/pull/207)

**Comment by ghost** [comment]
closed as stated above.

**Comment by natiki** [comment]
Hi,

Looks like mcrypt support is still listed on the website? (see screenshot). PR was only for the INI file. Also I cannot see definitively which version of J! no longer requires mcrypt support? And if we are going to be removing it from the website we need to indicate this J! version as well, because otherwise upgrading PHP becomes hit and miss.

![image](https://user-images.githubusercontent.com/4738140/58758388-2ecb3480-855e-11e9-9167-88b335ce4923.png)

**Comment by mbabker** [comment]
As the note says at the top of the page, the requirements reflect the current version of the branch.  Otherwise, the page would get un-ruly rather quickly by noting what version of Joomla added support for a PHP version or what version of Joomla introduced a requirement for a PHP extension or what version of Joomla removed a requirement for a PHP extension.

The page updates will be rolled out in a timely manner.  As it involves a change in a language file, the language file will be pushed to the translation system to get updates from translators then the updates rolled out in bulk so the requirements page has as minimal differences between languages as possible.
