### ISSUE TITLE
[4.0]  Backend: Admin-Login via tablet or smartphone unimpossible

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#25132]
### Steps to reproduce the issue

Use an smartphone/tablet (android) and try to login to the admin-backend under `https:://myDomain/administrator`. 

### Expected result

After setting up all necessary login-data (user,password) the backend should be displayed. 

### Actual result

At the moment, the login fails with a message: "Security token didn't match. ...." and a note:  "Fieldvalue can not be empty" for the userfield.
![20190606_102945517a](https://user-images.githubusercontent.com/5299726/59019950-48fc5f80-8849-11e9-9eff-e94517ff559e.jpg)

### System information (as much as possible)

J4 alpha 9/10  and android smartphone
The same is on an android tablet.

### Additional comments

All login-data works perfect on my laptop/pc-workstation.
I cleared all caches but nothing changes the login-behavior.

**Comment by richard67** [comment]
@hgh-esn Does the same happen with current nightly build?

**Comment by richard67** [comment]
Today no time, but tomorrow I'll try to reproduce that.

We need some testers with Android mobile devices for trying to reproduce it.

@hgh-esn Could you post here Andriod version and Browser name (I assume Chrome) and version? And maybe switch on debug and error reporting in global config when logged in from desktop, and then try again?

**Comment by brianteeman** [comment]
I can not replicate this with android 9 on chrome

**Comment by hgh-esn** [comment]
I my tests, I use  in all cases the browser  Chrome: 74.0.3729.157 and

1. Smartphone (Android: 7.0 Kernel: 3.18.35+) 
2. LENOVO Tablet YT3-850F (Android: 6.0.1 Kernel: 3.10.49,)

Also I have installed the latest nightly build of Joomla 4.
Also I activated the debug mode.
For going to login to the frontend I have activated the User: **demo-HGH** with Passw: **demo**
There you can try to login and see what happens there.

This morning the following happens:
When I selected the "desktop website" switch in chrome, I could login to the J4-backend "Control Panel".
But when selecting a menu (system, ...) entry, I was immediately logged out and thrown back to the login panel. 

When I switch back to non "desktop website" in Chrome, I could again login, but when selecting the system-menu I'm again thrown back to the login panel.

And then in both cases no further login was possible with the screen displayed on top, until I togged the 
"desktop website" in Chrome again.

@brianteeman 
Have you tried to select a menu item such as "system"?

**Comment by richard67** [comment]
I can't reproduce this issue (token not matching problem) with Android 6.0.1 on a Samsung Galaxy S5 mini.

I have other issues with current J4 nightly build, for which I am currently investigating if already known or new, that when you click the user icon at the right hand side of the tool bar at the top, no pulldown is shown, so I can't log out. This seems to be a CSS issue on anym small display, can be replicated with display size simulations for small mobile phone displays in Firefox on desktop, too. But that's not related to this issue here, just wanted to mention it if someone else finds that, too.

**Comment by ghost** [comment]
@richard67 can you please create a new Issue for the one you found? Cause if this Issue is closed your one too.

**Comment by richard67** [comment]
@franz-wohlkoenig As I wrote, am researching if there is already such issue. If not, the  I create one of course. But to me it looks as if the Atum backend template is not really ready for mobile phones because there are many issues, the one above was just the most annoying. And as far as I know there is still a project running for a new backend template, so I don't know if I shall make issues or not because new template project. Do you know anything about it?

**Comment by ghost** [comment]
New Backend Template should be merged as @wilsonge wrote a few Days ago so if the issue is an Template-one i would wait.

**Comment by richard67** [comment]
@franz-wohlkoenig Yes, is all template CSS issues related to small screen sizes.

**Comment by richard67** [comment]
Regarding this issue here: I have no idea what it could be. If it was the same with all end devices, mobile or desktop, then I would have ideas, like e.g. checking php session temp dir variable, but here the only idea I have is that on mobile device there is a wrong password in the cache or wrong password entered accidently because of other keybouard langauage than expected, but I am sure the author of this issue has checked that the password is correct uwint the eye icon before reporting this issue.

Neither Brian nor me could reproduce it. No idea what to do with it.

**Comment by ghost** [comment]
closed as unable to reproduce. It can always reopened if other can reproduce the issue. Thanks for reporting @hgh-esn.
