### ISSUE TITLE
[4.0] Build scripts TODO

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25163]
The build scripts can be massively simplified as we no longer need to convert all the JS from ES6 to ES5 as the production department have decided to adopt a browser support policy of PROD2019/005 - Change minimum version requirements for all browsers to n-2 and drop support for Internet Explorer. https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019

**Comment by C-Lodder** [comment]
You may need to keep babel for the custom elements, depending on your support for Edge, as they're rolling out a major update based on Chromium soon

**Comment by dgrammatiko** [comment]
I’m against the idea of dropping completely the es5static files. The reason is pretty simple: even if core doesn’t support ie11 (or also android uc) there might be people that want to provide such solutions to their clients. Removing the (I’ll also say) deprecated code won’t save you much at this point rather you’ll be shouting your own feet...
Just because most of the lucky ones don’t have to deal with corporate clients doesn’t mean there are t some unlucky one that have to, and not providing the needed parts to fulfill that means that your showing them the way out...

Ps I was the one barking about jquery, es6 and many other things but I never put proposed to do things in one and only direction (eg core doesn’t use jquery, mostly, but people that they don’t know any better can still use that Dino). I hope people see the difference here

**Comment by wilsonge** [comment]
I agree with @dgrammatiko on this one. We've said people can build templates for IE11 in our blog post and the aim is that. So we'll provide the ES5 files - however we just won't be using them (or providing polyfills for things like CSS Grid/CSS variables)
