### ISSUE TITLE
Update package path incorrect for 3.9.7 update

### ISSUE THREAD

**Issue by neildarlow** [joomla/joomla-cms#25178]
### Steps to reproduce the issue
1) Installation emails that a Joomla update is available
2) Login as Site Admin and follow Joomla update action from System Control Panel
3) The proposed update package URI path still points to the 3.9.6 version
4) Actioning the update will reinstall version 3.9.6

### Expected result
The update URI path should reference the 3.9.7 update package.

### Actual result
The version 3.9.6 update package will be downloaded and installed.

**Comment by richard67** [comment]
This is by purpose. There was an error in the 3.9.7 update detected which broke French sites and which was fixed meanwile, see PR #25177 . A new release 3.9.8 will be made soon. The update package path was reverted to 3.9.6 so no more French sites will get the bad update, see [https://github.com/joomla/update.joomla.org/commit/6a93929a88025a6e04c1d6bc129076f3845ecf0f](https://github.com/joomla/update.joomla.org/commit/6a93929a88025a6e04c1d6bc129076f3845ecf0f). That's why you see now 3.9.6 and not 3.9.7.

**Comment by richard67** [comment]
@HLeithner Can you confirm my comment above?

**Comment by HLeithner** [comment]
Yes and update server as now 3.9.8

**Comment by zero-24** [comment]
As we are now shipping 3.9.8 this is patched by https://github.com/joomla/update.joomla.org/pull/131 so I'm closing here.
