### ISSUE TITLE
Media Manager: Create subdirectory and Upload Files only into media-root-directory

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#25192]
### Steps to reproduce the issue
Try to create subdirectories and upload files (pictures) into (sub)directories multiple times.

### Expected result
Subdirectory "my_subdirectory" is placed into directory "my_directory".
Uploaded picture is placed into directory /my_directory/my_subdirectory.

### Actual result
Most of the times subdirectories and pictures are placed into media-root (/images).

### System information (as much as possible)
Joomla 3.9.8

### Additional comments
I think this bug came with Joomla 3.9.8, but I am not sure for 100%.
Sometimes the media-manager works correctly. Most of the time it doesn´t.

**Comment by Quy** [comment]
Please test PR ##25184

**Comment by ghost** [comment]
Closed as having Pull Request #25184

**Comment by bayareajenn** [comment]
This was happening before 3.9.8. I think perhaps it was after 3.9.6 that the issue began.

What happens is the first time you go to Content -> Media and navigate to a directory within /images (say /images/blog) and upload an image it will work and put it in the correct place. If you go to another place and upload an image, it saves to the root of /images.

If you leave Content -> Media and go to Articles or something and then go back to Media, it will work once. Then it saves to the root again.

Should I have put this in the PR? I'll go over there next and figure out how to test it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25192">issues.joomla.org/tracker/joomla-cms/25192</a>.</sub>

**Comment by bayareajenn** [comment]
@franz-wohlkoenig will you please open this issue back up? Issue 25184 is not a patch to resolve this bug. Issue 25814 is just different code for the Media Manager to work the same way with different code. It's not meant to resolve the bug - the contributor only mentioned that "maybe" it would solve the bug (which it doesn't). But people testing that patch need to not be thinking of the bug when testing.

The bug still needs a patch.

So will you please open this back up so that people can post here and coders can come up with a patch?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25192">issues.joomla.org/tracker/joomla-cms/25192</a>.</sub>

**Comment by bayareajenn** [comment]
Thanks you @franz-wohlkoenig  :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25192">issues.joomla.org/tracker/joomla-cms/25192</a>.</sub>

**Comment by HLeithner** [comment]
@BPBlueprint could you make a git animation because I'm not sure how to replicate the issue.

**Comment by bayareajenn** [comment]
@HLeithner here's what you do (I don't know how to make a git animation)...

1. login to the backend
2. Go to Content -> Media
3. Select a directory inside /images (so a subfolder - if you don't have one, create one)
4. Upload an image to a subdirectory of /images
It might work the first time. It does for me. Then...
5. Navigate to a different directory inside /images
6. Upload an image to that different directory and the image doesn't save there. It saves to the root of /images.

Now, sometimes if I do the first upload and then leave Media and go to say Content -> Articles and then go back to Content -> Media -> subdirectory, I can upload one and get it to stay in the proper directory. But if I do it again in the same or different subdirectory of /images, it saves the image in the root.

This is happening to me on sites hosted at Rochen (multiple sites) and Siteground (multiple sites) so I don't think it's a server configuration issue.

**Comment by bayareajenn** [comment]
Here's a video but I had to zip it since the media type isn't supported by github.
[media-upload-bug.zip](https://github.com/joomla/joomla-cms/files/3291461/media-upload-bug.zip)

**Comment by HLeithner** [comment]
I'm sorry but I'm unable to reproduce this, I tested it on my own servers and on joomla.com test instance without problems...

**Comment by bayareajenn** [comment]
Interesting. Do you think PHP version would affect it? What version of PHP
is joomla.com using? And your server? I'm on 7.2. But I'll test some other
sites on other versions and see if that brings anything to light.

**Comment by bayareajenn** [comment]
It's happening with all versions of PHP so that's not it. We're not alone...this thread people have it happening too. https://www.facebook.com/groups/joomlanospam/permalink/10156021610840997/

Can you suggest anything else I can check? I'm happy to do more testing but I'm not a coder. :(

**Comment by HLeithner** [comment]
could you try another browser?

**Comment by bayareajenn** [comment]
@HLeithner nailed it! Working fine in MS Edge. I was in FF before - all the other times. Are you using Chrome?

So it appears to just not work in Firefox. @BPBlueprint what browser are you using? 

I'm gonna ask on the FB thread too.

**Comment by bayareajenn** [comment]
On the facebook thread, two more people said they were using FF. So that's the common denominator. 

I tried disabling my add-ons one at a time and the problem persisted. So, is there any reason that this is our issue (meaning Joomla)? Or is it really a FF browser issue that should be taken up with them? (Lord knows how that will go.)

**Comment by brianteeman** [comment]
I used to see this a long time ago and forgot about it. Tried tonight to replicate it using both chrome and firefox on windows and could not

**Comment by bayareajenn** [comment]
Thanks Brian. I have a feeling this might just resolve itself with the next
FF update. Maybe it's some intermittent thing with their updates. But I
don't even know how to post to their issue tracker and let them know about
it. Like what would I even say to them?

Do you have any thoughts or suggestions on it? I don't think it's our code
at all. Do you?

I'm debating whether this should be closed or or just left open so others
can discuss as details become known.

**Comment by ghost** [comment]
Issue stay open till Reason (Browser, Core, ...) is clear.

**Comment by BurtNL** [comment]
I'm experiencing the same problem here, Joomla 3.9.8, PHP 7.2.x. Uploading fails and clicking the buttons 'Thumbnail view' and 'Detail view' in the Media manager showing the following error in the console of Firefox: NS_ERROR_NOT_AVAILABLE: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25192">issues.joomla.org/tracker/joomla-cms/25192</a>.</sub>

**Comment by HLeithner** [comment]
I replicated the issue and found the reason why the upload goes to the wrong folder. But my JS skill isn't good enough to fix it....

The problem is that aftern an upload the mediamanager javascript can't access the location of the iframe because it's empty.

https://github.com/joomla/joomla-cms/blob/staging/media/media/js/mediamanager.js#L107

maybe this is a sandbox problem or anything like that maybe @dgrammatiko has an idea why firefox behavior is different then chromes?

**Comment by HusiBT** [comment]
> 
> 
> @HLeithner nailed it! Working fine in MS Edge. I was in FF before - all the other times. Are you using Chrome?
> 
> So it appears to just not work in Firefox. @BPBlueprint what browser are you using?
> 
> I'm gonna ask on the FB thread too.

I use Firefox!
And right -> I checked with Chrome and no problems!

**Comment by dgrammatiko** [comment]
@HLeithner the only thing that might cause this, I guess is https://github.com/joomla/joomla-cms/blob/bc3cf7564698678cc9a657dbe69ca52043b4aa20/media/media/js/mediamanager.js#L28
(Are frames discontinued in ff?)
Try to get the iframe through the id of the parent div and see if that solves the problem here

**Comment by HLeithner** [comment]
I tried the same code in the console and I got a location object including all urls.

Maybe it is related to the POST on the upload? Are there any restrictions?

**Comment by bayareajenn** [comment]
> (Are frames discontinued in ff?)

Came across this with an update date of 18 March 2019 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame but I am not educated enough to know if this has something to do with it. And this too https://developer.mozilla.org/en-US/docs/Tools/Working_with_iframes.

**Comment by HLeithner** [comment]
No both are unrelated.

**Comment by bayareajenn** [comment]
> No both are unrelated.

Got it. Worth a try. At least you know I care. Let me know where I can help (I'm not a coder, sadly). Thank you and everyone for the help on this! You're appreciated!

**Comment by Quy** [comment]
Please test PR #25184<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25192">issues.joomla.org/tracker/joomla-cms/25192</a>.</sub>
