### ISSUE TITLE
Installing a component with only an installation sql file raises a big error message

### ISSUE THREAD

**Issue by glenatron** [joomla/joomla-cms#25202]
### Steps to reproduce the issue

Create a Component in accordance with the J3.x development tutorial with an sql folder and a simple `install.mysql.utf8.sql` but no numbered updates.

### Expected result

The SQL in the `install.mysql.utf8.sql` is run and there is no error raised.

### Actual result

A large error is raised, with the error stack ending in line 1085 of `Install.php` - which looks like this:

`$files = str_replace('.sql', '', \JFolder::files($this->getPath('extension_root') . '/' . $schemapath, '\.sql$'));
usort($files, 'version_compare');`

My suspicion is that `$files` contains no results, so there is nothing to sort.

Also the installer sql is not run in my case, but that may be completely unrelated.

### System information (as much as possible)

Running on a WAMP stack on Windows, but it seems plausible that this is going to be a reasonably common problem.

I did have the update section in my config xml, which may have been a bad thing when there weren't any files in that folder yet:
`<!update> 
		<schemas>
			<schemapath type="mysql">sql/updates/mysql</schemapath>
		</schemas>
</update -->`

Still I would expect this to be handled in a calmer way.

### Additional comments

I have worked around it with a little hedging on that `usort` call for now, but that is probably not the best solution.

**Comment by ReLater** [comment]
Do you have the installation tag inside your extension?
```
    <install>
        <sql>
            <file driver="mysql" charset="utf8">sql/example.install.sql</file>
        </sql>
    </install>
    <uninstall>
        <sql>
            <file driver="mysql" charset="utf8">sql/example.uninstall.sql</file>
        </sql>
    </uninstall>
```
https://docs.joomla.org/Manifest_files#SQL

**Comment by ReLater** [comment]
Maybe I've misunderstood you but I have some problems to understand what you exactely did and where to find the "J3.x development tutorial" that you mention.
Could you please post the error stack.
And the manifest file of your extension.
Thank you!

Just a hint: You can format code snippets with three backticks before and after a code snippet.

**Comment by ReLater** [comment]
Now I see:
- Download Step 6 of hello World manual: https://github.com/scionescire/Joomla-3.2-Hello-World-Component/archive/step-6-using-the-database.zip
- Extract and remove all files in `admin\sql\updates\mysql`.
- zip the package and install it.

Red warning message but no other messages(!)
```
Warning : usort() expects parameter 1 to be array, string given in /libraries/src/Installer/Installer.php on line 1085
Warning : end() expects parameter 1 to be array, string given in /libraries/src/Installer/Installer.php on line 1098
{"success":true,"message":null,"messages":{"warning":["JFolder: :files: Path is not a folder. Path: \/administrator\/components\/com_helloworld\/sql\/updates\/mysql"],"message":["Installation of the component was successful."]},"data":{"redirect":"\/administrator\/index.php?option=com_installer&view=install"}}
```

The extension is installed now.

#### **Reload the page:** or navigate to another one:
- You see the "correct" message from the message queue that should be displayed before reload (immediately after installation):
```
Warning
JFolder: :files: Path is not a folder. Path: /administrator/components/com_helloworld/sql/updates/mysql
```

**Pro:** Thus it's somehow an issue from my point of view even if the extension package manifest is misconfigured because the redirect/page reload is suppressed.

Their should be at least an additional message for users that the extension has been installed.

Irritating.

**Contra:** On the other hand I would say it's the job of the developer to avoid such errors before releasing an extension and a developer should be able to understand the red message. Not a Joomla core issue.

Contra would rule for me and I would close the issue.

#### After installation
![14-06-_2019_21-38-01](https://user-images.githubusercontent.com/20780646/59534237-ff1d1480-8eed-11e9-9464-3dc6a3bd0dfa.jpg)

#### After page reload
![14-06-_2019_21-41-44](https://user-images.githubusercontent.com/20780646/59534247-03493200-8eee-11e9-81e3-b7dd6bde8586.jpg)

**Comment by glenatron** [comment]
If nothing else, a more informative exception ( or performing some validation on the component xml file ) would make the problem a lot easier to troubleshoot- figuring out how to construct a component is pretty tricky even as an experienced developer and supporting people in doing that is probably a positive for the Joomla ecosystem.

**Comment by HLeithner** [comment]
@glenatron it woild be appreciated if you write a pr that make the install process smoother or bring us better error handling

**Comment by richard67** [comment]
This issue here could be related to an issue which the patchtester component had, see comment here: [https://github.com/joomla-extensions/patchtester/issues/186#issuecomment-309291088](https://github.com/joomla-extensions/patchtester/issues/186#issuecomment-309291088).

**Comment by glenatron** [comment]
@HLeithner sure, is the best way to raise the message to use `application->enqueueMessage($msg, 'error');` or is something else more correct in this circumstance?

Can confirm that failing to run the SQL installer file was me messing up the markup of my config file, so that is not relevant to this message at all.

**Comment by ghost** [comment]
@infograf768 can the Issue be closed?

**Comment by HLeithner** [comment]
@glenatron enqueue a message would be enough so if the developer test his component at least once he should see the problem.

I'm closing this. You can reference this issue in your PR.

**Comment by ReLater** [comment]
Maybe you're right and I don't understand your thoughts but there is already a correct message in the queue as you can see in the red error:

{"success":true,"message":null,**"messages"**:{**"warning"**:["JFolder: :files: Path is not a folder. Path: \/administrator\/components\/com_helloworld\/sql\/updates\/mysql"],"message":["Installation of the component was successful."]},"data":{"redirect":"\/administrator\/index.php?option=com_installer&view=install"}}

but it's not displayed. From my point of view the whole routine should stop if $files is not an array because the whole following db query is broken then.

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/Installer.php#L1098

**Comment by HLeithner** [comment]
2 possible ways, stop the installation or let the installer ignore the missing sql file.

**Comment by ReLater** [comment]
Because I prefer to learn coding "the hard way" I would leave it as ist is. See my "Contra" in https://github.com/joomla/joomla-cms/issues/25202#issuecomment-502239994
Why should Joomla react friendly here? The extension is wrongly configured. The red message contains all necessary informations for developers and more helpful informations than the message queue can provide.
