### ISSUE TITLE
[4.0] Template Details - author [RFC]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25237]
In the core of Joomla no individual is given specific named credit. This is true for everywhere except for the template. Why? What makes the template so special that we don't follow the same convention?

**Comment by richard67** [comment]
Good question.

**Comment by ghazal** [comment]
+1

Plus, there is a structural flaw in the footer tag:

```
<footer class="grid-child container-footer footer">
	<hr>
	<p class="float-right">
		<a href="#top" id="back-top" class="back-top">
			<span class="icon-arrow-up-4" aria-hidden="true"></span>
			<span class="sr-only"><?php echo Text::_('TPL_CASSIOPEIA_BACKTOTOP'); ?></span>
			</a>
		</p>
<jdoc:include type="modules" name="footer" style="none" />
	</footer>
```
The "back-to-top" feature is in the same tag as a call to a module in a footer position. So, when one assigns a module to this position, the module content is "glued" to the "back-to-top".

**Comment by richard67** [comment]
> Plus, there is a structural flaw in the footer tag:

@ghazal Please check if there is already an issue for that and create one, if not.

**Comment by ghazal** [comment]
Done.
[#25239]

**Comment by alikon** [comment]
I don't know why template should be special, imho no individual name credit should exists even in template

**Comment by mbabker** [comment]
The 4.0 templates are no different than the templates of 3.x, 2.5, and it looks like 1.5 (assuming I went far enough back in git history because I can't be bothered to download something that old) regarding author name.  I could have sworn this discussion has happened in the past, maybe there's something in the all-but-abandoned Google Groups.  If there's nothing there, it's probably buried in a Skype channel and good luck finding that.

**Comment by brianteeman** [comment]
The previous templates just had the name of the main designer. (Which I was always against) the proposed new one has a long list of SOME of the people who have worked on the template.

I saw no reason in the past and I see no reason now to treat contribution to the template any differently to the rest of joomla.

All together as a whole!

**Comment by mbabker** [comment]
I don't really care either way what the result is.  I just wanted to make sure it was clear in this thread the templates (for better or worse) have historically NOT had `<author>Joomla! Project</author>`, since when I originally read this I was thinking there was some change between 3.x and 4.0 (which there is in the number of names, but that's it right now).

**Comment by ot2sen** [comment]
It goes back to the first templates included. Thought of as external work, external support to some extent. Same with the early competition included templates. Made precedence of some sort.
History tells though that it ends up being community supported, and logically should hold the same project credits (and no favoured mini advertising in the core distributed package).
J4 could be the step to change that, to get in line with the rest of the distribution.

**Comment by brianteeman** [comment]
Thanks for the historical info @ot2sen I forgot about the competitions

**Comment by alikon** [comment]
see #25419 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25237">issues.joomla.org/tracker/joomla-cms/25237</a>.</sub>
