### ISSUE TITLE
4.0 logging out

### ISSUE THREAD

**Issue by marscom65** [joomla/joomla-cms#25254]
Hi,
working on localhost with MAMP PRO 5.3 and PHP 7.2.14, it's almost impossible to work in the backend: almost every operation leads to a logout. Adding an image in the content > saving > logged out. Changing from Control Panel to system > logged out. Clicking an article in the article list > logged out.
Only installation is the JCE PRO. Same behaviour before, without any third-party installation.

Martin

**Comment by HLeithner** [comment]
Which version do you use? Did you tested the version from the backend template repository? https://github.com/joomla/backend-template

**Comment by marscom65** [comment]
The latest Alpha version. Downloaded it from the JOOMLA project site.

**Comment by Quy** [comment]
It is better to test with the nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by ReLater** [comment]
But not today: https://github.com/joomla/joomla-cms/issues/25248

**Comment by brianteeman** [comment]
Even so it is not a common issue or we would all be seeing it. I suspect something in your configuration causing the issue. If you go to the system menu and then check to see if there are any warnings

**Comment by Quy** [comment]
Closing for now since it is not easy to troubleshoot with a local install. Please test with nightly builds and different browser if possible. Check PHP error log. This can be reopened when additional detailed information is provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25254">issues.joomla.org/tracker/joomla-cms/25254</a>.</sub>
