### ISSUE TITLE
[4.0] Extension-Update: Changelog-Button and empty Modal

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#25302]
### Steps to reproduce the issue
Install "German Language Pack 3.9.6.1

### Expected result
While there is no `<changelogurl>`-tag in the xml-file, for me, the **Changelog-Button**  hasn't to appear. Instead a N/A, just like with JCE? 

### Actual result
The **Changelog-Button**  appears and the modal shows an empty value. 
![2019-06-23_16h57_34](https://user-images.githubusercontent.com/5299726/59978167-d4ac1500-95d9-11e9-932f-8cd286a86ced.png)

### System information (as much as possible)
J4-Alpha-10-dev

**Comment by infograf768** [comment]
Confirmed with 3.9.8.1 French pack

**Comment by brianteeman** [comment]
The code is only checking if there is a changelog url - it doesnt check if there is any content at that url

**Comment by roland-d** [comment]
I have noticed this as well. There is a problem in the code somewhere as it executes the wrong query. I haven't been able to put my finger on it yet.

**Comment by infograf768** [comment]
> The code is only checking if there is a changelog url - it doesnt check if there is any content at that url

The code is wrong imho
The button should not display if no changelog url.

I tested 
`<?php if ($item->changelogurl != null) : ?>`
instead of 
`<?php if ($item->changelogurl !== null) : ?>`
and it will display N/A instead of the button on which one can click and get the empty modal.

<img width="565" alt="Screen Shot 2019-06-24 at 11 02 39" src="https://user-images.githubusercontent.com/869724/60005860-a11bca00-966f-11e9-9621-0ac397f572f3.png">

**Comment by infograf768** [comment]
or more simply
`<?php if ($item->changelogurl !== '') : ?>`

here works ok when there is a changelog url

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/25311
Closing as we have a patch.
