### ISSUE TITLE
"500 JHtmlBehavior::calendar not found" when opening 'Manage backups' in Akeeba

### ISSUE THREAD

**Issue by frankazoid** [joomla/joomla-cms#25356]
### Steps to reproduce the issue

1. install jomla 4
2. install akeeba (it won't install from web so i had to upload a latest package
3. run akeeba configuration wizard
4. run a backup
5. click 'manage backups' option

![screen shot 2019-06-28 at 09 14 54](https://issues.joomla.org/uploads/1/1f714f99200eb869c218587befe63239.png)

### Expected result

list of backups should be displayed

### Actual result

"500 JHtmlBehavior::calendar not found" error message is displayed

### System information (as much as possible)

latest mamp on macos

**Comment by ghost** [comment]
Is Akeeba Backup ready for J4?

**Comment by frankazoid** [comment]
It offers to install it right away. I thought that calendar is pretty basic function to stay in 4 at the same place. Sorry if I was wrong

**Comment by alikon** [comment]
that class `JHtmlBehavior::calendar` was deprecated in 3.x and has been removed in 4.x https://github.com/joomla/joomla-cms/pull/22295/files#diff-f6f264d0b0673dc25ecc75e7746ec235L266

**Comment by HLeithner** [comment]
@nikosdion do you have a j4 ready version of akeeba?

**Comment by infograf768** [comment]
Closing as not Joomla Core.

**Comment by infograf768** [comment]
Try commenting
`		//JHtml::_('behavior.calendar');
`
in /administrator/components/com_akeeba/View/Manage/Html.php

**Comment by frankazoid** [comment]
Yes, that helped! Thank you!

**Comment by ghost** [comment]
@frankazoid please ask next Time Dev. of 3rd-Party-Component first.

**Comment by nikosdion** [comment]
The currently published version of Akeeba Backup is compatible with alpha 8. The next version will be compatible with alpha 9. 

On June 11th I changed the line @infograf768 mentioned with
```php
		if (version_compare(JVERSION, '3.999.999', 'le'))
		{
			JHtml::_('behavior.calendar');
		}
```
since it's needed in Joomla 3.8 AFAIK. And that was all the changes I found necessary to support alpha 9 :)

Please do remember that Joomla! 4 is still in active development, as indicated by the alpha tag in the version number. As a result, compatibility issues with it are treated as low priority. This will change once Joomla! 4 reaches a mature beta or RC.
