### ISSUE TITLE
[4.0] Unused but not deprecated code

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25358]
This code in `libraries\cms\html\behavior.php` is for javascript polyfills for unsupported browsers **and** the polyfills it links to are no longer part of joomla.

So can we just delete them and/or do we need to mark them as deprecated in J3

https://github.com/joomla/joomla-cms/blob/0bdde5a48109e1e285a614c7f4c748649a967b84/libraries/cms/html/behavior.php#L293-L301

**Comment by Bakual** [comment]
Even when the code is useless and will not do anything, removing it could break extensions which for whatever unlikely reason have that call.
So just deprecate it in j3 and remove in 4.0.

**Comment by mbabker** [comment]
I'd say leave it.  You're still going to have to deal with polyfills (unless you're one of those people who thinks everyone on the internet should just use a nightly build of a browser with all the latest hotness enabled), just maybe not the IE conditional browser part of it.  If you remove this method now you're just going to re-add something similar when polyfills need to start being added in.

**Comment by brianteeman** [comment]
What about line 323 pointing to non existent scripts?

**Comment by mbabker** [comment]
If there are no polyfills being shipped with Joomla right now, just no-op the method.

Or, someone decide "Joomla doesn't need to ship polyfills because we have a rolling browser support policy and only latest version is ever supported" (which seems to be the push, not a good thing for frontend visitors to a Joomla site) and remove anything related to supporting browser polyfills.  I get the feeling the latter is going to be the path people take the way things are going around here.

**Comment by dgrammatiko** [comment]
> Or, someone

I was that someone but the removal was only temporary till we figure out a way to fetch those polyfills (eg there weren't - I think they still aren't Joomla3 was using the polyfill.io scripts - on npmjs at the time we've moved the assets to a package.json). Pretty easy to just include core.js from https://github.com/zloirock/core-js and get anything needed in a directory, format (.js/.min.js) you want...
