### ISSUE TITLE
[4.0] Test upgrade path from Joomla 3 to Joomla 4 on Postgres

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#25467]
@alikon @richard67 (or anyone else running postgres) can you please test the following:

1. Install a copy of Joomla 3.x (I was using 3.9.9 RC) on postgres
2. Use the upload file functionality with the latest nightly (https://developer.joomla.org/nightly-builds.html)
3. Check if Joomla upgrades successfully

Caveats:
- On the intermediate authentication pages you'll get template not found warnings (and the styling is not optimal)
- But once you get the Update finished page then you need to navigate to any other page and then proceed without any issues. 

However I expect the upgrade to actually work in functionality

**Comment by richard67** [comment]
Ok, will do that tomorrow evening after work, German time.

**Comment by alikon** [comment]
let me invite @twister65 to this postgresql party

**Comment by twister65** [comment]
I have this error during the upgrade:
![JoomlaPG_upgrade](https://user-images.githubusercontent.com/26852967/60823985-14adf300-a1a9-11e9-9441-bdaa0d195990.png)
It means that the timestamp of "checked_out_time" in
https://github.com/joomla/joomla-cms/blob/0f83986d1b95eb7e37881f1240b3e79b1a125558/administrator/components/com_admin/sql/updates/postgresql/4.0.0-2016-10-02.sql#L7-L8
is not correct, it should be:
'1970-01-01 00:00:00' instead of '0000-00-00 00:00:00'

**Comment by twister65** [comment]
> Error
The template for this display is not available.

I've got the same error with MySQL.

**Comment by twister65** [comment]
After building a new update package, I have this error:
![home_error](https://user-images.githubusercontent.com/26852967/60827223-feeffc00-a1af-11e9-89f2-6335ed897022.png)
It means that the home expression should be smallint and not text.
https://github.com/joomla/joomla-cms/blob/0f83986d1b95eb7e37881f1240b3e79b1a125558/administrator/components/com_admin/sql/updates/postgresql/4.0.0-2016-10-02.sql#L11-L12

**Comment by alikon** [comment]
@twister65 can you add your findings to  #25461 if you want
https://github.com/joomla/joomla-cms/pull/25461/files#diff-18dfb1b9c26a65fe27454cb3d7081eb0
branch is open even if is most related to mysql

**Comment by twister65** [comment]
@alikon , I can't push in your branch:
> Unable to push
remote: Permission to alikon/joomla-cms.git denied to twister65.
fatal: unable to access 'https://github.com/alikon/joomla-cms.git/': The requested URL returned error: 403

Should I make a PR ?

**Comment by richard67** [comment]
@twister65 Would be good if you could make a PR. I don't think it was a good idea by @alikon to add that to his PR, because his PR is focused on mysql and we should not mix things.

**Comment by alikon** [comment]
not a problem do as it is best for you

**Comment by richard67** [comment]
@wilsonge With twister's PR #25477 applied to the update package from last nightly build, the SQL errors disappear, and the behavior becomes like you described above, i.e. there are "template not found" warnings, but they disappear when update is finished and you are navigating through backend. So that PR makes the update finish without crash.

But there remain other issues to be handled. The first thing I saw is that com_search has been removed, but the menu entry in the left side admin menu in backend is still there. I don't dare to think about what will happen when updating a site with a search module in frontend. Do you have any plan for that already?

**Comment by ghost** [comment]
Closed as having Pull Request #25477
