### ISSUE TITLE
404 URL inside recaptcha_invisible

### ISSUE THREAD

**Issue by RolandSM** [joomla/joomla-cms#25488]
### Steps to reproduce the issue
Go to Plugins -> Invisible Recaptcha and click on the Google Recaptcha Link from the Description.

### Expected result
Google Recaptcha Site loading

### Actual result
404er error because the created URL is: http://mysite.de/'https://google.com...

### System information (as much as possible)
Joomla 3.9.8 with PHP 7.3

**Comment by ghost** [comment]
Can't confirm. Link https://www.google.com/recaptcha/intro/v3.html loaded as expected.
#### System information
Setting | Value
-- | --
PHP Built On | Linux lamp126.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.6
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.8 Stable [ Amani ] 11-June-2019 20:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by brianteeman** [comment]
Where you using english or another language?
There is no problem I can see in english but perhaps there is an error in the translation

**Comment by ghost** [comment]
German, English works as expected.

**Comment by RolandSM** [comment]
Yes, it´s the german translation file...

**Comment by brianteeman** [comment]
@tecpromotion Could you have a look at this please Stefan

**Comment by infograf768** [comment]
There is an error in the de-DE ini and sys.ini files
It should be
`PLG_CAPTCHA_RECAPTCHA_INVISIBLE_XML_DESCRIPTION="Dieses Captcha-Plugin verwendet den Google reCAPTCHA-Service um Spammer fernzuhalten. Google bietet diesen kostenlosen Service auf der Website <a href=\"https://www.google.com/recaptcha\" target=\"_blank\">https://www.google.com/recaptcha</a> an."`
Instead of
`PLG_CAPTCHA_RECAPTCHA_INVISIBLE_XML_DESCRIPTION="Dieses Captcha-Plugin verwendet den Google reCAPTCHA-Service um Spammer fernzuhalten. Google bietet diesen kostenlosen Service auf der Website <a href=\'https://www.google.com/recaptcha\' target=\'_blank\'>https://www.google.com/recaptcha</a> an."`

**Comment by infograf768** [comment]
Basically we should not escape single quotes. I.e. it would also work in this case if we had 
`<a href='https://www.google.com/recaptcha' target='_blank'>`

**Comment by tecpromotion** [comment]
Hi @RolandSM 
It's fixed in upcoming 3.9.10v1 now.

Thanks @infograf768 for hint with single quotes.

**Comment by infograf768** [comment]
@tecpromotion
Commented in your German PR as you have similar issue in 2 other lang files.

**Comment by tecpromotion** [comment]
> @tecpromotion
> Commented in your German PR as you have similar issue in 2 other lang files.

thanks @infograf768 
fixed now
