### ISSUE TITLE
[4.0] behavior.keepalive??

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25634]
> Keep session alive, for example, while editing or creating an article.

So my question is - should this be set on all pages with a form?

If not then what type of form should it be set on?

If you look through the codebase there is no consistency on this. I am happy to spend the time to make it consistent and logical - I just need to understand the when and where

**Comment by mbabker** [comment]
I'd go with a guideline of if a form gets submitted through POST then it should in most cases have keepalive since that form should have a CSRF check behind it (forms like a create item form, edit form, login form, contact form, etc.), and if it gets submitted through GET it doesn't need a keepalive behavior because these types of forms should essentially be nothing more than query filters for a page.  I say this also realizing the backend views are in kind of a FUBAR state because the search filters trigger a POST form submission, and it looks like the frontend com_content.archive view has the same "issue" which means Joomla isn't always using the appropriate HTTP action to do things sadly.

**Comment by brianteeman** [comment]
Thanks - I can work with that. I assume therefore that any form with keepalive must have the csrf check as well.

**Comment by brianteeman** [comment]
partial PR in #25638

**Comment by wilsonge** [comment]
It's not an implicit thing. All keepalive does is keep the session alive. However yeah basically all our forms should have a csrf check to try and stop request forgeries as a rule of thumb (can't think of any exceptions in core)

**Comment by brianteeman** [comment]
re-opening so it can be checked further after todays release

**Comment by brianteeman** [comment]
So to confirm 
every time we have a <form action we should also have a form.token
Because we dont
