### ISSUE TITLE
[4.0] resize image on upload and create srcset

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25655]
### Is your feature request related to a problem? Please describe.

users upload big images 3 - 10+ MB

### Describe the solution you'd like

resize image on upload and create srcset

**Comment by ReLater** [comment]
What do you mean with "srcset"? Save image with several sizes?

And then?

Who or what will where create the needed HTML?

```
 <picture>
  <source media="(min-width: 650px)" srcset="img_pink_flowers.jpg">
  <source media="(min-width: 465px)" srcset="img_white_flower.jpg">
  <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;">
</picture> 
```

The user? Or automatically?

And that is a very simple example that won't match for 50% of all sites because any template reacts different concerning responsive behavior and available space for the images.

What will happen with all of these images if you change the template and the sizes don't match there. Upload all images again after you've changed the configuration?

How complex would such a configuration become for users?

How complex would a code become that has to check if the images exist before the HTML is inserted in the page?

Or display pixalated images?

Please think before you post feature requests!

I prefer plugins that do these jobs before the then cached images are USED in frontend. Not destructively on upload.

BTW: You got already many answers concerning "resize image on upload" but ignored any aspect of it. "The slaves are on holidays at the moment."

**Comment by brianteeman** [comment]
@ReLater secret is a standard for loading images https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/

**Comment by C-Lodder** [comment]
https://extensions.joomla.org/extensions/extension/photos-a-images/images/imgen/
https://extensions.joomla.org/extension/imagerecycle-image-optimizer/

Both are free

**Comment by ghost** [comment]
Thanks @C-Lodder, closing for the Reason stated in above Comment.

**Comment by brianteeman** [comment]
@franz-wohlkoenig "Slow down... you move too fast"

Neither of those extensions are for srcset (unless I missed it) and that really is something that should be possible in core

**Comment by ReLater** [comment]
> @ReLater secret is a standard for loading images https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/

That's exactely what I asked in my comment and was talking about. To use srcset you
1) need images with different resolutions.
2) some magic that knows which resolutions are available.
3) some magic that is clever enough to call the correct image width sizes (and they differ in all templates because the width of the areas where images are inside can differ).
4) that builds a srcset HTML
5) that puts the HTML into the editor or somewhere via PHP, JLayouts.
6) the possibility to configure that for the needs of the individual template.

And because i use a custom plugin and JLayouts for that I know that this is not that easy to get good-looking results for different templates.

Thus you need a possibilty to remake the images and to  newly configure the whole system.

Thus:

> I prefer plugins that do these jobs before the then cached images are USED in frontend. Not destructively on upload.

**Comment by ghost** [comment]
Thanks Brian for reopening this, cous it realy should be possible in core

**Comment by ghost** [comment]
is this implemented in J4 ?

**Comment by brianteeman** [comment]
No - that's why its an open issue

**Comment by ghost** [comment]
what needs to be done to include this in J4.0?

**Comment by ghost** [comment]
@chnnst 
> what needs to be done to include this in J4.0?

1. A Developer writing an Pull Request
2. Two successfully Test
3. accepting the PR by the Release Lead

Same Procedere on every Issue.

**Comment by Quy** [comment]
Please test PR #34803
