### ISSUE TITLE
User Disable Actions Log

### ISSUE THREAD

**Issue by shraddhaSankpal27** [joomla/joomla-cms#25694]
### Steps to reproduce the issue
Login to Joomla Backend with Superuser access

Go to Users => Manage
Disable any user
Go to Users => Users Action Log
See the latest activity. "User user2 logged out from admin"

### Expected result
'User user2 logged out from admin' activity should not be logged because 'user2' is not login to the Joomla backend.

### Actual result
Activity should not be logged.

### System information (as much as possible)
Joomla - 3.9.10
![screen shot 2019-07-23 at 05 20 08](https://issues.joomla.org/uploads/1/e40a99da1e2c4d0cbb7d3c3ed77a224e.png)

![screen shot 2019-07-23 at 05 20 10](https://issues.joomla.org/uploads/1/a90d1339cf62b5023eedee3fc0f53c92.png)

**Comment by ghost** [comment]
Thanks for your Report. Can you please read #25688? If its the same issue please close this one also.

**Comment by shraddhaSankpal27** [comment]
Issue is on same action on user disable but its different one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25694">issues.joomla.org/tracker/joomla-cms/25694</a>.</sub>

**Comment by richard67** [comment]
Issue confirmed: Instead of something like "user XY blocked", the action log shows "user XY logged out from admin" when user XY is blocked by some super admin, but that user XY has not been logged in.

**Comment by Quy** [comment]
Based on [Michael's comment,](https://github.com/joomla/joomla-cms/issues/25688#issuecomment-513869306) I assume the message would have to be generic such as `User admin1 updated the user johndoe`.

**Comment by richard67** [comment]
Yes, just as you write it I remember that comment.

**Comment by ghost** [comment]
Thats why i asked if its the same Issue.

**Comment by richard67** [comment]
No, not the same. This issue here should be possible to be fixed because we already log user modifications. The other issue was about logging more details which would be new and technically not an easy thing.

**Comment by richard67** [comment]
It seems the onUserLogout event is triggered anyway, and this issues that log.

So I think somwhere the user is logged out (regardless if logged in or not) and so that event is fired.

As far as I understand this issue, the user modification is logged correctly, and so it only needs to surpress that user logout if the user is not logged in, or alternatively, surpress the log in that case.

If anyone has a quick idea how to do that, let us know here.

**Comment by richard67** [comment]
@mbabker Sorry when bothering you, but maybe you have an idea: The issue here seems not to be that the actions log just logs that some user was modified instead of logging the details. That's ok here. The problem here is that when a user is blocked, it seems there is made a forced logout even if the user is not logged in anywhere. And this logout action then triggers the event which logs the logout action, which is wrong in this case. Do you know where to look for that, and do you think it could be changed so the logout is not called when the user is not logged in? Or does this forced logout have some reason?

**Comment by alikon** [comment]
please test #25812
