### ISSUE TITLE
Terms and conds duplicated  in user registration

### ISSUE THREAD

**Issue by Pablo234** [joomla/joomla-cms#25710]
### Steps to reproduce the issue

Enable TERMS AND CONDS plugin

Register a new user

### Expected result

User must confirm terms and conds one time.

### Actual result

User must confirm terms and conds two times: 1 for terms and conds field and other one for PLUGIN.

**Comment by brianteeman** [comment]
please post screenshots - this doesnt make sense

**Comment by richard67** [comment]
Duplicate of #25706 ?

**Comment by ghost** [comment]
Closed as duplicate Report. It can always reopened.

**Comment by brianteeman** [comment]
@franz-wohlkoenig the other issue is also closed

**Comment by ghost** [comment]
> The field in the registration form is one that you have created. Only the one from the plugin is one that is part of core joomla

Was the Reason for close #25706. So you mean to reopen this?

**Comment by infograf768** [comment]
Looks like this issue comes from a confusion between `Terms of Service` and `Terms & Conditions`
The first one is set in the user_profile plugin, the second one from the user_terms plugin.
Therefore it does not look like a bug but as an easy to make confusion between both Terms to agree to.

<img width="770" alt="Screen Shot 2019-07-28 at 08 33 22" src="https://user-images.githubusercontent.com/869724/62003128-65629d00-b112-11e9-924f-fcd46d704c71.png">

I guess the issue was the same in #25706 but was not explained correctly there.
