### ISSUE TITLE
[4.0]  No tag is displayed to select in the article (ajax)

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#25759]
### Steps to reproduce the issue
Go to Tags and create new
Go to articles, in tags area i  write the initial of the tag name (ajax)  but nothing is shown.

### Expected result
In the tag area for the article, show the tags to select 

### Actual result
Nobody show in tag area of the article.

**Comment by ghost** [comment]
@Open2logic please look if duplicate of #23589

**Comment by ghazal** [comment]
@franz-wohlkoenig There has been many improvements on com_tags since January, specially with the JS scripts it uses (ie choices.js and joomla-field-fancy-select.js). So I don't think #23589 is relevant now.

@Open2logic I can't replicate this error. What kind of joomla 4 package are you using ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25759">issues.joomla.org/tracker/joomla-cms/25759</a>.</sub>

**Comment by alikon** [comment]
unable to replicate with the current 4.0-dev

**Comment by ghost** [comment]
closing Issue as not to replicate. @Open2logic you can always reopen the issue if needed.

**Comment by ChristoforosKor** [comment]
Is there a chance that takes too long to respond? I had a similar issue. Can you check the the network activity from firebug or your tool to see if the ajax call for com_tags is taking place? 
If no ajax call is happening to com_tags can you check if you have javascript errors?
If it the ajax call is made, can you see if it is taking to long to respond? or is it returning an error? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25759">issues.joomla.org/tracker/joomla-cms/25759</a>.</sub>

**Comment by ChristoforosKor** [comment]
I had the same issue with a site that holded 50.000 tags adn about 160.000 articles. It was taking to long to responed showing as staled. Often it was returning nothing. That's why I comment out this issue. If test this situation with such a kind of big volume propably you can reproduce the issue.
I am sorry for posting on closed issue, but the problem exists. I can open a new issue if it is more appropriate and provide you a db with such an amount of data.

**Comment by ghazal** [comment]
A new JS script is used for com_tags in J4, ie [choices.js](https://github.com/jshjohnson/Choices). So, you can't compare J3's com_tags and J4's com_tags performances.

And yes, open a new issue if you noticed that something is wrong in com_tags ...for J3

**Comment by SharkyKZ** [comment]
I can replicate this but I can't tell if it's intended behavior or not. This could have been changed for performance reasons. Maybe ask @Fedik as author of #22263.

**Comment by Fedik** [comment]
I cannot reproduce,
A search works as expected to me:
![screen 2019-08-03](https://user-images.githubusercontent.com/1568198/62414066-8dc12e80-b61f-11e9-84c6-6886cd16d192.png)

After  #22263 the tag field does not load ALL tags on initial load. 
It should show only searched while typing (more than 3 characters).

**Comment by Fedik** [comment]
the same for "Articles" table:
![screen 2019-08-03-2](https://user-images.githubusercontent.com/1568198/62414169-8f3f2680-b620-11e9-8343-2d8701bc885b.png)

**Comment by Open2logic** [comment]
Ok, is a error of  Chrome browse or extensions for Chrome, in others browsdr work correct.
