### ISSUE TITLE
Suggested improvements to Privacy/GDPR implementation

### ISSUE THREAD

**Issue by arvindpdmn** [joomla/joomla-cms#25781]
### Steps to reproduce the issue

1. Login with a valid user.
2. Let the user access URL path "/component/privacy/request".
3. User enters another email address (not his current email address). However, entered email address is valid in "users" table and this user has access to that email address. Select "Export" and submit.
4. Repeat steps 2 and 3 but select "Remove" instead of "Export".
5. Let user access the entered email's mailbox and confirm the two requests in sequence.

6. Let Super User login via admin panel and check "Users -> Privacy" menu. Both requests are noted as Confirmed but problem is admin intervention is needed to email exported data or delete user data.
7. Let Super User email exported data. Status remains as Confirmed: doesn't move to Completed.
8. Let Super User delete data. Status remains as Confirmed: doesn't move to Completed.

### Expected result

1. Any email (valid in DB) can be entered by current user: why not limit this to current user's email?
2. For export, email with exported data must be automatically once confirmed.
3. For remove, "Delete Data" must happen automatically.
4. Exported data does not include custom fields from "user_profiles" table. Custom data from "user_profiles" table is also not deleted.
5. In general, the flow is complex flow. Why not allow logged in user to download data right away?
6. When automated, status should become "Completed".

### Actual result

See above

### System information (as much as possible)

Joomla 3.9.10 installation. Tested on Firefox Quantum 68.0.1 (64-bit).

### Additional comments

None

**Comment by jeckodevelopment** [comment]
> For remove, "Delete Data" must happen automatically.

Unfortunately, you can't remove directly data, because you don't know if all the data of the user is erased. Not all the extensions support the core features yet.

**Comment by mbabker** [comment]
Automatically providing exports or executing the remove actions is not practical.  An administrator needs to review these requests to ensure that all data is picked up (in the case of other extensions which don't integrate into com_privacy having information) and be able to manually add info to the export or provide (legally justified) reasoning as to why info cannot be removed if need be.

Actions purposefully do not automatically transition.  Just because an administrator clicks the button to action a remove request does not mean it is fully complete; there may be other data to be removed that isn't integrated with com_privacy, or the administrator may need to write an email explaining that not all information is removed.  There is more to the workflow than clicking a couple of buttons.

**Comment by arvindpdmn** [comment]
Thanks for the clarifications.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25781">issues.joomla.org/tracker/joomla-cms/25781</a>.</sub>

**Comment by ghost** [comment]
@arvindpdmn if the Issue don't need to stay open please close it.
