### ISSUE TITLE
Restoring a version does not load tags or the Version Note.

### ISSUE THREAD

**Issue by vdrover** [joomla/joomla-cms#2578]
#### Steps to reproduce the issue
1. Install fresh j3.2.0 on localhost with php5.4.3 and MySQL 5.5.20. I used the new multilingual install feature and the following languages: English (GB), FR, HU and Afrikaans.
2. Open an article, add a tag and a version note.
3. SAVE.
4. Click the version button and restore the original (1st) version.
5. SAVE.
6. Click the version button and restore the newest (2nd) version.

#### Expected result
Upon restore of 2nd version, the Tag and Version Notes would be populated with the data entered in the tag and version notes fields as described above in Step 2.

#### Actual result
Upon restore of 2nd version, the tag and version nots fields are blank.

#### System information (as much as possible)
Database Version	 5.5.20
Database Collation	 utf8_general_ci
PHP Version	 5.4.3
Web Server	 Apache
WebServer to PHP Interface	 apache2handler
Joomla! Version	 Joomla! 3.2.0 Stable [ Ember ] 6-November-2013 14:00 GMT
Joomla! Platform Version	 Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36

**Comment by wilsonge** [comment]
Version history acts on the 'base content' fields. As tags are an extension to the UCM base content fields they aren't tracked by user history. Whilst this is inconvenient given the current code structure this won't be changed in the foreseeable future.

The version note field is only used for showing the reason for changes in the comparison view and shouldn't be 'displayed' in the version note field (as you're now in edit mode and will want to write a new version note rather than seeing the existing one).
