### ISSUE TITLE
[4.0] PHP error on Joomla Update page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25888]
### Steps to reproduce the issue

Go to `/administrator/index.php?option=com_joomlaupdate`

### Expected result

No PHP error

### Actual result

![Screenshot_2019-08-16 Joomla Update - J4 - Administration](https://user-images.githubusercontent.com/2019801/63154961-99dac200-c009-11e9-85a2-61559cb563d9.png)

**Comment by alikon** [comment]
i can confirm, even if it is not a fatal error but a Notice :smile:

**Comment by C-Lodder** [comment]
Oops, didn't even read the notice....just saw an orange box lol

**Comment by infograf768** [comment]
This gets rid of the Notice
```
		foreach ($rows as $extension)
		{
			if ($extension->manifest_cache)
			{
				$decode = json_decode($extension->manifest_cache);
				$this->translateExtensionName($extension);
				$extension->version = $decode->version;
				unset($extension->manifest_cache);
			}
		}
```
But it rather looks like a hack. :)

**Comment by richard67** [comment]
This notice happens when the extensions updater wants to check for an extension if there is an update, and this extension is a core extension but not added to the ExtensioneHelper.php core extensions list, so the updater tries to find an update like for 3rd party extensions. I will try to find out which extension is missing and if I find it, I will make a PR.

**Comment by richard67** [comment]
I've once noticed that here [https://github.com/bembelimen/joomla-cms/pull/37#issuecomment-520237996](https://github.com/bembelimen/joomla-cms/pull/37#issuecomment-520237996) and solved it here [https://github.com/bembelimen/joomla-cms/pull/39](https://github.com/bembelimen/joomla-cms/pull/39). Is the same file and same line where the warning occurs.

**Comment by richard67** [comment]
I think I have found it, but it seems not to come from the new backend template, i.e. the notice should have been there before, too.

**Comment by richard67** [comment]
@wilsonge The testing sample data is missing in the list of core extensions in the ExtensionHelper.php. But testing sample data is only available when working on cloned git repo, not when using e.g. a nightly build or a release package. That's why I did not get the notice when testing with the backend template, it was a nightly build. Do you know if it is safe then to add it to the list? If we don't add it we get the PHP notice mentioned above when it is available. But what happens if I add it and it is not available?

**Comment by richard67** [comment]
Yeah, that was it, testing sample data missing in core extensions list. If fixed, notice goes away.

**Comment by richard67** [comment]
PR is on the way.

**Comment by brianteeman** [comment]
Dont forget that testing sample daata plugin will not be shipped with joomla

**Comment by richard67** [comment]
@brianteeman Read my question to George above and you will see that I am pretty much aware of it. But it needs to be in the list if present. Question is if it will do harm when in the list but not present.

**Comment by richard67** [comment]
@brianteeman I've just checked, it is safe to have something which is not shipped in the list of core extensions, because this list is used to build where clauses for database queries, and if that thing is not installed, it will not be in the result set of that query because it is not in the extensions table in database.
@wilsonge No need for you to help, I've got it.

**Comment by ghost** [comment]
Closed as having Pull Request #25910

**Comment by richard67** [comment]
@brianteeman Would be nice if you can find time for testing. We currently have a lack of testers, maybe due to holidays.

**Comment by richard67** [comment]
New Pull Request is #25919 . Please test.
