### ISSUE TITLE
[4.0] [backend-template] Login animation is glitchy

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25904]
Despite my opinion on the ajax login being completely pointless:

### Steps to reproduce the issue

Login to the Joomla backend

### Expected result

Smmoth animation

### Actual result

Glitchy animation:
https://gyazo.com/c0d96b9bfe91ff045f3eadcc85a10203

**Comment by dgrammatiko** [comment]
@C-Lodder you do realise that is **impossible** to spread animation between http requests, right? The whole idea is wrong, here. People copy/pasted some behaviour of an SPA and tried to apply on an old fashioned http-request-everything. Of course, it doesn't work and I dare to say it would be impossible to be fixed due to the nature of the web. You see network will always be a question mark and having such a question mark in between some animation the effect will be always glitchy (what are you gonna optimise for? slow connections then you slow down the fast ones, are you gonna opt for fast connections? then slow ones will have a huge gap)

All and all just remove something that **IS NOT FIT** for joomla. If ever the backend becomes an app that will load the main content through ajax then you can bring the animations back. But not in the current state...

**Comment by C-Lodder** [comment]
@dgrammitiko yes I know. Only solution would be a fade out/in.

Currently just looks like a Pablo job

**Comment by Quy** [comment]
Fixed in #27857. If not, please advise. Thanks.
