### ISSUE TITLE
[4.0][RFC] remove postgresql or pgsql or PDO compatibility

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#25947]
### Steps to reproduce the issue
use j4 with something else than mysql < 5.7

### Expected result
all should work as expected

### Actual result
....  nothing is working as expected if you run something  more than mysql 5.7

### Additional comments
As we are not able to deal with something more than mysql >5.6.x, shulod be  more honest to declare that dued to few contributors we cannot guarantee that j.x will  work with any dbms different from  mysql  maybe less than 5.7   could  be much more near to reality

**Comment by mbabker** [comment]
I've been saying for years to just roll back to MySQL only because while support for other RDBMS' is good it's such a niche use case that's really only well suited for custom builds, and at that point Joomla isn't going to be a good choice for your needs (in part because there is so little ecosystem support, there are not many extension vendors providing PostgreSQL or SQL Server compatible packages and of those I know who have tried it they have also rolled back on the support because the niche use cases didn't justify the extra time and cost for that work).

**Comment by HLeithner** [comment]
We already fixed many postgres problems in j4 to make the situation better.

Drone already run postgresql tests, not many but it's a string point. Also system tests will run on both mysql and postgresql as soon as we start writing them. But for starting writing tests the system should be stable.

If there are problem please write an issue and we will try to fix it. In best case you have much more knowledge with pgsql as the most of us so you maybe able to provide a fix too.

**Comment by infograf768** [comment]
Looks like @alikon does not only refers to postgres but also to the MySQL version.
Have I understood correctly?

**Comment by alikon** [comment]
**mea culpa,** i was one of them who strongly believed in miracles, unfortunately, now i'm making count with the sad reality, even if it seems i'm only one of the few looking at the real things.... but even if it cost a lot to me to admit.... the reality is under of eyes, if you really  want to really look at it

**Comment by SharkyKZ** [comment]
What's wrong with PDO?
