### ISSUE TITLE
Repeatable custom field - Editor field: WYSIWYG-Editor problems when adding new list-item

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#25967]
### Steps to reproduce the issue
-Create a repeatable custom field at com_content/article with an editor-text-area
-use the WYSIWYG-Editor (in my case TinyMCE)
-go to article > repeatable field and start edit:
--add new repeatable-field-list item (the first item makes no problem)
--add a second and/or third item

### Expected result
On every repeatable-field-list-item (type Editor) you can see the WYSIWYG-editor correctly

### Actual result
-on first list-item you see the WYSIWYG-editor correctly
-add a new list-item > then there is no WYSIWYG-editor
-push the "editor on/off"-button at any list-item-field and you get one more WYSIWYG-editor on first item

If you save the article between, you can add a new list-item as expected. 

### System information (as much as possible)
PHP 7.2
Joomla! 3.9.11

**Comment by richard67** [comment]
Could you check if this is related to #25931 ?

**Comment by HusiBT** [comment]
I´m not sure, but maybe #25931 ist related to my issue.

So I tried to put the lines into plugins/fields/repeatable/repeatable.php as described at https://github.com/joomla/joomla-cms/pull/25931:
I added the lines 

if ('editor' === $formField->fieldtype)
{
   $child->addAttribute(name: 'buttons', value: 'true');
}

at line 74

But instead of having a fix, I get a syntax error (syntax error, unexpected ':', expecting ',' or ')' ) when I try to open the article with my repeatable fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25967">issues.joomla.org/tracker/joomla-cms/25967</a>.</sub>

**Comment by richard67** [comment]
@BPBlueprint The 'name: ' and 'value: ' are not part of the source code, they are function parameter names shown by the editor which @mvanvu used when making the screenshot in his pull request (PR) #25931. See here the source code of that file: [https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/repeatable/repeatable.php#L71](https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/repeatable/repeatable.php#L71).

So you have to add the code aou have mentioned with `$child->addAttribute('buttons', 'true');` instead of `$child->addAttribute(name: 'buttons', value: 'true');`.

Furthermore, this added code is only used for testing. If you want to test if PR #25931 solves your problem, you have to apply the changes of that PR. You can see the changes in the "Files changed" view of that PR: [https://github.com/joomla/joomla-cms/pull/25931/files](https://github.com/joomla/joomla-cms/pull/25931/files).

When you can manage that and test, please mark your test result for PR #25931 in the issue tracker here [https://issues.joomla.org/tracker/joomla-cms/25931](https://issues.joomla.org/tracker/joomla-cms/25931) by using the "Test this" button, then selecting the appropriate test result and then clicking the "Submitt test result" button.

Finally, if PR #25931 solved your problem so your test was good, close this issue here. Otherwise, if PR does not solve your problem, leave this issue here open and report back here that the PR did not help.

**Comment by HusiBT** [comment]
@richard67 Thanks for your help.

I now tested this code at repeatable.php and I also tested the changes at the TinyMCE-editor from PR #25931 (media/editors/tinymce/js/tinymce.js, media/editors/tinymce/js/tinymce.min.js and plugins/editors/tinymce/tinymce.php), but they didn´t solve my issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25967">issues.joomla.org/tracker/joomla-cms/25967</a>.</sub>

**Comment by richard67** [comment]
@BPBlueprint Thanks for reporting back.

**Comment by HusiBT** [comment]
Do you need any more information or could you reproduce this issue?

**Comment by HusiBT** [comment]
@richard67 Is there any idea how to solve that problem? Is there anything I can do by giving more information or something like that?

**Comment by richard67** [comment]
Thanks, the information could be helpful. Unfortunately I don’t have any idea yet how to solve it. Maybe someone with more knowledge on custom fields should have a look on it. @Sharky do you have any idea?

**Comment by Quy** [comment]
Please check if #27081 fixes the problem.

**Comment by HusiBT** [comment]
#27081 fixes the problem!

THAT´S GREAT!

**Comment by Quy** [comment]
Awesome! Please mark your test successful at the issue tracker so it can be merged. Thank you.

https://issues.joomla.org/tracker/joomla-cms/27081

**Comment by Quy** [comment]
Fixed per PR #27081.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25967">issues.joomla.org/tracker/joomla-cms/25967</a>.</sub>
