### ISSUE TITLE
[4.0] [RFC] Installer does not check the minimum requirements for databases

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#26106]
### Steps to reproduce the issue

Install 4.0 on a system running on systems that does not meat the database minimums for example mysql 5.5.*

### Expected result

The installer aborts or we show some message indication that the system is runnung in an not supported configuration.

### Actual result

Joomla still works for now but we don't tell our users this is a not supported setup.

### Additional comments

I personally see these workarounds.

0. let the installer stop working / showing an dedicated message
1. postinstall message checking the minimum versions.
2. system alert on any backend login to that site like we do with the php versions too.

Any other opinions?

The part why this is important is that starting with 4.0.0 we are stopping to allow updates for sites that don't meat that database requirements so such a site gets insecure by the first security realted release.

**Comment by wilsonge** [comment]
postinstall is no good as it requires having an installation. installer should stop working and show a page similar to the php minimum requirements page i think

**Comment by richard67** [comment]
@wilsonge This is not working or wrong. It is the same problem as I have with issue #27924 : The database connection validation of the setup model just checks if the user can connect with the provided credentials. If not, we come back to the form and can correct data. But the check of the database name (including try to install it) and check of db version are then done in the CreateDatabase function of the database model, and if somethign goes wrong there we end up as descibed in issue #27924 . The reason is that it seems to be missing a correct error handling in JS/Ajax for the final step, creating database if necessary and installing the cms. It seems the installation is unfinished work at this point, and it goes together with including the languages installation and default language selection, which requires some work at the same place. Unfortunately it is beyond my knowledge so I have no idea how to solve that.

**Comment by richard67** [comment]
I'm just preparing a PR to solve this issue. Stay tuned.

**Comment by richard67** [comment]
Please test PR #28135

**Comment by richard67** [comment]
Closing as having PR. Feel free to re-open if you think my PR doesn't solve this issue or if it turns out to be wrong for some other reason
