### ISSUE TITLE
php-update 7.1.31 > 7.2.21: Warning, Error

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#26116]
### Steps to reproduce the issue
After php-update 7.1.31 > 7.2.21 get no backend-login but:

```"Warning: mysqli_errno() expects parameter 1 to be mysqli, boolean given in /mnt/data/vhosts/casite-1127733.cloudaccess.net/httpdocs/libraries/joomla/database/driver/mysqli.php on line 992```
```Warning: mysqli_error() expects parameter 1 to be mysqli, boolean given in /mnt/data/vhosts/casite-1127733.cloudaccess.net/httpdocs/libraries/joomla/database/driver/mysqli.php on line 1004```
```Error: Could not connect to MySQL server.: Warning: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /tmp) in /mnt/data/vhosts/casite-1127733.cloudaccess.net/httpdocs/libraries/joomla/session/handler/native.php on line 194"```
### System Information
Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-cll-lve
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.31
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.12-dev Development [ Amani ] 12-August-2019 17:15 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by SharkyKZ** [comment]
This could be caused by missing PHP extensions.

**Comment by wojsmol** [comment]
@franz-wohlkoenig Error: Could not connect to MySQL server` can be caused by server-side issue as pointed by @SharkyKZ .

**Comment by mbabker** [comment]
> This could be caused by missing PHP extensions.

Doubtful, the MySQLi driver won't even attempt to connect if `ext/mysqli` isn't installed.  The first two errors clearly indicate that a connection was opened because there is nothing in the database API that reaches those two lines of the MySQLi driver without it, so you can rule out the incorrect PHP configuration issue for now.

To get to that specific set of PHP errors, the `$connection` property of `JDatabaseDriverMysqli` has to somehow be getting reset to a boolean value [after initially connecting to the database](https://github.com/joomla/joomla-cms/blob/00cd97530ed22a2c9bb94c0c3fea88cbfc056e9f/libraries/joomla/database/driver/mysqli.php#L166-L174).

To do anything meaningful with this report, at a minimum a full stack trace will need to be provided or a consistent reproduction scenario created.  Just switching the PHP version on a shared hosting server isn't a reliable reproduction scenario (as in a properly tested API, a reproduction scenario would be something you can write a PHPUnit test case for to prevent regressions).

**Comment by ghost** [comment]
Thanks guys for comment. It happend on a j3-testsite. Will install fresh and look what happens.

**Comment by kahikatea** [comment]
Hi franz-wohlkoenig,

Did you ever figure this out? I am having exactly this issue on the same hosting server.

regards,
Allan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26116">issues.joomla.org/tracker/joomla-cms/26116</a>.</sub>
