### ISSUE TITLE
[4.0] backend button different

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#26122]
### What needs to be fixed
For me it is har because everywhere different buttons and color
plus button
<img width="99" alt="grafik" src="https://user-images.githubusercontent.com/43232309/64078110-12fb3a00-ccd7-11e9-8431-843dd2396455.png">
<img width="106" alt="grafik" src="https://user-images.githubusercontent.com/43232309/64078112-1b537500-ccd7-11e9-8358-35b93d3a4819.png">
<img width="173" alt="grafik" src="https://user-images.githubusercontent.com/43232309/64078118-25757380-ccd7-11e9-87dd-2db1e88ef13b.png">
<img width="62" alt="grafik" src="https://user-images.githubusercontent.com/43232309/64078137-41791500-ccd7-11e9-99ff-c566635a4c4f.png">

install button

<img width="261" alt="grafik" src="https://user-images.githubusercontent.com/43232309/64078176-a46aac00-ccd7-11e9-8881-f25e29eb48b1.png">
<img width="185" alt="grafik" src="https://user-images.githubusercontent.com/43232309/64078179-acc2e700-ccd7-11e9-9e65-3f5f38180651.png">

### Why this should be fixed
I think buttons should be looking very similar so you understand it is button, everywhere is a diferente.

### How would you fix it
Make overview of buttons in Joomla, style and put back again

**Comment by Quy** [comment]
Duplicate #26075?

**Comment by ghost** [comment]
isn't this the same #26075

**Comment by B3nito** [comment]
The issue you link is about different class naming as far I get it?

**Comment by Quy** [comment]
Duplicate to me. It has to do with consistent styling of the buttons. See PR #26070 that is for #26075.

**Comment by mbabker** [comment]
To be fair, while the UI should be consistent, the one issue I took with the recent buttons suggestions was it came across as forcing a style for the sake of a consistent style and not always taking practical use into consideration.  So yes, make the buttons consistent, but please approach it with more than “this is how buttons are styled on the toolbar (since that is the dominant use case in the admin template) so the buttons will have this style everywhere no matter what”.

**Comment by B3nito** [comment]
yes and we need at least same color using

**Comment by Quy** [comment]
Duplicate
