### ISSUE TITLE
[4.0] system-tests-mysql failing for missing html element

### ISSUE THREAD

**Issue by eXsiLe95** [joomla/joomla-cms#26131]
When checking [PR 19300](https://github.com/joomla/joomla-cms/pull/19300 "PR 19300"), I noticed that `continuous-integration/drone/pr` failed. In detail, `system-tests-mysql` failed when looking for an html element with selector `h1.page-title` while trying to log in as administrator. 

### Steps to reproduce the issue

* Go to `<your joomla 4.0-dev installation>/administrator/index.php`
* Search for a html element that matches selector `h1.page-title`

### Expected result

* (At least) An element is found

### Actual result

* There is no such element

### System information (as much as possible)

* Fresh Joomla! 4.0-dev Installation from Git (Commit 6e3c348b6f2401d35fa179ffeae540dd1fd8edf6)
* PHP 7.2.19-0ubuntu0.19.04.2
* MySQL 5.7.27-0ubuntu0.19.04.1
* Apache/2.4.38 (Ubuntu)
* Brave Browser Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

### Additional comments

I'm seeing if I can create a PR to this issue

#### Screenshot:

![screen shot 2019-09-02 at 09 58 03](https://issues.joomla.org/uploads/1/1cead0fc02c0ef0939dcce0db1659eb7.png)

#### Original Error Log:

[Original Error Log](https://ci.joomla.org/joomla/joomla-cms/22817/1/23 "Original Error Log")

**Comment by Hackwar** [comment]
The situation is a bit different. The problem is not, that it is looking for a h1 on the login page, but after the login has happened and that h1 is indeed there. Otherwise all our tests would be failing. I've since made updates to the tests which fix the problem and when you update your branch to the latest version of 4.0-dev, you should see the tests pass now. For information: The tests didn't wait properly for effects and JS to finish and thus the browser did not see the elements properly or attach events to buttons before the test script tried to click on it.

**Comment by eXsiLe95** [comment]
I just had this PR updated and the issue is gone - thanks for the explanation! This issue can be closed :)
