### ISSUE TITLE
Textfilter-Settings Own blacklist doesn´t work at CustomFields Type Editor

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#26185]
### Steps to reproduce the issue
1. Set Filters for Joomla! Configuration > Textfilter > Blacklist
   a) Blacklist Filter Elements: p,span
   b) Blacklist Filter Attributes: style

2. User TinyMCE as editor

3. Create CustomField Type "Editor"

4. Fill this text/code into an article:
   <p>This is <span style="color:red;">my text.</span></p>

   a) into the usual Joomla!-article-content-Editor-Field
   b) into our created CustomField-Editor-Field

   SAFE the article

### Expected result
After saving the article we expect the code to be filtered on both Joomla!-article-content-field and CustomField-Editor-Field

Code should look like that:
This is my text.

### Actual result
Code is filtered correctly at Joomla!-article-content-Editor-Field
Code isn´t filtered correctly in CustomField-Editor-Field

No matter which plugin-filter-settings I use at!

### System information (as much as possible)
Joomla! 3.9.11

**Comment by zero-24** [comment]
Ok i can reproduce the problem. The problem is that there seams to be no initial value for the global options.

As a workaround i would suggest to go to the `Fields - Editor` Plugin, change nothing and just hit save. Another workaround could be to set the filter option in the field itself to "Text".

@laoneo @mbabker @HLeithner Do you have any suggestions on how to deal with that kind of issues?

As of now we don't set the initial values to the DB: https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L640

Here:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/libraries/fieldsplugin.php#L180-L185

We loop over the params and the [`use global` ](https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/editor/params/editor.xml#L50) option only works for sure in case we have an global value in the database.

So is the only fix to ship with that default values in the database or did i have overread something?

On a quick look this also does not seam to be limited to editor but should affect all fields that depend on `use default from plugin` settings or any default value that is set in the plugin but not saved yet.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

This issue is still present in joomla 4 and I have created a pull request for it #38617
cc @zero-24
