### ISSUE TITLE
Joomla Help includes a frame with tracking RFC

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#26200]
### What needs to be fixed
In Joomla Backend there is a Menu item Joomla!-Help. It includes the Google Tag manager. I think due to GDPR - at least in Germany it's like that, you have to have a popup informing about the tracking.

<img width="864" alt="grafik" src="https://user-images.githubusercontent.com/828371/64476656-ebeaaf80-d191-11e9-8a51-0884db1f2b0f.png">

### Why this should be fixed
GPPR / DSGVO

### How would you fix it
Put an external link to the docs from there instead of embedding?

**Comment by brianteeman** [comment]
Or simply remove the tags from the help pagrs

**Comment by mbabker** [comment]
1) This belongs moreso on the websites repo than the CMS repo

2) It's the same tracking code on all `joomla.org` pages.  Because, ultimately, that iframe is loading content from `help.joomla.org` (and `docs.joomla.org` also has the GA code in it, so should analytics be removed from there if it is direct linked from the CMS?  I don't see how direct linking versus loading a page in an iframe would get past the "you have analytics on this page called from my Joomla backend" concern).  It would be another argument altogether if it were loading content from your local server and Joomla was forcibly injecting some kind of analytics.  But, feel free to remove it from https://github.com/joomla/help.joomla.org if it's really that bothersome.

**Comment by coolcat-creations** [comment]
With "direct linking" I meant to place an external link to this site instead of embedding it in the backend. Of course you need to inform your visitors anyway about the usage of tracking cookies. Yes.

**Comment by mbabker** [comment]
The docs site still loads analytics though.  So your concern of "Joomla references help information that includes analytics" isn't answered by changing where the link points without removing analytics from the docs site as well.  It's only "embedded in the backend" by loading an iframe so that the user is not required to leave their site while reviewing help content, otherwise the entire help screen system could just be replaced with direct links to the docs site everywhere and the over-engineered docs API HTML parsing system could be decommissioned.

As for the lack of notification about the fact any of the sites have analytics, blame the compliance team who have yet to finalize the system to be used across all subdomains (which would eventually also apply to the help screens), of which I finished the work they asked of me to help get it implemented 9 months ago.  It's not anything unique to the help subdomain.

**Comment by brianteeman** [comment]
Please close this here and open in the correct place https://github.com/joomla/joomla-websites/ as there is nothing that can be done here
