### ISSUE TITLE
[4.0] It is inconvenient (long) to fill out 2 picture fields (4 fields with title) for each article.

### ISSUE THREAD

**Issue by SamusUA** [joomla/joomla-cms#26397]
**It is inconvenient (long) to fill out 2 picture fields (4 fields with title) for each article.**

See image!

With such arrangement of blocks, it is not necessary to fill in two fields of images. Only the top (1) needs to be filled. The bottom field, you need to fill in only if the images are different! I suggest making the bottom field hidden (reduced). This will save a lot of time when creating an article!

![Images](https://user-images.githubusercontent.com/41996277/65457790-080a7400-de55-11e9-8f6c-5a6a3140aa25.jpg)

**Comment by ReLater** [comment]
And how do you want to manage if one article only needs an intro image, the second only a full image, the third different images. I use all variants.

What's about e.g. plugins and layouts that distinguish between intro images and full images and know why?

Additional confusing settings and codes to detect the correct image? Then I would prefer to leave it as it is.

But I think that it should be possible to copy/paste image paths like it's possible in Joomla 3 + JCE Editor. Instead of opening the media manager again to select the same image again. Annoying actions.

**Comment by SamusUA** [comment]
**You are right, Annoying actions -  open media manager twice!**

> And how do you want to manage if one article only needs an intro image, the second only a full image, the third different images. I use all variants.

Very simple!
If you want to insert only the full image, you can insert it directly into the body of the article!

If you want to insert only intro image - insert into the second (initially hidden) block "alternative intro image"!

Variant 2
Make button - [copy image settings]  :).

**Comment by SharkyKZ** [comment]
>If you want to insert only the full image, you can insert it directly into the body of the article!

No, you can't. Images inserted into article's body aren't comparable to intro/full images.

>The bottom field, you need to fill in only if the images are different!

To my understanding, you want to use full image when intro image is not filled in (or other way around). In that case your best bet is making a layout override.

**Comment by SamusUA** [comment]
> **Variant 2
> Make button - [copy image settings] :).**

**Comment by brianteeman** [comment]
This is easily achieved using a template override. No need for something in the core to address your specific case. Can be closed
