### ISSUE TITLE
[4.0] content history broken by workflows

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26595]
### Steps to reproduce the issue
Create an article and save it
Edit the article and change its state from unpublished to published
Use versions to compare the two

### Expected result
Translated row called 
![image](https://user-images.githubusercontent.com/1296369/66784998-e04a8100-eed3-11e9-9854-389f4b8c27c2.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/66784878-919ce700-eed3-11e9-81ef-5fdadf9ef6ac.png)

**Comment by richard67** [comment]
Could be caused by #26295 ? If so: I will make a PR anyway for making com_contenthistory compatible with real null dates, but this can’t be merged before PR’s for nulldates for all other components relevant for content history have been merged.

**Comment by richard67** [comment]
I’ll check this tonight German time and make PR if it is the nulldate thing causing this.

**Comment by brianteeman** [comment]
Completely unrelated - this is nothing to do with dates

**Comment by richard67** [comment]
I see ... well, if you discover for com_contenthistory or somewhere else some issues which **are** or **might be** related to dates, let me know.

**Comment by alikon** [comment]
is this still an issue with the workflow v3?

**Comment by brianteeman** [comment]
Yes it is still a problem. 
![menu](https://user-images.githubusercontent.com/1296369/84536332-878eea80-ace5-11ea-947c-c847d801f51d.gif)

**Comment by brianteeman** [comment]
it looks like the change is not being written to the db until you close the article?

**Comment by bembelimen** [comment]
The problem is how the workflow is implemented. The flow is the following:
1. article gets saved
2. workflow adjust the article based on the given plugins (transition)

Now the history is written in step 1, so it does not get the updated values.

The solution would be either to write the history after execution of the workflow or to update the history entry when transition is through.

**Comment by brianteeman** [comment]
@bembelimen the reason isnt that important. What matters is that without the content history the workflow loses a major bit of functionality. Arguably its more importnat with workflows than before

**Comment by HLeithner** [comment]
OK I looked at it, 2 problems one solution.

As benjamin already said the history is saved before the workflow triggers.
Solution for this, we trigger the history save a secondtime after the workflow finished adding a "version note" -> "Workflow"

Second problem, we can't revert a version and shouldn't if the workflow is active, so solution for this. 
Deactivate the revert button (functionality) in the version history if workflow is active.
It's not possible to revert all workflow plugin actions even if we can revert the stage doesn't mean that the article is in the right state. Like reverting to an stage after a plugin triggered an unrepeatable action.

**Comment by brianteeman** [comment]
> Second problem, we can't revert a version and shouldn't if the workflow is active, so solution for this.

why?

Editor submits a new version. Admin check it and says no so they need to revert to the previous version

**Comment by wilsonge** [comment]
> Editor submits a new version. Admin check it and says no so they need to revert to the previous version

In this case if the article is already published the editor version is also live before admin review. If the article isn't live then state won't have changed. If the state has changed between the new version and the admin publishing then you're reverting multiple versions and potentially yes you wouldn't see a rollback. Potentially I guess if there is a path in workflow to revert the workflow state maybe we should execute it (or else not allow the rollback??) But kinda unsure on that

**Comment by joomdonation** [comment]
Hello

Do we have any plan with this Release Blocker issue? Do we still want to store **Status** and **Featured** of article into version history when workflow is enabled? I just look at it and think that the following might be solution:

- Revert PR https://github.com/joomla/joomla-cms/pull/31518 so that **Status** and **Featured** still be stored into version history.
- Add method **onWorkflowAfterTransition** into **Behaviour - Versionable** plugin (same with other workflow plugins). The purpose of that method is that it can get **Status** and **Featured**  from the workflow and update these values to latest version history of the item being saved

Could that be solution for this issue? I don't have experience with Workflow and it's code, so I could be wrong. Just trying to move forward with the remaining Release Blocker issues.

**Comment by rdeutz** [comment]
@bembelimen can you look at this and share your thoughts please.

**Comment by bembelimen** [comment]
My opinion is still the same: Values managed by the workflow should not be changeable by the versioning. Otherwise you can publish items without having the permission (as transitions).
The correct solution would be to implement a workflow rollback (if needed at all) and not a pseudo solution which works against the whole workflow concept.
This are two worlds: workflow disabled and workflow enabled.
So my opinion is: #31518 is the proper fix and in the future we can enhance it. But again: enabling the workflow is now a decision which is made by the admin and therefore he is changing the world and have new behaviours.

**Comment by joomdonation** [comment]
If so, can we remove Release Blocker label for this issue and move forward?

**Comment by brianteeman** [comment]
Might as well remove versions if workflow is enabled then as by design you are saying they are not compatible with each other

**Comment by brianteeman** [comment]
or document it as a known limitation when working with versions and workkflow

**Comment by joomdonation** [comment]
> or document it as a known limitation when working with versions and workkflow

That could work, I think. We can live with this limitation for now and wait for real life usages feedback. If users ask for a fix , we can re-visit this later.

**Comment by richard67** [comment]
> or document it as a known limitation when working with versions and workkflow

@bembelimen Do you think you can find the time to write such documentation? 😄

**Comment by bembelimen** [comment]
https://docs.joomla.org/J4.x:Workflow#Versioning

**Comment by richard67** [comment]
Thanks @bembelimen .

@brianteeman Is that sufficient to close the issue, or if not, can we at least remove the "Release Blocker" label?

**Comment by brianteeman** [comment]
Thanks @bembelimen 

@richard67 definitely enough for removing release blocker. Would like to see it recorded as a "known issue" somehow if possible

**Comment by richard67** [comment]
@brianteeman Would this be the right place? https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

**Comment by brianteeman** [comment]
Not really for me to say but if I was a new joomla user with no experience of ever using anything other than j4 but just switched on workflow and saw this problem then that would not be the place i would go. But I guess I would see it where @bembelimen wrote it. So maybe just leave it as it is.
