### ISSUE TITLE
Multiple user notes creation

### ISSUE THREAD

**Issue by kishorchate** [joomla/joomla-cms#26649]
### Steps to reproduce the issue
1. Go to manage user
2. click on +Add a Note
3. fill the data user notes form
4. click on save and close button multiple times
5. check the list view

### Expected result
1. only one entry should be allowed to submit at a time

### Actual result
1. Multiple entries are created

**Comment by vlaucht** [comment]
One way to fix this could be adding an additional column to the notes table in the database and save an unique identifier. This way multiple entries of the same note could be avoided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26649">issues.joomla.org/tracker/joomla-cms/26649</a>.</sub>

**Comment by alikon** [comment]
unable to replicate

**Comment by SharkyKZ** [comment]
I can replicate this with other items, e.g. articles.

**Comment by Hackwar** [comment]
I tested this and I can also not replicate this. I did what @kishorchate wrote and rapidly clicked on `Save` and it did not submit the form multiple times. Since we have two people who can't replicate this, the issue is 5 years old and I wouldn't know about other issues reporting about this as well, I'm closing this one. Thank you for reporting.
