### ISSUE TITLE
[4 Alpha 12]Minor Styling Issue: Category separator line should be above Workflows

### ISSUE THREAD

**Issue by Nishtha003** [joomla/joomla-cms#26710]
### Steps to reproduce the issue
In Toggle Menu under **Content** dropdown the separator line should be above Workflows option as per Content Dashboard.

### Expected result
Separator line should be **above** Workflows because in the Content dashboard Workflows is a part of Content Settings along with Fields & Field Groups.
In the dropdown also the options should be divided similarly.

### Actual result
Line is below Workflows.
**See image:** 
![image](https://user-images.githubusercontent.com/45933977/67146103-15285080-f2a5-11e9-8ace-184e140e208e.png)

**Comment by spahno** [comment]
Hey @Nishtha003,
I'm going to fix your issue!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26710">issues.joomla.org/tracker/joomla-cms/26710</a>.</sub>

**Comment by Nishtha003** [comment]
Sure @spahno go ahead!

**Comment by Quy** [comment]
Items in the Content Dashboard are separated with the separator and has nothing to do with grouping. See `Fields` and `Field Groups` where there is a separator between them. This is the expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26710">issues.joomla.org/tracker/joomla-cms/26710</a>.</sub>
