### ISSUE TITLE
[4.0] Recent css changes broke the dashboard

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26741]
As seen in the screenshots below some recent changes have messed up the display

### Quickicons
- Image not centered
- Text too close to image

![image](https://user-images.githubusercontent.com/1296369/67159889-70f4e700-f342-11e9-911f-263302b3fccf.png)

### Add module
- Image not contained in the box
![image](https://user-images.githubusercontent.com/1296369/67159896-823df380-f342-11e9-8e19-b132e781a52d.png)

### Add item
- Icon not contained in box
![image](https://user-images.githubusercontent.com/1296369/67159909-b9aca000-f342-11e9-99cd-7aab92edd5f3.png)

**Comment by Quy** [comment]
PR #26056 is the culprit.

**Comment by infograf768** [comment]
I can solve the icon not contained in box in my RTL patch to come as the error is also present there and does not need a specific rtl override.
I can also solve the position of the add Module icon in the same PR.

The other stuff is a bit more complex.
Text too close to image is in fact due to multiple lines and depends on the window width as the width of the quickicon container changes and not the height...
Centering of the icons themselves is also a bit tricky as we have to differentiate between quickicons icons with a + sign in `<li>` with `quickicon-linkadd` class an the others.

**Comment by infograf768** [comment]
@Quy
Reverting https://github.com/joomla/joomla-cms/pull/26056 solves all indeed (in LTR) except the centering of the Dashboard Add Module icon.
We can solve this last one with
```
.com_cpanel .cpanel-add-module .cpanel-add-module-icon {
    position: absolute;
    top: -0.25rem;  //instead of 0
    left: 12rem;  // instead of 0
    right: 0;
    bottom: 0;
}
```
<img width="464" alt="Screen Shot 2019-10-21 at 09 23 09" src="https://user-images.githubusercontent.com/869724/67184628-730f8200-f3e4-11e9-9cfe-9d582ed1b863.png">

**Comment by Quy** [comment]
Revert the PR.

In `\libraries\src\Toolbar\Button\PopupButton.php`, change `fa fa-square` to `icon-square`. The other icons use `icon-` except for the `Batch` icon.

**Comment by infograf768** [comment]
Doing that now. Will also correct the Dashboard add module stuff at the same time.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/26757
