### ISSUE TITLE
[RFC] - adopt the Sympony Lock Component

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#26812]
We already use the Sympony Console, in the hope to have a more improved CLI  applications
and to prevent multiple executions of a Console Command, i would like to hear your feedback about the adoption of the  symfony/lock  components

https://symfony.com/doc/current/console/lockable_trait.html

**Comment by mbabker** [comment]
To be honest, that particular component is a fair bit of overhead for such a small use case.  If there is more use for it than preventing a single command from being executed concurrently then it’s worth a look but I’d pass if that is the only core case we can come up with (and I say this as someone who has actually tested putting the Lock component to use and ending up abandoning that since it ended up not offering much benefit to our workflows).

**Comment by alikon** [comment]
ok will be reconsidered if and when there will more use case
