### ISSUE TITLE
Edit [4.0]User Notes -> Edit category -> Select image - Unable to see images clearly on change image popup#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26926]
### Steps to reproduce the issue
1. Open existing User Note for edit.
2. Click on the edit option against the category.
3. Go to the option tab.
4. Click on the select button for the image.

### Expected result
The items should clearly visible and should have enough space.

### Actual result
There is no enough space and items are not visible clearly.![screen shot 2019-11-02 at 09 53 33](https://issues.joomla.org/uploads/1/17ecd95171ee446bfe63882ebdcd357d.png)

**Comment by Quy** [comment]
PR #26988 helps with this issue. Go to Users > User Note Categories to manage categories rather than in User Notes.

![26926](https://user-images.githubusercontent.com/368084/68553292-baca6d80-03d4-11ea-86e1-e66216cd4a5a.jpg)



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26926">issues.joomla.org/tracker/joomla-cms/26926</a>.</sub>
