### ISSUE TITLE
[3.9.13]  This is normal ? - Cookies

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#27018]
### Steps to reproduce the issue

Add chrome extension Cookies App.:
 ![screen shot 2019-11-08 at 00 05 44](https://issues.joomla.org/uploads/1/c0ad3ec279340f708d916d4511db3611.jpg)

This extension identifies the cookies of a website, click on the left button above the web.

In the admin Joomla disable the plugin Authentication - Cookie.

### Expected result
No cookies detected

### Actual result
Cookies are active
![screen shot 2019-11-08 at 00 09 01](https://issues.joomla.org/uploads/1/6a416de0c1a87d00dbd25195ede85218.png)

### System information (as much as possible)
Jommla 3.9.13

### Additional comments
In Europe it is mandatory for a user to accept cookies, having to show an unpleasant warning. It is not possible to disable ALL cookies from a Joomla website

**Comment by mbabker** [comment]
That is the session cookie.  It is required for Joomla to function.  Opinions being like certain body parts, depending on who you ask and the mood they are in you will get a different answer as to whether this cookie falls under that mandate.

The plugin you disabled assists with the optional remember me functionality that automatically logs you in when you visit a site and have checked that box.

**Comment by Open2logic** [comment]
European law establishes that if they are necessary cookies from the web, they do not require user acceptance, only additional cookies such as analytics, behavior, etc.
To understand it better, if we deactivate that session cookie, does Joomla not work?

**Comment by brianteeman** [comment]
@mbabker has given the full and correct answer there is nothing further to say

**Comment by HLeithner** [comment]
@Open2logic atm Joomla doesn't work without the session cookie, if you remove it from the browser it will always create a new one and fill up the session table.

Basically in core) the session cookie is only needed if you have from fields with XSS protection or a logged in user. For 3rd party extensions its possible that it needs the session for other things like a shopping basket.

So for a website without login (even with login but logged out) a session is not needed but Joomla core always creates a session.

I'm closing this because there is not more to say except someone wants to check the possibility to remove the session auto creation.
