### ISSUE TITLE
[4.0][backend-template] - fill the gap

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#27039]
### What needs to be fixed

![Control Panel   my4   Administration](https://user-images.githubusercontent.com/181681/68541611-e2541280-03a1-11ea-8982-6a8143bfd02f.png)

**Comment by infograf768** [comment]
We have a separation between quickicon modules and other modules
`<div class="cpanel-modules cpanel-quickicons">`
and below
`<div class="cpanel-modules cpanel"> `

I guess if we did not have these separated divs a non-quickicon module could be displayed among the quickicons ones.
Imho not an issue.

**Comment by alikon** [comment]
i would desire/expect something like this .... without gap
1![Screenshot from 2019-11-10 10-45-56](https://user-images.githubusercontent.com/181681/68542008-593fda00-03a7-11ea-8023-2c539200fde9.png)

**Comment by richard67** [comment]
We could use the free space to display a module showing the static text "Why this gap" ;-) (joking).

**Comment by brianteeman** [comment]
Welcome to the world of alignment

**Comment by wilsonge** [comment]
This is using the CSS Column count stuff. It's going to be nearly impossible to do this properly. Bearing in mind that this is a module area so people can add custom modules at any point.

You're totally right it does look odd (and on my narrower laptop screen even worse than your screenshot because you can't see the module underneath) - but I really don't see an obvious fix without either not using native CSS or something that's going to break as soon as custom modules are added to this area

**Comment by alikon** [comment]
maybe i'm missing something obvious after reading this  https://css-tricks.com/centering-css-complete-guide/#horizontal-multiple-block
so let's close it

**Comment by wilsonge** [comment]
If you think you know how to fix it go for it. For sure it's something that doesn't look as nice as it can. I'm just not aware of anything

**Comment by N6REJ** [comment]
This is a result of using grid.  Anytime your using a masonry layout your going to wind up with uneven column heights.  The standard "fix" is to fill it with whitespace.

**Comment by N6REJ** [comment]
Or are we talking about a placeholder grid?
