### ISSUE TITLE
[4.0] Multilanguage Install

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27059]
Am I correct that in Joomla 4 it is not possible to configure a site as a multilingual site during the install OR to set the language that should be used as the default admin language or the default site language?

I can see that the default language stuff has been removed from the code but the language strings are still present

I can see the code to configure a multilingual site in the languagecontroller.php but its not presented to the user at all

If this is all as intended then I can go ahead and remove the unused code and strings

**Comment by infograf768** [comment]
Multilingual installation is indeed no more possible at J install time. The code is now in the plugin.
But imho we should still improve installation by being able to choose admin and site default  language after installing languages.
This as well as the session lang issue are to be done before beta.

**Comment by brianteeman** [comment]
> Multilingual installation is indeed no more possible at J install time. The code is now in the plugin.

The plugin is called Multilungual Sample Data in a group called sample data. It is **not** intuitive that this will setup your web site easily for a multilingual web site. Perhaps it should be renamed

If it is definitely not going to be in the installer then all the code/strings for it should be removed.

> But imho we should still improve installation by being able to choose admin and site default language after installing languages.

Then there should at least be an issue tracker for it so that someone might possibly write the code

> This as well as the session lang issue are to be done before beta.

Sorry, no idea what this is 

@wilsonge please advise on progressing here. Getting the install workable is far more important than modifying existing code a thousand times just to keep on trend

**Comment by infograf768** [comment]
> The plugin is called Multilungual Sample Data in a group called sample data. It is not intuitive that this will setup your web site easily for a multilingual web site. 

One could say the same about blog sample data. I don’t see that changing its name would change the situation. I am not the one who took the decision to use these plugins instead of what we had before in 3.x.

In any case one can indeed take away the related methods from the helper. They are the same as those in the plugin.

We already have an old issue for the lang session issue and @wilsonge is aware of that.
To test select en-US at install time. Go on installing until you get to install languages. Look at language in source at each stage. en-GB gets loaded instead of en-US.

Concerning default site and admin lang, I will create the issue. Alas the installation code was quite abandoned for many months and its code is extremely complex.

**Comment by wilsonge** [comment]
> We already have an old issue for the lang session issue and @wilsonge is aware of that.

I'm aware but not sure I've seen a GitHub issue for it? It's certainly not tagged with release blocker like it should be. It's only reset after the Joomla install is done and we swap the session over to use database driven sessions rather than the file driven one iirc

> But imho we should still improve installation by being able to choose admin and site default language after installing languages.

I'd agree with this. You shouldn't have to log in in a foreign language (i.e. english). But sample data should be kept in admin only - not as part of the installer

**Comment by infograf768** [comment]
looks l have to create 2 new issues then 🤪

**Comment by infograf768** [comment]
@wilsonge 
See https://issues.joomla.org/tracker/joomla-cms/25130 now marked as release blocker.

**Comment by wilsonge** [comment]
And i've added a release blocker here and we'll use this issue to track being able to set the default site/admin languages in the installer

**Comment by infograf768** [comment]
Choosing default lang issue is here:
https://github.com/joomla/joomla-cms/issues/27087

**Comment by brianteeman** [comment]
Looking into this and I see that the ability to set the default language has _never_ been part of the installer in J4 - oops

**Comment by HLeithner** [comment]
@infograf768 can you look into this and port it from j3?

**Comment by infograf768** [comment]
@HLeithner 
I am afraid j installation for j4 is so different from j3 that I do not have the knowledge to help on this. What I know is that the methods still exist in the model, that’s about all. Same for the session issue.

**Comment by HLeithner** [comment]
ok thanks, hope someone can have a look at it soon.

**Comment by brianteeman** [comment]
I am working on this - hope to have a draft later tody

**Comment by brianteeman** [comment]
Sorry not made much progress on this

**Comment by infograf768** [comment]
3 files are concerned:
installation/src/View/Remove/HtmlView.php
installation/template/js/remove.js
installation/tmpl/remove/default.php

I could here manage to display a specific `defaultLanguages` fieldset

<img width="720" alt="Screen Shot 2020-01-03 at 10 48 04" src="https://user-images.githubusercontent.com/869724/72413534-47e0c880-3770-11ea-8b31-7334ea98f9c1.png">

But remains 3 aspects to solve, so it is totally WIP.

1. getting to the default Languages fieldset after installing languages (it works when I skip directly instead of installing languages)
2. getting that fieldset form task to be submitted (needs some specific code in remove.js, what I have done is not working and I know it )
3. I also have a weird error in the htmlview.php if I follow the way the variables are coded there although it works.

If you like, I can post here my unfinished .diff

**Comment by brianteeman** [comment]
If you could that would be great and then I can try and get i done while on holiday in spain

**Comment by infograf768** [comment]
[defaultlang_wip.diff.zip](https://github.com/joomla/joomla-cms/files/4063755/defaultlang_wip.diff.zip)

**Comment by wilsonge** [comment]
@brianteeman @infograf768 is this https://github.com/joomla/joomla-cms/pull/27951 WIP with notes on what's left to do enough for one of you guys to pick up and finish?

**Comment by brianteeman** [comment]
Its on my todo list for tomorrow

**Comment by brianteeman** [comment]
not really very motivated to work on it - when it will sit there ofr months without tests or comments other than you have an extra space and please fix merge conflicts again - which seems to be the norm for anything that isnt trivial

**Comment by richard67** [comment]
@brianteeman Ping me when you have something which can be tested and I'll promise I'll test and advertise to others. It only can be that I am limited to weekends regarding time and personal power.

**Comment by brianteeman** [comment]
nearly done

**Comment by richard67** [comment]
@brianteeman Can this be closed now as we have PR #28328 ? Or is there something left to be done?

**Comment by infograf768** [comment]
We can safely close this.

**Comment by brianteeman** [comment]
nice to have more than 3 minutes to answer the question

**Comment by richard67** [comment]
Well to me it reads as if it is solved by that PR, but I always prefer to ask an issue's author because it always can be I have missed something when reading. That's why I had asked. Please protest if closing was wrong.
