### ISSUE TITLE
[4.0] Untranslated strings in presets admin menu

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27072]
### Steps to reproduce the issue
Go to Manage > Administrator Modules
Search/edit Admin Menu
Select `Preset > System Dashboard` and Save
View menu sidebar
Select `Preset > Help Dashboard` and Save
View menu sidebar

### Actual result

![system-dashboard](https://user-images.githubusercontent.com/368084/68914477-8d066100-0713-11ea-81fe-4426a90017fa.jpg)

![help-dashboard](https://user-images.githubusercontent.com/368084/68914479-8ed02480-0713-11ea-91de-a40ed6a72c6b.jpg)

**Comment by infograf768** [comment]
To test what happens, use debug lang.

The behavior depends on which page is displayed.
If the page is CPanel, the strings are translated as cpanel.ini is loaded

<img width="518" alt="Screen Shot 2019-11-15 at 08 51 14" src="https://user-images.githubusercontent.com/869724/68926201-3c2f5080-0785-11ea-9fb9-605e0783acad.png">

As soon as another manager page is displayed, they are no more EXCEPT if you copy these strings in the cpanel.sys.ini file.

### Before

<img width="513" alt="Screen Shot 2019-11-15 at 08 51 39" src="https://user-images.githubusercontent.com/869724/68926216-46e9e580-0785-11ea-8198-2c4103f54515.png">

### After
<img width="558" alt="Screen Shot 2019-11-15 at 08 56 45" src="https://user-images.githubusercontent.com/869724/68926475-e7d8a080-0785-11ea-9e42-7bdda095c9c2.png">

There will be no issue when using the content preset for example because the strings are present in mod_menu.ini.

The only good solution I see is to simply move the strings concerned to cpanel.sys.ini

EDIT: looks like it concerns only 6 strings btw.

**Comment by brianteeman** [comment]
> The only good solution I see is to simply move the strings concerned to cpanel.sys.ini

Hasn't that always been the case? If you want strings in menus then they have to be in the sys.ini

**Comment by infograf768** [comment]
> Hasn't that always been the case? If you want strings in menus then they have to be in the sys.ini

Sure, but we never needed any cpanel strings in menus before. So who ever coded that overlooked that aspect (and many others we are trying to solve one after the other).

**Comment by infograf768** [comment]
Will make a patch if nobody does it before.

**Comment by infograf768** [comment]
On it

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/27092

Closing as we have a patch
