### ISSUE TITLE
[stage] Error on `composer install`

### ISSUE THREAD

**Issue by vuchkov** [joomla/joomla-cms#27208]
### Steps to reproduce the issue

1. Create a new folder && enter it.
2. Clone Joomla project [stage]: `git clone git@github.com:joomla/joomla-cms.git .`
3. Start with `composer install`.

### Expected result

- We expect to install Joomla codebase through composer.

### Actual result

```
~/projects/j/3x(staging)$composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/dbunit 1.4.1 -> satisfiable by phpunit/dbunit[1.4.1].
    - phpunit/dbunit 1.4.1 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
  Problem 2
    - Installation request for phpunit/phpunit 4.8.36 -> satisfiable by phpunit/phpunit[4.8.36].
    - phpunit/phpunit 4.8.36 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 3
    - joomla/image 1.5.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - joomla/image 1.5.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - Installation request for joomla/image 1.5.0 -> satisfiable by joomla/image[1.5.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

### System information (as much as possible)

- PHP 7.2.24-0ubuntu0.18.04.1 (cli)
- Composer version 1.9.1

### Additional comments

- There are additional (necessary) composer dependencies.

### Proposed resolution

- Update `composer.json` and `composer.lock` files for the latest stable release [stage].

**Comment by mbabker** [comment]
1) Only in very exceptional circumstances should you actually be running a `composer install` against the 3.x branches.  About the only "good" reasons would be to update the dependencies or to run PHPUnit, but since most folks aren't writing tests in the first place the odds of someone actually needing to run the testing framework are pretty close to nil.

2) The Composer error message tells you exactly what is wrong, you're missing PHP extensions on your platform.  If you're really adamant about running `composer install` for whatever reason (which is not suggested nor supported for really anything but the two reasons I mentioned before, there's a reason the Composer manifest doesn't ship in release packages), use the `--ignore-platform-reqs` flag or install the missing PHP extensions.

**Comment by vuchkov** [comment]
Thank you very much!

Can I ask, do you planning to use (in future) composer and CLI version of Joomla CMS?
I'm ready to participate in a future Composer & CLI dependency repository of Joomla.
Thank you again.

**Comment by alikon** [comment]
take a look at this PR maybe you are interested ..... #21452
