### ISSUE TITLE
[4.0] Create article in a non published category

### ISSUE THREAD

**Issue by Luchen6** [joomla/joomla-cms#27242]
### Steps to reproduce the issue
Create content category with status [unpublished]
Create new article in the newly created category
Save the article

### Expected result
Article is saved

### Actual result
Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeInterface, null given, called in C:\xampp\htdocs\Joomdev\Joomla_4_12\plugins\finder\content\content.php on line 322 

### System information (as much as possible)
Joomla 4-12 beta
Clean installation

**Comment by Quy** [comment]
Thank you for reporting. This is already fixed in the nightly builds. https://developer.joomla.org/nightly-builds.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27242">issues.joomla.org/tracker/joomla-cms/27242</a>.</sub>
