### ISSUE TITLE
[4.0] order of css files

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27261]
### Steps to reproduce the issue
Expand the module position dropdown
![image](https://user-images.githubusercontent.com/1296369/70809055-ef0cc180-1db8-11ea-8bba-988f0ba94fba.png)

### Expected result

This css is loaded
https://github.com/dgrammatiko/joomla-cms/blob/28245843b39e1ec3365dfa33c2b89d2b0e6b185f/administrator/templates/atum/scss/vendor/choicesjs/choices.scss#L24

### Actual result
The css from the vendor is loaded after

![image](https://user-images.githubusercontent.com/1296369/70809421-a6093d00-1db9-11ea-9ebd-5f802e2f0b1c.png)

**Comment by Quy** [comment]
@dgrammatiko

**Comment by dgrammatiko** [comment]
Once https://github.com/jshjohnson/Choices/pull/794 is merged upstream we could just add the preferred z-index before importing their SCSS.

If someone needs to patch this at all costs the `!important` needs to be added at the relevant line (please let's not do that)

**Comment by Scrabble96** [comment]
This is exactly what I was referring to some months ago regarding the z-index of full-screen codemirror: the vendor css opens after the Joomla! core css, rendering the Joomla! css useless without !important added. See my issue https://github.com/joomla/joomla-cms/issues/23512 and closed PR https://github.com/joomla/joomla-cms/pull/23528, neither of which were resolved, but it all hinges on the order in which css is loaded. Surely the order for all css files should be:

1. Vendor css
2. Joomla! core css
3. Template css
4. User css

**Comment by dgrammatiko** [comment]
@Scrabble96 the order of the styles is like that (although I don't really understand what this joomla core css is).
Eg for com_content edit the css should be:
- the layout css
- all the css from each input
- the css from the template

This particular issue is due to the way we **override** the **original** vendor css. I could have just `@include vendor/original.css` and then added all the overrides on top creating unnecessary bloat for the end users to d/l...
Instead we recompiling the src of that scss to our needs but that didn't actually worked out as planned... Small bug, easy fix


PS. The PR upstream is already merged so I guess I need to do the PR to close this...

**Comment by Quy** [comment]
@brianteeman The overlapping is no longer an issue in the nightly build. OK to close?

**Comment by brianteeman** [comment]
closing as solved elsewhere
