### ISSUE TITLE
[3.10] Pre Update checker can't handle extension set update servers

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#27319]
### Steps to reproduce the issue

While fixing this: https://github.com/joomla/joomla-cms/issues/17969 (here: https://github.com/joomla/joomla-cms/pull/27318) i noticed that the Pre Update checker can't handle extension set update servers

### Expected result

The pre update checker can handle extension set update servers

### Actual result

The pre update checker can not handle extension set update servers

### Additional comments

The problem is more or less here: https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/components/com_joomlaupdate/models/default.php#L1518

This method only work correctly with extension update servers (single extension) but not extensionset update servers.

**Comment by richard67** [comment]
@zero-24 Do you have a link to an extensionset update server so we can check and investigate for a possible solution?

**Comment by zero-24** [comment]
You can use this extension as an example: (example: [JUEP für Joomla 3.zip](https://github.com/joomla/joomla-cms/files/3984192/JUEP.fur.Joomla.3.zip))

example updateserver are: https://www.jah-tz.de/downloads/extensions/juep/update.xml

**Comment by richard67** [comment]
Thanks, that helps a lot. Is anybody working on it already?

**Comment by zero-24** [comment]
Not that I'm aware of.

**Comment by richard67** [comment]
@zero-24 I've updated the link in the description to point to the right line of code due to recently merged changes in the same file. Will seee if I can work on this issue.

**Comment by richard67** [comment]
@zero-24 Important question: The build for this issue is "staging" in the issue tracker. But the link in your description is to the file on the 3.10-dev branch. Shall this be fixed in staging or in 3.10-dev?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27319">issues.joomla.org/tracker/joomla-cms/27319</a>.</sub>

**Comment by richard67** [comment]
~~It seems that not only the pre-update checker has problems with extensionset updates.~~

~~When testing with @zero-24 's plugin [JUEP.fur.Joomla.3.zip](https://github.com/joomla/joomla-cms/files/3984192/JUEP.fur.Joomla.3.zip) I've modified the version number in xml and database so that an update should be found for this plugin.~~

~~The plugin has 2 update sites: One with an extensionset xml and another one (sts) with a "normal" xml.~~

~~When the 2nd update site is activated, an update is found, and when it is not activated, no update is found.~~

~~When analysing code of the installer I saw that it seems not to handle extensionset update xml file, but in opposite to the pre-update checker the error is avoided by simply not loading the xml if it is not a "normal" one. The only place which I could find where extensionset is checked is in the FoF library, but this seems not to be used anywhere in 3.10 in the installer.~~

~~So I'm a bit confused now.~~

~~Somewhere extensionset have to be handled correctly for languages and for core updates because the translations update site and the core update site both point to an extensionset xml. But I haven't found the place in code where this is checked (except in the FoF library).~~

~~But for extensions extensionset seems not to be supported if my test was right.~~

~~Does anybody know more about it? @zero-24 Do you have an idea or know who could have one?~~

**Update:** Forget the above. I had to modify the xml files so that there's a target platform version 3.10, then the update was found.

**Comment by richard67** [comment]
@zero-24 Meanwhile it is also clear to me that this issue is for 3.10-dev, because on staging we don't have the pre-update check yet. Could you change the branch in the issue tracker from "staging" to "3.10-dev"? I could do that for you, but I don't like very much to modify other people's issues or PRs without having asked them.

**Comment by richard67** [comment]
PR #27410 is ready. @zero-24 and others please test.

**Comment by richard67** [comment]
Closing as having PR #27410 .
