### ISSUE TITLE
API basic authentication plugin does not allow passwords with spaces

### ISSUE THREAD

**Issue by pjdevries** [joomla/joomla-cms#27372]
### Steps to reproduce the issue
Create a user with a password containing spaces.
Send a valid API request, authenticated by the above mentioned user's name and password.

### Expected result
200 response

### Actual result
403 response

### System information (as much as possible)
Windows 20 + Docker
Apache 2.4.41
PHP 7.3.12
MySQL 5.6.46

**Comment by richard67** [comment]
Joomla version is 4.0-dev, right? The description is missing this information.

I think J3 doesn't have webservices, ut maybe I'm wrong.

**Comment by richard67** [comment]
Closing as there is pull request PR #27373 .

@pjdevries If you have an issue for which you have already a fix you don't need to make an issue and a pull request (PR), it is sufficient to make the PR only. But if you have an issue for which you don't know yet that you have a solution, then of course open an issue. And so or so if there is a PR to solve an issue, the issue can be closed, that's why I'm closing it for you.

This all just for your information, there was nothing wrong.
