### ISSUE TITLE
[4.0] Blog Layout Ordering

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#27478]
### Steps to reproduce the issue

When setting up a Blog Layout, the choice to align by parameters and/or by row or column order is missing in Version 4.  RE: Align by date horizontal vs. Align by Title Vertical.  This option should be restored as selectors vs. "classes."

Why?  How man beginning users 1) know what classes are, and 2) know what class to place where for a desired result.

Can anyone shed light on fixing this issue to restore the options to A) Order by ... and B) Flow by Row or Column options?

**Comment by ankurshr01** [comment]
can I work on this issue?

**Comment by 200MPHMEDIA** [comment]
Have no objection to anyone working on the issue.

 

We are not code capable, so appreciate your help.

 

Joomla! 3 had this option for the Blog Layout, yes?

 

If you refer back to 3, you will find a better configuration of choices for the Category Blog Layout.

 

We cannot figure out “why” the option choices were removed.

 

Understand that “classes” may have been added to configure this, but what beginning user knows anything about classes, let along which class is needed for which layout.

 

Replicating the same options on J! 3 seems to be a wiser course of action for Category Blog Layouts.

**Comment by ReLater** [comment]
There were already requests like yours. The decision was made that J4 will not have your requested settings.

It depends on the CSS "framework" that a template provides which CSS classes the user has to use.

Thus, it's the job of template developers to add a documentation to their templates or provide an additional framework plugin that makes the requested settings possible or to provide ready-to-use menu items overrides for this or that.

Joomla 4 core isn't tied as strictly as Joomla 3 to a specific base CSS system (like BS 2).

(I don't say that I liked this decision concerning classes instead of "settings" that could be "translated" to classes in the background according to template requirements. In a scenario where you use different templates the new approach is annoying for users. On the other hand it has some advantages (Maybe. Depends on the used CSS system.)).

**Comment by 200MPHMEDIA** [comment]
OK, got all that.  Like you, do not agree with that decision to “code up” layouts, which is instinctive of programmers and code guys.

 

They would rather write 100 lines of code vs. clicking on a backend button.

 

Anyway, for the default template, what are the “classes” to enter (and where to do it), to create some sort of flow options.

 

Appreciate your response.  Thanks.

**Comment by ReLater** [comment]
> Anyway, for the default template, what are the “classes” to enter (and where to do it), to create some sort of flow options.

I don't know if there's already a documentation. Maybe @ciar4n can help.

**Comment by ciar4n** [comment]
This is the PR that removed the layout options you speak of.. https://github.com/joomla/joomla-cms/pull/18319

- Classes allow for an unlimited number of options
- Classes allow us to avoid future b/c breaks as they are coupled with the template (not core)
- Original parameters force templates to adhere to a set number of layout options

@ankurshr01 Rather than reverting previous work, it would be more forward-thinking if you implement something like what @mbabker suggests here... https://github.com/joomla/joomla-cms/pull/18319#issuecomment-336637993. This would allow for user-friendly parameters while keeping the benefits of class-based options.

**Comment by web-eau-net** [comment]
This is crazy, the end user is relegated to the background when he should be at the center of the project.

**Comment by ciar4n** [comment]
> This is crazy, the end user is relegated to the background when he should be at the center of the project.

Bootstrap layout options have been replaced with #18319

**Comment by web-eau-net** [comment]
So theses classes will replace the Blog layout parameter in the backend. Ok, thank you. 
Is it functional now? 
How the end user will know wich classes to use here?

**Comment by ciar4n** [comment]
> Is it functionnal now?

Yes this should now be functional.

> How the end user will know wich classes to use here?

Once J4 goes to beta I will write up some docs.

**Comment by web-eau-net** [comment]
Thanks a lot for your answers.

- the CSS classes Boxed and Masonry are ok (good job) but not for the columns :/ 
- thanks for the doc and I really hope that end users will understand that now, they must read a doc first before using Joomla...

**Comment by ReLater** [comment]
> thanks for the doc and I really hope that end users will understand that now, they must read a doc first before using Joomla...

And if you use another template you have to read another doc and if you test serveral templates you have to read several docs and change the classes after each template switch or have to create several menu items for each template and ...

**Comment by web-eau-net** [comment]
It will be very "funny" and "easy" for the end users, they will love this... (or not).
We'll see.

**Comment by ciar4n** [comment]
> the CSS classes Boxed and Masonry are ok (good job) but not for the columns 

If not working for columns could you please create an issue. Thank you.

> And if you use another template you have to read another doc and if you test serveral templates you have to read several docs and change the classes after each template switch or have to create several menu items for each template and ..

What is your point? If you are happy to set a strict number of layout options for the sake of being able to have a dropdown to select from then just revert #18319

**Comment by web-eau-net** [comment]
> > the CSS classes Boxed and Masonry are ok (good job) but not for the columns
> 
> If not working for columns could you please create an issue. Thank you.
> 
Ok, I will 

> > And if you use another template you have to read another doc and if you test serveral templates you have to read several docs and change the classes after each template switch or have to create several menu items for each template and ..
> 
> What is your point? If you are happy to set a strict number of layout options for the sake of being able to have a dropdown to select from then just revert #18319

In fact, you reply to a Joomla pro user who ask you end users questions (your grandmother, my neighbour, the friend of a friend, anyone who uses Joomla without being not familiar at all with Flexbox, CSS Grid...). 
Yes, I can manage these classes and it will be fine for me (because I'm pro) but it will be different for many end users. And Joomla must think to them because they are many.

BTW, thanks for your help and for your hard work for J4 :)

**Comment by bembelimen** [comment]
Closed as we have a draft: #30910

**Comment by brianteeman** [comment]
This release blocker should be re-opened as the referenced PR was closed

**Comment by richard67** [comment]
So we have now issue #32012 and this one here, both release blockers, and both about the blog layouts, only maybe with different idea about what would be the right way to solve it. Isn't that duplicate somehow, or am I missing something? Does it need 2 issues for that?

**Comment by alikon** [comment]
better 1 only
please refer to #32012
