### ISSUE TITLE
[RFC] The Sponsored Contribution Program

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#27708]
### Introduction to the Request for Comment
Maybe GitHub is not the right place for that. But I'd like to receive your comments on this idea that has been around for a while and the best way to proceed on this matter is directly asking the people who directly contribute with code and volunteer time.
Please comment this issue in a honest and polite way. 
The aim of this initiative is to increase the sustainability of Joomla from a development perspective.
This proposal is still in a RFC phase and has not been approved/adopted.

# Sponsored Contribution Program
## The Initiative
Maintaining and evolving one of the leading Open Source Content Management Systems (CMS) is not an easy job and, as in many open source projects, most of the code is developed by a small number of people who are in charge both for the daily maintenance as well as for the product evolution. Being based solely on the volunteer efforts might slow down the technological evolution of the CMS.

The Sponsored Contribution Program allows companies to be more involved and recognized in the project development, directly contributing time of their employees to work on the Joomla project. 

## How it works / Opportunities

The interested company can join the Sponsored Contribution Program paying a small one-time subscription fee (To be defined) and then can select whether to support the development of a brand-new feature (sub-project) or the daily maintenance.

The Sponsors will be listed in the “Sponsored Contribution Program” page on the Joomla.org website.

### New Feature / Sub-Project Funding
One interesting opportunity is to sponsor one specific sub-project (e.g. New Media Manager, Modern Router, Accessible Backend Template, etc.) directly funding the development of such feature. In this case the fund will allow the volunteers to hold one or several code sprints sponsored by the company where they work towards the milestones to develop the feature/sub-project. 
The sub-project will result directly sponsored by the company and the company will get recognition for that.
Generally sub-projects are intended to last in a defined timeframe.
The financial plan will be arranged by the Joomla Team who presented/planned the sub-project. 
The inclusion of a pull request is at the discretion of the development/maintainers team(s).
Sub-Projects are defined by the Production Department according to the Project's roadmap.

#### Benefits for sponsoring companies

- All GitHub Pull Requests related to the subproject will be marked by the label “Sponsored Feature”.
- The Pull Requests on GitHub will include at the end of the description “This sub-project has been sponsored by [COMPANY]” with a link to the company website and a small logo.
- When the sub-project starts, a blog post on a Joomla.org website will be released to introduce the sub-project acknowledging the sponsor with a note, company name, logo and link. 
- When the sub-project is complete and merged to the core, a blog post on a  Joomla.org website will be released to introduce the sub-project acknowledging the sponsor with a note, company name, logo and link. 

### Code Contributions (Sponsored Development Time)

Another opportunity is to allow employees to directly contribute to the Joomla code during their working hours. In this way the Joomla Project will receive the efforts of the sponsor employees as code (maintenance, bugfix, new features) and the sponsor will get recognition for that.
The inclusion of a pull request is at the discretion of the development/maintainers team(s).

#### Benefits for sponsoring companies

- All GitHub Pull Requests submitted by the Sponsor’s employees will be marked by the label “Sponsored Contribution”.
- Each Pull Requests submitted on GitHub by the Sponsor’s employees will include at the end of the description “This PR has been sponsored by [COMPANY]” with a link to the company website and a small logo.
- Sponsor will be acknowledged in the stable release announcement in the Thank you section with the name linked to the sponsor website.
- When the Sponsor will join the “Sponsored Contribution Program”, there will be an announcement on a Joomla.org website mentioning the Sponsor name, link and logo.

**Comment by brianteeman** [comment]
> The aim of this initiative is to increase the sustainability of Joomla from a development perspective.

I would immediately cease all my volunteer contributions. 

You use accessibility as an example. Have you any idea the number of hours that I personally have spent on this. There is no way you could afford that. Nor am I asking for pay or expecting any. I am not asking for my business to be promoted as a sponsor (because ultimately if I am not spending time on joomla I am working on my company timer). 

All that will happen with this proposal is that you will kill all volunteer contributions. Instead of contributing a pull request everyone will just post an issue and sit back and wait to be offered to be paid to do the work.

The correct way to deal with this is to ask those companies that employ developers 

- Do you ask your staff to contribute? 
- Do you encourage your staff to submit their fixes or do you keep them for yourself?
- Do you support your staff to contribute to Joomla by giving them some paid contribution time?
- Do you make a financial contribution to Joomla?

That is what many other open source projects do. But paying developers directly. No thanks. Not for me.

https://lwn.net/Articles/790954/


It really saddens me to see this.

Without the people prepared to "scratch that itch" and do something you will never achieve anything. 

It is very easy for anyone to say that something must be changed. It seems that far too many people think that their involvement stops there. No amount of project management, blogs, meetings or discussions can solve that. The only way you can see change is to roll up your sleeves.

For far too long people invested in the success of Joomla have sat back and watched others do the work. Expecting them to put food on your tables as well as on their own. It's no surprise that a large percentage of those of us who do contribute have at various times suffered burnout and mental health issues.

But unless you stand up, roll up your sleeves and say "what can I do" then that is all it is. A start with no end.

Many, if not the majority, of the people who write the code that you use everyday - do it for love. They have no professional involvement with using Joomla. Yet you all feel entitled to comment, criticise and blame them for your perceived failures in Joomla. 

You want changes but you want someone else to do it.
You want changes but you are not prepared to spend time in testing those changes.
You want changes but you haven't even looked to see that many of them are already ready and waiting for you in Joomla 4
You want the freedom to use, adapt and change Joomla to suit your own needs but you expect someone else to do that for you.
You want free food but then you complain that it's not the type of food you wanted.

**Comment by richard67** [comment]
@brianteeman I couldn’t have said it better. Thank you for your post and the link. I should sleep since 1 hour because have to work tomorrow, but I could not stop reading.

**Comment by mbabker** [comment]
> * The Pull Requests on GitHub will include at the end of the description “This sub-project has been sponsored by [COMPANY]” with a link to the company website and a small logo.

I see the link spam problem I pointed out two years ago never received even a modicum of thought.  What is to stop me from shadow editing every pull request I have made since April 2016, or every abandoned feature proposal I have out there, and adding a "Sponsored by [Happy Dog Web Productions](https://hdwebpros.com)" comment to each of those?  There are zero edit notifications in GitHub, and the odds of someone realizing that this GitHub repository has been turned into a cesspool of backlinks are slim to none.  Are you really promising to invest hours of every day reviewing every change to the issues and pull requests of the over 180 repositories in Joomla's GitHub organizations to police this?

I'm all for finding ways to sponsor contributor time because it is complete BS that a handful of people presently actively work or previously have worked over full time hours for this project without as much as a "thank you for your time".  But turning GitHub into a cesspool of link spam and making joomla.org focus even less on the software (because people still want to turn that into a community funnel, like the software is an afterthought once again) is not one of the more positive ways of rewarding said sponsorship.  Might as well get Google back on the phone for their ad proposal :wink:.

**Comment by alikon** [comment]
why for  the sake of God , they **[COMPANY]** cannot start helping by a little step, 
simply, they **[COMPANY]** can share they employees for let's say 5 hrs/week or whatever they feel comfortable , to simply help in testing the pr's that we currently have **(279)** or solving the issues **(548)** ...  why this simply & silly concept  it is so hard to be adopted.
if they really want to contribute this is the most simply, fast  and welcomed way

**Comment by richard67** [comment]
What @alikon suggests is ok for me. I just don't want a kind of class system with permanently having 2 classes of coders, paid and volunteer.

**Comment by richard67** [comment]
P.S.: What I agree with in Brian's statement is his (and my) impression of the expectation some people have on Joomla and what they are willing to do for it. If only 50% of those people who say in the diverse Glip chats for Forum for the Future stuff how much they love Joomla, or maybe even only 20% would come to GitHub one time in a week and pick up 5 PRs to test, we would not have 288 open PRs.

**Comment by brianteeman** [comment]
For background I can recall at least 3 separate times that we have had contributions as a result of a sponsorship - each time with major issues

1. As soon as the code was delivered the developer and sponsor ceased their involvement leaving Joomla with unmaintainable code that was eventually removed after years of not working.

2. The code was completed after 18 months during which time no one did any work on that area of the code base because someone else was being paid to do it

3. The sponsoring company required a guarantee that the code would be merged

**Comment by rdeutz** [comment]
I am not against paying people for doing work on Joomla! I am against give up control in which direction Joomla! moves.

What is missing in the proposal is, what happened when something a company is working on is not included and the final PR is closed without merging? Do we add a message company X worked on this but is doesn't hit the level of quality we need. 

Instead of looking for a bit of a companies marketing budget, why not make the communities stronger. Invest time in building stronger communities over the globe. In Germany we spend a lot of time to make our community better and we have at the moment a lot of people contributing to the code base. We have had a strong community in the Netherlands, and still have, even if there are more quite as the were in the past. There are more examples and we have to learn from the past. I believe in stronger communities, were people feel good and can work without being in cross fire. This is the key to success.

**Comment by jeckodevelopment** [comment]
Thanks everyone for sharing their feedback on that.
I really appreciate your input.

As mentioned in the beginning, this was an idea that has been around for several months (or years) now and I thought that GH would have been the right place to discuss it and get your inputs and think IF and eventually HOW this could be done.

**Comment by richard67** [comment]
Regardless whether I like this idea or not: I think the spam problem described by @mbabker could be solved by using a separate page and not the PR itself to list the sponsoring companies. Where this page should be and what it should list (just a count of sponsored PRs or projects, or a list of links to the PRs for each company) should be discussed further. The list should be sorted either by manual edit or by a good sorting criteria so that more recent things are shown on top, and if equal bigger number of sponsored PRs or bigger amount is at the top, so companies who have sponsored much but long time ago, or who have sponsored only a little bit are more at the bottom.

For the PRs itself then a label “sponsored” would be enough. (One more label, I am not sure if Michael will like this idea ;-) )

**Comment by jeckodevelopment** [comment]
Just to add some background information about this idea, that's what other projects do:
https://make.wordpress.org/community/2019/01/02/paid-freelance-contributors-the-idea-of-the-wapuu-program 

How WordPress marks Sponsored Contributions: 
- https://profiles.wordpress.org/hristo-sg/
- https://profiles.wordpress.org/amykamala/

Company contributions on Drupal:
https://www.drupal.org/third-grove#projects-supported 
https://www.drupal.org/node/2373279/issue-credits

I can understand the spam issue and thank you for bringing it.
If the sponsored contribution is an idea that can be accepted in this Project, we can work together to find the ways to make it working without spamming our codebase or our repositories.

**Comment by brianteeman** [comment]
Company contributions works a little differently to sponsored contributions as you describe.

Every time I contribute on drupal.org and get a credit I can chose to keep that credit as Brian or I can add the company (perhaps a client) so that the client also gets a credit. Note that credits are given for a lot more than writing the code and they have had a lot of spam as a result which now means that when code is merged the merger has to go through all the contributions and work out who gets credit.

**Comment by brianteeman** [comment]
Should add that with drupal it is more of a "corporate recognition" than a "corporate sponsor". 

_I did this contribution while I was at work for employerA_ 
or 
_I did this contribution while working on a web site for clientA_

Very different to what you propose

**Comment by mbabker** [comment]
@jeckodevelopment Those programs are very different to the idea proposed here which is basically "we will pay Joomla X dollars to be listed as a 'sponsor' for Y work within the project".  The key thing being that companies aren't paying Drupal/Acquia or WordPress/Automattic to be able to "claim" this entitlement.

And the fact of the matter is it shouldn't take some sort of financially beneficial agreement between a sponsor or contributor and OSM, Inc., to be able to acknowledge and recognize contributors, whether it be because the project directly funded someone, a contributor's company paid for their time, or they went the fundraising route (i.e. all of Hannes' PRs where he acknowledged the work came from his fundraising efforts or someone paying contracting time for it).  BTW, has the GDPR FUD calmed down enough that https://github.com/joomla/framework.joomla.org/commit/8b06cd600df6a8f46a0a6d4587a7aa5a31d581b6 can be reverted and https://framework.joomla.org/contributors can once again meaningfully recognize contributors across the Framework repositories, or is it still mandatory to bend over backwards in order to use someone's name and picture as an acknowledgement and recognition of their contributions to Joomla?

**Comment by jeckodevelopment** [comment]
> BTW, has the GDPR FUD calmed down enough that joomla/framework.joomla.org@8b06cd6 can be reverted and https://framework.joomla.org/contributors can once again meaningfully recognize contributors across the Framework repositories, or is it still mandatory to bend over backwards in order to use someone's name and picture as an acknowledgement and recognition of their contributions to Joomla?

we should still have their consent.
I've an idea to have it working

**Comment by mbabker** [comment]
Don't waste your time on it now.  If nobody could decide on a policy over the last 2 years then clearly the status quo wins, which is to do nothing.  Better off just killing the page completely at this point over leaving the "GDPR says Joomla cannot thank you for your contributions" message up.

**Comment by alikon** [comment]
let me amend you a little bit :smile: 

> GDPR says Joomla cannot thank you for your **"free"** contributions, if you were paid then yes

**Comment by uglyeoin** [comment]
Getting more volunteers and more sponsored devs is the general idea here and I like it.  Since Joomla! forbids paying developers, this is the only method.  We could of course allow Joomla to pay developers and then suddenly they sponsor things and Joomla controls it.  So it could go towards testing PRs etc.  Whatever Joomla! wants or needs.  

It feels like everyone is pretty quick to shut this down, but if we work together with the goal of "more code for Joomla!" then we could find a workable solution.  I see no reason why people can't be thanked, I think it's a shame as @mbabker says, not even so much as a thank you.  That's a real shame a lot of people put in a lot of effort.  

That said it seems like we lack volunteers, or have people who are interested but unwilling to contribute code, only opinion.  Which is another question altogether.  I believe we can get them to contribute.

**Comment by davidsteadson** [comment]
> That said it seems like we lack volunteers, or have people who are interested but unwilling to contribute code, only opinion. Which is another question altogether. I believe we can get them to contribute.

OT, but I disagree. I don't think there's a lack of volunteers - there's a lack of efficient use of volunteers and too high turnover. This creates a lack of institutional memory (not helped by a lack of documentation in many instances) so people are (a) constantly having to reinvent the wheel and/or (b) feeling entirely unappreciated for the work they've put in.

Fixing that, of course, may go a way towards _not_ needing to consider paying for development too.

**Comment by brianteeman** [comment]
For reference and to get an idea of how much you would need for even a small feature
https://civicrm.org/make-it-happen

**Comment by uglyeoin** [comment]
> 
> 
> For reference and to get an idea of how much you would need for even a small feature
> https://civicrm.org/make-it-happen

I don't know how they choose those amounts.  However, if that's how much we need then that's how much we need.  If we can do it for less then great.  If it costs more then that's ok because we value our contributors time.  Joomla! is an immense community.  None of those numbers seem very high to me at all when contributed to by a lot of people.  Especially not if combined with volunteers too.

**Comment by jeckodevelopment** [comment]
it all depends on how you want to use funds.
If you spend the money to gather people together for a weekend somewhere to commit on a specific project/goal, then you might need more money than the one reported by Civi, but depends also on how many people you want to put in one room.
If you spend money to "give a stipend" to someone for a specific purpose temporarily, then it's another story, you might need less money (or more, depending on how many people you want to pay), but it's not easy either, especially for Joomla.

The first method has always been the choice of Joomla

**Comment by brianteeman** [comment]
I guess this RFC has run its course

**Comment by alikon** [comment]
sure
