### ISSUE TITLE
[4.0] Ensure language packs can install into the api/language folder

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#27706]
### Steps to reproduce the issue
There are at least two formats

1. A zip with multiple sub-directories e.g. from crowdin where the xml looks like

```
<files>
		<folder type="language" client="site" id="fr-FR">language/fr-FR</folder>
		<folder type="language" client="administrator" id="fr-FR">administrator/language/fr-FR</folder>
</files>
```

2. A package with multiple sub-zips (one per application) - see french 3.9 packs as an example.

```
<file type="language" client="administrator" id="fr-FR">admin_fr-FR.zip</file>
<file type="language" client="site" id="fr-FR">fr-FR.zip</file>
```

### Expected result
Language packs can install api language data

### Actual result
They can't

**Comment by SharkyKZ** [comment]
Crowdin files seem to be broken. Manually made packages work for me though. Discover needs fixing. And some cosmetic adjustments in `com_installer`.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/27711#issuecomment-580136021 for the new language packs format. 

Tested installing with the new format and it does work OK without https://github.com/joomla/joomla-cms/pull/27711 which specially deals with Discover.

Remains to modify crowdin to get the new format when downloading (and com_localise if we can as it is atm broken because of the new files names)

**Comment by zero-24** [comment]
I have just tried it and can confirm that this has been fixed in the meantime. So closing here for now.
