### ISSUE TITLE
[4.0] Highlighted taxonomy illegible

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#27824]
### Steps to reproduce the issue

Use Smart Search in frontend. Use category name as keyword.

### Expected result

Readable text.

### Actual result

![Screenshot_2020-02-06 Smart Search](https://user-images.githubusercontent.com/7325021/73923200-212b3300-48d3-11ea-8c0a-d8a869f1e563.png)

**Comment by infograf768** [comment]
The issue comes from the use of `badge-secondary` and `span.highlight`
the text is white and the highlight is yellow, so no contrast.

Can be solved to get
<img width="1208" alt="Screen Shot 2020-02-06 at 10 45 40" src="https://user-images.githubusercontent.com/869724/73925242-0904e500-48ce-11ea-9eb4-ac4f1ed523f2.png">

By modifying the css to
```
span.highlight {
background-color: #ffffcc;
font-weight: bold;
padding: 1px 4px;
color: #343a40; // color added
}
```
But also, obviously the .badge text is much too small and its padding is not enough.
By modifying the .badge css to use
```
padding: 0.45em 0.8em;
font-size: 85%;
```
we would get
<img width="578" alt="badge" src="https://user-images.githubusercontent.com/869724/73926259-a6144d80-48cf-11ea-8787-cd843551702b.png">

What do you think?

**Comment by infograf768** [comment]
Will make PR later.

**Comment by brianteeman** [comment]
@infograf768 did you forget?

**Comment by infograf768** [comment]
I was concentrated on the damned svg...
Will do tomorrow.

**Comment by brianteeman** [comment]
NP. just shout if not and I can do it

**Comment by infograf768** [comment]
Closing as we have a patch.
https://github.com/joomla/joomla-cms/pull/27914
