### ISSUE TITLE
[4.0] RFC List views too busy

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27876]
The list views are getting busier and busier and for many sites a lot of the information really isnt needed.

I don't want to propose a completely configurable list view as thats just a mess of options. Instead just a really simple Basic/Advanced switch with the default being Basic.

Below is a mockup of what it could look like

### Basic
![image](https://user-images.githubusercontent.com/1296369/74132868-4c699700-4bdf-11ea-89e2-0714d0553e4b.png)

### Advanced
![image](https://user-images.githubusercontent.com/1296369/74132874-4ffd1e00-4bdf-11ea-88ee-3d1cde2cb7fb.png)

**Comment by peteruoi** [comment]
I think it's a nice idea to have customisable list view. However to have a fixed "light" view it's very subjective. Thousand of use cases and it's surely debatable if hits is more important or author or none.
I think that the extra options for everyting it's not as mess as you suggest cause it will be  one time configuration when you build the site and dependable on your needs. (It won't be something like customise the blog view layout per menu for example).
In ideal situations we would need to make it acl dependable but that's not gonna happen till joomla 6. So  I think your idea is really worth it but don't make 2 views but everything configurable (shown or not) and let the user decide with a post install message whether he will go to the list configuration screen and customise it. But let's be clear if this gonna happen it's just that one configuration for all users.

Something to discuss however is whether the default view will be the crowdy or the cleaner. My opinion would be to be with the same as attributes as joomla 3 so that the old users that migrate don't find any differences.

**Comment by brianteeman** [comment]
Sorry for confusion. The colour was a different issue. I will update the screenshot

**Comment by 200MPHMEDIA** [comment]
The "Access" column should be visible and it should be changeable to any ACL level by clicking on the item to change it vs. opening the object and going through several steps to do it.  That way, if a user forgets initially, they can instantly change it in the list view.  J! 3 has that feature.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27876">issues.joomla.org/tracker/joomla-cms/27876</a>.</sub>

**Comment by brianteeman** [comment]
> The "Access" column should be visible

That;s the problem with making a basic/advanced view - it will have to be one persons subjective choice. My subjective choice is that access is not relevant on a regular site so it is in the advanced set.

>  J! 3 has that feature.

Where? I don't see it

**Comment by Fedik** [comment]
I would prefer "review" existing columns/styling, without segmentation to Advanced/Basic/Even more basic/Basic than ever.

From my point of view.

* "Featured" and "Status" take really to much attention. I have no idea what we can do about, in j3 it was icons, but here it not really possible.
* ~"Date created" can be removed.~
* Title column need simplify a bit, drop "Alias" label: do  `Blabla Title (blabla-title-alias)` instead of `Blabla Title. Alias: blabla-title-alias`
* When User open the page a "main attention" need to be on a title, somehow

**Comment by mbabker** [comment]
> * "Date created" can be removed.

For a lot of people (myself included), being able to quickly see created/published date is quite important, especially in organizations where content is routinely being loaded into a website before it's scheduled publication time.  Something you might be able to de-emphasize somehow, but definitely not something that can just go away.

> * Title column need simplify a bit, drop "Alias" label: do  `Blabla Title (blabla-title-alias)` instead of `Blabla Title. Alias: blabla-title-alias`

A better use of the space the alias occupies would be a frontend link to the item.  In the list view context, there are very few places where the alias actually needs to be immediately visible.  In WordPress I quite regularly use the "View" quick link from the backend list views to jump to the corresponding frontend item.

**Comment by Fedik** [comment]
about a created column,  you are right, I have edited my comment :)
alias still useful to have especially when title != alias, and need to find "what the article for this link"

**Comment by brianteeman** [comment]
@fedik That is why/when you would use the advanced view

**Comment by brianteeman** [comment]
@mbabker same comment to you. Use the advanced view for your use case. Basic will not be for everyone. Your use case with the date is not something everyone uses.

**Comment by chmst** [comment]
The user should select, which columns he wants or needs. So everyone can choose his or her preferences. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27876">issues.joomla.org/tracker/joomla-cms/27876</a>.</sub>

**Comment by brianteeman** [comment]
How about 

1. Basic View  (as above)
2. Advanced View 
 - Select all
 - Select individual columns as a checkbox

The code would be a bit more complex but it should satisfy your requests

The only thing would be it would be per list view (ie com_content, com_contact) and not per user as that would start to get really complex and messy. 

There could be a compromise setting similar to the editor setting per user which would be Basic/Advanced where Advanced = the settings made by the site admin in the component

**Comment by peteruoi** [comment]
@brianteeman that is what i was talking about. With this everyone wins. Simplicity for simple cases or new joomla users, Customisation for every use case according to everyone's need. Per list view is more than enough to have such a great small feature in core. (It;s not the perfect sollution someone might say cause there is a case where different user groups would want different view but if we go this road it will be more complex and will not make it..)

Some might argue about some fields in the basic view but as far as everyone can customise it as he wants then there is no problem!

So it sounds perfect!

**Comment by C-Lodder** [comment]
@brianteeman You could do something like this: https://github.com/joomla/40-backend-template/pull/90

**Comment by brianteeman** [comment]
Thanks @C-Lodder I will check that out - I forgot all about it

**Comment by Quy** [comment]
Is this same as #24495?

**Comment by brianteeman** [comment]
possibly. not really enough information there to know what that refers to

**Comment by brianteeman** [comment]
closed see #27956
