### ISSUE TITLE
[4.0] Workflow - confused

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27902]
Can anyone explain this to me
![image](https://user-images.githubusercontent.com/1296369/74320844-414a6e80-4d79-11ea-8fa3-4692aefdb9f2.png)

As you can see we have a column with an icon and text next to it.

From what I can tell the icon represents the status and the text represents the stage as shown here when using a different workflow

![image](https://user-images.githubusercontent.com/1296369/74321145-b61da880-4d79-11ea-90a3-64e83131a1d0.png)

I'm all ok up to this point.

The problem comes with the change select. For both workflows it looks like this

![image](https://user-images.githubusercontent.com/1296369/74321254-dea5a280-4d79-11ea-881f-a09d01444fa4.png)

![image](https://user-images.githubusercontent.com/1296369/74321261-e1a09300-4d79-11ea-8a83-ecb0fd2d21e0.png)

So why does it say **"Published [Published]"**
What is the meaning/significance of this or is it a bug? I was expecting something like this when you have a custom workflow

![image](https://user-images.githubusercontent.com/1296369/74321533-5247af80-4d7a-11ea-875a-f896e3ca8ec7.png)

**Comment by richard67** [comment]
> So why does it say **"Published [Published]"**

Is doesn't say **"Published [Published]"**, it says **"Publish [Published]"**.

First one is the transition, to publish, the second one in brackets is the state after the transition, i.e. it will be published.

**Comment by brianteeman** [comment]
Why the transition and not the stage?

/me confused

**Comment by richard67** [comment]
Sorry typo, in brackets is sta**g**e after transition, not sta**t**e after transition.

So it is "Transition [Stage after that transition]"

**Comment by richard67** [comment]
Why it was made like this you have to ask the inventor ... hope he or she reads and comments.

**Comment by richard67** [comment]
@bembelimen Could you confirm my understanding or corect me if I'm wrong, and explain why it was made like that? I think the reason was because for the "old" system we also used actions, i.e. verbs, and not status, i.e. not adjectives, for the pull down, is that right?

**Comment by brianteeman** [comment]
It's nothing to do with adjectives or verbs. Should it be stage or transition?

**Comment by richard67** [comment]
As I said: "Transition [Stage after that transition]"

**Comment by brianteeman** [comment]
> As I said: "Transition [Stage after that transition]"


Thats not what it is displaying

What we have is 
"Transition [Condition]"

![image](https://user-images.githubusercontent.com/1296369/74340810-8765f900-4d9e-11ea-8cd5-1c6ca30a7d4f.png)

![image](https://user-images.githubusercontent.com/1296369/74340831-9b115f80-4d9e-11ea-9b3e-d86d2bea7bbe.png)

![image](https://user-images.githubusercontent.com/1296369/74340866-ab293f00-4d9e-11ea-9cde-fd0cde6c81f7.png)

**Comment by bembelimen** [comment]
Richard is right, it's "Transition [new condition]". The reason is very easy: you execute transitions (in theory multiple transitions can lead to a stage, so it makes no sense to put in the stage here) and not the stage.

Perhaps I'm wrong here, but the idea was from you Brian? So the user understand the new condition of the item.

**Comment by brianteeman** [comment]
You mean I am right not Richard ;)
It still confuses me that you select something in a list and the selected value is not what is displayed

**Comment by bembelimen** [comment]
Ups yes, sorry, I shouldn't write in the tram...ofc, you're right.

If I remember correctly (and I still fully agree to it), this combination helps people to see, if the article after execution is visible/disabled on the page, to prevent surprises. (Because now you don't see any condition based on the stage name)

**Comment by brianteeman** [comment]
The issue is that the value selected is not the value displayed

**Comment by richard67** [comment]
Let's say I was right on the left side - that there is a transition - and then you were right with the right side - that there is a condition and not a state - but this condition belongs to the state after ttransition, that's why bembelimen said "new condition", so I was not too much wrong with the right hand side.

I think the problem behind it is that you can define states and transitions with names not being as similar as e.g. "Publish [published]". So it might make sense to show both, so you know what action you do /the transition) and what is the result at the end (the new condition).

**Comment by bembelimen** [comment]
You could also have a "neutral" name like: "proofread" but it does not indicate if it's visible on the page (published) or not (unpublished). Probably the confusion comes from reusing the old names?

**Comment by brianteeman** [comment]
Actually it becomes more confusing when using your own names (thats how I spotted it)

For me the main issue is the difference between the selected value and the displayed value. Pretty certain that this fails accessibility rules

**Comment by brianteeman** [comment]
I guess it comes down to - do I need to know what the name of the transition is?

I need to know the stage that the article is in and the condition that means. I don't need to know the name given to the transition - do i?

**Comment by bembelimen** [comment]
Yes you need, because different transitions could go to a stage and you could have a plugin which does something on a transition but does nothing on another one.

**Comment by brianteeman** [comment]
Closed as this is no longer relevant with wfv3 #29235
