### ISSUE TITLE
bad wrong Joomla template bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#27936]
brian just claims that google PageSpeed Insights are completely wrong, but I disagree

#27838 #27934

j 3,9,15, php 7.4.2

copy protostar name it mytemplatecopy and instead of this

... /templates/mytemplatecopy/css/template.css" rel="stylesheet" type="text/css" />
.../templates/mytemplatecopy/css/user.css" rel="stylesheet" type="text/css" />

you get this ugly code

.../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />

Is there an option to get rid ?8e17160b713641b3cc489b29e3405a51 of this ugly joomla template code addition ?

That code protostar template makes joomla site slow as hell. Do google PageSpeed Insights. It slows site by about 3 seconds.

Due to the complex number of closed but unsolved issues of joomla it would be better to test it yourself https://developers.google.com/speed/pagespeed/insights/

Whese tests show how bad horrible joomla template performs with thisfeature not disabled on .../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" /> to claim this?

if moust of 10000 joomla bugs are closed unsolved then it is better to choose wordpress
this is my last comment on that big joomla template bug, if joomla maintainers choose to ignore that bug for 3 years than joomla is really abandonware software.

I liked joomla a lot but it seems its time to move on

**Comment by alikon** [comment]
it has been explained to you more than twice times from different people
please stop to open again and again the same no-isssue
thanks

**Comment by richard67** [comment]
I agree in closing this issue. The 2 main points in it are definitely wrong.

1. You claim protostar to be the problem for slow page speed. Look at the results from my website (unfortunately in German, pagespeed decides about language), which is a pure protostar with a few overrides for colours, and you'll see they are fine. So it is maybe you as the admin of your website doing something wrong? Htaccess or PHP settings, whatever?
![homepage_page-speed](https://user-images.githubusercontent.com/7413183/74584180-aac3ba80-4fcf-11ea-8f2a-2bffc2ee5b0a.png)

2. The checksum as URL parameter on assets (js, css) are common technology on today's websites, to make sure new versions will be applied regardless of older cached version. Just analyse markup of some big popular commercial or public services site and you will see.

**Comment by richard67** [comment]
P.S.: Or other popssible reason for 1st issue with page speed: Maybe you have hundreds of 3rd party plugins installed for this and that fancy purpose, that can also slow down your page ;-)

**Comment by ghost** [comment]
0 - 3rd party plugins installed , this is new site just default joomla

Richard you should test copy protostar name it mytemplatecopy and instead of this

you get this code in your website?

.../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />

**Comment by richard67** [comment]
@Milglius Sure I get this code, and it is pretty fine for me, because this is modern technology standard. Google has no problems with it. When I change CSS, I don't have to clean browser cache to see the results, because the checksum will have changed so for the browser it is a new URL so browser doesn't use old cached stuff. Check markup of your gouvernment's website and I think with a likelyhood of 95% you should see they use this technology, too.

P.S.: It has nothing to do with copying the Porotstar template. You will get the same on the original Protostar.

**Comment by richard67** [comment]
@Milglius One more thing about the "strange" css URLs and SEO: You know every search engine has a cache, whe people can see the cached version of pages in the search results. Imagina what happens if you change content and css of your site so stuff gets indexed and cached again, but it still would use the old css from their cache? So in fact it was the search engines who have required this technology using a version-dependend URL for js and css assets. So why should it not be SEO- friendly?

**Comment by brianteeman** [comment]
Final comment before I ask for this to be locked

It is NOTHING to do with copying the template!!!




````<link href="/cms/templates/protostar/css/template.css?521d15956b4114624c142fbc038a4dfc" rel="stylesheet" />````

**Comment by richard67** [comment]
@brianteeman Thanks for confirming what I said above. Shall I lock it now?

**Comment by richard67** [comment]
@Milglius I will lock this conversation now. Everything related to your "issue" has been explained to you several times, and above you can read all. There is no need to continue with it, you just waste our time and keep us from catching and fixing the real bugs.
