### ISSUE TITLE
[4.0] Sometimes not possible to create items on the fly (UX)

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#27985]
### Steps to reproduce the issue

Create tag titled `One Mississippi`.
When creating articles, try to create tag titled `Two Mississippi`.

### Expected result

Possible to add `Two Mississippi` tag.

### Actual result

Not possible to add `Two Mississippi` tag, `One Mississippi` is always shown and selected.

![mississippis](https://user-images.githubusercontent.com/7325021/74819986-eb8e3d00-5309-11ea-8aca-738ee1854721.png)

**Comment by jwaisner** [comment]
I can confirm this. 

Is it because it is searching for anything that matches the typed text instead of search by exact text?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27985">issues.joomla.org/tracker/joomla-cms/27985</a>.</sub>

**Comment by SharkyKZ** [comment]
I'm OK with the result appearing but it should be possible to add a tag with similar title.

**Comment by brianteeman** [comment]
This works in J3 but not in J4

I suspect therefore it is related to the change from the chzn js to using choices.js
