### ISSUE TITLE
With latest version of Application/Console Package from the Framework breaks CMS Console

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#27997]
### Steps to reproduce the issue
Update the framework to latest application + console versions. All our console code breaks. This is related to how much symfony code we want to reproduce (i.e. the introduction of the application interface causing us to change how things work) and how the input class is used by the console

Fall out of https://github.com/joomla/joomla-cms/pull/26820

**Comment by mbabker** [comment]
You should be mostly OK on Console, https://github.com/joomla-framework/console/compare/7032ec021d1bec2c37e1067b148590a4a7d3ec83...master is the diff from where the lock file says things are at now (the big change is the app handles uncaught Throwables with output instead of relying on an event listener to do it).

Application shouldn't be an issue on its own, it's going to introduce deprecations galore though because of deprecating the Input access as a property.  https://github.com/joomla-framework/application/compare/3d549e0248cd8973f0c5b66fe49f4647c756488d...2.0-dev for the diff.

Combined, with the CMS environment's tight coupling to `Factory::getApplication()->input`, that's where you start running into problems.  Even this shouldn't prevent upgrading the Console package to current version, it's already unaware of the `Joomla\Input\Input` class anyway and as long as `Joomla\Application\AbstractApplication` is at a version where it is input aware then nothing will be terribly broken.

Because of this issue, OAuth1 and OAuth2 shouldn't be updated because they were modified to use the interfaces, see https://github.com/joomla-framework/oauth1/compare/36da2b80c5e525a724e59a2c54515fdedca90bd1...2.0-dev and https://github.com/joomla-framework/oauth2/compare/98ff49808169523339cc8fd072aec9fe8c5f892b...2.0-dev

From #27996 the only other questionable update is the Event package if `Joomla\Event\DelegatingDispatcher` is in use anywhere (which, it shouldn't be).  Everything else should be safe per SemVer and defined version constraints.

**Comment by wilsonge** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/26820
