### ISSUE TITLE
contact component not scalable

### ISSUE THREAD

**Issue by olijens** [joomla/joomla-cms#28074]
### Steps to reproduce the issue
Set up a few thousand contacts (we manually uploaded 34k contacts through the database, not the web interface).
Go to the page of the contacts, select a single contact

### Expected result
The single contact shows up.

### Actual result
The application hangs and times out.

### System information (as much as possible)
Reproduced on two different machines. One Ubuntu 18.04 virtual machine with 8 GB memory, PHP memory of 2 GB, apache2, php 7.1. The other is Debian 10 with 8 GB memory, PHP memory of 2 GB, apache2 and php 7.3.

### Additional comments
I traced this down to a for loop in htdocs/component/com_contact/model/category.php, function getItems(). When asking for a single item the model still fetches all items and loops through them causing the hang.

**Comment by zero-24** [comment]
Hi @olijens please check and test: https://github.com/joomla/joomla-cms/pull/28077

**Comment by olijens** [comment]
Hi @zero-24 , I saw it and checked in my local environment. Works fine but I am a little worried that this leaves the $contacts variable unset and it is used later on in the method. Like in line 287 then an if check is using the $contacts variable and in other places inside this method. Perhaps it would be proper to address this?

**Comment by joomdonation** [comment]
@olijens My comment https://github.com/joomla/joomla-cms/pull/28077#discussion_r383919535 should address your concern

However, with that PR, the issue will only be shorted if you choose to not **Show Contact List**. If you set that parameter to Yes, the original issue will still happens. Maybe we should limit number of contacts instead of loading all like how it's at the moment.

But at least the PR will solve your issue for now .
