### ISSUE TITLE
[4.0] Outdated dependency - chosen-js

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28154]
Expected version: 1.8.7
Actual version: 1.6.2

**Comment by brianteeman** [comment]
This one is intentional

**Comment by C-Lodder** [comment]
Why would it be intentional?

**Comment by brianteeman** [comment]
Because they broke BC iirc

**Comment by wilsonge** [comment]
We can probably try and figure out an upgrade path - given chosen itself looks like it's about to die https://github.com/harvesthq/chosen/commit/91041bc9dd6867f9a1668050a1b092d92027f13b

**Comment by C-Lodder** [comment]
I thought Chosen was replaced with Choices/Awesomplete?
Is is still being used in certain places?

**Comment by wilsonge** [comment]
As far as I know it's not used anymore in core. But it never got removed after choices got added - and as the api's in php for the two methods are fairly different - It's probably one of those things that will stay there forever for the upgrade path but as deprecated method

EDIT: Did a quick search and there's one place left in com_privacy in the frontend (looks like an oversight rather than intentional) - plus an unused-in-core deprecated tags field method.

**Comment by Fedik** [comment]
hm maybe we can find a way to drop it somehow? not really much fun to keep this legacy for long,
it would be known b.c. break

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/28247 Chosen got dropped from the view as expected

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/28354
