### ISSUE TITLE
Blog layout settings missing #columns

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#28325]
### Steps to reproduce the issue
Create a new menuitem og the type Category blog. Under the tab Blog Layout, the setting #columns is missing. It is there in J3.x

### Expected result
Possibility to set #columns on Category blog

**Comment by GCLW** [comment]
I believe it was intentionally removed https://issues.joomla.org/tracker/joomla-cms/25939<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28325">issues.joomla.org/tracker/joomla-cms/28325</a>.</sub>

**Comment by Quy** [comment]
See #21106 for discussion.

**Comment by jwaisner** [comment]
The last bit of this was removed in #22840 . Closing as this is now expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28325">issues.joomla.org/tracker/joomla-cms/28325</a>.</sub>
