### ISSUE TITLE
custom module properties not accessible to oncontentprepare event

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#28449]
### Steps to reproduce the issue

Create a custom module which requires plugin prepared content such as {myplugin dosomething}. Enable PrepareContent in the plugin.

### Expected result

I expect onContentPrepare() to be passed the module object in the same way that it is passed an article object.

### Actual result

onContentPrepare() is passed an StdClass object with a text property containing the module text. There is no other information about the module properties - such as the ID. For an article all the information I require is in the object.

**Comment by Hackwar** [comment]
Thank you for reporting this to the project and sorry that it took so long to respond to you. We've been discussing this issue in the maintainers chat and we agree that the event itself is not good, since it is too generalised. However due to backwards compatibility, we wont get out of this anymore. At the same time, the event is used the way it is expected and thus we wont be changing anything here. Maybe your solution would be to react to `onRenderModule`? Since we can't change this, I'm closing this issue.
