### ISSUE TITLE
[Feature] Zapier integration

### ISSUE THREAD

**Issue by solracsf** [joomla/joomla-cms#28538]
### Is your feature request related to a problem? Please describe.

Do some automation just like we do with Wordpress or Drupal
https://zapier.com/apps/wordpress
https://zapier.com/apps/drupal

### Describe the solution you'd like

Integration with Zapier ecosystem and connect Joomla with more than 2000+ apps.
https://zapier.com/apps/joomla
https://zapier.com/platform

**Comment by brianteeman** [comment]
I am flagging this feature request as for joomla 4 for two reasons
1. We are not adding new features in J3
2. From my quick read of zapier it would require joomla 4

Having said that this is not something that would be added to joomla. It is something that is added to zapier so I am _not really sure_ that this is the correct place.

I suggest that you contact the Production Department lead @marcodings to discuss this further.

**Comment by infograf768** [comment]
hmm
https://zapier.com/platform/tos

**Comment by solracsf** [comment]
I understand your concerns but i'm actually using zapier with a big Wordpress website and the ability to connect it with 7 of our External apps without any external module/plugin is a big advantage.

This is why we actually recommend every new big project to rely on CMS or frameworks connected with Zapier and are actually migrating one J3 website to Drupal. The time and money saved with Zapier is a big win for both agency and customers.

Nowadays being an isolated CMS without external connections, either by a clic and point system like Zapier or internal features without external modules is a non-sense IMHO.

External modules means rely on poor updates/features, poor support and also security concerns.

This is why this feature requests exists. ☺️

**Comment by mbabker** [comment]
You do realize the Drupal and WordPress integrations rely on those same "external modules" that are by your own definition poorly supported and introduce security concerns?  None of those integration points (at least in the case of WordPress) are built right into the platform, and to my knowledge neither Acquia nor Automattic are the contributors behind those integrations.

All Joomla needs to do is expose an API.  4.0 does that.  Joomla doesn't need to get in the business of writing more integrations for third party platforms when it barely has the resources to write integrations for its only first party platform.

**Comment by alikon** [comment]
thank you @mbabker to share some more light on this

so if someone from the Zapier platform or from any user interested on this please contact our  Production Department lead @marcodings

**Comment by natecovington** [comment]
> thank you @mbabker to share some more light on this
> 
> so if someone from the Zapier platform or from any user interested on this please contact our Production Department lead @marcodings

I'm interested in (co-?) sponsoring an official Zapier / Joomla app:
https://zapier.com/apps/joomla/integrations

I just need it to be able to create articles in Joomla based on "triggers" in the Zapier ecosystem.  I think this would be great for the overall Joomla community, because right now it looks like I would need a Joomla 4 site and manually setup "webhooks" to make this work.  I am looking for a Joomla extension that I can install in my /administrator dashboard and log into Zapier to finish authenticating and configuring the 'Zaps', filling in the fields for the Joomla article, intro text, image, author, etc.

It looks like someone would need to reach out to Zapier from the an official @joomla.org mailbox so they can make it an official App, otherwise I'd only be able to create this as a private app.  It also looks like @marcodings has passed away so I'm not sure who to contact about this now.  

Hopefully someone at Joomla.org can go through the "New App" process at Zapier:
https://developer.zapier.com/app/new

Then we can make it a public-facing Zap integration...

Hopefully this is right place & method for doing this.  Let me know!

**Comment by webgras** [comment]
I just came on this issue. As I am the current production department coordinator of Joomla, I could reach out to Zapier from an official e-Mail-address. 
@natecovington if you are still interested and want to support here, please contact me directly. Thanks!

**Comment by natecovington** [comment]
> I just came on this issue. As I am the current production department coordinator of Joomla, I could reach out to Zapier from an official e-Mail-address. @natecovington if you are still interested and want to support here, please contact me directly. Thanks!

Yes!  I'm interested, but I'm not sure how to contact you directly, other than this.  My email is natecovington@gmail.com if that works better
