### ISSUE TITLE
[4.0] Warning when moving categories in batch

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28578]
### Steps to reproduce the issue
Make a tree of categories. Move and copy these categories. It is possible to make wrong moves, then a warning appears like this one.

![screen shot 2020-04-04 at 21 07 11](https://issues.joomla.org/uploads/1/fd4917f6e67b3e386d8f949800aa3a72.jpg)

### Expected result
The warning should be informative for the user. 

### Actual result
For non-developers, the warning looks harsh.

**Comment by Quy** [comment]
Please test PR #20943 for J3

**Comment by richard67** [comment]
@Quy Not related, or only indirectly. Here it is just the text of the warning which is an issue.

**Comment by richard67** [comment]
Maybe I'm too much a developer, because to me the message is very clear.

**Comment by Quy** [comment]
It might be related in that it may fix the issue to not get the error message.

**Comment by richard67** [comment]
Well, it might be that I got this issue wrong.

**Comment by chmst** [comment]
I think the error message itself is necessary, but the message could be less "development".  Something like "Moving the category to this place is not possble".

**Comment by mbabker** [comment]
This is why it's a bad idea for errors to go uncaught throughout the system and them eventually get shown to all end users.  This is the type of error message that is appropriate for debugging at a development level, but this is also the same type of error that should be getting caught in the component MVC and being transformed into something more appropriate for end user display.  The right fix is not to "dumb down" Exception messages because they might get shown to an end user who isn't the intended audience.

**Comment by richard67** [comment]
Agree.

**Comment by chmst** [comment]
In J4 no longer valid.
