### ISSUE TITLE
[4.0] Plugin quick icon doesn't display in icon position in backend

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#28583]
### Steps to reproduce the issue

On Joomla! 4.0 updated with last changes.
Publish a third party plugin in icon position in backend, the plugin doesn't appear :

![image](https://user-images.githubusercontent.com/876395/78501730-461a1600-775d-11ea-9787-01b40c72d3c3.png)

### Expected result

The plugin should be displayed in icon module position

### Actual result

See screenshot above

### System information (as much as possible)

Php 7.3.16, MySQL 5.7.26

The third party quick icon plugin is this one  : https://github.com/Kunena/Kunena-Forum/tree/6.0-install/src/plugins/plg_quickicon_kunena

**Comment by brianteeman** [comment]
It should be displayed in a  group called 3rd party ....

Look at how akeebabackup does it

**Comment by brianteeman** [comment]
Might be related to the bug you reported in #28582

**Comment by 810** [comment]
We want our plugin to be showed on the Update Checks, because its a plugin that is checking the component version. So it should be placed on "MOD_QUICKICON_MAINTENANCE" group.

Its not a fixed quick link to the backend component.

**Comment by brianteeman** [comment]
As far as I am aware that is not possible as the code was written so that anything non core went in the 3rd party module but you would need to check with @hackwar who wrote it

**Comment by xillibit** [comment]
> 
> 
> It should be displayed in a group called 3rd party ....
> 
> Look at how akeebabackup does it

You mean like here : https://github.com/joomla/backend-template/pull/279#issuecomment-499411761 ? I didn't know that was a third party position

**Comment by ReLater** [comment]
When I try Group "update_quickicon" (not "mod_quickicon)" in plugin settings it's displayed inside "Update Checks" module.

**Comment by brianteeman** [comment]
@xillibit yes thats what I meant

**Comment by ReLater** [comment]
I don't understand the issue. I simply changed the Group setting in the plugin and see it (a bit "destroyed" in the image because I had to remove the Kunena class dependencies):

![06-04-_2020_13-27-24](https://user-images.githubusercontent.com/20780646/78554034-a4e99900-780a-11ea-9a79-4d7c8ca32442.jpg)

When I read post 1 that's what was asked for.

**Comment by 810** [comment]
i have now set it to "update_quickicon" and thats working. Thats is good, but there should be written somewhere on the docs that you need to set it to that, that only core plugins can use  "MOD_QUICKICON_MAINTENANCE".

For the removing Kunena class dependencies, we are checking why the system - kunena plugin wouldn't be enabled by default on install.

**Comment by ReLater** [comment]
> For the removing Kunena class dependencies, we are checking why the system - kunena plugin wouldn't be enabled by default on install.

A misunderstanding, I think. Because I only installed the plugin and not the whole package. I got messages because of missing Kunena classes in `use` lines. Therefore I removed them and class calls  inside plugin code.

(I found no build instructions for the 6.0 package and a ZIP of folder /src/ could not be installed).

**Comment by xillibit** [comment]
I close the issue because it has been fixed in kunena
