### ISSUE TITLE
[RFC] Module chromes

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28807]
There are currently 4 default module chromes in Joomla's core:

> \layouts\chromes

- outline
- none
- html5
- table

What I'm proposing Joomla has a single, default chrome, without any styling.
So basically remove `outline`, `table` and `html5`

Chromes should derive from the template

**Comment by Quy** [comment]
Related #20864?

**Comment by brianteeman** [comment]
What is the benefit?

**Comment by Bakual** [comment]
First: This chromes by no means are "default" chromes. The default for any moduleposition is specified by the template. Those are "system" chromes.

Personally I don't see anything wrong with having some simple chromes shipped by the CMS which can be used by templates and users so not everyone needs to reinvent the wheel.

The "outline" one is actually used for the template position preview.
The "html5" is actively used by cassiopeia.
The table one seems like something you shouldn't use nowadays. That one could maybe removed with 4.0.

**Comment by C-Lodder** [comment]
@brianteeman because the design should be dictated by the template. `none` or `table` are not used in core. So I ask myself, why would Joomla need to ship something it doesn't use in core? It's just more unecessary maintenance.

@bakual Fair enough with the `outline` chrome. `html5` is only used by the banner. `cardGrey` and `default` are exactly the same other than the `card-grey` class, so the `default` chrome can be updated and used by the banner

**Comment by brianteeman** [comment]
> @brianteeman because the design should be dictated by the template.

But it still is as the chrome is defined in the template.  These are just generic chromes that a template can use to avoid reinventing the wheel. Or am I missing something?

**Comment by C-Lodder** [comment]
The chrome is defined in the template, but the code belongs to the core. Two of them aren't used by core and one of them is unecessary.

> because the design should be dictated by the template.

By this I was trying to say that chromes code should belong to the template, not the CMS

**Comment by coolcat-creations** [comment]
@C-Lodder I agree to what you say, but what if someone is using the existing chromes in the (old) template - is there already a doc how to migrate a J3 Template to a J4 Template? If we need to work anyway on the templates to make it work with J4 we could provide the chromes in the docs as a download so that the template person can include it if needed...

**Comment by Bakual** [comment]
Honestly, the files really don't hurt anyone, it's not like it's much to maintain in there.
Two of them (none and outline) are still needed anyway.
One could discuss about table.

> html5 is only used by the banner. cardGrey and default are exactly the same other than the card-grey class, so the default chrome can be updated and used by the banner

If `default` is the same, why even use a custom one? Just use `html5` instead. That's what I would do in my template so I don't have to maintain it myself. That's why the system chromes are there to begin with.

**Comment by C-Lodder** [comment]
> it's not like it's much to maintain in there.

`html5` was still using BS2 until yesterday, but ok.

Closing
