### ISSUE TITLE
[4.0] Bootstrap sizing don't work in module paramaters

### ISSUE THREAD

**Issue by web-eau-net** [joomla/joomla-cms#28820]
### Steps to reproduce the issue
1. setup a Bootstrap size in the advanced tab of a module

### Expected result
Display ![screen shot 2020-04-27 at 05 59 44](https://issues.joomla.org/uploads/1/833fe137815db56490aa891806b8fcd0.jpg)a module according to the Bootstrap size selected in the advanced tab

### Actual result
Nothing happen because the Bootstrap class generated is wrong (see file attached)

### System information (as much as possible)
Joomla 4.0 Beta 1 Development

### Additional comments
Issue on frontend and backend

**Comment by micker** [comment]
same as https://github.com/joomla/joomla-cms/issues/25952
thanks for confirm this issue

**Comment by Bakual** [comment]
It could be fixed in the module chrome. But maybe the parameter is better removed as it is tied to Bootstrap and not every template uses Bootstrap.

A year ago I thought about allowing custom parameters for module chromes (see https://github.com/joomla/joomla-cms/pull/23577) which would allow templates to provide own ways of implementing similar functionality. But it's a bit tricky to do 😄

**Comment by micker** [comment]
we can't change params to be compatible with css grid ??
we lose some important feature for website integrator, joomla already propose some godd option for easy configuration ... without this we need code, overide or hardcoding

**Comment by C-Lodder** [comment]
seems @wilsonge fixed the inorrect class being used: https://github.com/joomla/joomla-cms/commit/a5ca9b25101e38423b39e8672896527df8e2c4f7

**Comment by web-eau-net** [comment]
Thank you Charlie :) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28820">issues.joomla.org/tracker/joomla-cms/28820</a>.</sub>
