### ISSUE TITLE
[4.0] Media Manager - backend loads in modal

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28842]
### What needs to be fixed
When editing an image in the Media manager Modal and clicking on "Save & close" the whole backend opens in the modal

![grafik](https://user-images.githubusercontent.com/828371/80416940-38c3f780-88d5-11ea-8f76-4e54c6016432.png)

**Comment by brianteeman** [comment]
Confirmed

**Comment by infograf768** [comment]
Confirmed.
Also, internal server error when saving name of file or folder.
![mediamanager](https://user-images.githubusercontent.com/869724/80457365-748bab00-892f-11ea-98ca-eb292aee3d3f.gif)

I chose to add this bug here as there is a possibility that both issues may need working on same files.
If required, will create a specific issue.

**Comment by adj9** [comment]
When you edit an image in modal media manager and click "save and close" the backend is start in modal mode. Confirm gif of @infograf768.
Editing images from the media is not modal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28842">issues.joomla.org/tracker/joomla-cms/28842</a>.</sub>

**Comment by dgrammatiko** [comment]
FWIW this is something the Media Manager Group overlooked when we were working on the Editing part (iirc initially the idea was to not have the editing available in the modal). Anyways it's not extremely hard to fix this but it requires touching a few files. If anyone wants to pick this issue I could guide them otherwise I guess I will have to do the coding myself

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30730
