### ISSUE TITLE
[4.0] RFC - Help Screens - URL and Statistics / Privacy Issue

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28865]
The Help Screens are on another domain than docs but seem to be the docs pages. Can someone explain why the URLs are different?

Also I already noted somewhere else that there is Google Analytics running in this modal which is actually a privacy issue and should be opt-in.

Besides that it would be good to have at least a cookie-less tracking to know which Helping Articles people mostly click and to give them the possibility to provide basic feedback on the docs like "this doc did help / did not help" - if we keep an eye on the stats here we know which areas can use some UX improvements.

<img width="1398" alt="grafik" src="https://user-images.githubusercontent.com/828371/80570685-889cde80-89fb-11ea-90ce-3fd6cb0ca22d.png">

<img width="697" alt="grafik" src="https://user-images.githubusercontent.com/828371/80571049-34462e80-89fc-11ea-8e67-0d2b60b32a60.png">

**Comment by brianteeman** [comment]
Is my memory failing or didn't you raise this before?

**Comment by coolcat-creations** [comment]
Yes I raised it before and I wrote it also above that I raised it before - however I can't find the issue anymore and it's not solved yet...

**Comment by mbabker** [comment]
The help screens are rendered by extracting content out of the Docs wiki through the MediaWiki API, manipulating the HTML a bit to be usable in the context of the iframe or pop out window, and applying basic theming to the resulting content.  To my knowledge there is not an adequate way to iframe or render a similar layout directly from the Docs site.

All .org properties utilize GTM scripts for analytical purposes.  This content is coming from .org, it is not Joomla injecting a tracker into your Joomla installation, and it has served me well a time or two being able to refer to traffic numbers demonstrating the resource’s high use when people talk about trying to change things for the sake of change (it actually individually gets slightly more traffic than the community subdomain).  You are welcome to suggest the removal of analytics as a whole from .org, but I would not encourage a behavior of “this website should not have analytics because it is linked from the Joomla administrative interface”, because that same rule would have to apply to several subdomains, and by the time you removed GTM from those sites about the only things left with analytics are the VEL and Showcase Directory.  On the same note, if the GTM config isn’t set to the anonymous mode for Analytics, that definitely should be fixed.

**Comment by brianteeman** [comment]
Found your previous closed issue here #26200 which was closed by me as it is an external site issue and not for the cms and redirected you to the correct repo where you opened an issue https://github.com/joomla/joomla-websites/issues/1348 which is still open. 

So I am closing this here once again as the other repo is the correct place

**Comment by coolcat-creations** [comment]
Thank you but as it's taking effect in the CMS we need to keep it open here too in my opinion. Otherwise we lose track of this privacy issue that we deliver with Joomla Core. 
Or we have to add a cookie banner in the backend ;-)

**Comment by Hutchy68** [comment]
How is it a privacy issue? What is being tracked and how? Afaik help is just a proxy, period. If it is more and there is tracking going on, how and where?

**Comment by coolcat-creations** [comment]
@Hutchy68 see the Screen I posted- Google Analytics Cookies are set in the help Pop-ups ...

**Comment by Hutchy68** [comment]
I don't even remember when and why that was added, tracking use and abuse? Is there a need for it? Is someone actually looking at that data?

IIRC, Joomla should be using anonymizeIP on all its Tags. Can we easily verify that the Google Analytics cookie and its setup does not include Google’s advertising features?  Then as I understand, it is GDPR compliant, no consent needed.

**Comment by coolcat-creations** [comment]
No in Germany it would be even then not gdpr compliant... in Backend should be no GoogleTracking at all. 
If you display it as an external Link and open the whole docs page then maybe It works because you clearly leave the Backend then, otherwise you have to ask for opt in to gather this statistics.

**Comment by mbabker** [comment]
Given you are the Vice President of Open Source Matters, Inc., you are welcome and encouraged to action https://github.com/joomla/joomla-websites/issues/1419 then which would permanently resolve any issues regarding this matter.
