### ISSUE TITLE
[4.0] Suformfield, modal fields did not open if multiple

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#28953]
### Steps to reproduce the issue
implement subform which includes a modal form
add a filed type which uses the modal, media or user field like
```
<field
 name="test"
 type="subform"
 multiple="true"
 >
  <form>
     <field
          name="text"
          type="user"
      />
  </form>
</field>
```

Click add subform and check if all modals open

### Expected result
Every modal field should open

### Actual result
Only first modal field opens

### System information (as much as possible)
PHP Version | 7.3.14
Joomla! 4.0.0-beta1-dev Development [ Mañana ] 17-October-2019 20:21 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by fatrr** [comment]
The bug seems to be in /media/system/js/fields/joomla-field-subform.(min).js at line 107.
row = row.closest(that.repeatableElement) === that ? row : null;
If you comment or delete thet line it works. but i don't understand the utility of that line at the moment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28953">issues.joomla.org/tracker/joomla-cms/28953</a>.</sub>

**Comment by Quy** [comment]
Duplicate #26711? Do you get the same error in the browser's console?

**Comment by HRIT-Florian** [comment]
@Quy maybe, but these runs into a other and new console error
`this.modal.open is not a function`

**Comment by Quy** [comment]
Please test #30455

**Comment by Quy** [comment]
Please test PR #32624
