### ISSUE TITLE
[RFC] Unique template names or not?

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#28959]
Currently it's possible to install templates with the same name to different clients (site/administrator). I need to know if this is intended or not because there are some issues caused by this. Client isn't taken into account when uninstalling and in 4.0 Atum media files (`media/templates/atum`) would cause a conflict.

**Comment by infograf768** [comment]
Imho, it is an oversight. Should be corrected.

**Comment by brianteeman** [comment]
Agree with @infograf768

**Comment by richard67** [comment]
Agree, too.

**Comment by mbabker** [comment]
If you’re going to require globally unique template names and not unique per application, the same must be done for modules using the same justification.

Personally, I wouldn’t try to force it because of naming conventions used inside the media folder, which is mostly conventionless (the css and js subfolders come from media override support in JHtml but seems that is going away with the web asset API, but nothing mandates base folder names).  You mentioned “some issues”, what are the other issues beyond the name in the media folder?

**Comment by SharkyKZ** [comment]
Nothing that can't be fixed. Just needed to know which way to go. Thanks.
