### ISSUE TITLE
SMTP Connect Failed (Mailcow Server)

### ISSUE THREAD

**Issue by mbh-dev** [joomla/joomla-cms#29136]
### Steps to reproduce the issue

Mail Settings
Send Mail: Yes
Disable Mass Mail: No
From Email: user@domain.tld
From Name: Name
Reply To Email: 
Reply To Name: 
Mailer: SMTP 
Host: mail.domain.tld
SMTP Port: 465
SMTP Security: SSL
SMTP Authentication: Yes 
SMTP Username: user@domain.tld
SMTP Password: ********************************

### Expected result

Test email sent successfully

### Actual result

Error
Test mail could not be sent.

### System information (as much as possible)

Joomla 3.9.18
Mail server located on separate machine

### Additional comments

When trying to connect to Mailcow mail server, via all options possible, Joomla fails.
Mail server is accessible from other CMS (WordPress) and direct connects via email clients, webmail and telnet. No logs on mail server of Joomla even trying to connect to it.

Extremely confused and require assistance, thanks.

I've tried troubleshooting using other forums and posts but none have helped.

**Comment by HLeithner** [comment]
Can you please activate debugging in the global configuration and try again? this should create a log file in `administrator/logs`

**Comment by toivo** [comment]
@mbh-dev please follow in detail the instructions you received yesterday how to debug SMTP mail in your forum topic at https://forum.joomla.org/viewtopic.php?f=708&t=980140.  These problems are usually caused by firewalls at either end or issues with domain names and SSL certificates, rarely with Joomla.  The SMTP transaction log will give us the full account what went on. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29136">issues.joomla.org/tracker/joomla-cms/29136</a>.</sub>

**Comment by brianteeman** [comment]
As there is an active forum thread for this it should be closed here. Thanks

**Comment by mbh-dev** [comment]
Following @HLeithner the error log shows the following:

[24-May-2020 14:07:31 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemOfflajnJoomla3compat has a deprecated constructor in /home/xxxx/public_html/plugins/system/offlajnjoomla3compat/offlajnjoomla3compat.php on line 83
[24-May-2020 14:07:31 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemDojoloader has a deprecated constructor in /home/xxxx/public_html/plugins/system/dojoloader/dojoloader.php on line 41
[24-May-2020 14:07:31 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemOfflajnParams has a deprecated constructor in /home/xxxx/public_html/plugins/system/offlajnparams/offlajnparams.php on line 41

**Comment by toivo** [comment]
@mbh-dev those PHP Deprecated messages come from the third party plugin from Offlajn and they are not related to the SMTP connection issue.  The active forum topic where you just posted new debug information a few minutes ago is the right place to continue.  The issue was closed here four days ago because of that.

**Comment by HLeithner** [comment]
@mbh-dev if you provide an SMTP communication log it would be easier to solve the problem.

**Comment by toivo** [comment]
@HLeithner the SMTP log was provided to the forum topic at https://forum.joomla.org/viewtopic.php?f=708&t=980140#p3605241 and it shows the error "Connection refused (111)" - the ball is in the OP's court.

**Comment by HLeithner** [comment]
@toivo thanks I checked the forum but I missed the smtp log.... and you already answered it.
@mbh-dev I would suggest to change the auth type to STARTTLS and port 25 or 587 and try again.
