### ISSUE TITLE
[4.0] Accessibility settings break "Add module" modal

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29131]
### Steps to reproduce the issue

1. Go to your Atum template settings
2. Enable `Monochrome`, `Highlight Links` or `High Contrast`
3. Go back to the admin dashboard
4. Click the `Add module to the dashboard` button at the bottom

### Expected result

Modal shows

### Actual result

Modal doesn't show and can no longer scroll

**Comment by chmst** [comment]
Which system environment? 
In my environment (Firefox, win10) everything is as expected wen adding new module, scrolling is possible and no errors. ![screen shot 2020-05-18 at 18 24 04](https://issues.joomla.org/uploads/1/f65066de2408b4b57238816d6fe79075.jpg)

What's wrong:  There is no high contrast but this is not in scope here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29131">issues.joomla.org/tracker/joomla-cms/29131</a>.</sub>

**Comment by C-Lodder** [comment]
Win 10, FF (latest) and Chrome (latest)

**Comment by C-Lodder** [comment]
Have you compiled the latest code recently?

**Comment by chmst** [comment]
Yes. But just noticed that it is not on every dashboard, only on the main dashboard.

**Comment by chmst** [comment]
pardon, it was not indended to close this

**Comment by ghost** [comment]
Issue confirmed.

Go to Home Dashboard, where you have to scroll down to reach `Add module to the dashboard` and click:

![Screen Shot 2020-09-23 at 12 34 28](https://user-images.githubusercontent.com/70466955/94001996-95024900-fd99-11ea-9364-3b951e8ad80e.png)

Click on a module:

![Screen Shot 2020-09-23 at 12 34 50](https://user-images.githubusercontent.com/70466955/94002033-a21f3800-fd99-11ea-917d-15c6cb8c30d0.png)

Unable to scroll in the Modal up.

**Comment by brianteeman** [comment]
Not sure when but this appears to have been fixed now. I cannot replicate the scroll issue.

![module](https://user-images.githubusercontent.com/1296369/128629664-394ee1da-bb4d-4efb-9578-6abbb746da41.gif)

**Comment by Quy** [comment]
Reproducible in Chrome.

**Comment by C-Lodder** [comment]
If the a11y classes are added to the `<html>` tag rather than `<body>`, it fixes the issue.

**Comment by jonaskuske** [comment]
The problem:
Modals use fixed positioning with `height: 100%` so that they are as tall as the screen. The height of a fixed element is relative to its containing block, which by default is `<html>`. So normally, the modal is as tall as `<html>`, meaning as tall as the visual viewport. However, some properties such as `transform` make an element act as a containing block for fixed elements. A CSS `filter` shouldn't do this, but due to a bunch of browser bugs, `filter` and other properties that cause a new composite layer also turn elements into containing blocks for fixed elements: https://github.com/w3c/csswg-drafts/issues/400

When `filter` is set on body through an a11y class, suddenly `<body>` is the containing block for the fixed modal. The modal is not as tall as the viewport anymore but as tall as the scrollable area, since `100%` refers to the body now. On pages that are scrollable, meaning `<body>` has a greater height than `<html>`, the modal container will be too tall and the modal positioned off screen.

<p align="center"><img width="400" src="https://user-images.githubusercontent.com/30421456/236025841-77cfd428-accc-48d1-bce3-78eaacc15db5.png"></p>

Applying the a11y classes to `<html>` fixes the problem as @C-Lodder mentioned, since now it is always `<html>` that acts as modals' containing block, no matter if a `filter` is active or not.

**Comment by Quy** [comment]
@C-Lodder I can no longer reproduce now that modals have being replaced with dialogs. Please confirm. Thanks.

**Comment by C-Lodder** [comment]
@Quy Cannot replicate in 4.x or 5.1 anyy longer. Closing
