### ISSUE TITLE
[4.0] Logging yourself of frontend out via backend

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29176]
### Steps to reproduce the issue

1. Login to the **frontend** with a your super user account
2. Login to the **backend** with your super user account
3. On the dashboard, under the `Logged-in Users` module, click the `Log out` button

### Expected result

If the `Log out` button is there, I'd expect myself to be logged out of the frontend.
If you shouldn't be allowed to log yourself out, then the button shouldn't be there in the first place.

**Comment by chmst** [comment]
If I don't miss something then I think that this is expected behaviour.

If it is not a shared session then 
The Super User can cancel his user session in Frontend but remains logged in in the backend. This can be useful (at least I use this in J3)

If it is a shared session then in J4 the user has no button to log out himself in the logged module.


In J3, if it is a shared session, then the super user can cancel the session and log himself out. 
This could be seen as an issue, but in J3,not in J4.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29176">issues.joomla.org/tracker/joomla-cms/29176</a>.</sub>

**Comment by ghost** [comment]
Can´t confirm. Logged in as super user in front- and backend and click in backend on ´logout´-button logs frontend-super user out.

**Comment by Quy** [comment]
Closing as non reproducible.
