### ISSUE TITLE
Memory Exhaustion on PHP 7.4.x

### ISSUE THREAD

**Issue by wharminda** [joomla/joomla-cms#29245]
### Steps to reproduce the issue
Updating Joomla or accessing a pagebuilder gives a memory exhaustion error on PHP 7.4. Changing to PHP 7.2 and it works fine.

PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 2521585 bytes) in /home/sitename/public_html/libraries/src/Document/HtmlDocument.php on line 796

### Expected result
Works as per PHP 7.2

### Actual result
Memory Error

### System information (as much as possible)
PHP Built On 	Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64
Database Type 	mysql
Database Version 	5.5.5-10.3.23-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.4.6
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.9.18 Stable [ Amani ] 21-April-2020 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by wharminda** [comment]
Solved, not a Joomla problem.

**Comment by toivo** [comment]
@wharminda This looks like an issue with the configuration of the web server, rather than Joomla.  Please create a forum account at https://forum.joomla.org.  Create a topic in the 3.x General Questions forum with the details of the error and post also the results from the Forum Post Assistant (FPA), by following the instruction at https://forumpostassistant.github.io/docs/.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29245">issues.joomla.org/tracker/joomla-cms/29245</a>.</sub>
