### ISSUE TITLE
[4.0b1] Fill in or fill out?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29294]
### Steps to reproduce the issue

mess around in safari with the login page to generate this kind of issue

### Expected result

in out in out shake it all about - I dont have all the answers... It just seems weird having one say "fill in" and one say "fill out" 

### Actual result

"Fill out"

"Fill in"

<img width="546" alt="Screenshot 2020-05-30 at 23 39 43" src="https://user-images.githubusercontent.com/400092/83340366-fffdb080-a2ce-11ea-8a0b-87aa50847a14.png">

Maybe the fill "out" is a HTML5 thing?

### System information (as much as possible)

Safari on Mac

### Additional comments

Im thinking this is a "won't fix" but hey whatever, your choice.

**Comment by C-Lodder** [comment]
Chrome and FF both say "**fill in**". Either way, the tooltip is generated by the browser.

I suppose the error message could be changed to `This field is required`

**Comment by brianteeman** [comment]
> Maybe the fill "out" is a HTML5 thing?

Yes from the browser

> Chrome and FF both say "fill in". Either way, the tooltip is generated by the browser.

Our message was changed on request to match that.

Personally I would say this is a don't fix but not my call

**Comment by HLeithner** [comment]
I think we can't change the text in Safari right? And I'm not in favor to change our texts because the browser has another hardcoded tool tip. This would so only work for english and not for any translation (at least I see no way to manage this).

I'm closing this as won't fix, if anyone has another opinion feel free to reopen this.

And thanks for the report.
