### ISSUE TITLE
[4.0b1] Email Notifications is Required asterisk

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29342]
### Steps to reproduce the issue

Edit a user in Joomla 4.0.0 beta 1 admin console

Go to the User Action Log Options

### Expected result

Email Notifications field label with no asterisk indicating its a required field because how can a toggle yes/no be a required field?

### Actual result

`Email notifications *`

<img width="952" alt="Screenshot 2020-05-31 at 19 13 25" src="https://user-images.githubusercontent.com/400092/83359587-06456880-a373-11ea-98c7-da37b1ab1373.png">

**Comment by brianteeman** [comment]
I agree. I brought this up before and was told I was wrong

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/pull/24982

**Comment by conconnl** [comment]
Totally agree, if you can choose 2 options (Yes/No) then it's not required as you do not have the option to not choose anything.

Asterisk should be removed.

**Comment by mbabker** [comment]
> Totally agree, if you can choose 2 options (Yes/No) then it's not required as you do not have the option to not choose anything.

https://github.com/joomla/joomla-cms/pull/24982#issuecomment-496012905 and follow on comments still stand.  Just because you don't have a way of submitting a non-empty value through the UI does not mean that the form field definition should not have a required attribute if the application data model states that the field cannot be stored with a non-empty value, especially now that Joomla claims to have an API (and this API for some strange reason elects to use form definitions in a number of locations).  Sadly, the only way to enforce the "this field cannot be stored with an empty value" server-side validation rule because Joomla does not have a proper validator API (a proper validator API is something like those in Symfony or Laravel where data models can be validated at will regardless of input source, not the `Joomla\CMS\Form\FormRule` class) is with the use of the required attribute, which bleeds into the frontend display.  But hey, too late to do anything for 4.0 on that topic now.

**Comment by brianteeman** [comment]
This should be closed for the reasons stated above

**Comment by brianteeman** [comment]
@Quy What extra information are you asking for /me confused

**Comment by Quy** [comment]
Sorry I don't remember. Close?
