### ISSUE TITLE
[v4.0b1] Warning on Ajax request during installation

### ISSUE THREAD

**Issue by juliopontes** [joomla/joomla-cms#29354]
### Steps to reproduce the issue

Just trying to install

### Expected result

XHR POSThttp://localhost/joomla4/installation/index.php?task=installation.create&format=json [HTTP/1.1 200 OK 220ms]  SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data      1      <br />      2      <b>Notice</b>:  Undefined property: stdClass::$db_select in <b>installation\src\Model\DatabaseModel.php</b> on line <b>336</b><br />      3      {"token":"9e450711ecca2ed4518c9118a4b6c971","lang":"en-US","error":false,"data":{}}

### System information (as much as possible)

PHP 7.4.3
Using XAMPP v3.2.4

**Comment by ReLater** [comment]
> v4.0b1

<strike>I wonder about this outdated version "b1" and would recommend to use a nightly build for installation
https://developer.joomla.org/nightly-builds.html
</strike>

**Comment by ReLater** [comment]
@juliopontes 
Forget my last comment, please! I don't know why nightly builds haven't switched to next beta-2 after beta-1 has been released 2 days ago.
Confused ;-)

**Comment by brianteeman** [comment]
@ReLater the actual build of the nightly is beta2-dev which apparently is to signify it is the dev release before beta2. Please see #29284

**Comment by ReLater** [comment]
Thanks. Yes.
Meanwhile i know.

Reason was:
The https://update.joomla.org/core/nightlies/next_major_list.xml
and https://update.joomla.org/core/nightlies/next_major_extension.xml
are pointing to outdated beta-1-dev-ZIPs (that don't exist).

**Comment by HLeithner** [comment]
I created a pr for beta2-dev nightlies (https://github.com/joomla/update.joomla.org/pull/167) but has nothing to do with this issue.

@richard67 can you have a look at this?

**Comment by richard67** [comment]
@juliopontes What happens if you install a 3.9.18 on the same server under the same conditions (database type and version)?

I ask because the possible reason for your issue also exists in Joomla 3.9.

It happens only if you specify in the installation form a database name for which no database exists yet, and a user who has the privilege to create a database, e.g. "root" for MySQL databases, and you use the "MySQL (PDO)" driver, i.e. with "MySQLi" or "PostgreSQL (PDO)" it doesn't happen.

Can you confirm this?

**Comment by juliopontes** [comment]
@richard67 I've just test with latest 3.9 works fine.

**Comment by richard67** [comment]
@juliopontes And 4.0 Beta 1 still doesn't work on the same server?

**Comment by juliopontes** [comment]
@richard67 Just tested with latest Beta 2 and have same issue.

Ajax request: index.php?task=installation.create&format=json
<br />
<b>Notice</b>:  Undefined property: stdClass::$db_select in <b>C:\xampp\htdocs\sites\joomla4b2\installation\src\Model\DatabaseModel.php</b> on line <b>336</b><br />
{"token":"b3cdec3c7933249cfa7bf8c73fc9d892","lang":"en-US","error":false,"data":{}}

PHP Version 7.4.6

**Comment by richard67** [comment]
@SharkyKZ Could you have a look on it? I don’t have PHP 7.4 yet. Can you reproduce it?

**Comment by richard67** [comment]
@SharkyKZ Forget my previous comment, it's not a 7.4 issue, I think.

**Comment by richard67** [comment]
@juliopontes Which of the following 2 methods do you use for the database?
1. Specify a database name for which no database exists and a database user who has the privilege to create a new database. In this case the Joomla installation will create the database.
2. Before installation of Joomla, create a database and a database user with full access to this database only, and in the Joomla installation specify that user and that database.

Either of these methods should succeed, but if in method 1 the user doesn't have the privilege to create a database, the installation fails (normally with a meaningful error message).

I ask because knowing which of these 2 methods you use would help me to identify the error (or confirm what I think I have identified).

And for you the above information could be helpful, too: If you have used method 1 when it failed, you can try method 2, and vice versa, if you have used method 2 when it failed, try method 1.

Thanks in advance for answering my question and reporting back.

**Comment by richard67** [comment]
@juliopontes Please test Pull Request (PR) #29556 . Just replace the changed file by the one of this PR, or you even can to the 2 small changes with an editor. Then start a new installation. If it works, mark the test result in the issue tracker here [https://issues.joomla.org/tracker/joomla-cms/29556](https://issues.joomla.org/tracker/joomla-cms/29556) by using the "Test this" button, selecting the appropriate test result and then using the "Submit test result" button.

Because I'm not 100% sure that the PR solves all aspects of this issue, I leave it open until you have tested the PR with success, or if someone else can reproduce the issue and tested with success.

**Comment by richard67** [comment]
Closing as PR #29556 claims to solve the issue.

@juliopontes Please test as described in my previous comment. The issue could be reproduced on PHP 7.4 (not by me because I don't have 7.4 yet), and the PR solves it. It just needs one more test to be ready for going into J4 code.

On J3 it is definitely not an issue, I have checked that.
