### ISSUE TITLE
[4.0] ATUM - Diminuish the size of everything please!!!

### ISSUE THREAD

**Issue by pedro-olaia** [joomla/joomla-cms#29399]
### Is your feature request related to a problem? Please describe.
 Problem is the general usuability of Atum... I have to make more clicks and much but much more scrolling to have things done then what I had in Joomla 3.x... it seems this was designed for people that have no fingers and have to operate joomla by touching screens with their toes! Why all those fat buttons (Painted with bleach) and freaking huge boxes? Who designed this shit? What happened to what it was presented last year??????

### Describe the solution you'd like
Make everything smaller in size. Close to what is ISIS now, in size, colors, shape and form. Isis is freaking ugly but people can work with it!

### Additional context
I am a disabled person, I need to have an intuitive UI environment or else I lost to much time looking for simple buttons that should be intuitive to find like the save button, white, equal to all other buttons... I just get lost looking to where the fck is the save button... imagine the rest!... My clients are also disabled like me and just like all the clients of everybody else that uses joomla for their businesses, for their boutique agencies, for their productivity.... I can't sleep since I tried the beta version of joomla 4 Atum and realised it's going to kill my business... will the UI be considerably different in the end... or is it better for me and all the community that uses joomla as  tool for work, to start to look for another CMS system? Maybe in the end webflow its not that expensive! 

By the way... are you asking to the community to try a joomla Atum version for disabled people?? Wouldn't be more wise to ask for desable people to do it? How many desabled people had already tryed this "let's gonna kill joomla" solution? Did you at list cared about integrate disabled people in this J4 development?

Are you (Joomla elite people) open to real collaboration for changes that can really improve Joomla, or are you still closed and arrogant like shtt just like always? And like always is better to don't even bother...  Do you know that "Atum" means "Tuna" in Portuguese???

Really I can not sleep... this is my issue... Trying the beta version of Joomla 4 just made me realise how much my business is close to an end!!!  

Ok lets be calm, Im in shock, Im sorry for bad language... I can make a custom css file and override... override... override... isn't override joomla's middle name? ye it will be in joomla's spirit!

But man.... you are just KILLING JOOMLA. Atum it's the last drop in the death sentence of this brigliant CMS!

**Comment by marcodings** [comment]
Thank you for your feedback, we can use and value also YOUR perspective and contribution. 

Joomla has an accessibility team that deals with ensuring Joomla is accessible. I do not want to get your hopes up that anything significant can / will change on short term as we are in Beta now and our goal is to get Joomla4 released asap. 

Accessibility is an extremely complex topic and design is very personal, Joomla has been working on this back-end template for **multiple years** and has been open for contribution and feedback. I would definitely not characterize this as elitist irrespective of the fact that we can not accommodate everybody. 

Please contribute and help joomla better contact **Carlos Cámara**  through here [Joomla accessibility team ](https://volunteers.joomla.org/teams/accessibility-team)
and read more about what our [Joomla volunteers portal](https://volunteers.joomla.org/)

Hope we can see you there soon

**Comment by progreccor** [comment]
pedro-olaia is totally right!

**Comment by marcodings** [comment]
> pedro-olaia is totally right!

Vladimir, help us then make it better, see my initial answer

**Comment by zikkuratvk** [comment]
Brilliant CMS looks very good, it's a pity that it was abandoned 4 years ago.

https://github.com/rickybrown/BrilliantCMS

**Comment by progreccor** [comment]
> 
> 
> > pedro-olaia is totally right!
> 
> Vladimir, help us then make it better, see my initial answer

I still remeber what happened to Honsu

**Comment by nikosdion** [comment]
@marcodings There is an actual bug in Atum.

The frontend template (Cassiopeia) has a base font size of 14px set to the root `html` tag. Therefore the Bootstrap 4 base font size of 1 rem for everything under the `body` tag is realistic and works great for desktops, touch screens and people with disabilities that restrict fine motor control. Note that this is why the whitespace is there and no, it's not based on the feedback of the Joomla! accessibility team; it's the BS4 default.

The Atum backend template, however, does not do that therefore everything is oversized. How much oversized? 14.28% bigger. That's because browsers default to a base font size of 16px since they also default to a serif font and we all know that serif fonts are less legible than a sans serif font of the same size which is why all computer UIs use sans serif fonts to begin with.

If you set your browser to use a base font size of 14px then you won't perceive Atum as horribly big, it looks spanking great! But this is not the default browser setting which 99% of your users will experience. Have y'all tested Atum on a _clean_ install / VM? 

Solution: add `html { font-size: 14px }` to Atum's CSS to make it consistent with Cassiopeia. 

This change works great. I made a plugin yesterday to apply this change on my Joomla 4 dev site since it would otherwise not fit on my 15" MacBook Pro's screen, which is just plain silly.

PS: The Atum development was being mostly done in secret as you very well know. Telling people off for not participating in the closed development process is not just wrong, it's outright invalid. Based on our discussion at the forum event this past January we both seem to agree that FOSS is written to benefit its users. Users find Atum horribly _large_ due to an omission during its development. Please spend less time chastising people and more time exploring what happened, whether it's a bug and how it can be fixed.

**Comment by infograf768** [comment]
Tested 
```
html { 
   font-size: 14px;
}
```
and indeed it helps a lot.
If we do that it means we have to reconsider many places using rem as these are relative to the html fontsize.

**Comment by nikosdion** [comment]
All rem values are fine since they are relative. As long as you use rem everywhere (you do) changing the font size basically scales the entire interface without any side-effects.

If you were trying to do absolute pixel arithmetic (e.g. to size bitmap images) using rem and your external knowledge of the base font size that's not defined in the template then it's wrong for many reasons including the fact that absolute pixel arithmetic should use px, not rem.

Finally, if Joomla had ever used rem without realizing it's a _relative_ size (that's the "r" in rem) I would posit there'd be a much bigger issue ;)

**Comment by marcodings** [comment]
@nikosdion would you mind makin this a seperate issue as its "specific, i would do it but i don't want to "steal" your idea

I overlayed the 14px 
![image](https://user-images.githubusercontent.com/3484222/83617532-7e857700-a589-11ea-9241-39eda081bc32.png)

**Comment by infograf768** [comment]
> All rem values are fine since they are relative. As long as you use rem everywhere (you do) changing the font size basically scales the entire interface without any side-effects.

It has side effects
Look at radius, tiny, joomla logo, etc.
I did not say we should modify all rem, but quite a few

**Comment by bembelimen** [comment]
> PS: The Atum development was being mostly done in secret as you very well know.

Will this urban legend never disappear? Repeating it everytime does not make it true.

**Comment by crystalenka** [comment]
> It has side effects
> Look at radius, tiny, joomla logo, etc.
> I did not say we should modify all rem, but quite a few

These would have to be modified then, but as they are not dependent or relative to the font size (why would they be?) I'd suggest using px instead to avoid issues for people who then size up their screens or font size for accessibility. (As it is, you'd have a giant Joomla logo with huge border radius, and that's not exactly desirable, either.)

**Comment by marcodings** [comment]
Thank you @nikosdion

**Comment by marcodings** [comment]
Closing the issue as it has been made specific and is adressed in #29401

**Comment by nikosdion** [comment]
@bembelimen I apologize. "Done in secret" is wrong. "Done in an ivory tower, willingly shutting off the community's feedback" is the correct term. We could all see the changes, just not have a say on them.

**Comment by infograf768** [comment]
@crystalenka
logo also depends on height in rem
Afer adding html 14px
<img width="1344" alt="Screen Shot 2020-06-03 at 12 00 42" src="https://user-images.githubusercontent.com/869724/83623770-08394280-a592-11ea-8f58-40b698de7d1f.png">

Modifying height (in rem)
<img width="1264" alt="Screen Shot 2020-06-03 at 12 01 14" src="https://user-images.githubusercontent.com/869724/83623831-1d15d600-a592-11ea-974e-dd07413e1142.png">

**Comment by crystalenka** [comment]
> @crystalenka
> 
> logo also depends on height in rem
> 
> Afer adding html 14px
> 
> <img width="1344" alt="Screen Shot 2020-06-03 at 12 00 42" src="https://user-images.githubusercontent.com/869724/83623770-08394280-a592-11ea-8f58-40b698de7d1f.png">
> 
> 
> 
> Modifying height (in rem)
> 
> <img width="1264" alt="Screen Shot 2020-06-03 at 12 01 14" src="https://user-images.githubusercontent.com/869724/83623831-1d15d600-a592-11ea-974e-dd07413e1142.png">
> 
> 
> 
> 

I understand but the height of the logo should _not_be defined in rem for exactly this reason. Px should be used instead. Same for border radius.

**Comment by pedro-olaia** [comment]
> 
> 
> Thank you for your feedback, we can use and value also YOUR perspective and contribution.
> 
> Joomla has an accessibility team that deals with ensuring Joomla is accessible. I do not want to get your hopes up that anything significant can / will change on short term as we are in Beta now and our goal is to get Joomla4 released asap.
> 
> Accessibility is an extremely complex topic and design is very personal, Joomla has been working on this back-end template for **multiple years** and has been open for contribution and feedback. I would definitely not characterize this as elitist irrespective of the fact that we can not accommodate everybody.
> 
> Please contribute and help joomla better contact **Carlos Cámara** through here [Joomla accessibility team ](https://volunteers.joomla.org/teams/accessibility-team)
> and read more about what our [Joomla volunteers portal](https://volunteers.joomla.org/)
> 
> Hope we can see you there soon

I don't know what people with accessibility issues will do with Joomla after joomla die... And Joomla will die because common users are abandoning the project. Clear and simple. You have the numbers! This is not an issue to talk with Carlos Cámara, that's an issue to talk with the strategy leader! Also I didn't find the Design team, can you help me on that?!

"and design is very personal"... no it's not! Design is very technical, a solving problems oriented methodology that involves strategy. You might be confusing Design with looks or aesthetic that is a very wrong assumption similar to confuse CSS with computer programming. 
I kinda can understand now why there is no Design department in Joomla volunteers portal, and why the new J4 have such a bad usability.... Good Design is all about functionality and can be extremely good when it looks bad. For me and my clients what we need is something easy to work around, simple to find things and execute fast. The look and feel of the platform can help a lot on that as it can and should orient the eye for the main tasks, but the main issue is not the looks, its the usability of J4, its the visual confusion for the eye and the mind, it's the time lost in scrolling and scrolling, clicking and clicking again, making large movements with the mouse from one box to another!

The main issue here is not the complexity of the accessibility topic. Is the survival of Joomla. And project liders not willing to understand and accept that there is a problem is the major problem! Impossible to change or fix anything if you are not willing to accept that there is a problem!

In my opinion, Joomla 4, like it is, should never come out... putting it asap out there may become one more nail for the coffin. I hope you leaders have at list the sensibility to understand the need to keep joomla 3 alive until Joomla 5 is out!

**Comment by nikosdion** [comment]
@pedro-olaia While the initial feedback from Marco was poorly worded he was willing to accept there is a problem and asked me to file an issue. You will see that I closed my issue because it's a complicated topic with no good solution. Right now you can change your browser base text size and Joomla, as well as all other sites written with modern accessibility guidelines in mind, will no longer look horribly big. That's not a satisfactory solution but I see that the blame is equally divided between browser defaults preserving legacy settings, modern accessibility guidelines not taking into a account said legacy settings and Joomla having to use BS4 without modifying for very good reasons that were discussed elsewhere. There is no good solution _at the moment_, lest you want to take a backwards step in accessibility.

Regarding releasing Joomla 4, it _had_ to be done for the same reasons that Joomla 1.6 had to be released: if it's in forever alpha no issue will ever be addressed, the project stagnates and dies.

You asked to talk to the strategy leader. There isn't one per se. Joomla 4 started as a short term project which would deliver a stopgap solution by the end of 2016 or mid-2017 at the latest. The goals and strategy were written in a piece of paper by yours truly at J and Beyond 2015 where a dozen of us converged to discuss Joomla's future. Unfortunately the effort got sidelined with a futile effort to redefine Joomla as a cross-breed between Laravel, Symfony and a CMS. That led me and others quit in protest or lose interest. That effort was relegated to Joomla X and development of Joomla 4 restarted around 2017-ish (exactly when I can't tell you; I'd quit in October 2015 because I disagreed with not putting the users and their needs first and foremost in the development strategy). Of course by that time the project had already lost two years, things were evolving fast in the web and parts of the strategy had to be rethought.

The reason I am going into this tirade is for addressing the death of Joomla. If Joomla 4 was never released we'd be stuck with a codebase that began development 9 years ago. That codebase has been on its deathbed since 2015. _That is what was losing Joomla users_. Sticking with it would be the guaranteed death of Joomla, period.

Is Joomla 4 any good? No. It's a massive rewrite while still maintaining a modicum of backwards compatibility. There were too many decisions made, too many changes taking place and too much that needs polishing. Just like 1.5, 1.6 and 3.0 were before it. They all sucked at release and were mostly unusable around beta. Thinking it could ever be different is a pipe dream. By releasing Joomla 4.0 there's an opportunity to find everything that's problematic and address it for 4.1 and 4.2. As experience has shown us, around 4.1 we'll have a usable CMS again – if and only if we keep looking out for problems and trying to get them fixed. That's up to all of us: core developers, third party developers and the community. The alternative model is having a corporate overlord dictating development like you see in WordPress. And please don't tell me WP is better when they _force_ the block editor down the throat of everyone, demanding that everyone becomes a proficient JavaScript developer if they want to just build sites beyond the very basics.

Back to the problem at hand. Because of the nature of the beast I think the best solution is a **user profile** plugin to allow users to set the base font size if they so wish, even though it's a BAD idea for accessibility. Being a per user setting able bodied backend users could set the base font size to 14px or 15px, making the size of the backend template reasonable. Backend users with disabilities would still be able to use their browser's settings OR the user profile setting to use a larger base font size. Everyone's happy.

The kicker? Such a plugin already exists in Joomla 4! It's the accessibility options one. If I would have the production department agree that this is a reasonable change I could submit a PR with a default setting of 14px and the ability to either unset it or change it to whatever size you want between 8px and 72px – so that even when using Joomla in someone else's browser the disable backend user still gets their preferred font size. It's not the _best_ approach but it's the _practical_ approach. I am going to reopen issue #29401 with this comment so we don't need to track progress in two places at the same time.

**Comment by chmst** [comment]
@pedro-olaia 
>this was designed for people that have no fingers and have to operate joomla by touching screens with their toes

Just a note: I am working with disabled who have to touch buttons with their tongue or toes because they have no hands (or cannot use them). This is not a joke. It is really very difficult to meet the needs of everyone.
