### ISSUE TITLE
[4.0b1] Error: 0, after trying to install joomla 3.x template

### ISSUE THREAD

**Issue by GixxerMKD** [joomla/joomla-cms#29394]
### Steps to reproduce the issue
Fresh beta 1 installation
Tried to install one of JoomShaper's template to see what will happen (template version J3.x)

### Expected result
Error message regarding the unsupported extension (version).

### Actual result
An error has occurred.
0 Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin()
Back-end shows the error message on all screens, cannot do anything in the admin.

### System information (as much as possible)
Local installation (wamp) php 7.3.1, mysql 5.7.24, apache 2.4.37

**Comment by SharkyKZ** [comment]
This should be reported to JoomShaper. It's up to extensions to handle compatibility with Joomla! versions. Closing as non-core issue.

**Comment by github-canni** [comment]
@SharkyKZ  So installing an extension by a user could possibly corrupt the whole installation? Shouldn't there a rollback feature? Shouldn't joomla extension installation prevent installation wrong/incompatible extensions? Though it's a third party issue - this is a non expected behaviour breaking the backend. Should be considered as feature request rather than closing the ticket.


- Prevent site breaks by detecting incompatible extensions
- Rollback feature if installation goes wrong

**Comment by GixxerMKD** [comment]
Exactly what i thought.

+1

**Comment by SharkyKZ** [comment]
This is something for extension developers to implement. We cannot possibly tell whether an extension is compatible or not. This should be done in extension's installation script.

**Comment by GixxerMKD** [comment]
Yes but we are talking about user making mistake and selecting wrong file
for installation which would render his site completely useless.

**Comment by ReLater** [comment]
How should Joomla identify if an extension is not compatible with it? Impossible. And if an extension breaks Joomla completely how can a rollback feature help that is also broken then.

The only reliable "rollback" is a backup before installation. Akeeba Backup for Joomla 4 is out for a while now. Therefore no problem to make backups.

> This is something for extension developers to implement.

Exactly! The extension must block the installation, not Joomla.
