### ISSUE TITLE
Cannot send email using SMTP using mandrillapp.com

### ISSUE THREAD

**Issue by alecsvee** [joomla/joomla-cms#29400]
I was trying out Joomla to send email thru SMTP using mandrillapp.com but i get an error 
![Screenshot 2020-06-03 at 3 35 56 PM](https://user-images.githubusercontent.com/910717/83609273-a0462480-a5b0-11ea-9235-2ad21ef8955f.png)

my settings are as follows
![Screenshot 2020-06-03 at 3 41 58 PM](https://user-images.githubusercontent.com/910717/83609429-e0a5a280-a5b0-11ea-913f-a5527fcc9e48.png)

This setting works using other CMS.

**Comment by HLeithner** [comment]
I don't think that your smtp username is "Covenant Evangelical Free Church"

**Comment by chmst** [comment]
@alecseeve In general you can get help for such issues in the joomla forum. 
Please let us know if your issue is resolved. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29400">issues.joomla.org/tracker/joomla-cms/29400</a>.</sub>

**Comment by Quy** [comment]
Please ask help in Joomla Forum. https://forum.joomla.org/
