### ISSUE TITLE
[4.0b1] three column (plugin) config layout results in bad UX

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#29418]
### Steps to reproduce the issue
create a lot of configuration options in a plugin.
open the plugin configuration

### Expected result
all options should be displayed 'logical' as configuration options are set by the developer in a specific order because that adds value / is logical.

### Actual result
configuration options are displayed in three columns in down - across order placing the option in an illogical way on the screen. This results in a lot of up down scrolling and a bad UX, especially when you conditional fields (showon) that when selected push settings off screen or onto other column.

![screen shot 2020-06-04 at 08 27 34](https://issues.joomla.org/uploads/1/4f5fcb63ce378dd982d9d439e7f29ca0.jpg)

**Comment by ReLater** [comment]
The main problem from my point of view is that some users have "problems" just because they have to scroll the page (what a drama) others because of this multi column layout. I belong to the latter ones.

All settings in my custom plugins look weird, are too small now while lots of white space besides them ... and so on ... just because of this restricting mutli column thing. Months ago I've spent a lot of time to have them all vertically aligned, full width, no-padding, no-margin with J3 AND J4. 

In J4 complete chaos since the multi columns were established. If you use subform fields forget them completely ...

Remove hard-coded multi columns! Or give a chance to individually control column counts easily via manifest files.

**Comment by infograf768** [comment]
This is due to the class
`column-count-md-2 column-count-lg-3`
in article edit
and generally in
`.../layouts/joomla/edit/params.php`
through `echo LayoutHelper::render('joomla.edit.params', $this);`

modifying to `col-12 col-lg-6` would do the trick.

Do we have a way to introduce a variable class param for that layout? If not, is it feasible? At which level?

**Comment by Ruud68** [comment]
@ReLater @infograf768 Thanks for the follow up.
Agree that this is subject to the users preferences.
Following @wilsonge presentation on the J4 beta release on Jandbeyond, the target audience next to agencies and template designers) for J4 is (extension) developers.
I am mentioning this to point out that adding a parameter to toggle the multicomlumn or not is ONLY feasible if that config .xml will then NOT break J3.
in PHP you can work around J4 / J3 restrictions / features but in forms you cannot.
This is for me as an extension developer very important because like it or not, when my extension only works on J4 I will loose a lot of customers, and no... as only 27% is currently on J3.9 I will loose instantly 70% of my potential customer base when my extension doesn't work anymore on J3.x
J3.10 will not fix that because my guess is that this version will only be used by the people who are actually updating their site to J4 (which is likely only a part of the 27%)

**Comment by ReLater** [comment]
> Do we have a way to introduce a variable class param for that layout?

Any extension has other needs to display the settings and also from tabulator to tabulator. As long as the extensions can't call the JLayout with their favored class parameters for each tabulator I don't think that just adding the possibility to add custom classes to the JLayout helps a lot.

Other problems of automatic, stupid ordering of the settings are well described in @Ruud68 's screenshot.

But yes, going away from column-count to simple col classes instead would be at least helpful because one can override it easier in an extension backend css than all these column-count stuff.

For me column-count classes are a nice feature for self-sufficient cards or blocks but not for form fields.

And again: 1 column and the need of a little bit more scrolling is better than the current situation.

> At which level?

In the manifest files of the extensions. fieldset classes or whatever. BUT I KNOW that it's not that easy.
 and

> I am mentioning this to point out that adding a parameter to toggle the multicomlumn or not is ONLY feasible if that config .xml will then NOT break J3.

Agree

**Comment by richard67** [comment]
Don't we have already some 25 (or so) issues for this column layout thing? Or were these only for global config?

**Comment by Quy** [comment]
Duplicate #25891 
PR #29398

**Comment by ReLater** [comment]
The provided prs don't change anything. One is just removing the column-count from outer filedsets if nested.
The other one ended in a discussion if column-count 2 or 3.

> For me column-count classes are a nice feature for self-sufficient cards or blocks but not for form fields.

**Comment by Ruud68** [comment]
agree with @ReLater and also want to emphasize that what ever solution is chosen, it should not break joomla 3.x (where x is not 10) as that will force developers to maintain multiple versions of their extensions or to create their own configuration interface: which for a plugin would mean a lot of overhead and duplicated code.

**Comment by Quy** [comment]
Please add your comments to https://github.com/joomla/joomla-cms/issues/25891 so they are in one issue. Thank you.
