### ISSUE TITLE
The PHP temporary folder is not set.

### ISSUE THREAD

**Issue by Mansaylon** [joomla/joomla-cms#29421]
### Steps to reproduce the issue
In Backend on Dashboard go to 'Update Checks' -> 'Joomla is up to date' -> 'Upload & Update'

### Expected result
No Warning

### Actual result
Warning
The PHP temporary folder is not set.

### System information (as much as possible)
Tmp directory controls with 775 rights.

### Additional comments
No problems with version 3.x on the same server.

**Comment by richard67** [comment]
Is there maybe some open_basedir restriction in your php.ini limiting access to the temp folder, e.g., because it is same folder for both installations, and for one of them it is within the open_basedir allowed paths, and for the other not?

**Comment by richard67** [comment]
Setting to "Information Required", see my previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29421">issues.joomla.org/tracker/joomla-cms/29421</a>.</sub>

**Comment by ReLater** [comment]
This irritating warning is there on nearly any host since I know Joomla. I never had any problems with ignoring it and that's the answer in forums since years: "Ignore this message".

1) It shouldn't be a warning but an info if we really need it in Joomla any longer.
2) The description should **start** with "Only if you're having issues ... then ..." to make clear that thinking about the "problem" is a waste of time ;-)
3) The php.ini part should be removed/replaced ("ask you host") because only some hosts provide a php.ini in customer accounts.
4) It should explicitely say that it's not talking about the Joomla <strike>log</strike> temp path.

BTW: The warning can be found at several places in Joomla.

![05-06-_2020_11-55-04](https://user-images.githubusercontent.com/20780646/83864690-5f235100-a725-11ea-8763-af9eee1604c7.png)

**Comment by ChristineWk** [comment]
Can't confirm "Actual result". But agree with the informations / proposals from @ReLater.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29421">issues.joomla.org/tracker/joomla-cms/29421</a>.</sub>

**Comment by richard67** [comment]
@Mansaylon What is your PHP version? It might be that you had posted it in the other issue. But could you post here again, too? Thanks in advance.

**Comment by Mansaylon** [comment]
7.4.5
or
7.3.17
Testet with both.

But found that the same warning is also with Joomla 3.9.x. And I can still do installations.
This warning is irritating if everything still works.

With Joomla 4 I could not test any installations because there are no components, templates, plugins.

**Comment by ReLater** [comment]
> With Joomla 4 I could not test any installations because there are no components, templates, plugins.

Nothing has changed with J4. You'll see exactely the same maessage in the same server environment.

> This warning is irritating if everything still works.

Agree.

**Comment by adj9** [comment]
From the Joomla! dashboard, I have no PHP error warnings.

The PHP Version Check plugin is enabled.

I have not done any code checks for the expected result.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29421">issues.joomla.org/tracker/joomla-cms/29421</a>.</sub>

**Comment by Mansaylon** [comment]
Got an answer from the hoster. They have tested everything and say that this warning can be ignored. Everything works.

**Comment by richard67** [comment]
@Mansaylon Thanks for reporting back.
