### ISSUE TITLE
The media manager of joomla 4.0 cannot insert picture links

### ISSUE THREAD

**Issue by ymqjh** [joomla/joomla-cms#29522]
The media manager of joomla 4.0 cannot insert picture links, article thumbnails cannot be imported into external pictures, request to add, request.![screen shot 2020-06-09 at 08 33 44](https://issues.joomla.org/uploads/1/b703fc916f6e6ace11357c392b4fe1e4.jpg)![screen shot 2020-06-09 at 08 33 46](https://issues.joomla.org/uploads/1/ce5b1442b321808ab99d500ab44b620d.jpg)

**Comment by toivo** [comment]
@ymqjh the screen capture is from the tab Images and Links of Article: Edit.  What happens when you go to the field Intro Image, select an image from the images folder and click Select? Both Intro Image and Full Text Image are saved into a new article and presented perfectly all right at the front end.

If you have issues with uploading images from Content - Media, please create a new topic to the Joomla! Forum in the Joomla 4 related sub forum at https://forum.joomla.org/viewforum.php?f=803, but please provide more information about the J4 version you working with and the test environment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29522">issues.joomla.org/tracker/joomla-cms/29522</a>.</sub>

**Comment by Quy** [comment]
Duplicate #28852
