### ISSUE TITLE
[4.0] [3.9] Asset separation

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#29569]
### Is your feature request related to a problem? 
Assets in Joomla are a disaster because regardless of their origin, whether it is a publication or a plugin or a template or component or modules they are all together; What it happens that in sites with many publications (for example about 40,000 a year) as in a news page the reading of the assets leads to the ttfb ("Time To First Byte") going from a response time of 50ms to 3000ms for example. This explains why in a new, clean joomla installation the behavior is so fast and over time it becomes so slow as articles are added. So it is necessary to separate the system assets (plugins, templates, components and modules) and put the assets that originate the articles APART or possibly eliminate that the articles and categories NO longer generate assets.

### Describe the solution you'd like
So it is necessary to separate the system assets (plugins, templates, components and modules) and put the assets that originate the articles APART or possibly eliminate that the articles and categories NO longer generate assets.

**Comment by Stuartemk** [comment]
#30245

**Comment by Hackwar** [comment]
I also looked at this issue for a long time and did both tests right now and in the past and I think you are barking up the wrong tree here. We aren't loading Gigabytes of data on each request from the assets table and even millions of rows in a table aren't a big issue for a RDBMS. Please get another professional opinion on the site in question and see which optimisations are possible there, but the assets table is also not really something which we will change. Because of that I'm closing this issue.

**Comment by Fedik** [comment]
@Stuartemk @Hackwar there actualy a fix that can address this issue https://github.com/joomla/joomla-cms/pull/44078
Please review and test.
