### ISSUE TITLE
[4.0] Updates page badly laid out so name of extension is only one word wide

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29766]
### Steps to reproduce the issue

install Akeeba Backup 7.1.4
Go to the extension updates page
click find updates

### Expected result

Something laid out better than it is

### Actual result

The "Name" column is only wide enough for a single word, meaning Akeeba Backup Core package is shown as 

```
Akeeba 
Backup 
Core 
package
```

The URL and the information link could be simple buttons with pop overs, or links to the urls, that would save a lot of space. 

<img width="1601" alt="Screenshot 2020-06-22 at 22 30 38" src="https://user-images.githubusercontent.com/400092/85337247-064f0900-b4d8-11ea-9edf-19bcf6092c1f.png">

screenshot is 1600px x 1600px (half a 27inch iMac retina screen) 

// Sorry @nikosdion for picking on you ;-) 

### Bonus

There is a useless popover on the name, that just shows the name again

<img width="493" alt="Screenshot 2020-06-22 at 22 32 39" src="https://user-images.githubusercontent.com/400092/85337415-56c66680-b4d8-11ea-8e62-7230e97f2ed5.png">

**Comment by nikosdion** [comment]
I would appreciate if I was not mentioned on every issue that is unrelated to my code and I have nothing to do with, especially ones that I have reported at least one or more months in advance. It is very disruptive to my day if I wake up to dozens of emails from github about issues that are completely unrelated to my software and my code.If I have to waste my time sorting through all that and related email it is extremely unlikely that I will find the time to make a productive contribution to this project. As I have said before, please do not waste my time so that I can be more effective in my contributions. Thank you!

**Comment by PhilETaylor** [comment]
I cannot find your open reports regarding this. If this is a duplicate it can be closed. It’s certainly not yet been addressed and is a valid issue to be reported.

I’m sorry you feel this way - simply hit the unsubscribe button. No need for a roast tirade.

**Comment by ReLater** [comment]
See https://github.com/joomla/joomla-cms/issues/25021

You can't copy links inside a popover or tooltip. I could live with a modal... But one should see the links before clicking (or not). Too many extensions use these urls for propaganda, not info.

And, just BTW, I personally don't think that it's a problem to display extension names or other entries as multiliners. But I'm a purist, not an aesthete ;-)

**Comment by Quy** [comment]
Please test PR #29772
