### ISSUE TITLE
[4.0] Login bad error message

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29773]
### Steps to reproduce the issue

Upgrade nightly build (today is 2020-06-24). Logout / Login Administrator.

### Expected result

Home Dashboard / Control Panel OK

### Actual result

There is a stray error message as illustrated:

![screen shot 2020-06-24 at 06 06 06](https://issues.joomla.org/uploads/1/c140d828e1e2653554125ea03641a70e.png)

The blue link leads to Urgent privacy requests - the ones I forgot about whilst testing.

### Additional comments

The last thing I did was save Global Configuration after changing default Captcha.

**Comment by ReLater** [comment]
### See next comment https://github.com/joomla/joomla-cms/issues/29773#issuecomment-650551530

<strike>
The first part is easy. The lines

`"REQUESTFOUND_MESSAGE" => Text::_('PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_MESSAGE'),`

`"REQUESTFOUND_BUTTON"  => Text::_('PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_BUTTON'),`

are missing here:
https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/quickicon/privacycheck/privacycheck.php#L63-L65

Then I get:
![24-06-_2020_16-55-54](https://user-images.githubusercontent.com/20780646/85580028-ab362700-b63b-11ea-8359-c4999d742ffa.png)


2. part could be to chnage

`PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_MESSAGE="%s Urgent Privacy Request(s) to manage."` 

to

`PLG_QUICKICON_PRIVACYCHECK_REQUESTFOUND_MESSAGE="urgent Privacy Request(s) to manage."` 

It's used here(?) .
https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/plg_quickicon_privacycheck/js/privacycheck.es6.js#L46

I don't know if JS has a sprintf analog and if it should be used here if yes.
</strike>

**Comment by ReLater** [comment]
It looks like the alert message has been removed by @brianteeman  on purpose: See https://github.com/joomla/joomla-cms/pull/24893

but then the JS logic was brought back some months later by @bembelimen erroneously: See https://github.com/joomla/joomla-cms/pull/25570

and https://github.com/joomla/joomla-cms/commit/50eae65195ad4b3a35a5f91602043560d3f63282#diff-e815986c9bc783495edecba9f87d8f84 ( @fancyFranci )

Otherwise we both wouldn't see the alert message concerning privacy requests.

**Comment by ceford** [comment]
I think this problem has gone away
