### ISSUE TITLE
[4.0][CLI] No confirmation step on deleting users

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29819]
### Steps to reproduce the issue

8e2552d07613acfcdb619a6481d92e78d6e5a83e

<img width="501" alt="Screenshot 2020-06-28 at 20 26 23" src="https://user-images.githubusercontent.com/400092/85956412-a811a280-b97d-11ea-902a-edffbdd6380d.png">

### Expected result

a `Are you sure you want to delete this user?`

### Actual result

User deleted without confirmation 

### Additional comments

The CLI asked for confirmation when deleting an extension - but not when deleting a user 

<img width="558" alt="Screenshot 2020-06-28 at 20 28 05" src="https://user-images.githubusercontent.com/400092/85956450-e60ec680-b97d-11ea-9d59-35ce4d0bc0e0.png">

**Comment by alikon** [comment]
please test #29827

**Comment by alikon** [comment]
reopened as #29827 was not the solution

**Comment by mbabker** [comment]
#29827 was correct but it should use `$io->confirm()` instead of `$io->ask()`.  The `confirm()` helper very specifically is only going to accept a yes looking answer as confirmed, the way you handled it it will basically accept anything that is not "no" as a "yes" looking answer.

But, you also need to check Symfony's API to see what happens if it determines the current console session is non-interactive.  It may very well be that it skips the prompt if it determines the session is non-interactive.

(BTW, a `--force` flag should also be introduced into these things that bypasses the prompt)

**Comment by alikon** [comment]
thanks for the tip 
reopend #29827 using `$io->confirm()` instead of `$io->ask()`

i left this open cause still we need to check better your last point

**Comment by alikon** [comment]
closing as the non-interactive flag should be OK now
please re-test #29827
