### ISSUE TITLE
[4.0] json_decode() expects parameter 1 to be string

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#29825]
### Steps to reproduce the issue
Add a custom media field.
Add a custom subfields field.
Edit an article.
Under Fields tab, add a row under the subfields field.
Leave blank and click Save button.

@astridx

### Actual result
> PHP Warning:  json_decode() expects parameter 1 to be string, object given in \libraries\src\Form\Field\AccessiblemediaField.php on line 133

**Comment by astridx** [comment]
Thanks @Quy. You probably inserted me because I created [this](https://github.com/joomla/joomla-cms/pull/27712) PR. 
I am not sure whether my PR is the cause for this error. I will check this evening.
There were problems with the media field and the subform before. For example [here](https://github.com/joomla/joomla-cms/issues/26711).

**Comment by Quy** [comment]
PR #29840
