### ISSUE TITLE
[4.0] Front end logout leads to 404 error

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29868]
### Steps to reproduce the issue

Upgrade to Beta-3 Dev
Login in to Front end
Logout

### Expected result

Redirect to Home page

### Actual result

Redirect to http://localhost/j4beta2/index.php/en/change-password which throws a 404 Not Found page

### System information (as much as possible)

Firefox and Google Chrome on Mac OSX

### Additional comments

Why is the 404 page pretty much a full page except for the Header?

**Comment by ceford** [comment]
After login I was redirected to my Profile because I had not confirmed consent to the the Privacy Policy. And all links led to the Profile. Having accepted the Policy, way down the page, all works normally. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29868">issues.joomla.org/tracker/joomla-cms/29868</a>.</sub>

**Comment by joeforjoomla** [comment]
Confirmed, but the problem was there even before than Beta 3

**Comment by paternax** [comment]
I have this issue only if I'm logged in in to the frontend and be in the editing modus of an article. (4.0.0-beta4-dev)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29868">issues.joomla.org/tracker/joomla-cms/29868</a>.</sub>

**Comment by ghost** [comment]
Can't confirm on Menu Item Type `Login Form` or Module `Login`. User stay on Page after Logout.

**Comment by ceford** [comment]
Now testing in github fork/clone of joomla-cms - currently 4.0.0-beta5-dev. As @paternax says, if Logout whilst editing - Error403 page.

**Comment by HLeithner** [comment]
I'm not sure if I understand the problem (or it's 2 problems)

1. issue opener @ceford you login and get redirected to the profile page to accept the privacy consent right? As long as you don't accept this the website will not work for you that's expected. and if I read your comment right the page works after accepting the consent.
2. @paternax you have a complete different situation with another error? if you logout while you are on an edit screen you get a 403 "No access" error which is also expected when your site doesn't redirect the user to another page on logout.

@ceford if I'm wrong please reopen the issue I'm closing this.
@paternax if you have another issue then cliff describes and I also ready confirmed as expected behavior please create a new issue.

**Comment by ceford** [comment]
This is an old issue and I am content for it to be closed. However, the Login form and Login menu have a Logout Redirect item that is set to Default but that seems not to be defined anywhere. I was expecting it to be the the site default page but it looks like it is just the current page. Hence 403 if you logout on an edit page.
