### ISSUE TITLE
[J4] Should J4 be oriented directly to BootStrap 5?

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#29944]
On June 16,[ BootStrap version 5](https://mdbootstrap.com/docs/standard/components/buttons/) was **[published](https://v5.getbootstrap.com/docs/5.0/getting-started/introduction/)**.
The tasks set for the new version are all solved, and all the development of new features is over.
Now BootStrap 5 is being tested, anyone can try it out and find errors. BootStrap 5 has an Alfa version.
I believe that the final version will be released much earlier than the final version of J4.

Bootstrap 5 first alpha was officially released on June 16, 2020.
New features of BS5, Summary of the most important changes:

1. jQuery was removed
2. Switch to Vanilla JavaScript
3. Drop Internet Explorer 10 and 11 support
4. Improved grid system
5. Improved documentation
6. Improved modularity
7. Improved forms
8. New responsive font
9. New utilities & helpers
10. Easier customization & theming
11. Lighter package
12. New API available

Detailed explanations for all the changes in our [video tutorial](https://youtu.be/c9B4TPnak1A).

**Comment by Quy** [comment]
See previous discussion #27420

**Comment by 4digitalworld** [comment]
@wilsonge
Release available - [v5.0.0-alpha1](https://github.com/twbs/bootstrap/releases/tag/v5.0.0-alpha1)
[v4.5](https://github.com/twbs/bootstrap/releases/tag/v4.5.0) is also available.

I think that Bootstrap 5 could be made as the main one for Joomla 4.

And after 3-4 years, when Bootstrap 6 will be available, then also make the transition to the new version. This will help many companies that make websites on Joomla for customers so that there is always work to switch to new technologies.

My fears are related to the fact that support for Bootstrap 4 will be discontinued on **[November 26, 2020](https://github.com/twbs/release)**, and therefore the Joomla 4 stable version will most likely be released later than support for Bootstrap 4 will stop. It will be old technology at that time.

Moreover, the blog [says](https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/) that the [migration](https://v5.getbootstrap.com/docs/5.0/migration/) from version 4 to version 5 will be as easy as possible. I believe that this can be debated now.

**Comment by korenevskiy** [comment]
> Moreover, the blog [says](https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/) that the [migration](https://v5.getbootstrap.com/docs/5.0/migration/) from version 4 to version 5 will be as easy as possible. I believe that this can be debated now.

Is it possible that when they talk about a very simple transition from BS4 to BS5, they say that all classes of controls and buttons are the same?
**Does this mean we can make a switch in the template with the version selection?**

**Comment by korenevskiy** [comment]
If we replace BT with the new version 5 and If the template is crooked. This means that we need to edit the styles of the template itself. So how index.php this is a standard code whose structure does not depend on styles at all.

**Comment by Quy** [comment]
Per @wilsonge comment in #27420:

> If the release is available we’ll move to it but there’s really nothing we can do right now

**Comment by wilsonge** [comment]
Alpha doesn’t change much. Last time the alpha was 2 years before stable bs4 was released (and there were large differences between the versions). And we’re targeting j4 now for end of this year. If bs5 is in something like RC before we go stable we can investigate but right now it’s still not really an option for us
