### ISSUE TITLE
[4.0] Editing content on frontend gives duplicate breadcrumbs

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30001]
### Steps to reproduce the issue

Edit an article on the frontend on Joomla 4
Note the bread crumbs

### Expected result

No duplicate
or 
Home / testMenuLink / testArticle

### Actual result

`Home / testMenuLink / testMenuLink `

![Screen Recording 2020-07-05 at 04 49 21 PM](https://user-images.githubusercontent.com/400092/86536438-87969a80-bedf-11ea-974d-130468435ac9.gif)

### Additional comments

might happen in Joomla 3 - not tested.

**Comment by chmst** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30001">issues.joomla.org/tracker/joomla-cms/30001</a>.</sub>

**Comment by richard67** [comment]
@chmst In J3, too?

**Comment by chmst** [comment]
@richard67 not in the sites I have available for frontend editing. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30001">issues.joomla.org/tracker/joomla-cms/30001</a>.</sub>

**Comment by richard67** [comment]
It **_is_** an issue on staging, too:

![j3-view-article-frontend](https://user-images.githubusercontent.com/7413183/87223438-37a35200-c37d-11ea-9d21-5afaa28057f1.png)

![j3-edit-article-frontend](https://user-images.githubusercontent.com/7413183/87223441-3a05ac00-c37d-11ea-92b5-7bc4b0eb2b6d.png)

**Comment by richard67** [comment]
Confirmed on J4 (4.0-dev) and J3 (staging).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30001">issues.joomla.org/tracker/joomla-cms/30001</a>.</sub>

**Comment by PhilETaylor** [comment]
To be clear, I named the menu item and the article title different and it was the menu item text added twice

**Comment by richard67** [comment]
Ah, ok, thanks for the info.

**Comment by richard67** [comment]
Confirmed, it's the menu item taking precedence for both the good and the bad, additional breadcrumbs item.

**Comment by richard67** [comment]
Hmm, it seems we even have more issues with breadcrumbs when editing articles in frontend.

Scenario: I have a menu with one home page item, which is a "featured articles" view for any category, and I have one featured article with title "Test article 1" in category "Uncategorized".

When going to the home page I see that one article, breadcrumbs is "Home" without a link => OK.

When now on the Home page edit that article, I get breadrcumbs "Home -> Home", with the first one being a link and the second one not, as described here in this issue. The first link leads back to the normal, not edit view, on the home page.

Nothing new so far.

But when I do that from the single article view (for which there is no menu item) it is even more weird.

So when on the home page clicking the title = link to the article, I get breadcrumbs "Home -> Uncategorized -> Test article 1", with the last one not being a link => OK.

But when I now edit that article, I get "Home -> Home".

That may be expected behavior, but one would expect "Home -> Uncategorized -> Test article 1" in that case, or with the duplicate last item isue here "Home -> Uncategorized -> Test article 1 -> Test article 1".

So from a user point of view the question seems to be: Where the hell is the random generator generating those breadcrumbs?

Now let forget about how it works now and think about what would make sense.

When editing the article, it could make sense to have the link to the article in the breadcrumbs, because that link leads back to the normal, not editing view. The last item could be then something showing that we are in edit mode, e.g. "Home -> Edit", or "Home -> Uncategorized -> Test article 1 -> Edit".

Ok, wishful thinking, but that's how I would like it.

So or so this has no meaning for SEO, like other breadcrumbs issues might have, because a search engine will never see an article in edit mode.

**Comment by alikon** [comment]
imho breadcrumbs/pathway needs a fully rethink/redesign

**Comment by PhilETaylor** [comment]
Still an issue in 4.1-dev

<img width="996" alt="Screen Shot 2022-03-06 at 21 56 36" src="https://user-images.githubusercontent.com/400092/156943787-1eb641d9-9eab-4497-9ba4-711f0d3f2921.png">
