### ISSUE TITLE
[4.0] Restore Article from history not working

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30006]
### Steps to reproduce the issue
com_contenthistory must be active and save_history must be "on" (this is by default)

Open an article, change something and save.
Re-open the article, click the Versions Button.
The modal with the history opens.
Select one of the older Version san click on "restore".

### Expected result
The older version replaces the newer one (as in 3.9..)

### Actual result
The newer version remains unchanged.

### System information (as much as possible)
win10, php 7.4, FF and edge

**Comment by PhilETaylor** [comment]
how is this different to https://github.com/joomla/joomla-cms/issues/30002 ?

**Comment by ReLater** [comment]
Frontend should be fixed with https://github.com/joomla/joomla-cms/pull/30004 but isn't. Just some side effects are fixed. **Before:** the edit screen closes without text changes. In the backend I saw then a locked symbol in articles overview (after reloading the articles view).

Frontend/Backend: Both don't restore correctly. Doing nothing.

For all cases I tried to restore the oldest version. I don't know if that matters anyhow.

**Comment by ghost** [comment]
Click on ```Restore``` of first Version got:

![Screen Shot 2020-09-19 at 09 54 17](https://user-images.githubusercontent.com/70466955/93662178-741aba80-fa5e-11ea-8909-39236b3867de.png)

Click on newer Version works:

![Screen Shot 2020-09-19 at 09 57 29](https://user-images.githubusercontent.com/70466955/93662200-a4625900-fa5e-11ea-9a4f-608701bc45f0.png)

**Comment by Quy** [comment]
@chmst Please confirm this is fixed per #32932.

**Comment by chmst** [comment]
Fixed with #32932. Thank you!
