### ISSUE TITLE
[4.0] Plugin Manager - TinyMCE - Duplicate IDs

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30015]
### Steps to reproduce the issue

1. In your Plugin Manager, open TinyMCE.
2. Open your browser inspector and search for `captionTable`

### Expected result

Unique IDs

### Actual result

3 instances of the `captionTable` ID

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
... and there can be even more if you add more sets

For anyone who wants to work on fixing this the problem is that the form is repeated for each set so any field that uses an ID will be duplicated for each set

![image](https://user-images.githubusercontent.com/1296369/99066735-5458cc00-25a1-11eb-9069-3fa28cbb0151.png)

**Comment by bembelimen** [comment]
Is there any (a11y?) reason for having this IDs (they are all over the whole Joomla!)

**Comment by HLeithner** [comment]
closed because of PR #31829
