### ISSUE TITLE
[4.0] Missong icon on Crop button

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30024]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_templates&view=templates`
2. `Cassiopeia Details and Files`
3. Click `template_thumbnail.png`

### Actual result

Missing icon on `Crop` button

![screeny2](https://user-images.githubusercontent.com/2019801/86574663-13ef9e80-bf6e-11ea-875a-05045666c182.png)

**Comment by infograf768** [comment]
Found where is the issue but I don't know how to solve.
The button itself has a class made up with the icon class

<img width="775" alt="Screen Shot 2020-07-07 at 10 55 03" src="https://user-images.githubusercontent.com/869724/86753561-731de380-c040-11ea-9e00-10419f167ff1.png">

It should only have `btn btn-primary`

This comes from the `renderButton()` method in `/libraries/src/Toolbar/ToolbarButton.php`
`$options['btnClass'] = 'button-' . $this->getName() . ' ' . ($options['btnClass'] ?? '');`

where `$this->getName()` = the icon class defined in the HtmlView
`ToolbarHelper::custom('template.cropImage', 'fas fa-crop', 'fas fa-arrows-alt', 'COM_TEMPLATES_BUTTON_CROP', false);`

Other instances of `ToolbarHelper::custom(` do not have this issue.

@N6REJ 
Any idea?

**Comment by infograf768** [comment]
Ok, found it.

The issue is that **this is the ONLY HtmlView** using directly some `fas fa-stuff` as icon for quite a few toolbar buttons.
All other use wordings which correspond to icons.
Example here `envelope`:
`ToolbarHelper::custom('mail.send', 'envelope.png', 'send_f2.png', 'COM_USERS_TOOLBAR_MAIL_SEND_MAIL', false);`
will use as button class:
`<button class="button-envelope  btn btn-primary" type="button">`

**Comment by infograf768** [comment]
One solution is to modify the custom method
```
	public static function custom($task = '', $icon = '', $iconOver = '', $alt = '', $listSelect = true, $formId = null)
	{
		$bar = Toolbar::getInstance('toolbar');

		// Strip extension.
		$icon = preg_replace('#\.[^.]*$#', '', $icon);
		$icon = str_replace('fas fa-', '', $icon);  // ADD THIS LINE to STILL GET A CUSTOM CLASS

		// Add a standard button.
		$bar->appendButton('Standard', $icon, $alt, $task, $listSelect, $formId);
	}
```
to get
`<button class="button-crop  btn btn-primary" type="button">`

What do you think?

**Comment by N6REJ** [comment]
I'm having a hard time thinking clearly today but my first question is why are we using .png for class's?  Did we plan on using images then change our mind?  Whats the real purpose?

**Comment by infograf768** [comment]
It is a remnant of older code. 2.5.0 and 3.0+ have these images in the images folder of the template. It became unnecessary when we started to use icomoon.
In 2.5 they were used in the css
`.icon-32-featured					{	background-image: url(../images/toolbar/icon-32-featured.png);	}`

Instead of getting rid of these (the images could be used for B/C and were kept in the template), was coded `$icon = preg_replace('#\.[^.]*$#', '', $icon);` for .png not to be present in the button class.

![Screen Shot 2020-07-08 at 06 58 28](https://user-images.githubusercontent.com/869724/86878314-ea0eb700-c0e8-11ea-9e9a-db024551db51.png)

I guess we can safely get rid of these now as these images are not provided anymore in 4.0 template.

Anyhow, this can be for another patch as this is not the original issue here.

**Comment by N6REJ** [comment]
I'll have to leave this to better folks then me.. I think your on to something though @infograf768 
I think aside from your fix, the use of toolbar::custom needs to be consistent.

**Comment by N6REJ** [comment]
@infograf768 it should not be
`<button class="button-crop btn btn-primary" type="button">`
but instead `<button class="btn btn-primary" type="button">`
the class belongs on the span.

**Comment by Quy** [comment]
PR #30206
