### ISSUE TITLE
[4.0] Contact display ignores form settings

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30052]
### Steps to reproduce the issue

Create a contact
Create a menu item for the contact
View the Site, select the Menu item - see the Contact data and email form.
Edit the contact, set Display / Contact Information to Hide, set Form / Contact Form to Hide
View the Site - reload the Contact menu

### Expected result

No contact and no email form (J3 behaviour)

### Actual result

Contact data and email form are displayed.

### Additional comments

There my be more Contact issues - just started checking.

**Comment by Bakual** [comment]
The settings from the menuitem will override the settings from the contact since the menuitem is specific to this contact.
So changing settings in the contact has no effect on your form, you need to change them in the menuitem. That is expected behavior.

If you however instead have a menuitem pointing to a contact category, and from there select your contact, then the settings from your contact will take precedence over the menuitem and your changes will be visible.

**Comment by ceford** [comment]
Thank you for that explanation. I am revising the Help screens so I will make sure that point gets a prominent mention. Closing this issue.

**Comment by ceford** [comment]
Could you explain something else: In the Menu Edit Form for an individual contact, the Mail Options / Contact Form drop down changes from red with Hide selected to green with Show selected. Apart from Red meaning bad and green meaning good, what exactly is the significance of the colour? Something I can put in the Help screen.

**Comment by Bakual** [comment]
I wouldn't say bad or good. Red is usually disabled/off/hide and green is /enabled/on/show.
There are some rare cases where it is different (eg the "Site Offline" setting in the global configuration is the other way around).
