### ISSUE TITLE
file upload_max_filesize warning message omits post_max requirement

### ISSUE THREAD

**Issue by BartelBe** [joomla/joomla-cms#30098]
if php.ini has a too low upload_max_filesize, the system correctly issues a warning and instructions to correct php.ini BUT omits the required post_max setting requirement

### Steps to reproduce the issue
upload a file with administrator/index.php?option=com_installer&view=install

### Expected result
when following instructions, php.ini upload_max_filesize will function

### Actual result
at the very next occasion, Joomla will issue a new warning 
	
Warning PHP Upload Size bigger than POST size.
The value of the upload_max_filesize in the php.ini file is greater than the post_max_size variable. ...

### System information (as much as possible)
this new warning can be AVOIDED by COMPLETING THE INSTRUCTION to set both the upload_max_filesize AND the post_max_size variable to the same value.

**Comment by richard67** [comment]
@BartelBe This has been fixed already for Joomla 4 with Pull Request (PR) #27665 . I plan to make a PR to backport this change to Joomla 3, similar to the same change for the Joomla Update component's Upload & Update feature, which has been implemented with PR #27570 for J4 and will be backported to Joomla 3 with PR #29895 if that will be merged.

Update: I just see your issue is slightly different, it's about the instructions text.

**Comment by Quy** [comment]
PR #31736
