### ISSUE TITLE
Jquery 1.12.4 - JavaScript Libraries with vulnerabilities

### ISSUE THREAD

**Issue by edilei1904** [joomla/joomla-cms#30222]
Good afternoon

According to: https://www.webpagetest.org/ this version of JQuery contains some security vulnerabilities.

Is it possible to upgrade to version 1.12.5, solving this problem? In my applications I had no problems with compatibility.

Joomla_3.9.20-Stable-Update_Package / media / jui / js / jquery.min.js

Att,
Edilei

**Comment by HLeithner** [comment]
Where did you found a 1.12.5 version of jquery? (Last version is 1.12.4 at https://code.jquery.com/jquery/)

We fixed the issue already a long time ago, you can find more information at https://github.com/joomla/joomla-cms/issues/19464

I'm closing this because we backported the fix and our version is not effected

**Comment by edilei1904** [comment]
Sorry, I hadn't checked on github.

The version of 1.12.5 is still unstable.

Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30222">issues.joomla.org/tracker/joomla-cms/30222</a>.</sub>
