### ISSUE TITLE
Actionlog settings dont show components to check and therefore dont save actions

### ISSUE THREAD

**Issue by volandku** [joomla/joomla-cms#30364]
### Steps to reproduce the issue
Old site after many updates, i couldnt repeat this bug on other sites

### Expected result
Must be extensions to choose where to log actions

### Actual result
Nothing shows  ( administrator/index.php?option=com_config&view=component&component=com_actionlogs )

### System information (as much as possible)
doesnt matter (all ok - php 7.2 + all extensions)

### Additional comments
I decide problem
There is no data in #__action_logs_extensions

To fix bug you need to SQL it

```
INSERT INTO `#__action_logs_extensions` (`id`, `extension`) VALUES
(1, 'com_banners'),
(2, 'com_cache'),
(3, 'com_categories'),
(4, 'com_config'),
(5, 'com_contact'),
(6, 'com_content'),
(7, 'com_installer'),
(8, 'com_media'),
(9, 'com_menus'),
(10, 'com_messages'),
(11, 'com_modules'),
(12, 'com_newsfeeds'),
(13, 'com_plugins'),
(14, 'com_redirect'),
(15, 'com_tags'),
(16, 'com_templates'),
(17, 'com_users'),
(18, 'com_checkin');

ALTER TABLE `#__action_logs_extensions`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
```

PS. I checked DB actuality at administrator/index.php?option=com_installer&view=database and it said everything ok
This needs to be fixed

**Comment by richard67** [comment]
@volandku The database checker at `administrator/index.php?option=com_installer&view=database` checks only the structure, i.e. the result DDL (data definition language part of SQL) like CREATE TABLE or ALTER TABLE statements, not the content, i.e. DML (data manipulation language part of SQL), i.e INSERT, UPDATE or DELETE.

What you refer to is missing content.

One explanation for that could be that you have updated the site in past with an outdated method, copy the files and run the database fix (which as I said will not add the missing content like the updater will do when running the complete SQL script), or there was some problem with an update in past so you had to use that procedure to fix it.

The obsolete method can still be found in the docs, and many people are missing the big red box at the top telling that this method is obsolete since 3.5 or so.

So or so, according to your statement "Old site after many updates, I couldnt repeat this bug on other sites" I am almost 100% sure it is caused by something having gone wrong with the past update when the action logs were added (don't remember the version now).

Please check and report back all you know about the update history and if my assumption might be right.

Thanks in advance.

**Comment by volandku** [comment]
Well, maybe 
I support this site not long time so I cant say how exactly it was updated.
Other sites I support long time and updated works fine.

But I think there must be any tool to diagnost this problem cause I spend more then have an hour to understand problem and decide it

**Comment by richard67** [comment]
I see no way to check all content which once was inserted with an update but meanwhile might have been modified. We can’t make the database checker check for content in the same way as doing for the structure, because not all content has unique keys, and content might have been modified later. So I don’t see a general solution for every case of broken content after updates with errors or with wrong methods. For the special case here where we have a more or less hardcoded list of what had to be there for the core, we could implement maybe something similar as we have with the list of core extensions in the extensions helper, but I don’t think that is a good idea. At least I don’t wanna be the one who has to implement it.

So I see this as a won‘t fix, but this is my opinion only, other opinions are welcome.

**Comment by volandku** [comment]
Well, may be at least can be implemented check for any data in table in /administrator/components/com_actionlogs/models/fields/logtype.php ( like count($extensions)==0 )
And system Warning\Error message about no data to disaplay with link to this page for example to easy fix it

**Comment by richard67** [comment]
Maybe. But for sure we can’t do that for every possible data problem from past updates.

**Comment by volandku** [comment]
Agree.
Just this case was abnormal.
No errors, no php warnings, no debug messages,no any data to give any suggestions why actions dont logging at all
I even didnt know there must be components to choose until today I saw it at another site

**Comment by alikon** [comment]
I agree too this is a  won‘t fix
