### ISSUE TITLE
J4 Nightly build of 2020-08-14 kills site

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30365]
### Steps to reproduce the issue

I did a live update this morning.

### Expected result

It usally works fine.

### Actual result

The server returned a "500 Whoops, looks like something went wrong.".

### Additional comments

Stepping through with the debugger I found this fatal error:

Joomla\Database\Exception\PrepareStatementFailureException: Unknown column 'inheritable' in 'field list' in /Users/ceford/Sites/j4beta2/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:141

I did a new install - that has worked fine.

**Comment by ceford** [comment]
For anyone who gets stuck this will fix the problem:

ALTER TABLE `wuj0d_template_styles` ADD `inheritable` TINYINT NOT NULL DEFAULT '0' AFTER `title`, ADD `parent` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL AFTER `inheritable`; 

Where you replace wuj0d with your own database table prefix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30365">issues.joomla.org/tracker/joomla-cms/30365</a>.</sub>

**Comment by richard67** [comment]
@ceford Known issue, should be solved meanwhile for latest 3.10 nightly and 4 nightly, see #30333 and #30363 .

Please check by using the 3.10 nightly of last night (with date of today) ast starting point and the 4.0 nightly of last night for updating. If you have an older 3.10 you can update it to the last 3.10 nightly before updsting to the 4.0 nightly.

If you have the time: Could you check if that works for you and report back the result? Maybe I've made a mistake, you never know. Thanks in advance.

**Comment by ceford** [comment]
As I understand the discussion any J4 Beta installed before today will break on live update but from today live updates will work. So I don't see how I can test. If I remove those two columns I will be back to the 500 error. I am not using 3.10 at all!

If it is the case that updating J4 BetaX-Dev installed or updated before today is broken we could just post a message in the Forum with the fix. I will do that anyway for anyone who falls into the same trap that I did this morning.

**Comment by richard67** [comment]
@ceford 

> As I understand the discussion any J4 Beta installed before today will break on live update but from today live updates will work.

Yes.

> I am not using 3.10 at all!

I see, then I got your issue wrong yesterday. It was not clear to me from which version you did the live update.

Please note that we officially don't support updates betwene nightly builds. This is not the issue here, it is just a general reminder.

We officially supported updating between the betas, and this has been broken now. Not my fault. I had to fix the update from 3.10, which is the more important thing, and the broken update from J4 Beta n (with n < 4) to Beta 4 is a kind of collateral damage we could not avoid, as it seems.

> If it is the case that updating J4 BetaX-Dev installed or updated before today is broken we could just post a message in the Forum with the fix. I will do that anyway for anyone who falls into the same trap that I did this morning.

We will have a hint in the release notes for the next 4.0 Beta 4. But a forum post before that is of course very helpful. If you could create one I'd be happy.

But maybe this issue (broken J4 Beta update) is so important that an info from the release lead would be necessary? Ping @wilsonge ;-)

**Finally, beside all that: I've noticed you help Joomla much with testing and in forum and I think with docs , too. And I think it's time to say a big thank you. Keep on going, it is greatly appreciated.**

**Comment by Fedik** [comment]
please test #30369

**Comment by alikon** [comment]
closing as we have a pr #30369
