### ISSUE TITLE
[4.0] Display of horizontal mod_articles_news module

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#30426]
### Steps to reproduce the issue
Create an article flash module with horizontal display in hand-top position
![Modules___Flash_d_information_-_J4_beta_4_-_Administration](https://user-images.githubusercontent.com/26197929/90748718-d7d08d00-e2d2-11ea-8473-cd5b1ff674d2.jpg)

### Expected result
![affichage-horizontal](https://user-images.githubusercontent.com/26197929/90748758-e1f28b80-e2d2-11ea-8327-16f346259285.jpg)

### Actual result
![Home](https://user-images.githubusercontent.com/26197929/90748776-e9199980-e2d2-11ea-9d94-8c8c45a490e4.jpg)

**Comment by chmst** [comment]
Control-label has a width of 240px which looks strange if there is plenty of place. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30426">issues.joomla.org/tracker/joomla-cms/30426</a>.</sub>

**Comment by chmst** [comment]
@Magnytu2 Your issue is that images are not full width on smaller viewports? Or what would be your proposal?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30426">issues.joomla.org/tracker/joomla-cms/30426</a>.</sub>

**Comment by Magnytu2** [comment]
@chmst Hello, I don't think my problem is the width of the images. Since my goal is to put three articles in three columns. This is why I chose the horizontal layout.

**Comment by Quy** [comment]
Please test PR #30527
