### ISSUE TITLE
[4.0] Frontend: Edit Article like Module

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30558]
### Is your feature request related to a problem? Please describe.
User have to 
click | and click
---- | ----
![001-gear](https://user-images.githubusercontent.com/70466955/92114080-91aa1c00-edf0-11ea-981f-09ac82982c41.png) | ![002-edit](https://user-images.githubusercontent.com/70466955/92114113-9ff83800-edf0-11ea-87a1-744abe5c6cdb.png)

to edit a Article.

### Describe the solution you'd like
Edit Article like Module: A "Edit"-Icon is show if user hover Module.

**Comment by infograf768** [comment]
Since we do not propose any more Print and Mail to a friend which were displayed in 3.x in the dropdown, it looks indeed unecessary to use a cog dropdown.
Also any tooltip for the Edit should use `role="tooltip".
The difference with edit modules, should be the the permanent display (when authorized) and not on hover + the term "Edit" next to it as  done with the dropdown.
Looking into it.

**Comment by infograf768** [comment]
We should get something like
<img width="906" alt="Screen Shot 2020-09-05 at 08 27 42" src="https://user-images.githubusercontent.com/869724/92299339-c08bd380-ef51-11ea-9c25-0e6046b68e63.png">

**Comment by ghost** [comment]
Pull Request #30588
