### ISSUE TITLE
Joomla doesn't display php error/warning 

### ISSUE THREAD

**Issue by Quadratica** [joomla/joomla-cms#30631]
Joomla doesn't display any php errors/warnings, even though when i set "Error Reporting" option to "Development".
I have to develop some joomla extensions, then the first setting i set is this option above, because i absolutly need to be able to see PHP errors.

I found out that joomla fails to display errors because of this code line:
**set_exception_handler(array('JErrorPage', render'));** , this is on the file: "/libraries/cms.php" (at line number 71).

In my opinion when i select "Development", i would like this code line was skipped, what do you think about?

**Comment by ReLater** [comment]
I can't reproduce this issue. I see PHP warnings, errors, notices in Joomla (every day).

Is `display_errors` deactivated on your server the hard way?

**Comment by Quadratica** [comment]
I tried to set server `display_errors` On, but i wasn't be able to see any error message.
Now `display_errors` is dectivated, "Error Reporting" option, i think above option should overwrite server settings.

is there anyone having the same problem of mine?

**Comment by ReLater** [comment]
In the Joomla backend: Check `System > System information > PHP information > display_errors`. If `error_reporting` is activated in Joomla it tries to switch this setting to 1 (= on).

To be on the safe side: If you add code that should show a fatal error on your page, you see a blank, white page? Nothing else?

Did you test already with template Protostar to be sure that it's not a "stupid" template?

The same with setting "Maximum" instead of "Development"?

**Comment by Quadratica** [comment]
To be on the safe side: If you add code that should show a fatal error on your page, you see a blank, white page? Nothing else?
> Only Blank Page

Did you test already with template Protostar to be sure that it's not a "stupid" template?
> I'm using a third party template, yes, it could be a bad template.

The same with setting "Maximum" instead of "Development"?
> Yes

**Comment by Quy** [comment]
Please ask help in Joomla Forum. https://forum.joomla.org/
