### ISSUE TITLE
Installation of joomla-4 beta4 failed.

### ISSUE THREAD

**Issue by fujisawa2238** [joomla/joomla-cms#30674]
hi,
I am investigating joomla-4.
We are looking forward to the release of the new system.

I was looking into beta1 for joomla-4, but recently uploaded to beta4 and it failed and I lost my system. See attached image.

I got the following warning message and modified php.ini.
'Warning: The PHP temporary folder is not set'
But it failed.

I don't know the cause. advice please.

php.ini
post_max_size= 50M
upload_max_filesize= 100M
memory_limit = 256M
max_execution_time = 300
max_file_uploads
upload_tmp_dir

thank you.

**Comment by ghost** [comment]
> I suggest you install a brand new nightly or beta4, not update.

https://github.com/joomla/joomla-cms/issues/30665#issuecomment-694025887

**Comment by richard67** [comment]
> I was looking into beta1 for joomla-4, but recently uploaded to beta4 and it failed and I lost my system. See attached image.

What means "uploaded"? Did you mean "updated", i.e. using the Joomla Update Component?

Or did you just mean you have uploaed beta 4 and unpacked it and that's all you have done? In this case it was not a valid update because database changes never will be applied.

Furthermore it is always a good idea to read release announcements before updating, even if it is a Beta only.

The [release announcement of 4 Beta 4](https://www.joomla.org/announcements/release-news/5822-joomla-4-0-0-beta4-and-joomla-3-10-alpha2.html) says:

> In order to update from Joomla 4.x to any newer release please make sure you configure your Joomla Update Components Options to point to the Update Channel “Testing” and set the Minimum Stability to “Beta” this setting also now supports updates between pre-releases. Specifically for upgrading to beta 4 please also read the following link: https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4

Have you read that, and have you followed the instructions given on [https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4](https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4) ?

**Comment by Scrabble96** [comment]
It's also worth noting that Akeeba backup - if you use it - works on Joomla 4 Beta.

**Comment by richard67** [comment]
> It's also worth noting that Akeeba backup - if you use it - works on Joomla 4 Beta.

?

**Comment by Scrabble96** [comment]
> > It's also worth noting that Akeeba backup - if you use it - works on Joomla 4 Beta.
> 
> ?

@fujisawa2238 ’lost his system’. If s/he had used Akeeba Backup before attempting the update, then all is not lost.

**Comment by Scrabble96** [comment]
> > > It's also worth noting that Akeeba backup - if you use it - works on Joomla 4 Beta.
> > 
> > 
> > ?
@fujisawa2238 ’lost his/her system’. If s/he had used Akeeba Backup before attempting the update, then all is not lost.

**Comment by richard67** [comment]
@Scrabble96 Ahhhhh!!! I need glasses!!!! Instead of "noting" I was reading "nothing" ;-)

**Comment by fujisawa2238** [comment]
Hi,
Thank you for a lot of advice on my post.
Certainly, I think the most reliable method was to install beta4 directly itself.
But I had no other way to get Joomla-beta4. Because the only beta1 I have was my only Jomla-4.
It has to tell my story below.

1. I have failed to install Joomla-4 beta-version many times, beta2, beta3, beta4.
 Because of warning errors are "Error: This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP." and
 "Error: Could not connect to the database. Connector returned error message: Could not connect." to database: MySQL server has gone away. "
2. I asked my server company to resolve this cause. The answer was, "We can't do that individually. You have to solve it yourself."
 I don't have the ability to make that technical solution.
3. If this situation is the same as the stable release of Joomla-4, then even if it's a J4-only system (not a migration from J3), 
 I'm in a situation where I can't use Joomla4,but J-3 was easy to install.
 That is a big problem for my customers (10 more companies).
4. The following information does not seem to be information that anyone can do.
  https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4
5. What I really want to do now is a preliminary survey of Joomla-4 (although I'm planning to move from J3 next time).

Please give me where live in a different language world some advice on what do I do .
Thank you.

**Comment by richard67** [comment]
@fujisawa2238 We are not responsible for your server configuration, and it's clear that this issue here is caused by server malconfiguration. Please ask for support in the support forum [https://forum.joomla.org/](https://forum.joomla.org/). There are also zones in other languages than English in that forum, see [https://forum.joomla.org/viewforum.php?f=542&sid=2f70cf5542ef4809cfce0f594e21d834](https://forum.joomla.org/viewforum.php?f=542&sid=2f70cf5542ef4809cfce0f594e21d834) . Check if you can find your language there. Thanks in advance.
