### ISSUE TITLE
Change 'Kiev' to 'Kyiv'

### ISSUE THREAD

**Issue by nonme** [joomla/joomla-cms#30679]
### Steps to reproduce the issue

System -> Global Configuration -> Server -> Location Settings -> Website timezone

### Expected result

'Kyiv'

### Actual result

'Kiev'

**Comment by njilrem** [comment]
yes, I think this issue has to be solved. The author of the issue is right.

**Comment by metamisha** [comment]
Make Kyiv, not Kiev...

**Comment by HLeithner** [comment]
copy-paste from the timezone datebase:
```
# From Paul Eggert (2018-10-03):
# As is usual in tzdb, Ukrainian zones use the most common English spellings.
# For example, tzdb uses Europe/Kiev, as "Kiev" is the most common spelling in
# English for Ukraine's capital, even though it is certainly wrong as a
# transliteration of the Ukrainian "Київ".  This is similar to tzdb's use of
# Europe/Prague, which is certainly wrong as a transliteration of the Czech
# "Praha".  ("Kiev" came from old Slavic via Russian to English, and "Prague"
# came from old Slavic via French to English, so the two cases have something
# in common.)  Admittedly English-language spelling of Ukrainian names is
# controversial, and some day "Kyiv" may become substantially more popular in
# English; in the meantime, stick with the traditional English "Kiev" as that
# means less disruption for our users.
```

If the timezone database changes the name joomla will follow this in the meantime we will not confuse our users and introduce a mapping layer between joomla and php.

So if you want to change it please suggest the change to IANA

**Comment by richard67** [comment]
Confirmed. It comes from the IANA time zone database. You can find their discussions about this issue in their mailing list [http://mm.icann.org/pipermail/tz/](http://mm.icann.org/pipermail/tz/). I was following that in past because I had to deal with timezones for other purposes than Joomla. See e.g. this thread in their mailing list: [https://mm.icann.org/pipermail/tz/2017-December/025690.html](https://mm.icann.org/pipermail/tz/2017-December/025690.html). And there was much more.
