### ISSUE TITLE
Bootstrap 5 for Joomla 4

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30805]
### Is your feature request related to a problem? Please describe.
In **December 2020**, in 2-3 months a stable version of Bootstrap 5 is released.

Currently, @Joomla 4 uses Bootstrap 4

### Describe the solution you'd like
I suggest skipping Boostrap 4 and releasing a stable version of Joomla 4 along with Bootstrap 5 later this year.

I want Joomla to develop together with Bootstrap and millions of users of this CMS see that this CMS is developing. I do not want Joomla 4 to repeat the mistake of Joomla 3, which came out in 2012 - 8 years ago and we will forever remain with the old technologies at that time.

**Bootstrap 5** [https://github.com/twbs/release#bootstrap-5](https://github.com/twbs/release#bootstrap-5):

- v5.0.0-alpha2 in September 2020 (delayed due to team vacations)
- v5.0.0-alpha3 in October 2020 (additional new features and breaking changes)
- v5.0.0-beta1 in October 2020 (final instance of breaking changes)
- v5.0.0-beta2 in November 2020 (beta bug fixes, possibly a 3rd beta)
- v5.0.0 in December 2020 (stable release)

### Additional context
I remember 4.5 years ago I [suggested](https://github.com/joomla-x/joomla-pythagoras/issues/82) using Bootstrap 4 for Joomla 4, but that was a long time ago. Since then, Bootstrap 4 has gone through its entire life cycle and will no longer be developed.

I think it will not be a very difficult transition from Bootstrap 4 to Bootstrap 5 for everything that has already been done.

Bootstrap 5 offers a better version for **accessibility** and also has **dark theme elements**.

**Comment by zero-24** [comment]
cc @wilsonge

**Comment by Quy** [comment]
https://github.com/joomla/joomla-cms/issues/29944#issuecomment-654227683

**Comment by Ruud68** [comment]
When making your extensions ready for J4 a lot of work needed is to change all your back-end views from BS2.3 to BS4. Changing to BS5 is IMO (as an extension developer) no option as it means redoing weeks (!) of work already done.

Some extension developers are creating their own 'templates' for the backend for their extensions (like acymailing and akeeba), but for me that totally defies the use of the framework and all that it has to offer! You choose Joomla as a framework and rely that you can use it to build your extensions on without code duplication (templates).

Don't think to lightly about replacing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30805">issues.joomla.org/tracker/joomla-cms/30805</a>.</sub>

**Comment by joeforjoomla** [comment]
@Ruud68 you are right! I've spent months of work to redo all my extensions from BS2 to BS4... now having to change again to BS5 just a few months before the release of J4 would be a nightmare!

**Comment by 4digitalworld** [comment]
> 
> 
> @Ruud68 you are right! I've spent months of work to redo all my extensions from BS2 to BS4... now having to change again to BS5 just a few months before the release of J4 would be a nightmare!

There is truth in your words, but it is true for you, but not for your clients.

If you look at this issue from the other side, then the transition from Bootstrap 4 to B5 will be much easier than the transition from Bootstrap 2 to B4.

The development of Bootstrap 4 ends this year. Bootstrap 5 will be relevant for the next 5 years. Which would you choose - the future or the past?

Joomla can lay the foundation for the future, for the next 5 years, so that customers do not complain that a new version of Joomla 4 has been released and it uses outdated technologies. The client is not a fool and knows about new technologies. 

**Ultimately, you will not have to think about changing the design in the next 5 years if you do everything on Bootstrap 5, otherwise, already at the beginning of next year, more and more requests from customers will appear for the transition to Bootstrap 5.**

**Comment by brianteeman** [comment]
Do not confuse the front end and the admin.

**Comment by 4digitalworld** [comment]
> 
> 
> Do not confuse the front end and the admin.

I understand you, but if the admin panel is on Bootstrap 4, it will be very difficult to convince developers to make a front on Bootstrap 5. Until now, almost all developers make a front on Bootstrap 2, and this is in 2020, they use technology that was outdated from 2013. I want to believe in the future.

**Comment by Ruud68** [comment]
Customers (with all respect) do not care about how the back-end looks: bs2 or bs4 /5 it is all the same: it should do what it is supposed to do.
For the front-end that is where the real impact will be. As an extension developer here the issue is not bs2 or bs5 but the site template which is always based on some other framework.

So as an extension developer you have a choice here: create your own layouts based on your own css (then the site front-end template / bs framework version doesn't matter), or pull in the BS version from the back-end and create BS layouts... with all the additional bloat and conflicts with the front-end template as a result.

So for me the issue is not the front-end layouts (as I create my own layouts and css) but the back-end layouts. As said some extension developers are also using their own layouts and css for the back-end (circumventing this issue) but to be honest, that is where my customers really complain about: why does extension X like like this and extension Y look like that (it totally breaks UX for them).
So for the back-end I want (need!) to stick to what Joomla offers, and because we are already on beta all my extension are already migrated to what is in this beta.

**Comment by Ruud68** [comment]
> Joomla can lay the foundation for the future, for the next 5 years, so that customers do not complain that a new version of Joomla 4 has been released and it uses outdated technologies. The client is not a fool and knows about new technologies.

And @sanek4life I totally agree with you! but on the other side: the back-end template is IMO abandoned (try doing a PR against the back-end template, no reaction from any of the devs for months), so making a change like you propose will not add to a 'quick' release... more likely more devs (extension devs) will switch to a passive state again...

**Comment by 4digitalworld** [comment]
> 
> 
> > Joomla can lay the foundation for the future, for the next 5 years, so that customers do not complain that a new version of Joomla 4 has been released and it uses outdated technologies. The client is not a fool and knows about new technologies.
> 
> And @sanek4life I totally agree with you! but on the other side: the back-end template is IMO abandoned (try doing a PR against the back-end template, no reaction from any of the devs for months), so making a change like you propose will not add to a 'quick' release... more likely more devs (extension devs) will switch to a passive state again...

The transition to Bootstrap 5 will be in any case within a year. Development of Bootstrap 4 ends on December 31, 2020, maintenance is ending on December 31, 2021, and Bootstrap 4 will not be supported after December 31, 2021 (**End-of-life**).

So in any case, you will have to switch to Bootstrap 5 within a year. You can do this together with Joomla 4, or for example when Joomla 4.1 / 4.2 is released, or release Joomla 5 in 2022 together with Bootstrap 5, there are many options here.

Joomla 3 lost a lot of users because it used Bootstrap 2 (like many developers of the Joomla 3 extensions).

**Comment by Ruud68** [comment]
every body can switch to BS5, just install a (front-end) template that supports that: no (end) users lost here. If you as an extension developer want to base your extension on BS5, just package BS5 as part of your extension and load it: no need for BS5 in Joomla needed for that.
I am more likely to abandon Joomla if I am 'forced' to create my own layouts for the back-end (because with little more effort I decouple it from the framework and 'migrate' to e.g. WP), again talking about the back-end here :)

**Comment by joeforjoomla** [comment]
Actually the problem is the backend, once all extensions have been refactored from BS2 to BS4 it's a massive rework to do again a change to BS5. The frontend is not the problem.
However in December 2020 Joomla 4 should be at least in RC, so having a huge shift at an RC stage is not doable.

**Comment by alikon** [comment]
v5.0.0-alpha2  was released yesterday https://github.com/twbs/bootstrap/releases/tag/v5.0.0-alpha2
so i don't think we can realistic plan to release j4 stable with  bs5..... maybe we can re-think about it for 4.1 or later

**Comment by zero-24** [comment]
Well beta is planed for october and stable for december. Should't @wilsonge take the decision on such a critical thing?

**Comment by HLeithner** [comment]
I would say nothing has changed since alpha1 (Quy already mentioned https://github.com/joomla/joomla-cms/issues/29944#issuecomment-654227683) so we can close this till a RC comes up. But I think it's nothing we can really consider if we hold our timeline.

**Comment by 1337180** [comment]
Joomla 4 is going to be a huge step forward, major rewritting plugins, bootstrap 5 is the future, I think Joomla needs to do this (go for bootstrap 5) to stay relevant and updated

**Comment by breebee** [comment]
Jesus, after spending a year forcing all my components to use bootstrap 4 I was so excited that joomla 4 will ship with bootstrap 4, but I didnt even think of bootstrap 5... I also have a bootstrap 4 admin backend so this is really frustrating as a dedicated joomla user for almost 10 years I must advise to make this a priority. Joomla has made my life more difficult then it needs to be, just, because, of bootstrap + jquery being behind on everything im trying to integrate. Plugins to prevent joomla from even loading bootstrap 2/3 then creating a completely blank joomla template , then retro fitting every single view... Please do not make us go through this garbage again. Maybe an script to automate migration, run through all files replace col-md-4 with ect ect or something.. My heart just exploded when I found out theres bootstrap 5 on the way with joomla 4 relese candidate. But why even use a framework... joomla should have its own css and js library or use no css or js. I would prefer the latter, get rid of all this nonsense and leave crispy clean blank template with joomla only working php and the database. How bout that.. Sorry for my anxiety attack, you deserve it

**Comment by genr8r** [comment]
For those still following this "closed" issue, I want to briefly state that I would support including BS5 in J4.

I understand that this is breaking the rules of our release cycle being that we are in feature lock for our own beta. I understand that there will be communications to be had with our extension devs. We can either have those conversations now or spend the entire lifecycle of J4.x explaining why we are supporting an old framework. I did get the frontend/backend distinction up above, but agree that splitting frameworks between the two is unnecessary bloat. I also understand that this might mean shipping a beta framework with our first RC. RIght now BS is saying:
- v5.0.0-beta2 in January 2021 (beta bug fixes, possibly a 3rd beta)
- v5.0.0 in February 2021 (stable release)

We are likely weeks away from avoiding potentially years of headaches.

I am not saying this is what we "should" do. **I trust our Production team to make the best call** based on: 
1. the work they need to do to make the 11th hour upgrade.
2. and for what it would mean for our extension developers.

**I AM saying that I would strongly support BS5 if that is decision.** I would also work with the relevant parties to handle comms with our extension developer community if that is helpful.

I am sorry to "reopen" the debate with my comment here. I just wanted to provide any assurance I could to production in what I know are time sensitive decisions.
