### ISSUE TITLE
"System - WebAuthn Passwordless Login" plugin enabled by default on Joomla 4 Installation

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-cms#30905]
### Steps to reproduce the issue

* Install Joomla 4 Beta 4
* Go to Global Configuration
* On the Server tab, change Force HTTPS to either "Administrator Only" or "Entire Site"
* Go to System > Plugins
* Search for "auth" to filter for Authentication plugins
* "System - WebAuthn Passwordless Login" is enabled

### Expected result
To avoid confusion when enabling HTTPS on new J4 websites, the "System - WebAuthn Passwordless Login" plugin should be ~~disabled by default, or~~ properly documented in JDOCS as a new feature.

### Actual result
When you switch on HTTPS for your site, your login module has the "Web Authentication" button appear unexpectedly and without administrator expecting to see it (based on J3 experience).

![image](https://user-images.githubusercontent.com/5515866/94988275-5fd2d380-05af-11eb-918b-9a0ae027a9af.png)

**Comment by particthistle** [comment]
Following initial feedback from @zero-24, currently crossing out the "disable" part of the request, and leaving this here for discussion as well as an open Documentation Required item.

For details that need to be reworked into Documentation see: https://github.com/joomla/joomla-cms/pull/28094

**Comment by zero-24** [comment]
I have just added the docs required label here thanks. Yes all details and a baseline for that document can be found here: https://github.com/joomla/joomla-cms/pull/28094

**Comment by particthistle** [comment]
Raised this in relation to testing https://github.com/joomla/joomla-cms/pull/30897

I noticed to there's a handful of issues needing addressing too on WebAuthN including a Release Blocker at time of writing.
https://github.com/joomla/joomla-cms/issues?q=is%3Aissue+is%3Aopen+webauthn

**Comment by particthistle** [comment]
Documentation started:
https://docs.joomla.org/WebAuthn_Passwordless_Login

**Comment by PhilETaylor** [comment]
I know last time I asked why I was shot down, but if this plugin is going to be enabled by default, then the other two factor authentication plugins should be enabled by default too.

The argument against it last time was that "2fa needs something else set up on a users phone etc..." well that argument is moot now you have enabled by default webauthn which requires users to buy a USB key!

The other argument agains 2fa being enabled by default was that the "secret key field" should be confusing being always shown... well Webauthn being enabled by default will now show (on https) the webauthn button, so again that argument is moot now too.

So once again I propose that 2fa should be enabled by default out of the box the same way webauthn is. 

It can always be turned off - like webauthn - if a site admin doesn't want that feature

**Comment by brianteeman** [comment]
Webauthn does not require a USB key. There are other options

**Comment by PhilETaylor** [comment]
I know that. I use a MacBook Pro with fingerprint reader too but the point is you ALWAYS need a hardware device for webauthn, whereas the same is not true for 2fa codes, which can be generated by software like 1Password which can even scan QR codes

Preciously the argument that not enabling 2fa by default because “it can’t be used without something else” is now an invalid argument as for webauthn you need hardware, specific compatible hardware, and a specific compatible browser, and a specific compatible operating system, and valid ssl - much more stringent set of conditions than 2fa with generated codes!!!

The decision - as always - is not mine to make - joomla will do whatever it wants, but let history state the reasons given previously for not enabling 2fa by default out of the box are now moot if webauthn is enabled by default

And like I said, both can be easily enabled/disabled after installation by the site admin, so in the end it doesn’t matter, but joomla should promote security best practice with the same passion and aggression that accessibility has been getting recently...

**Comment by PhilETaylor** [comment]
Deleted my comments - Im no longer interested in commenting on 2fa/webauthn issues. Im done.

**Comment by brianteeman** [comment]
lol

**Comment by brianteeman** [comment]
There doesnt appear to be any reason for this Issue to remain open?

**Comment by kitepascal** [comment]
> Webauthn does not require a USB key. There are other options

I did not find a solution for Android yet. Am I missing something?


So I agree with that until theres a cross-mobile fingerprint solution:

> 99% of users won't use WebAuthn. Showing the button by default in the backend login is simply confusing. It should be treated as the 2FA plugin, enabled only when needed.

As an option its a good thing. But enabled by default is only confusing for now.


I thought about letting me implant my car keys, so I surely wont put an USB stick in my pocket.

**Comment by chmst** [comment]
Closing - continued in https://github.com/joomla/joomla-cms/issues/36060
