### ISSUE TITLE
[4.0] Sample Data multingual - twice

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30929]
### Steps to reproduce the issue
Upgrade joomla 3.10alpha to joomla 4beta

### Expected result
there is ONE multilingual sample data plugin

### Actual result
Two are listed
![image](https://user-images.githubusercontent.com/1296369/95117075-df8fa800-073f-11eb-920f-e37da0bf1635.png)
![image](https://user-images.githubusercontent.com/1296369/95117106-eae2d380-073f-11eb-87fd-a46d1f20fa76.png)

### Cause
This is because there are **two** database records for the plugin in #__extensions

Perhaps caused by having both
https://github.com/joomla/joomla-cms/blob/c4db4676cff8f15734b3e5b445d4eb17739da762/administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-11.sql#L1-L4

https://github.com/joomla/joomla-cms/blob/c4db4676cff8f15734b3e5b445d4eb17739da762/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-31.sql#L1-L3

**Comment by infograf768** [comment]
Looks like the first one should be deleted

**Comment by richard67** [comment]
Since both of the update SQL scripts are from before Beta 1 and so from before our update promise, we can just delete one of the 2 duplicate insert statements. I assume the one in 4.0.0-2018-06-11.sql where it has wrong enabled status.

In addition, we need a new update SQL for updating previous Beta versions to the future Beta which will contain the fix for this issue. The SQL needs to be a bit clever, it needs to get the lowest of the IDs of the duplicate records to delete that one. I can help with that if necessary. Maybe I can later make a PR even, but right now I don't have the time.

**Comment by richard67** [comment]
I'll work on it.

**Comment by richard67** [comment]
The 2nd plugin has been added with commit https://github.com/joomla/joomla-cms/commit/fc0d2ea3c8e9f9451a1bdda8311e4c7640e7edef#diff-97d026690fd483a67b57a74953ef4a50 .. it seems that was a mistake.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #30945 .
