### ISSUE TITLE
[4.0] mod_search - phantom module

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30927]
### Steps to reproduce the issue
Upgrade joomla 3.10alpha to joomla 4beta

### Expected result
com_search and its plugins and modules are still present - the docs say there will be an update site for this now uncoupledextension.

I should alternatively be able to uninstall the  component and its associated plugins and modules

### Actual result
Create a new module
![image](https://user-images.githubusercontent.com/1296369/95116748-68f2aa80-073f-11eb-8c31-d667287741dc.png)

Oh that looks strange it says mod_search not Search - never mind create the module anyway
![image](https://user-images.githubusercontent.com/1296369/95116772-7445d600-073f-11eb-8b52-8b59e5cd454d.png)

Go to Extensions: Manage
![image](https://user-images.githubusercontent.com/1296369/95112183-8b34fa00-0738-11eb-85f5-b9d4a11199ea.png)

Oh that looks strange it says mod_search not Search - never mind uninstall it anyway
![image](https://user-images.githubusercontent.com/1296369/95112325-b0c20380-0738-11eb-8c4d-a8a4388f3a18.png)

### Explanation
During the second stage of the update this script is run `administrator/components/com_admin/script.php` which is for removing files

It is removing the code and language file for mod_search

As nothing else for the search component is removed then this probably should not be removed either. OR if it is going to be removed then all of search should be removed INCLUDING the sql record in #__extensions

This record in #__extensions is what is creating the phantom record in the list of extensions

**Comment by richard67** [comment]
As far as I understand we should not delete the record in database and also not delete the files and folders because com_search might be present when updating, except that the maintainers of com_search decide to keep completely separate versions for J3 and J4 without any migration path, so the J3 component has to be removed. But I don't think that's the way to go.

So PR #25559 has to be extended by ignoring the com_search files and folders when creating the list of files and folders to be deleted for adding that to script.php. => Ping @wilsonge .

**Comment by brianteeman** [comment]
@wilsonge ping again

**Comment by wilsonge** [comment]
Manually patched the script.php for now (see linked commit). Also added it into my PR here https://github.com/joomla/joomla-cms/pull/25559 for future regenerations of the script items

**Comment by wilsonge** [comment]
Also thanks for the reping!

**Comment by brianteeman** [comment]
Thanks @wilsonge
