### ISSUE TITLE
J3.9.21 ACL problèm in admin articles view : edit state button actived in categories not authorised

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#30923]
Hi.

In com_content ACL in articles (list) view the button state is active in categories where user cannot publish.

I think the problem is on the $user->authorise('core.edit.state', 'com_content.article.' . $item->id) wich don't take the edit state option of the categorie or somethink like this.
But it's strange that in case of article in categorie authorised in modification with edit state to false for the current users group, the button in well desactived ($canChange is false).

To temporarily correct this I overloaded the admin view with change of the line 139 of articles.php

$canChange  = $user->authorise('core.edit.state', 'com_content.article.' . $item->id) && $canCheckin;

to

$canChange  = $user->authorise('core.edit.state', 'com_content.article.' . $item->id) && $canCheckin  && ($canEditOwn || $canEdit);

Regards

**Comment by joomdonation** [comment]
I don't check on Joomla 3 but on latest Joomla 4, I could not re-procedure the issue. And by looking at the code, the code for checking edit state permission of article looks perfect fine to me. 

With that said, I would say that this issue is invalid (at least for Joomla 4), and close this issue. If you still see the issue with Joomla 4, please give us exactly step by step what we need to do to see the problem you mentioned so that we can check it further if needed.
