### ISSUE TITLE
problem whith asset table which extend nested class wich declare an alias property/row

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#30944]
Hi.

The asset table class define in /librairies/src/Tables/Asset.php extend Nested table wich have a proprety "alias"
But the asset table don't have a row named "alias".

This make an exception when we call a JTable store method whith update null param at true (for exemple for update a category).

Regards.

**Comment by Hackwar** [comment]
Hello @rolandalsace, thank you for reporting this issue. I can see that this was indeed a problem in Joomla 3, since at that time the CMS database class simply took the whole object and tried to insert every attribute. With Joomla 4 we switched to the framework database package which only inserts attributes which have a column in the table. This means that this issue is solved when updating to Joomla 4 or later. I'm sorry that responding to this issue took so long. Since this has since been solved, I'm closing the ticket now.
