### ISSUE TITLE
[4] Incorrect integer value: 'Its2020AndStillJoomlaDoesntValidateInput' for column 'header' at row 1

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31003]
### Steps to reproduce the issue

Joomla 4 Admin Console
Redirects Component -> Options -> Enable Advanced Mode -> save
Redirects Component -> New

Set Redirect Status Code to string "Its2020AndStillJoomlaDoesntValidateInput"

Click Save.

### Expected result

Validation exception. Redirect Status code should be something in 3xx range.

### Actual result

No validation until the user supplied value hits the database layer and then a mysql error is displayed to the user:

`Save failed with the following error: Incorrect integer value: 'Its2020AndStillJoomlaDoesntValidateInput' for column 'header' at row 1
`
<img width="1601" alt="Screenshot 2020-10-08 at 22 17 56" src="https://user-images.githubusercontent.com/400092/95514650-32719580-09b4-11eb-9b05-60e4b43d44a8.png">

### Additional comments

Also note that saving a redirect status code of `999` is validated as ok and the link saved :-( 

<img width="965" alt="Screenshot 2020-10-08 at 22 19 57" src="https://user-images.githubusercontent.com/400092/95514774-68af1500-09b4-11eb-953c-dd1c50973ede.png">

**Comment by brianteeman** [comment]
I know how to partially fix this
```
		<field
			name="header"
			type="redirect"
			label="COM_REDIRECT_FIELD_REDIRECT_STATUS_CODE_LABEL"
			description="COM_REDIRECT_FIELD_REDIRECT_STATUS_CODE_DESC"
			default="301"
			filter="integer"
			validate="number"
		/>
```

But that just results in a 0 being saved when you try to save a string

**Comment by PhilETaylor** [comment]
and of course 0 is not a valid HTTP Status Code ;-)

**Comment by PhilETaylor** [comment]
and of course 0 is not a valid HTTP Status Code ;-) ... even though its sometimes used as an error code :)

**Comment by Llewellynvdm** [comment]
This should not be hard to fix at all... but why say **Its2020AndStillJoomlaDoesntValidateInput** that is just not true. 

@brianteeman is right that this is a partial fix, since as you may know Joomla can have its own special validation rule for any field, so there seems to be at least one simple option here... lol :+1: 

- We add a special validation rule for this field to insure that only valid HTTP status codes are used.

I see the code was worked on [about three years ago](https://github.com/joomla/joomla-cms/blame/staging/administrator/components/com_redirect/models/forms/link.xml#L104)... but I am sure more can be done. Tell me @PhilETaylor are you willing to push any code towards this should the Release Leads agree?

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31016 (for staging).
