### ISSUE TITLE
[4] PopUp New file - Site Template

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#31033]
### Steps to reproduce the issue
Go to:
- Site Templates
- Cassiopeia Details and Files
- New File

PopUp is not well formatted
![Schermata 2020-10-10 alle 10 45 53](https://user-images.githubusercontent.com/5918444/95651034-a19bd680-0ae7-11eb-8860-acbd82ebd4f3.png)

I expect a larger PopUp with more spaced out elements.

### Actual result
I expect a larger PopUp with more spaced out elements.

### System information (as much as possible)
- Websito
- Chrome  86.0.4240.75 (Build ufficiale) (x86_64)
- macOS 10.15.7

**Comment by ghost** [comment]
cant confirm modal-size-issue (macos).

#### firefox

![image](https://user-images.githubusercontent.com/71960554/95651794-f55cee80-0aec-11eb-91a9-5a7b5051577b.png)

 #### safari

![image](https://user-images.githubusercontent.com/71960554/95651838-2e955e80-0aed-11eb-9056-6ed0d0a5a586.png)

**Comment by particthistle** [comment]
Layout is using jviewport-width60 instead of jviewport-width80, which sets the modal to 60% of the viewport width.

<code>.modal-dialog.jviewport-width60 {
	width: 60vw;
	max-width: none;
}</code>

Changing the modal to use jviewport-width80 for smaller screens would resolve the issue.

The modal also has a height setting locked in that sees the menu tree overflow off the bottom of the modal as it uses 50vh.
<code>
.jviewport-height50 {
	height: 50vh;
}
</code>


**Additionally, same problem occurs when you click on Manage Folders**
![image](https://user-images.githubusercontent.com/5515866/95651677-b86a1980-0b37-11eb-8e4f-32b408d6ed32.png)

**Mobile is also a problem:**
![image](https://user-images.githubusercontent.com/5515866/95651872-e00db180-0b38-11eb-8d37-ec89ea17c378.png)


### Proposed solution
- Change the two modals to use jviewport-width80 and jviewport-height70
- Add a max-height:65vh value to .tree-holder to stop the overflow.

That would look like following at 1920x1080.
![image](https://user-images.githubusercontent.com/5515866/95651717-0252ff80-0b38-11eb-8d97-7c24544e1417.png)

And this at 1366x768
![image](https://user-images.githubusercontent.com/5515866/95651788-5827a780-0b38-11eb-8c11-f0dcd9aaf0ce.png)

**Comment by infograf768** [comment]
Issue confirmed here on Firefox. 
Also for Manage Folders where Close and Delete buttons are broken.
Please propose patch

**Comment by PhilETaylor** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/30954

**Comment by infograf768** [comment]
@particthistle 
I'm afraid your proposal will not work on different screen sizes.
<img width="1095" alt="Screen Shot 2020-10-10 at 12 13 50" src="https://user-images.githubusercontent.com/869724/95652554-3c011780-0af2-11eb-86c4-8c69883e2536.png">
<img width="595" alt="Screen Shot 2020-10-10 at 12 13 12" src="https://user-images.githubusercontent.com/869724/95652555-3efc0800-0af2-11eb-83b4-555928e7a215.png">

**Comment by roland-d** [comment]
Closing as we have a PR #31037
