### ISSUE TITLE
[4.0] TinyMCE change Button .tox-statusbar__wordcount text to text constant

### ISSUE THREAD

**Issue by nadjak77** [joomla/joomla-cms#31136]
### Steps to reproduce the issue

install f.e. german installation pack 
go to article - new article
see the TinyMCE 
on the right bottom you can see
![grafik](https://user-images.githubusercontent.com/37655645/96347042-56f9fb80-109f-11eb-8b30-c33753811f1d.png)

This is not a languagestring, so it cannot be translated

### Expected result
should be translation string

### Actual result
there is no constant in the languagefile

**Comment by SharkyKZ** [comment]
That's how it's translated in German language pack

    PLG_TINY_BUTTON_TOGGLE_EDITOR="Editor an/aus"

**Comment by nadjak77** [comment]
I do Not mean the Editor-Button, but the text „words „ above the blue button

**Comment by brianteeman** [comment]
This is part of TinyMCE, not joomla

**Comment by bembelimen** [comment]
The reason is very easy, in ```media/vendor/tinymce/langs/de.js``` (and all other language files) the string is:
```
"Words: {0}": "W\u00f6rter: {0}",
```

but should be:
```
"{0} Words": "W\u00f6rter: {0}",
```

or https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/themes/silver/main/ts/ui/statusbar/WordCount.ts#L22

has to be changed from:
```
'{0} ' + mode
```
to
```
mode + ': {0}'
```

(to test you can change the ```media/vendor/tinymce/themes/silver/theme.min.js```, search for ```"{0} "+e``` and change to ```e+": {0} "```)

So as @brianteeman said, you have to report it at TinyMCE.

**Comment by alikon** [comment]
closing as non core issue
please report on https://github.com/tinymce/tinymce

**Comment by brianteeman** [comment]
Thanks for digging into this @bembelimen

**Comment by nadjak77** [comment]
Thanks. I will report it at TinyMCE
