### ISSUE TITLE
[4.0] Revert PR #29571

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#31165]
PR #29571 breaks admin login.

### Steps to reproduce the issue
log into admin on working install
pull latest commits from 4.0-dev
try logging into admin
notice nothing happens.

### Expected result

can login admin

### Actual result
login button does nothing.

### System information (as much as possible)

4.0-dev 19oc20 1900cst pull

### Additional comments
reverting commit allows logging in again
ran both composer install & npm ci but didn't fix the issue.

**Comment by SharkyKZ** [comment]
I can't reproduce the issue.

**Comment by richard67** [comment]
@SharkyKZ On a new install of current 4.0-dev I can't reproduce either.

But as @N6REJ wrote, he has pulled the changes on an existing installation and then had the issue.

So maybe we will have an issue when not making a new installation but updating?

=> It needs to test if a J4 Beta 4 can be updated to latest nightly J4 build (which includes #29571 ) to see if there is an issue when not having made a new installation.

In addition it should also be tested in a 3.10 can be properly updated to latest nightly J4 build without running into the issue.

I'll try to find time later for testing that, but if someone else could test that, too, it would be safer because I might make mistakes.

**Comment by SharkyKZ** [comment]
My guess you need to clear browser cache. If you're using some weird browser, https://github.com/joomla/joomla-cms/pull/31169 might help.

**Comment by brianteeman** [comment]
Can not confirm

**Comment by N6REJ** [comment]
idk what happened.. its working fine now.
