### ISSUE TITLE
Message in category blog is not user-friendly

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31193]
### Steps to reproduce the issue
Make a Category Blog where no articles are found. The following message will not be very helpful for users. Users know nothing about categories or subcategories. 

### Expected result
Ad non-native speaker I have no suggestion. Something like "Sorry, at the moment we have no articles here."

### Actual result

<img width="754" alt="bad-message" src="https://user-images.githubusercontent.com/1035262/96745289-45c62d00-13c6-11eb-9f00-25fc5e7c1f05.PNG">

### Additional comments
In all versions

**Comment by jiweigert** [comment]
I'm totally fine with just the first part: ```There are no articles in this directory.```
No Sorry, as an appology can't change the fact, that ```There are no articles in this directory.``` ;-)

And that sub-categories may contain articles... is a useless, unneeded info, because I'm looking for articles in **this** category.

My 2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31193">issues.joomla.org/tracker/joomla-cms/31193</a>.</sub>

**Comment by chmst** [comment]
Or remove the message? If there is nothing, why tell the user that there is nothing?

**Comment by ghost** [comment]
> Or remove the message?

Message give user security, that there are ´No Matching Results´ (message in backend).

**Comment by chmst** [comment]
There is a field where the message can be swithed off "show_no_articles" and with language overrides it can be changed. So close this issue, every translator can make it more userfriendly.
