### ISSUE TITLE
[4] B\C of type="templatestyle" and multiple="true" plus fancy-select.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#31249]
### Steps to reproduce the issue
- In Joomla 3 add or change a field of `type="templatestyle"` with `multiple="true"` like this:
```
<field name="whateverName" type="templatestyle" default=""
 label="Select whatever"
 multiple="true"
 description="">
</field>
```
- You get automatically a "chosened" field

![27-10-_2020_15-25-10](https://user-images.githubusercontent.com/20780646/97319719-6af6e780-186d-11eb-8bbe-3cd03073a0ab.jpg)

- In Joomla 4 add or change a field of `type="templatestyle"` with `multiple="true"` like this. Don't forget the `layout` attribute that works as expected wit `list` fields:

```
<field name="whateverName" type="templatestyle" default=""
 label="Select whatever"
 multiple="true"
 layout="joomla.form.field.list-fancy-select"
 description="">
</field>
```
- Field doesn't use the `fancy-select` feature. Multi selection needs `STRG`.

![27-10-_2020_15-25-43](https://user-images.githubusercontent.com/20780646/97320438-1607a100-186e-11eb-9753-49cafaef5c88.jpg)

### Expected result
- Joomla 4 field should use fancy-select feature.

**Comment by Harmageddon** [comment]
The problem seems to be that the `GroupedlistField` is not organized and split into layouts, but rather hardcoded in the field class. So the layout can't be easily overridden with the fancy-select alternative.
For cleaner code and consistency with most other fields, the best solution would be to change the `GroupedlistField` implementation to a layout-based one. This needs some digging into the code, as there is hardcoded HTML in several places inside the class.

But for the problem described here (how to make multi-select grouped lists fancier), maybe somebody knows another solution based on CSS classes or JS behaviour?

**Comment by Fedik** [comment]
To fix this issue need to move `GroupedlistField::getInput()` to layout as it done for `ListField::getInput()`
and create 2 layouts
 `joomla.form.field.groupedlist` - default
 `joomla.form.field.groupedlist-fancy-select` - optional

Anyone brave here? :)

**Comment by Fedik** [comment]
Please test #34091
