### ISSUE TITLE
Move or Copy in Batch funtionality missing in PHP 8

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#31467]
### Steps to reproduce the issue
Install Joomla 3.9.23 with PHP 8 (64 bit but it doesn't matter)
Add some Categories, Articles, and Menu Items.
Use Batch in any of these to copy or move them.

### Expected result
That one can copy or move items to other Menus, Article Categories, etc.

### Actual result
The Move or Copy option/drop-down is missing from the Batch box.

### System information (as much as possible)
Joomla 3.9.23
PHP 8.0.0RC5 (It's Harald's server)

### Additional comments
Here's what it looks like missing said option.
![articles-batch-rc2-2020-11-23_12-30-56](https://user-images.githubusercontent.com/5952595/100003022-115ddc00-2d8b-11eb-9781-b1037058dad2.png)
![batch-php8-3 9 23ga-2020-11-23_11-25-21](https://user-images.githubusercontent.com/5952595/100003025-128f0900-2d8b-11eb-85f3-04633b672136.png)

**Comment by HLeithner** [comment]
The reason for this is the new string to number comparison in PHP 8 [RFC](https://wiki.php.net/rfc/string_to_number_comparison).

Since we use a non type safe comparison in administrator/components/com_content/views/articles/tmpl/default_batch_body.php:27

```
<?php if ($published >= 0) : ?>
```

This evaluates to true in php < 8 and to flase in php >= 8

So we should check the source for all non type safe comparisions and change them... at least in Joomla 4 we changed a lot.

For j3 I would suggest to fix the batch templates and fix reported bugs except someone want's to take the challange to check the codebase for non type safe comparisions.

**Comment by HLeithner** [comment]
Btw. as workaround for php8 it's possible to set the publish filter to "unpublished", "published" or "archived"

**Comment by b2z** [comment]
@HLeithner so in this case `$published` is not numeric?

**Comment by HLeithner** [comment]
yes because it empty `''` a fix is easy just cast $published to `int` if you can create a PR I would be happy to merge it.

**Comment by alikon** [comment]
please test #31536
