### ISSUE TITLE
[4.0] Font Awesome icons are all broken

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#31470]
### Steps to reproduce the issue
Joomla 4.0 Beta 6 dev

### Expected result
Font awesome icons CSS are correct

### Actual result
All icons are gone and broken with wrong character and encoding

![image](https://user-images.githubusercontent.com/17835460/100024146-84e10700-2de6-11eb-926a-aee28b4f444d.png)

**Comment by chmst** [comment]
Could you please change the title of your issue so that it is more precise.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31470">issues.joomla.org/tracker/joomla-cms/31470</a>.</sub>

**Comment by N6REJ** [comment]
Instead of showing part of a file that you dont understand please show exactly where it's broken.  Show me a use case.
Ty<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31470">issues.joomla.org/tracker/joomla-cms/31470</a>.</sub>

**Comment by joeforjoomla** [comment]
@N6REJ Bear what do you mean that i don't understand? What damn are you saying?
Don't you see that all icons have lost the correct 'content' value?

Example Beta 5: .icon-checkmark:before,.icon-file-check:before,.icon-ok:before,.icon-publish:before{content:"\f00c"}
Beta 6: .icon-checkmark:before{content:""}.icon-checkmark-2:before,.icon-checkmark-circle:before{content:""}

There are all badly encoded characters: 

**Comment by brianteeman** [comment]
@joeforjoomla I tested the current branch and ran npm i - no problem. I downloaded last nights build - no problem. I compared the file from the build to the one I created with the script - no problem

**Comment by joeforjoomla** [comment]
@brianteeman i just downloaded the build 1 minute ago https://developer.joomla.org/nightlies/Joomla_4.0.0-beta6-dev-Development-Full_Package.zip
And the file is broken there

**Comment by brianteeman** [comment]
That's the same file I used with no problem

**Comment by joeforjoomla** [comment]
I even updated on a live server to beta 6 and the problem is still the same... file broken.

**Comment by brianteeman** [comment]
Brand new install on a clean server using the nightly zip

![image](https://user-images.githubusercontent.com/1296369/100083041-d9b16b80-2e40-11eb-8090-1f3d8f461622.png)

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/100083269-1e3d0700-2e41-11eb-89e4-f08c7c7a7f22.png)

**Comment by joeforjoomla** [comment]
@brianteeman how is it possible that for me the file has no content values? the zip should be the same for everyone isn't it? Additionally the live update should be the same.

**Comment by joeforjoomla** [comment]
@brianteeman i'm seeing that only certain icons are not displaying.... for example not working:
![image](https://user-images.githubusercontent.com/17835460/100084237-cc997a00-2e4a-11eb-82e9-1ad99ceef832.png)
working:
![image](https://user-images.githubusercontent.com/17835460/100084271-d91dd280-2e4a-11eb-89c9-9fefe378a122.png)

**Comment by joeforjoomla** [comment]
And this is the value that is used fo the 'content'
![image](https://user-images.githubusercontent.com/17835460/100084367-f8b4fb00-2e4a-11eb-973f-16b56c8d43d0.png)

**Comment by joeforjoomla** [comment]
Should not be regular 'content' as in the original FontAwesome file and as it has always been?
![image](https://user-images.githubusercontent.com/17835460/100084815-88f34000-2e4b-11eb-9c6f-898ba2d5e92f.png)

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/100085419-eaafac00-2e43-11eb-85ad-48ffd88e5096.png)

![image](https://user-images.githubusercontent.com/1296369/100085429-ef746000-2e43-11eb-8f4b-aaba39201478.png)

**Comment by brianteeman** [comment]
Maybe there is something here https://fontawesome.com/changelog/latest

**Comment by joeforjoomla** [comment]
Ok i think the problem was the font-weight override not the content value. My fault.
Can you please explain why in the Joomla file there is not the regular content value such as \f5oe but a squared question mark? 

Why not this?
![image](https://user-images.githubusercontent.com/17835460/100086154-49c5ee80-2e4d-11eb-9779-047ea966ba1d.png)

**Comment by joeforjoomla** [comment]
![image](https://user-images.githubusercontent.com/17835460/100086488-c953bd80-2e4d-11eb-886d-8a417e850307.png)

**Comment by C-Lodder** [comment]
The "encoding" issue you see is due to the PR I made to move Joomla from node-sass to dart-sass: https://github.com/joomla/joomla-cms/pull/31290

As far as I can tell, it doesn't have an effect on the rendered icons.

Compiling the data as opposed to the actual files may overcome this, but then you've got the `@import` hell that comes with it.
Else you can revert the PR and update to the latest version of node-sass, however it's deprecated

**Comment by brianteeman** [comment]
Thanks for the explanation

**Comment by joeforjoomla** [comment]
Thanks for the explanation and to inform us. Not sure where we should go here.

**Comment by N6REJ** [comment]
Next time instead of ranting @ me et al perhaps you could explain your viewpoint.  I would've explained that thats a failure of dart.  I hate it too<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31470">issues.joomla.org/tracker/joomla-cms/31470</a>.</sub>

**Comment by joeforjoomla** [comment]
@N6REJ Bear you right, sorry for this and i apologize for the misunderstanding.
