### ISSUE TITLE
Joomla bug fields apear and disapear incorrect way

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#31505]
### Steps to reproduce the issue

Write article in joomla 3.9.23 frontend,  with diferent fields assigned to diferent categories

enter data in field

then you select category which don't have that field assigned

and your field disapear

### Expected result

First select category then enter data in that category assigned field

### Actual result

First enter data in field, then select category, if selected category don't have that field, you get other field that assigned to selected category and you need to enter data in that new field

### System information (as much as possible)

joomla 3.9.23

### Additional comments

Maybe first tab should be publishing with selecting category that way you will not get to select the field which will disapear then you select category?

**Comment by infograf768** [comment]
If you just need changing the order of tabs, you can create a template override for edit form and move 
`<?php echo JLayoutHelper::render('joomla.edit.params', $this); ?>`
 after the publishing tab.

Instead of
<img width="737" alt="Screen Shot 2020-11-27 at 12 21 02" src="https://user-images.githubusercontent.com/869724/100445422-5ba5cc80-30ad-11eb-830d-5cc821da3813.png">

you would get
<img width="728" alt="Screen Shot 2020-11-27 at 12 36 10" src="https://user-images.githubusercontent.com/869724/100445450-66606180-30ad-11eb-999f-5c2a2006e988.png">

**Comment by ghost** [comment]
Why do we need to hide Joomla bug with a template override instead of fixing it ...

@infograf768 could you please be so kind and submit pull request ?

**Comment by ghost** [comment]
I wouldn't call this a "bug", more a matter of taste and @infograf768 gave a solution. But maybe my knowledge of user experience is not good enough.
