### ISSUE TITLE
Since update of joomla/archive composer still think it's 1.1.7 installed and update to 1.1.8

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#31673]
You had forgot something in this PR https://github.com/joomla/joomla-cms/pull/31513 now composer update joomla/archive from 1.1.7 to 1.1.8 when i tried to just update the joomla/image package, but the 1.1.8 is already installed....

I'am using composer 2.0.7

_Originally posted by @xillibit in https://github.com/joomla/joomla-cms/pull/31663#issuecomment-745605580_

**Comment by HLeithner** [comment]
Not sure what you mean with this composer.json tells us that joomla/archive is 1.1.8
https://github.com/joomla/joomla-cms/blob/staging/composer.lock#L190

**Comment by xillibit** [comment]
I mean in the installed.json it still says 1.1.7 for joomla/archive : https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/composer/installed.json#L190

yesterday i had done a `composer update  --no-dev -v joomla/image` , it has updated joomla/archive too in 1.1.8

**Comment by wilsonge** [comment]
The reason is the discrepancy between those files. When this was merged upgrading the version https://github.com/joomla/joomla-cms/pull/31514 we never merged in the composer files for whatever reason. so composer.lock mismatches with the installed file so it will always try and upgrade whatever other composer command you are running

**Comment by wilsonge** [comment]
Fix https://github.com/joomla/joomla-cms/pull/31676
