### ISSUE TITLE
Extension Installer Drag&Drop appears to accept multiple files dropped but doesn't work

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31720]
### Steps to reproduce the issue

In Joomla 3 admin navigate to the Installer for extensions

Upload Package File tab

Select multiple zip files on your computer and drag and drop to install them all

(On Mac) it appears too allow dragging of multiple files from finder and dropping them 

### Expected result

Error message saying to only drop one file

### Actual result

It only uploads the FIRST file, and continues to install that zip ONLY

![Screen Recording 2020-12-18 at 08 53 16 pm](https://user-images.githubusercontent.com/400092/102660640-420b1880-4173-11eb-9896-56558b6af337.gif)

### System information (as much as possible)

Safari Technology Preview on MacOS 11.2 Developer Beta
PHP8

**Comment by AMurray2016** [comment]
Is the upload/install failure caused by the 2M max upload limit (as shown in your screen-capture)?  

Some of those extensions in your example are < 2M (the Akeeba Contact Us is 1.12M (according to the version I have) and some exceed 2M (such as latest Akeeba Backup download 2.5M)....  Just putting this suggestion out there. Might be wrong, and it may have nothing to do with the problem.

I assume that the drag/drop screen is reporting accurately what your max file upload limit is as per PHP config setting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31720">issues.joomla.org/tracker/joomla-cms/31720</a>.</sub>

**Comment by brianteeman** [comment]
@AMurray2016 the problem is that it doesnt accept multiple files as drag and drop
