### ISSUE TITLE
[4.0] media manager plugin order

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#31861]
### Problem identified
hello on media manager we have a problem with order of value
options order need to be more used to less used
for no we have quality at first ... the less important for end user

![image](https://user-images.githubusercontent.com/2539440/103625641-8bad7e80-4f3b-11eb-8735-e5f4f91924b1.png)
![image](https://user-images.githubusercontent.com/2539440/103625747-b4357880-4f3b-11eb-808f-d709f34f3746.png)

And its realy strange we have 3 quality field in each tab => that not good we only need one

### Proposed solution
i can propose a propose a pr on action plugin field to change ordering
width height axes quality
![image](https://user-images.githubusercontent.com/2539440/103625549-6d478300-4f3b-11eb-8976-f3efd95ccb77.png)
![image](https://user-images.githubusercontent.com/2539440/103625925-de873600-4f3b-11eb-886c-271e09df352d.png)
![image](https://user-images.githubusercontent.com/2539440/103625999-e9da6180-4f3b-11eb-9eb4-6d22394f6cff.png)

For quality field i propose to add this only in rezize plugin

**Comment by micker** [comment]
no body for quality field, i know is trivial pr but i think this part need to be clean

**Comment by HLeithner** [comment]
can you please check if this pr solves the problem https://github.com/joomla/joomla-cms/pull/31810

**Comment by HLeithner** [comment]
sorry forget it the mentioned pr is unrelated to your issue

**Comment by micker** [comment]
yes the problem is the order of fields (need to be more usefull) AND 3 quality field (unecessary)

**Comment by HLeithner** [comment]
Each tab is it's own plugin and is  unrelated to the other plugins that's the reason why you have 3 fields for quality.

I'm pretty sure the plugins can be optimized. In this case I would create 3 separate issues one per plugin with the prosed solution. Or better start a discussion to get a better overview what other people think and there feedback.

I'm closing this here because it's too unspecific and is better discussed in the discussion area.

I would like to get your feedback on the #31810

**Comment by micker** [comment]
done here https://github.com/joomla/joomla-cms/discussions/31912
