### ISSUE TITLE
[4b6] Filesystem package being used is still 1.x

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31916]
### Steps to reproduce the issue

Open a Joomla 4 beta 6 site in PHPStorm

### Expected result

No warning 

### Actual result

<img width="428" alt="Screenshot 2021-01-08 at 21 06 29" src="https://user-images.githubusercontent.com/400092/104064246-7d8a8700-51f5-11eb-858e-d98f2226b373.png">

Now this could be a false warning, I'll reach out to the phpStorm project too to see if there is a way to identify what is causing this flag... 

I thought at first it was the Symfony php8 pollyfill but after removing that and trying again I still got the same warning.

**Comment by PhilETaylor** [comment]
ok Found it.

The first issue should be ok as an attribute can be interpreted by PHP 7.2 as a comment.

Attributes are only allowed since PHP 8.0 in libraries/vendor/symfony/service-contracts/Attribute/Required.php
```
#[Attribute(Attribute::TARGET_METHOD | Attribute::TARGET_PROPERTY)]
```

The second issue is "Classes named String are forbidden in PHP 7"
in file.
libraries/vendor/joomla/filesystem/src/Stream/String.php

So we just ignore this right?

**Comment by HLeithner** [comment]
For the comment I think we have to ignore it but the filesystem package is interesting.

Because it seems that composer pulls joomla/filesystem 1.3 and not 2.0, the cms doesn't have a direct dependency on the Filesystem package and all dependencies require ^1.3| ^2.0 I'm not sure if it's intended to use 1.3 package in j4.

/cc @wilsonge

**Comment by wilsonge** [comment]
I suspect it's because composer is preferring the stable tag of the filesystem package. I suspect when we tag a 2.0 stable for the filesystem package we will pull in that. I'll tag a release blocker here to check. But I don't think there's explicitly anything we can do until we go to tag framework packages

**Comment by wilsonge** [comment]
The symfony service contracts are tagged as 7.2.5 and higher. So I think we're pretty safe there. Just an IntelliJ bug

**Comment by HLeithner** [comment]
we can require ^2.0 in the cms because at the moment we test with the old version which should do the same but isn't the same code. When do we plan to tag stable for the framework?

Maybe this is true for other packages?

**Comment by wilsonge** [comment]
> When do we plan to tag stable for the framework?

Unsure. Shouldn't be too long after we put the CMS into RC. A few weeks minimum before we tag stable in the CMS...

I don't think we should add explicit requires in the CMS for things we don't depend on...

To be honest we probably need to look at decoupling the filesystem package from the archive package anyhow because I don't think the archive package will inherit our FTP settings anyhow :/

**Comment by richard67** [comment]
As far as I can see, the archive package has meanwhile been tagged with 2.0 Beta 4, which includes the change from PR https://github.com/joomla-framework/archive/pull/26 , so what remains to be done is to update the CMS with that Beta 4 (it still used Beta 2 as far as I can see). Or am I missing something?

**Comment by brianteeman** [comment]
This should be closed now
