### ISSUE TITLE
[4b6] Disable SEF Plugin breaks default template logo url

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31989]
### Steps to reproduce the issue

Joomla 4 beta 6 - install the "Testing Sample Data"
Visit frontend, click a menu link in the left menu to get to an article
Note that the CASSIOPEIA logo (white text on blue background) is present

In Joomla Admin disable the "System - SEF" plugin

Refresh your article page on the frontend

Note the logo is now a broken image

### Expected result

Regardless of SEF settings expectation is to see the logo

<img width="446" alt="Screenshot 2021-01-10 at 17 42 09" src="https://user-images.githubusercontent.com/400092/104130896-2e666280-536b-11eb-8492-65ac3a81defb.png">

Image logo url is http://127.0.0.1:4444/templates/cassiopeia/images/logo.svg

### Actual result

Note that `joomal4b6` shown in this screenshot is my "Site name" in Joomla Global Config and is not related to the SEF issue. 

<img width="622" alt="Screenshot 2021-01-10 at 17 43 07" src="https://user-images.githubusercontent.com/400092/104130918-505fe500-536b-11eb-8251-fd05e0d4a086.png">

Image logo URL is http://127.0.0.1:4444/index.php/templates/cassiopeia/images/logo.svg

**Comment by brianteeman** [comment]
Unable to replicate

![image](https://user-images.githubusercontent.com/1296369/104131203-e7796c80-536c-11eb-841a-b9f9440d7ff8.png)

![image](https://user-images.githubusercontent.com/1296369/104131210-eea07a80-536c-11eb-8dff-59a520e0c5f7.png)

![image](https://user-images.githubusercontent.com/1296369/104131215-f6601f00-536c-11eb-8162-746d18e9c8cd.png)

**Comment by PhilETaylor** [comment]
Maybe because your site is in a subfolder

**Comment by brianteeman** [comment]
Correction - it breaks as soon as I go away from the home page

**Comment by PhilETaylor** [comment]
As per the "Steps to reproduce the issue"  

> Visit frontend, click a menu link in the left menu to get to an article

**Comment by bembelimen** [comment]
The problem is, that the SEF-Plugin is (beside its little SEF changes) more a "fix all the broken things"-plugin. Like all the broken paths because Joomla! <= 3 has a wrong base tag which [is removed in Joomla! 4](https://github.com/joomla/joomla-cms/pull/25077).
So probably we should make this plugin a locked plugin to prevent disabling it (or re-add the base tag again, but in a correct way).

**Comment by Hackwar** [comment]
There is no correct way to add the base tag. It does not belong into our output.

**Comment by ReLater** [comment]
> So probably we should make this plugin a locked plugin to prevent disabling it

The ability to disable almost everything in Joomla 4 has been given so that developers can establish their own solutions wherever they want. A big step forward. If we now start to disable the disabling possibility for every extension where something could possibly work wrong, that would be a bad solution. One can not uninstall these extensions  anymore in Joomla 4. That should be sufficient.

See also https://github.com/joomla/joomla-cms/pull/28563#issue-398436871
below headline "This is a list of extensions that can be disabled"

**Comment by PhilETaylor** [comment]
This issue is NOT about the SEF Plugin. Its about broken image paths.

The image should load regardless of the state of the SEF plugin.

**Comment by ReLater** [comment]
> The image should load regardless of the state of the SEF plugin.

If you disable Joomla's link corrections for image paths? From my point of view that's the well known behavior.

**Comment by PhilETaylor** [comment]
whatever, fixed. https://github.com/joomla/joomla-cms/pull/32714
