### ISSUE TITLE
Joomla color field in admin template

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#32042]
### Steps to reproduce the issue

setup several color fields, if the color field is the last in the column, the selector moves to 2nd column, or 3rd if color field is in 2nd colum, making a color selection not possible

### Expected result

Select color from selector

### Actual result

Not being able to use selector

### System information (as much as possible)

change css to fix issue:

.minicolors-panel {position: fixed}

### Additional comments

see screenshots for the before and after results.

**Comment by Quy** [comment]
Duplicate #29956

**Comment by brianteeman** [comment]
@cloudfaction Thank you so much for testing and taking the time to report it

**Comment by ceciogit** [comment]
ive also noticed that months ago (supposed it was my fault because i was messing with admin template) ive solved replacing the field with a standard   html|type|color   field, but i think that the template do something with the values for calculating light/dark text overlay. so probabily not a good solution 

![ezgif-3-1bdba21e56b6](https://user-images.githubusercontent.com/51973854/105580918-98c9ca80-5d8f-11eb-8475-742cf5eee975.gif)

**Comment by Quy** [comment]
Closing as duplicate. Thanks.
