### ISSUE TITLE
[4.0] Deprecated SASS

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32111]
The sass compiler has been updated and is now issuing a lot of deprecation notices - that I am sure a frontender can quickly resolve

See https://sass-lang.com/documentation/breaking-changes/color-units

--compile-css will show you all the places that need to be updated

**Comment by ceciogit** [comment]
hello @brianteeman , can you kindly tell me more about that? you see deprecations on backend template or frontend or both?
what you mean by "--compile-css" is that a cli (node) command for people that have the src code instead of distro? 

P.S. sorry for all the questions instead of a solution .. but i really want to understand J4 Better , and also cuz ive always dreamed about compiling SASS directly with some cli code that reside on joomla node-modules instead of installing dart and others to accomplish that ..

**Comment by brianteeman** [comment]
Closed #32144
