### ISSUE TITLE
[4.0] [cassiopiea] Large gap inbetween containers

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32165]
### Steps to reproduce the issue

Visit the frontend of your site

### Actual result

![Screenshot_2021-01-26 Testing Home](https://user-images.githubusercontent.com/2019801/105821907-47018a00-5fb3-11eb-9e10-729aa532af95.png)

**Comment by wilsonge** [comment]
This seems to be intentional. https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/blocks/_layout.scss#L33 there's a 4rem top and bottom padding which means top-a and top-b there's 8rem padding.

@drmenzelit Comes from your commit here https://github.com/joomla/joomla-cms/commit/6ad05373ef4d3c31b5816089450667cd987d6db2 - not sure if you want to adjust or if it's expected to you

**Comment by drmenzelit** [comment]
We had a big discussion about white space between modules... we can replace padding with margin, then it will not sum up between containers

**Comment by C-Lodder** [comment]
There shouldn't be any padding or margins. It's using css-grid, so it should be dealt with by `grid-gap`

**Comment by drmenzelit** [comment]
I see... grid-gap for the body is set to 0 1em

**Comment by drmenzelit** [comment]
but changing it will have other consequences... for example it will add a gap between header and banner
![grafik](https://user-images.githubusercontent.com/9153168/105998373-dccd1000-60ac-11eb-8a97-e5ee0ed74f1e.png)

**Comment by brianteeman** [comment]
Any update on this?

**Comment by drmenzelit** [comment]
Closing with PR #33310
