### ISSUE TITLE
[4.0] Uncaught Reference Error - boostrap not definded

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#32185]
### Steps to reproduce the issue
Fresh installation 4.0 dev, after npm ci. Open Global Configuration, watch Console

<img width="852" alt="bootstrap-not-defined" src="https://user-images.githubusercontent.com/1035262/106259117-145bc980-621f-11eb-9873-e77298be67de.PNG">

On Xampp, win10.

**Comment by dgrammatiko** [comment]
That's probably because of a wrong order of the scripts. Try moving https://github.com/joomla/joomla-cms/blob/83d1e49f45c5d93688a7024b0dbd2795cfe9380e/layouts/joomla/form/field/media.php#L119-L120

before https://github.com/joomla/joomla-cms/blob/83d1e49f45c5d93688a7024b0dbd2795cfe9380e/layouts/joomla/form/field/media.php#L158

PS. Nope, that's not the problem. Change https://github.com/joomla/joomla-cms/blob/83d1e49f45c5d93688a7024b0dbd2795cfe9380e/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L192
to 
```js
})(customElements, Joomla, bootstrap);
```

and https://github.com/joomla/joomla-cms/blob/83d1e49f45c5d93688a7024b0dbd2795cfe9380e/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L1 to 

```js
((customElements, Joomla, bootstrap) => {
```

**Comment by chmst** [comment]
With these changes 

((customElements, Joomla, bootstrap) => {
...
})(customElements, Joomla, bootstrap);

the first two errors have gone, it remains the third one at line 247.






<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32185">issues.joomla.org/tracker/joomla-cms/32185</a>.</sub>

**Comment by dgrammatiko** [comment]
Try changing
```js
&& bootstrap.Modal.getInstance(this.modalElement) === undefined)
```

to

```js
&& bootstrap.Modal.getInstance
&& bootstrap.Modal.getInstance(this.modalElement) === undefined)
```

**Comment by chmst** [comment]
@dgrammatiko thank you for instructions, sorry but id does not work. Maybe I missed something but also with latest changes  (and npm ..) I see the  error Uncaught ReferenceError: bootstrap is not defined (line 247).

**Comment by dgrammatiko** [comment]
@chmst check #32193

**Comment by chmst** [comment]
Closing as there is a PR
