### ISSUE TITLE
[4.0b7] Contact Layout Address mis-aligned with icon

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32247]
### Steps to reproduce the issue

Create a contact in 4.0b7 admin and link it to a menu item
View that contact on the frontend

### Expected result

The address is aligned with the icon

### Actual result

<img width="245" alt="Screenshot 2021-02-02 at 20 41 11" src="https://user-images.githubusercontent.com/400092/106659709-013a5800-6597-11eb-9d5a-545f7014308a.png">

### System information (as much as possible)

safari on mac

**Comment by drmenzelit** [comment]
That is an expected behaviour, the address is a description list, with the icon being the `<dt>` element. If you choose to show text instead of icons, it looks like this:
![grafik](https://user-images.githubusercontent.com/9153168/107125876-a1042880-68ac-11eb-94bd-1219e61addb4.png)

**Comment by Harmageddon** [comment]
Hmm... While I agree that this is the default behaviour of dl elements, I'd say it is not expected like this at this point. Looking at the source code, I find a "dl-horizontal". Since Bootstrap 4, this has no effect anymore:

> `.dl-horizontal` has been dropped. Instead, use `.row` on `<dl>` and use grid column classes (or mixins) on its `<dt>` and `<dd>` children.

https://getbootstrap.com/docs/4.5/migration/#typography

So we should come up with our own implementation for `dl-horizontal` (or drop it from core, if we decide that it is not needed anywhere).

**Comment by RickR2H** [comment]
Added a PR #33780 to fix it for now. Please test.

**Comment by alikon** [comment]
please test #33780
