### ISSUE TITLE
[4.0b7] Disabled dropdown looks visually the same as enabled dropdown

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32262]
### Steps to reproduce the issue

Create a "Create a contact" menu type as super admin
Login to Joomla 4.0b7 frontend **AS AN EDITOR user role**
Click that menu item
go to publishing tab

NOTE the Featured dropdown is disabled.

### Expected result

The (disabled) Featured dropdown looks visually different to the Category and Tags dropdowns which are enabled. 

### Actual result

The (disabled) Featured dropdown looks visually exactly the same as the Category and Tags dropdowns which are enabled. 

### System information (as much as possible)

<img width="874" alt="Screenshot 2021-02-02 at 22 37 54" src="https://user-images.githubusercontent.com/400092/106672034-4f575780-65a7-11eb-8344-b76965077e79.png">

### Additional comments

Same issue with the Status field (which is disabled) when creating an article on the frontend:

<img width="857" alt="Screenshot 2021-02-02 at 22 38 13" src="https://user-images.githubusercontent.com/400092/106672079-65651800-65a7-11eb-877f-723e7ebb192f.png">

**Comment by chmst** [comment]
How did you proceed to make the featured field disabled? If I am registered and go to create a contact, the field is enabled.

**Comment by PhilETaylor** [comment]
No idea, Ive slept since then. Try logging in as an Editor on the frontend.

**Comment by ghost** [comment]
@PhilETaylor can you please update the issue happen only if logged in as member of editor-usergroup? i tried to test the issue and didn't get it until i read at the end of the discussion about `editor` ;-)

**Comment by brianteeman** [comment]
Steps to reproduce.
- Install the sample data
- Login to the front end as an Author
- Click on Create a Post from the right hand menu
- click on the publishing tab
- observe that the category can not be changed and the cursor changes
- observe that the other non disabled dropdowns look the same

All the css and js is working correctly. the background color for the select is being changed to a gray color. the problem is that the select-bg.svg background is the full width of the input and it has a white color on top of the gray background.

**Comment by PhilETaylor** [comment]
Checked today and its still the same.
