### ISSUE TITLE
Error installing J4 Dev 8 on XAMPP 

### ISSUE THREAD

**Issue by bobbla** [joomla/joomla-cms#32318]
### Steps to reproduce the issue
Install J¤ on XAMPP with PHP 7.4

### Expected result
Installment 

### Actual result

Fatal error: Maximum execution time of 120 seconds exceeded in E:\xampp\htdocs\j4test\202102\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php on line 433
Oops! An Error Occurred
The server returned a "500 Whoops, looks like something went wrong.".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### System information (as much as possible)
WIN 10 Pro XAMPP 3.2.4 PHP 7.4

**Comment by richard67** [comment]
@bobbla Did you install from a git clone? Or did you use the nightly build from https://developer.joomla.org/nightly-builds.html ?

**Comment by breebee** [comment]
It explains the error which is your exceeding the maximum execution time of 120 seconds. Just raise the variable limit until your computer can finish executing for the easiest solution. The best solution is using a linux distro with nginx :) and not using xampp or windows.

**Comment by chmst** [comment]
I am installing j4 frequently with max_execution-time 120, win 10, xampp. Both the git clone and the nightly build . I suppose that something happened to your database during execution of the installation. Could you inspect your mysql.error.log?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32318">issues.joomla.org/tracker/joomla-cms/32318</a>.</sub>

**Comment by bobbla** [comment]
I used the Nightly builds on developer.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32318">issues.joomla.org/tracker/joomla-cms/32318</a>.</sub>

**Comment by chmst** [comment]
So did I and works for me. Have you set a database password in your xampp? Could you inspect the log files in xampp?

**Comment by richard67** [comment]
@bobbla The database used for that installation was empty? Or has it been used in past for installations of previous J4 versions, so that there were still database tables in it? And if so, have you used the same database prefix as with the previous installation? If so, then the new installation tries to rename the old, present tables, and this might explain why it took more time in your case as it does when we are testing with empty databases. If you had used a different database prefix, then the old tables would not need to be renamed, but the database will get filled more and more if you do that often. This could also be a reason why it starts to become slow.

Could you check and report back if one of these scenarios was the case? Thanks in advance.

**Comment by chmst** [comment]
Closing as there is no answer.
