### ISSUE TITLE
[4.0] Finder js  Uncaught TypeError

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#32325]
### Steps to reproduce the issue
Display the smart search module in frontend.
Load frontend

```
Uncaught TypeError: Awesomplete is not a constructor

finder.js:70:34
```
@Hackwar

**Comment by Fedik** [comment]
hm, it because finder.js have an optional dependency from Awesomplete.js.

In theory, this:
https://github.com/joomla/joomla-cms/blob/f8565780fc2eefea09e86071eb4d0d346f52420a/components/com_finder/tmpl/search/default_form.php#L16-L24

need to be moved before this:
https://github.com/joomla/joomla-cms/blob/f8565780fc2eefea09e86071eb4d0d346f52420a/components/com_finder/tmpl/search/default.php#L12-L15


Unfortunately WebAsset cannot handle optional dependencies, currently.

**Comment by Fedik** [comment]
please test #32333

**Comment by infograf768** [comment]
Closing as https://github.com/joomla/joomla-cms/pull/32333 solves issue
