### ISSUE TITLE
[4.0b7] Capsule display with the use of Workflow

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32347]
Display of a message at the top left when using the Workflow. I am not sure this is normal.

![Articles_-_Joomla_4_beta_7_du_03022021_-_Administration](https://user-images.githubusercontent.com/26197929/107152428-0ec15a80-6968-11eb-97d1-8e5630b835a5.jpg)

**Comment by chmst** [comment]
Confirmed, thank you for reporting. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32347">issues.joomla.org/tracker/joomla-cms/32347</a>.</sub>

**Comment by richard67** [comment]
Is the skipto js doing that?

**Comment by chmst** [comment]
No, probably not. It appears since changing to BS5. Maybe @wilsonge and @dgrammatiko can have a look here.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32347">issues.joomla.org/tracker/joomla-cms/32347</a>.</sub>

**Comment by dgrammatiko** [comment]
>  It appears since changing to BS5.

It is BS5 related, more precise it's a bug from the upgrade to the newer Popper.js. I think this is already fixed in their repo so we need to wait for beta 2

**Comment by dgrammatiko** [comment]
@Magnytu2 @chmst should be fixed with #32378

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32378 . Thanks in advance.
