### ISSUE TITLE
[4.0b7] adding an icon changes the font

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32471]
Hello following the addition of an icon on a menu link or a module, the font changes.

![Capture d’écran 2021-02-19 à 09 17 15](https://user-images.githubusercontent.com/26197929/108592983-3ef9f780-7371-11eb-8ea9-5a79c8a17412.png)

**Comment by ReLater** [comment]
I presume that you used the field "Link Class" of the menu item where you entered a font class like "fa fa-home". Because it's the class of the anchor `<a>` I would say the behavior is correct somehow and I would use an override. 

Setting no image but fill the Image Class and use it in override as a SPAN class if no image provided.

Or maybe easier: CSS to force that only the `::before` part of the `<a>` uses `font-family: "Font Awesome 5 Free";`.

As long as there is no specific setting "Icon Class" or something similiar I think any other solution in core would be just strange when a user defines a "Link Class"

**Comment by Magnytu2** [comment]
You are a thousand times right. You must actually use Font Awesome 5. fa fa-homme> fas fa-home
How to put a small space to the right of the icon? One space is not enough.

**Comment by Magnytu2** [comment]
@ReLater After checking, it works fine on Safari, but not Firefox or Chrome.
![Capture d’écran 2021-02-21 à 16 45 39](https://user-images.githubusercontent.com/26197929/108630322-6b427080-7464-11eb-834e-2f39a5880ea7.png)

**Comment by ReLater** [comment]
The CSS is clear here. 

The HTML

`<a href="/" class="fa fa-home" aria-current="page" tabindex="0">Home</a>`

The CSS for `<a>` AND its `::before` part
```
.fa, .fas, [class^="icon-"], [class*=" icon-"] {
    font-family: "Font Awesome 5 Free";
    font-weight: 900;
}
```
From my point of view your "Accueil" is not the same font-family like "Blog" (compare the lower `l`s.) Any browser falls back in another font-family in cases like this if it doesn't know what to do ;-)

**Comment by drmenzelit** [comment]
@N6REJ as the icon expert can you maybe have a look here?

**Comment by brianteeman** [comment]
iirc you need to use just "fa-home" as the class and then make sure that there is a class which will still target the icon something like `.mod-menu li [class^="fa-"]::before`

its a css issue not anything really specific to fonts

**Comment by chmst** [comment]
Cosing as the pr  #34658 should solve this issue
