### ISSUE TITLE
[4.0] New fields layout utility classes don't work

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#32487]
The new field layout utility classes from PR #32422 don't work when inside the form-grid (which defines display:grid) a control-group div is present.

### Steps to reproduce the issue
Edit the templateDetails.xml file from Cassiopeia and add e.g. `class="form-select span-1-inline stack"` to the fields. Go to Template Styles and check the layout of the fields.

### Expected result
The fields should display horizontal like described in the PR.

### Actual result
The fields are still one below the other. The classes are there but the grid definition doesn't work here:
"grid-column has no effect on this element because it is not a grid element.
Try adding display:grid or display:inline-grid to the parent element. "

![grafik](https://user-images.githubusercontent.com/9153168/108639375-862cd900-7494-11eb-83d5-07661b64e3c6.png)

@ciar4n can you have a look here? Thanks

**Comment by ciar4n** [comment]
It looks likes I shouldn't have reverted removing the extra attribute (https://github.com/joomla/joomla-cms/pull/32422#issuecomment-779050471). Because the class attribute does not add the class to the containing div, it is not suitable for these utilities. 

I'll create a PR to fix. Originally I call the attribute `display=" ... "`.. I assume this name is ok?

**Comment by dgrammatiko** [comment]
>  Originally I call the attribute display

@ciar4n  will `parentclass` be more appropriate/specific?

**Comment by ciar4n** [comment]
PR created and updated to use `parentclass`.... #32488
