### ISSUE TITLE
[4.0] "categoryedit" and "tags" field show 2 dropdown lists

### ISSUE THREAD

**Issue by tranduyhung** [joomla/joomla-cms#32977]
### Steps to reproduce the issue

* Create a new menu item for `Create Article` menu item type (for creating a new article in front-end)
* Access this new menu item in front-end

### Expected result

* `Category` field should show 1 dropdown list for selecting category.
* `Tags` field should show 1 dropdown list for selecting tags.

### Actual result

* `Category` field shows a dropdown list with another one inside it.
* `Tags` field shows a dropdown list with another one inside it.

![joomla-bug](https://user-images.githubusercontent.com/503262/113465766-e124f900-9460-11eb-95b8-b0f14a039a11.png)

### System information (as much as possible)

* Joomla! 4.0.0-beta7 Beta [ Mañana ] 2-February-2021 19:23 GMT
* PHP 7.3.27-9+ubuntu20.04.1+deb.sury.org+1
* Web server Apache/2.4.41 (Ubuntu)
* MySQL server 8.0.23-0ubuntu0.20.04.1

**Comment by joomdonation** [comment]
Could you try night build package https://developer.joomla.org/nightly-builds.html ? It works well here for me on Joomla 4 nightly build (4.0.0-beta7 is outdated, there have been many changes to Joomla 4 since that version released)

![Create-a-Post](https://user-images.githubusercontent.com/977664/113465965-285fb980-9462-11eb-9653-7f0bf61ddd9e.png)

**Comment by drmenzelit** [comment]
I can't confirm this issue
