### ISSUE TITLE
[4.0] Backend: Remove Line below Multilingual Sample Data

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33067]
### What needs to be fixed
As title say:

> ![grafik](https://user-images.githubusercontent.com/78906980/113977880-882fd900-9843-11eb-9c1f-43140ec52d4f.png)

### Why this should be fixed
Same Look like other Modules:

> ![Screenshot_2021-04-08 Home Dashboard - sandramay09050408 - Administration(1)](https://user-images.githubusercontent.com/78906980/113977499-f6c06700-9842-11eb-81af-760c42bb0f82.png)

### How would you fix it
I don't know.

### Side Effects expected
I don't know.

**Comment by Bond97** [comment]
Maybe I'm wrong, but it's impossible to do this. Because modules "Recently Added Articles" and some others are consist of table.

But module Sample Data contains a list of items "Blog sample data" and "Multilingual sample data".

First group of modules contains these tags: `thead, tbody, td, tr` and others.
Sample Data contains tags: `div class` and `li class`.

CSS for tags `div class` and `li class` contains specific border width for it. Screenshot is attached below (CSS are displayed in right corner).
![image](https://user-images.githubusercontent.com/78050514/114097487-c4594d00-98c8-11eb-8daa-ae6c3224ab65.png)

If I change parameter "1px" to "0px" in that CSS - screenshot is attached below:
![image](https://user-images.githubusercontent.com/78050514/114097694-126e5080-98c9-11eb-8d28-d25af17b5030.png)

As you can see, borders are hidden completely.

I don't know, is it possible to modify CSS, when only one border are visible - between "Blog Sample Data" and "Multilingual Sample Data". Because if I change other parameters in that CSS - it will be visible all borders. Screenshot is attached below.
![image](https://user-images.githubusercontent.com/78050514/114098174-ab04d080-98c9-11eb-8391-44a895177455.png)

Maybe Joomla devs and maintainers are possible to answer to this question.

**Comment by drmenzelit** [comment]
That could help
`.list-group-item:nth-last-child(3) {
  border-bottom: none;
}`

**Comment by Quy** [comment]
Thanks for the report. Please test PR #33106.
