### ISSUE TITLE
Password reset discloses Email Address

### ISSUE THREAD

**Issue by CharlieH96** [joomla/joomla-cms#33138]
Hi

This issue is about the users component disclosing if an Email Address is registered to a user or not.

Thanks

### Steps to reproduce the issue
Use the com_users password reset process
Enter a registered Email
You now know this Email is registered as it redirects you, and can check for leaked passwords etc in hopes for gaining access.
Enter an invalid Email
You now know this Email is not valid due to notice message

### Expected result
Most modern applications use a system which gives a vague message such as, if the Email exists, then to check their inbox.

### Actual result
Email Address is disclosed if it exists.

### System information (as much as possible)
Joomla ‎3.9.24 

### Additional comments
There is no ideal way to modify this without making core changes from what I have seen

**Comment by richard67** [comment]
@CharlieH96 Would pull request #30787 solve your issue?

**Comment by CharlieH96** [comment]
Hi @richard67 

Yes it looks like it would.

Any news on this being merged?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33138">issues.joomla.org/tracker/joomla-cms/33138</a>.</sub>

**Comment by richard67** [comment]
The pull request (PR) #30787 needs 2 good tests before it will get status "RTC" (ready to commit), and then later be merged.

For testing, apply the changes in the PR and test as described there in testing instructions part of the PR's description.

After the test, please mark your test result by going to the PR in our issue tracker here https://issues.joomla.org/tracker/joomla-cms/30787 , use the "Test this" button at the top left corner, select the appropriate test result (hopefully success) and then submitt.

Would be great if you could test it.

Another thing we do is that we close an issue as soon as we have a PR which claims to solve it (and later if necessary re-open it if turns out if that was wrong), and so I close this issue here. But thanks for reporting, maybe it puts more focus on that PR, and hopefully you can test it.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #30787 . Thanks in advance.
