### ISSUE TITLE
[4] Layout issue of non-fancy radio boxes in admin console

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33144]
### Steps to reproduce the issue

A form with a field like 

```
	<field
					name="show_total_votes"
					type="radio"
					label="PLG_VOTE_TOTAL_VOTES_LABEL"
					default="0"
					filter="integer"
					>
					<option value="0">JHIDE</option>
					<option value="1">JSHOW</option>
				</field>
```

note there is no `layout="joomla.form.field.radio.switcher"` part.

### Expected result

Nicely laid out standard HTML radio buttons

### Actual result

Example screenshot:

<img width="521" alt="Screenshot 2021-04-15 at 20 01 04" src="https://user-images.githubusercontent.com/400092/114923954-56130e00-9e25-11eb-9d69-d0bff889bda1.png">

### System information (as much as possible)

Safari on mac

**Comment by YatharthVyas** [comment]
I can confirm this issue for Chrome (up to date) on Windows 10
![image](https://user-images.githubusercontent.com/53610833/115115529-9653c700-9fb2-11eb-8e5e-04a69957dcb4.png)


Also, the [Plugin documentation page for Joomla 4](https://docs.joomla.org/J4.x:Creating_a_Plugin_for_Joomla) doesn't mention about `layout="joomla.form.field.radio.switcher"` in their example. I remember this because I was riddled by this issue during my GSoC task and felt like I was doing something wrong.

**Comment by PhilETaylor** [comment]
#33176
