### ISSUE TITLE
[4.0] Plugin -> User - Joomla API Token -> Allowed User Groups doesn't reset to the default ID.

### ISSUE THREAD

**Issue by YatharthVyas** [joomla/joomla-cms#33194]
### Steps to reproduce the issue
1. Visit Joomla Admin Panel
2. Plugins -> User - Joomla API Token
3. If Super User is selected then clear it, select another group and save
4. Clear out the selection (Ctrl + Click on the selected item)
5. Save
6. Refresh / Check the database table

### Expected result
The field should attain the default value, ie. Super Users (ID: 8)

![image](https://user-images.githubusercontent.com/53610833/115195903-f0689f80-a10c-11eb-8961-50684eafbf0f.png)

### Actual result
Defaults to the previously selected item(s) (Administrator in the case of the gif below)

![image](https://user-images.githubusercontent.com/53610833/115195776-cb742c80-a10c-11eb-8e89-28f0b6d9e4f9.png)

![result](https://user-images.githubusercontent.com/53610833/115196528-a46a2a80-a10d-11eb-8f2a-a2515d0c59c1.gif)

### System information (as much as possible)
![image](https://user-images.githubusercontent.com/53610833/115196929-180c3780-a10e-11eb-8206-c244814c9bf9.png)

### Additional comments
Discovered while testing #33188 (Issue still persists after changing the layout)

The default value for this field in the XML seems to be fine.
https://github.com/joomla/joomla-cms/blob/c57cd15d1d0f7b860c5b9d678348a09fbc6a5792/plugins/user/token/token.xml#L31 

If I clear the value in the database table directly then the input field selects Super User (ID: 8) by default on save. But after selecting a different user group, this bug is again reproducible.

If multiple fields were selected before then all of them are retained. (No updation)

**Comment by richard67** [comment]
@YatharthVyas That's how form validation works in Joomla (at least in 4), as far as I know. If there is a field which has an invalid value, and I'd assume an empty group ID field is such a case, then the form is not saved, so all previous values are retained.

This makes sense since there might be interdependencies between fields regarding data, so it could lead to an inconsistent result if you just set one field back to the default and save the changes for the others.

Ok, this case here might be a bad example, but I think you get what I mean.

So for me the issue here is not that the changed form data is not saved and the previous form data is retained instead of using the default.

For me the issue is that there is no validation message ("Invalid field Allowed User Groups" error alert) shown, or it is shown only for a short time and then hidden by the "Plugin saved." success alert, that can also be. And at the end the "Plugin saved." success alert is shown, which should not be the case.

But I might be wrong or missing something, so lets see if other opinions drop in.

**Comment by richard67** [comment]
Thinking more about it, I don't see any issue. Clearing the field with selecting it while CTRL key pressed is nothing which a user would want to do, and if that happens, it's ok for me that the field changes back to the previous selection when saving.

**Comment by YatharthVyas** [comment]
It makes sense now. Thanks for the insight @richard67 . I'll close the issue for now and if need be, it can always be re-opened.

**Comment by Fedik** [comment]
> Defaults to the previously selected item

This is how `<select multiple>` works, if all items is unchecked then the browser do not send anything to server, and so on server stays old value.
The same behavior for checkboxes, if they unchecked then the browser do not send anything to server.

**Comment by Fedik** [comment]
@YatharthVyas if you like you can make a PR to make this field "required", this should help to avoid such cases
