### ISSUE TITLE
[4b8-dev] Unable to delete style (copy of Cassiopeia)

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33222]
### Steps to reproduce the issue
Go to Templates: Styles, create some copies of the Cassiopeia template. Then try deleting one of the copies. You will receive an error that the last template cannot be deleted. Strange behavior. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/115607442-abe82a00-a2ed-11eb-89c2-aea5609883c6.png)

**Comment by ghost** [comment]
Cannot confirm the issue. Made 2 copies and deleted 1 got:

> ![image](https://user-images.githubusercontent.com/78906980/115655903-77e42780-a334-11eb-85fe-fff69aaee6a3.png)

Test on nightly build.

**Comment by ChristineWk** [comment]
Confirm issue:

**![screen shot 2021-04-22 at 18 13 29](https://issues.joomla.org/uploads/1/d2b7fe2b4f592a29ddabf0d320d2c7bb.jpg)**
Joomla 4.0.0beta8-dev

@sandramay0905 what do you have that we don't have? :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33222">issues.joomla.org/tracker/joomla-cms/33222</a>.</sub>

**Comment by brianteeman** [comment]
Create a template style
Delete that style

no problem at all.

**Comment by brianteeman** [comment]
![issue](https://user-images.githubusercontent.com/1296369/115783576-ee286e80-a3b4-11eb-9df1-6fe8dc9de392.gif)

**Comment by chmst** [comment]
Works for me

![Animation](https://user-images.githubusercontent.com/1035262/115784022-e02b1b80-a3bd-11eb-8d61-5a5d84151a51.gif)

**Comment by ChristineWk** [comment]
Thanks for your instructions (gifs)

a) OK, with Duplication of the Style, the deletion works.

![screen shot 2021-04-22 at 21 45 18](https://issues.joomla.org/uploads/1/da19de5ac1d8f7f885a9f5312fa44c95.jpg)

b) ![screen shot 2021-04-22 at 21 46 04](https://issues.joomla.org/uploads/1/7ee0d1aa133e1876032f74c88e59aff9.jpg)

Unfortunately I make something wrong, because number (8) I can't delete. 
If starting again with Duplication, it will then become number (9) again etc.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33222">issues.joomla.org/tracker/joomla-cms/33222</a>.</sub>

**Comment by brianteeman** [comment]
Are you sure that they are all styles of the same template

![image](https://user-images.githubusercontent.com/1296369/115790023-f638dc00-a3bd-11eb-98cf-870b0879144d.png)

**Comment by ChristineWk** [comment]
@brianteeman 

Oh no (:- 
Just checked: Duplicate of Cassiopeia > Deletion: works OK. 

Therefore I think the reason is, that I have:

![screen shot 2021-04-22 at 22 11 39](https://issues.joomla.org/uploads/1/b22014517c8306097edd34adc2671e28.jpg)

Copied Template Cassiopeia & entered another name. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33222">issues.joomla.org/tracker/joomla-cms/33222</a>.</sub>

Thanks for clarification

**Comment by ghost** [comment]
@Kostelano can you retest having https://github.com/joomla/joomla-cms/issues/33222#issuecomment-825210335 in mind?

**Comment by Kostelano** [comment]
Thanks, figured it out. It's good that there is no problem :). I close it.
