### ISSUE TITLE
Joomla user management "Send password" doesn't work properly

### ISSUE THREAD

**Issue by durian808** [joomla/joomla-cms#33290]
### Steps to reproduce the issue
Go into Users > Manage, turn off "Send password".  Create a new user.

### Expected result
Notification email will not be sent to the user.

### Actual result
Notification with username and password is sent to the user.

### System information (as much as possible)
Joomla! 3.9.24.  EasySocial 3.2.24 (current version).  Joomla 3.9.25, 3.9.26 changlog bug fixes appear not to address this problem.

### Additional comments
A work-around is to turn off "Notification Mail to User" in the "User - Joomla!" plugin.

**Comment by joomdonation** [comment]
That setting is used to control whether password will be sent to users when they register for an account on frontend of your site. It has nothing to do with email sent when user account is created from administrator area of your site.

If you don't want email sent when user created from administrator area of your site, turn of **Notification Mail to User** in **User Joomla!** plugin is the right way, not work-around.

Closing this issue as this is expected behavior.

**Comment by durian808** [comment]
> That setting is used to control whether password will be sent to users when they register for an account on frontend of your site. It has nothing to do with email sent when user account is created from administrator area of your site.

But the "Send Password" tool tip doesn't indicate that the setting only applies when the user registers from the frontend, so it's a trap.  When the admin sets Send Password to NO on this page, the implication is that the user will not receive a password notification from the website – there's no mention of another setting, elsewhere in the admin panel, i.e the User Joomla! plugin. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33290">issues.joomla.org/tracker/joomla-cms/33290</a>.</sub>
