### ISSUE TITLE
[4.0] Blank slate modal issue

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33319]
@bakual my turn to say sorry I didnt check it before it was merged.

If you are in a modal when you click on the "add your first..." then the resultant page is the full page not the modal. See video

### Actual Result
![modal](https://user-images.githubusercontent.com/1296369/116005130-887af300-a5fd-11eb-92fa-03fd0bfe880e.gif)

### Expected Result
![image](https://user-images.githubusercontent.com/1296369/116005115-78631380-a5fd-11eb-94c8-bf9db712f73b.png)

**Comment by Bakual** [comment]
Good find. Simplest fix would be to not show the create button when in a modal. Because you should actually use the "Create" button in the menuitem form to create a new article.
We could also add a conditional in the view to only load the blankstate layout if not in a modal. We have such conditials already there to avoid loading the toolbar.
Loading the article form in the modal will probably get dirty as the current modal doesn't have any save buttons 😄 

I'm not sure what the expected behavior would be.

**Comment by PhilETaylor** [comment]
I'll leave you @Bakual to look at this one, my bed and then the day job tomorrow is now calling me and taking my time.

**Comment by Bakual** [comment]
Decided to not show the button when in a modal: https://github.com/joomla/joomla-cms/pull/33331
