### ISSUE TITLE
[4] Post Installation Messages Module Notification only shows for Joomla CMS and not other components

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33311]
### Steps to reproduce the issue

Install Joomla 4.0-dev

Go to the Post Installation Messages and click hide all messages. 

Note that the Bell in the toolbar top right has no red number on it. 

Run this SQL to add a fake post installation message for the Atum Template (change the db prefix!) - this replicates you installing a new extension that inserted a new post install message.

```
INSERT INTO `jos_postinstall_messages` (`postinstall_message_id`, `extension_id`, `title_key`, `description_key`, `action_key`, `language_extension`, `language_client_id`, `type`, `action_file`, `action`, `condition_file`, `condition_method`, `version_introduced`, `enabled`)
VALUES
	(99, 210, 'TEST', 'TEST', '', 'com_cpanel', 1, 'message', '', '', '', '', '4.0.0', 1);
```

Reload the admin home page. 

### Expected result

Expect the Bell to show a badge showing the number of messages to read

<img width="492" alt="Screenshot 2021-04-25 at 17 35 53" src="https://user-images.githubusercontent.com/400092/116001502-b146bc80-a5ec-11eb-9378-08aa5bc07cf8.png">

### Actual result

<img width="520" alt="Screenshot 2021-04-25 at 17 36 15" src="https://user-images.githubusercontent.com/400092/116001517-bf94d880-a5ec-11eb-90cd-a7ce19bcb39a.png">

### Additional comments

You can see the message is unread/waiting if you go back to the Post Installation Messages page and change to Atum Administrator Template

<img width="1324" alt="Screenshot 2021-04-25 at 17 37 13" src="https://user-images.githubusercontent.com/400092/116001554-e18e5b00-a5ec-11eb-9de2-1c7054107076.png">

**Comment by YatharthVyas** [comment]
Issue Confirmed. 

### My findings while debugging this:

This is happening because the Module that renders the Post Installation Messages Button uses `getIems()` function 
https://github.com/joomla/joomla-cms/blob/4d831f7e6487df3356cbf3b597d85ff4e80ae04b/administrator/modules/mod_post_installation_messages/mod_post_installation_messages.php#L19

from `com_postinstall/src/Model/MessagesModel.php` to determine the count
https://github.com/joomla/joomla-cms/blob/4d831f7e6487df3356cbf3b597d85ff4e80ae04b/administrator/components/com_postinstall/src/Model/MessagesModel.php#L130
This getItems() function returns only those items that match the extension id (:eid) returned by `$this->getJoomlaFilesExtensionId()` (binded in the query as :eid) which happens to be Joomla CMS (ID: 212)
https://github.com/joomla/joomla-cms/blob/4d831f7e6487df3356cbf3b597d85ff4e80ae04b/administrator/components/com_postinstall/src/Model/MessagesModel.php#L160

If you temporarily remove line 160 and 161 (refer to the above link) then the correct messages count is shown as we are no longer putting a constraint on the extension_id :

### Image 1
Correct Output (All Joomla CMS Messages have been hidden)
![image](https://user-images.githubusercontent.com/53610833/116004907-75c6e500-a622-11eb-98f9-bcbe8130a0e5.png)

### Image 2
Correct Output for Count but TEST message (from Atum Administrator Template) is also being shown
![image](https://user-images.githubusercontent.com/53610833/116005940-d3f5c700-a626-11eb-8148-ad9cce62226a.png)

However, deleting these 2 lines is not the correct way to go as `getItems()` is also used to render the messages for the 
Post Installation Messages Component page (Refer 2nd image where TEST is getting rendered for Joomla CMS selection). 

Hence, I believe that **a new function is required in Model.php** that **returns the count of all messages** not limited by a single extension_id and this function's return output should be used to display the messages count.

Hope this helps!

**Comment by PhilETaylor** [comment]
Although I have flagged this as a Joomla 4 issue - it probably is the same in Joomla 3 also - although "aint nobody got time for that" anymore.

**Comment by alikon** [comment]
please test #33344
