### ISSUE TITLE
Joomla 4 - startTabSet() in some circumstances can return void

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#33396]
### Steps to reproduce the issue

Component view html making use of Bootstrap tabs.

### Expected result

startTabSet() to return a string or a raise a sensible exception.

### Actual result

Get this message on screen:
Return value of Joomla\CMS\HTML\Helpers\Bootstrap::startTabSet() must be of the type string, none returned

### System information (as much as possible)

PHP 7.4

### Additional comments

Before closing braces should either return string or raise a sensible exception.

**Comment by PhilETaylor** [comment]
What is the full content of your call including the selector and params? Are you calling the method twice with the same selector and params?

**Comment by PhilETaylor** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/33397

**Comment by BrainforgeUK** [comment]
Not tried fix, but problem in component was due to _sometimes (!)_ startTabSet was being called twice with the same selector and params.

**Comment by PhilETaylor** [comment]
That was the problem I identified and debugged, my notes are in the PR. Thanks for confirming.

**Comment by PhilETaylor** [comment]
Thanks for reopening 

The agreement made in #33397 is that this is probably a "Wont fix" and that developers should know not to use the same id multiple times.

However the thing we will fix is to die gracefully with either an exception thrown, or just to ignore the fact that you asked for a duplicate element with the same id - instead of a PHP error message which is not good enough really for Joomla.

**Comment by PhilETaylor** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/33409

**Comment by alikon** [comment]
please test #33409
