### ISSUE TITLE
[Atum] joomla-alert.scss oddly located

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#33552]
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss

This file exists in the Atum template but only ever used in the installation template.

**Comment by dgrammatiko** [comment]
It’s also used in atum

**Comment by brianteeman** [comment]
where?

**Comment by dgrammatiko** [comment]
Here: https://github.com/joomla/joomla-cms/blob/4ca223102fd9cc40e4ff7436807294bf99fe7d3f/layouts/joomla/system/message.php#L45

This line calls the `media/vendor/joomla-custom-elements/css/joomla-alert.css` but since there is an override (it's how Joomla IS supposed to work correctly) in `administrator/templates/atum/css/vendor/joomla-custom-elements/joomla-alert.css` the system will load that file instead...
