### ISSUE TITLE
[Atum] joomla-tab.scss exists but never used

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#33551]
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss

I may be mistaken but it seems this file is never compiled or imported.

**Comment by brianteeman** [comment]
and it looks like there are other overrides in pages\_com_content and blocks\_toolbar

**Comment by dgrammatiko** [comment]
A simple source check on any page that has tabs indicates that the css is used. I guess people are confused as they expecting that the scss file `should` be imported in the template.scss. But this was the way we were building sites a decade ago, these days we try to componentize as much of our code as we could so that the code could be reusable and extendible...

I don't think there's something to do be done here, other than teaching people how to go away from the monolithic css file and embrace the modular paradigm. This will eventually lead to the deprecation of monolithic frameworks like Bootstrap...

![Screenshot 2021-05-06 at 10 32 01](https://user-images.githubusercontent.com/3889375/117267208-53b93800-ae56-11eb-8451-3b4c5618b36a.png)

**Comment by dgrammatiko** [comment]
![KnAPRl](https://user-images.githubusercontent.com/3889375/117268399-86affb80-ae57-11eb-955f-284312b189fd.gif)
