### ISSUE TITLE
[4] Modal cannot be closed with ESC after clicking in it 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33608]
### Steps to reproduce the issue

One quick one for @dgrammatiko ;-)

### Expected result

Open any modal in Joomla 4 admin - click ESC keyboard key - see it closes (Expected in 2021 that any modal closes on pressing of esc key)

### Actual result

Now, Open any modal in Joomla 4 admin - click with the mouse anywhere INSIDE the modal -  click ESC keyboard key - see it now doesn't close. 

### System information (as much as possible)

safari on mac. No console errors.

**Comment by brianteeman** [comment]
If I remember correctly the WCAG standard says that if it is a dialog then yes but if its a modal or alertdialog then no.

For the diff between a modal and a dialog this is as good as any https://www.nngroup.com/articles/modal-nonmodal-dialog/

**Comment by PhilETaylor** [comment]
LOL That article accurately describes all the reason Joomla should not be using modals for the majority of tasks that Joomla uses modals for...

**Comment by brianteeman** [comment]
I must have read something completely different then

**Comment by dgrammatiko** [comment]
Well, this is a problem with the dependency script, Bootstrap modal. A simple test using the batch modal and following the testing guide indicates that the script is fine with the modal that their body is not an iframe. Repeating this with let's say user selection or image selection the problem is obvious and the only difference with the previous step is that in this case, the modal content is an iframe. Probably worth opening an issue in their repo instead of trying to monkey patch things here...

**Comment by PhilETaylor** [comment]
Thanks for the explanation.
