### ISSUE TITLE
[4] TypeError: null is not an object (evaluating 's.classList')

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33652]
### Steps to reproduce the issue

Click "Add module to the dashboard" on the Home Dashboard page. Look at JS Console. 

Everything seems to work still despite message.

### Expected result

No JS console errors

### Actual result

TypeError: null is not an object (evaluating 's.classList')

<img width="607" alt="Screenshot 2021-05-08 at 18 55 27" src="https://user-images.githubusercontent.com/400092/117548827-f7f5d700-b02e-11eb-9f46-d4d407b30998.png">

### System information (as much as possible)

safari on mac

### Additional comments

@brianteeman found when checking the width of search box
@dgrammatiko ;-)

**Comment by dgrammatiko** [comment]
Check #33679

**Comment by joomdonation** [comment]
The reason is the same with issue https://github.com/joomla/joomla-cms/issues/33634 which @brianteeman reported. It causes by repaint PR 

By doing the fix as propose, we are losing the feature which we added from this PR https://github.com/joomla/joomla-cms/pull/32657.

Adding the missing HTML code back should solve both the issue and allow showing a message when there are no modules found from searching.

**Comment by joomdonation** [comment]
Closing because PR https://github.com/joomla/joomla-cms/pull/33679 solves this issue.
