### ISSUE TITLE
[4.0] System - Language Code

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33761]
This plugin is unlike any other. Before you can configure it you must enable it. And while it is disabled you can not even see the saved values. 

Why? I can't see a reason for this

**Comment by joomdonation** [comment]
For some reasons, the plugin parameters are loaded via plugin method https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/languagecode/languagecode.php#L127 , not define in XML like other plugin parameters. I guess we need to implement a new Form Field Type for parameters from this plugin so that the parameters not depend on status of the plugin like how it works at the moment.
