### ISSUE TITLE
[4.0b8] Error in Copy Template

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33783]
### Steps to reproduce the issue
Go to Site Templates. The only one is Cassiopeia. Open the template and click on copy template. .

### Expected result
The template is copied ( and this worked some days ago)

### Actual result

![grafik](https://user-images.githubusercontent.com/1035262/117841740-92e3f080-b27d-11eb-99e2-14246da2b3cc.png)89a9-2025269fdf61.png)

Additional information: 
Tried on the newest  4.0 dev on lcalhost (win10)
and with a fresh installation of the nigtly build 4beta7 on a fresh webspace

**Comment by ChristineWk** [comment]
Confirmed on: Nightly Update from today 4.0.0Beta8-dev

(?) Location: .../administrator/index.php?option=com_templates&view=template&id=211&file=aG9tZQ
Netzwerkanalyse: Status 303 Methode Post

**Comment by richard67** [comment]
Same problem here on local Linux as well as on shared hosting (also Linux). So it doesn't happen on Windows only.

**Comment by richard67** [comment]
Creating the copy in the `tmp` folder works, there is a folder like `template_copy_609acb8200f15`. But then it seems it fails with copying it to the final location. That could be an issue with the extensions installer, which is used to do a discovery installation.

@PhilETaylor Could that be a side effect of the empty states for discovery installation? That's the only recent change I see here, beside the removal of GUI parts pf FTP, of which I don't think they could cause the issue here.

**Comment by richard67** [comment]
> Creating the copy in the `tmp` folder works, there is a folder like `template_copy_609acb8200f15`. But then it seems it fails with copying it to the final location. That could be an issue with the extensions installer, which is used to do a discovery installation.
> 
> @PhilETaylor Could that be a side effect of the empty states for discovery installation? That's the only recent change I see here, beside the removal of GUI parts pf FTP, of which I don't think they could cause the issue here.

Hmm, this can't be the reason.

**Comment by PhilETaylor** [comment]
Fixed - PR coming

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33804 . Thanks in advance.
