### ISSUE TITLE
Code injection vulnerability

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#33935]
Hi guys, 
PHP 7.4.16 + Joomla 3.9.26 (also on a Joomla 4.0 beta 5 installation)

the Server Patchman scan has reported a:

Code injection vulnerability in PHPMailer
/home/.../libraries/vendor/phpmailer/phpmailer/src/PHPMailer.php

**Comment by HLeithner** [comment]
First, please don't report security issues on the public tracker. Send an email to security@joomla.org

If your report is about CVE-2020-36326 is likely invalid for Joomla 3.9.26 because only effects 6.1.8 - 6.4.0 - however, Joomla 3 uses PHPMailer 5.x which is unaffected by that issue.

But for further investigation please send the modified file to security@joomla.org

Joomla 4 is not covered by the JSST until it's released never the less we will update phpmailer before next tagged version.
