### ISSUE TITLE
[4] dashboard box colours?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34108]
### Steps to reproduce the issue

Has something just broke this... I swear I have now deleted and reinstalled, and recompiled the JS and CSS many times in the last 10 mins and both Safari on mac and Google Chrome on mac are showing this wrong now. iPhone 12 pointed at the same installation looks perfect though!! 

<img width="1601" alt="Screenshot 2021-05-22 at 17 27 05" src="https://user-images.githubusercontent.com/400092/119233943-2f7e7c00-bb23-11eb-87f3-b5e3e54c5ec3.png">

**Comment by PhilETaylor** [comment]
<img width="932" alt="Screenshot 2021-05-22 at 17 29 59" src="https://user-images.githubusercontent.com/400092/119233981-58067600-bb23-11eb-8577-f60911874a2c.png">

**Comment by PhilETaylor** [comment]
Confused.

**Comment by PhilETaylor** [comment]
Hmmmmm.... seems a complete reinstall from scratch fixed it... but maybe that means we have an upgrade issue... I'll close for now.

**Comment by PhilETaylor** [comment]
@richard67 when you are next testing your upgrade paths, please see if you accidentally replicate this.

I did npm builds loads and it never fixed it and it was not a cache issue, which leads me to believe it was a db issue as after reinstalling from /installation/ it was fine again.

**Comment by richard67** [comment]
@PhilETaylor I think it comes from the backend template repaint for which I had to add later update SQL for the Atum template style parameters: https://github.com/joomla/joomla-cms/pull/33375 . Have you run the SQL update scrips, too, after having pulled changes and run npm? The database fix will not run that because it's DML (data manipulation language) and not DDL (data definition language).

**Comment by PhilETaylor** [comment]
I cannot remember the last time I reinstalled the db from scratch, and I always forget to run update sql's...

I did not have this problem until yesterday. which is strange. 

I think the check for db schema updates should be on the home dashboard and "in your face"

**Comment by brianteeman** [comment]
> I think the check for db schema updates should be on the home dashboard and "in your face"

No as its really only relevant to those few of us who are testing and not going through an install

**Comment by richard67** [comment]
@PhilETaylor The check for db schema update will not help here because it checks only DDL statements which change structure, and the schema version. So in this case it will only show that the schema version is not matching, and when you use the fix button, it will fix the schema version in db.

But it will not sun completely those SQL scripts which according to the schema version haven't run yet, like it would do e.g. a tool like https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281 .

I think about implementing that since long time, something like `The database checker has detected a possibly incomplete update. If this is the case, use the "Complete update" button to fix that.`.

But it has certain risks, e.g. if a script has aborted somewhere in the middle so some update statements (DML) did not run and because we haven't reliable criteria in every case to check in db if we have to run them again or not.

We would need a database checker not only for the schema (structure) but also for data, and we would have to link every insert or update or delete statement to a condition which allows to verify if that statement needs to be run or not (not in all cases the `WHERE` clause of the particular statement is sufficient for that).

**Comment by PhilETaylor** [comment]
Thanks for the explanation. If you are all happy Im happy :-) 

I guess I was just shocked and worried so close to RC release to see what I saw, which persisted after NPM updates... but I now understand - thanks.

**Comment by richard67** [comment]
That was why I explained so much, because I wanted you to understand and not just to believe.
