### ISSUE TITLE
Update from 3 to 4

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34169]
I'm a little confused on the process for this. My assumption is as follows - please correct me if this is wrong

1. You must update to joomla 3.10 first
2. Then you use the pre-update check and upgrade to joomla 4

If that is correct then dont we need to have an rc of 3.10 otherwise no one can test an upgrade to joomla 4 with the upcoming release candidate for joomla 4

**Comment by richard67** [comment]
> I'm a little confused on the process for this. My assumption is as follows - please correct me if this is wrong
> 
>     1. You must update to joomla 3.10 first
> 
>     2. Then you use the pre-update check and upgrade to joomla 4

This is correct.

> If that is correct then dont we need to have an rc of 3.10 otherwise no one can test an upgrade to joomla 4 with the upcoming release candidate for joomla 4

There should be a release of 3.10 made together with the one of 4.0, as usual, but if the 3.10 is an alpha or beta or RC doesn't make any technical difference, it only makes a difference in the 3rd party developers might not be willing to test with a 3.10 which has alpha or beta status.

I think the next 3.10 should at least be beta.

**Comment by brianteeman** [comment]
@richard67 beta releases are targeted at developers. Release candidates are targeted at everyone. If there is no 3.10(alpha/beta/rc) available then no one can test the update. Thats one of the most important things to be testing with an RC

**Comment by richard67** [comment]
There is a 3.10 available and people can test the update. If you are on 3.9.26 or staging and select the "Testing" update channel and minimum stability "Alpha", you get the update to the last 3.10 alpha 5 offered.

**Comment by brianteeman** [comment]
I hope thats all documented in the 4.0 RC release

**Comment by richard67** [comment]
The steps from 3.9 to 3.10 to 4.0 is described in the recent release announcements for 3.10 alpha and 4.0 beta releases, see section "Can I update my website from 3.9.x to Joomla 4 Beta 7?" in the last one here: https://www.joomla.org/announcements/release-news/5833-joomla-4-0-0-beta7-and-joomla-3-10-alpha5.html

Of course I hope it will be documented that well in the next release announcement, too.

For the step from 3.10 to 4.0 there is also https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration , which uses the "Next" channel instead of a custom URL for the step from 3.10 to 4. No sure which one is right now, but I think I remember both works.

**Comment by brianteeman** [comment]
ok - thanks
