### ISSUE TITLE
The Home Dashboard is quite a mess on Safari in RC1

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#34359]
### Steps to reproduce the issue

Open the home Dashboard

### Expected result

A clean interface on the right

### Actual result

Blocks all over the place. Post Installation Messages notification and link to the frontend as a plain link, not styled. 

### System information (as much as possible)

Safari 14, Mac OS X 11.2.3, Joomla 4 RC 1
<img width="1350" alt="Schermafbeelding 2021-06-02 om 11 32 55" src="https://user-images.githubusercontent.com/3033162/120457662-ec2fd300-c396-11eb-9268-4659e2ba204b.png">

**Comment by ghost** [comment]
Looks like a update from a beta. Please clean your browser cache and open the admin template style and save or do a clean install.

Clean install of today (safari, mac):

![image](https://user-images.githubusercontent.com/78906980/120460127-1edacb00-c399-11eb-92a7-ca5b6e1e409d.png)

**Comment by richard67** [comment]
@stimpsonjcat Did you update from a previous Beta? Or from a previous nightly build? The latter is not supported and so can cause a mess. Please report back. Thanks in advance.

**Comment by ChristineWk** [comment]
> 
> 
> @stimpsonjcat Did you update from a previous Beta? Or from a previous nightly build? The latter is not supported and so can cause a mess. Please report back. Thanks in advance.

@richard67 Made yesterday the update from previous nightly build 4.0.0-beta8-dev to:


4.0.0-2021-05-30 | ‎4.0.0-rc2-dev
-- | --




successfully. Looks same as from @sandramay0905

**Comment by stimpsonjcat** [comment]
I've upgraded from the latest official beta this morning, just after the release of RC1. Cleaning the cache did help somewhat, but still not all modules are the same width. leaving a lot of space in between. I'll try installing from scratch.
<img width="1399" alt="Schermafbeelding 2021-06-02 om 14 14 48" src="https://user-images.githubusercontent.com/3033162/120478619-581d3600-c3ad-11eb-8782-992d2914079a.png">

**Comment by brianteeman** [comment]
the database is out of date.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/33045

**Comment by richard67** [comment]
Updating from nightlies is not supported and results in SQL statements from update SQL scripts not being executed, or being executed twice, depending on which script has been run as last with the previous update.

The reason for this is that we have decided to combine update SQL scripts to reduce their number before making RC 1.

It was this PR here: https://github.com/joomla/joomla-cms/pull/34139 .

What you can do is to go through the update SQL scripts 4.0.0-2021-04-22.sql, 4.0.0-2021-04-27.sql and 4.0.0-2021-05-21.sql and check which os the SQL statements haven't run yet. But that requires some database knowledge.

**Comment by brianteeman** [comment]
@richard67 the update scripts address structure not content and in this case it is content so they wont help in this case

**Comment by richard67** [comment]
@brianteeman No, you know pretty well that the update SQL scripts touch both structure and content and that I had to make one after your PR especially for that. See #33375 . I's the schema checker which ignores content updates, but we have and always had content updates like insert into menu table or whatever else in our update SQL scripts, and you know that.

**Comment by brianteeman** [comment]
sorry -multitasking during a meeting with the eu and my brain exploded

**Comment by richard67** [comment]
@stimpsonjcat It seems the database was not up to date since longer, so you could be lucky and the fix could be easy: Go to "System - Manage - Database" and check what the database checker reports, but don't use the "Fix" button because this will only fix the structure but not the data needed to solve your problem. There should be a problem about schema version not matching. Note which database schema version is reported (should be the lower one of these 2 with respect to the naming scheme of the update SQL scripts). Then check which update SQL scripts are available for your database type and run all which have a later schema version in their name.

E.g. if your database is MySQL or MariaDB, you can find the script here: https://github.com/joomla/joomla-cms/tree/4.0-dev/administrator/components/com_admin/sql/updates/mysql

If your database schema version is e.g. "4.0.0-2020-12-20.sql"m you have to run scripts "4.0.0-2021-04-22.sql", "4.0.0-2021-04-27.sql" and "4.0.0-2021-05-30.sql",

The "4.0.0-2021-04-27.sql" is the one which solves your problem.

**Comment by richard67** [comment]
@stimpsonjcat If you don't have much content created yet or are just testing, the easiest thing you can do is to make a new, clean installation of 4.0 RC 1 and then copy your content to there from the (messed) installation. Updating between releases will be safe, so you will be able to update to RC 2, RC 3 and so on (with the possibility to skip some RC x on the way) and then to final. But updating from nightlies or between nightlies is officially not supported.

**Comment by sluc69** [comment]
Updated from (existing website) J4-Beta7 to RC1. No problems encountered during upgrade. 
At first glance no difference on chrome-browsers and safari (Big Sur with iPad, iPhone emulator) on front & back-end.

Media manager is cleaned up and usable (still limited on docs, video media).

The option and other tabs items/dropdowns are stretched to available width, is this per design? A bit silly on a  23inch monitor.
In general I like it!
Will go deeper in the coming days....

Is there an upgrade path from J3 to J4?? I tried with J3-3.10 first then J4 but failed horrible, aka broken.

![j4-rc1](https://user-images.githubusercontent.com/82952282/120596048-d6dda600-c475-11eb-8a58-8b29275b230a.jpg)

**Comment by ChristineWk** [comment]
> Is there an upgrade path from J3 to J4?? I tried with J3-3.10 first then J4 but failed horrible, aka broken.

In order to upgrade from 3.9.x to Joomla 4, you have to go via the latest 3.10 release. There is no direct upgrade path between 3.9 and 4.x planned nor supported. All upgrades go via 3.10.

For the upgrade please follow these steps:
1. Go to the Joomla Update Component Options and switch the Update Channel to “Testing” and the Minimum Stability option to “Alpha”.
    2.  Update to the latest 3.10 alpha using the Joomla Update Component.
    3. Switch the Update Channel to “Custom URL” and set the Custom URL to “https://update.joomla.org/core/test/310to4_list.xml”
   4.  Now you get, update to the latest 4.0 Release Candidate.
   5.  Please carefully check the results from the pre-update checker in terms of your environment and your installed extensions before upgrading.
    6. After the upgrade please switch back to the “Testing” Update Channel with the “Release Candidate” minimum stability to get future updates between Joomla 4 RCs.

    

https://www.joomla.org/announcements/release-news/5837-joomla-4-rc-1-and-joomla-3-10-alpha-6.html

**Comment by drmenzelit** [comment]
Closing this now. Can be re-opened if the solutions posted above don't work.
