### ISSUE TITLE
[j4RC1]Admin broken Warning! Internet Explorer should not be used for proper operation of the Administrator Backend.

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#34451]
Hello i have a realy strange bug on rc1
i update whitout any problem .. working on it 
after relaod it all my admin is broken 
with this message `Warning! Internet Explorer should not be used for proper operation of the Administrator Backend.`
i am on chrom/firefox
i see this error, some idea ?
![2021-06-07_15h59_04](https://user-images.githubusercontent.com/2539440/121029902-4a025780-c7a9-11eb-8aa8-6475c2f3de35.png)
regards

**Comment by Fedik** [comment]
I suspect something with GZIP on server config or htaccess 
that cause  `content_decoding_failed` error,

**Comment by micker** [comment]
its realy strange i diasble gzip, i only have this problem in backend no problem in front end

**Comment by micker** [comment]
ahh htacess is the fault
`## These directives are only enabled if the Apache mod_headers module is enabled.
## This section will check if a .gz file exists and if so will stream it
##     directly or fallback to gzip any asset on the fly
<IfModule mod_headers.c>
	# Serve gzip compressed CSS files if they exist
	# and the client accepts gzip.
	RewriteCond "%{HTTP:Accept-encoding}" "gzip"
	RewriteCond "%{REQUEST_FILENAME}\.gz" -s
	RewriteRule "^(.*)\.css" "$1\.css\.gz" [QSA]

	# Serve gzip compressed JS files if they exist
	# and the client accepts gzip.
	RewriteCond "%{HTTP:Accept-encoding}" "gzip"
	RewriteCond "%{REQUEST_FILENAME}\.gz" -s
	RewriteRule "^(.*)\.js" "$1\.js\.gz" [QSA]

	# Serve correct content types, and prevent mod_deflate double gzip.
	RewriteRule "\.css\.gz$" "-" [T=text/css,E=no-gzip:1]
	RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-gzip:1]

	<FilesMatch "(\.js\.gz|\.css\.gz)$">
		# Serve correct encoding type.
		Header append Content-Encoding gzip

		# Force proxies to cache gzipped &
		# non-gzipped css/js files separately.
		#Header append Vary Accept-Encoding
	</FilesMatch>
</IfModule>`

**Comment by richard67** [comment]
@micker If your issue is solved then please close the issue here. Thanks in advance.

**Comment by Eriekhiel** [comment]
My Joomla site had the same issue which was due to incorrect addressing of the log paths.  The generated paths by Joomla's configuration.php file for some reason were not the proper ones for my hosting firm.  By contacting them and putting in the correct path resolved this issue.

The symptoms were the JS and the CSS were not loading on the admin side of the site.  It was not due to a htaccess/Gzip issue.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34451">issues.joomla.org/tracker/joomla-cms/34451</a>.</sub>
