### ISSUE TITLE
[4.0] Sort order of fields relative to their actual location in the table

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34501]
### Steps to reproduce the issue
Enable the use of a workflow in the content component settings. Go to the content component. Please note that in the element sorting field on the page, the STAGE field is at the very bottom, however, I remember exactly that we previously saved the order in this field relative to the actual location in the table (in this case, the stage line should be the second after ORDERING).

Somewhere in the admin panel I have already encountered a similar problem, it makes sense to check all the pages. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/121818688-58f97600-cc91-11eb-8c90-cbd7263b32f7.png)

**Comment by ghost** [comment]
Confirming the issue.

**Comment by brianteeman** [comment]
You are correct - the intention of the sort order is to match the order of the columns. 

In this case everything is in the correct order except for the Stage which is only available when workflows is enabled.

Instead of the stage filter being defined in the xml with an additional attribute such as required=workflows as we have with other conditional filters such as languages it is being _injected_ into the form

**Comment by brianteeman** [comment]
Took a long time but please test #44486
