### ISSUE TITLE
[4.0] When Language Filter with sef_suffix are active base URL's are like /en.html

### ISSUE THREAD

**Issue by elpescador-nl** [joomla/joomla-cms#34523]
### Steps to reproduce the issue
Make a multilingual website:
- Install new language
- Create a content language
- Enable the Language Filter plugin (associations = yes, makes it easier to see the result)
- Activate _sef_ + _sef_suffix_ (+ _sef_rewrite_) in the global configuration

### Expected result
Associations and links in mod_languages to the default (home) pages of different languages should be:
- https://www.example.com/en/
- https://www.example.com/es/
- https://www.example.com/nl/

The .html suffix only with deep links to non default pages:
- https://www.example.com/en/my-article.html

### Actual result
Associations and links in mod_languages to the default pages are like:
- https://www.example.com/en.html
- https://www.example.com/es.html
- https://www.example.com/nl.html

### System information (as much as possible)
- Joomla! 4.0.0-rc1 Release Candidate [ Mañana ] 1-June-2021 20:36 GMT
- PHP 7.4.10
- nginx/1.19.2
- fpm-fcgi

### Additional comment
I was wondering if the problem lies in the Language Filter plugin or in the _sef_suffix_ logic.

**Comment by brianteeman** [comment]
Confirmed for the home pages with the following config

![image](https://user-images.githubusercontent.com/1296369/122091111-5d906c80-ce00-11eb-8ad5-02fe27ebe2b3.png)

**Comment by elpescador-nl** [comment]
Additionally... without the _sef_suffix_ the URL's are like:
- https://www.example.com/en
- https://www.example.com/es
- https://www.example.com/en/my-article
 
...whereas these should have a trailing slash (in J!3.9 there is):
- https://www.example.com/en/
- https://www.example.com/es/
- https://www.example.com/en/my-article (no trailing slash as expected)

The _buildFormat()_ function in the _SiteRouter_ adds the format (_.html_) in case there is no trailing slash, so I don't think the issue is in that part. I can't find why there is no trailing slash in the default/home pages yet.

**Comment by joeforjoomla** [comment]
Confirmed. 
Actually the home links are totally broken compard to J3 on a multilanguage J4 website, plus the language switcher module throws a 404 page when changing the language.

So bad to find this issue at a RC stage, this makes it impossible to use J4 on a multilanguage website or update from a J3 multilanguage website, a lot of penalties about SEO would occur because of duplicated home page links.

Additionally there are other issues such as the logo linking to the website home page without /en,/es suffix, menwhile the menu link to en.html, es.html

This issue should be marked as release blocker.

**Comment by wilsonge** [comment]
> Actually the home links are totally broken compard to J3 on a multilanguage J4 website, plus the language switcher module throws a 404 page when changing the language.

This I can't reproduce at all.

I can fully reproduce the issue in the original report here - so it's a release blocker. But yeah there's no 404's. Just the SEF URLs not being as expected.

cc @Hackwar

**Comment by richard67** [comment]
Would be good to know when it was broken, with rc1 or before.

**Comment by joeforjoomla** [comment]
@richard67 this has always been broken, since the ALPHA stages of J4.

**Comment by brianteeman** [comment]
thank you for reporting it back then

**Comment by richard67** [comment]
I am not sure if the "en.html", "es.html" and so on was a deliberate decision or not ... I've tried to find old issues and PR where that was discussed, but I was not successful yet.

If you ask me: Personally I'd prefer it to work like in J3 regarding the home pages, which is (as far as I understand) what @elpescador-nl wants, too.

What we have now in J4 is at least not consistent (if not broken): The language switcher links to e.g. "es.html" and "nl.html" for the other languages if current language is English, but if you click on the logo, the language filter brings you e.g. to "en/" instead of "en.html", and there the mess begins.

**Comment by brianteeman** [comment]
its clearly a bug

**Comment by brianteeman** [comment]
I believe the problem is in the test here
https://github.com/joomla/joomla-cms/blob/9812f17e323a144fa9faf451b88607072ec16714/libraries/src/Router/SiteRouter.php#L542

Although in reality the real problem is that the url for the home page in another language is 
example.com/fr

when the test is expecting it to be
example.com/fr/

Note the trailing slash

**Comment by elpescador-nl** [comment]
> Although in reality the real problem is that the url for the home page in another language is
> example.com/fr
> 
> when the test is expecting it to be
> example.com/fr/
> 
> Note the trailing slash

As I observed in an earlier post I think the **real problem** indeed is the **absence of the trailing slash** in home/default page url's. The decision of whether or not to add the _.html_ suffix is just based on the absence/presence of the trailing slash.

**Comment by brianteeman** [comment]
Please test #34538

**Comment by richard67** [comment]
Alternative PR is #34558 . It will be ready for test soon.

~~Update: No, doesn't work (yet).~~

Update 2: Now it works. I only don't know if my PR is the right way to fix the issue.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34558 . Thanks in advance.
