### ISSUE TITLE
Enable Workflow in the Blog Sample Data Plugin

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#34741]
### Is your feature request related to a problem? Please describe.

It is not a problem but confirming to what is being said in the Blog Sample Data.

In the Blog Sample Data, there is an article about the new feature Workflow.  The sentence in that article reads as follows:

`We have activated a workflow for the sample data blog.`

However, when the Blog Sample Data is installed in the back-end Administrator, the Workflow menu item does not appear in the Content menu.  The user who installed the Sample Data would look for a menu item such as Workflow.  Without the menu item, the user has to go to the Articles Options and in the tab Integration enable the Workflow.  This could be a stretch for an inexperienced user.

So, it would be nice if the menu item "Workflows" appear on the left side menu (below the menu item Content).

### Describe the solution you'd like

In the table _xyz_extension_, in the row that contains the value **com_content** for the column _name_, in the column _params_ add the value **"workflow_enabled":"1"** at the end of the parameter list that is already available.

This setting would allow the user to see the menu item Workflows on the left side menu.

**Comment by Kostelano** [comment]
The item is available if integration is enabled. But not everyone will need this component. I would prefer to change the wording of the mini-article, in which I would add where exactly to include this component.

There are enough phrases in the demo articles that describe where and what to click, where to go, etc.

**Comment by chmst** [comment]
@imanickam thanks for the hint!

**Comment by Valc** [comment]
For me has been not easy to found it. At sample data for me some similar to this text at "PLG_SAMPLEDATA_BLOG_SAMPLEDATA_CONTENT_ARTICLE_9_INTROTEXT" key is more clear and direct.
`<p>Workflows manage the stages your articles must go through until they are published.</p><p>The component to manage workflows is not enabled by default because we believe that not everyone goes you will need this new functionality.</p><p>If you want to be able to see the workflow that we have activated for this sample data, you first need to activate the functionality</p><ul><li>Access the administration area</li><li>From 'Content' > 'Articles' > 'Options' > 'Integration' tab set 'Enable workflow' to 'Yes'</li><li>Save changes</li></ul><p>From here when you access 'Content' again you should be able to see the section 'Workflows'</p><p>Also, when you edit an article you should be able to see the new configuration parameters related to workflows.</p>`

**Comment by chmst** [comment]
At the moment we have Language Freeze and no update of languages is possile. But a PR for a new release would be highly appreciated.

**Comment by chmst** [comment]
Thank you all - please test #35536
