### ISSUE TITLE
[4.0] Language Pack requirements & Quality Control

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34938]
Sorry no idea where else to ask this question.

Are there any requirements for language packs before they are added to the list of available languages.
Is there any form of quality control (not translation quality) but code

For example I noticed that the de-DE and de-CH do not have any of the api language files and the ta-IN language includes an extra file `\api\language\ta-IN\langmetadata - Copy.xml`

cc @HLeithner @tecpromotion

**Comment by zero-24** [comment]
> For example I noticed that the de-DE 

Yes we are aware of that and are about to adjust our build tooling.

**Comment by HLeithner** [comment]
that's in the responsibility of the language coordinator per language, afaik we don't have a central control instance for language packs. Except for installation/core translation shipped with joomla it self it's merged into the cms via a pull request.

**Comment by brianteeman** [comment]
I am not really concerned about the missing de-* api files but the extra file in the tamil language is an obvious issue and not knowing the build tools possibly a security issue

**Comment by zero-24** [comment]
> not knowing the build tools possibly a security issue

Our build tools (the [current one](https://github.com/joomlagerman/team/tree/master/Hilfsprogramme) the [new one](https://github.com/joomlagerman/joomla/pull/1995)) and [the issue you mention](https://github.com/joomlagerman/joomla/issues/1382) is public on github, I cant speak for other languages. :)

**Comment by brianteeman** [comment]
@zero-24 I was referring to the tools that built the tamil pack with the extra file

**Comment by brianteeman** [comment]
Update server url missing from da-DK language pack manifest

**Comment by brianteeman** [comment]
also #35002 russian language errors breaking updates

**Comment by brianteeman** [comment]
and another one breaking updates #35512

**Comment by Kostelano** [comment]
At the very beginning of the Joomla installation, when choosing a language, there is no logic in the headers of the languages. Somewhere it starts with a native name, then in parentheses in English. Somewhere - the opposite. Somewhere - a language tag. Somewhere - no brackets at all.

Since the files are part of the Joomla core, this needs to be fixed. Perhaps every time you update files (like in https://github.com/joomla/joomla-cms/pull/35379). Or maybe it's better to create some kind of information page for TT coordinators.

@conconnl

![Screenshot_1](https://user-images.githubusercontent.com/8440661/132997707-fe16b8b2-a162-4923-98c3-54164bd93e91.png)

**Comment by conconnl** [comment]
@Kostelano 
I have no clue why you tagged me!

Yes, some people are creating documentation. 
They haven’t existed or were maintained for many years in the end the documentation will become better then it has been before.

**Comment by brianteeman** [comment]
every day it seems we have new issues with faulty language packs :(

**Comment by brianteeman** [comment]
Closed
