### ISSUE TITLE
[3.9> 3.10> 4.0] Switching to J4 loses menu links and cannot be corrected.

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#35013]
I just changed my site (my play) from J3 to J4. If I retrieve the content, images, categories correctly, I lose my tree structure and menu links. All my articles are under site / category / articles. In J4, I (not always) lose the categories and cannot reassign them by saving the articles again in the correct categories. If I change category, it works fine.

<img width="2051" alt="Capture d’écran 2021-08-01 à 15 53 34" src="https://user-images.githubusercontent.com/26197929/127774091-73387386-b90b-4495-b91a-749f9990173f.png">

**Comment by zero-24** [comment]
That sounds to me like a modern vs "old" router thing right @Hackwar ?

**Comment by Hackwar** [comment]
I'd say yes. But with the given information, I can't be sure. What are you expecting to be the right URL? What is your menu structure?

**Comment by Magnytu2** [comment]
Hello and thank you for your help.

Normally this article is in the Joomla 4 category, but the category does not want to display like in J3.9.

https://www.joomanji.fr/le-workflow-a-disparu

**Comment by zero-24** [comment]
The intention is to add a warning about non-modern router setups into the pre-upgrade checker so the site owner is aware of the change #35106

**Comment by brianteeman** [comment]
@zero-24 I can not see how from the information provided that notice will help in any way to fix the category of the articles

**Comment by zero-24** [comment]
Its a notice that the routing is going to be switched from legacy to modern with all implications that come with it including changing URLs where I'm not 100% sure that this is the case here but it sounds like that to me.

**Comment by brianteeman** [comment]
>  I (not always) lose the categories and cannot reassign them by saving the articles again in the correct categories

That can NOT be anything to do with routing

**Comment by zero-24** [comment]
Good to know one worry less 👍

**Comment by Magnytu2** [comment]
Hello, what bothers me is that for a lot of articles this has worked. My site (under joomla 3.9) was in modern url. But I have several articles, which despite being in a category, do not display the url of the category. And when we click on the category link from the opened article. Instead of displaying the articles of the category, display the home page ...

**Comment by brianteeman** [comment]
Would it be possible to have admin access to the site (or a backup) so that I can check more closely

**Comment by Magnytu2** [comment]
Yes of course, I will send you an email with the accesses.

**Comment by brianteeman** [comment]
Got it and will check it in an hour or so

**Comment by brianteeman** [comment]
Found your problem.

When you have two menu items that point to the same piece of content then the menu item with the lowest itemid takes precedence.

In your case your home page and your joomla 4 menu items are identical - they are both category blogs for the category joomla4

That is why the items in the category joomla4 are displayed as root level urls eg https://www.joomanji.fr/le-workflow-a-disparu when you expected it to be https://www.joomanji.fr/joomla-4/le-workflow-a-disparu

The subcategory items of joomla4 are displayed with the expected url because they have a sepecific menu item to display the category and a more specific menu itemid will take precedence.

The method I used to work all of this out was to disable sef urls. With SEF disabled you can see the itemid in the url. From that I could check the id in the list of menu items. That showed me that the links that dont work as you expected have an id of 140 but the id you were expecting was 124. Comparing the two menu items showed me that they were identical and hence the problem. 

In this case the itemid used was not the lowest but that was because it is the home menu

**Comment by Magnytu2** [comment]
Oh, well then! You're right, I changed the category for my homepage and it seems to be working. My homepage under Joomla 3.9 was built with Sp Page Builder and therefore shouldn't give me this kind of problem. Here under Joomla! 4 I wanted to stay close to the native functioning of Joomla!
Again a very big thank you to you for your patient and kindness.@brianteeman
<img width="1680" alt="Capture d’écran 2021-08-13 à 11 21 24" src="https://user-images.githubusercontent.com/26197929/129336222-11dd4089-1907-412c-8387-ba543722b494.png">

**Comment by brianteeman** [comment]
I have a similar structure on my own blog

**Comment by brianteeman** [comment]
For anyone who comes across this it was nothing to do with modern routing

**Comment by zero-24** [comment]
So this can be closed now?
