### ISSUE TITLE
[4.0] Separator in metis menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35062]
### Steps to reproduce the issue
Install blog sample data and create a menu item of type Menu Separator in both the blog menu and the special menu
![image](https://user-images.githubusercontent.com/1296369/128571284-0ab6661d-4c35-47e1-adf6-e0b22762a900.png)

## Expected result
Separator text is displayed

### Dropdown menu displays line
![image](https://user-images.githubusercontent.com/1296369/128571016-6da6c1c5-8822-46bb-8770-e058b1478181.png)

### Regular menu displays text
![image](https://user-images.githubusercontent.com/1296369/128571177-9733c0cf-c5f6-4920-9a8c-12ebf10377ea.png)

**Comment by richard67** [comment]
Hmm, from memory I'm almost sure we had it working in past, there was the menu item's title shown if it was not empty, or a line was shown if the title was a space only. But I might remember wrong or mix up J3 and J4.

**Comment by brianteeman** [comment]
the class in the dropdown is a  divider
```
metismenu.mod-menu .mm-collapse>li.divider:not(.parent) {
    width: auto;
    height: 1px;
    border-bottom: 1px solid #ced4da;
}
```

**Comment by chmst** [comment]
In J3, the separator is text as it is in your example and is unchanged for non-metismenus.

In Metismenu it was intended to have a separator line (texts can be added to a menu as headlines). 

We can change this so that the separator is a line if the param menu_text is "no" and is a text if the param menu_text is "yes".
But it is not self explaining.
