### ISSUE TITLE
[4.0]edit button are non-clickable in frontend

### ISSUE THREAD

**Issue by pinak3748** [joomla/joomla-cms#35115]
### Steps to reproduce the issue
On opening the frontend the hover menu has more gaps than it can be at the click of the edit button.

### Expected result
can't even change it in inspect has it can not be clicked I even tried to use TAB but it did not work either

### Actual result

https://user-images.githubusercontent.com/59458280/129450817-733ab003-8490-4548-ae93-9c420b87e697.mp4

### System information (as much as possible)
os - windows 10
browser - brave
php8

**Comment by mitishchanana** [comment]
you try your best .so don't take stress

**Comment by richard67** [comment]
@pinak3748 What means not clickable? Nothing happens when you click on it? In this case I can't reproduce that here. Or did you mean something else? In this case please explain more detailed. And which version of Joomla 4 did you use, and has it been a new installation or does that site have an update history? Thanks in advance for reply.

**Comment by brianteeman** [comment]
It is NOT a hover menu. It is just information. That is why you can't move the mouse from the link to the information to click on it - where there isnt anything to click on ;)

**Comment by pinak3748** [comment]
Ok i misunderstood it with dropdown o thought i could not click on it has it has more margin-left

**Comment by richard67** [comment]
@pinak3748 No problem. Thanks for reporting back.
