### ISSUE TITLE
[4.0] Update BS to v5.1.0

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#35182]
Current BS version used is v5.0.2, which includes a known bug with the dropdown component, resulting in the following error:

> Uncaught TypeError: this._menu is undefined

Please can we update to v5.1.0 to rectify this?

### System information (as much as possible)

- Joomla 4
- PHP 7.4

**Comment by HLeithner** [comment]
Of course we can update but it didn't make it into 4.0.0, if you can create a PR it would be very appreciated.

**Comment by dgrammatiko** [comment]
> Of course we can update but it didn't make it into 4.0.0

Well, not as easy as 1,2,3. BS 5.1 has some breaking changes (for the current templates) as it moves some SCSS vars to CSS Vars. Also as they not doing the whole transition in one pass it means for the next few patch versions they will keep breaking things (at least for the current templates) unless someone figures out a way to transition the current template CSS vars to something that won't break on each update... BTW I know because I already have done the transition (but will not open a PR as I have no clue if the code is future proof and won't break badly with their next patch)

**Comment by brianteeman** [comment]
I also took a look the other day. It would have to be for 4.1.0 because of the breaking changes and **not** 4.0.1

**Comment by dgrammatiko** [comment]
> I also took a look the other day. It would have to be for 4.1.0 because of the breaking changes and not 4.0.1

Maybe then I should finish the child templates and have 4.1 just on templates (like soon-ish not in 6 months)

**Comment by C-Lodder** [comment]
So what are extension devs who use BS supposed to do for the next 6 months?
I know BS can be a pain with BC breaks sometimes, but the sooner Joomla releases an update with the latest BS version, the better.

**Comment by dgrammatiko** [comment]
Please test #35518

**Comment by richard67** [comment]
Closing as having a pull request Please test #35518 . Thanks in advance.
