### ISSUE TITLE
[4] No "real" error page, always a "page not found"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35206]
### Steps to reproduce the issue

generate a 403 or php fatal issue in Joomla 4

### Expected result

403/Error page

### Actual result

"The requested page can't be found." (which is factually incorrect) 

<img width="994" alt="Screenshot 2021-08-17 at 22 49 51" src="https://user-images.githubusercontent.com/400092/129805363-6e470de4-a250-4567-870a-4bff8cd4fa59.png">

**Comment by ReLater** [comment]
I think that guests don't need more than a blanket information like that. Joomla doesn't handle it as 404, e.g. collects it in redirects. Admins can activate Debug for further investigations. In other words: I'm happy that there is just one simple error page instead of 15 variants in the background for this or that. Can create an override for my error page or just 1 language string and handle the output like I want instead of confusing people with blah blah concerning the reason why they don't see nothing.
