### ISSUE TITLE
[4.0] skipto link

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35211]
More a note for me to check with upstream but there is an issue when used on the frontend with the css used for the background of the message with the shortcut keys

![image](https://user-images.githubusercontent.com/1296369/129852946-168e4de0-6155-4a11-925b-29f70fa27576.png)

**Comment by PhilETaylor** [comment]
didn't this get fixed already before? you removed the min-width in the css?

**Comment by brianteeman** [comment]
yes thats what i thought but it was reported again last night and I havent had time to recheck it

**Comment by brianteeman** [comment]
and this is in the front end and I think it was the admin I was checking before

**Comment by woluweb** [comment]
Hi there,

Indeed I reported the issue during the JUG London meeting :)

The issue is coming from:
.skip-to .skip-to-tooltip {width: auto;}

located in the following line in the <head> section:
<style type="text/css" id="is-skip-to-js-4">

I quicly tested with
width: 300px;
and then the background covers the whole text.

Hardcoding the width is not the correct fix of course, but that was just a quick approach.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35211">issues.joomla.org/tracker/joomla-cms/35211</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a pr to test #35537
