### ISSUE TITLE
type="usergroup" is not working in Joomla 4

### ISSUE THREAD

**Issue by ashik685** [joomla/joomla-cms#35358]
### Steps to reproduce the issue

I check that type="usergroup" is not working in Joomla 4. There is not way to select usergroup

### Expected result

But it needs to be a dropdown to select them

### Actual result

Nothing works.

### System information (as much as possible)

Joomla 4

**Comment by alikon** [comment]
should be `type="usergrouplist"`

**Comment by richard67** [comment]
@ashik685 Like it was in Joomla 3 it still is in Joomla 4, see the comment above by @alikon : You have to use the right type "usergrouplist". See also https://docs.joomla.org/J3.x:Adding_custom_fields/Usergroup_Field .

**Comment by richard67** [comment]
Closing as expected behaviour since type="usergroup" is wrong, see https://docs.joomla.org/J3.x:Adding_custom_fields/Usergroup_Field . And see also here for an example: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_users/config.xml#L19 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35358">issues.joomla.org/tracker/joomla-cms/35358</a>.</sub>

**Comment by roland-d** [comment]
Actually the **usergroup** field type does exist in Joomla 3 as well. See the documentation at:
https://docs.joomla.org/Usergroup_form_field_type

Yes, the **usergrouplist** works in both Joomla 3 and Joomla 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35358">issues.joomla.org/tracker/joomla-cms/35358</a>.</sub>

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/0ef893b8caa1f1dd158cd5c86212f132943f8398/libraries/joomla/form/fields/usergroup.php#L39
