### ISSUE TITLE
Deleting a languagepack

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#35364]
### Steps to reproduce the issue
Why isn’t is possible to delete a language pack from System  - Manage - Languages? Is it by design? I can understand it is not possible from System – Install – Languages (it is an installation). Maybe because it is the same screen? I did have to search. The only way is now from System – Manage – Extensions. 

### Expected result
Delete a language pack on the place where you manage it.

### System information (as much as possible)
Joomla 4.0.2

**Comment by richard67** [comment]
It is by design because managing the extension means installing and uninstalling, while managing the language means setting the default language.

For this, different components are used (com_installer for installing and uninstalling extensions and com_languages for managing languages).

It would be silly from an architectural point of view to teach com_languages how to install and uninstall extensions.

**Comment by MartijnMaandag** [comment]
Thanks
