### ISSUE TITLE
[4] Versions Toolbar allows click when button disabled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35377]
### Steps to reproduce the issue

In admin, Edit an article, click versions DONT select a version

Hover over the disabled buttons in the modal, note:

1) The disabled mouse cursor only shows over TEXT not the images
2) Clicking is disabled on the TEXT of a button
3) Clicking is NOT disabled on the images or to the right of the text (but still on top of the button)

### Expected result

If a button is disabled - clicking ANYWHERE on that button should be disabled. 
If a button is disabled - hovering ANYWHERE on that button should show a disabled cursor

### Actual result

Easier to see:

![Screen Recording 2021-08-25 at 10 39 09 pm](https://user-images.githubusercontent.com/400092/130868434-a3bb5df3-e7a7-4622-87f3-4ff03b1525bc.gif)

### System information (as much as possible)

safari on mac

### Bonus Issue for Brownie Points and to note.

The ACTIONS menu on a list view DOESNT show a disabled cursor... but is correctly unclickable on the icon or text

![Screen Recording 2021-08-25 at 10 43 58 pm](https://user-images.githubusercontent.com/400092/130868751-aa1198b9-7493-4389-9efa-2d0ce4fb3379.gif)

**Comment by brianteeman** [comment]
the same bug is present on the preview and compare buttons but not the keep or delete buttons

i suspect it's related to the javascript

**Comment by richard67** [comment]
Yes, looked like spam. I've deleted it.

**Comment by richard67** [comment]
> Been a lot of this spam the last three days

Yeah, there is a guy who looks like you and has same username and opens a lot of issues within a short time 😛 

(teasing joke)

**Comment by rjharishabh** [comment]
Please test #35761

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35761 . Thanks in advance.

**Comment by richard67** [comment]
@PhilETaylor I just see the PR only solves the first of the 2 things you have mentioned in expected result:
- If a button is disabled - clicking ANYWHERE on that button should be disabled.
- If a button is disabled - hovering ANYWHERE on that button should show a disabled cursor

The disabled cursor, is that something some browsers do for disabled buttons, and others do not? Or is that something to be done with CSS? Am asking because when testing the PR I did not see any cursor change.
