### ISSUE TITLE
[4.0][3.10] Pre-Update Checker shows misleading Update Required

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#35384]
### Steps to reproduce the issue
Install an "outdated" extension that's compatible with the current Joomla! version.

### Expected result
No required updates showing or at least 'Optional Updates' showing.

### Actual result
Update Required
![image](https://user-images.githubusercontent.com/1422378/130936867-b5d0852c-0d74-44e0-839a-31be08deb450.png)

### System information (as much as possible)
Latest 3.10.1 and 4.0.2

### Additional comments
The Pre-Update Checker shows the update as required, even though the version currently installed works fine and is compatible. Very confusing to end-users IMO.
Rant: Honestly the Pre-Update Checker is doing more harm than good at this point. Issue #34599 is closed but points remain valid.

**Comment by Kostelano** [comment]
What is meant by "version is working fine"? How can you know if there are any major changes in the newer version, for example, to improve security?

This page clearly states that there are updates for the installed versions. Isn't it the same information, in a slightly different form, you see on the main page of the control panel?

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/130976594-f11c27f3-baf7-46a7-89cc-0d4e87e3c93e.png)

**Comment by OctavianC** [comment]
> 
> 
> What is meant by "version is working fine"? How can you know if there are any major changes in the newer version, for example, to improve security?

A compatible Joomla! 3.10.x or Joomla! 4.0.x version of the extension, which is a few versions behind the latest version of the extension, but yet still fully compatible.
> 
> This page clearly states that there are updates for the installed versions. Isn't it the same information, in a slightly different form, you see on the main page of the control panel?

The page clearly states that there are REQUIRED updates. How does it assess that? It doesn't, the wording is simply misleading. We've not had this issue before 3.10 as people would always update their Joomla! installation, especially since the _one click_ update mechanism. Now, they are scared because of these messages. They postpone updates, which is detrimental to the CMS's health.

Thank you @brianteeman, I'm aware of that changelog, I've wrote it myself :)

**Comment by Kostelano** [comment]
It took me a while to realize that these are your extensions :).

It seems to me that you should be one of the first to worry if people allow themselves not to update your extensions and then write a ton of support emails asking "I'm broken, what's wrong?" That is why I am still in favor of the fact that the wording is "requires updating", since it is logical to use the latest versions of the product with corrections for the latest version of Joomla.

**Comment by brianteeman** [comment]
> Thank you @brianteeman, I'm aware of that changelog, I've wrote it myself :)

I realised that. 

And I also know that whenever I have to submit a support ticket I am always asked what version am I using and if its not the latest version I am told to update and see if its already fixed.

> Rant: Honestly the Pre-Update Checker is doing more harm than good at this point

How can telling your paying customers that they should be upto date causing harm

**Comment by richard67** [comment]
I can reproduce that the pre-update checker offers an update even if it's not necessary because the currently installed version of an extension is flagged as compatible with the current CMS version as well as with the CMS version to be updated to. This can be even more critical if the version to which the extension shall be updated is not compatible to the current CMS version, e.g. if checking for update from 3.10.x to 4.0.x and the offered update works only with J4.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/35419 might solve the issue. @OctavianC Could you please test ? 

I'm closing this issue for now. Will re-open if the PR is not accepted.

**Comment by richard67** [comment]
@OctavianC Please test #35510 . Thanks in advance.
