### ISSUE TITLE
You are not allowed to login. Please contact administrator.

### ISSUE THREAD

**Issue by xhorizont** [joomla/joomla-cms#35595]
Every time somebody signs in administration it displays "You are not allowed to login. Please contact administrator."

Everything works but it's just annoying

John

**Comment by brianteeman** [comment]
Is that the exact text of the message.

**Comment by xhorizont** [comment]
Yes

**Comment by brianteeman** [comment]
That string does not appear anywhere in the core of Joomla

**Comment by PhilETaylor** [comment]
Please send a screenshot of the whole screen when this message is shown so that we might make guesses as who to tell you to talk to first

**Comment by ChristineWk** [comment]
Someone had the same response (found in the forum). It was because of this extension:
https://extensions.joomla.org/extension/miniorange-oauth-client/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35595">issues.joomla.org/tracker/joomla-cms/35595</a>.</sub>

**Comment by alikon** [comment]
closing as not a core issue
