### ISSUE TITLE
[4.x] CLI command cli/joomla.php - Notice: Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by Kubik-Rubik** [joomla/joomla-cms#35625]
### Steps to reproduce the issue

With the command `php cli/joomla.php list`, you get a list of all available CLI commands.

The script throws a PHP notice if the system plugin "System - Page Cache" is enabled:

**Notice: Undefined index: HTTP_HOST in /xxx/libraries/src/Uri/Uri.php on line 103**

### Expected result

No errors, regardless of what plugins are activated.

### Actual result

See the error above.

### System information (as much as possible)

Joomla! 4.0.3, PHP 7.x & 8.x

**Comment by brianteeman** [comment]
Confirmed

**Comment by alikon** [comment]
please test #35722

**Comment by anibalsanchez** [comment]
From my comment in #35722:

_About #35625, the problem is that the `php cli/joomla.php list` is firing the "System - Page Cache" when it's called from the console. Why would a console application fire the "System - Page Cache" plugin? It shouldn't. By default, a console application doesn't have to interact with the site cache._

The joomla console application calls to `PluginHelper::importPlugin('system');` to initialize all system plugins. So, the problem seems to be that the "System - Page Cache" plugin tries to read the URI when it is executed in the console context. In my opinion, the plugin should do nothing and ignore the execution if it is the console context.

PS: Now commenting in the right issue ;-)
