### ISSUE TITLE
[4.0] Fix button missing from database checker

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#35630]
### Steps to reproduce the issue
go to system->database

### Expected result
button shows to fix & check db.

### Actual result
menu missing.
![image](https://user-images.githubusercontent.com/1850089/134227480-ce75bde4-1e52-4c25-9f2d-ce8d0efee679.png)

### System information (as much as possible)
4.0-dev current

**Comment by brianteeman** [comment]
Looks like you have disabled the toolbar in the admin template

![image](https://user-images.githubusercontent.com/1296369/134229346-97a52d2b-55cb-445b-a8cb-fbc8bd1a1b9e.png)

**Comment by N6REJ** [comment]
nope, its there in full screen but not in partial

**Comment by brianteeman** [comment]
Found it. There is a bug in the css and at certain resolutions the toolbar disappears completely

**Comment by klucon** [comment]
This problem is also with the new article.
When I put the browser on 1/2 monitor, I click on Content -> Articles -> New, the menu disappears. If I want to save or cancel the article, I have to put the browser in full screen.

<button class="navbar-toggler toggler-toolbar toggler-burger collapsed collapse show" type="button" **data-bs-toggle="collapse"** data-bs-target="#subhead-container" aria-controls="subhead-container" aria-expanded="false" aria-label="Tools" style="">
				<span class="toggler-toolbar-icon"></span>
			</button>

If I remove the bold text, the menu also works on 1/2 monitor, but I don't know which file it is in.

Edit: Joomla 4.0.3

**Comment by brianteeman** [comment]
it is on all pages - the solution is not what you highlight - its in the css media queries

**Comment by N6REJ** [comment]
just fyi here's a mobile shot 
![image](https://user-images.githubusercontent.com/1850089/134413953-956ddce0-8390-4ab8-92ba-0be5b27e6cda.png)

**Comment by RickR2H** [comment]
Closing as having a pull request. Please test #35860<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35630">issues.joomla.org/tracker/joomla-cms/35630</a>.</sub>
