### ISSUE TITLE
Twofactor authentication plugins have wrong group in xml

### ISSUE THREAD

**Issue by basd82** [joomla/joomla-cms#35637]
if you look in the xml of totp (google authenticator) en yubikey in the xml file bothe have syttem as group.

the group should be twofactorauth

i have add two patches as sugestion

**Comment by basd82** [comment]
i forgot to attache patches

[totp.patch.txt](https://issues.joomla.org/uploads/1/b137ae877918f45e2fec7363e380f8de.txt)hes[yubikey.patch.txt](https://issues.joomla.org/uploads/1/d6c393fc95508000651e629537eeb45e.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35637">issues.joomla.org/tracker/joomla-cms/35637</a>.</sub>

**Comment by zero-24** [comment]
Oh yes good catch. Can you send your patches as github pull request against the 3.10-dev branch?

**Comment by wojsmol** [comment]
@zero-24 @basd82  PR created https://github.com/joomla/joomla-cms/pull/35638

**Comment by zero-24** [comment]
Closing as the PR has been merged thanks :)

**Comment by basd82** [comment]
How do do that?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by zero-24** [comment]
For simple changes like this you can use this: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

For larger PRs i would recommend a full local git/github setup: 
https://docs.joomla.org/Working_with_git_and_github

For this case here @wojsmol already did it with #35638 so this issue will be fixed by the next update.
