### ISSUE TITLE
[4.0] Invalid markup on error page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#35786]
### Steps to reproduce the issue

1. Open `layouts/joomla/content/full_image.php`
2. Create a PHP error by removing `use Joomla\CMS\HTML\HTMLHelper;` from the top.
3. In the **frontend** of your site, go to any single article that contains a **Full Article Image**

### Actual result

Whilst the page does show an error, the HTML markup is completely off and invalid.

If you inspect the source code, you'll notice the `<head>` tags are empty, and all the markup inside the `<body>` is wrapped inside `<div class="com-content-article item-page" itemscope="" itemtype="https://schema.org/Article">`

![image](https://user-images.githubusercontent.com/2019801/136512727-a5fbbf42-2320-4674-a4e2-1768756e8e2c.png)

![image](https://user-images.githubusercontent.com/2019801/136512632-f33acde0-12c9-4c9b-9aa6-4899e6904269.png)

**Comment by brianteeman** [comment]
confirmed

**Comment by brianteeman** [comment]
It's weird. It only happens when the error is in a layout

**Comment by C-Lodder** [comment]
Yeah, definitely a bizarre one

**Comment by khu5h1** [comment]
Hey, I am working on this issue for the last 3-4 days and I made a few observations which are as follows:

1. The origin of the problem is from `components\com_content\tmpl\article\default.php` .
2. The reason for this problem is that the `default.php` file is using `LayoutHelper` to render components like `full_image` or `info_block`.
3. So what this `LayoutHelper` does is that It renders the whole error page when there is an error in the component. 
4. As the `info_block` is executed before the `full_image` component the `info_block` comes before the error. 
5. I am trying to figure out the solution to the problem.

@brianteeman if you have any suggestions for a solution, it would be a great help. 

Regards

**Comment by brianteeman** [comment]
I dont think its related to the layouthelper as I have just come across the exact same thing with a plugin on the main template

**Comment by Quy** [comment]
I can not reproduce this in v5.1. Please confirm. Thanks.

**Comment by Quy** [comment]
I cannot reproduce in v4.4.4.

Removed `use Joomla\CMS\Layout\LayoutHelper;` in `layouts/joomla/content/full_image.php`.

![35786](https://github.com/joomla/joomla-cms/assets/368084/14da29fa-a228-4484-9d56-90425f9a6129)

**Comment by Hackwar** [comment]
I also tested this on a few sites and can't replicate this anymore. I had this issue in the past as well, but since then it seems to have been fixed.

**Comment by brianteeman** [comment]
I could replicate this before but not now

**Comment by Quy** [comment]
Closing as this is no longer reproducible by several people. Thanks.
