### ISSUE TITLE
Trying to get property 'id' of non-object in ....  /libraries/src/Updater/Adapter/ExtensionAdapter.php on line 333\n

### ISSUE THREAD

**Issue by vddesign** [joomla/joomla-cms#35815]
### I get this in the errorlog of the server when i am logged in in administrator on 4.0.3. Server gets to high CPU use and get in limited position

Error in log:
Trying to get property 'id' of non-object in .... /libraries/src/Updater/Adapter/ExtensionAdapter.php on line 333\n

### System information (as much as possible)
Joomla 4.0.3 PHP 7.4.23
Dadatbaseversion: 10.4.21-MariaDB-log-cll-lve

**Comment by richard67** [comment]
Duplicate report to #29778 , #35376 , #34959 ... ?

**Comment by vddesign** [comment]
Hi Richard, I probably think so, I am not a developer but designer ;) Have no experience with this. Does it mean that the developers are going to look into it? The sever of my website gives me problems with using to much CPU.

**Comment by richard67** [comment]
@vddesign When does your problem happen? When the check for extensions updates is running after you logged in? I.e. does the icon for extensions update status show "Checking extensions ..." like it is described in #29778 ? If so, which 3rd party extensions do you have installed? If there are some, maybe it helps to go to the "System" panel and then click the "Update Sites" link in the "Update" section and then for update sites belonging to 3rd party extensions disable one update site after the other and see when the problem goes away? Or if you can't use the backend because of that issue, disable them in database e.g. with phpMyAdmin?

**Comment by vddesign** [comment]
Thank you very much Richard for your help. 
I use 13 3rd party extensions. It seems that two of them are responsible for this problem: Acymailing and JCE Editor.  If I disable them both, there are no notifications, so I leave them disabled for now. Is it meaningful to send the makers of these extensions this issue do you think?
Thanks a lot.

**Comment by richard67** [comment]
> Thank you very much Richard for your help. I use 13 3rd party extensions. It seems that two of them are responsible for this problem: Acymailing and JCE Editor. If I disable them both, there are no notifications, so I leave them disabled for now.

I'm happy you could solve it for now. Thanks for reporting back.

> Is it meaningful to send the makers of these extensions this issue do you think? Thanks a lot.

Of course it is.

I close this issue as duplicate report since we already have some to cater for that. But you still can link refer to it when you contact the extensions providers.

**Comment by richard67** [comment]
Closing as duplicate report. See issues #29778 , #35376 and #34959 .

In this case here it was caused by 3rd party extensions, but of course the core should be able to handle wrong extension manifests or update sites, so these issues need to be solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35815">issues.joomla.org/tracker/joomla-cms/35815</a>.</sub>

**Comment by vddesign** [comment]
Great, Thanks again.

**Comment by richard67** [comment]
Please test #35822 . Thanks in advance.
