### ISSUE TITLE
Authentication with "Active directory" no longer works

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#35829]
Hello,
while it worked under Joomla 3 with the same configuration, the authentication with "Active directory" does not work anymore under Joomla 4.0.3

### Steps to reproduce the issue

**Here is my configuration:**
![ldap](https://issues.joomla.org/uploads/1/fb69873b06c1133d7ef27bec736b2d28.jpg "ldap")

### Expected result

that it works as before.

### Actual result

error message : ldapfailure The login does not match the password, or you do not have an account yet.

### System information (as much as possible)

Joomla 4.0.3

### Additional comments

I did some debugging and found that the users_dn field is not used for "direct binds" when it should be.
To make this work, I modified the joomla/plugins/authentication/ldap/ldap.php file as follows:
						//$ldap->bind($ldap->escape($credentials['username'], '', LDAP_ESCAPE_DN), $credentials['password']);
						$dn = str_replace('[username]', $credentials['username'], $this->params->get('users_dn', ''));
						$ldap->bind($dn, $credentials['password']);

**Comment by PhilETaylor** [comment]
The LDAP in Joomla 4 is so bad as to be totally unusable. It needs a complete rewrite by someone who understands LDAP. 

https://github.com/joomla/joomla-cms/issues/35571
https://github.com/joomla/joomla-cms/issues/35573
https://github.com/joomla/joomla-cms/issues/25434
https://github.com/joomla/joomla-cms/issues/35316
https://github.com/joomla/joomla-cms/issues/35216

https://github.com/joomla/joomla-cms/pull/35323
https://github.com/joomla/joomla-cms/pull/32400

**Comment by nickdring** [comment]
I find it amazing that J4 shipped without a working LDAP plugin

**Comment by CPLT-C1** [comment]
Where's the best place to check for an update on this one? This is a show-stopper for me; I've rolled back to 3.10.3 for now...

**Comment by dallenk** [comment]
working LDAP is a must-have for several of the organizations I support.    Previously I used jmapmyldap (https://shmanic.com/tools/jmapmyldap/download.htm) which works fantastic on a Joomla 3 site.   I am not a coder by any stretch so perhaps this project can be revived with a new fork and updates for Joomla4 ?

**Comment by gopalji** [comment]
I have this LDAP error since php8, the reason I found in isConnected() function of ldapclient.php:

public function isConnected()
{
  return $this->resource && \is_resource($this->resource);
}

the "\is_resource($this->resource" expression causes the error. Uncomment it and it works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35829">issues.joomla.org/tracker/joomla-cms/35829</a>.</sub>

**Comment by PhilETaylor** [comment]
The LDAP in Joomla 4 is so broken it should be removed as a feature completely

**Comment by gopalji** [comment]
Forgot to mention: using Joomla 3.10. 
LDAP authentication essentially for us

**Comment by zero-24** [comment]
@gopalji can you please send a PR against 3.10 with the details to reproduce and the detailed error messages this here is about the J4 LDAP Plugin. Interessting to know would be a detailed error message and maybe with an var_dump on $this->resource to understand why it fails on PHP 8.1

**Comment by richard67** [comment]
Closing as having a pull request. It claims to solve this issue. Anything else which came up in comments here should be handled with separate issues. Please test #37959 . Thanks in advance.

**Comment by FPC-RamonHerrera** [comment]
I pulled down a copy of 4.2.3 today.  The aforementioned fix is in place, my LDAP was broken in spite of that, using the same configuration as many of my other 3.X sites.

I tried dvince38's fix.

> To make this work, I modified the joomla/plugins/authentication/ldap/ldap.php file as follows:
> //$ldap->bind($ldap->escape($credentials['username'], '', LDAP_ESCAPE_DN), $credentials['password']);
> $dn = str_replace('[username]', $credentials['username'], $this->params->get('users_dn', ''));
> $ldap->bind($dn, $credentials['password']);

This absolutely WORKS, thank you dvince38 very much.

**Comment by FPC-RamonHerrera** [comment]
Here is a screen pic of my LDAP plugin configuration.

![image](https://user-images.githubusercontent.com/56167394/194082895-e0cb9ae9-757a-40b8-92a6-3d38914497cb.png)

**Comment by DoctorDeatch** [comment]
> 

unfortunately, it didn't help me :(

**Comment by tatankat** [comment]
A fix is not yet in place, this issue is closed because a pull request to test is available! However, there is a lack of successful human tests to have it included in a release.
Please apply the fix at #37959 and (quoting @richard67):
> please go to the pull request in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/37962 and mark your test result by using the blue "Test this" button at the top left corner, selecting your test result and then submit. Thanks in advance.

After 2 successful human tests, the patch should hopefully be included in a coming release.

@DoctorDeatch you probably have (also) other ldap issues, there are multiple issues with multiple fixes of which you may need a combination to get it working with your setup. (J4: #37962 #37959 #38388; J3: #38750)
I created an new update package that includes all ldap pr, so you test them all at once: https://github.com/tatankat/joomla-cms/releases/tag/4.2.3-patched

Please do test! Please press the blue button!

**Comment by cheesegrits** [comment]
@tatankat any luck getting your PR(s) merged?  Do you still need testers?

I used to maintain my own fork of JMapMyLDAP, but don't have the time or energy to migrate it to 4.x.  But if the native plugin worked properly, I could make do with that.  So I'm happy to help out with testing and anything else you need to get this stuff fixed.

**Comment by tatankat** [comment]
@cheesegrits partially.
The problem reported here should be fixed with the merged PR #37959 in 4.3
For PRs #38388 & #37962, there is still testing to be done.
