### ISSUE TITLE
$category->setKey('id')->setParent($categories, 'parent_id')->setNestable(); Multiple Categories

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35872]
Hi,

is there documentation for the new router in J4 somewhere. I would be particularly interested in the part where an item can have multiple categories. 

Thank you.

Jan

**Comment by brianteeman** [comment]
>  I would be particularly interested in the part where an item can have multiple categories.

That's news to me

**Comment by forify** [comment]
# How to Fix a Cracked Bathroom Basin - Tips That You Should Know

![https://cdn.pixabay.com/photo/2013/02/18/18/35/basins-83090__340.jpg](https://cdn.pixabay.com/photo/2013/02/18/18/35/basins-83090__340.jpg "Kitchen")

If you're looking for ways on how to fix a cracked sink basin, then this article should help. A broken basin can be annoying to say the least. If you have the patience and money to replace a sink, make sure you also repair the basin first. It can cost a lot more to replace a sink than it does to repair one.

Be sure its lined up correctly

There are a few things you can do on how to fix a cracked sink basin. One of them is to make sure the basin is lined up correctly. It's usually the basin that is the problem, not the actual basin faucet.. When you put the sink and faucet together, they don't line up properly, and when you try to use them, there's friction that causes the clogging.

Clean it up!

Another way on how to fix a cracked sink basin is to clean it. Any type of mineral build up will eventually cause the sink basin to drain into the drain. To clean the sink basin, you need to open it up and remove any strainer or rubber stopper inside. If you have a metal basin, you need to open it up and remove the metal clips that hold it in place. These clips can get very sticky and you might need to use pliers to loosen them.

Once you've removed everything from the basin, take some rubbing alcohol and a cotton cloth and clean the area. If you're looking for tips on how to fix a cracked sink basin, this is step number one. Next, put some rubbing alcohol on the basin and wipe off any residue left from the cleaner. Use the cloth to gently rub the area as you work your way around the basin. You should only be doing this for about 10 minutes at a time because if you do it longer than that, the resin or cement that's used to fix the basin might be ruined.

Wipe it dry

Once you've finished cleaning the basin, apply some penetrating solvent and make sure that you wipe it dry before re-using it. You should also check to make sure that any instruments or utensils that you're using with the sink are not damaged. If they are, you can contact a professional to repair the problem for you. As far as keeping water out of a cracked sink, this next tip on how to fix a cracked sink basin will help you out.

Remember to never put ice in there

One last thing that you can do when you want to know how to fix a cracked sink basin is to make sure that you never put ice in the sink. The reason for this is that the ice will cause the basin to freeze and you won't be able to drain the water out. If you want to be sure that the basin is drained properly, you can place an ice cube inside and let it set for about 20 minutes. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35872">issues.joomla.org/tracker/joomla-cms/35872</a>.</sub>

**Comment by joomdonation** [comment]
> is there documentation for the new router in J4 somewhere

The only documentation I can found is https://docs.joomla.org/J3.x:Supporting_SEF_URLs_in_your_component . Maybe this article https://quantumwarp.com/kb/articles/30-joomla/962-my-joomla-modern-router-notes could be useful.

> I would be particularly interested in the part where an item can have multiple categories.

Unfortunately, I don't think we have any build-in support for routing when one item is assigned to multiple categories.

**Comment by forify** [comment]
...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35872">issues.joomla.org/tracker/joomla-cms/35872</a>.</sub>

**Comment by PhocaCz** [comment]
@joomdonation Thank you.

**Comment by richard67** [comment]
@PhocaCz Can this issue be closed?

**Comment by PhocaCz** [comment]
Yes.
