### ISSUE TITLE
Update -> Database Table Structure Up to Date: NO

### ISSUE THREAD

**Issue by Jokerminator** [joomla/joomla-cms#35915]
Joomla 4.0.3 hosted @ Joomla.com (CCP)

### Steps to reproduce the issue
Pre-Update Check for Joomla ‎4.0.4 says "Database Table Structure Up to Date: NO
Go to 'System - Maintenance - Database' and use the 'Update Structure' button."
But the "Update Structure" button is grayed out and the page says "No Matching Results"!

### Expected result
I can click the "Update Structure" button to meet the update requirements.

### Actual result
"Update Structure" button is grayed out, not clickable and the page says "No Matching Results"

### System information (as much as possible)
I created the site 2 days ago @ joomla.com and updated the PHP version to 8.0.1.1.

**Comment by ghost** [comment]
Correction: PHP 8.0.11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35915">issues.joomla.org/tracker/joomla-cms/35915</a>.</sub>

**Comment by richard67** [comment]
Does the page with the button show a table with rows, one for the CMS core and the possibly more rows for 3rd party extensions?  Each of these rows should have a badge showing if there are problems found or not, and when a badge shows that there are problems, details are shown in a tool tip when hovering the badge.

To fix probles it first needs to select the corresponding row(s) before using the “Fix” button. Each row has a check box at the left side for selecting it, like all the other list view in backend have.

Please report back. if possible with screenshots, how that page looks for you and which problems were found and if the “Fix” button works for you when having selected a row.

if the page does not show any rows, please report back which 3rd party extensions you have installed, because very likely it would be a syntax error in an SQL update script if such an extension which causes the database checker break.

Thanks in advance.

It’s a new feature in Joomla 4 that the database checker checks not only the CMS core but also 3rd party extensions if they have update SQL scripts.

**Comment by ghost** [comment]
I attached a screenshot of what I've seen. There is no fix button.

Looks like cloudaccess.net ( the joomla.com hoster ) is working on
something, because the site is *extremely* slow I get kicked out after
about only one minute of being logged in.

**Comment by richard67** [comment]
@XenoEgger I don't see any screenshot, but as I understand it would not really show much, so that's ok. Let us know here if there is something new.

**Comment by ghost** [comment]
Well, I attached the screenshot to the e-mail. Guess that didn't work. So I had to log in to GitHub again.. :((

The only things I did to the automatic, fresh installation @ joomla.com was: Login as admin. I didn't do anything else!
Then I tried to update because Joomla told me that 4.0.4 is available.

<img width="1100" alt="SystemMaintenanceDatabase" src="https://user-images.githubusercontent.com/16600503/139147917-82830326-3ceb-4b24-b2e6-5de498f27798.PNG">

**Comment by ghost** [comment]
This is what I ( sometimes, because sometimes it says 4.0.3 is up to date..... ) see when I click to update Joomla
<img width="1094" alt="JoomlaUpdateWTF" src="https://user-images.githubusercontent.com/16600503/139149292-0d45c9c8-cf27-49f5-aa1e-e5d436983272.PNG">
:

**Comment by richard67** [comment]
@XenoEgger Could you go to the “System” panel and there to section “Manage” and there select “Extensions” and then in the list view of extensions sort by ID in descending order so you see those with the highest ID at the top and then make a screenshot and then post it here? Thanks in advance.

**Comment by ghost** [comment]
I hope the first page is enough.
<img width="1082" alt="Joomla4Extensions" src="https://user-images.githubusercontent.com/16600503/139277854-6bcb63be-1b77-4c54-a4c3-0434c41158be.PNG">

**Comment by richard67** [comment]
Hmm, I see no additional extensions ... I have no idea.

**Comment by richard67** [comment]
@XenoEgger Please apply the changes from pull request #35951 and check if you now can see anything on the "System - Maintenance - Database". If yes, hover over the badge which shows the problem as described in that PR in the testing instructions so you can see the problem details and make a screenshot so we can find out what your problem is.

And mark the test result for that PR as successful in the issue tracker if it works as described so you can see the error details. For doing this you go to the issue tracker here https://issues.joomla.org/tracker/joomla-cms/35951 , use the "Test this" button, select the right test result and submitt.

Thanks in avdance.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35951 . Thanks in advance.

**Comment by b2z** [comment]
I have exactly the same problem on Joomla 4.0.6 running on joomla.com (CCP).  

Wanted to update to Joomla ‎4.1.0-rc2, but:
![image](https://user-images.githubusercontent.com/3051676/152375777-b343bd75-560a-42d6-a295-993ca7bb60f1.png)
![image](https://user-images.githubusercontent.com/3051676/152375881-1f0ec217-811c-40fa-ae4a-478e4af654d7.png)
![image](https://user-images.githubusercontent.com/3051676/152375935-38a13a5b-3a05-405f-ba78-fb3d44c09d3a.png)

I am running this website from beta stages of Joomla 4.0. May be this causing this issue.

**Comment by richard67** [comment]
> I have exactly the same problem on Joomla 4.0.6 running on joomla.com (CCP). Wanted to update to Joomla ‎4.1.0-rc2, but: ![image](https://user-images.githubusercontent.com/3051676/152375777-b343bd75-560a-42d6-a295-993ca7bb60f1.png) ![image](https://user-images.githubusercontent.com/3051676/152375881-1f0ec217-811c-40fa-ae4a-478e4af654d7.png) ![image](https://user-images.githubusercontent.com/3051676/152375935-38a13a5b-3a05-405f-ba78-fb3d44c09d3a.png)

@b2z And does it help to apply the change from PR #35951 ?

**Comment by b2z** [comment]
@richard67 I thought #35951 was merged into 4.0.6 already.

**Comment by richard67** [comment]
> @richard67 I thought #35951 was merged into 4.0.6 already.

@b2z Yes, you are right. Then I have no idea. Maybe you can see something when switching debug on in global configuration and setting error reporting to maximum and then going to the database checker (Maintenance: Database)? If you get a call stack in that case, could you post it here?

**Comment by b2z** [comment]
@richard67 nope. What I think it's kind of artefact of updating from Joomla 4.0 beta versions.

**Comment by Scrabble96** [comment]
I'm having the same problem with a recent installation of J4.0.5 on cloudaccess.host and I haven't installed any beta versions, just J4.0.5 as it was installed for me by CCP. No extensions added. English API Id 215 is the most recent for me, too.

**Comment by bonaondrej** [comment]
Hello, i have the same issue from 4.0.1 ... i several times bypass it by manual update of installation package, however after 4.1.0 the css of site was broken so i revert to 4.0.6.  Any idea? I created a new empty 4.0.0 site without any additional plugin/extension and manually migrate data from 3.x site. But ![screen shot 2022-02-16 at 20 00 49](https://issues.joomla.org/uploads/1/1749db98ee093f9d4954abdae73d9645.png)![screen shot 2022-02-16 at 20 00 50](https://issues.joomla.org/uploads/1/fdcb54d772fd48263dc8b9b69370cecb.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35915">issues.joomla.org/tracker/joomla-cms/35915</a>.</sub>

**Comment by richard67** [comment]
> Hello, i have the same issue from 4.0.1 ... i several times bypass it by manual update of installation package, however after 4.1.0 the css of site was broken so i revert to 4.0.6. Any idea?

@bonaondrej If "bypass it by manual update of installation package" means that you have just uploaded the files but not used the Joomla Update Component's "Upload & Install" method, then it is clear why the CSS was broken: With 4.1, the core templates (Atum for admin and Casiopeia for site) are changed to support child templates. This includes a database change which decides where the templates look for their assets. If you now just copy the files and maybe fix the database (which only fixes structural changes but not data changes), this data change will be missing, and so the templates will look for their assets at the wrong place.

I could provide you with an SQL statement to fix that.

But when reading "i several times bypass it", then I think your database is missing more changes.

Our documentation is very clear about that you HAVE to use the Joomla Update Component and not just copy the files.

**Comment by bonaondrej** [comment]
Thanks Richard,  please send me the SQL fix, a if possibly also previous i could run them in order to fix this "disabled" button.

In worst case i will do full-reinstall

Br

**Comment by richard67** [comment]
How shall I know which other SQL statements haven't been run? It's not a support forum here, and I do not have the time for that.

**Comment by bonaondrej** [comment]
Sorry,  I know that this is not a support forum. Please if possible just send me the latest.

**Comment by richard67** [comment]
https://github.com/joomla/joomla-cms/blob/4.1-dev/administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-11-28.sql#L4

**Comment by tmumm** [comment]
Running the SQL command fixed the admin template issue for me.  But yes, I think other database changes are missing as well.  I don't see the new accessibility plugin was installed, and don't see the button in my article manager.  I did an upload and upgrade, and then did a "reinstall core files"  I've come across this admin template issue on three upgrades on three different hosts.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35915">issues.joomla.org/tracker/joomla-cms/35915</a>.</sub>

**Comment by fusedNL** [comment]
On Joomla 4.1.5 fresh install I have the same issue upgrading.

<img width="1543" alt="" src="https://user-images.githubusercontent.com/43825089/186356069-cd255dae-8298-4cf2-acb4-3b8febda630e.png">

**Comment by Magic73** [comment]
On Joomla 4.1.2 same issue:
![image](https://user-images.githubusercontent.com/7645382/201875652-fe7d0282-ce44-42a7-954f-1f577df0857b.png)

![image](https://user-images.githubusercontent.com/7645382/201875756-d4a3c7be-6bfe-4d1a-981d-b1436ff4870e.png)

![image](https://user-images.githubusercontent.com/7645382/201875805-d78d57ba-2a8b-41ab-ad42-73a48cd424e6.png)

**Comment by brianteeman** [comment]
The problem is that your install did not use the joomla installer - presumably one from your web host?. You should contact your hosts and tell them this. They broke it - they should fix it ;)

Basically The schemas table is missing an entry for the version of joomla installed.

If you are on 4.1.2 then the query should be
INSERT INTO `#__schemas` (`extension_id`, `version_id`) VALUES (220, '[4.1.1-2022-02-20.sql];

**Comment by Magic73** [comment]
but I already update joomla in the past without any issue.

**Comment by krishunt** [comment]
I had the same problem and fixed it by reinstalling the Joomla core files. I was then able to upgrade the site to the next version with no issue. I wonder why this isn't being offered as a solution rather than all the technical blah blah blah and finger pointing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35915">issues.joomla.org/tracker/joomla-cms/35915</a>.</sub>

**Comment by b2z** [comment]
@krishunt thank you for solution. Probably will save the time for others! No one offered, because no one knew how to fix it :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35915">issues.joomla.org/tracker/joomla-cms/35915</a>.</sub>

**Comment by sabersaberi2** [comment]
I know you don't believe me.
But I have the same problem. I didn't use a third-party extension to update Joomla. I tried to upgrade from the latest version of Joomla 3 to the latest version of Joomla 4 from the Joomla core itself. The upgrade process was completed and now I want to upgrade to Joomla 5 but I have this error:

Database Table Structure Up to Date
Go to 'System - Maintenance - Database' and use the 'Update Structure' button.

I also read the following link and followed it:

https://docs.joomla.org/J4.x:Fix_%22Database_Table_Structure_NOT_Up_to_Date%22_before_Update/en

There was already such a row in the database and my problem still persists.
INSERT INTO `#__schemas` (`extension_id`, `version_id`) VALUES
(700, '4.4.4-2024-03-28');

I also go to the
Maintenance: Database
path and click the
Update Structure
option and nothing happens, the page just refreshes.

![Image](https://github.com/user-attachments/assets/7e38e235-8505-4ef9-853f-89d45128a3ff)

**Comment by sabersaberi2** [comment]
The problem by modify in this line RESOLVED and when I update to joomla 5 , that file automatically set to default:
in line 1380 in joomla 4 version:
/administrator/components/com_joomlaupdate/src/Model/UpdateModel.php
change the 
return false 
to 
return true
in the joomla5 that line automatically in line 1370
