### ISSUE TITLE
[4.0] Indexer breaks when content ist too long 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#36054]
### Steps to reproduce the issue

Updated an installation from J3 to 4.0.4. Years ago, editors used to add images into articles with drag and drop into the editor. 

### Expected result
The record is skipped during indexing. 

### Actual result
The indexer breaks 
![image](https://user-images.githubusercontent.com/1035262/141787074-2d149f0f-86cd-4cbb-9db0-6266109c46de.png)

**Comment by Quy** [comment]
@Hackwar

**Comment by Hackwar** [comment]
That looks like a third party finder plugin, not a core issue. I had similar issues with DOCman, who have insanely long routes which they want to store in that field. The field in the DB is already 400 chars long and I don't want to extend that further, among other reasons because we are getting issues with index length. Normally, the route should be like 50 chars at max...

**Comment by chmst** [comment]
Thanks!  I close this for now, as I cannot repeat this at the moment.
