### ISSUE TITLE
Error while installing sample data

### ISSUE THREAD

**Issue by Shubhamverma2796** [joomla/joomla-cms#36064]
Installation of sample data fails as shown in the below video:

https://user-images.githubusercontent.com/54266411/142010821-5460dd05-d230-4a8e-8f31-aa473e94ba76.mp4

Also, whenever I click on the "x" button, the error message is removed, but the loading bar is stuck in between, as shown in the above video, and clicking on the other "Install" buttons also doesn't work.

Imo, the loading bar should also be removed after clicking on the "x" button even if the installation fails because a stuck loading bar creates confusion to the user.

**Comment by chmst** [comment]
Thanks for reporting. There are 2 issues. Do you know the reason, why the installation failed? This should not happen. 

Did you start the sample data installation on a fresh database? Or repeat the installation?

**Comment by Shubhamverma2796** [comment]
@chmst  I am not aware of the reason. After setting up the Joomla in the local host, I tried to install the sample data and encountered these errors.

**Comment by Bakual** [comment]
It's expected that you need to refresh the page after an error before you can install another sampledata. The install buttons get deactivated to prevent installing multiple sampledata in parallel. So that part isn't really an isssue. 
As for the failed installation itself, the multilingual is a bit tricky as the error message doesn't reveal much helpful. For some reason it can't create the menu. Most likely it already exists. The other two sampledata are quite straightforward - an identical tag already exists.

This could happen if you already installed the sampledata before and didn't remove it completely. Then it is expected to fail.

**Comment by Shubhamverma2796** [comment]
@Bakual, can you please tell me how I can remove the sample data completely so that I can get rid of these errors.

**Comment by chmst** [comment]
Sample data cannot be deleted. The easy way is: 

Delete your configration.php file. This lets install you joomla again with a fresh database. 
Give this database a new name or delete the old database before you install new.

**Comment by Bakual** [comment]
Delete all Tags, Content Items (articles, contacs, ...), Categories, Menuitems.
Or do like Christiane said and delete the complete database and do a fresh installation :-)

**Comment by chmst** [comment]
So your issue is not the Error while installing, but the fact that the scrollbar is not deleted after an error message. The issue is related to Errors due to multiple starts of sample data installation. Maybe Related to #22634, #20479 - remove or disable the button after first installation of sample data

**Comment by Quy** [comment]
Duplicate #23633

**Comment by Quy** [comment]
Closing as duplicate.
