### ISSUE TITLE
Progressive caching - Wrong custom module menu assignement

### ISSUE THREAD

**Issue by sirpatrick2** [joomla/joomla-cms#36102]
### Steps to reproduce the issue
Turning on "Progressive Cache" and assigning module to different menus

### Expected result
The Menu should be visible according to the corresponding assignement

### Actual result
Changing the page (menu) the module doesn't change according to what is selected

### System information (as much as possible)
Joomla 4.0.4
Ubuntu 20.04
PHP 7.4 FPM

### Additional comments
maybe the cache prevents from changing the module according to assignments as it keeps the old one in memory

**Comment by phunsoft** [comment]
I'm probably suffering from the same bug. Here are some details.

I'm quite new to Joomla, so please bear with me should I mix up terms.

I've build a new site using Joomla 4.04 using only standard components excpet from the "Latest New enhanged (free)" extension. Template a copy of Cassiopeia, modified by user.css only. The site has a couple of articles so far. The home page has one favourite article and module "Latest News Enhanced" (LNE) at position "main-bottom". The module is set to show on the Home page only (Main menu entry "Home"). 

Other main menu entries point to either category blog, or single articles. There are two (legal) links to articles in the footer.

While developing, the LNE modul was only ever shown on the "Home" page, as desired. This behaviour was seen on  Windows/xampp, as well as on the public server.

After being happy with the look and feel, I enabled caching on the public site, and chose "progressive caching". I did a few changes to articles and categories.

Soon thereafter, the LNE module started to show up on other pages, instead of only the home page. I logged in to the admin backend and double checked, did another save, and the LNE module disappeared again. But only to re-appear a bit later. some more looking into the backend, and all over a sudden, the LNE module did not appear on the Home page, anymore. I was puzzled, could not find a repeatable sequence of actions, both frontend as well as backend, to influence whether and where the LNE module was shown or not.

Then I remembere enabling the cache, and that this unreliable behaviour has started after this confoig change. Switched caching off, and the advese behaviour was no seen since then.

What information should I post to help with this problem?

**Comment by Fedik** [comment]
I can confirm the bug.

For now you can use "Conservative Caching", it seems not affected by this bug.

**Comment by Fedik** [comment]
Please test the fix #36193
