### ISSUE TITLE
Import RSS feed issue in Joomla 3.x

### ISSUE THREAD

**Issue by arlexwong** [joomla/joomla-cms#36120]
### Steps to reproduce the issue
This issue happens when the 3rd party component uses Joomla simplepie library and PHP 8.

JoomlaFolder/libraries/vendor/simplepie/simplepie/library/SimplePie/Parse/Date.php
LINE 544 and 545

0 implode(): Argument # 2 ($array) must be of type ?array, string given

``` PHP
		$this->day_pcre = '(' . implode(array_keys($this->day), '|') . ')';
		$this->month_pcre = '(' . implode(array_keys($this->month), '|') . ')';
```

### Expected result
PHP syntax error 
- implode(separator,array)

### Actual result
It works fine in PHP 5.x and PHP 7.x except PHP 8.

### System information (as much as possible)
Joomla 3.10.3, PHP 8

**Comment by brianteeman** [comment]
Looks like a problem upstream in simplepie https://github.com/simplepie/simplepie/issues

**Comment by zero-24** [comment]
We are shipping an outdated and by the core unused lib here. Within the core we IIRC use our own Feed lib for now. We can not upgrade to the latest version because of the php version supported by J3. J4 does no longer ship with this lib.

So i guess we have to build another backport repo and try to make it compatible with php8.. or mark it as known behavior when that is not possible.

**Comment by zero-24** [comment]
Ok looks like there is still a 1.3 branch that supports php 5.3, but I'm not sure whether they still support that branch in the meaning of doing releases. I have just done a PR + that question lets see what they say: https://github.com/simplepie/simplepie/pull/702

**Comment by zero-24** [comment]
Hi @arlexwong please test: https://github.com/joomla/joomla-cms/pull/36358
