### ISSUE TITLE
[4.1] Child templates and html overrides

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36229]
### Steps to reproduce the issue
Create some html overrides for cassiopeia and then create a child of cassiopeia
Open the child in the template manager and you will see
![image](https://user-images.githubusercontent.com/1296369/183608540-7d9eb119-e23a-4833-89f5-40547be03f32.png)
You have no means of knowing if there is an override in use (present in the parent) or if you are just using the core

### Additional comments
not tested but I would assume that all the messages and information about updated files being present will only appear in relationship to the parent template. It would not be unreasonable for a user to ignore those messages as they are using the template called **andromeda** on their site and the messages are for some other template called **cassiopeia**

**Comment by brianteeman** [comment]
This bit me really hard today. it makes child templates completely useless to me

**Comment by dgrammatiko** [comment]
This is a standing issue for the template manager obviously exaggerated when child templates are also in the mix. The root problem is that the overrides diffing, notification, etc is completely rubbish as almost everything that is coming from GSOC. The whole architecture of figuring out the updated layouts is very wrong (that's even without the child templates). The way that the system tries to figure out what is changed is by checking 2 points the extension entry point and the template `html` folder. I mean it doesn't need much thinking to figure out that this is extremely shortsighted, because there is an API where a developer could intervene and set another layout folder/entry. In such case you get always notifications (what happens to many templates at the moment as they have an intermediate point for their layouts either in a plugin/library/etc) although there might be absolutely nothing changed! This obviously affects the child templates as these are actually using the parent template as their entry (if it exists) layout. In sort it's the same issue many 3rd PD templates experiencing since 4.0!

To the point of your issue:
- when 4.1 was under development this was noted
- it couldn't be patched in some hacky way
- thus it was left for a broader refactor of the whole override notification system

@bembelimen can verify that the decision was to leave that for another minor release, meaning I wouldn't be involved for that issue

**Comment by brianteeman** [comment]
This is not about improving the UI/UX for cosmetic reasons. Without it the entire child templates thing is useless.

It should be something like this. Then you could see if there was an override in place already etc

![image](https://user-images.githubusercontent.com/1296369/183912204-fffd6a9a-7dcd-4813-8967-70b1a1e0239b.png)

**Comment by brianteeman** [comment]
Just another example of unfinished functionality added to the core and then never finished.

**Comment by brianteeman** [comment]
in which case child templates should not have been added. it is useless as it is right now.

I said it wasnt usable and it wasnt complete when it was merged but no one listened again

**Comment by dgrammatiko** [comment]
>  it is useless as it is right now.

I'll repeat again that Child Templates were introduced in 4.0.0. What you're complaining about is the GUI, which obviously you can completely ignore and do things in the CLI or your IDE. The GUI that shipped in 4.1 was a compromise due to B/C restrictions.

**Comment by brianteeman** [comment]
its still useless

**Comment by dgrammatiko** [comment]
> its still useless

Then don't use it, you're not forced somehow to use it.
