### ISSUE TITLE
[4.x] Field Display - suggestion

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36276]
I'm wondering if "render" is perhaps a more complex term than is needed and it would be better to say "display".

## Current
![image](https://user-images.githubusercontent.com/1296369/145394085-99cbada9-40f2-46ff-99bc-b46ab571402b.png)

## Proposal
![image](https://user-images.githubusercontent.com/1296369/145394029-fba7d66c-81ae-4af5-8d1c-75c3278c903c.png)

cc @coolcat-creations @softforge @ceford

**Comment by coolcat-creations** [comment]
I remember creating a layout proposal for this area one day and restructured it into "input" and "output". I hope I can find it somewhere.

**Comment by ChristineWk** [comment]
hi elisa, not sure, maybe this one? #18431

**Comment by coolcat-creations** [comment]
@ChristineWk Thank you!!! yes I guess this was this one, I thought I separated it more clearly into input and output (headlines)

@brianteeman I think the reason why it was named Render Class, is because the file responsible for the output is called like that?

![grafik](https://user-images.githubusercontent.com/828371/145431545-46dba788-443c-4f79-9028-a5b2f47c9710.png)

**Comment by brianteeman** [comment]
please test #36279

**Comment by softforge** [comment]
Display is definitely better than render, Show is an alternative
