### ISSUE TITLE
[4.0.5 RC-4] PHP 8.1 compat

### ISSUE THREAD

**Issue by frostmakk** [joomla/joomla-cms#36293]
### Additional comments
It doesn't look like the updated framework made it to  4.0.5 RC-4

PR #36248 is also essential to avoid crash with error reporting enabled. 
Correction: Nightly build has updated framework and run without this PR.

**Comment by xillibit** [comment]
with debug mode enabled with Php 8.1.0 there are plenty of deprecated messages from debug bar : 

`Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php on line 792`

`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php on line 792`

`Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php on line 808`

`Deprecated: Implicit conversion from float -INF to int loses precision in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\DataFormatter\DataFormatter.php on line 81`

` Deprecated: Return type of DebugBar\DebugBar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\DebugBar.php on line 484`

`Deprecated: Return type of DebugBar\DebugBar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\DebugBar.php on line 479`

` Deprecated: Return type of DebugBar\DebugBar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\DebugBar.php on line 474`

`Deprecated: Return type of DebugBar\DebugBar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\Users\xillibit\git\joomla-cms-40-dev\libraries\vendor\maximebf\debugbar\src\DebugBar\DebugBar.php on line 489`

I think it should be fixed in upstream

**Comment by dgrammatiko** [comment]
PRs exist already: https://github.com/maximebf/php-debugbar/pull/489 and https://github.com/maximebf/php-debugbar/pull/467

**Comment by wilsonge** [comment]
As you can probably see from commit history I did a large round of fixes last night, merging others fixes and merging in the framework fixes.

I'm not coming close to pretending I've fixed all the deprecation warnings - most pages will still have a couple. But they should still work.

I don't realistically see us fixing all of them before the release on Tuesday - especially as noted that several of them depend on upstream dependencies to make a release.

We do best efforts for this release (and practically in a production setup that should be good enough anyhow even though far from ideal). And just keep pushing on at other deprecation issues for the next release in January.

**Comment by xillibit** [comment]
no problem

**Comment by frostmakk** [comment]
4.0.5 is out, and running with maximum error reporting enabled on PHP 8.1, so closing this.
