### ISSUE TITLE
speedy tests

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36308]
we keep getting people doing multiple tests that all occur within 1 minute of each other.

No matter how simple the issue is there is no way at all that they can be tested and reported in such a short time

**Comment by brianteeman** [comment]
@khu5h1 there is no way that you really have tested all the issues you are marking as successful tests. Its just not possible in the time between tests. there is also no ppoint in reporting your fake test results on something that is already rtc

**Comment by richard67** [comment]
I had the same thoughts, but we simply cannot proof anything. Someone might test several PRs in a row and then at the end of all mark the test results for all of them. How can we know if tests were real or fake?

**Comment by brianteeman** [comment]
1. Check their github account it seems joomla is not alone in being a victim
2. As soon as I called them out they stopped
3. As long as we dont accept their tests its not a problem
4. This is not the first time or the only account doing this.

**Comment by khu5h1** [comment]
@brianteeman Actually, for the last 3-4 days I have not added any test to the PR. I was testing all the PRs in a row. So that I may add my results at the end. I have genuinely tested each and every PR.
I will keep this in mind from next time to Test PR and then update the status at the same time. Actually, I was not aware that adding all the tests at the end would create a false impression. 
Also, I had seen other PRs where the testing was done even after RTC so that's why I did the same. I assure you that I will keep this in mind next time.

**Comment by brianteeman** [comment]
As things could have changed between the time that you tested several days ago and the time that you reported the test results it makes your test results almost invalid

**Comment by khu5h1** [comment]
@brianteeman Actually I was not aware of that. But now I am clear and from now onwards, I will post my test results as soon as I will test the PR. :)
