### ISSUE TITLE
[4.0]Site didn't work after update to Joomla 4.0.x with PHP 8.0.13

### ISSUE THREAD

**Issue by banchaa** [joomla/joomla-cms#36313]
### Steps to reproduce the issue

Under the path: JROOT/libraries/src/Document/Document.php
Row: 638

After Update from Joomla 3.10.x to Joomla 4.0.x. Fatal error.

### Expected result

An Array-Variable initiated as $attribs should be created and a key-value-pair automatically assigned to it.
Key: "type"
Value: "text/css"

### Actual result

It's instead breaking the site with a fatal error, because of an avoidable syntax-issue.
See here: https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying

### System information (as much as possible)

--

### Additional comments

The syntax is being written, without having the variable explicitly initiated as an array-variable first. For the current syntax ($attribs['type'] = 'text/css';) to properly work, the $attribs variable needs to exist beforehand.

I Replaced the current syntax at row 638 with the following: $attribs = array('type' => 'text/css');

Site works now.

**Comment by ReLater** [comment]
> the $attribs variable needs to exist beforehand.

from my point of view it does exist. See line https://github.com/joomla/joomla-cms/blob/4.0.5/libraries/src/Document/Document.php#L633
where `$attribs` is initialized as `array()`.

For me it looks like that other code (3rd extensions?, overrides?, template?) uses method `addStyleSheet()` wrongly and passes over `$attribs` with wrong data type instead as of type `array`. Or maybe it still uses the now completely outdated `(url, mime, media, attribs) method signature` instead of `(url, options, attribs) method signature` which is not compatible wit Joomla 4 anymore. See lines from Joomla 3: https://github.com/joomla/joomla-cms/blob/3.10.4/libraries/src/Document/Document.php#L660-L686 that have been removed in Joomla 4.

**Comment by banchaa** [comment]
It was indeed a file of an template.

The file of my template has the following code:
$doc = JFactory::getDocument();
$doc->addStyleSheet($template.'/style/responsive.css');

How should be the code written instead if you would like to assist?

Thank you very much in advance!

**Comment by ReLater** [comment]
Your posted code is not the most "modern" one but it's correct and doesn't throw a fatal error in Joomla 4.
