### ISSUE TITLE
[4.0] Php 8 notices 

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#36528]
### Steps to reproduce the issue

go to a page with a Joomla\CMS\HTML\HTMLHelper::call

### Expected result

no errors

### Actual result

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in libraries\src\Layout\BaseLayout.php on line 119

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in libraries\src\HTML\Helpers\Select.php on line 139

**Comment by PhilETaylor** [comment]
Did you check all the outstanding open PRs ? There are several that fix these things that you can test and mark them as successful and speed up their merging by doing so

**Comment by PhilETaylor** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/36355/

https://github.com/joomla/joomla-cms/pull/36355/files#diff-610ce01e216b006e1d1e4bc6f38eca81debd39639f1ea66322fe37ee1c132ea8

https://github.com/joomla/joomla-cms/pull/36355/files#diff-8bf969a2cd98d0f69d5039e831077436d9d5d7e6b791eadca541187c4854dc6a
