### ISSUE TITLE
[3.10 rc only] Update manager notifies of availability of 4.0 rc update

### ISSUE THREAD

**Issue by akuropka** [joomla/joomla-cms#36614]
### Steps to reproduce the issue
Use "Joomla Next" or "Testing" as update channel.
Update Joomla to a release candidate version equal or greater to 3.10.4.

### Expected result
The system is up to date.

### Actual result
Joomla update notifies about the avilability of a 4.0 release candidate.
However, 3.10 rc update details are given as package URL and in additional information.

### System information (as much as possible)
Windows Server 2016 Datacenter
IIS x64 Installation with PHP 8.0.15

### Additional comments
Update notification for a 4.0 build does not happen for stable releases or release candidates up to including 30.10.3 (as far as I remember). The upgrade notification still appears (which is fine and expected, of course).

### Screenshot
![Screenshot 2022-01-09 at 10-16-46 Joomla Update - Administration](https://user-images.githubusercontent.com/22570574/148676538-24e8ed83-65de-46ca-ba00-ba611cc40944.png)

**Comment by zero-24** [comment]
Hmm please post your mysql version and your minimum stability setting.

Joomla Next should not provide any none stable version.

And the testing update server should force you to go via 3.10.5-rc1 to go to 4.0.6-rc2

**Comment by akuropka** [comment]
Ups, sorry, it's MariaDB 10.6.5 (using mysqlnd 8.0.15).

I just realized that earlier I got an update notification only within the branch (3.10.x) but not for upgrading. This behavior changed since two minor versions (3.10.x), On the testing channel I reiceive stable updates as well (e.g. 3.10.4-rc1 to 3.10.4).

I don't receive an update notification from 3.10.x to 4.0.x (stable).
I receive an update notification from 30.10.x-rcy to 4.0.x-rcy (release candidate).
However, information is inconsistent if you look at the screenshot.

I just checked Joomla next today for writing this issue and it gives me an update notification as well. This may be intended... but don't now if it's intended for Testing as it was not like that earlier. If it's as well intended then this is not an issue, of course. However, 3.10 and 4.0 are two different versions for me as of now (since having projects not working with 4.0 yet due to template issues).

Just wanted to let you know my experience...

**Comment by zero-24** [comment]
Ok i think i got the point now.

There are three update server

Joomla Next (Takes you always to the latest major)
Default (Takes you to the latest version of your current major but not to the latest major)
Testing (Takes you to the latest tagged testing version including providing the upgrade to the latest major)

What is a bit confusing for me is that the download URL and the version showed is different.

I have to try to replicate this exact issue in order to understand what is happening here.

So can you please provide the current version you are running, the updateserver selected and the stability setting used. Will than try to replicate that issue so we understand why the version vs url is different.

**Comment by akuropka** [comment]
I am on Testing > Release Candidate.
![20220112_154239_firefox](https://user-images.githubusercontent.com/22570574/149162108-12670b82-c1ee-4f16-a384-3c894d1e4282.png)

Up to 3.10.3 I did not get any update notice for 4.0.x, from 3.10.4 on I get update notices for 4.0.x.
The update package url and additional information always displayed 3.10.x releases, the behavior did not change.

Thank you. 😀

**Comment by brianteeman** [comment]
That's weird.

![image](https://user-images.githubusercontent.com/1296369/149162847-852b9cb9-14b6-4165-b68b-2384c21de526.png)


![image](https://user-images.githubusercontent.com/1296369/149162732-43c664fe-c2e7-4b43-8c13-87ff72a58e01.png)

**Comment by akuropka** [comment]
Yeah, as indicated the update for the 4.0.x major is only found if you're on a release candidate of 3.10.x. If a stable version is installed the next major is not shown.
@brianteeman, if you would update to 3.10.5-rc1 I am confident you would be offered to update to 4.0.x-rc.

**Comment by brianteeman** [comment]
Confirmed. Your initial post was not clear on that

**Comment by zero-24** [comment]
> Yeah, as indicated the update for the 4.0.x major is only found if you're on a release candidate of 3.10.x. If a stable version is installed the next major is not shown.

Yes its intended to have the latest 3.10 instelled in order to get 4.x. With the testing channel you have to check the stability too but this channel not intended for "live" sites ;)

>@brianteeman, if you would update to 3.10.5-rc1 I am confident you would be offered to update to 4.0.x-rc.

Yes and this is also the intended behavior also for the joomla next channel (where it is here the stable versions only)

**Comment by akuropka** [comment]
@zero-24, thanks for clarification.

Yet, this is inconsistent in my idea.

1. The behavior was different before 3.10.4-rc.
2. The behavior does only apply to rc-builds. In the testing channel you receive stable builds as well and stable builds (even in testing channel) do not offer update to next major through this update function. So, in the very same channel the update policy differs from the build installed on which you have no influence if you follow update advises.
3.  For the time being Joomla 4.0 exists next to 3.10 and both are supported. Thus it should be if you're on 3.10 then you stay on 3.10 but receive rc-builds and if you're on 4.0 you remain on 4.0.

The testing channel is not for production environment. But I use them for testing new builds first to avoid any conflicts in production environment. For the time being I need to rely on 3.10 for some installations as templates are not adjusted yet.

Anyways, just my two cents.

**Comment by zero-24** [comment]
> The behavior was different before 3.10.4-rc.

We changed the behavior to force you to go via the latest version but that was after 3.10.2 starting with 3.10.3 we have not published the stable versions via the testing channel as you can see in the history of commits here: https://github.com/joomla/update.joomla.org/commits/master/www/core/test/list_test.xml

> The behavior does only apply to rc-builds. 

Well yes because we only deliver them via the Testing Channel. ;)

> In the testing channel you receive stable builds as well

Not in the short past the last one was 3.10.2.

> and stable builds (even in testing channel) do not offer update to next major through this update function.

Hmm yes you have to go via the latest 3.10 in that update channel too. Which right now would be 3.10.5-rc1; As you can see here you can update to 4.0.6-rc1 when you are on the "target platform version" 3.10.5-rc1 using the testing channel: https://github.com/joomla/update.joomla.org/blob/master/www/core/test/list_test.xml#L10

> For the time being Joomla 4.0 exists next to 3.10 and both are supported. Thus it should be if you're on 3.10 then you stay on 3.10 but receive rc-builds and if you're on 4.0 you remain on 4.0.

Yes that is what is happening with the default channel: you stay within the current major. You have to use the Joomla Next Channel to get to the next major.

With the testing channel we have the problem that we can not provide both features with one update server. So one thing would be we "mimic" the Joomla Next or the Default channel. Right now we mimic the Joomla Next Channel allow everryone to test the update to 3.10 rc builds and starting from there to 4.x rc builds.

When you want to stay on 3.10 you have two options. Keep using the Testing update server, update always to the latest 3.10 builds but ignore anyupdates provided to J4. THe other way arround is to switch back to "Default" after updating to an 3.10-rc build.

> The testing channel is not for production environment. But I use them for testing new builds first to avoid any conflicts in production environment. For the time being I need to rely on 3.10 for some installations as templates are not adjusted yet.

Thats good, thanks for doing that.

## Next Steps

Ok I think i understand the issue now and would prepare the following for 3.10.5 onwards:
- Default: Will keep you within the current major (3.10.x / 4.x) (-> No changes here)
- Next: Will always provide the latest major but foces you to go via the latest 3.10 release for now. (-> No changes here)
- Testing: This update server will provide you to the latest released builds, starting with RC releases, but now will include stable builds. This update server will still mimic the Next update channel and provide the latest 4.x release when you are running the latest 3.10 release.
Meaning the Testing Channel is going back to also provide stable packages but still mimic the Next channel to allow the tests  updates between 3.10 and 4.x using this channel.

Would that work for you?

**Comment by akuropka** [comment]
Hi @zero-24,

thank you for your reply in detail. 

That may be that there have not been any stable builds most recently but now the stable is offered again, everything as you indicated. I think the proposed solution is workable. The disadvantage is that by default frequently update notices are sent by email which is a good feature in General.

I will be switching to the default channel now as I can track updates on GitHub as well and install as needed for the time being (I am working on going to 4.0 but time is limited for such things).

Keep up the great work and thanks for all!
