### ISSUE TITLE
[4.0.6] Fatal error redirect.php

### ISSUE THREAD

**Issue by mger1994** [joomla/joomla-cms#36800]
After changeng one language to another and again to the first lange redirect system get fatal error. ![screen shot 2022-01-23 at 08 51 49](https://issues.joomla.org/uploads/1/cf55a6c7bb2986110f179534f9b310a8.png)

![screen shot 2022-01-23 at 08 51 53](https://issues.joomla.org/uploads/1/58a14f009fd920e7f1066d99d06d31da.png)
In previous version i had no problem with redirect.

**Comment by brianteeman** [comment]
https://docs.joomla.org/J3.x:Redirects_from_Redirect_system_plugin_(if_enabled)_cause_internal_server_errors_500

**Comment by richard67** [comment]
@mger1994 Please check and report back if the information linked in the previous comment solves your issue. I think it will. If it does, this issue can be closed. Thanks in advance.

**Comment by richard67** [comment]
Closing as it's for sure solved with PR #36733 . See the linked documentation for a workaround until the fix is released: https://docs.joomla.org/J4.x:Redirects_from_Redirect_system_plugin_(if_enabled)_cause_internal_server_errors_500<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36800">issues.joomla.org/tracker/joomla-cms/36800</a>.</sub>
