### ISSUE TITLE
Untranslated message JLIB_JS_AJAX_ERROR_OTHER when changing the menu of a menuItem

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37108]
### Steps to reproduce the issue

This is not always replicable 

J4.1 with blog sample data and debug modus on 

Open the home item (in main menu) and change the menu, save and close (vite, vite!). 

### Expected result
Success message

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/154859593-d2cb5a59-0163-4de2-86e5-99b355c92b88.png)
for a short moment this message appears and disappears after a second. 

### System information (as much as possible)
Working on xampp, php 8.0, win11, System debug on, error-reporting maximum. 
Console shows a 303 and something with core.js in line about 400. but only for a few moments
This is not always replicable - maybe it depends on the the time between actions.

**Comment by Fedik** [comment]
This error means that JSON response is broken. That happen when error-reporting maximum on php 8+.
Because PHP add Deprecation notice to response, that breaks whole JSON response.

It is translated:
https://github.com/joomla/joomla-cms/blob/f412e135298643bab6255fe498db69a5c8a91dbb/administrator/language/en-GB/lib_joomla.ini#L663
https://github.com/joomla/joomla-cms/blob/f412e135298643bab6255fe498db69a5c8a91dbb/language/en-GB/lib_joomla.ini#L662

However it may be not loaded to JavaScript, on that page, like here example:
https://github.com/joomla/joomla-cms/blob/ea5af7b57c969f47b15b5bc80ca8b8cf6bff2290/administrator/components/com_scheduler/tmpl/tasks/default.php#L31

**Comment by brianteeman** [comment]
Can you still replicate this? I tried and couldnt

**Comment by chmst** [comment]
Could not replicate - maybe caused by my localhost
