### ISSUE TITLE
Missing map files

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#37121]
### Expected result
Every file that mentions `//# sourceMappingURL=` should have an associated .map file as mentioned

### Actual result
A couple of files that mention a .map file, don't actually have one.

### System information (as much as possible)
This is all straight from Joomla 4.1

### Additional comments
Missing map files:
\media\vendor\webcomponentsjs\js\webcomponents-bundle.js.map
\media\vendor\jquery-migrate\js\jquery-migrate.min.map

From what I've seen, most browsers that can't open the .map file continues working without error, but some browsers that I've been testing with have been throwing 404 errors and complaining that files can't be found.

**Comment by brianteeman** [comment]
> but some browsers that I've been testing with have been throwing 404 errors and complaining that files can't be found.

And they are? or is it a secret you want to keep to yourself. Seriously if you want me to appreciate the issue and it is reproduceable then you need to give them all the required information

**Comment by Chaosxmk** [comment]
Oh, sorry, completely forgot that information. I noticed it in Safari 10.1.2 and Internet Explorer 11. I was going to test more browsers, but I'm having issues. I suspect it's more of an issue with older browsers that were just starting support .map files.

**Comment by dgrammatiko** [comment]
Couple of things here:

- Joomla 4 by default never loads jQuery in the front end
- even if you load it, will **not** load the migrate script as this is ONLY for development (so check your extensions)
- The web components polyfill in reality will never be used as the supported browsers for J4 don't need it!

- Joomla never had map files for the javascript files (and unless someone radically changes some APIs won't happen any time soon)
- The reason is simple: Joomla also provides a DEBUG mode where it serves the non minified version of the script, so, unless you're doing some heavy bundling (Webpack/Rollup/etc) you don't need maps
- The reported missing files are **ONLY** reported **IF** someone opens the browser inspector (which is the initiator for fetching this files). What I'm trying to say here is that this is not an issue.

**Comment by Chaosxmk** [comment]
I figured that the response would be similar to this, as it honestly doesn't actually affect anything meaningful. Just figured that since I saw it I'd report it. Feel free to close this issue if there are no plans on changing this.

**Comment by alikon** [comment]
then let's close it ;)

**Comment by dgrammatiko** [comment]
@alikon just a comment here, although this was rightly closed there are no docs on how/why Joomla is dealing with static files/assets. So, some time this issue might reappear, because many people are not aware of Joomla's ways of doing things. Maybe it's time to setup a git based documentation for developers (clone vue's docs?). It takes zero effort and sharing knowledge is a solid base for growth.

end of rant

**Comment by brianteeman** [comment]
@dgrammatiko https://github.com/joomla-projects/developer-documentation
