### ISSUE TITLE
article order in category blog

### ISSUE THREAD

**Issue by burninghey** [joomla/joomla-cms#37179]
### Steps to reproduce the issue
Try to reorder articles in a category blog

### Expected result
As mentioned in tutorials for joomla 3, the article order in admin panel should carry over to the frontend. 
There should be an option for sorting articles in the category settings

### Actual result
Article order in the backend is not connected to the frontend. Even worse, if one logged in user sorted articles in the frontend (via setting to category list, sorting, set back to category blog), it's saved per device, and overwrites any global setting.

Option for sorting arcticles (as shown in the category list type) does not display for the category blog. 

### System information (as much as possible)
Windows 10, Opera Browser

### Additional comments
Workaround: set type to category list, choose category, set a sorting method, save, revert type to category blog, choose category, save. BE SURE to not have set any personal order, ask a friend to peer-review the page from another device

**Comment by chmst** [comment]
Thanks for your first contribution. I have a few questions. You are working in Joomla 3.10?

You say that the order of articles is not visible in frontend. In general it is, we have no other issues for this feature. 
How are you presenting articles in frontend? In a blog - and which ordering is defined for this blog? 
Can your users change menu items and ordering of articles in blog layouts? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37179">issues.joomla.org/tracker/joomla-cms/37179</a>.</sub>

**Comment by brianteeman** [comment]
> As mentioned in tutorials for joomla 3, the article order in admin panel should carry over to the frontend.

Only manual ordering does that - nothing has changed here - all the tutorials are still correct.

There are two places to set the ordering. The first is the artcile options when you can set the default site ordering

![image](https://user-images.githubusercontent.com/1296369/156424961-27778bc3-070f-48a9-ad21-80a567017d57.png)

Or in the menu item 
![image](https://user-images.githubusercontent.com/1296369/156425165-2491c57f-6828-4cca-9c81-fe5182f9639c.png)

If set in the menu item it will override the setting in the article options for that menu.

If you want to have a manual ordering of your articles etc then after ordering them in the admin you need to set the options above to "ordering" instead of date etc

**Comment by burninghey** [comment]
Thank you for your time. Just noticed the second option, missed it before. 

Main issue here are unexpected results. I tried to change the order in the frontend first, but this was only for me. After that, anything i did in admin panel had no effect for my device. Seems a personal order is saved somewhere in the cookies. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37179">issues.joomla.org/tracker/joomla-cms/37179</a>.</sub>

**Comment by brianteeman** [comment]
I guess this can be closed now
