### ISSUE TITLE
MariaDB and Galera cluster 10.5

### ISSUE THREAD

**Issue by TristisOris** [joomla/joomla-cms#37195]
Starting from MariaDB version 10.5 and higher, within the Galera database cluster, Joomla 3.10.6 does not work correctly with the entry in the database. At any attempts to make changes from the site, an error message appears (see screenshot) and the DB node drops out of the cluster.

at 10.5, 10.6 it works only as single node mode.
at 10.4 works both single and cluster.

was no any logs at Galera, so nothing to attach.
![screen shot 2022-03-03 at 12 29 38](https://issues.joomla.org/uploads/1/1bacab7a96450aead794f805f20dd540.png)

**Comment by PhilETaylor** [comment]
MariaDB is not officially supported and only MySQL is https://downloads.joomla.org/technical-requirements

In the early days of the fork there was not much difference, as time goes on the two products will diverge more and more. 

At the moment this is not a Joomla issue, because it doesn't fall under the remit of "supported server software"... 

3 years ago @mbabker stated on twitter "Theoretically, as long as any MySQL "drop in replacement" remains compatible with MySQL features & C libraries that PHP uses (MariaDB or Percona as 2 big examples, and yes I did have a deployment on Percona for a bit), any of them can be used as a backend for Joomla without issue"

3 years is a long time.

**Comment by TristisOris** [comment]
oh, we totaly miss this moment. Got it, thank you.

**Comment by HLeithner** [comment]
The problem shouldn't be MariaDB, my servers using percona-server without problems.

But the cluster setup needs special attention which is hard to support if since we don't have a test system. So as long as nobody came up and help us on this topic we can't support database clusters.

I'm closing this for the moment. if you like to help you can reopen the issue at anytime.

PS: sooner or later we need a mariadb specific database driver but I would expect that wouldn't solve the cluster problem.

**Comment by joomleb** [comment]
@HLeithner 
> PS: sooner or later we need a mariadb specific database driver but I would expect that wouldn't solve the cluster problem.

I'm totally agree as @alikon wrote here https://github.com/joomla/joomla-cms/issues/34847#issuecomment-970529194  and  here https://github.com/joomla/joomla-cms/issues/36183#issuecomment-985011118
From MariaDB 10.5 (and 10.6) the fork between it and MySQL began to be more and more relevant...
