### ISSUE TITLE
Menu Item Type Alias Settings Use Redirection Yes/No always redirect and in a strange way

### ISSUE THREAD

**Issue by hehemrin** [joomla/joomla-cms#37264]
### Steps to reproduce the issue

Create article One. 
Create menu item A: Menu Item Type > Articles > Single Article
Select article One. 
Create menu item B: Menu Item Type > System Links > Menu Item Alias
Select article One. 
Settings for menu item B > Use Redirection: No

### Expected result

1. Click on menu item A: Will show article One under menu item A. 
2. Click in menu item B: Will show article One under menu item B. 

### Actual result

1. Will highlight both menu item A and B. Else works as expected. 
2. Will redirect to menu item A, despite setting Use Redirection = No. Or actually, it will highlight both menu items A and B. Furthermore, if Item A and B are placed on separate menus, that are displayed one at a time, it will be menu item A that is shown.
Finally, if I change settings Use Redirection = Yes, I cannot see any difference in Actual result. 

### System information (as much as possible)

Joomla 3.10.6. 
I have no knowledge if same issue occurs in Joomla 4.

### Additional comments
Has been/is under discussion in Joomla forum topic: [Menu Item Type Alias > Use Redirection > No > has no affect](https://forum.joomla.org/viewtopic.php?f=706&p=3655311#p3654964 "Menu Item Type Alias > Use Redirection > No > has no affect")

**Comment by hehemrin** [comment]
### System information addendum: 
Firefox 98.0 on macOS 12.2.1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37264">issues.joomla.org/tracker/joomla-cms/37264</a>.</sub>

**Comment by pepperstreet** [comment]
Hello, it's been a while, but I had the same thoughts and experiences like you. 
I have to do some further tests, but I guess it is still the same behavior. 
In my opinion and at least for **Joomla! 3.x** , I would expect to have two different parameter settings and results:  
 
- Redirect should lead to the original MenuItem. Therefor use the originals ItemID and the Alias. 
- No Redirect should use the Alias's MenuItemID and also its alias. 

As far as I can tell, that is NOT the behavior at all. 

As far as **Joomla 4.x** is concerned, there is no change either. 
Except for the conditional display of the parameter _Template Style_! So, it obviously should also have an effect on the applied template style. I have found a related description in the J!4 help, which does mention that "Style" keep/change feature. But only that feature. No other hint of a correct use case or intended behavior.

Since there is no difference in J!3 and 4 , I consider this a bug. Or at least it is an incomplete feature.  
Maybe there are other users with experiences or a better explanation for the _**Alias**_ MenuItem Type?

(PS: I am going to report this for J!4. I could not find another issue/topic)

**Comment by hehemrin** [comment]
Good pepperstreet to hear you have same/similar experience and view of my bug report. I have not started my migration to J4 yet, but have had this bug in mind hoping it was solved, because it is still an issue for me. But now when you have found it is not solved in J4, great that you will report the issue! I intend to migrate well before EOL of J3, but unfortunately I cannot do any trials myself for time being. When you have reported on J4, please give a reference here so I easily can follow up and join on J4 when I'm there!

**Comment by Hackwar** [comment]
This is actually expected behavior. The "Menu Item Alias" is simply copying the link it points to to the position of the alias menu item in the menu. It does not create a new route or a new menu item, especially if you don't use the redirection. This is not a bug.

**Comment by brianteeman** [comment]
so what is the expected difference in behaviour when redirection is enabled or not

**Comment by hehemrin** [comment]
It is of course good if my bug is not a bug. 
But I cannot help I do not understand that it is not a bug. 
### Example
I write an article named "Apples". 
In the main menu I create a menu item "Apples" with the article "Apples" as a Article- Single article type. 
In the main menu I also have an item "Farming".
"Farming" opens as a separate menu. '
In this second menu I have a menu item "Apples". 
I use Manu Item Alias and reuse the article "Apples". 
I want the user to stay on this second menu and therefore I mark "Use Redirection" = No. But when I go to the page, I jump to the article in the main menu instead. I am redirected in my opinion. 
If I instead mark "Use Redirection" = Yes, I will also jump to the article in the main menu. I am redirected, which is correct. 
(If I instead have both menu items on the same menu, same level, I will se both menu items highlighted.)
### So
I do not understand the purpose of the button "Use Redirection" Y/N. If it is not a bug, I would like to understand what the difference is between yes and no. 
I am not a Joomla expert all, so I can absoultelt be mistaken. But please help me and explain more why this is not a bug. And it is also appreciated if explained if it is possible to somehow achieve what I want to achieve. 
(See also the linked forum thread that lead to this bug report.)

![redirect](https://user-images.githubusercontent.com/37445161/220691387-95be59a4-638f-4bea-a98c-2876432e84c3.png)

**Comment by Webdongle** [comment]
https://docs.joomla.org/Help4.x:Menu_Item:_Alias#Form_Fields 
> Use Redirection. The Template Style field is not used if this options is set to Yes.

But https://help.joomla.org/proxy?keyref=Help310:Menus_Menu_Item_Menu_Item_Alias#Details
> Use Redirection. (Yes/No) If set to Yes then visitors will be redirected to the linked menu item.

So in J4 Use Redirection applies to using/not using the Templates css?
But in J3 it applies to the menu item redirecting/not redirecting the menu item?

Please someone describe the logic to this

**Comment by pepperstreet** [comment]
Closed!?

**Comment by Webdongle** [comment]
Typical.  Questions asked about discrepancies and the thread gets closed.

**Comment by joomdonation** [comment]
Looking at this issue, I have to agree that this is a bug. As of right now, the **Use Redirection** parameter does not have any affect at all, it always links to the original menu item.

From looking at the code, I think it is designed so that when **Use Redirection** is set to Yes, there will be a 301 redirect to the original menu item, not link to original menu item as you all described here. We still have code in our [SiteApplication here](https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Application/SiteApplication.php#L748-L780)

So maybe that **Use Redirection** set to Yes is designed to allow redirecting from old link to new link, same as how our Redirects manager works these days ? As we have Redirect Managers, maybe it is not needed now?

No clue how **Use Redirection** set to No should work. Maybe it should work as how it is now.

**Comment by Webdongle** [comment]
So it's another Joomla enigma that everyone has an opinion of, nobody agrees on and nobody knows what the heck it does?
