### ISSUE TITLE
[4.1] Brand change "1" to true

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#37352]
### What needs to be fixed
Just download and install the zip
Copy the template compare database and both contain Brand "1"

Change the name of the copied template and compare the databases and in the *_template_styles table there was a change in the Brand record. It went from "1" to true.

In the first step when making the copy of the original template it was kept as "1", the difference was caused by changing the name of the copied template, it was at that moment that it changed from "1" to true.

Original
{"brand":"1","logoFile":"","siteTitle":"","siteDescription":"","useFontScheme":"0","colorName":"colors_standard","fluidContainer":"0","stickyHeader":0,"backTop":0}

Copied
{"brand":"1","logoFile":"","siteTitle":"","siteDescription":"","useFontScheme":"0","colorName":"colors_standard","fluidContainer":"0","stickyHeader":0,"backTop":0}

Change Name
{"brand":true,"logoFile":"","siteTitle":"","siteDescription":"","useFontScheme":"0","colorName":"colors_standard","fluidContainer":"0","stickyHeader":0,"backTop":0}

**Comment by ReLater** [comment]
In my case it's sufficient to open & save the template style "Cassiopeia - Default" to have in `params` field of db table `template_styles` a `"brand":true` or `false`. After Joomla installation it was `"brand":1`.

It's not really an issue (but inconsistency) because cassiopeia code doesn't use "type-casted" checks for this setting (but integer for default value 1). Example:

`<?php if ($this->params->get('brand', 1)) : ?>`

Addition: The relevant field is a radio field with switcher layout.

**Comment by chmst** [comment]
Please test #4148

**Comment by richard67** [comment]
> Please test #4148

#41458 !
