### ISSUE TITLE
[4.1] Workflow missing translations

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#37390]
### Steps to reproduce the issue

1. open com_workflow/stage/edit (new)
2. open com_workflow/transition/edit (new or edit)

### Expected result

No untranslated strings

### Actual result

2 untranslated strings
1. `COM_WORKFLOW_STAGE_FORM_NEW` → code and language mismatch #32060
https://github.com/joomla/joomla-cms/blob/882fa8682227ee9ee64ddaf81bfb686ed012277c/administrator/language/en-GB/com_workflow.ini#L77-L78
https://github.com/joomla/joomla-cms/blob/882fa8682227ee9ee64ddaf81bfb686ed012277c/administrator/components/com_workflow/tmpl/stage/edit.php#L36
3. `JGLOBAL_FIELDSET_NOTIFICATION` → missing fieldset label
https://github.com/joomla/joomla-cms/blob/882fa8682227ee9ee64ddaf81bfb686ed012277c/plugins/workflow/notification/forms/action.xml#L4

### System information (as much as possible)

Joomla: 4.1.1-rc3-dev
PHP: 8.1.1
DB: 10.4.22-MariaDB

**Comment by infograf768** [comment]
Error only for one string
 COM_WORKFLOW_STAGE_FORM_ADD="Add Stage" 
 
 Easier to modify code to use `ADD` instead of `NEW` as release is tomorrow Tuesday 29
 
 ` <form action="<?php echo Route::_('index.php?option=com_workflow&view=stage&workflow_id=' . $input->getCmd('workflow_id') . '&extension=' . $input->getCmd('extension') . '&layout=' . $layout . $tmpl . '&id=' . (int) $this->item->id); ?>" method="post" name="adminForm" id="workflow-form" aria-label="<?php echo Text::_('COM_WORKFLOW_STAGE_FORM_' . ((int) $this->item->id === 0 ? 'ADD' : 'EDIT'), true); ?>" class="form-validate"> `

**Comment by brianteeman** [comment]
The date of the release is irrelevant to the fix

**Comment by infograf768** [comment]
`The date of the release is irrelevant to the fix` 

It is not in this case. It is easier at this stage to modify the code as anyway the RC code is to be modified just before release to cope with security.

I suggest you think a bit further before writing.

**Comment by brianteeman** [comment]
and thats why we had such crap code all over the place that we now have to fix.

**Comment by bembelimen** [comment]
I guess it's me, but I'm checking with the [latest RC](https://github.com/joomla/joomla-cms/releases/tag/4.1.1-rc2) and can't find the element. Would someone give me a screenshot/hint?

**Comment by brianteeman** [comment]
it's the aria-label

**Comment by bembelimen** [comment]
Yeah, I checked that, too

![grafik](https://user-images.githubusercontent.com/1229869/160375620-79f1fe54-8028-43a7-9f95-a129db2b1029.png)

**Comment by brianteeman** [comment]
its easy to miss in the report but

Stage - New

Transition - New & Edit

**Comment by bembelimen** [comment]
Ah, ok, thanks. If someone could make a PR today, I can get it in for the 4.1.1 release.

**Comment by richard67** [comment]
> Ah, ok, thanks. If someone could make a PR today, I can get it in for the 4.1.1 release.

@bembelimen PR for changing it in the PHP file? Or for adding a new language string in the language file?

**Comment by richard67** [comment]
And what about the 2nd error with the missing fieldset label? The discussion above was only about the first error.

**Comment by bembelimen** [comment]
Fix the language files

**Comment by bembelimen** [comment]
So be more clear:
it would be nice to have two PRs, one adding the strings to the language files, one fixing the label.

**Comment by richard67** [comment]
@bembelimen For point 1 see #37393 . With the missing label (point 2) I do not see any issue. It looks like it should here:

![2022-03-28_workflow-transition-notification](https://user-images.githubusercontent.com/7413183/160400500-2e0d7611-2bf0-4d2e-be22-5878535679ba.png)

**Comment by richard67** [comment]
For the first point please test #37393 .

**Comment by richard67** [comment]
For the second point I see no issue. Even without a label, the tab title and the legend of the fieldset have the right value and are translated well.

And I see many other places where we have fieldsets without label.

But if I should add one, I would use text "COM_WORKFLOW_NOTIFICATION_FIELDSET_LABEL" because that's the text of the workflow notification plugin, and when that id disabled the notifications tab in the transition edit is not shown.

@brianteeman What do you think? Is that necessary and is it right?

**Comment by brianteeman** [comment]
just been loking at that one. its a bit tricky as its an injected plugin and the string is used for the tab title and the fieldset afaict

![image](https://user-images.githubusercontent.com/1296369/160415421-919c9be4-8fc6-4b2f-9bbe-dea847d49a4b.png)

I cant see how/where t he compound string is being generated so the only option i am aware of is to create a new string

JGLOBAL_FIELDSET_PUBLISHING

**Comment by richard67** [comment]
@brianteeman We already have a string for that in the workflow notifications plugin. See PR #37394 .

**Comment by brianteeman** [comment]
yes - sorry. multitasking and failing

**Comment by richard67** [comment]
Closing as we have PRs now for both issues, see PRs #37393 and #37394 .
