### ISSUE TITLE
[4.1] Information about the new feature for two-factor authentication

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37482]
### Steps to reproduce the issue
When installing 4.1, 4.2 and probably higher, among other things, we get a brief message about the possibilities of two-step authentication on the site.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/161566239-f03f8a1a-8fab-4a1c-9a9e-1dbbac4bbf41.png)

In 4.1, the option to enforce authentication for groups of users was added.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/161566262-9c3d0fc7-7c75-4b12-ba99-a45f271add0d.png)

My suggestion is to correct (expand) the 2-Step Verification capabilities message a bit as improvements have been made to it. After all, this will also apply to new users.

If the maintainers don't find it necessary, please close it.

**Comment by richard67** [comment]
My 5 cent: Yes, the message could be improved by adding a short sentence about the possibility to enforce it for particular user groups and where this can be done.

And I think it might also be a chance to change the description so that it makes clear that you can also use other OTP authenticators and not only Google. Currently it reads as if it would work only with that one.

But I'm only one maintainer, let's wait for more opinions.

**Comment by brianteeman** [comment]
@richard67 I did update the plugin description to reflect that six years ago. You can use the same/similar text here https://github.com/joomla/joomla-cms/pull/12833

**Comment by richard67** [comment]
@Kostelano Why closed? Did you close the wrong issue by accident? Or is it not an issue for you anymore?

**Comment by Kostelano** [comment]
I close, because 4.2 introduced MFA.
