### ISSUE TITLE
full image should not have lazyload

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#37751]
### What needs to be fixed
Joomla adds (layout/joomla/html/image.php) lazyload to article full image, this is wrong by google lighthouse "Largest Contentful Paint image was lazily loaded"    

### Why this should be fixed
Not so good user experience.

### How would you fix it
remove lazyload from full image (keep for intro)

**Comment by dgrammatiko** [comment]
This is up to the designer. The y can do that on their designs:
- override https://github.com/joomla/joomla-cms/blob/3a7a3a2a9c9e1e0ada8a30ba9ea8f6969feedeb6/layouts/joomla/content/full_image.php
- after https://github.com/joomla/joomla-cms/blob/3a7a3a2a9c9e1e0ada8a30ba9ea8f6969feedeb6/layouts/joomla/content/full_image.php#L26 add `'lazyload' => 'eager'`
- Job done.

Joomla as a generic CMS has no idea if the Full Image or any other content needs to be eagerly or lazily loaded. It uses lazy as the default but really it should be the designers job to define those properties PER LAYOUT. There's no way either value will be correct for all cases

Just a correction here, it should be `'loading' => 'eager'` not `lazyload`, sorry my bad

**Comment by drmenzelit** [comment]
Closing this as expected behavior with a good explanation from Dimitris on how to change it.

**Comment by pl71** [comment]
Of course, CMS doesn't know what is visible and what is not.
At least logo image will be visible at First Contentful Paint for sure.
So Cassiopeia template could be modified with `eager` here.
(Intro image should be displayed before fulltext image so the original proposal is also not quite correct) 
Regarding the rest, what is above the fold could be checked at rendering time by JS.
I've experimented with a js script using IntersectionObserver and PageSpeed Insights didn't complain regarding the desktop view. 
However, it still complains about the mobile view.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37751">issues.joomla.org/tracker/joomla-cms/37751</a>.</sub>

**Comment by dgrammatiko** [comment]
> Regarding the rest, what is above the fold could be checked at rendering time by JS.

That will never work on an actual image element and a `src` attribute because of the way img tag works on the browsers. The attribute is signalling the browser AT PARSE time, the js is executing way later (and there should be a complete DOM to act upon) thus you cannot undo the initial signal (eager/lazy) as the images are already queued for fetching (or already in the fetching phase). The only way to make this work with JS is to have a `data-src` instead of a `src` attribute and when the JS executes you switch the loading and data-src attributes but that has 2 huge disadvantages: 
- Needs JS (no progressive enhancement)
- Images are always fetched very late

**Comment by pl71** [comment]
Until browsers themselves handle the subject issue with laziness we can do a little.
Meanwhile, with a significant amount of predictability, we can say that the first image of the first article in `Featured Articles` (div.items-leading) should not have `lazy` loading.
