### ISSUE TITLE
[j4] adde set in tinymce not working

### ISSUE THREAD

**Issue by web54** [joomla/joomla-cms#37895]
### Steps to reproduce the issue
go into tinymce plugin
In advanced tab : set number of set to 4
delete manager from actually set and assign this group to set 3
make some changes in set 3
login as manager

### Expected result

changes in set 3 would be observed if logged as manager

### Actual result

no changes seen as if the manager was in another group

### System information (as much as possible)
Joomla 4.1.4 ( and lower )

**Comment by brianteeman** [comment]
Cannot replicate. Make sure that the user is not in more than one group

**Comment by brianteeman** [comment]
Guess it wasn't a joomla problem after all?

**Comment by web54** [comment]
I just will try to replicate ( haven't had time to)

**Comment by web54** [comment]
tried with a fresh install (softaculous) and same results
I can give you the credentials or post them there  (that is a public test site)

**Comment by brianteeman** [comment]
please send me the details so I can try to see what is the problem as I cant replicate on my servers

**Comment by brianteeman** [comment]
never mind - found the bug

**Comment by brianteeman** [comment]
maybe @fedik or @dgrammatiko will find the problem before I do.

Basically what is happening is that tinymce is ignoring the additional set. It displays a default instead (which is why I didnt spot it before)

**Comment by brianteeman** [comment]
and just to make more fun - the same bug is present in j3

**Comment by web54** [comment]
Another funny thing: I only saw this bug because I was doing tests for my conference in Brussels about the personalization of the joomla admin for groups.
It's something I never use, and apparently, nobody else does either ;)

**Comment by brianteeman** [comment]
I personalise it a lot just dont think I've ever had a need for more than two sets

**Comment by Fedik** [comment]
That is correct behavior. 
Keep in mind that the order is important, smallest number has "greater access":
Set 0 - greater access
Set 1 - lowest than previous
Set 2 - lowest than previous
Set X - lowest than previous

What you actualy doing:
0 - greater access/ admin
2 - lowest access/ public
3 - greater access/ manager

The plugin will loop from `Set X` to `Set 0` (from lowest access to greater) and stops on last good match.
Because Manager also has Public access the plugin will stop on "Set 2" instead of "Set 3".

https://github.com/joomla/joomla-cms/blob/c69835953bd622a021dabbe791e62c6ef7fd0e52/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php#L136-L154

**Comment by Quy** [comment]
Closing per comments.
