### ISSUE TITLE
Media-Manager: No upload from Camera with Android

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#37939]
### Steps to reproduce the issue
1. Login with Android mobile device
2. Go to media manager (or article picture-upload) and try to upload an image
3. Chose Camera and take a picture with your mobile phone camera
4. try to upload this to Joomla!´s media manager
5. wait until progress-bar is ready

### Expected result
taken picture is uploaded/shown in media manager and can be used

### Actual result
the picture is NOT uploaded cannot be used

### System information (as much as possible)
Joomla! 4.1.4
Android mobile phone (different ones)
I think same with Apple iPhone (but not sure)

**Comment by brianteeman** [comment]
i had no problem with android 12 using media manager, selecting uoload, then camera and takimg a photo.

**Comment by dgrammatiko** [comment]
![FTmm_KeWIAIt6gn](https://user-images.githubusercontent.com/3889375/171183894-9fa17fbb-3d88-4b03-8d09-36551bd9a628.jpeg)

**Comment by simbus82** [comment]
Aside from the fact that the mobile media manager is still really a UX nightmare, the camera upload on android works fine for me too.
Maybe @BPBlueprint you have a size limit for uploads and the system doesn't give any warning.
In fact, there is no info or message that informs us of the successful upload, you understand that it was successful only because you see the image in the folder.

**Comment by HusiBT** [comment]
This was a good hint!
It was mod_security used by our Firewall/Imunify360

Thanks!
And sorry ... I thought it would be a bug

**Comment by alikon** [comment]
could you the issue then 😃
