### ISSUE TITLE
joomla 4 save & new button 

### ISSUE THREAD

**Issue by sofianhit** [joomla/joomla-cms#37958]
hi

please move the " save & new " button on all admin pages from inside the dropdown menu to uotside it.
that will add more easy create Much of contents . (see the attached image).

thanks

**Comment by sofianhit** [comment]
![screen shot 2022-06-01 at 15 57 20](https://issues.joomla.org/uploads/1/3b8f588f467f926474e071bc7c542d6d.png) image attachment <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37958">issues.joomla.org/tracker/joomla-cms/37958</a>.</sub>

**Comment by richard67** [comment]
The proposed change would be completely inconsistent, all things related to save in the pulldown except of this button.

**Comment by chmst** [comment]
Your screen is from J3. In J4 we have a new logic for action buttons and sorry, we will not change it for now.

**Comment by richard67** [comment]
> Your screen is from J3. In J4 we have a new logic for action buttons and sorry, we will not change it for now.

@chmst ??? The screenshot is definitely J4, except if someone has created a 3rd party template which makes J3 looks like J4.

**Comment by sofianhit** [comment]
my screen is from j4 . but i added the button by photoshop to show you my idea.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37958">issues.joomla.org/tracker/joomla-cms/37958</a>.</sub>

**Comment by sofianhit** [comment]
if you think about adding 20 Categories and 150 articles at least ... in this case the admin will click 340 times instead of 170 when creating the content . 

i dont know why developers did not think about this from the scratch .

thanks .

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37958">issues.joomla.org/tracker/joomla-cms/37958</a>.</sub>

**Comment by chmst** [comment]
> if you think about adding 20 Categories and 150 articles at least ... in this case the admin will click 340 times instead of 170 when creating the content .

Yes, I know and understand. Have the same problem at the moment. But there were reasons why the j3 style was not used in J4 - and developers will not change the logic. 

BUT - In the next version, Joomla wll have a plugin for shortcut Keys. Maybe this will be what you need :)

**Comment by sofianhit** [comment]
yesssssss ... it will be very Interesting and perfect way to play easy with contents .

you mean keyboard shortcut Keys !! right ? 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37958">issues.joomla.org/tracker/joomla-cms/37958</a>.</sub>

**Comment by chmst** [comment]
Still in test - it is not a promise - and would be helpful :)

**Comment by sofianhit** [comment]
good step .

thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37958">issues.joomla.org/tracker/joomla-cms/37958</a>.</sub>

**Comment by brianteeman** [comment]
Should be closed as we now have the shortcut keys in 4.2 and there is nothing more to do

**Comment by najatuk** [comment]
The reason that people would want this is that it would help a lot with workflow rather than having to use a dropdown when producing content that is not page by page, for me it would be better if the dropdown item was "save and close" and the default was "save and new".  I understand that now since version 4.2 there are now shortcut keys, that's great.  Unfortunately, until now, I haven't discovered what they are, and doing a google search of "shortcut key save and close joomla 4" among other searches reveals a shortcut plug-in by regular labs, the shortcut keys for JCE editor, and absolutely nothing about core shortcut keys for Joomla 4.  I am an end user, but you know, like so many people using Joomla, I have been using it since Mambo.  If I can't figure out what the shortcut keys are even after logging into github, I wonder how many new users are going to have the patience to figure out how to produce content quickly using Joomla.  Does anyone want to give me a hint on the shortcut for "Save and New?"

**Comment by alikon** [comment]
please see https://github.com/joomla/joomla-cms/pull/38290
