### ISSUE TITLE
403 You are not permitted to use that link to directly access that page - upon edit article

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#38010]
### Steps to reproduce the issue
Use Chrome browser. 
Login frontend with super user account
On a blog layout view with several articles, click edit on an article, and cancel
Do the same on another article
And so on

### Expected result
No errors - you can edit the article

### Actual result
403 You are not permitted to use that link to directly access that page (#250).
This happens more or less randomly

### System information (as much as possible)
Joomla 4.1.4 
PHP 7.4.29

### Additional comments
I cannot seem to find a system in this error
I can also make it come in Firefox - but it seems to happen less often !??

**Comment by chmst** [comment]
Why did you link #250 ?

**Comment by brianteeman** [comment]
@chmst thats part of the 403 error message and not a ref to a gh issue

**Comment by rbuelund** [comment]
Yes that should not have been linked in my message. Think it happende automatically.

**Comment by rbuelund** [comment]
Actually i also every once in a while experince this on Joomla 3 sites when trying to edit an article from a list view ?? Is this an old known bug ?

**Comment by rbuelund** [comment]
Is there any input on this - I have users who are getting annoyed over this isssue - and I do not know what to tell them ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38010">issues.joomla.org/tracker/joomla-cms/38010</a>.</sub>

**Comment by chmst** [comment]
I could not find any open issue like yours and cannot replicate it.

Maybe there is something which destroys session data on your system? .htaccess? Any extensions for security? Maybe your hoster can support you here by checking error logs.?

**Comment by rbuelund** [comment]
I have only Admin tools installed on the site - have not changed the htaccess file for a long time, and I think the problem is quite new.

**Comment by rbuelund** [comment]
Nothing usefull in the error log - I can only see the 403 error in the access log.

**Comment by chmst** [comment]
Could you deactivate Admin Tools?

**Comment by sarahhayes103** [comment]
I have experienced the same issue with Joomla 4 on several different servers, when using the edit button on the menu item in the admin area. It appears to be caused by the modal code and an escaped single-quote, which triggers mod security.


This is what Mod Security has recorded
Request: GET /administrator/index.php?option=com_content&view=article&layout=modal&tmpl=component&c031c1a6095d274fd4db831353fc1c01=1&task=article.edit&id=%27%2022%20%27
Action Description: Access denied with code 403 (phase 2).
Justification: String match "'" at ARGS:id.

# DEFA-1785
SecRule REQUEST_METHOD "@rx ^GET$" "id:77140923,chain,phase:2,block,log,severity:2,t:none,t:normalizePath,msg:'IM360 WAF: Joomla Component Jreservation Blind SQLi Vulnerability||MVN:%{MATCHED_VAR_NAME}||T:APACHE||MV:%{MATCHED_VAR}||',tag:'service_i360custom',tag:'joomla_plugin'"
SecRule REQUEST_FILENAME "@endsWith /index.php" "chain,t:none,t:normalizePath"
SecRule ARGS:option "@streq com_content" "chain,t:none"
SecRule ARGS:view "@streq article" "chain,t:none"
SecRule ARGS:id "@contains '" "t:none"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38010">issues.joomla.org/tracker/joomla-cms/38010</a>.</sub>

**Comment by RustyR** [comment]
I'm having the same error trying to use the edit link to (some) users in "Users" -> "Manage". Even not able to edit my own superuser account via this path. Strangly when using "User menu" -> "Edit Account" I will be able to edit the superuser account.

Someone knows what to do about it?

**Comment by joomdonation** [comment]
@RustyR Usually, it happens when :

- Someone else tried to edit the user account before. But they left the edit screen without saving change or without click on Cancel/Close button. In this case, the record remains checked out and you will have to check in it first before editing
- Or you use wrong link to edit the account. The right link is in this format **index.php?option=com_users&task=user.edit&id=415** (it does several technical things here) before redirect you to edit screen with this kind of URL **index.php?option=com_users&view=user&layout=edit&id=415** . So if you use wrong link to edit like this **index.php?option=com_users&view=user&layout=edit&id=415**, Joomla knows that you do not go with the right route and it will display that error.

That are the two possible cases (beside session timeout) I can think about this error,

**Comment by RustyR** [comment]
@joomdonation: 

- I'm the only one who did edit the user account(s) and after a global checkin still not able to use the edit link.
- The link is in this format: **index.php?option=com_users&task=user.edit&id=415**

**Comment by joomdonation** [comment]
@RustyR From technical point of view, it seems the code which stores/retrieves data to/from session is not working properly on your site for some reasons. Without check it directly on your site to see the error, it's hard to say why it is not working

Since it relates to session, you might want to go to System -> Global configuration, look at System tab, change **Session Handler** to use a different option (compare to the current one) to see if it address the issue. If not, I guess you will have a developer to check it directly on your site to figure out what's wrong and get it sorted

Here we can only check and fix the issue if there is a reliable way tore-procedure it on a fresh Joomla installation.

**Comment by RustyR** [comment]
@joomdonation Thanks very much for taking the time to look into this matter. After letting it go for 24 hours the problems are gone. I think it was cache related (if that's possible with handling sessions). Thanks again and have a nice day!!

**Comment by joomdonation** [comment]
@RustyR Strange but happy to here that it is gone :). Thanks for the update !

**Comment by Hackwar** [comment]
@rbuelund are you still encountering these issues? Or did you find a solution in the meantime?

**Comment by rbuelund** [comment]
I have not encountered the problem for a while now - so maybe it has vanished :-) ?

**Comment by Quy** [comment]
Closing for now. Thanks for reporting back.
