### ISSUE TITLE
elementos creados en los menu se abren con .html en lugar de ...&view=article&id=1

### ISSUE THREAD

**Issue by danielalejandroperezb** [joomla/joomla-cms#38120]
### Steps to reproduce the issue

abrir gestion de menu en Joomla 4.1.5
ingresar a los elementos del menu
crear nuevo elemento
ingresar titulo de elemento
en Tipo de elemento del menú seleccionar Mostrar un solo articulo
seleccionar articulo
guardar y cerrar
### Actual result
![screen shot 2022-06-22 at 08 59 15](https://issues.joomla.org/uploads/1/ef285d623a58c1c14b56d054d32a537f.jpg)
![screen shot 2022-06-22 at 09 01 18](https://issues.joomla.org/uploads/1/ad9cd4e2454299abd90f058ce6106283.jpg)

### Additional comments

![screen shot 2022-06-22 at 09 01 52](https://issues.joomla.org/uploads/1/bb72ded1ac26a887d0c641316abd482f.jpg)

**Comment by ReLater** [comment]
Please post your SEO settings in Global configuration (Configuración global):

![grafik](https://user-images.githubusercontent.com/20780646/175080508-39f08034-865b-48b0-981e-c9611b8d5ff4.png)

**Comment by chmst** [comment]
Please write english, if possible. 

As @ReLater alread wrote, the problem is caused by your system settings. First set all SEO Settings "off", rename your .htaccess to htacces.txt (be sure to remove the dot before htacess. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38120">issues.joomla.org/tracker/joomla-cms/38120</a>.</sub>

**Comment by Quy** [comment]
Closing due to no response with requested info.
