### ISSUE TITLE
[4.1] Wrong menu list order in the administration menu.

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#38143]
### Steps to reproduce the issue
Create several menus in a random order and having as first letter a random alphabetical order. Check the menus order in the left administration menu.

### Expected result
It is expected to see the menus ordered in a logical order. **The most common useful way for everybody, is to order them alphabetically.**

### Actual result
The problem is that they are ordered by ID (descending) but this way puts the menus like in random order and this is not easy for finding the one you want easily.

### System information (as much as possible)
Joomla 4.1.5

### Additional comments
Please check the following image. 
The example contains some menus in Greek text.
Notice that in the right side the menus are ordered alphabetically, so all the menus called "Βασικό" are together, but in the administration menu the menus are ordered by ID, so the menus called "Βασικό" are separated and in general the menus are not ordered alphabetically.
https://demo.impression-estudio.gr/_issue-tracker/issue-on-administration-menu-list-order.png

**Comment by brianteeman** [comment]
Known issue - this has been reported before

**Comment by pritam825** [comment]
is the issue solved or not? @brianteeman

**Comment by Quy** [comment]
> Known issue - this has been reported before

#30970

**Comment by richard67** [comment]
> The most common useful way for everybody, is to order them alphabetically.

How can you know that? Have you done a poll or a research?

> The problem is that they are ordered by ID (descending) but this way puts the menus like in random order.

It’s not a random order. ID descending results in those which I have created as last are being at the top and those I have created long time ago at the bottom. For me that’s very handy because often I forget something when creating a menu and so need to edit it again, but then when all is ok after a few edits I will not touch it anymore.

Changing ordering in the backend list views is one or max. 2 clicks on a column header. Not really a big thing.

So for me this issue here is not really an issue.

**Comment by HLeithner** [comment]
Yes I have the same problem, sorting by I'd is not useful. But alphabetical also doesn't fit my needs. I need ordering by the ordering column.

**Comment by brianteeman** [comment]
> Changing ordering in the backend list views is one or max. 2 clicks on a column header. Not really a big thing.

That is NOT what is being talked about here. @impressionestudio is referring to the order of the menus (not items) in the sidebar

![image](https://user-images.githubusercontent.com/1296369/175806355-9753eef9-201f-4041-a813-5338ddf1023e.png)


If I wanted to change that to a display that for example grouped all the en-gb menus together then it is not possible.

The screenshot above is from the sample data on a multilingual site and there is no means for me to change that display order so that it looks like this

![image](https://user-images.githubusercontent.com/1296369/175806468-b3d0f2f6-2d1a-4e43-af16-ca17695dfd5e.png)


As @HLeithner says. any predefined order will never satisfy anyone. There should be the ability to order the menus

**Comment by richard67** [comment]
> Check the menus order in the left administration menu.

Ouch ... I missed that when quickly reading the description. Thanks @brianteeman for clarifying.

**Comment by impressionestudio** [comment]
I suggested the alphabetical order because it can be done automatically and it is easy for the eye to find the menu it searches for.
Of course, a custom order is also very useful but this needs an extra knowledge on how it can be done from the admins and maybe this makes Joomla to be hard if an admin does not know this capability.
Anyway, I like both cases, alphabetical or custom order.

**Comment by brianteeman** [comment]
It needs an ordering column such as this. Alphabetical is no better than by id. It satisfies your use case but not everyones

![image](https://user-images.githubusercontent.com/1296369/175807199-33dcf463-61f8-4dbb-b603-1b39e701029d.png)

**Comment by HLeithner** [comment]
Changing the ordering to "manual ordering" (without other options) would be easy to implement (didn't checked the menu code yet) and allows you to order the menu alphabetical too. Also it doesn't add another option how the menu should be sorted. And it preserves the current behavior.

Only thing I can say for the moment is I don't have the time to implement this feature now.

**Comment by brianteeman** [comment]
I made a start #38149

**Comment by HLeithner** [comment]
Closing as we have a pr

**Comment by richard67** [comment]
Hmm, the PR is still draft/work in progress.
