### ISSUE TITLE
0 WebAssetManager is locked, you came late

### ISSUE THREAD

**Issue by robertajambrek** [joomla/joomla-cms#38308]
I wanted to work in my website and this message pops up: "0 WebAssetManager is locked, you came late".
Also, there is a quix update avalible from today, but i cant update it, i get this message: "Failed to extract file: index.php_option_com_digicom_task_responses_source_authapi_release_file_pid_117_rid_821".
I was able to work normally yesterday.

**Comment by richard67** [comment]
> I was able to work normally yesterday.

Then something has changed since yesterday, either a 3rd party extension has been updated or the CMS, or something else has been changed. If you can't provide more information on that, I don't think we can help you much.

And you should know that it is impossible to help you if you do not specify any information like the Joomla version you use, the PHP version and so on.

The "0 WebAssetManager is locked, you came late" might come from a 3rd party extension which tries to load resources (js or css) after the page has been rendered (simplified explanation), and the issue with the quix update is also a 3rd party extension thing.

Please note that the issues here are for reporting issues with the CMS core.

You should try to get support in the support forum https://forum.joomla.org/ .

Closing as not a core issue.

Feel free to re-open if you can provide information which points to a possible bug of the CMS core.
