### ISSUE TITLE
[4.2 RC1] Maintenance - Clear Cache

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38314]
### Steps to reproduce the issue
Update Joomla 4.2 RC1 from Joomla 4.1.5

### Expected result
On the Clear Cache page, a file named **_media_version** appears. And I can't clear it. I don't know what this is either. Also, delete buttons work without selection. In other words (The selection feature doesn't work either, by the way), it seems to do the cleaning process without selecting it, but it doesn't.

Please watch the video:

https://user-images.githubusercontent.com/423588/180027311-4f0b50f0-04f5-4a6b-975a-e090c49aeaf1.mp4

### System information (as much as possible)

Joomla 4.2 RC1
PHP Version	8.1.8
Database Version	5.7.38-cll-lve
Theme: Cassiopeia - Default

**Comment by brianteeman** [comment]
> On the Clear Cache page, a file named _media_version appears. And I can't clear it.

It is regenerated immediately. If you look at the file you will see its updated everytime

> I don't know what this is either.

See https://github.com/joomla/joomla-cms/pull/37457

> Also, delete buttons work without selection

Delete ALL does work as thats intended behaviour - that button makes no sense otherwise

Delete button is disabled until a selection is made.

### Summary
You are assuming that when you clear cache then there will be nothing in the cache. This is an incorrect assumption. As the cache contains folders/files generated by joomla it is of course possible that there will always be files in the cache as they are created as soon as the cache is cleared.

Everything is working as intended

**Comment by HLeithner** [comment]
Explained by brian, thanks

**Comment by ghost** [comment]
Ok then, thank you.
