### ISSUE TITLE
[4.1.5] UX: Multilingual Associations: 'Status' Icons different to other components

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38419]
### What needs to be fixed
In Multilingual Associations the icons of 'Status' are different to other components:
| Multilingual Associations | Example 'Contacts' |
| --- | --- |
| <img width="322" alt="ma-status" src="https://user-images.githubusercontent.com/89642616/183396654-1d6fda82-8ee4-4c02-8d70-1850a4fc0220.png"> | <img width="390" alt="default-status" src="https://user-images.githubusercontent.com/89642616/183396630-92f1cfcf-122a-4403-93f3-a2dc6eed004a.png"> |

### Why this should be fixed
Better UX if using the same icons.

### How would you fix it
?

### Side Effects expected
?

**Comment by richard67** [comment]
The difference is: In the other components, the status can be changed by clicking the icon, and there is a tool tip telling that, so it is not just a display but a toggle.

In the multilingual status view, the icon cannot be clicked, it is just a status display.

I hope you agree with me that for this reason they definitely should look different.

And if you check the multilingual status module where the status is also shown with check marks but cannot be toggled, they are also shown without a circle, so that is consistent, too.

Closing as expected behaviour.

**Comment by ghost** [comment]
> I hope you agree with me that for this reason they definitely should look different.

I do, thanks @richard67, haven't thougt about 'toggled'.
