### ISSUE TITLE
After component options are modified the method getParams in ComponentHelper returns old values

### ISSUE THREAD

**Issue by counterpoint** [joomla/joomla-cms#38420]
### Steps to reproduce the issue

Create a plugin to handle onExtensionBeforeSave and onExtensionAfterSave. Put in diagnostics based on Joomla\CMS\Component\ComponentHelper::getParams() to show or save one of the option values. Change the option value and save. Note that both of the plugin methods show the old value, even though the new value is in the database. 
### Expected result

The new value for the option should appear in the result returned by Joomla\CMS\Component\ComponentHelper::getParams()

### Actual result

The old value is returned by Joomla\CMS\Component\ComponentHelper::getParams()

### System information (as much as possible)

Logical problem, will occur in any system.

### Additional comments

This very much reduces the usefulness of the plugin hooks since there is no way to detect what has happened in the onExtensionAfterSave code.

**Comment by khobraariyadh** [comment]
تأسست ايكيا على يد انجفار كامبراد عام 1943، وظهرت على أرض الواقع ككتالوج طلب بالبريد في مدينة ألمهولت المشجرة بالسويد. وهي اليوم علامة تجارية عالمية للأثاث المنزلي توفر الأسعار المناسبة والتصميم والراحة للناس في جميع أنحاء العالم. ربما قطعنا شوطًا طويلاً منذ بداياتنا المتواضعة، لكن رؤيتنا تظل كما هي: خلق حياة يومية أفضل للكثير من الناس. استكشف قصة ايكيا هنا، لمعرفة المزيد عن تراثنا، وما الذي يدفعنا اليوم والطرق التي نسعى بها للتأثير بشكل إيجابي على الناس والكوكب.
في عام 1995 استخدمت شركة ايكيا مصطلح التصميم الديمقراطي للمرة الأولى وكان ذلك في معرض ميلانو للأثاث، والتصميم الديمقراطي هو أداة تستخدمها ايكيا عند تطوير منتجاتها وتقيمها، لها خمسة أبعاد وهي الوظيفة، والشكل، والجودة، والاستدامة، والسعر المنخفض.
وخلال التسعينيات ازداد اهتمام إينغفار بالبيئة، وموّل مشروع "زرع بذرة" في مدينة بورنيو الماليزية بعد أن دمر حريق مساحات كبيرة من غاباتها، وبهذا المشروع أُعيدَت زراعة أكثر من 12500 هكتار من الغابات المطيرة أي حوالي 125 ألف متر مربع.

[تركيب اثاث ايكيا]( https://furniture-riyadh.com/)

عندما يكون مكيف الهواء قيد التشغيل، فمن الطبيعي أنّ يتسرب الماء من أنابيب التصريف في الأيام الحارة، أو في الطقس البارد نتيجة تبريد الوحدة الداخلية وتجمد المياه فيها، وتسربها عند ذوبانها، ويعد هذا الأمر طبيعياً في حال كان مكيف الهواء قيد التشغيل، إلا أنّه يوجد أسباب أخرى تؤدي إلى تسريب المياه من مكيف الهواء إلى الخارج كما يلي: اتساخ فلتر الهواء أو انسداده. انسداد في أنبوب التصريف. انخفاض مستوى التبريد في الوحدة الداخلية للمكيف. وجود كسر في وعاء التكثيف. وجود خلل في تثبيت الأنابيب الداخلية. يمكن حل مشكلة تسرب المياه إلى الخارج بتحديد وتشخيص المشكلة أولًا، ثم إيقاف مكيف الهواء عن التشغيل، وفصل مصادر الطاقة عنه، وفي حال كان الأمر صعباً أو لم يكن بمقدور الشخص التعامل مع المشكلة، يُفضل الاتصال بفني الصيانة لإجراء التشخيص وحل مشكلة التسريب.

[شركة تركيب مكيفات بالرياض]( https://furniture-riyadh.com/air-conditioning-installation-riyadh/)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38420">issues.joomla.org/tracker/joomla-cms/38420</a>.</sub>

**Comment by Hackwar** [comment]
Hello @counterpoint, sorry that this took so long. I understand what you are trying to do, however I disagree that this is a bug and we wont be fixing this. Yes, the data in ComponentHelper::getParams() is not updated during the request when the component parameters are updated in the database. However it is expected that this isn't necessary. If your extension updates the component params and needs to access them afterwards, the expectation would be that your extension also updates the value in ComponentHelper::getParams(). You can do so by simply updating the value(s) in the registry object returned by getParams(). You can also compare the old value from ComponentHelper::getParams() with what is saved in the database in the events you mentioned above.

So to summarise: If you need to edit the configuration and have the result of ComponentHelper::getParams() updated in the same request, then you have to take care of that yourself. We are not going to update this in the system. Because of this, I'm closing this issue.
