### ISSUE TITLE
4.0.0 to 4.1.5 upgrade path now also broken - Call to undefined method UpdateModel::isTemplateActive()

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#38486]
### Steps to reproduce the issue

So, the Joomla project has chosen to stop people upgrading from Joomla 4.0.0 to 4.2.0 in one step - because of https://github.com/joomla/joomla-cms/issues/38474

Instead users of Joomla 4.0.0 are forced first to 4.1.5 by https://github.com/joomla/update.joomla.org/pull/261

When a user attempts a 4.0.0 to 4.1.5 upgrade they end in an error message:

`Call to undefined method Joomla\Component\Joomlaupdate\Administrator\Model\UpdateModel::isTemplateActive()`

### Expected result

Joomla should be able to upgrade through the PUBLISHED and OFFERED upgrade path with a smooth upgrade experience and no error messages 

### Actual result

<img width="1594" alt="Screen Shot 2022-08-16 at 23 21 47" src="https://user-images.githubusercontent.com/400092/184995595-02db59b3-1b97-4045-a467-57fe854e196a.png">

The solution - again - is to delete administrator/cache/autoload_psr4.php

Face meet desk. 

This is because - like I said - ALL versions before 4.0.5 had no concept of deleting the administrator/cache/autoload_psr4.php and so would break on any upgrade. 

THE CORRECT way of "fixing" this is to fix it in com_joomlaupdate and RELEASE A NEW VERSION of com_joomlaupdate which needs to be updated before upgrading Joomla.

**Comment by PhilETaylor** [comment]
@roland-d @zero-24

**Comment by zero-24** [comment]
Thanks we will look into that. But I'm suprised that it should be broken just now and that we have not got reports of similiar issues before.

**Comment by zero-24** [comment]
Could you post to us the specifications of the maschine that you are running your tests with?

**Comment by PhilETaylor** [comment]
Im not surprised. No one uses Joomla 4. 

Its a docker container. Its rock solid and runs perfectly. This is not an infrastructure issue - this is a Joomla Code bug where the code to delete the autoload_psr4.php was only added in Joomla 4.0.5-rc1 and so upgrading from any version below that (mine is 4.0.0) to any future version will be broken.

 Im surprised you cannot see that instantly.

**Comment by PhilETaylor** [comment]
Let me spell it out to you... 

**THE CORRECT way of "fixing" this is to fix it in com_joomlaupdate and RELEASE A NEW VERSION of com_joomlaupdate which needs to be updated before upgrading Joomla.**

You need to add this code https://github.com/joomla/joomla-cms/pull/37990/files to com_joomlaupdate and release a new version of com_joomlaupdate and force users to upgrade that component BEFORE upgrading Joomla.

In the mean time, we have another Joomla release screwed up because no one tested and the quality was shocking. Another release that hurts Joomla's reputation ...

**Comment by zero-24** [comment]
Yes its on the list thanks.

**Comment by joomdonation** [comment]
The file administrator/components/com_joomlaupdate/finalisation.php is called at the end of extraction process, so the change from https://github.com/joomla/joomla-cms/pull/37990 should be available when update from any Joomla version. So in theory, we do not need to release new version of com_joomlaupdate.

I also just tried to update from 4.1.0 to 4.2.0 from my local computer and it worked well. Maybe it is not working is because the old code is still used somehow (cache?) ?

**Comment by PhilETaylor** [comment]
Now test 4.0.0 to 4.2.0 as no you will see it’s not well. Or 4.0.0 to 4.1.5 which also dies.

**Comment by zero-24** [comment]
yes that are our results too. there are many sits where its working fine but some where it does not. interestingly it can be regular reproduced when going from 4.0.0 to 4.2 but not when going from 4.0.0 to 4.1.5 while it still looks like phil is getting it there too. we are still investigation se we can understand whats happening. we have also got reports of 4.1.5 to 4.2.0 upgrades fail but again not all the time just sometimes.

**Comment by nikosdion** [comment]
@zero-24 I have gotten various weird issues on three out of six sites I upgraded from 4.1.5 to 4.2.0 because the autoload_psr4.php file is not being removed. My theory is that there was traffic on the site which prevented the file from being removed.

I will submit a PR for JoomlaUpdate's extract.php to do that so you could publish a new JoomlaUpdate version to address this.

**Comment by PhilETaylor** [comment]
>  My theory is that there was traffic on the site which prevented the file from being removed.

Doesn't explain why this can be replicated in isolation, in a docker container, on a localhost.

**Comment by nikosdion** [comment]
@PhilETaylor The finalisation.php DOES have code to remove that file. That said, I think it is the wrong place to have that code. This code should be running before we include finalisation.php. Give me 5' for the PR and you can tell me if it works for you?

**Comment by joomdonation** [comment]
It's right that Joomla older than 4.0.4 use the file finalisation.php which does not have code to re-generate namespace map and that's the root reason causing the error

If you use Joomla 4.0.4 or newer, upgrade should work well.

**Comment by PhilETaylor** [comment]
> If you use Joomla 4.0.4 or newer, upgrade should work well.

LMAO - yeah, tell that to users that are presented with a one click upgrade from 4.0.0 to 4.2.0... or 4.0.0 to 4.1.5 (as Published) 

If Joomla publishes and upgrade path, then it should work seamlessly. 

Telling users they can only upgrade correctly if they use 4.0.4 and above is not the solution. 

Joomla 4.0.0 with an updated com_joomlaupdate is the solution.

**Comment by nikosdion** [comment]
@joomdonation @PhilETaylor Can you pease test https://github.com/joomla/joomla-cms/pull/38491 since you clearly both have environments demonstrably affected by this issue? My PR is more of an educated guess based on my experience with the core code and the way restoring backups might break a site. Thank you.

**Comment by PhilETaylor** [comment]
> That said, I think it is the wrong place to have that code. 

It also needs to be (needs to stay as well) after finalizeUpdate (where it already is) because admin.php deletes classes/files

**Comment by PhilETaylor** [comment]
> Can you pease test https://github.com/joomla/joomla-cms/pull/38491

but of course extract.php doesn't exist on 4.0.0 ... so.. like I said a whole new com_joomlaupdate would need releasing.

**Comment by nikosdion** [comment]
> but of course extract.php doesn't exist on 4.0.0 ... so.. like I said a whole new com_joomlaupdate would need releasing.

I **EXPLICITLY** said, in no uncertainty terms:

> I will submit a PR for JoomlaUpdate's extract.php to do that so you could publish a new JoomlaUpdate version to address this.

You are being deliberately obtuse and disruptive a.k.a. toxic. Stop it.

**Comment by PhilETaylor** [comment]
You know what - Fuck you. I have better things to do than be here.

**Comment by nikosdion** [comment]
Thank you for your valuable feedback and your personal attacks.

**Comment by PhilETaylor** [comment]
Fuck you

**Comment by wilsonge** [comment]
OK I've given @PhilETaylor a ban for this. This behaviour is unacceptable

**Comment by nikosdion** [comment]
I am truly sorry it came to this 😞 Hopefully Phil can find it in him to approach this project, its maintainers and its contributors with a less aggressive attitude. I appreciate his past work in the core — I use a lot of his contributions in my own extensions and all of my sites — and the fact that he does convey issues reported to him by his clients. I don't disagree with what he does, just how he did it.

When I said this:

> Thank you for your valuable feedback and your personal attacks.

I really do thank him for valuable feedback. I was being snarky about the personal attacks. In retrospect, this sentence works in Greek — especially if you know me personally — but reads very differently in English and the British cultural context. I apologise for writing something which came across far more snarky and annoyed than I intended.

We are all here because we care about Joomla. We are all passionate about this project and want it to succeed. Sometimes tensions can run high. I am the first one to admit that my behaviour is far from perfect. At least I have figured out why it happens (undiagnosed ADHD for the first 40 years of my life; now it's being treated), I am actively trying to improve upon it and when I inevitably say something hurtful [I try to apologise and de-escalate](https://github.com/joomla/joomla-cms/issues/38485#issuecomment-1217586810) to the best of my ability. That's all I ask of other people; nothing more than what I do myself.

Phil, I am sorry for the way I came across.
