### ISSUE TITLE
Performance issue with 4.21: 9 seconds response time backend and frontend

### ISSUE THREAD

**Issue by WeibelMarc** [joomla/joomla-cms#38665]
### Steps to reproduce the issue
Apply the 4.21 Joomla update to a 4.20 website.
Compare the same pages between a 4.20 and a 4.21 instances.
For the same page (back-end or front-end, 4.21 takes 7 seconds more to display a page : SpeedIndex 9 seconds instead of 2 seconds.

### Expected result
Same performance with 4.21 as with 4.20

### Actual result
7 seconds more to display a page.

### System information (as much as possible)
PHP 7.4 (switch t PHP 8.1 is not possible as long as there are 3.9 websites on the same server). 
Same behaviour with or without Page Caching.
![joomla-421-performance-issue-12-seconds](https://user-images.githubusercontent.com/111305298/187928852-d2127bad-ca95-4a75-9130-4e6a39eae46b.jpg)
The attached screenshot is from a development website not fully optimized.

### Additional comments
The server administator has checked the logs and there is no server issue.
I believe it, because another website (Joomla 3.9) is runing on the same server with fantastic performances (Lighthouse SpeedIndex <2 seconds for all pages).

**Comment by richard67** [comment]
Please check pull request #38664 and the correspoinding issue #38662 . Does the problem disappear if you disable the Webauthn system plugin? If yes, it is the same issue. In this case please close your issue because ita duplicate report. And if you can, test the pull request.

In general it would be helpful if people would have a look if an issue has already been reported before open the 99th duplicate issue for it.

**Comment by richard67** [comment]
@WeibelMarc Sorry, was not my intention to appear rude. Thanks for checking.

**Comment by WeibelMarc** [comment]
You are welcome. I just wanted to show my goodwill. Best regards.
