### ISSUE TITLE
Jinput  not see not Latin value 

### ISSUE THREAD

**Issue by akbet** [joomla/joomla-cms#38836]
Hi

### Steps to reproduce the issue

in router I have: from user input:

$vars['letindex'] = $segments[2];

if $segments[2] === "w" or "1" or "R" ..

In controller 
echo JFactory::getApplication()->input->get('letindex', ""); // return "w" or "1" or "R" .. all work good

BUT if $segments[2] === "п" or "Д" or "Г" - some not latin letter

In controller 
echo JFactory::getApplication()->input->get('letindex', ""); // return empty
also
echo JFactory::getApplication()->input->get('letindex', "ппп"); // return empty

I use last joomla 4.2.2. PHP 8.1.9

Regards
Andrew

**Comment by akbet** [comment]
If I use filter RAW - all work good

Regards
Andrew<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38836">issues.joomla.org/tracker/joomla-cms/38836</a>.</sub>

**Comment by richard67** [comment]
@akbet URL can contain only ASCII characters, see the specification here: http://www.faqs.org/rfcs/rfc1738.html . Other characters need to be percent encoded. Where does the input "letindex" come from? Is that a text field with URL filter? In this case removing non ASDCII characters is the expected behaviour, I would say.

**Comment by Fedik** [comment]
Use `$app->input->getString('letindex')` or `$app->input->get('letindex', 'string')`.
Default filter is `cmd` (command)
