### ISSUE TITLE
[BUG][J4.2] Keyboard Shortcuts not working when editing Article

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#38870]
### Steps to reproduce the issue
Edit article and hit J and A to save the article. If you are inside the editor, J and A is written to editor instead to run save event.

### Expected result
Save article regardless of where the cursor is located

### Actual result
It is not possible to save article when the cursor is over the editor, which is mostly if you're writing an article

### System information (as much as possible)
Joomla 4.2

**Comment by brianteeman** [comment]
I would argue that this is the expected behaviour. If the shortcut keys work when inside the editor how would you write your own name. 

The same is treue with almost every shortcut system. For example here in github if I press ? outside of the editor then I get a popup of the available shortcuts. But obviously inside the editor I get the ?

**Comment by PhocaCz** [comment]
Maybe the problem is in the selected shortcuts and pressing them one after another. Usually, if possible, the Control key is used in conjunction with another key. But I'm not an expert on shortcuts or accessibility, so I can't judge the choice of keyboard shortcuts.

Personally, I would suggest turning off the plugin by default and if someone turns it on, he/she will understand that Joomla shortcuts replace browser shortcuts and I would choose established shortcuts like:

CTRL+S - save
CTRL+N - new,

etc.

Shortcuts are currently unusable in some situations, e.g. if you're writing an article and want to save it, etc. (It is my personal opinion and may be based on ignorance of some specifications, so please do not take it as a criticism of the existing solution).

**Comment by pinochico** [comment]
>>> I would argue that this is the expected behaviour.

Ha,
Obviously we all expect something different.
And your expectations seem to support and even defend this bullshit?

Do you think copying nonsense from github will make you world class?

Good thing programmers with "expected behavior" don't work at apple, otherwise I'd have been going crazy pressing A+ for 30 years of something expected. 

Keyboard shortcuts should work in combination with function key(s).
And the best solution is to map the keyboard shortcuts in the system, not to specify it based on how someone sleeps or advocates that it is "expected behavior".

Vanity of vanities

Translated with www.DeepL.com/Translator (free version)

**Comment by PhocaCz** [comment]
To avoid any escalation, I'm closing this thread.

Let's not label this behavior as a bug.

If anyone has similar problems as me, then I would recommend installing this plugin from Regular Labs ( https://extensions.joomla.org/extension/keyboard-shortcuts/ ). Here the shortcuts are assigned to the Control button and you can save the article even if you have the cursor in the editor, etc.

Jan
