### ISSUE TITLE
Combobox dropdown does not display above radio group that follows

### ISSUE THREAD

**Issue by ron4mac** [joomla/joomla-cms#38897]
### What needs to be fixed
A combobox dropdown should have sufficient z-index to display above ensuing form elements in the ATUM administrator template

### Why this should be fixed
It is visually distracting to the UI

### How would you fix it
Increase the z-index for `.awesomplete > ul` to 2
media/templates/administrator/atum/css/vendor/awesomplete/

### Side Effects expected
None

**Comment by Hackwar** [comment]
Hello @ron4mac, thank you for reporting this. The code you are reporting is actually coming from awesomplete itself and we are already overwriting this in our templates with a value of 1000. If you want this to be changed, please open a new ticket in the upstream project. Since this is not in our power to manage, I'm closing this issue here.
