### ISSUE TITLE
SEARCH Search term as a part of search result word

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38946]
### Is your feature request related to a problem? Please describe.

When searching, only search results are returned that contain the exact word entered and not also those that contain the word as part of a word. A user who does not expect this will therefore think that there is no content for his search term. Example: the search for " Ernährung" (nutrition) leads nowhere if the text of the article in question says "Ernährungsdiktatur" (nutrition dictatorship). It would be nice if the search could also find word components.

**Comment by richard67** [comment]
@hytsch Which version of Joomla do you use? As far as I could see, Joomla 4.2.0 came with that feature, see #36752 . Does that fulfill your requirement? If you are using Joomla 4.2.x, could you check in the configuration of Smart Search the value of the "Word Match" parameter?

If the pull request which I have mentioned implemented what you request so it is in 4.2.x, please close this issue, otherwise report back what's missing. Thanks in advance.
