### ISSUE TITLE
Files are not copied on update

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#38956]
OFF TOPIC

**Comment by Skullbock** [comment]
Hi, we at ZOOlanders have experienced this issue in the last 6+ months with our Essentials for YOOtheme Pro extension repeatedly (10+ tickets from customers), and each time our suggested fix was to manually reinstall the package, which always resulted in the issue itself being resolved.

We originally thought it may have being caused by the client's server not correctly extracting all the files, or timing out, or similar issues, but we had reports from clients who use both Joomla and Wordpress version of our extension on the same server, and the issue was happening only in Joomla.

We then had a report and following conversation with @SniperSister who experienced the issue himself with our extension and his own. He's now notified us that the legendary @nikosdion finally found the root cause of the issue in this ticket.
We're going to try and reproduce this situation too and post here the results to confirm that's actually the root cause.

Thanks again to both @nikosdion and @SniperSister for taking the time to debug this so thoroughly

**Comment by nikosdion** [comment]
Before this trace I thought that the problem happens at archive extraction, namely that not all files are extracted. It looks like I was close, yet so far away! For quite some time (FOF 3.6 and later) I had a post-installation section which would copy the extracted files where they belonged and it worked. This had me thinking that, well, this is neither an extraction problem nor a file copy problem, so what exactly is it?

Deciding to add type hints in my script was merely code polishing. I didn't expect to ever see Joomla using a different installer adapter. As soon as I made this change in Akeeba Backup 9.3.0 I started getting tickets about a different kind of installer adapter being used. I tried getting access to the affected sites but by the point I did they were already updated manually and the issue could not be reproduced.

It was pure luck that a client had this issue, had enabled a way to get debug traces and decided to send me the trace.

This had me trace back the code, trying to figure out how this can happen. I am still not 100% sure that my explanation is correct, but this is the only way I can see the code in 4.2.3 returning the wrong manifest. Feedback is more than welcome. I've been chasing this white whale of a bug for ten years.

**Comment by rdeutz** [comment]
Valid issue

**Comment by nikosdion** [comment]
Open your own issue. I don't want to contribute anymore. Can you please respect that?

**Comment by nikosdion** [comment]
Besides, your organisation's official which I reported for a CoC violation —and got laughed to my face in return— is adamant that this issue does not exist. He's calling me a f…k-up (sorry for the language, quoting him verbatim), a coward, and has openly asked for my banning from the project. You can't simultaneously _as an organisation_ let these comments stand on the original issue I opened with this problem **AND** tell me that this is a valid issue without coming across as the worst kind of hypocrites.

Enough with this.
