### ISSUE TITLE
Note Form Field sets div incorrectly in Joomla 3.10.10

### ISSUE THREAD

**Issue by jjbongio** [joomla/joomla-cms#39083]
Haven't converted to J4 yet because of an extension dependency, but wanted to report this in case it was still an issue. 

getLabel in note.php field last line is
`return '</div><div ' . $class . '>' . implode('', $html);`
should be 
`return '<div ' . $class . '>' . implode('', $html) . '</div>';`

### Steps to reproduce the issue
Use the note type in any form in an admin extension. The incorrect `</div>` will close
the main container.

**Comment by richard67** [comment]
@jjbongio If you check the [description of your issue on GitHub](https://github.com/joomla/joomla-cms/issues/39083) you will see that the markup is not visible, e.g. the `<div>`. Markup or code needs to be quoted with ` to be visible here. I could correct that for you, but I thought it's better if I let you know first. Let me know if you have some questions or if I shall change the description for you.

**Comment by richard67** [comment]
@jjbongio Done. If you edit the description you will see how I have done it.

**Comment by jjbongio** [comment]
Got it. Thanks muchly.

**Comment by ReLater** [comment]
I checked that issue yesterday (TBH, not too intensive) but couldn't find any unclosed `<div>` in the source code of checked pages. For example:

![grafik](https://user-images.githubusercontent.com/20780646/198693922-171cf4c1-3a14-496c-89d1-41d7fbc63e64.png)

But I gave up to find the code place where the `</div>` is added.

**Comment by ReLater** [comment]
The same with a `close="true"`. No invalid HTML.

![grafik](https://user-images.githubusercontent.com/20780646/198695342-ced0f558-3e34-46eb-91c3-ead64fc6b701.png)

**Comment by ReLater** [comment]
This issue seems to be Joomla 3. I have tested with Joomla 4. But in Joomla 4 it's the same PHP code and no invalid HTML:

`return '</div><div ' . $class . '>' . implode('', $html);`

**Comment by jjbongio** [comment]
I may not have explained it well. The generatedd HTML is perfectly valid, but it does the wrong thing. The `</div>` closes an outer div and the `<div>` starts a new div at the same level as the outer div. What it should do is return a div with the label code in it and close it.
If this isn't clear, I can code an example.

**Comment by ReLater** [comment]
I would say that's on purpose. Because in note fields the label is just a H4 headline here and not a real field label. The same for the description.

Yes, the empty divs are not nice in Joomla 3 but I think it would be bigger effort to put the label (= headline) into a div with `class="control-label"` than to leave it as it is.

As always: I don't have to decide that. But that's for sure not a security issue (or a bug). Joomla 3 is locked for other fixes than these.

Examples from Joomla 3:

![grafik](https://user-images.githubusercontent.com/20780646/198834182-38457535-1cc2-4d89-9575-7bffdc83dcac.png)

![grafik](https://user-images.githubusercontent.com/20780646/198834194-36af9616-4358-405b-bff3-02a86a84faa7.png)

![grafik](https://user-images.githubusercontent.com/20780646/198834203-4ffdcdc3-ce58-4ce8-9458-f4091db8c6f9.png)

**Comment by billyroberts11** [comment]
This issue is likely to be related to Joomla 3's fault[.](https://northell.design/)

**Comment by Fedik** [comment]
That on purpose as @ReLater already noted. This hacky way works for years, and unlikely will be changed for Joomla 3.10.
However would be nice if someone find a less hacky way to render this field in Joomla 4

**Comment by jjbongio** [comment]
I'm not sure I'm describing this correctly (I'm new to the forum, so be patient).
I have a field defined in a form as

<field
name="note1"
type="note"
label="Some Label"
/>

When I use this form in the backend, the returned label is 
`</div><h4>Some Label<div>`

which closes out the containing div.

**Comment by Fedik** [comment]
@jjbongio you described it correctly.
This `</div><h4>Some Label<div>` is on purpose.

Look the layout file[ joomla.form.renderfield](https://github.com/joomla/joomla-cms/blob/3.10-dev/layouts/joomla/form/renderfield.php), it render field label and input, like:
```php
<div class="control-group">
  <div class="control-label"><?php echo $label; ?></div>
  <div class="controls"><?php echo $input; ?></div>
</div>
```

Now, because we do not want that Note label be inside `<div class="control-label">`, we do `return '</div><div ' . $class . '>' . implode('', $html);` in the Note field label, and in result we get:
```php
<div class="control-group">
  <div class="control-label">
    </div><h4>Some Label<div>
  </div>
  <div class="controls"><?php echo $input; ?></div>
</div>
```

As you can see result markup is correct, even when `$field->label` return incorect one.

**Comment by chmst** [comment]
@jjbongio I have marked your code so that it is visible. I am wondering how you check the source code of your site? 

I have added your code in user config.xml and get this: 

![grafik](https://user-images.githubusercontent.com/1035262/199678838-decdbb0e-6bf3-4e17-81e8-165f554e911a.png)

If your structure is destroyed then the error could be somewhere on your site and produce a side effect here.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/199680924-21ad9eef-5bca-40bb-a588-017a8350ceb0.png)

**Comment by Fedik** [comment]
> I am wondering how you check the source code of your site?

The Inspector not a reliable source, it shows rendered result (by browser) not real markup (from server).
Because Browser may magicaly fix a broken markup, it will looks correct in the Inspector.

And it possible to get a broken markup with Note field. Check my previus comment for details.
When rendering on your own (I mean without use of `$form->renderField($field)`), example:
```html
<p><?php echo $field->label; ?></p>
```
It will produce:
```html
<p></div><h4>Some Label<div></p>
```


It does not happens in core forms, but easily in 3rd extensions in custom form.

**Comment by jjbongio** [comment]
@Fedik Yes, it is a custom form, and I am using $field->label

**Comment by jjbongio** [comment]
I was looping through $form->getFieldSet() as $field and echoing $field->label and then $field->input
When I changed it to echo $field->renderField (), it worked nicely without closing the parent div.

Thanks to all for your comments.

**Comment by Baliar93** [comment]
I have reviewed the issue mentioned in the link, and I would like to share my thoughts on it. It seems that the issue is related to [Joomla CMS](https://gloriumtech.com/ "") and is numbered 39083.

After going through the details provided, it appears that there is a bug or a problem with the CMS. In order to assist you better, I would appreciate it if you could provide more information about the specific error or behavior you are experiencing. It would be helpful to know the steps to reproduce the issue, any error messages encountered, and any relevant system configurations.

Additionally, if you have any ideas or suggestions on how to resolve this issue or work around it, please feel free to share them. Collaboration within the Joomla community can often lead to quicker and more effective solutions.

Looking forward to your response and further discussions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39083">issues.joomla.org/tracker/joomla-cms/39083</a>.</sub>
