### ISSUE TITLE
[4.2x] php formatting in article default.php

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#39136]
I've been going through a load of template changed files - mostly switching tabs to spaces, but noticed some formatting inconsistencies:

### What needs to be fixed
lines 93-94, 115-116 and 137-138 of components/com_content/tmpl/article/default.php all start like this:
 ```       <?php```
```        if ...```

and lines 96-97 are like this:
```    endif;```
```    ?>```
 
### Why this should be fixed
Other instances of this code - for example in blog.php or featured/default.php - are like this:
```    <?php if ...```

and for lines 96-97:
```   endif; ?>```
like all other instances in this file

### How would you fix it
Merge lines together

### Side Effects expected
None

**Comment by brianteeman** [comment]
its not just the lines you highlight that are inconsistent :(

**Comment by chmst** [comment]
There are countless small similiars dicrepancies in layout files, becaus there were many different contributors and the code was written over a long time. 
Maintainers discussed your issue and we decided to close it because we don't see this as bugs (they don't give wrong results or break the function).
