### ISSUE TITLE
[4.x] Plugin "Extension - Finder" is broken

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#39182]
### Steps to reproduce the issue

1. The plugin is searching for a `commonwords` file like in that folder`(/administrator)/language/xx-xx/xx-xx.com_finder.commonwords.txt`
https://github.com/joomla/joomla-cms/blob/9cbe6cb5b204705a2a66b7b774160d78eb783a01/plugins/extension/finder/finder.php#L139-L143
The core file (for lang en-GB) was renamed from `language/en-GB/en-GB.com_finder.commonwords.txt` to `language/en-GB/com_finder.commonwords.txt` in PR https://github.com/joomla/joomla-cms/pull/27130

2. A language pack consists of three parts `site`, `admin`, `api`. Even if the _site_ language contains the file (with correct file name), they will be deleted again if the _admin/api_ language is installed afterwards
https://github.com/joomla/joomla-cms/blob/9cbe6cb5b204705a2a66b7b774160d78eb783a01/plugins/extension/finder/finder.php#L57-L60

### Expected result

Plugin should work as expected (when _commonwords_ are needed)

### Actual result

  - clean installation
  - check database #___finder_terms_common
  - some values for "en" are present
  - install an **en** lang pack for example (en-US)
  - check database #___finder_terms_common
  - values are deleted
  - install any other lang pack
  - table is still empty

### System information (as much as possible)

J4.x

cc @Hackwar

**Comment by Hackwar** [comment]
I fixed the first part in #39188, but regarding the second complaint, I'm calling this by design. It is not as if the common words would make a big difference or something and I expect there to be just one such file in the different language files.

**Comment by richard67** [comment]
@Hackwar @heelc29 Would it be a solution for the 2nd part of the issue if we do the `removeCommonWords` and `addCommonWords` only when the client of the extension is equal to 'site'?

Currently when installing a complete language pack we can rely on the site client being installed as last because it comes as last in the alphabetical order of the clients (administrator, api, site). But there is still the possibility that people install languages separately and not as package. And if in future someone invents a new client named 'whatever' we will have the problem again, too.

**Comment by heelc29** [comment]
@richard67 https://github.com/joomla/joomla-cms/pull/39188#issuecomment-1312738595

> The order of installation will depend on the package manifest.

**Comment by heelc29** [comment]
See https://github.com/joomla/joomla-cms/pull/39188#issuecomment-1317624502
