### ISSUE TITLE
Created_by field looks disabled but is writeable

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#39232]
### Steps to reproduce the issue
Open an article, go to tab publishing. 
The created_by input field looks disabled, but is not 

![grafik](https://user-images.githubusercontent.com/1035262/202553235-1cadcdb6-4025-4f9d-9a30-4d48b2b69b85.png)

### Expected result
The field looks disabled only if readonly="true"

### Actual result
The field looks disabled when readonly=""

### System information (as much as possible)
A very old issue

**Comment by crystalenka** [comment]
Should it be possible to overwrite it? Do we want to make it disabled for real, remove the styling, or something else?

I do see why this would be implemented - I imagine it's to discourage changing it accidentally since maybe changing the created user would remove someone's permissions to edit it. But "fake" disabled styling isn't the best solution here for sure.

**Comment by crystalenka** [comment]
I think you're right Brian, but it also gives the impression that the button is (or should be) disabled also, doesn't it? Because those are disabled styles, not readonly (which should be different imho)

**Comment by chmst** [comment]
On FF a new user is selectable and is stored.

**Comment by brianteeman** [comment]
correct. but you cannot type a username directly because the input is indeed readonly.

The best option is probably to change it so that there is just a button and text instead of a button and readonly input

**Comment by crystalenka** [comment]
Readonly input is appropriate, because it's significant info, will be submitted with the form, and should be able to be read by screenreaders etc, but the visual affordance should be different than that of disabled fields.

This is boils down to a styling issue. Not sure if it's part of Bootstrap or our overrides.

**Comment by crystalenka** [comment]
I agree with you Christiane, it is a little confusing
