### ISSUE TITLE
Joomla\CMS\Application\ApiApplication broken constructor

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#39373]
### What needs to be fixed
`Joomla\CMS\Application\ApiApplication::__construct()` accepts an instance of `Joomla\Input\Json` which is passed to the parent `Joomla\CMS\Application\CMSApplication` class which accepts only an instance of `Joomla\CMS\Input\Input`. This results in a type error.

### Why this should be fixed
Class is virtually unusable.

### How would you fix it
Narrow the accepted type in `ApiApplication` or widen the accepted type in `CMSApplication`.

### Side Effects expected
Maybe.

**Comment by wilsonge** [comment]
We should widen the parent. Originally there was some issues with the base class but at least https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Application/WebApplication.php#L85 seems to be fixed now when I test locally.

Still probably something safer fixed in 5.0 I guess despite that??

**Comment by SharkyKZ** [comment]
This should totally be fixed in 4.x. Funny thing is, this would have automatically fixed itself in 5.0 anyways because `Joomla\CMS\Input\Input` and co were already deprecated for removal in 5.0.

**Comment by Hackwar** [comment]
Thank you for reporting this issue. You are right, that this is a problem, but it is not something we can fix in a b/c way right now in either 4.4 or 5.x. For 6.0 this has been fixed by removing the CMS Input classes. Thus I'm closing this issue,
