### ISSUE TITLE
Bug in Prebuilt packages

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#39444]
### Steps to reproduce the issue
Go for example into the issue https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/39443/downloads/60210/ and download the prebuild package [Joomla_4.2.x_to_4.2.7-dev+pr.39443-Development-Patch_Package.zip](https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/39443/downloads/60210/Joomla_4.2.x_to_4.2.7-dev+pr.39443-Development-Patch_Package.zip)

In your Joomla test environment on Joomla 4.2.4 (or higher) go into the Joomla Updater and install the downloaded package.

### Expected result
The package updates your Joomla Version with the patch

### Actual result
Not only with this PR but also with another one I had first this screen. I tested it on three different sites and on two different servers.

<img width="1502" alt="Bildschirmfoto 2022-12-18 um 12 11 51" src="https://user-images.githubusercontent.com/828371/208295534-585ef00f-4952-449b-aec4-e630cd23a620.png">

and afterwards a message that the update went successful:
![Screenshot 2022-12-18 at 12-12-08 Upload   Update - Your Joomla! Site hosted with CloudAccess net - Administration](https://user-images.githubusercontent.com/828371/208295556-95923a9b-ca05-4bfa-8113-da68dc068df5.png)

But nothing was installed actually.

### System information (as much as possible)
I am not sure if this is a 
- user issue (did I confuse something?)
- or a prebuilt package issue
- or a Joomla issue

**Comment by crystalenka** [comment]
@richard67 

- usability bugs are also valid bugs
- user error is often because of a usability bug 
- is the problem the verbiage or the issue she's experiencing?

**Comment by richard67** [comment]
@coolcat-creations Regarding the issue: You need to download the https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/39443/downloads/60210/Joomla_4.2.7-dev+pr.39443-Development-Update_Package.zip . The patch packages 4.2.6 to 4.2.6 or 4.2.x to 4.2.7 are know to be incomplete regarding assets in the media folder. That means if you have a PR which only changes scss or js, if can be that there is nothing in the package. You can also use the custom update URL for a live update, that also installs the package which works and which I have mentioned first.

**Comment by richard67** [comment]
> @richard67
> 
>     * usability bugs are also valid bugs
> 
>     * user error is often because of a usability bug
> 
>     * is the problem the verbiage or the issue she's experiencing?

Read the title of this issue again. It says there is a bug where the description says that it's not clear yet where the bug is, and so it anticipates the result of the investigation which has to be done.

In fact the bug is not in the patch upload but in the fact that we still build the 4.2.6 to 4.2.7 or 4.2.x to 4.2.7 patch packages for nightly builds and for pull requests (but not for releases) while we know that these packages are incomplete because they do not include changes in the media or the vendor folder.

So please when making a title for an issue, try to summarize the issue and not the possible reason which has not been investigated yet.

**Comment by richard67** [comment]
@coolcat-creations Could you check and report back if it works for the PR you have mentioned in the description when you use the update package https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/39443/downloads/60210/Joomla_4.2.7-dev+pr.39443-Development-Update_Package.zip or the custom update URL https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/39443/downloads/60210/pr_list.xml ? Thanks in advance.

**Comment by richard67** [comment]
We will meanwhile fix the package build for the PRs so the questionable packages will not be built anymore in future. It had been fixed once in past, if I remember right, but somehow that got lost.

**Comment by richard67** [comment]
So regardless of my little complaint about the title, thanks for reporting.

**Comment by coolcat-creations** [comment]
Custom Update URL works as expected because thats what @crystalenka did to fix the missing patch on one of the test sites. The proposed package https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/39443/downloads/60210/Joomla_4.2.7-dev+pr.39443-Development-Update_Package.zip works as well. 

_In fact the bug is not in the patch upload but in the fact that we still build the 4.2.6 to 4.2.7 or 4.2.x to 4.2.7 patch packages for nightly builds and for pull requests (but not for releases) while we know that these packages are incomplete because they do not include changes in the media or the vendor folder._

So there is a bug / known issue in the prebuilt packages. 

_We will meanwhile fix the package build for the PRs so the questionable packages will not be built anymore in future. It had been fixed once in past, if I remember right, but somehow that got lost._

Yes I would recommend to remove them if they are unusable to test.

**Comment by richard67** [comment]
The nightly builds will not contain patch packages anymore. This has been fixed here in this repo with this commit https://github.com/joomla/joomla-cms/commit/f0206375b8092b567b97864a6232eb1b66b5ba30 for the 4.2-dev branch and will be merged up to 4.3-dev when the branch freeze for alpha 2 has ended.

This can be checked here: https://developer.joomla.org/nightly-builds.html . The nightly builds for 4.2 which I just have run don't include the patch packages anymore. Those for 4.3 still do.

The package build for pull requests will also not contain patch packages anymore. This has been fixed in the docker images here: https://github.com/joomla-projects/docker-images/commit/3b35e8b2e076d08c6f6ce05fe3a57a4722c8fd2b .

It might need further steps until we can see the result on the downloads page for pull request.

Thanks @HLeithner for both fixes.

Note that this should be a temporary solution until the build of patch packages has been fixed so they can be used.

**Comment by coolcat-creations** [comment]
Ok thank you I close this issue then! :-)
