### ISSUE TITLE
J 4.2.6 Adding Parent in Tags on the fly does not work

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#39441]
### Steps to reproduce the issue
Go to components » Tags
Create a tag and inside the creation form add a Parent on the fly (Type in a non Existing Name for the Parent and hit Return)
The Field accepts the input
Click Save and Close

### Expected result
The Parent Tag is created on the fly

### Actual result
Although it seems that the parent is created, it's not. The Item has no the value none as parent

**Comment by brianteeman** [comment]
I followed your instructions and confirm the bug

Interesting observation is that if you "Save and Close" you get an apparent success
![image](https://user-images.githubusercontent.com/1296369/208254510-f6ac2e4a-0a3d-45a1-a1c5-884d88666a65.png)

But if you just tried to "Save" you can clearly see the problem
![image](https://user-images.githubusercontent.com/1296369/208254542-99f16e6e-4cd8-4eca-ac3a-c7998fcb487f.png)

Personally I would not expect to be able to create a parent tag on the fly here. You can not for example create a parent category. So for me the fix is to prevent it appearing to offer that functionality in com_tags

**Comment by coolcat-creations** [comment]
I am fine with disabling the ability to type and save, I did not see the red warning at saving though

**Comment by brianteeman** [comment]
The error message is displayed only on a new tag when you try to create a parent and then press save
Not on an existing tag or when you save and close

**Comment by chmst** [comment]
@brianteeman correct. This is why I added the bug label. 

If we accept the feature "generate parent items on the fly" can be discussed ,but ist must be clear and no error my occur.

**Comment by chmst** [comment]
Please test #39443
