### ISSUE TITLE
[5.x] Real mail templates

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39492]
### Is your feature request related to a problem? Please describe.
The mail templates feature  is great and it offers a lot of possibilities beyond the mere customising of the text.

For example you can create templates with your site branding, colours, fonts and images and additional text eg contact details etc

### Describe the solution you'd like
Currently the only way to achieve this is to create each template.

What I would like to see is a "main mail template" and the only things that go in the component record would be the text required for the body of the message.

For example you could leave all the individual messages exactly as they are and just create/update/edit the master template., Now you have fully branded mail templates without having to edit each record.

In addition if you at a later date install an extension that supports mail templates then that will also use the master template

**Comment by crystalenka** [comment]
I really like this and entirely agree. 

I think we are moving in a direction where it may make sense to have a place for site branding with some of these things so they're not defined in lots of different places. 

Things like logos, a few colors, favicons, etc. 

Right now the place that this happens/belongs is template styles. I don't know if that makes sense for mail templates also. But it would be nice to be able to have multiple available mail template styles in some use cases. 

Just brainstorming a little bit.

**Comment by wilsonge** [comment]
> Things like logos, a few colors, favicons, etc.

Logos and colours was something we thought about for when we looked at putting service worker support into core.

Also Logo work might have been done as part of the GSOC 22 Schema.org project https://github.com/joomla-projects/gsoc22_schema.org that wants to have a logo field especially if your website represents an org.

The biggest issue with all of this is how to mandate it for existing sites - because things can fail really hard for this sort of data - and it's hard to give template provider dependant fallback options for such important things
