### ISSUE TITLE
Deactivated phases still appear in the filter

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#39509]
### Steps to reproduce the issue
Deactivate a workflow phase. 

### Expected result
The deactivated phases no longer appear in the "Workflow phases" filter. Just as deactivated categories no longer appear in the category filter.

### Actual result
The deactivated phases still appear in the "Workflow phases" filter. 

### System information (as much as possible)
Joomla 4.2.6, PHP 8.1

**Comment by brianteeman** [comment]
I'm not sure I fully understand the issue - could you post a few screenshots please

**Comment by brianteeman** [comment]
It has been two months since you filed this bug report. As this was not clear I asked for further explanation or screenshots so that we could investigate.

Without that information it is impossible to do anything and if it is not provided in the coming days I recommend that this is closed as unactionable

**Comment by richard67** [comment]
@hytsch Could you please provide some screenshot to make your issue clear to us, as requested in the 2 previous comments? Thanks in advance.

**Comment by brianteeman** [comment]
This shoudl be closed for the reasons stated above
