### ISSUE TITLE
Adding feature to add more than three links in Image link of  Articles

### ISSUE THREAD

**Issue by Kaushik1216** [joomla/joomla-cms#39589]
### Is your feature request related to a problem? Please describe.
At current User can add at most 3 Link with article through image link of articles . we should provide feature with which user can add more links if he/she want. 

### Describe the solution you'd like
Making a button to add more fields in which user can add more links

**Comment by wojtekxtx** [comment]
Quite not necessary imo.

**Comment by ReLater** [comment]
Just 2cents:

From my side a welcome feature. I don't like the current implementation. Also because of the rigid a-b-c PHP code.

Needs an intensive rework of this feature (code-side). Also because of B\C.

I would manage it via a more flexible subform where you can add more links, maybe more attributes per link, and where you can reorder the links more easily.

To reduce redundant codes maybe a Helper class or similar could be helpful.

**Comment by wojtekxtx** [comment]
> To reduce redundant codes maybe a Helper class or similar could be helpful.

@ReLater if you really need/want this feature to be implemented than just introduce some `helper` and thats it.

**Comment by brianteeman** [comment]
The original intention for J4 was to remove these fields completely as it is much easier to achieve now with custom fields but it was kept for backwards compatibility.

If you need to have a url field then use a custom field and if you make it repeatable then there is no limit for anyone on the number of urls you can add.

No point in adding code to do something that is already possible AND can be done much better with custom fields.

**Comment by HLeithner** [comment]
@brianteeman can you please stop reporting every comment of @wojtekxtx it's really offending against maintainers

**Comment by HLeithner** [comment]
And as already said please use custom fields for more links. I'm closing this.

**Comment by brianteeman** [comment]
> @brianteeman can you please stop reporting every comment of @wojtekxtx it's really offending against maintainers

when something is done for his troll posts
