### ISSUE TITLE
[4.3] Rename Articles - Newsflash

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39582]
In its original version almost 20 years ago this module would display the intro of 1 random article from a selected range of articles. That was all it could do. You could change the selection criteria but not how many wuld be displayed.

Over the years this module has gained significant functionality - it even comes with multiple layouts in core now so that it can be used to display multiple articles in different blocks (see blog sample data)

I have also seen mutplie examples of this module beeing used to create accordion, slider and even photo galleries.

### Problem identified
The name "Newsflash" no longer accurately describes the purpose of the module

>Articles - Newsflash
The Article Newsflash Module will display a fixed number of Articles from a specific Category or a set of Categories.

### Proposed solution
Rename the module to "Articles - Content" - _**only in the lang strings**_

>Articles - Content
The Article Content Module will display a fixed number of Articles from a specific Category or a set of Categories.

### Open questions
It will require some documentation udates

**Comment by crystalenka** [comment]
I agree that newsflash doesn't make sense with what it can do but not sure "content" makes it more clear. 

Even with the new functionality, it's still limited to showing "previews" of articles, right? Like a "latest posts" section with intro text. (I'm not at my computer right now to check so I could be wrong.)

Happy to brainstorm alternatives for this though.

**Comment by brianteeman** [comment]
Its really not limited at all. It will display images and custom fields out of the box. In many ways it is no different to a blog view.

I chose "Articles - Content" after looking at the names of the other modules in an attempt to maintain consistent naming. Otherwise I would just have proposed calling it "Articles", happy to hear other suggestions. But we really need to give it a new name for 4.3.0

**Comment by crystalenka** [comment]
Thinking aloud here...

The biggest difference that I know of from the other article modules is that the others generally are just lists of linked titles. So I definitely see where you're coming from with your suggestion. 

The thing is that the other articles modules are titled basically by how they're filtered, not how they're displayed, and most of the filters are possible with the newsflash module also, with the exception of the dynamic ones.

I would almost want to rename all the articles modules to be more accurate because at first glance, it's not clear why e.g. "Articles - Latest" is different from the newsflash module with the ordering set to show most recent. 

So for this example, "Articles List - Latest" would make it more clear.

And then maybe "Article Previews" or something instead of newsflash?

Maybe something like:

- "Articles - Archived" ➡️ "Articles List - Monthly Archive"
- "Articles - Categories" ➡️ "Article Categories List" (since it doesn't list articles at all)
- "Articles - Category" ➡️ "Articles List - Filtered by Category" _(not sure about this. This one's strength is the dynamic category selection that it can do.)_
- "Articles - Latest" ➡️ "Articles List - Latest" (or "most recent"?)
- "Articles - Most Read" ➡️ "Articles List - Most Read"
- "Articles - Related" ➡️ "Articles List - Related"

**Comment by brianteeman** [comment]
Still not a fan of the word _preview_. Definitely a fan of introducing the word _list_

My first choice was just to rename it to "Articles" but that doesnt fit with the styling of the others.

**Comment by crystalenka** [comment]
Random words that come to mind when brainstorming this:

Extended, detailed, rich, expanded, complex, configurable...

**Comment by brianteeman** [comment]
_articles anywhere_ 😁

**Comment by crystalenka** [comment]
Based on the suggested naming convention above with "Articles List", maybe something like this?

"Articles Group [or set?] - Expanded"

Or "Articles - Flexible List"?

**Comment by chmst** [comment]
I agree that the name "News" is outdated.
But I am not in favour to rename it now in J4. 
I would prefer a plan how to make one module wihch is a combination of latest / news / popular / category in J

**Comment by brianteeman** [comment]
I am absolutely not a fan of "do-it-all" mmodules

**Comment by crystalenka** [comment]
@chmst I agree, as I was going through the names above I was thinking that especially the more basic ones could be combined and would love to see a more streamlined approach with only 2-3 module types. Not sure we can remove old module types though, that would be a pretty big break. :/ 

I think if we rename anything in the language strings it probably would have to be in J5 because of the docs updates etc. It's not a technical bc break but maybe a UI one?

**Comment by brianteeman** [comment]
I prefer a module that does a single task and does it well.

Whenever you try to combine tasks you increase the potential for either making compromises to the functionality or creating a UI that is not understandable.

When you have a single task then it is easy to understand and setup. There are very few, if any, options and it just _does what it says on the tin_

When you combine tasks then you start to get all sorts of configuration options etc

**Comment by crystalenka** [comment]
Hmmm. I think it depends on the user and their mental model. 

Especially for new users, they might not understand the difference between so many different modules that are extremely similar. (Like articles latest and articles most read--do we really need different modules for just changing the sorting?)

Configuration options are not inherently bad as long as they are intentional and have sensible defaults. They can lower the barrier to entry and provide flexibility which people are starting to expect from CMSs. 

But as I said--it depends. :)

**Comment by brianteeman** [comment]
Ever tried to explain this
![image](https://user-images.githubusercontent.com/1296369/211279041-dbe6dbff-ef56-4658-8f14-7f9988484117.png)

**Comment by chmst** [comment]
I agree for "one concern - one module" is the correct way in development and better than a "all-in-one". 
But this is not what we have now. So I stand to my opinin that renaming a module in J4 does not have any benefit.

**Comment by crystalenka** [comment]
@brianteeman yes I have. 

@chmst i agree that renaming shouldn't happen in J4, but it's a valid discussion for J5, no?

**Comment by rytechsites** [comment]
How about: since that is the purpose, to display content (and not be used as a 'list')
Article - Display Content

I'm also confused about the purpose when Articles - Category (should also have a name change), really does the same function as the current newsflash, because you can display text or not.

I understand the concern of not having 'all in one', but what is the real difference of functionality between the current newsflash and the articles cateogry, functionality wise?

Or is it because people really like creating overrides for article - newsflash... so it is important to keep both?

**Comment by carlitorweb** [comment]
> I understand the concern of not having 'all in one', but what is the real difference of functionality between the current newsflash and the articles cateogry, functionality wise?

I will say, right now is performance only (But maybe it's not that significant)

**Comment by brianteeman** [comment]
> So I stand to my opinin that renaming a module in J4 does not have any benefit.

It is a fundamental principal of accessibility that something should be Understandable. Describing this module as a newsflash is not understandable as it does not act as a newsflash but instead as a way of displaying content.

**Comment by brianteeman** [comment]
> I'm also confused about the purpose when Articles - Category (should also have a name change), really does the same function as the current newsflash, because you can display text or not.

No that module only displays a list. This is the only module that displaye content

**Comment by chmst** [comment]
When I see this image, I would say: Rename all the modues which provide a list to : Article List Category, Article List Latest, and so on. 
Then it makes sense to rename Articles newflasch to Articles :)

**Comment by brianteeman** [comment]
I would also be happy with that

**Comment by wojtekxtx** [comment]
https://github.com/joomla/joomla-cms/issues/39582#issuecomment-1375330493

> Whenever you try to combine tasks you increase the potential for either making compromises to the functionality or creating a UI that is not understandable.

@brianteeman true. However, let me just add that by combining tasks (that `module` is supposed to do/undertake) you create poosibility for bugs to slip in. Even unwillingly.

>  mental model.

@crystalenka: Whoa, thats courageous to say this! In other words, you incline that insane people cannot use Joomla? Insanity can be medically treated in the way that minimizes impact illness have on person life.

**Comment by brianteeman** [comment]
Folks - time to stop responding

**Comment by crystalenka** [comment]
"A mental model is an explanation of someone's thought process about how something works in the real world." https://en.wikipedia.org/wiki/Mental_model

**Comment by wojtekxtx** [comment]
@crystalenka: 👍 for this. Many thanks.

@brianteeman oh yeah, you say its time to stop responding to your malicious comments? I suppose you are right ;)

But seriously: since you wrote comment, could this have been comment with no malice towards me? Say whatever, but your comment only proves that Crystal's husband was 100% right with all negative comments on J!'s leadership.

**Comment by bembelimen** [comment]
Fun fact: Crystal is leadership, Brian is not... 

Anyways please stop with posting all this off topic comments everywhere. First and last warning.

**Comment by wojtekxtx** [comment]
> Brian is not...

@bembelimen may be true, but Brian is cofounder of J!

**Comment by brianteeman** [comment]
> I'm also confused about the purpose when Articles - Category (should also have a name change), really does the same function as the current newsflash, because you can display text or not.

@rytechsites mea culpa I didnt notice that you can display introtext with this module now. You still can't display the images though?

**Comment by brianteeman** [comment]
Closed - never going to happen
