### ISSUE TITLE
Idea: Styling of the "Read more ..." button on the homepage.

### ISSUE THREAD

**Issue by samitkapoor** [joomla/joomla-cms#39765]
**This issue targets the style of the "Read more ..." button on the home page.**
![Screenshot 2023-01-31 234113](https://user-images.githubusercontent.com/77121931/215847339-57009d6a-4369-4e87-b670-629bdabfad1d.png)

Currently, the background color of the button looks very simple and the read more button doesn't look very exciting.

I'd like to work on the styling of the button and change its background color to orangish, which would also match the color scheme of the website and also look more appealing and exciting just like the Download button on the top of the website.
![image](https://user-images.githubusercontent.com/77121931/215848388-e9b69bdc-b382-412d-9837-4e1b8779cab4.png)

I also propose adding some transition to the button style that would change some styling of the button when the user hovers on it, which would make the button more clickable!

**Comment by samitkapoor** [comment]
I would like to work on this issue..

**Comment by richard67** [comment]
This issue is about the styling of the joomla.org site, but here is the repository for the CMS code and not for the website where the styling should be made. So this issue here is at the wrong place. It should be reported in this repository: https://github.com/joomla/joomla-websites .

Closing as not an issue with the CMS core.
