### ISSUE TITLE
Inconsistet update progress bar 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#39829]
### Steps to reproduce the issue

Update to  a new version  and watch the progress bar.  The last number is not presented in MiB

![grafik](https://user-images.githubusercontent.com/1035262/218034740-f9b806df-7fd0-484d-a34d-a036b0fa2b69.png)

**Comment by brianteeman** [comment]
The last number is the number of fils iirc

**Comment by chmst** [comment]
This possible, will try to inspect the next update. But would prefer a text also for this number.

**Comment by brianteeman** [comment]
confirmed it is the number of files

**Comment by brianteeman** [comment]
Took me a while to find it as I knew it sounded familiar. Like you i think the text should be there and I raised the issue of the missing text at the time https://github.com/joomla/joomla-cms/pull/35388#issuecomment-908749460

and the response from the author was NO https://github.com/joomla/joomla-cms/pull/35388#issuecomment-909440321 and its just not worth the emotional energy to challenge the author.

**Comment by sandewt** [comment]
I confirm this issue.

At school, for example, you learn in physics that it is important to state the unit.
Otherwise, the result of a sum could just as well be 'euros', 'dollars' or even 'cows'.
In short, it is important to call the unit, here 'files', as I understand.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39829">issues.joomla.org/tracker/joomla-cms/39829</a>.</sub>

**Comment by 2003tanmay** [comment]
> Took me a while to find it as I knew it sounded familiar. Like you i think the text should be there and I raised the issue of the missing text at the time [#35388 (comment)](https://github.com/joomla/joomla-cms/pull/35388#issuecomment-908749460)
> 
> and the response from the author was NO [#35388 (comment)](https://github.com/joomla/joomla-cms/pull/35388#issuecomment-909440321) and its just not worth the emotional energy to challenge the author.

so, we have to present 'files' after last number or not?

**Comment by alikon** [comment]
please test #40742
