### ISSUE TITLE
List view: Filter number of records

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#39859]
### Does your feature request relate to a problem? Please describe it.
In the list view, I can look at max. 500 records, or equal to all. Editing, e.g. disabling ALL records or users, leads to a crash of the browser for larger amounts of data. 

### Describe the solution you would like to see
For a website with a few thousand records, pagination at 1000, 2000, 5000 10000 records would be very helpful.

**Comment by joomdonation** [comment]
I don't think we would support for that large number of records. Assume there are 2000 records displayed, how would you find the record you want to do something? If you want to delete 2000 records for example, it's very likely that it won't work because usually, max_input_vars from php settings of server set to 1000, and it could not submit data for large number of records for processing. It is also slow and require more memory to render that large number of records, and could cause fatal error because timeout or lack memory.

**Comment by alikon** [comment]
there are a lot of filter options already in place to help to fine grain the list
so not the way to go
