### ISSUE TITLE
Template Manager ico 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39861]
### Steps to reproduce the issue
Using the template manager try to upload an *.ico image such as a favicon
It should fail
Go to the template manager options and add ico to the list of alloed image formats

![image](https://user-images.githubusercontent.com/1296369/218809310-9621afa9-a006-4435-a85c-b5210d74d654.png)

Try again to upload an *.ico image using the template manager

### Expected result
File uploaded

### Actual result
File Uploaded success message
AND
File not uploaded error message

![image](https://user-images.githubusercontent.com/1296369/218809552-19880ab1-9959-4ed0-8b2d-000e3cd93512.png)

**Comment by wilsonge** [comment]
You need to add `image/vnd.microsoft.icon` to the `Legal MIME Types` field

We validate the file format and the mime type of the file as part of the security checks.

**Comment by brianteeman** [comment]
This is in the template manager not the media manager where there is no mime type field and if twasnt clear the ico image is uploaded despite the error messages

![image](https://user-images.githubusercontent.com/1296369/218814969-1a39728f-f18c-4f64-8c25-89b7c8b0a786.png)

**Comment by wilsonge** [comment]
🤦 i'm blind. sorry.

**Comment by dgrammatiko** [comment]
.ico images are not valid for the `img` tag: https://github.com/joomla/joomla-cms/pull/12009

Also you shouldn't use .ico for favicons anymore, use PNG: https://caniuse.com/link-icon-png

**Comment by brianteeman** [comment]
@dgrammatiko that isnt the point. the conflicting messages is the issue

**Comment by dgrammatiko** [comment]
The green alert is correct because the file was uploaded correctly

The error comes from https://github.com/joomla/joomla-cms/blob/23de0b11d843747a6a747083a4294c7f59a58fa3/libraries/src/Image/Image.php#L620 which is coming from https://github.com/joomla/joomla-cms/blob/23de0b11d843747a6a747083a4294c7f59a58fa3/administrator/components/com_templates/src/Model/TemplateModel.php#L1461

You could try to patch things, probably here (?): https://github.com/joomla/joomla-cms/blob/23de0b11d843747a6a747083a4294c7f59a58fa3/administrator/components/com_templates/src/View/Template/HtmlView.php#L188

Again, the `ico` files are not images for the browsers (or most web tools).

**Comment by brianteeman** [comment]
not interested in debating the value of ico or if they are images or if they should be used.

This issue is purely about the two conflicting messages

**Comment by dgrammatiko** [comment]
> This issue is purely about the two conflicting messages

This is not an issue. ICO ARE NOT IMAGES (in the sense that jpg, png,avif,webp, gif) both for the browser and the PHP tools (the image class). Adding that extension to the allowed ones and expecting that somehow both PHP and Browsers will actually do something more than an error is delusional...

**Comment by wojtekxtx** [comment]
> ICO ARE NOT IMAGES 

@dgrammatiko o_0. What? If not imges than what they are?

> you added a non valid image format into the array of valid images

@dgrammatiko than this img type (`ico` in this case) should be made valid by adding support for it. Pretty obvious.

**Comment by brianteeman** [comment]
that is NOT the issue I am reporting.

You should never be able to get both a success and a fail message for the same thing

**Comment by dgrammatiko** [comment]
> You should never be able to get both a success and a fail message for the same thing

Once again: you added a **non valid image format** into the array of valid images and expected somehow to work, that would never work because neither browsers or PHP GD is not considering .ico files as valid images.

**Comment by wojtekxtx** [comment]
> neither browsers or PHP GD is not considering .ico files as valid images.

@dgrammatiko any reasoning behind this?

> this weird format

@dgrammatiko why do you think `ico` is weird?

> that is NOT the issue I am reporting.

@brianteeman if so, could you please explain to us, in more detailed way, what are you trying to report here? Serious question.

**Comment by brianteeman** [comment]
closing this and will re-open a new issue with a big warning to NOT discuss if an ico is an image or not

**Comment by Orgoth** [comment]
> > You should never be able to get both a success and a fail message for the same thing
> 
> Once again: you added a **non valid image format** into the array of valid images and expected somehow to work, that would never work because neither browsers or PHP GD is not considering .ico files as valid images.

@dgrammatiko You are writing nonsense!

imagemagick is supporting ico "convert -list format | grep ICO -> ICO* ICON      rw+   Microsoft icon"
tested under Kubuntu 22.04 LTS and Debian 12 Server "ImageMagick 6.9.11-60 Q16 aarch64 2021-01-25"
Even the current release 7.1 does support ico.
https://github.com/ImageMagick/ImageMagick

Nearly all Browsers are supporting ico as image format.
https://en.wikipedia.org/wiki/Favicon#Browser_implementation
https://en.wikipedia.org/wiki/Favicon#HTML5_recommendation_for_icons_in_multiple_sizes

> HTML5 recommendation for icons in multiple sizes
> The current HTML5 specification recommends specifying multiple sizes for the icons, using the attributes rel="icon" sizes="space-separated list of icon dimensions" within a <link> tag.[39] Multiple icon formats, including container formats such as Microsoft .ico and Macintosh .icns files, as well as Scalable Vector Graphics may be provided by including the icon's content type in the format type="file content-type" within the <link> tag.

Only GD-Lib does not support the ico format.

> .ico images are not valid for the img tag (ie cannot display inside an HTML doc): https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#supported_image_formats

Have a look at the link tag.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#examples:~:text=There%20are%20a%20number%20of%20other%20common%20types%20you%27ll%20come%20across.%20For%20example%2C%20a%20link%20to%20the%20site%27s%20favicon%3A
```html
<link rel="icon" href="favicon.ico" />
```
A lot of pagebuilders are using the image folder to select the favicon and all Browsers are still supporting ico as favicon.

Since you have referred to caniuse, I will also do so.
https://caniuse.com/mdn-html_elements_link_rel_icon

![Auswahl_525](https://github.com/joomla/joomla-cms/assets/1035170/a96270aa-8386-440e-bde3-ada42d8e7848)

> will use ICO over PNG if ICO has better matching sizes set
> safari: If both ICO and PNG are available, will ALWAYS use ICO file, regardless of sizes set.

Only the manifest icons does not support ico in all cases. "or is simply unknown if it is supported"
https://caniuse.com/mdn-html_manifest_icons

**Comment by dgrammatiko** [comment]
> Nearly all Browsers are supporting ico as icon-image format.

My comment was: `.ico images are not valid for the img tag (ie cannot display inside an HTML doc):` **which is not about the `<link rel=icon>`!!!!**
You don't even understand the problem but you thought you'll give some input (and calling my comments nonsense). So, kindergarten explanation:
- Open your favourite browser
- Drag and drop any image file
- The supported formats will be rendered in the browser
- Guess what? The `.ico` file **WILL NOT**, You know why? Because that image format is not supported by the browsers (for the HTML pages, only as an icon for their chrome tabs!

All your other comments are irrelevant

**Comment by Orgoth** [comment]
> > Nearly all Browsers are supporting ico as icon-image format.
> 
> My comment was: `.ico images are not valid for the img tag (ie cannot display inside an HTML doc):` **which is not about the `<link rel=icon>`!!!!** You don't even understand the problem but you thought you'll give some input (and calling my comments nonsense). So, kindergarten explanation:
> 
> * Open your favourite browser
> * Drag and drop any image file
> * The supported formats will be rendered in the browser
> * Guess what? The `.ico` file **WILL NOT**, You know why? Because that image format is not supported by the browsers (for the HTML pages, only as an icon for their chrome tabs!
> 
> All your other comments are irrelevant

And so that you can't claim that it only works because it was loaded directly via the file system, here again with an html file, with an img and the favicon.

![Auswahl_534](https://github.com/joomla/joomla-cms/assets/1035170/9b1cba3c-a6cb-4d0b-833a-5729a30d2e9a)

![Auswahl_535](https://github.com/joomla/joomla-cms/assets/1035170/65401450-8599-4a20-bcdc-2b10cbb8b5b2)

**Comment by Orgoth** [comment]
And vivaldi 6.2.3105.54 (Stable channel) stable (64-Bit) :

![Auswahl_536](https://github.com/joomla/joomla-cms/assets/1035170/92575fbd-54d7-45a9-b34d-64cbcf0730e3)

**Comment by dgrammatiko** [comment]
@Orgoth probably this is new but **personally** I'll stick to the SPECS: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#supported_image_formats and not do anything with that legacy proprietary format, the web has moved on...

**Comment by Orgoth** [comment]
That is also absolutely right that it must continue.
Nevertheless, it is a format which is supported by all common browsers and be it for legacy reasons.
Accordingly, the statements from you were unfortunately wrong and could not stand so.

As communicated by me, some page builders such as Yootheme use the images folder for the favicons and there ico cannot be uploaded even if the user enables them.
But this is a separate point that does not belong here to the actual ticket, because this is just a duplicate message, as you have also seen in the other ticket.

**Comment by dgrammatiko** [comment]
If you are using tools that are still using `.ico` files I guess you could use better your time to fill issues to their support so they could move to something more modern (png or even better svg) instead of fighting over a closed issue...

Unsubscribing

**Comment by Orgoth** [comment]
@dgrammatiko
It was solely your manner, as well as the false factual claims of you, that prompted me to write anything at all about this.
Also, that you have not answered questions that were addressed to you directly. 
See @wojtekLs 
And that you just ignored the obvious problem, what @brianteeman reported and permanently stuck to the point of view that the format is weird and outdated or not recognized as an image.
The image is clear, there is a success message and an exception and there should be only one of them.

Please do not make false claims without having practically counter-checked that this is indeed the case.

Yes lets close this discussion here, we have made our point clear.
