### ISSUE TITLE
Guided Tours - Editors

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40019]
## Steps to reproduce the issue
When you are not using **tinymce** or **no editor**  then any tour that accesses the editor area produces unexpected results.

Creating seperate issue for each bug report so that they dont get lost inside a bigger report (again)

![image](https://user-images.githubusercontent.com/1296369/222952069-42421ad0-6381-4181-8984-9b7fdeded572.png)

### JCE
![image](https://user-images.githubusercontent.com/1296369/222952081-c81b6bed-daf1-4a27-b8b7-1c16b527fa79.png)

### Codemirror
![image](https://user-images.githubusercontent.com/1296369/222952111-0bf72d5e-7ef9-4d81-9611-f5ed684c8330.png)

As can be seen above an error is shown in the console and the editor area will not accept any input. There is no indication to the user taking the tour why this is the only step on the tour that is disabled.

**Comment by wojtekxtx** [comment]
@brianteeman can confirm this, although wording could be better.

**Comment by obuisard** [comment]
Some of it is addressed by PR #40044.

For CodeMirror, it is tricky, we cannot make it work as of now because CodeMirror itself is not accessible.
We can make CodeMirror available to mouse events, but by doing so, we penalize users who need to tab through.
I would suggest we fix CodeMirror first (one cannot tab out of the codeMirror editor as of now).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40019">issues.joomla.org/tracker/joomla-cms/40019</a>.</sub>

**Comment by wojtekxtx** [comment]
@obuisard what do you mean that CodeMinor is not accessible? Its very much IS [accessible](https://github.com/codemirror/codemirror5).......

**Comment by obuisard** [comment]
> @obuisard what do you mean that CodeMinor is not accessible? Its very much IS [accessible](https://github.com/codemirror/codemirror5).......

You can't tab out of it.

**Comment by wojtekxtx** [comment]
@obuisard have not noticed it
