### ISSUE TITLE
Guided tour "Create articles". Category and other "choices" fields not editable

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#40029]
### Steps to reproduce the issue
- Start a tour "How to create articles".
- Go through the steps.
- See image. In step "Select Category" it's not possible to edit the category field. [See also comment](https://github.com/joomla/joomla-cms/issues/40029#issuecomment-1455142288) of @brianteeman below
- Win10. Firefox. Mouse navigation. Nightly build of today, Update package, 4.3 to 4.3.

![grafik](https://user-images.githubusercontent.com/20780646/222967931-ade11311-1e54-4980-af5b-d4512f19bcee.png)

**Comment by brianteeman** [comment]
The same error is present for any field using choices such as tags

**Comment by wojtekxtx** [comment]
@ReLater you dont have to *edit* fild; you have to *select example value from dropdown*

**Comment by brianteeman** [comment]
@wojtekxtx no you cannot - did you even try

**Comment by obuisard** [comment]
The only way to access a fancy select in Joomla is to use the :has selector, which is available on all browser, except for Firefox, behind a flag. 
With the way Joomla builds these fancy select boxes, I don't see another way to get to it if there is more than one fancy box on the page, which is often the case.
Firefox is planning on supporting :has in the first half of this year (https://bugzilla.mozilla.org/show_bug.cgi?id=418039).
What I would suggest, since there is no real certainty with Firefox, is to use the :nth-child selector for now, which will ensure proper support.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40029">issues.joomla.org/tracker/joomla-cms/40029</a>.</sub>

**Comment by Quy** [comment]
Please test PR #40077. Thanks.

**Comment by ChristineWk** [comment]
@Quy I didn't see the reference to the PR when I called up the issue. You can only see it on Github.
