### ISSUE TITLE
Router::$cache is using so much memory

### ISSUE THREAD

**Issue by anilalci** [joomla/joomla-cms#40091]
### Steps to reproduce the issue
Call Route::_ method one million times for different url

### Expected result
low memory usage

### Actual result
high memory usage

### System information (as much as possible)
memory_limit = 1G

### Additional comments
One of them can be a solution;
- cache on/off configurable
- clean cache method
- object limit for cache

**Comment by joomdonation** [comment]
Our routing system stores the processed URLs into `Router::$cache` so that it does not have to handle building process more than one time for the same URL. Please note that this is `in memory` cache, data in `Router::$cache` are the URLs for each page load. In real life usages, there won't be that large number of URLs per page, so I think the current implementation is fine. 

Since this is in memory cache for each page load, I think the solutions you suggested are not applicable, too.

**Comment by joomdonation** [comment]
@Hackwar Could you please provide an example code which allows `loads your version of the router class` ? That would help users who has similar requirement.

**Comment by Hackwar** [comment]
```
<?php
use Joomla\CMS\Plugin\CMSPlugin;

class plgSystemMyownrouter extends CMSPlugin
{
	public function onAfterInitialise()
	{
		require_once __DIR__ . '/router.php';
	}
}
```

And in the router.php you have your copy of the router class.
