### ISSUE TITLE
New install 4.2.9 no css just text ?

### ISSUE THREAD

**Issue by SC110022** [joomla/joomla-cms#40140]
Admin dashboard without css just text?

**Comment by toivo** [comment]
This could be caused by the so called Double Gzip issue, mentioned in the [Joomla 4.2.9 Announcement Discussion](https://forum.joomla.org/viewtopic.php?f=9&t=1000437) at the [Joomla! Forum](https://forum.joomla.org).  If there is still a problem, please create a topic at the  [Joomla! Forum](https://forum.joomla.org).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40140">issues.joomla.org/tracker/joomla-cms/40140</a>.</sub>

**Comment by Quy** [comment]
Please enable the debug mode and check the error.

Then you can ask in the forum for support.
