### ISSUE TITLE
[4.3] guided tours - tour permissions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40200]
### Steps to reproduce the issue
try to change the permissions of a tour

### Expected result
![image](https://user-images.githubusercontent.com/1296369/227745823-bfe1267f-5d8d-41ee-8b6a-2b12acfef03f.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/227745813-85655574-6592-4641-9ce9-ad18190068e6.png)

**Comment by obuisard** [comment]
It's the same as articles, once an article is created. I don't think there are missing permissions here.

**Comment by brianteeman** [comment]
Surely a better analogy would be with categories or workflows. Categories contain articles. Workflows contains stages, Tours contain stages.

**Comment by richard67** [comment]
@brianteeman I think you mean steps. But the steps do not have assets.

**Comment by brianteeman** [comment]
ok let me try it another way.

How can I prevent someone from creating a new step.

With the current permission settings I can prevent them from deleting or editing a tour and as a consequence I have prevented them from deleting or editing a step.

BUT I can still create new steps in the tour. I should be able to prevent that

**Comment by obuisard** [comment]
One thing though, if someone has no access to a tour, the steps should not be accessible from the tour list. That has to be fixed (apply the same access we apply to the title of the tour in the list to prevent edit).

![image](https://user-images.githubusercontent.com/5964177/227973715-01df4527-d6fa-460d-aa34-10874550cde4.png)

Steps have no permissions because it was considered a tour and its steps are the same 'object'. Therefore, access to a tour should trickle down to its steps: 
if one can edit a tour, one can edit its steps. If one can delete a tour, the steps are deleted, if one can create a tour, one can create its steps...

I understand now that we need those extra permissions (create/edit own)

The steps list page is missing access restrictions in case someone can just edit the URL to access a tour's steps (assuming we prevent the click on the step's count in the tour list).

I will create a PR to address all those issues.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40220 . Thanks in advance.
