### ISSUE TITLE
Remove obsolete simplepie and phpmailer libraries from Joomla 4

### ISSUE THREAD

**Issue by biltongandpotroast** [joomla/joomla-cms#40245]
### Steps to reproduce the issue

Running the Joomla 4 Pre-Update check warns of the simplepie and phpmailer libraries not being compatible.

Perform an upgrade from Joomla 3.x to Joomla 4.x.

### Expected result

You would expect that the Joomla 4 upgrade process would remove these libraries from the installation.

### Actual result

The upgrade does not remove the obsolete simplepie and phpmailer libraries from the installation.

### System information (as much as possible)

Upgrade from Joomla 3.10.11 to Joomla 4.2.9

### Additional comments

There is information in the online Joomla community advising that these libraries are obsolete in Joomla 4. So you would expect that the Joomla 4 upgrade process would remove them from the installation but it doesn't.
Many hours must be wasted by Joomla implementers trying to work out how to remove them.

**Comment by richard67** [comment]
@biltongandpotroast I think there is some misunderstanding on your side. When the Pre-Update check warns of the phpmailer libraries not being compatible, that doesn't mean that these libraries are obsolete. It means that they are not compatible with Joomla 4 in the versions which are available on Joomla 3. But they will be updated with the core when updating the CMS to 4. See here the PR which updated it for Joomla 4: #34598 . And if you check the installation package of any Joomla 4.x version you will see the phpmailer is still included.

With the simplepie you are right, it is obsolete in Joomla 4, and so it is removed with the update, see here for the code: https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_admin/script.php#L6858-L6872 . So if these folders still are there after the update, then your update has not run completely. This makes me ask: How have you updated? Have you used the Joomla Update component like it should be, and has the update run without any errors? Or have there been errors, or have you used an old, unsupported method for updating like e.g. just uploading and unpacking the zip file and then running the database fixer? That would not work and is unsupported since 3.4 or 3.5.

**Comment by brianteeman** [comment]
Closing as there is nothing to do here. The question was answered
