### ISSUE TITLE
[4.3] [Not a bug] [Possible duplicate] Pre-update check shows extensions check on update 4.2.x to 4.3

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-cms#40445]
Sorry, I forgot, Is it intended that now, before update 4.2.x [4.2.3, for example, also for 4.2.7] to 4.3, there are the complete update check (with extensions check)? Simillar to J3 to J4 update, simillar that was for 4.0.2 -> 4.0.3 in #35904 "by mistake" (and "edited" in #35978 PR [after this PR, I don't remember that I saw it when I updated multiple times, from 4.0.x to 4.2.3, for example]).

![image](https://user-images.githubusercontent.com/3628514/233618278-2d6a228e-d1d0-4b40-aa3e-030f8316af2a.png)

**Comment by richard67** [comment]
@AndNovAtor As far as I can read in the code and the comment here it is desired behaviour to show the pre-update check not only when updating to a new major but also when updating to the next minor: https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php#L294-L313 

```
// Show only when we found a download URL, we have an update and when we update to the next minor or greater.
```

**Comment by richard67** [comment]
Closing as expected behaviour. The pre-update check shall be shown when updating to a new major or to the next minor version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40445">issues.joomla.org/tracker/joomla-cms/40445</a>.</sub>
