### ISSUE TITLE
Messaging login/logout in the frontend of Joomla 4.3.0

### ISSUE THREAD

**Issue by irathers** [joomla/joomla-cms#40458]
Whenever a user logs in or logs out on the front end of Joomla 4.3.0 a banner message is displayed on screen.
This is listed as a new feature in the 4.3.0 release notes but there are no details about controlling it.

Login/logout messages were not shown in version 4.2.9 and previous releases.   If this functionality is required by some users, then it should be optional.   I cannot find any parameters in the backend that enable me to turn this functionality off.

Screenshots are attached to show the login/logout messages produced and they are simply not required.![screen shot 2023-04-23 at 01 28 24](https://issues.joomla.org/uploads/1/99415b1a75fd5cf08cc81820d0672ad8.jpg)

### Additional comments

![screen shot 2023-04-23 at 01 28 26](https://issues.joomla.org/uploads/1/6357b310939a500830c123bda014cc58.jpg)

**Comment by sandewt** [comment]
If you find the message (logon / logout) annoying, you can make a language override.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40458">issues.joomla.org/tracker/joomla-cms/40458</a>.</sub>

**Comment by sandewt** [comment]
> I cannot find any parameters in the backend that enable me to turn this functionality off.

That's correct. 

Originally this functionality was planned, but was not added in the end. See for the discussion #30834.

**Comment by irathers** [comment]
Thank you for the quick reply.

I don't understand the need for these messages.   In 4.2.9 when you login you get a greeting like Hi Bill Smith and the button changes to 'Logout'.   When you logout the username, password input boxes appear along with a 'login' button.

Are there any plans to provide some control over these new login/logout messages in the next release?   If not can you provide me a link to details on how to make a language override.

Many thanks
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40458">issues.joomla.org/tracker/joomla-cms/40458</a>.</sub>

**Comment by sandewt** [comment]
> Are there any plans to provide some control over these new login/logout messages in the next release?

Joomla is open source and is consensus-based. So you can simply submit a proposal.

Example lanuguage override, see: https://docs.joomla.org/J3.x:Language_Overrides_in_Joomla

**Comment by J-Wick4** [comment]
This was driving me nuts. Almost every major website does not show these messages. There should really be a setting for these to turn off easily.

**Comment by lucdonk** [comment]
This was driving me nuts also. Almost every major website does not show these messages. 
There should really be a setting for these to turn off easily.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40458">issues.joomla.org/tracker/joomla-cms/40458</a>.</sub>

**Comment by sandewt** [comment]
> There should really be a setting for these to turn off easily.

At the time, as I mention above, this option did not make it. If there is enough demand for it, it can still be realized easily. By default there are no messages.

![233392094-b05427eb-84b6-48a8-b2db-7668c57719b5](https://user-images.githubusercontent.com/9271775/234281397-6e31e763-7a10-4176-afaf-1539fd4d3a2b.png)

@chmst please your opinion.

**Comment by lucdonk** [comment]
Would be nice to see these options included.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40458">issues.joomla.org/tracker/joomla-cms/40458</a>.</sub>

**Comment by Pinkeltje** [comment]
Remove or add option to enable/disable please
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40458">issues.joomla.org/tracker/joomla-cms/40458</a>.</sub>

**Comment by WoodyF4u** [comment]
Yes for mee too.
And we have a couple of same questions atr our Dutch Joomla forum.

So it would be very nice when this will be added in the next J4.3.x release.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40458">issues.joomla.org/tracker/joomla-cms/40458</a>.</sub>

**Comment by chmst** [comment]
As was said in the former discussion, more params are not really welcome and a message management system would be great. 

My2cent:

A Logout message is always useful. Most people don't logout - but if they do, because they are on sensitive data, then it is good information.

Whether a login mssage is useful depends on the application. If the user remains on the same view after login, it can be welcome.
If the login leads the user to a new internal site it seems to be deistracting.

A param for the Login Message could help.

**Comment by sandewt** [comment]
@chmst 

I totally agree with your justification for a login and logout message and that a param for the Login Message could help.

In order not to get b/c with Joomla 4.3, the login and logout messages are displayed by default in case of a new PR.  So that additional actions are required to disable the messages. This unfortunately in contrast to the previous, originally intended  PR #30834.

The question is what is wisdom in this case?

**Comment by Pinkeltje** [comment]
I totally agree with @irathers 

> I don't understand the need for these messages. In 4.2.9 when you login you get a greeting like Hi Bill Smith and the button changes to 'Logout'. When you logout the username, password input boxes appear along with a 'login' button.
Is there a pull or feature request where I can find the origin of this addition?

**Comment by brianteeman** [comment]
I am wondering if the reason that people are not liking these messages is because their template design does not display such messages in a nice way as seen on the the screenshots in the first post.

I never even noticed the messages on my cassiopeia based sites or on my sites using a custom message view as they were formatted nicely

Cassiopeia screenshot
![image](https://user-images.githubusercontent.com/1296369/235096027-eecd1b19-8bbc-4960-8906-9cf81e02d997.png)

Custom template screenshot
![image](https://user-images.githubusercontent.com/1296369/235095796-cd7dce59-cb82-4e90-95d3-331e9995a51a.png)

**Comment by Pinkeltje** [comment]
I just find it redundant to mention that someone is logged in. You log in to access certain content, so you do that intentionally. Once logged in, you either see a welcome message, or a logout button, so any right-thinking person then knows they are logged in.
Layout of the message can always be changed, but I am more concerned with the added value of this message. Hope someone can explain that to me.

**Comment by Fedik** [comment]
> I am wondering if the reason that people are not liking these messages is because their template design does not display such messages in a nice way

To be honest, in 99% our messaging system does not give any usefull information for avarage visitor. To them it is a distracted information, spam. Many admins just hides this block in their templates.

By looking how much comment this thread got we should consider to add the switch. Even though we do not like to introduce "params" for every "little thing"

> @sandewt  The question is what is wisdom in this case?

Add the params as in your original PR, where login/logout message is disabled by default, as it was in 4.2.

That what I think.

**Comment by sandewt** [comment]
@Fedik Thank you for your comment.

> To be honest, in 99% our messaging system does not give any usefull information for avarage visitor.

Agree.

> Add the params as in your original PR, where login/logout message is disabled by default, as it was in 4.2.
But as 1 switch (to switch both Login/Logout), instead of 2.

Disabled by default is also my preference. And accept the b/c in this case because J4.3 is just out. There are more pros than cons, judging by the comments.
The use of 1 switch is a good and creative compromise.

> as it was in 4.2

Should be J4.3

**Comment by Stevec4** [comment]
Another vote to provide a switch or turn it off by default.
@sandewt I installed your original PR and it works perfectly.

**Comment by sandewt** [comment]
>  I installed your original PR and it works perfectly.

Doesn't seem wise to me, before you know it, you're using outdated software. Or the software will be overwritten with the next update.
_The advice is to make a language override._

**Comment by Stevec4** [comment]
Not to worry it is a test server with the 4.3.1 RC . Just want to see if it worked.

**Comment by rmuzzini** [comment]
i totally agree with @irathers, @Pinkeltje, @Fedik, @Stevec4…
Nobody expects this "feature".
please, turn it off or give us an option to disable it, at least.

**Comment by alikon** [comment]
please test https://github.com/joomla/joomla-cms/pull/40531
