### ISSUE TITLE
Cannot click the checked button in the overrides checker

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#40463]
### Steps to reproduce the issue
https://youtu.be/f7oju7wbvDw

Go to overrides checker.
Make sure there are overrides to check.
Click on the "checked" icon.
It says no file found.

### Expected result
It should use the file next to the check button.

### Actual result
It says no file found.
You can click the checkbox and then use the menu to mark the item as checked but you cannot click the check box and use the icon.

### System information (as much as possible)
[systeminfo-2023-04-23T12_40_26+01_00.txt](https://issues.joomla.org/uploads/1/f55d2cc2c4fd0881c033f797ac82dc6b.txt)

**Comment by brianteeman** [comment]
Duplicate report of a known and now fixed issue.

**Comment by richard67** [comment]
Closing as duplicate report.

This issue has already been reported here https://github.com/joomla/joomla-cms/issues/40393 and fixed with this PR: https://github.com/joomla/joomla-cms/pull/40397 .

The PR is ready to commit. I think the release leads will include that not into the next 4.3.1 but into 4.3.2. @obuisard Please check and confirm.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40463">issues.joomla.org/tracker/joomla-cms/40463</a>.</sub>
