### ISSUE TITLE
Design fix in menu position in admin template

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#40482]
### What needs to be fixed
The design of modules added in the menu position in the admin template.
Please see the images before and after below.

https://demo.impression-estudio.gr/_issue-tracker/administrator-module-positions-before.png 
https://demo.impression-estudio.gr/_issue-tracker/administrator-module-positions-after.png

### Why this should be fixed
Bad design and usability problem. The buttons are touching each other and the drop down menu is unreadable.

### How would you fix it
I think it is easy for the creator of the template to add some CSS code based on the rest template in order to make this area look good.

### Side Effects expected
No side effects.

**Comment by HLeithner** [comment]
Hi @impressionestudio is can already be done by changing the module position form "status" to menu". since the core doesn't ship a "clear cache" and "JCH" it's up to you or the developer to position the module at the best fitting place.

We see the problem that the space in the statusbar is limited, so we are very selective before adding new modules to this position.

I close this ticket because you can solve it your self.

**Comment by brianteeman** [comment]
@HLeithner you misunderstand the request. The request is NOT that these items are moved by default. The request is that the styling applied to the modules is not great when they are moved to anywhere other than the status bar and that this styling should be fixed
