### ISSUE TITLE
Cassiopeia template does not load mata tag robots

### ISSUE THREAD

**Issue by oleksand** [joomla/joomla-cms#40549]
### What needs to be fixed
I don't see meta name="robots" loaded

**Comment by brianteeman** [comment]
It is only present when it is not the default of index, follow

![image](https://user-images.githubusercontent.com/1296369/236607623-a4851cd3-94f8-44e0-9a1a-604a8ce3eafe.png)

**Comment by richard67** [comment]
@oleksand Could you check the previous comment and report back if the robots meta tag is shown when you adjust it to anything else than the default "index, follow"?

**Comment by richard67** [comment]
Closing as expected behaviour. See previous comment https://github.com/joomla/joomla-cms/issues/40549#issuecomment-1537068081 for details. Feel free to reopen if you think this is wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40549">issues.joomla.org/tracker/joomla-cms/40549</a>.</sub>
