### ISSUE TITLE
Unexpected message on template admin.

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#40666]
### Steps to reproduce the issue

Install a child template without any media files.
Why? In real world unlikely, but when developing/testing!

Goto template admin page
.../administrator/index.php?option=com_templates&view=templates/...

### Expected result

Normal behaviour.

### Actual result

Get unexpected error message.
The template folder is not writable. Some features may not work.

### System information (as much as possible)

PHP 8.2

### Additional comments

Discovered when testing pull request:

https://github.com/joomla/joomla-cms/pull/40665

**Comment by BrainforgeUK** [comment]
Easy to fix, but if the media folder does not exist should it automatically create it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40666">issues.joomla.org/tracker/joomla-cms/40666</a>.</sub>

**Comment by dgrammatiko** [comment]
> Why? In real world unlikely, but when developing/testing!

Because the file manager for the templates WILL NOT allow users to create the media root folder for a template, it expects the folder to exist upon installation! The limitation comes from the outdated file manager. Also the only way Joomla exposes the creation of a child template is through the toolbar button, and there the media folder is created by default. So, the point is if you try to create child templates your way, better check the existing code in the templateModel and follow the same steps

**Comment by brianteeman** [comment]
The error message is completely correct. Without the media folder things will not work as expected

**Comment by BrainforgeUK** [comment]
Agree - see 'real world' comment above.

**Comment by brianteeman** [comment]
so why open an issue?

**Comment by brianteeman** [comment]
as I wrote there it is rediculous to think it is a good idea that if you write bad code that will not work that you are never told that it is bad code that will not work, Take a break, enjoy the sunshine and think about it.
