### ISSUE TITLE
Routing issue with conflict of submenu item and subcategory

### ISSUE THREAD

**Issue by keep** [joomla/joomla-cms#41146]
### Steps to reproduce the issue

- Create an article category: sport news
- Create a subcategory: basketball
- Create a tag: basketball-tag
- Create a category blog type menu item which points to sport news
- Create a 'tagged items' menu item, which points to basketball-tag and the alias is basketball and the parent is the sport news
- Create an article, where the category is sport news/basketball and the basketball-tag is assigned

### Expected result

When you open the basketball menu item and it lists the article, and you click the article title, Joomla should show the article content.

### Actual result

It doesn't show the content but lists the article list

### System information (as much as possible)

Demo site: https://tagtester.cloudaccess.host/
Joomla 4.3.2

### Additional comments

It might be a conflict of the submenu item alias and the subcategory alias of basketball

**Comment by mentalhacker** [comment]
This possible routing problem is quite a big issue.
We have a news portal, and we have several subcategories with submenu items, and we use tags for multiple categorization purposes.
This issue is really serious: the aliases of the corresponding subcategories and submenu items are identical. If the menu item is set to category blog type, this sameness doesn't cause any problem. But if you set the menu item to tagged items, the aliases come into conflict, and the routing mechanism collapses. But it shouldn't make any difference if you use categories or tags as the basis of menu items.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41146">issues.joomla.org/tracker/joomla-cms/41146</a>.</sub>

**Comment by Fedik** [comment]
I was able to reproduce only after looking on your site, 
the inctruction a bit confusing.

Addittional to the instruction. The final menu structure is:
```
- Sport news => category blog for "sport news"
-- Basketball => tagged items for "basketball-tag"
```

Then article `basketball-article` will have  the `/sport-news/basketball/basketball-article` url, and will open Tags list instead of detail.

**Comment by mentalhacker** [comment]
Thanks for the confirmation.
If it's really a bug, it's quite big (and annoying), so it's high time for the developers to address this issue.

**Comment by Hackwar** [comment]
It, too, took me some time to understand the whole issue and also the test-site to finally grasp this. However, I have to say that this is expected behavior or if you want that rephrased: A known limitation of our routing system. You created an identical route in 2 different components and in that case, the component with the best fitting (longest part of the URL matches with the menu item) menu item "wins". In your case, that is the com_tags component/router then, but that router doesn't know what to do with the "test-article" part. The only bug we have here is that the router does not throw a 404 for that URL as it actually should. The tagging has been improved in 4.3 quite a bit, but it will require additional work in the near future. In that additional change, I will fix the 404 issue, but besides that, this is not actually a bug.
