### ISSUE TITLE
[5.0] Update doc blocks

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41173]
As an **example**

There are 27 identical uses of `@link \JFilterInput::clean()` plus about 100 more variants

From my understanding this is wrong on at least 2 counts

1. `@link` is to display a hyperlink to a URL and it should be `@see`
2. `JFilterInput` should be `InputFilter`
3.  when there is **no** use statement for this then the fqn must be used or it simply doesnt work which as we now remove unuse use statements might have increased. 
4. afaict `@see` only works when it is on a new line

There is no point in having docs if they are not correct so I propose that these `@link` are updated as above and while it might not always be necessary to use the fqn it would make it more consistent 

So this would make 

```
     * @param   array    $urlparams  An array of safe url parameters and their variable types, for valid values see {@link \JFilterInput::clean()}.
```

```
     * @param   array    $urlparams  An array of safe url parameters and their variable types, for valid values
     * @see \Joomla\CMS\Filter\InputFilter::clean()
```

**Comment by HLeithner** [comment]
Since most of the occourence is in the `Controller::display` function which actually inherit the documentation of the base class, the question is if we should continue to keep the duplicated documentation or let the ide and phpdocumentor do this for us.

About the points.

1+4. yes make sense
2. Yes more or less al J-Prefixes have to be changed
3. normally the tools detecting unused `use` statements also understand that they are used in the docblocks.

**Comment by brianteeman** [comment]
closed - looks like i did this
