### ISSUE TITLE
Full text gets writtent into intro text

### ISSUE THREAD

**Issue by MayaSima** [joomla/joomla-cms#41201]
### Steps to reproduce the issue
Create a new article with only full text (no intro text)

### Expected result
The text gets written into `fulltext` database field

### Actual result
The text gets written into `introtext` database field

### System information (as much as possible)
Joomla 4.3.3
MySQL 8.0.33
PHP 8.0.29

### Additional comments
It seems this happened after the latest update to Joomla 4.3.3, but I am not sure.

**Comment by richard67** [comment]
> It seems this happened after the latest update to Joomla 4.3.3, but I am not sure.

This can not be, there is no difference between 4.3 and 3.10.

For 3.10 see https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/Table/Content.php#L135-L152 .

For 4.3 see https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Table/Content.php#L143-L156 .

I can confirm that it was always like that, as far as I can look back.

Closing as expected behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41201">issues.joomla.org/tracker/joomla-cms/41201</a>.</sub>
