### ISSUE TITLE
[5.0] schemaorg missing data or default values

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41252]
### Steps to reproduce the issue
1. Create an article - do not add a schema. Display the article in a single article menu item and make sure it is set to show the created date.  Check the values in the json+ld in the frontend
2. Edit the article - add some values to blogposting schema. Check the values in the json+ld in the frontend
3. Edit the article - add some values to the date fields in the bloposting schema

### Observed Results
1. "dateModified":"2023-07-26T07:27:37+00:00",   (kown bug that it says modified but thats not the issue being discussed here)
2. New schema data used but date fields now blank
3. Date fields now have the values from the schema

### Expected Results
Any field that has a fallback value should be used unless it is changed in the schema
The same can be observed with any field that has a fallback value

### Additional comments
Any schema field that has a matching field in the existing article fields should use those fields. Maybe pre-fill the field in the schema so I can edit them.
The important thing is that you shouldnt have to enter the same thing twice

**Comment by HLeithner** [comment]
The legacy/fallback plugin is not intended to work if a schema is selected in the article. That would be unexpected for the user and for us.

Autofilling is a thing we already talked about and how to solve it, so it's on the list but it's not so trivial as it sounds at a first glance. But I'm optimistic we solve it.

For example, pre-filling the fields doesn't work
* if you do it on opening the article (because new articles are not filled)
* Auto filling on save also has the problem that you can't make fields empty, which could be solved with additional input elements (not sure about ux here)
* Adapting with javascript if other fields changed, this could be a way but could also be problematic with 3rd party extensions

any ideas are welcome

**Comment by HLeithner** [comment]
The content plugin is a fallback if you don't use the schema.org implementation and is not for extending other schemas.

not sure what you suggest with the image, if you leave it blank then you can't leave it empty, what's if you don't want that a date is shown, or the author should not be shown in the json+ld data.

**Comment by brianteeman** [comment]
> The content plugin is a fallback if you don't use the schema.org implementation and is not for extending other schemas.

There is no **content** plugin. There is only the **system** plugin, as I said before, which makes no mention of it being a fallback AND it is required if you do use the schemaorg.

**Comment by HLeithner** [comment]
![image](https://github.com/joomla/joomla-cms/assets/1497730/8dd2e8de-5a6f-41d1-a38c-d600446a02d9)

This plugin adds the "article" schema as fallback if real schema.org types are not used.

**Comment by brianteeman** [comment]
Wow I would never have guessed it was there. Especially for contacts

**Comment by brianteeman** [comment]
So can you please confirm exactly what the minimum settings are for the fallback behaviour to be active

**Comment by brianteeman** [comment]
closed
