### ISSUE TITLE
[4] Remove guided tour on unwanted view

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#41273]
Actualy guided tour are configure to all views but it not necessary and that create a problem of priority for other component

Guided tour need to be activaed via good context

for now in my component i have this
![image](https://github.com/joomla/joomla-cms/assets/2539440/85943c52-5826-4da3-ae1c-1aeb81f9b81e)
user need to cllic on sall all tours to see the component tours
![image](https://github.com/joomla/joomla-cms/assets/2539440/cb1737f2-b54e-4e65-8525-8c4ac2dc1137)
the good behavior is to display guided tour in his context add home dashboard
![image](https://github.com/joomla/joomla-cms/assets/2539440/9b8d93c1-28e7-4769-8738-81d0c229317b)

**Result** 
in component
![image](https://github.com/joomla/joomla-cms/assets/2539440/6f25bbcb-ce7a-448c-bdd8-2022fe0332d8)
in dashboard
![image](https://github.com/joomla/joomla-cms/assets/2539440/9f04c9ac-6a9d-401c-a844-bbd982cfdce4)
in articles
![image](https://github.com/joomla/joomla-cms/assets/2539440/680b8eed-57d7-4457-b884-e32e727bd9f4)

i hope it can be corrected @obuisard

**Comment by obuisard** [comment]
Salut Yannick @micker, I actually am planning to write a PR that adds 'context' to the core tours, so that we can then more easily show/hide tours as you described. We could have all tours shown in the dashboard, but once in a specific component, like articles, just show the tours linked to articles.

**Comment by micker** [comment]
Great happy to help with test

**Comment by obuisard** [comment]
Wonderful, thanks Yannick, the PR will be linked to this issue once ready :-)

**Comment by brianteeman** [comment]
There is a potential accessibility issue with doing that. Navigation should always be predictable. In other words if you click on a button on screen one then it should do the same on screen 2

**Comment by wilsonge** [comment]
My understanding of that was always that on any given page the button should behave in a reproducible way. I don't understand what is accessible about going to a page and having the current component at the top of the results (as an example) in order to ensure that keyboard users don't have to scroll through long lists of items to find the component they are currently in.

**Comment by obuisard** [comment]
Related issue #40023

**Comment by brianteeman** [comment]
closed see #41303

**Comment by alikon** [comment]
closing as #41303 has been merged
