### ISSUE TITLE
 Media field type now encondes image metadata into the actual value #35871 

### ISSUE THREAD

**Issue by rambro** [joomla/joomla-cms#41373]
Hi all,

I think I am  having this problem with my DJ Image Slider extension for joomla 4.x. with the Cassiopeia template. When I select a picture it gives me this encoded metadata with the actual path of the file. For example:

**images/legionpics/veteranspark/vmemorial2 sized.jpg#joomlaImage://local-images/legionpics/veteranspark/vmemorial2 sized.jpg?width=607&height=520**

Anyway what is happening on the front end is I am not seeing the pictures in the slider. I see the arrow markings and the progression dots, but not the pictures. It is kind of frustrating. I don't know if this is the cause of it. 

DJ-ImageSlider (version 4.5.1)

Rick Ambrosino

https://merrickpost1282.org/index.php/veterans-park

**Comment by brianteeman** [comment]
Your issue is nothing to do with the extra data in the path. Accessed directly the image loads ok

https://merrickpost1282.org/images/legionpics/veteranspark/vmemorial2%20sized.jpg#joomlaImage://local-images/legionpics/veteranspark/vmemorial2%20sized.jpg?width=607&height=520

Your problem is that you have a missing script that the image slider needs.
https://merrickpost1282.org/media/djextensions/jquery.easing-1.4.1/jquery.easing.min.js

Closing as this is not a core issue and you should contact the developers of the image slider
