### ISSUE TITLE
[5.0 Beta 1] : Menu : PHP Deprecated:  Creation of dynamic property in\Controller\ItemController on line 540

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#41638]
### Steps to reproduce the issue
Create a new menu, enter a title, select Articles in menu item type, and select Single Article, select any existing article, and save the menu

### Expected result
No message in errorlog

### Actual result
PHP Deprecated:  Creation of dynamic property Joomla\Component\Menus\Administrator\Controller\ItemController::$type is deprecated in D:\laragon6-------------\www\j5beta\administrator\components\com_menus\src\Controller\ItemController.php on line 540

### System information (as much as possible)
PHP 8.2, Joomla 5.0 beta 1, Windows 11, Laragon

**Comment by chmst** [comment]
On a fresh installation of 5.0.0 beta1 I cannot repliate your error. 
Did you update a site? How? Are you using extensions on you site?

**Comment by HLeithner** [comment]
Actually we have the line which case this problem and it looks like that this variable assignment is useless...

https://github.com/joomla/joomla-cms/blob/aa52c06a408f6b6ca06abd0c0cb790e6dbb0b355/administrator/components/com_menus/src/Controller/ItemController.php#L540

I have to check if we still needed but at a quick look I didn't saw any usage of it, also because after it's set the application cycle ends with a redirect...

**Comment by HLeithner** [comment]
if you look at the commit when it was introduced it looks like an accident and could be removed safely.

https://github.com/joomla/joomla-cms/commit/18161975387ec9c58d173fe5c2718907134b55d2#diff-e96b71d95eddaefa97e2d88a0df59f875a5b55c4f76323eb1d70f831258769c3R359

@chmst can you create a PR please?

**Comment by alikon** [comment]
please test #41682
