### ISSUE TITLE
Deprecated: Automatic conversion of false to array is deprecated in HTMLHelper.php on line 795

### ISSUE THREAD

**Issue by heli63** [joomla/joomla-cms#41776]
### Steps to reproduce the issue
Hello, when I just updated my test-site to php 8.1 an get now this error message when I try to create a new module for the simple-social-media-stream of Asana Plugins

### Expected result
Creating a new module

### Actual result
This error: Deprecated: Automatic conversion of false to array is deprecated in HTMLHelper.php on line 795

### System information (as much as possible)
php 8.1.23, Joomla 4.3.4, mysql 5.7.40, Apache-Webserver

**Comment by ghazal** [comment]
Maybe you should inform asanaplugins.com of this error message. I have seen it posted by users (in other contexts) and, I would guess, according to where it is in HTMLHelper.php, it could be related to a badly coded call to a js file/script in the plugin. 
Php 8.1 is less tolerant than former versions.

**Comment by Fedik** [comment]
Please contact to the plugin developer to update their plugin.
The issue because the plugin uses old code that originaly was made for older joomla, wich have a diferent method call:
https://github.com/joomla/joomla-cms/blob/a4ba1df6b44c8041909ca0d952f93dfd792579b0/libraries/src/HTML/HTMLHelper.php#L676-L679

Thanks!
