### ISSUE TITLE
var_dump(ing) or print_r(ing) various Joomla variables exhausts PHP memory limit 

### ISSUE THREAD

**Issue by joomlabeat** [joomla/joomla-cms#41832]
Similar to #34531  

I have encountered this in a few occasions so far with Joomla4.
The last occurrence is on the category blog layout.
    `/components/com_content/tmpl/category/blog.php`
Trying to run `var_dump($this->category)` - it will never happen.
Memory is exhausted (I have raised the memory limit up to 4GB, just for testing).

It happens in other locations with other similar variables - only that I don't have them at hand right now.

But, also the article layout ... 
   `/components/com_content/tmpl/article/default.php`
   `var_dump($this);`

Will also produce the same.

### Steps to reproduce the issue
Add `var_dump($this->category)` in  `/components/com_content/tmpl/category/blog.php`

and try to load a category blog page.

### Expected result
The category blog layout + the output of the var_dump() command.

### Actual result
Fatal error: Allowed memory size of ...  bytes exhausted...

### System information (as much as possible)
Joomla 4.x versions - PHP 8x up to 8.1.x

**Comment by Fedik** [comment]
This is because you trying to `var_dump` a loot of data.
The reason you have many articles in category and category children. And so in result var_dump produce a huge output.

I am closing it, because it is not a joomla issue.

**Comment by smartmultimedia** [comment]
Respectfully disagree with "not joomla issue", because:   
(1) the issue did not exist in Joomla 3;   
(2)  this issue does exist in Joomla 4;   
(3)  it is not an environment / server issue -- it appears to be some sort of infinite recursion, so it doesn't matter how much memory PHP has available,  it will always fail with out of memory exception

This issue in it's various forms, sometimes makes debugging other issues painful.


**Replicate issue:**
```
$db = JFactory::getDBO();
print_r($db);
```

**Expected result:**
A standard result that you would expect from print_r() 

**Actual result:**
Allowed memory size of 536870912 bytes exhausted (tried to allocate 260050944 bytes)

-----

**Possible solution:**

Edit /libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php

Add this new "magic method" to the class:

```
	public function __debugInfo() {
		return [
			'connection' => $this->connection,
			'name' => $this->name,
			'nameQuote' => $this->nameQuote,
			'nullDate' => $this->nullDate,
			'utf8mb4' => $this->utf8mb4,
			'mariadb' => $this->mariadb,
			'dbMinimum' => static::$dbMinimum,
			'dbMinMariadb' => static::$dbMinMariadb,
			'serverType' => $this->serverType,
			'count' => $this->count,
			'cursor' => $this->cursor,
			'executed' => $this->executed,
			'limit' => $this->limit,
			'offset' => $this->offset,
			'options' => $this->options,
			'sql' => $this->sql,
			'statement' => $this->statement,
			'tablePrefix' => $this->tablePrefix,
			'utf' => $this->utf,
			'errorNum' => $this->errorNum,
			'errorMsg' => $this->errorMsg,
			'transactionDepth' => $this->transactionDepth
		];
	}

```
