### ISSUE TITLE
Route not generating friendly URLs for existing menu entries

### ISSUE THREAD

**Issue by apaulo** [joomla/joomla-cms#41897]
### Steps to reproduce the issue
Having the following menu entry:
ID: 524
Type: Articles->Create Article
Link: index.php?option=com_content&view=form&layout=edit

Execute: _echo Route::\_('index.php?option=com_content&view=form&layout=edit');_

### Expected result
- a SEF-friendly URL path according the Joomla menu structure (v.g. _/articles/add_).

### Actual result
- Un-friendly URL path: _/component/content/form?layout=edit&Itemid=101_ (Itemid 101 refers to the home menu entry).

### Additional comments
Execute _echo Route::\_('index.php?Itemid=524');_ and it returns the expected result

**Comment by robbiejackson** [comment]
This sort of thing seems to be a common problem, considering the number of recent related problems on Joomla stack exchange, eg:
- [Joomla 4: How to add a main menu item to the article?](https://joomla.stackexchange.com/questions/33371/joomla-4-how-to-add-a-main-menu-item-to-the-article "")
- [Short Url with FlexiContent Or Remove menu item alias from URL](https://joomla.stackexchange.com/questions/33366/short-url-with-flexicontent-or-remove-menu-item-alias-from-url "")
- [Joomla 4 - change in way URLs generated compared to Joomla 3](https://joomla.stackexchange.com/questions/33165/joomla-4-change-in-way-urls-generated-compared-to-joomla-3/33261#33261 "")

I believe that at least part of the problem stems from the router `preprocess()` function which (as far as I can see) doesn't attempt to find the best match between
- the view/layout etc parameters in the `Route::_()` call and
- the associated view/layout etc parameters in the menuitem.
  
In other words it seems to go with an `Itemid` if the component associated with the menuitem matches the `option=` parameter of the `Route::_()` call, but doesn't seek to match on other parameters such as `view` or `layout`. Those other parameters then need to get included by adding them as query parameters to the URL instead.

I think that it's important that SEF URLs are not only functional (in that they get you to the right page), but also aesthetically pleasing (rather than looking awkward with additional `&view=...&layout=...` parameters, which in this case could be avoided if the best menuitem was chosen). 

(The router has changed from Joomla 3 to Joomla 4 in this area, and it has caused some issues for people who have had printed material produced which quoted the old URLs, or links from other sites. And there doesn't seem to be any Joomla configuration that can maintain the previous URLs, or govern what gets generated as the SEF URL.) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41897">issues.joomla.org/tracker/joomla-cms/41897</a>.</sub>

**Comment by Hackwar** [comment]
Can you check if #42989 improves this for you? It wont entirely fix it, but provide a slight improvement hopefully.

**Comment by Hackwar** [comment]
Since we have #42989, I'm closing this issue.
