### ISSUE TITLE
[all] Pre-Update check not working?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42118]
### Steps to reproduce the issue
On a joomla 4.4 site set the update server to https://update.joomla.org/core/nightlies/next_major_list.xml

Install a variety of extensions and run the pre-update check

![image](https://github.com/joomla/joomla-cms/assets/1296369/c8e6d9f5-cdd9-4a10-803a-5167d3661a57)

targetplatform name="joomla" version=".*" (rsform)
targetplatform name="joomla" version="((4)|(5\.(0|1|2|3|4|5|6|7|8|9)))" (dpattachments)

![image](https://github.com/joomla/joomla-cms/assets/1296369/51e418b6-2db3-49a6-aab9-750261a4de49)

targetplatform name="joomla" version="((3\.(10|11))|(4))" (dpcalendar)
targetplatform name="joomla" version="((3\.(8|9|10|11))|(4\.(0|1|2|3)))" (acf)

### Issue
No matter what I try I cant see a way for me to declare that an extension is NOT compatible with joomla 5

Is that not supported?
If it is supported what is the way to declare an extension as not compatible with joomla 5 in the update checker.

for example I hjave some tinymce 5 based plugins that will crash joomla 5 as it uses tinymce6 and I would expect there to be a way for me to mark the extension as not compatible and should be removed before update

**Comment by rabidgrowth** [comment]
Me too! Your problem is one problem from two I come here to say.

I make small plugins for clients. I putted targetplatform="(4.(1|2|3|4|5|6|7|8|9|10))". I copy this trick from JCE, heh. Your problem happen for me also with joomla 4.4. He says "update information unavailable". Not can stop clients upgrade to joomla5. If they upgrade, boom.

Hope he fix before joomla6.

**Comment by richard67** [comment]
If an update is compatible or not is determined by the targetplatformversion of the update site’s extension.xml. There is no way for the user to change something on that.

**Comment by brianteeman** [comment]
> If an update is compatible or not is determined by the targetplatformversion of the update site’s extension.xml.

That is the entire point of this. There is no way to say an extension is **NOT** compatible in the  update site’s extension.xml

**Comment by alikon** [comment]
> There is no way to say an extension is NOT compatible in the update site’s extension.xml

let me disagree

there is already , i mean instead of "No Comaptibility information" -> "**Not Compatible**"

**Comment by brianteeman** [comment]
Please show me how to do that as I have tried everything I can think of

**Comment by PhocaCz** [comment]
Please see: https://joomlacommunity.cloud.mattermost.com/main/pl/1qi7njmwmf8h9ku8p4t8jo9m5w

**Comment by PhocaCz** [comment]
Copied from the discussion: 
Please take the following with a grain of salt as it is based on total ignorance of the update process.

If I understood correctly, we would need three results instead of two.

At the moment everything is probably checked via the preg_match function and it returns only two possible results: True or False. So, if the check is: 4.[01234]|!5.* (and for the sake of example we take that condition as valid), then False will be valid for two variants:

FALSE:
(a) the number was not found (4.[01234])
(b) the number is found, but we want the opposite, to exclude it (!5.*)
TRUE:
(a) the number was found

and since the PHP function only fractions TRUE/FALSE, one extra condition would have to be split into two. In the case of false, it would still check whether the version was not found or was found and marked for exclusion. This is a difficult task to get information from the regex about whether it returned false because it didn't find the version, or because it did find it but it was marked for exclusion. Because it returns true or false.

One could simplify everything with the **targetplatformexclude** parameter. Probably the condition should be tested before **targetplatform**.
