### ISSUE TITLE
Please help! Half of my websites crashed when updating to 4.4.0

### ISSUE THREAD

**Issue by maggus** [joomla/joomla-cms#42154]
### Steps to reproduce the issue

- I have updated 18 websites from 4.3.4 to 4.4.0.
- A third of my websites crashed when updating them (on different servers!)
- Most of them are not accessible any more. I cannot login into the backend. And I get no error message. Purging the cache does not help.
- When trying to re-install the Core Files on Joomla's Standard Update server, it tells me I have version 5.0.0 installed! What is going on???

I really could cry as I have to recover nearly 18 websites for my customers. The one manual update I have made was working fine, but all other updates made with mysites.guru's core mass install function did crash. This has never happened before.

**Comment by joeforjoomla** [comment]
Confirmed!

Updating from 4.3.4 goes directly to 5.0.0 and not to 4.0.0. The result is that the compatibility plugin is not enabled and the website totally crashes. Damn.

**Comment by brianteeman** [comment]
Just to confirm then, the updates that all failed were not done with the joomla update component but by a closed source third party service.

**Comment by brianteeman** [comment]
The same service that has boasted about how many sites it has updated to 4.4 <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Over 200 <a href="https://twitter.com/hashtag/Joomla?src=hash&amp;ref_src=twsrc%5Etfw">#Joomla</a> 4.3.4 to Joomla 4.4.0 upgrades done by <a href="https://t.co/PdOzJbZMh9">https://t.co/PdOzJbZMh9</a> subscribers so far... and more pending... <a href="https://t.co/QBa2fVPZq8">pic.twitter.com/QBa2fVPZq8</a></p>&mdash; mySites.guru - The single dashboard for Joomla/WP! (@mysitesguru) <a href="https://twitter.com/mysitesguru/status/1714341787421069644?ref_src=twsrc%5Etfw">October 17, 2023</a></blockquote> 

And that you will not be able to upda5te to joomla 5 with that service
<blockquote class="twitter-tweet">For that reason, you cannot use <a href="https://t.co/PdOzJbZMh9">https://t.co/PdOzJbZMh9</a> to &quot;upgrade&quot; between the series when Joomla 5 is released.</p>&mdash; mySites.guru - The single dashboard for Joomla/WP! (@mysitesguru) <a href="https://twitter.com/mysitesguru/status/1709294507500438007?ref_src=twsrc%5Etfw">October 3, 2023</a></blockquote>

**Comment by maggus** [comment]
When clicking the re-install button in the Joomla! Update component it updates to 5.0.0 instead of re-installing 4.4.0. This happens without any third party service like mysites.guru.

**Comment by maggus** [comment]
I can't say what is the problem. But yes, I have used a third party service. What makes me really wondering that I cannot login into the backend - and no error is reported. I even cannot log out when being logged in before the update.

**Comment by ToxicTeemanIsWrong** [comment]
To replicate Joomla's Bug USING JOOMLA ONLY :

1. upgrade to Joomla 4.4.0 using com_joomlaupdate - you are now running Joomla 4.4.0
3. return to Joomla Update and Click Check for updates 
4. and then REINSTALL Joomla Core files button - Joomla then installs Joomla 5.0.0 !!!!! 

This is 100% a Joomla bug and NOTHING TO DO WITH [The service that is not allowed to be named!]

This is 100% a Joomla 4 bug and can be produced with Joomla Admin Console alone - without any third party code installed at all. 

![F8rIZ2tXQAAmaY_](https://github.com/joomla/joomla-cms/assets/148289132/bead2be2-d7c9-42d2-8a27-6179948494f3)

**Comment by ToxicTeemanIsWrong** [comment]
So https://update.joomla.org/core/sts/extension_sts.xml - The DEFAULT Joomla Update Source has a section 

```
<update>
<name>Joomla! 5.0</name>
<description>Joomla! 5.0 CMS</description>
<element>joomla</element>
<type>file</type>
<version>5.0.0</version>
<infourl title="Joomla 5.0.0 Release">
https://www.joomla.org/announcements/release-news/5900-joomla-5-0-and-joomla-4-4-are-here
</infourl>
<downloads>
<downloadurl type="full" format="zip">
https://downloads.joomla.org/cms/joomla5/5-0-0/Joomla_5.0.0-Stable-Update_Package.zip
</downloadurl>
<downloadsource type="full" format="zip">
https://github.com/joomla/joomla-cms/releases/download/5.0.0/Joomla_5.0.0-Stable-Update_Package.zip
</downloadsource>
<downloadsource type="full" format="zip">
https://update.joomla.org/releases/5.0.0/Joomla_5.0.0-Stable-Update_Package.zip
</downloadsource>
</downloads>
<tags>
<tag>stable</tag>
</tags>
<supported_databases mysql="8.0.13" mariadb="10.4" postgresql="12.0"/>
<php_minimum>8.1.0</php_minimum>
<sha256>
c9b1c03befbfe4c953140ef35972495c83d6df7dde01b446af8cbe01189d4b04
</sha256>
<sha384>
dfee7f6c8ccf009bd5e601abe87a2937c9bb0afc2767b00f734b45adcaaa7382502e7b27c08def840e501a5f9ba52f8c
</sha384>
<sha512>
d3f773ea94dd2de33d8fa3e9909c57e6bb5966daa54df02cb6426c823e77bf12d73fa05d92b365db8df4b1bbd98ea4993bec10eb8b3f8557d6aa544e497cda05
</sha512>
<maintainer>Joomla! Production Department</maintainer>
<maintainerurl>https://www.joomla.org</maintainerurl>
<section>STS</section>
<targetplatform name="joomla" version="4.4.0"/>
</update>
```

Note that its targeting 4.4.0:

`<targetplatform name="joomla" version="4.4.0"/>`

- and delivers Joomla 5.0.0 to it... funny that... 

**Again totally unrelated to mySites.guru !**

**Comment by richard67** [comment]
The update channel in the Joomla Update component, was that set to „Default“? Or to „Next“? We have an issue with the update site, but as far as I can see only on the „Next channel“.

**Comment by ToxicTeemanIsWrong** [comment]
It was set to Default. Every test of mine is a clean install of Joomla. I also manually checked it was set to default before every test.

**Comment by richard67** [comment]
P.S.: Confirmed that it has nothing to do with mySites.guru. It must be some mistake with our update site.

**Comment by richard67** [comment]
> It was set to Default. Every test of mine is a clean install of Joomla. I also manually checked it was set to default before every test.

Thanks for checking. We continue to investigate. Sorry for the inconvenience.

**Comment by ToxicTeemanIsWrong** [comment]
![F8rVD_KW4AELHg1](https://github.com/joomla/joomla-cms/assets/148289132/e3bacfcc-019c-4dc8-ada4-5606baa469c5)

And with that confirmation - I shall leave you and your project alone again.

**Comment by HLeithner** [comment]
I temporary remove it from the update server, you can still download the joomla 5 update package from downloads.joomla.org and manually install it (after you updated your site to 4.4.0). I would expect that we will solve this issue tomorrow.

**Comment by ToxicTeemanIsWrong** [comment]
Just to confirm, for those reading, - after your change to the update streams just now - it's currently now impossible to "reinstall" the Joomla 4.4.0 files over the top of Joomla 4.4.0 as a side effect. 

After clicking check for updates on an already Joomla 4.4.0 you are given no update and no option to reinstall the Joomla 4.4.0 files. 

I do understand this is a side effect of what you have done temporarily but maybe others reading this overnight, would not.

**Comment by richard67** [comment]
No, reinstall core on 4.4.0 should work now and result in 4.4.0, update from 4.4.0 to 5.0 will work too when you change Update channel to „Next“. What was removed was the update within the 5 version which is not relevant yet and so was removed. It will be needed later when 5.0.1 will come.

**Comment by ToxicTeemanIsWrong** [comment]
Then you have another bug to fix, because right now, since @HLeithner change, it's IMPOSSIBLE to get the "Reinstall core files" button to show up on a Joomla 4.4.0 website.

**Comment by HLeithner** [comment]
Yes thats a side effect, you can download the update file from downloads.joomla.org and upload it if you need to.if the update Blocks the Version you can try to rename the file or uploade the files by Hand. But tbh using a backup you did before the 4.4.0 update is a safer approach

**Comment by ToxicTeemanIsWrong** [comment]
> No, reinstall core on 4.4.0 **should work now** and result in 4.4.0, 

Doesn't. Before @HLeithner change it would install 5.0.0 - after the change it now doesnt allow reinstall of core files at all. You click Check for updates and it says no updates available, and gives the check for updates button again - and not the reinstall core files button. 

> Update from 4.4.0 to 5.0 will work too when you change Update channel to „Next“.

Also doesnt. 

![ScreenShot-2023-10-18-00 37 01](https://github.com/joomla/joomla-cms/assets/148289132/e74b7bba-6b5f-4794-9951-5ab45c2cfeec)


> Yes thats a side effect,

Which is what I was trying to communicate but @richard67 disagrees and says it should work as he has described. 

I dont know if he has even tested, but Im sat here with a clean site and neither of the things he says should still be possible, are. 

Maybe the "now" in his sentence means "you should be able to do these things once the bugs are fixed" rather than "you should be able to do these things now, despite the change to the update stream that allows us all to go to bed and deal with this issue tomorrow" who knows. 

The fact is "now", right now at 23:38UTC, neither of these things are possible - temporarily - until the underlying bugs are fixed

**Comment by gesellea** [comment]
deleting administrator/cache/autoload_psr4.php does not allow me to log back in to affected sites, and I really do not want to restore a backup unless really needed, can I do something else to help you guys get to the bottom of this?

**Comment by woluweb** [comment]
same as @gesellea here: 20+ website where I can't login any more in the backend (page simply refreshes but if I type a wrong login/password then it says it)

**Comment by ToxicTeemanIsWrong** [comment]
I’m just waking up

Send me the sites ftp using https://fix.mysites.guru/now and I’ll take a look for free at any broken site you upgraded with mySites.guru - however, the update is not done by mySites.guru, but by the Joomla core update code, using the update path provided by Joomla - all mySites.guru does is call internally the Joomla com_joomlaupdate classes without needing to login.

MySites customers always get FREE support when major issues occur - you two know that. I'll design a downgrade process in the next few hours but I need some reference sites. Ay resultant tool will be provided with the world to fix their sites. 

I can see from our logs that you both used the mass upgrade tool to upgrade to Joomla 4.4.0 - and then you used the same mass upgrade tool and selected the same sites AGAIN which forced a reinstall of the 4.4.0 files (well it would normally) but because of the bug in the Joomla Update Sites, the Joomla 5.0.0 files were delivered from the Joomla Update Streams instead of Joomal 4.4.0 (as described earlier in this bug report) and this is what has upgraded your sites incorrectly to Joomla 5.

If you had not selected to mass upgrade the sites a second time, then you would not have destroyed the sites. The logs show that you selected the sites a second time. This is also why some customers have issues on a subset of their sites - it will only be the sites they triggered the update TWICE  on. 

<img width="481" alt="Screenshot 2023-10-18 at 07 41 54" src="https://github.com/joomla/joomla-cms/assets/148289132/c2036e67-b826-4b61-9d75-79d1deeb25c9">

The mySites.guru relationship in this thread is simply that you selected the sites a SECOND time from the mass upgrade list, and mass upgraded them - which before, would have reinstalled the same version over the top, but because of the bug in Joomla, your sites were upgraded to Joomla 5.0.0. If the bug with the update streams were not there, mySites.guru would have done what it has done for over a decade - and replaced core files like for like from the same version. 

You would have had the same problem if you had updated the site, and then used the reinstall core files feature in Joomla admin without the use of a third party service. Unfortunately the third party service just made it easier for you to trigger the updates and several people (yesterday and historically) just blindly select all the available sites in the list without looking at the upgrade path presented.

To confirm - late last night I removed the feature to "reinstall core files" from mySites.guru so no one else can fall foul of this Joomla bug.

**Comment by gesellea** [comment]
I only did a couple sites, I could wait until a definite fix?

I will send at least one site, so you could check it out ...

Op wo 18 okt 2023 om 08:51 schreef ToxicTeemanIsWrong <
***@***.***>:

**Comment by MyInputIsNotValued** [comment]
So @ToxicTeemanIsWrong has been banned from contributing the same way @PhilETaylor was - **the Joomla Projects Loss** - as we have all the data they need, and without us they would still be ignoring the fact this is a bug in Joomla and would still be clueless. 

I will not sit around and have Joomla Founders sang off and deflame me... 

oh well. 


<img width="532" alt="Screenshot 2023-10-18 at 08 21 41" src="https://github.com/joomla/joomla-cms/assets/148320248/2ac32d5b-7c1c-4023-87c1-10351683caf3">

**Comment by MyInputIsNotValued** [comment]
and now you have deleted all the VALUABLE INPUT THAT WAS PROVIDED FOR FREE - now Joomla users have no FACTUAL information.... great one Joomla - you suck!

**Comment by MyInputIsNotValued** [comment]
oh but I see you left Toxic Teemans personal attacks against mySites.guru service..... funny that - protecting your own again... despite the huge number of issues Toxic Teeman creates the project - fully that...

**Comment by gesellea** [comment]
> Phil you are banned from the project and with your behaviour today you showed that this was a right and good decision. Your input was always valued but you personal behaviour not.

I do not agree that this is the correct way, without Phil I would have switched to Wordpress a long time ago, don't block somebody who is so valuable for the community simply because you don't like them!

You cannot argue that Joomla hasn't always been the most stable platform, but because of Phil we were always able to find a solution. Without him, I will think twice about installing a new Joomla instance!

**Comment by gwstyles** [comment]
I agree with gesella, the project is constantly calling for volunteers and one of the most valuable you ban, its crazy.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42154">issues.joomla.org/tracker/joomla-cms/42154</a>.</sub>

**Comment by richard67** [comment]
What else shall we do if someone is permanently violating our code of conduct?

**Comment by cybersalt** [comment]
@woluweb Did you do a mass update through mysites.guru? If so, mysites will fix it for you as a client. Just submit a work request after logging in.

**Comment by brianteeman** [comment]
I can see the bug but I am still trying to understand why you would have tried to do the update twice.

**Comment by cybersalt** [comment]
> What else shall we do if someone is permanently violating our code of conduct?

We all know of others who regularly violate the code of conduct and are not banned. I'm not interested in getting into "it" with anyone, but some very large and unhealthy personalities have turned Joomla into a hostage situation for a lot of us  - to the point where we avoid eye contact so we don't get shot.

**Comment by rdeutz** [comment]
> We all know of others who regularly violate the code of conduct and are not banned. I'm not interested in getting into "it" with anyone, but some very large and unhealthy personalities have turned Joomla into a hostage situation for a lot of us - to the point where we avoid eye contact so we don't get shot.

We are trying to fix this. 

Some people give good input and help, but on the other side they are being unfriendly. I can handle that but new people run away. So the question is: Is the total effect more positiv or negativ? It is not a question if I like someone or not.

**Comment by SniperSister** [comment]
> I guess you have to strike a balance between having brilliant coders with no social skills or not.

Coding is not just about writing code, it's about understanding requirements, weighting pros and cons of solutions for different user groups, handling criticism and suggestions – or simpler: it's about communication. Social skills aren't optional, they are a vital part of the job.

**Comment by formfranska** [comment]
> Some people give good input and help, but on the other side they are being unfriendly. I can handle that but new people run away. So the question is: Is the total effect more positiv or negativ? It is not a question if I like someone or not.

So I'm not a coder at all but I've read enough threads that I think I can understand that Phil is an incredible resource. I'm not a coder but I'm also a person that is probably referred to as someone lacking social skills (at least sometimes 😉).

What scares me more than anything else is when people are being silenced. This happens in too many communities and societies i m h o. I think that could also make "new people run away".

**Comment by gwstyles** [comment]
I completely understand your point of view. I just don't think banning is the solution, there are two really good coders banned I know of and they have both found and fixed many of the update problems before we even know of them in the past and to loose that is a shame.

**Comment by brianteeman** [comment]
Please share the contents of the update log. That is the key to everything

**Comment by woluweb** [comment]
> Please share the contents of the update log. That is the key to everything

This is all I have in `/administrator/logs/joomla_update.php` (not truncated). The same on the 2 sites I have just fixed. I guess the same for all my other sites concerned.

```
#
#<?php die('Forbidden.'); ?>
#Date: 2023-10-17 20:57:56 UTC
#Software: Joomla! 4.4.0 Stable [ Pamoja ] 17-October-2023 16:00 GMT

#Fields: datetime	priority clientip	category	message
2023-10-17T20:57:56+00:00	INFO 178.62.5.35	update	COM_JOOMLAUPDATE_UPDATE_LOG_FINALISE
2023-10-17T20:57:56+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_SQL_BEGIN
2023-10-17T20:57:56+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_SQL_BEGIN_SCHEMA
2023-10-17T20:57:56+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_UPDATE_LOG_QUERY
2023-10-17T20:57:56+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_UPDATE_LOG_QUERY
2023-10-17T20:57:56+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_SQL_END
2023-10-17T20:57:56+00:00	INFO 178.62.5.35	update	COM_JOOMLAUPDATE_UPDATE_LOG_DELETE_FILES
2023-10-18T05:28:04+00:00	INFO 178.62.5.35	update	COM_JOOMLAUPDATE_UPDATE_LOG_FINALISE
2023-10-18T05:28:04+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_SQL_BEGIN
2023-10-18T05:28:04+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_SQL_BEGIN_SCHEMA
2023-10-18T05:28:04+00:00	INFO 178.62.5.35	update	JLIB_INSTALLER_SQL_END
2023-10-18T05:28:04+00:00	INFO 178.62.5.35	update	COM_JOOMLAUPDATE_UPDATE_LOG_DELETE_FILES
```

**Comment by brianteeman** [comment]
Possible brainwave. 
The logs should be much bigger than that and not with language keys for the message. I am therefore making a leap to say that the update was done using the cli updater and that is where the bug lies. Both in terms of you not being able to log in after update AND the faulty log file

**Comment by WrongAgain221** [comment]
` I am therefore making a leap to say that the update was done using the cli updater and that is where the bug lies.`

Wrong.

178.62.5.35 is the mySites.guru IP address. This update was conducted with the mySites.guru service as evidenced by that IP address. mySites.guru chooses not to translate strings. 

This issue is a different issue to Joomla 4.4.0 "Reinstall Core Files" delivering Joomla 5.0.0 files which is a confirmed non-mySites.guru issue and can (could be, before the update sites xml was changed) replicated without any third party service.

**Comment by peterwouda** [comment]
> Let's focus on the issue raised by @maggus and also experienced at least by @gesellea and myself. I am speaking here of sites which were upgraded to Joomla 4.4 and where you cannot login in the backend any more (the page just reloads).
> 
> [ Note: some people had suggested that this might be because the website would have already migrated to 5.0.0, but that was _not_ the case, at least for my own cases ]
> 
> A long story short, here is the easy fix if you can't login any more in tha backend after the Update:
> 
>     * download the Upgrade Package (not the Full Package) from https://downloads.joomla.org/cms/joomla4/4-4-0 and put it at the root of your site. If you are in the Console, the command is
>       `wget https://downloads.joomla.org/cms/joomla4/4-4-0/Joomla_4-4-0-Stable-Update_Package.zip`
> 
>     * unzip it. If you are in the Console the command is
>       `unzip Joomla_4-4-0-Stable-Update_Package.zip`
> 
>     * only then delete `/administrator/cache/autoload_psr4.php` (don't worry, that file gets re-generated automatically)
> 
> 
> PS: most probably the root cause was that all files were not unzipped properly during the initial Update process

This works great in my situation! Thanks for sharing @woluweb

**Comment by bembelimen** [comment]
See the [Upgrade FAQ](https://docs.joomla.org/Category:Version_4.4.0_FAQ)

**Comment by ernienet** [comment]
> Let's focus on the issue raised by @maggus and also experienced at least by @gesellea and myself. I am speaking here of sites which were upgraded to Joomla 4.4 and where you cannot login in the backend any more (the page just reloads).
> 
> [ Note: some people had suggested that this might be because the website would have already migrated to 5.0.0, but that was _not_ the case, at least for my own cases ]
> 
> A long story short, here is the easy fix if you can't login any more in tha backend after the Update:
> 
> * download the Upgrade Package (not the Full Package) from https://downloads.joomla.org/cms/joomla4/4-4-0 and put it at the root of your site. If you are in the Console, the command is
>   `wget https://downloads.joomla.org/cms/joomla4/4-4-0/Joomla_4-4-0-Stable-Update_Package.zip`
> * unzip it. If you are in the Console the command is
>   `unzip Joomla_4-4-0-Stable-Update_Package.zip`
> * only then delete `/administrator/cache/autoload_psr4.php` (don't worry, that file gets re-generated automatically)
> 
> PS: most probably the root cause was that all files were not unzipped properly during the initial Update process

YAY! I followed the steps and it worked perfectly - I just have to do this for 18 more sites and they'll all be fixed.

**Comment by gesellea** [comment]
can confirm that this works, and I only have 2 sites where I do not have SSH :-p (hosted by the client), but at least we have some way to fix it quickly...

**Comment by woluweb** [comment]
> can confirm that this works, and I only have 2 sites where I do not have SSH :-p (hosted by the client), but at least we have some way to fix it quickly...

Well, if you don't have SSH (or a good file manager by the host) then indeed it takes ages to upload an *unzipped* package.

In such a case, I do the following: I upload the ZIP file and then use a little script to **unzip**.

There are probably plenty out there but personally I use the one written by the founder of my Joomla User Group, ie @cavo789 : https://github.com/cavo789/zip_unzip

**Comment by gesellea** [comment]
excellent tip, thank you !

**Comment by alikon** [comment]
i believe that this issue can be closed now
