### ISSUE TITLE
DB-tables not updated whem upgrading to 4.4.0

### ISSUE THREAD

**Issue by dsimonse** [joomla/joomla-cms#42205]
### Steps to reproduce the issue
Just upgraded to Joomla4.4.0 from 4.3.4 and the DB-version/DB-updateversion don't match the new version.![screen shot 2023-10-23 at 04 21 13](https://issues.joomla.org/uploads/1/6e2bf64e7db8111626a61e4d8216dca1.jpg)

### Expected result
That the DB-tables should reflect the new version

**Comment by richard67** [comment]
@dsimonse How did you perform the update? Have you used the Joomla Update component?

**Comment by dsimonse** [comment]
Hi Richard,

 

I didn’t use the Joomla update-component since it was not working.

I installed ”Joomla_4.4.0-Stable-Full_Package.zip”

 

//Dennis

 

Från: Richard Fath 
Skickat: den 23 oktober 2023 11:26
Till: joomla/joomla-cms ***@***.***>
Kopia: dsimonse ***@***.***>; Mention ***@***.***>
Ämne: Re: [joomla/joomla-cms] DB-tables not updated whem upgrading to 4.4.0 (Issue #42205)

 

@dsimonse <https://github.com/dsimonse>  How did you perform the update? Have you used the Joomla Update component?

**Comment by richard67** [comment]
@dsimonse What means the Joomla Update component was not working? Do you have any error message or the update log "administrator/logs/joomla_update.php" from the trial with the update component?

And what means `I installed ”Joomla_4.4.0-Stable-Full_Package.zip”`? You've just unpacked that package? This package is only for new installations and not for updates, and unpacking a zip without using the Update Component will for sure not start the database updates to run.

All I know up to now looks to me as expected behaviour. You cannot update without using the Joomla Update component or Joomla CLI. For how to correctly update using the Joomla Update component see https://docs.joomla.org/J4.x:Updating_from_an_existing_version .

Closing as expected behaviour.

For the "Joomla Update component was not working" please open a new issue if it doews not work as described in the referred document, with details like e.g. the content of the "administrator/logs/joomla_update.php" file. Thanks in advance.

**Comment by richard67** [comment]
P.S.: I hope you have made a backup before you made the update. If so, please revert to that backup and proceed the update as described in the doc linked in my previous comment. Otherwise, if you do not have a backup,m you have to run the SQL statements from the update SQL scripts `administrator/components/com_admin/sql/updates/mysql/4.4.0-2023-05-08.sql` and `administrator/components/com_admin/sql/updates/mysql/4.4.0-2023-09-13.sql` in phpMyAdmin, replacing the `#__` in the statements by your actual database prefix (including the underscore).

**Comment by dsimonse** [comment]
Hi Richard,

 

I was to fast and installed the updatepackage (and had no backup) without you sql-scrips.

It corrected the DB-warnings, but do I have to run them anyway?

 

//Dennis

 

Från: Richard Fath 
Skickat: den 23 oktober 2023 12:02
Till: joomla/joomla-cms ***@***.***>
Kopia: dsimonse ***@***.***>; Mention ***@***.***>
Ämne: Re: [joomla/joomla-cms] DB-tables not updated whem upgrading to 4.4.0 (Issue #42205)

 

P.S.: I hope you have made a backup before you made the update. If so, please revert to that backup and proceed the update as described in the doc linked in my previous comment. Otherwise, if you do not have a backup,m you have to run the SQL statements from the update SQL scripts administrator/components/com_admin/sql/updates/mysql/4.4.0-2023-05-08.sql and administrator/components/com_admin/sql/updates/mysql/4.4.0-2023-09-13.sql in phpMyAdmin, replacing the #__ in the statements by your actual database prefix (including the underscore).

**Comment by richard67** [comment]
> It corrected the DB-warnings, but do I have to run them anyway?

@dsimonse Yes, you have to run the 2 SQL scripts like I said. Correcting the warnings with the fix button only fixes the versions mismatch but does not run any update SQL script. Personal note: No backup, no mercy 😛

**Comment by dsimonse** [comment]
Hi Richard,

 

I did find the scripts in the folder but have no idea how to run them – please advice!

 

Regards
Dennis

 

Från: Richard Fath 
Skickat: den 23 oktober 2023 12:23
Till: joomla/joomla-cms ***@***.***>
Kopia: dsimonse ***@***.***>; Mention ***@***.***>
Ämne: Re: [joomla/joomla-cms] DB-tables not updated whem upgrading to 4.4.0 (Issue #42205)

 

It corrected the DB-warnings, but do I have to run them anyway?

@dsimonse <https://github.com/dsimonse>  Yes, you have to run the 2 SQL scripts like I said. Correcting the warnings with the fix button only fixes the versions mismatch but does not run any update SQL script. Personal note: No backup, no mercy 😛

**Comment by richard67** [comment]
@dsimonse If you read the comment where I mentioned the scripts, you will see that I already have advised how to run them (in phpMyAdmin). If you don't know how to do that you should not try to run a website. For more questions pelase use the support forum https://forum.joomla.org/ . This here is an issue tracker to track bugs and issues but not a support forum for such questions. Thanks for you understanding.

Additional hint: When updating with the Joomla Update component, which is the only way to do updates, it does not need to run SQL scripts manually. It is only needed in such cases like here when a broken site with incomplete database updates needs to be fixed.
