### ISSUE TITLE
This site can't be updated to Joomla ‎5.0.0

### ISSUE THREAD

**Issue by nasirkhan** [joomla/joomla-cms#42228]
### Steps to reproduce the issue

1. Update a Joomla site to v4.4.0
2. check the Joomla Update

### Expected result
I expected it to show me in detail which requirements were not met to update to v5.0.0. For example, if the PHP version is the issue, it displays the PHP version available on the server and the recommended version. 

A generic message is not useful at all. We should not expect a Joomla user will know the database server name or version. Unless we show them the actual issue s/he might not be able to fix that and continue the update. 

### Actual result

When I tried to update, it shows me a generic messages. 

```
This site can't be updated to Joomla ‎5.0.0

An update to Joomla ‎5.0.0 was found but your web server doesn't meet the [minimum requirements](https://downloads.joomla.org/technical-requirements). Please contact your web host to update your server.
You are on the "Joomla Next" update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x) and you will also be notified when the future major release (5.x) will be available. Before upgrading to 5.x you'll need to assess its compatibility with your environment.
```

### Additional comments
![Screenshot 2023-10-27 at 21-04-09 Joomla Update - Nasir Khan Saikat - Administration](https://github.com/joomla/joomla-cms/assets/396987/6f53b707-3218-47cd-b257-e4f610420d7b)

**Comment by brianteeman** [comment]
The link with the relevant information is in the message

**Comment by nasirkhan** [comment]
It checks if all the requirements meet the recommended versions, so showing that result to the user will be useful. 

As I mentioned above if someone knows the issue specifically then s/he might ask the hosting provider to fix/update that. 

I checked the doc and I know which component needed to be updated and I did that. But I am sure there are others who might not be able to do that.

**Comment by ghazal** [comment]
Did you read carefully what Brian said, and the technical requirements for J!5?
https://manual.joomla.org/docs/next/get-started/technical-requirements/#requirements-for-joomla-5x<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42228">issues.joomla.org/tracker/joomla-cms/42228</a>.</sub>

**Comment by C-Lodder** [comment]
The OP doesn't need help obtaining the requirements. They're referring to the generic message displayed.

Seeing as the checks are already performed, it would make sense to show which check actually failed, rather than having to manally find the version of 3 separate services.

**Comment by nasirkhan** [comment]
@C-Lodder thanks for understanding the issue. 

I did not understand the reason for hiding the test results and showing a generic message with a link that does not have the requirements of v5. Joomla v5 is a major release and we could not create a page to publish the requirements!

**Comment by brianteeman** [comment]
it is easy enough to make the requested change if the maintainers agreed

**Comment by richard67** [comment]
> it is easy enough to make the requested change if the maintainers agreed

@brianteeman I would like that but I'm only one. Maybe you could make a PR to come forward?

**Comment by N6REJ** [comment]
> It checks if all the requirements meet the recommended versions, so showing that result to the user will be useful.
> 
> As I mentioned above if someone knows the issue specifically then s/he might ask the hosting provider to fix/update that.
> 
> I checked the doc and I know which component needed to be updated and I did that. But I am sure there are others who might not be able to do that.

thats done in 3 to 4 and 4.+ so idk why it shouldn't be that way in 5 also.

**Comment by brianteeman** [comment]
@richard67 in light of comments from the release leads I wont waste my time on it without prior approval.

**Comment by brianteeman** [comment]
> showing the issues that prevent it is done in 3 to 4 and 4.+ so idk why it shouldn't be that way in 5 also.

That;s not correct

**Comment by richard67** [comment]
> ... in light of comments from the release leads ...

@brianteeman Where? Have I missed something?

**Comment by Fedik** [comment]
As already was discussed in https://github.com/joomla/joomla-cms/issues/42034
The Updater is picking the best URL match for User site from available in update XML, based on Server environment. Because in XML it is possible to provide an update for difefernt envrimoment (we do not use it, but it possible). 
It does not meant to show any "check result", but only the "best URL" if any is match to env.

To display a proper check result it is need to code some additional testing code, aside existing. Or re-think existing.

It is not a trivial change.
Until someone will come come up with proper solution I would suggest do not pollute the issue. 
Or it can be just closed.

**Comment by chmst** [comment]
@nasirkhan thanks for bringing this up. 
From a user's point of view I completely agree with you. 

But it seems that this is not as trivial, as @Fedik explained and as we can see in former discussions. 

I suggest to keep this open.

**Comment by N6REJ** [comment]
> > showing the issues that prevent it is done in 3 to 4 and 4.+ so idk why it shouldn't be that way in 5 also.
> 
> That;s not correct

once again you run your mouth before engaging brain.  When you update from 4.3 to 4.4 it runs a compatiblity check and shows you what might be issues.  If you think it doesn't then you should reinstall core and put your glasses on.

**Comment by richard67** [comment]
@N6REJ The issue here and the related issue #42034 are not about the pre-update check, they are about no update being applicable due to minimum version requirements for PHP and database for the update are not met. This is something which cannot have happened from 4.3 to 4.4 as these requirements only change with a new major version, i.e. from 3 to 4 or 4 to 5.

**Comment by N6REJ** [comment]
> I expected it to show me in detail which requirements were not met to update to v5.0.0. For example, if the PHP version is the issue, it displays the PHP version available on the server and the recommended version.

@richard67 thats not what I understand from the opening of the ticket
>I expected it to show me in detail which requirements were not met to update to v5.0.0. For example, if the PHP version is the issue, it displays the PHP version available on the server and the recommended version.

**Comment by Scrabble96** [comment]
I have just received this same message. Firstly, the link goes to the wrong info page as it has been moved to https://manual.joomla.org/docs/next/get-started/technical-requirements/#fn-2 

That aside, I upgraded an old version of a site on a backup sub-domain of a J4 site, upgrading it to 4.4.0 and then to 5.0.0  successfully as a test a couple of days ago. Then, I copied over the latest live version to the same domain and tried to upgrade that one, only to get this message 'This site can't be updated...' message . My PHP is 8.1.24, database is 10.6.15-MariaDB-cll-lve-log. The Web Server is LiteSpeed - an Apache alternative - but which is not listed in the requirements page  but has always worked before.

BUT... I logged out and logged in again on another browser (from Firefox to Chrome) and it has now updated to 5.0.0. Is it a cache issue, perhaps?

**Comment by richard67** [comment]
> and 3->4 did have the check https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration

@N6REJ We are not talking about the check for the PHP version and database type being supported which is and always was shown in the pre-update checker. This always referred to the currently installed Joomla version, not to the one to which you want to update.

What we are talking about is that when the updater searches for an update, it sorts out all updates which do not have the right targetplatgormversion in their XML. In addition it checks the required PHP version and the required versions for the different database server types from the update site's XML and sorts out unsuitable updates.

In J3 this resulted in "no update found" for the quickicon and the update component's view.

Since J4.something the quickicon had shown an available update, but the component view not, this was confusing and reported with issue #42034 and solved with PR #42103 so that the user gets a message that there has been an update found which is not suitable. That was all which could be done without bigger changes in the code of the update component and the installer library.

As said, this thing is only relevant for the requirements of the target version to which you want to update, and that is something which changes only with a major version and so can not have happened when updating from 4.3 to 4.4, like you wrote.

**Comment by brianteeman** [comment]
and that is why I wont waste my time without prior approval

**Comment by nasirkhan** [comment]
thanks, everyone for participating in the conversation. I can not answer everyone but here are some replies I need to address. Many of you talking like this is not an issue and some others are suggesting ignoring/accepting this issue. 

Please find and talk to someone who is using Joomla and has 0 technical knowledge, or just assume, s/he wants to update to J5. S/he will not have any clue about the issue and will land on the wrong page and if s/he is brave will open *Joomla! Programmers Documentation*, a page that is built for the Joomla developers. As s/he does not know the exact problem, who will help that person? S/he will hire a developer? call hosting company? or ask Joomla team members? 

@Fedik  
> To display a proper check result it is need to code some additional testing code aside existing. Or re-think existing.
Why do you want to keep the issue and suggest not to code? 

> ... Or it can be just closed.
This is a major issue for the end user, but surely not for the Joomla team members. Otherwise, it should have been fixed. 

@N6REJ 
thanks for sharing the link. 

@richard67 
why you are pushing to accept a sub-standard product? 
> This always referred to the currently installed Joomla version, not to the one to which you want to update.
This is Joomal 5, not Joomla 50 there are only a few major releases earlier. So first we need to agree, we want to build a good product. For minor releases, you are showing test results and for major releases, you are showing the wrong URL. Results help to fix/change what is needed.

**Comment by Fedik** [comment]
I have wrote a different thing. And explained some root reasons of the issue. Please check it again. Thanks.

**Comment by N6REJ** [comment]
I'm going to give a users view and then be quiet.
From 3->4 we show what issues might exist.
from 4.3 to 4.4 we do the same if I recall
from 4->5 we SHOULD, and thought we did,  show the same.

IMO we should do this for every release that has a possible conflict not just major releases. 
Lets not force them to go to some document that may or may not be right ( we all know our documentation history ).  Lets give them the info they need.  Quite frankly if we have the ability to do it for one upgrade, irregardless if its a major or not, we should be able to do it for all upgrades.
This helps the uneducated end user.  That shouldn't be a bad thing

**Comment by brianteeman** [comment]
@N6REJ Please read again the posts by @richard67 you are talking about something completely different to the issue here!!

**Comment by brianteeman** [comment]
As can be seen by this new issue report the situation in J3 was worse #42249

**Comment by josephsimony** [comment]
Any update on this? 
_(Using "Joomla" since the first Mambo releases, managing my own servers)_

PHP 8.2.x
MariaDB 10.6.16
Apache/Litespeed Enterprise

![screen shot 2023-12-08 at 18 37 08](https://issues.joomla.org/uploads/1/89bb35f8d7794e0f11924b4f8d0a51e7.png)

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42228">issues.joomla.org/tracker/joomla-cms/42228</a>.</sub>

**Comment by richard67** [comment]
Btw. I'm working on a fix, not sure yet if I will be successful.

**Comment by richard67** [comment]
Closing as having a pull request (PR):

@nasirkhan @josephsimony and others. Please test PR #42489 .
