### ISSUE TITLE
Issue Deprecated: stripos() in WebClient.php for ever?

### ISSUE THREAD

**Issue by Chessy65** [joomla/joomla-cms#42317]
### Steps to reproduce the issue
If you access from a joomla system to another joomla on which is Joomla 4.4 and PHP8.1 or higher an dthe WebClient.php is needed,
then you receive 9 !! error lines with following text:

Deprecated: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in ../libraries/vendor/joomla/application/src/Web/WebClient.php

This issue is for a long time and should be solved, but it is missing in the actual fork. Why?

You need insert only '(string)'

### Expected result
see picture

### Additional comments
I have found it already im #39960![screen shot 2023-11-07 at 17 57 48](https://issues.joomla.org/uploads/1/7c62e576ef272de874ddd5260bcdd810.jpg)

**Comment by alikon** [comment]
please test https://github.com/joomla-framework/application/pull/121

**Comment by samlatif** [comment]
I have the sam error,
PHP Deprecated: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /libraries/vendor/joomla/application/src/Web/WebClient.php on line 286.

joomla4.4 PHP 8.2.14 template Cassiopeia. Any suggestions to solve it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42317">issues.joomla.org/tracker/joomla-cms/42317</a>.</sub>

**Comment by dustbin34** [comment]
Hello I have this issue. Only at the root of my website :  if I enter http://mywebsite.com I have the deprecated issue, if I enter http://mywebsite.com/index.php that's ok. 
I use Cassiopea, how could I solved this trouble?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42317">issues.joomla.org/tracker/joomla-cms/42317</a>.</sub>

**Comment by dustbin34** [comment]
Sorry problem solved!  I connected to the Joomla aministration and after a cache clearing the issue Deprecated: stripos(...) on my home page has disappeared.
Bye!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42317">issues.joomla.org/tracker/joomla-cms/42317</a>.</sub>

**Comment by richard67** [comment]
Please test #42937 . Thanks in advance.

**Comment by richard67** [comment]
For 5.x this issue has been fixed with PR #42945 , which will be part of the 5.1.0-beta1 coming up tomorrow.

For 4.4 it still needs to be fixed.

**Comment by DrZen33** [comment]
I am also seeing the same problem in Joomla 5.1.2
My Error Log file is massive, because of this problem. It repeats over and over again...
When I posted about this problem before, someone replied and said it was probably being caused by an Extension and to just ignore it. I've turned off my Extensions on test site and cannot locate what is causing this. Is Joomla the problem?

PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /libraries/vendor/joomla/application/src/Web/WebClient.php on line 502
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public_html/libraries/vendor/joomla/application/src/Web/WebClient.php on line 505
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public_html/libraries/vendor/joomla/application/src/Web/WebClient.php on line 508
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public_html/libraries/vendor/joomla/application/src/Web/WebClient.php on line 526
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public_html/libraries/vendor/joomla/application/src/Web/WebClient.php on line 472
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public_html/libraries/vendor/joomla/application/src/Web/WebClient.php on line 483
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public_html/libraries/vendor/joomla/application/src/Web/WebClient.php on line 494
PHP Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public_html/libraries/vendor/joomla/application/src/Web/WebClient.php on line 498<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42317">issues.joomla.org/tracker/joomla-cms/42317</a>.</sub>
