### ISSUE TITLE
[5] Blog Sample Data: Danish installation fails

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#42342]
### Steps to reproduce the issue
Installation of Blog Sample Data using Danish language.

### Expected result
Installation successful.

### Actual result
Installation fails at step 1:
![bsd-danish](https://github.com/joomla/joomla-cms/assets/147295380/b40f5503-c743-4128-a966-622caee924cf)

### System information (as much as possible)

Linux lamp302.cloudaccess.net  3.10.0-962.3.2.lve1.5.81.el6h.x86_64 #1 SMP Wed May 31 12:07:35 UTC 2023  x86_64
mysql
8.0.34-cll-lve
utf8mb4_0900_ai_ci
utf8mb4_0900_ai_ci
None
Yes
8.1.24
Apache
cgi-fcgi
Joomla! 5.0.0 Stable [ Kuboresha ] 17-October-2023 16:00 GMT
Enabled (classes_aliases:"1", es5_assets:"1")
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0

### Additional comments
Blog Sample Data fails if Danish is the first language to  install or not the first.

Other languages fail at step 1 or another step. Should this be reported as issue for each language or all in one issue?

**Comment by tkuschel** [comment]
I can reproduce this issue with Danish language only. Tested with German de-DE, and British English en-GB.

I found the issue, it is caused by the Danish language file in `administrator/language/da-DK/plg_sampledata_blog.ini`
There is a tag title which must be unique!
Excerpt from the language file:
```
...
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_NEWSFEEDS_TITLE="Min blog"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_0_TITLE="Millioner"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_1_TITLE="Kærlighed"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_2_TITLE="Kærlighed"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_3_TITLE="Joomla 5"
PLG_SAMPLEDATA_BLOG_STEP1_SUCCESS="Trin 1: Tags, artikler, felter og arbejdsgang gennemført!"
...
```
Kærlighed exists twice and the logic building the table creates an alias with the same name!
Thank you for posting your issue; you should e.g. change the line to PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_1_TITLE="Kærlighed" to, translated from English tag, probably:
```
...
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_NEWSFEEDS_TITLE="Min blog"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_0_TITLE="Millioner"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_1_TITLE="I hele verden"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_2_TITLE="Kærlighed"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_3_TITLE="Joomla 5"
PLG_SAMPLEDATA_BLOG_STEP1_SUCCESS="Trin 1: Tags, artikler, felter og arbejdsgang gennemført!"
...
```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42342">issues.joomla.org/tracker/joomla-cms/42342</a>.</sub>

**Comment by fgsw** [comment]
Thanks @tkuschel

**Comment by rbuelund** [comment]
This has now been corrected on crowdin. Thanks for the notice.
