### ISSUE TITLE
Call to undefined method JApplicationAdministrator::isClient() on Joomal 3.6.5 to 3.8.2

### ISSUE THREAD

**Issue by jazzy1979** [joomla/joomla-cms#42407]
My website is hosted on godaddy attempted to migrate from Joomla 3.6.5 to 3.8.2 using joomla upgrade. Failed to fix it I copied postupdate.php and ran after which  backend got restored but I am only seeing this error on each menu tab:

Call to undefined method JApplicationAdministrator::isClient()

Checked my db as suggested by this forum and I have client_id column already. Any suggestions.

**Comment by wilsonge** [comment]
Check for this function https://github.com/joomla/joomla-cms/blob/3.8.2/libraries/src/Application/CMSApplication.php#L742-L754 in your `libraries/src/Application/CMSApplication.php` file. I would also add that you really need to be moving to the latest version. Joomla 3 as a whole has been unsupported by the project since September after 2 years of maintenance. You need to move to 3.10 and then to J4 as soon as practically possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42407">issues.joomla.org/tracker/joomla-cms/42407</a>.</sub>

**Comment by toivo** [comment]
Feel free to search the Joomla! Forum how similar issues have been resolved in the past, for example [Fatal error: Call to undefined method JApplicationSite::isClient() after update to 3.8](https://forum.joomla.org/viewtopic.php?t=958743)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42407">issues.joomla.org/tracker/joomla-cms/42407</a>.</sub>

**Comment by alikon** [comment]
Support has ended on 17 August 2023 for Joomla 3.x
