### ISSUE TITLE
Schema.org autofill data

### ISSUE THREAD

**Issue by sergeytolkachyov** [joomla/joomla-cms#42466]
### Is your feature request related to a problem? Please describe.
We have updated Russian Joomla Commuity portal from J3.10.12 to 5.0.0. and now getting it in order. Yesterday I tried a new J5 feature -  Schema.org  plugins. That's swag. But we have a 3k+  articles, different types... Some parts of them are creating from plugin - we parse our Telegram channel and copy posts from there to community portal to specified category automatically. And for each of them we must fill Schema.org data **MANUALLY**! It's crazy! And our site is not so big. We can find Joomla sites with tens and hundreds thousands of articles... 

**-- What can we do here? 
-- Just die**.

### Describe the solution you'd like
I think there could be a system with predefined settings for each category of articles (for ex.). So, I'll say to Joomla: 
> Articles in this category are BlogPosting schema type only. Fill title from title, author data from com_contact, image from intro or fulltext image etc..., But for other category my articles are products because I did an overrides there. So article title is product title, that article custom field is product price, etc...

Due to schemaorg data is stored in separate database table may be we need a new bulk action in articles list for updating a schema org data for articles with category rules.

**Comment by brianteeman** [comment]
So this is compltely undocumented but without doing anything at all there are some schemaorg default settings that are automatically created for you. This is controlled by the "Cotent - Joomla" plugin.

If you view the source of your generated web pages you will see the output in the head - it is a line beginning `<script type="application/ld+json">`

**Beware** - again undocumented -  that if you have any template overrides then you will need to review them to remove any reference to `itemprop` etc. Otherwise you end up with both schemaorg and the old style data which is not good.

**Comment by sergeytolkachyov** [comment]
I'm talking about something else. In order for the data to schema.org they were filled out - I need to go into each of the 3000 articles and select at least the type of schema for the article and save it. If you do not do this, the default markup will not appear in the article.

**Comment by brianteeman** [comment]
Thats not true. Check my personal site where I have NOT added anything to any of the articles since I upgraded to joomla 5 but they all have basic schemeorg data

Example
https://brian.teeman.net/joomla/892-responsible-web-design
![image](https://github.com/joomla/joomla-cms/assets/1296369/a893c424-9911-46a9-bce7-a06f8b5cdbfd)

**Comment by sergeytolkachyov** [comment]
Thank you. Forgot to clear cache )) For BlogPosting it works.

**Comment by bembelimen** [comment]
What would be a nice improvement: auto fill data to the new fields based on certain rules. If you have an idea how to implement this, feel free to make a PR!
