### ISSUE TITLE
Media Manager displays wrong file type

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#42518]
### Steps to reproduce the issue
1. Use a Joomla installation with current version (i.e. 4.4.1 or 5.0.1)
2. Upload a text file into the /images folder
3. Open Media Manager in thumbnail mode
4. Check, which icon is displayed for the uploaded text file.

### Expected result
The file should be displayed as text file.

### Actual result
The file is displayed as being a PDF file.

J4.4.1:

![Screenshot 2023-12-14 at 11-58-52 Media - J4Masterclass - Administration](https://github.com/joomla/joomla-cms/assets/7933215/199134b7-9e17-4fc8-bfaa-b224c5434547)

J5.0.2 (nightly build)

![Screenshot 2023-12-14 at 11-58-28 Media - J5 Test - Administration](https://github.com/joomla/joomla-cms/assets/7933215/eada6709-0ad2-4252-b19a-c5b1325b0354)

### System information (as much as possible)
J4.4.1 / J5.0.2
PHP 8.2.2

**Comment by brianteeman** [comment]
confirmed

**Comment by ReLater** [comment]
It's the same with file types doc, xls, txt.

![grafik](https://github.com/joomla/joomla-cms/assets/20780646/ed53bc5e-8358-4d17-9890-dd34e8b670a7)

I think it's just because a wrong icon type (fa-file-pdf) is used for all of them:

![grafik](https://github.com/joomla/joomla-cms/assets/20780646/60df3759-3b2c-4314-b2cb-f9c3b51b3433)

**Comment by brianteeman** [comment]
see the discussion here https://github.com/joomla/joomla-cms/pull/34634#discussion_r785477396

**Comment by brianteeman** [comment]
Please test #42527
