### ISSUE TITLE
[5.0.2][System - SEF] does not work correctly for rel="canonical"

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#42720]
### Steps to reproduce the issue
1. enable the plugin `System - SEF`
2. enter the full path of your website in the `Site Domain` field
3. look at how the `rel="canonical"` tag identifies SEF and non-SEF links

### Expected result
only SEF links will be defined as `rel="canonical"`

```
example:
https://site.com/my-article
```

### Actual result
any links (SEF and non-SEF) are defined as `rel="canonical"`

```
example:
https://site.com/my-article
https://site.com/index.php?option=com_content&view=article&id=1

^ both of these links and any other links are defined as canonical
```

### System information (as much as possible)
Joomla 5.0.2

### Additional comments
![изображение](https://github.com/joomla/joomla-cms/assets/3662519/b5d1b61a-15f6-4081-be60-d7b5216145e2)

**Comment by Quy** [comment]
Duplicate #26416?

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/26416#issuecomment-535864756

**Comment by Quy** [comment]
Closing as duplicate.

**Comment by weeblr** [comment]
> As far as I know, https://github.com/joomla generates a canonical link (for articles and categories) based on two data:

Not at all. Joomla has no knowledge of any canonical URL and does not try to compute a canonical tag.
The only thing it does (it's done by the SEF system plugin), is change the **domain**.

If you configured **Site domain"** to be `https://example.com`, the SEF plugin will issue a canonical tag on all pages of the site with that domain.

So if current URL is `https://example.com/some-url?fcblid=12356`, the canonical tag will also be:  `https://example.com/some-url?fcblid=12356`

And if the site can be accessed through another domain, for instance `https://example.net/some-url?fcblid=12356`, then the canonical becomes simply also: `https://example.com/some-url?fcblid=12356`

I'm sure we can continue this in your other issue though

**Comment by weeblr** [comment]
>  I mean that the canonical link (not rel="canonical" tag) in Joomla is created based on a menu item, or based on a specific category link.

Best to use canonical URL then, instead of canonical link.

> Why doesn't Joomla add a rel="canonical" tag to this canonical link, instead of adding a canonical tag to every (including non-canonical) link in the current setup.

Because that's not the role of a rel=canonical tag. The rel=canonical tag is only useful on **duplicates**.

If the canonical URL for a given page is `https://example.com/some-article`, then **you do not need a rel=canonical link inside that page**.

You need a rel=canonical **pointing** at  `https://example.com/some-article` on all other pages are that have different URLs but are in fact the same page.

For instance on:

- `https://example.com/some-article?fbclid=12346` (URL shared on Facebook)
- `https://example.com/some-article?utm_campaign=may-2025` (ad tracking)
- `https://example.com/some-category/some-article`
- `https://example.com/index.php?option=com_content&view=article&id=12`

And Joomla has no mechanism to identify which is a duplicate and which is a totally different piece.

Which is why Joomla only adds a canonical to a page when the Domain site is in use - and still does a bad job at it in most cases, because the domain is only a small part of the problem.

**Comment by weeblr** [comment]
>  in fact, you are mistaken when you say that Joomla does not know which link for an article is canonical.

Considering my experience with Joomla, that is extremely unlikely. The router certainly has made many progress over the years though, so for many sites, there will never be any issue (and therefore canonical tags are not needed at all).

> if we use only one domain (the site is not available on different domains), then when you go to an article, Joomla always generates one canonical link for the article.

It creates as many links as there are menu items path to it. It may pick one, normally the first one it finds in the menu structure that matches best the non-sef request, but that does not mean multiple URLs are not generated. 

> Let's say if the canonical link of your article is site.com/category-news/11-article, then go to the duplicate/non-canonical URL like site.com/category-video/11-article and you will see that despite the fact that you followed the non-canonical link, the article title is clickable and the article title, when clicked, will redirect you to the only correct canonical link.

Then why doen't it use always the same link in the first place?

**Comment by brianteeman** [comment]
@weeblr dont waste your time
