### ISSUE TITLE
Blog sample workflow lacks publish transition

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#42875]
### Steps to reproduce the issue
Enable workflows.
Assign the Blog workflow to a category.
Create a new article and change the workflow stage.

### Expected result

In one of the stages there should be an option to publish the article.

### Actual result

There is only a Publish and feature transition, after all checks have been done in the stages before.

### System information (as much as possible)

Joomla 5.1 alpha 3

### Additional comments

In this workflow there is no option to just publish an article. All articles are featured. Unless you publish and feature first, then unpublish the article and then publish it again. If you publish it again there's no option to feature the article.

**Comment by rdeutz** [comment]
@bembelimen can you have a look here, please? What is the best way to tackle this?

**Comment by HLeithner** [comment]
@stimpsonjcat it's now clear where your issue is. You can create your own workflows with own transition which allows you to feature and public an article at the same time. 

I'm closing this because the issue tracker are for bugs and feature requests in this case I think the forum is the better place to ask.
