### ISSUE TITLE
Extension manifest. Description field attribute

### ISSUE THREAD

**Issue by philip-sorokin** [joomla/joomla-cms#42996]
Hello.

Is description working in J5 extension manifests? I see no tooltips and description defined in language files in constants. Can you help me with this issue? I do not know if it's a bug, you can close this issue if it's not. Thank you.
![2024-03-11_13-32-36](https://github.com/joomla/joomla-cms/assets/11632367/73a56ed1-66b7-4d8f-a4ff-ff61c6b2ad56)

**Comment by philip-sorokin** [comment]
I see, thank you. In my opinion, tooltips in J3 were much better! This issue can be closed, but please, think about implementation of tooltips.

**Comment by alikon** [comment]
closed

**Comment by joomdonation** [comment]
> This issue can be closed, but please, think about implementation of tooltips

@philip-sorokin I remember tooltip is not used because it has accessibility issues. I'm not knowledgeable to explain the details, just try to give you some info so that you understand the reasons.

**Comment by brianteeman** [comment]
> > This issue can be closed, but please, think about implementation of tooltips
> 
> @philip-sorokin I remember tooltip is not used because it has accessibility issues. I'm not knowledgeable to explain the details, just try to give you some info so that you understand the reasons.

**that was NOT the reason and am getting sick of repeating this**. the problem was that bootstrap provided no method of indicating that a label had a tooltip. As a result in Joomla 3 every label had a tooltip even though in the majority of cases it was completely useless. So the decision was made to remove the tooltip and to display the description (tooltip) on screen so that we could really see what descriptions were pointless and then they were removed. It was always the intention to allow tooltips as long as there would be a visual indicator that it actually existed and was accessible (just like the rest of the ui). However instead of adding code to turn the descriptions into tooltips code was added to use the button instead.
