### ISSUE TITLE
Edit a signle article from menu

### ISSUE THREAD

**Issue by niosme** [joomla/joomla-cms#43106]
### Steps to reproduce the issue
Site is multilingual with two languages. Greek and English.
Created a field and attached to an article.
When i go to edit the articles from the menu which shows a single article with a custom field attached the popup throws this error

Invalid controller: name='article', format=''

### Expected result

Popup should open the article to be editted.

### Actual result

Popup with a message Invalid controller: name='article', format=''
![Screenshot 2024-03-21 at 9 26 53 AM](https://github.com/joomla/joomla-cms/assets/96840280/d8f78b5c-647b-42d3-94b8-c78dedf7e8da)
![Screenshot 2024-03-21 at 9 27 01 AM](https://github.com/joomla/joomla-cms/assets/96840280/ee8583c9-eae7-4fc8-89ad-c73dc3425155)

### System information (as much as possible)

Joomla 4.4.3
Php 8.2
Broswer: Firefox 123.0.1

**Comment by Quy** [comment]
Unable to replicate.
Maybe a conflict with a non-core extension.
Enable `Debug System` and `Error Reporting` to Maximum to get a trace stack.

**Comment by niosme** [comment]
There are no extensions installed in this installation.

Debug throws the same error without any stacktrace. The only things shows up before the edit article popup at the menu edit page is that
 PHP Deprecated:  Creation of dynamic property Joomla\Database\Mysql\MysqlDriver::$charset is deprecated in /home/user/public_html/libraries/vendor/joomla/database/src/Mysql/MysqlDriver.php on line 121
by i dont think is something that have to do with that situation.

**Comment by brianteeman** [comment]
unable to replicate

**Comment by chmst** [comment]
Which type of filed is it?

**Comment by niosme** [comment]
Its two calendar fields and one integer field.

**Comment by Fedik** [comment]
The quotes not an issue, `$input->getInt("' 3 '")` will clean it up, and return `3`.

From you har files I can see that something interrupt `&task=article.edit` request, because the response still contain `id=' 3 '` however it cannot hapen in core.
In core the ID is cleaned here https://github.com/joomla/joomla-cms/blob/9363e787206af2a91fae9c57e32305ca7036d5f0/libraries/src/MVC/Controller/FormController.php#L380
then goes redirect to `&view=article&id=3`. 

But, even if you do manualy `&view=article&id=' 3 '` it still will work, in core (because ID is filtered).
A reason of your issue is somewhere else.

I do not realy see how the error on your screenshot can hapen in core, unles there something is modified.

If you do not have any extensions installed, then you probably need to check you server config, if there any extra URL filtering or something.

**Comment by Fedik** [comment]
BTW, The error message `Invalid controller: name='article', format=''` means that the https://github.com/joomla/joomla-cms/blob/14a1ad4279abef9a56b21282367001429c5a4519/libraries/src/MVC/Controller/BaseController.php#L329 cannot find controller.

However this code not used by Joomla 4. Joomla 4 uses `ComponentDispatcher`.

So, I think there is realy something wrong with your installation.

**Comment by brianteeman** [comment]
a har file will not help debug the problem. Server logs and a stack trace are the only way to truly see what is going on. The fact that you cannot get a stack trace to display is a concern.

**Comment by niosme** [comment]
Its the popup which doesnt throw the stack trace and no error occured.If i disable the seo it redirects to the homepage instead of throwing this.
By the way its a copy of a working installation on the exact same server under a same hosting package.

I dont know what is happening. Its surely something with the installation but i just copied it. You can close the issue and if i figure out what is happening i ll let you know.

**Comment by Quy** [comment]
Closing. Hopefully, you will be able to figure it out and let us know. Thanks.
