### ISSUE TITLE
Smart search filters not work correctly

### ISSUE THREAD

**Issue by thanhnv37** [joomla/joomla-cms#43528]
### Steps to reproduce the issue
Create two (or more) taxonomies have node with same title.
For example: 
I created two taxonomies that are: Language and Variant.
Both taxonomies have one node with title "__notset__"

Then I created a filter and select all nodes from these both taxonomies.

### Expected result
The search results displays all items by default (since all nodes selected)

### Actual result
Display only some items, because the Search modal merge node by their title, so the query not include all ids of selected nodes.

### Additional comments
To resolve this issue, I modified the file below:
**components/com_finder/src/Model/SearchModel.php**

Replace the code line (line 194):
`$taxonomies = \call_user_func_array('array_merge', array_values($this->searchquery->filters));`

With below one:
```
//$taxonomies = \call_user_func_array('array_merge', array_values($this->searchquery->filters));

$taxonomies = [];
for ($i = 0, $c = \count($groups); $i < $c; $i++) {
    $taxonomies = array_merge($taxonomies, array_values($groups[$i]));
}
```

Please check this issue, and I hope that you can apply this fix to the next release of component.

![taxonomy-nodes](https://github.com/joomla/joomla-cms/assets/10413985/589bc4ba-bc1a-4c00-ae8e-744078a20a14)

**Comment by Hackwar** [comment]
Which joomla version is this? Because we changed several things in 5.0 and this could already be fixed there.

**Comment by thanhnv37** [comment]
Hi @Hackwar, 

This issue is still persists in the latest version 5.1.2.
You can follow steps that I provided above to reproduce this issue.

**Comment by hendrikbehncke** [comment]
The issue persists in 5.2. 
It also happens when there are categories with the same title but a different parent category. Then only the last category will exist in the filter.

Would it be solved if the `alias` from `#__finder_taxonomy` would be queried here? https://github.com/joomla/joomla-cms/blob/5.2-dev/administrator/components/com_finder/src/Indexer/Query.php#L554

At least one could change the alias and still use the same title for categories.

**Comment by Quy** [comment]
Please test PR #44437. Thanks.
