### ISSUE TITLE
CSS Fix for Isis Admin template for better editor use on ipad.

### ISSUE THREAD

**Issue by AlexHarris79** [joomla/joomla-cms#4386]
#### Steps to reproduce the issue
When using either TinyMCE or Codemirror editors on an iPad, the top and bottom navbars prevent typing in text. This is caused by the classes .navbar-fixed-bottom and .navbar-fixed-top having the value position:fixed and that interferes with the pop-up, onscreen touch keyboard of the ipad.

Can be fixed by adding the following lines to /administrator/templates/isis/css/template.css

.navbar-fixed-bottom, .navbar-fixed-top, .subhead-fixed {position:relative!important}
.subhead-fixed {top:0px!important}
@media (min-width: 768px){
body {padding-top:0px!important;}}

#### Expected result
The navbars should be set to position:relative and not interfere with the ipad's keyboard.

#### Actual result
The navbars hover across the input area of the editor.

**Comment by brianteeman** [comment]
Its been over a year since this was first reported and with no progress or any other comments I am closing this. It can always be re=opened if someone has a solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4386">issues.joomla.org/joomla-cms/4386</a>.</sub>
