### ISSUE TITLE
[5.2] Error on saving nested Subform

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#44168]
### Steps to reproduce the issue

When I try to save this nested subform, the entries are saved but still I get the error:

**Save failed with the following error: Field 'value' doesn't have a default value**
![grafik](https://github.com/user-attachments/assets/c7133275-f323-4570-b37d-9b430ccf2265)

![grafik](https://github.com/user-attachments/assets/9d3a44f8-0bc4-4a7f-a8d2-e2b668e41666)

If I disable the nested subform no error appears.

### Expected result
no error

### System information (as much as possible)
The currently installed Joomla! version is "‎5.2.0-rc1-dev" ‎5.2.0-rc1-dev

**Comment by brianteeman** [comment]
From the information provided I could not replicate the error

**Comment by coolcat-creations** [comment]
Maybe because I updated the site with an update package ? No clean installation...
Not sure how to debug.

**Comment by coolcat-creations** [comment]
I tested it on another site I upgraded from 5.1.4 to 5.2 nightly build and same:
The error appears when data is added into the nested subform (in my case the grid items)

<img width="1319" alt="grafik" src="https://github.com/user-attachments/assets/a50493e9-4c82-410c-a28c-9610341ee895">

**Comment by brianteeman** [comment]
are you sure the problem isnt from the first field where you have not selected an item?

**Comment by coolcat-creations** [comment]
Yes because if I leave the "grid" fields empty the error does not appear and because in my first testing site no other fields exist.

**Comment by hayyi** [comment]
I encountered the same error, but resolved it by changing my database column from non-nullable to nullable, which made the error disappear. I'm not sure if this is related to your issue, but it might be worth checking your database for the stored value

**Comment by coolcat-creations** [comment]
Ok but thats a fresh install of 5.1.4 + Update to RC1, not sure sending the users to the database is a good user experience. Maybe this set to Nullable could be implemented in the update?

**Comment by brianteeman** [comment]
It should be NULL by default

**Comment by coolcat-creations** [comment]
I confirm it was NULL

**Comment by brianteeman** [comment]
So it is nothing to do with that then

**Comment by coolcat-creations** [comment]
Agree, but the error is there anyway.

**Comment by coolcat-creations** [comment]
Updated to RC1 and issue still exist

**Comment by coolcat-creations** [comment]
In a fresh install the subform elements even do not appear when repeating

![Image](https://github.com/user-attachments/assets/9b2aeefb-8e4e-4d8b-a25e-907321f3c25c)

**Comment by brianteeman** [comment]
> From the information provided I could not replicate the error

Maybe if you provided more details on the exact setup of the fields someone will be able to help you. As it is right now, based on the limited information in your screenshots I still cannot replicate this.

**Comment by coolcat-creations** [comment]
It seems it was an issue with the nightly build package, 
I installed again a new 5.1.4 made an update to 5.2 RC1 and the issue did not appear anymore.
now I installed again a new 5.1.4 made an update by uploading the folder into the joomla update component to make sure I did the same like in the failed ones  and the issue did not appear. Closing.

**Comment by coolcat-creations** [comment]
I have to reopen this again because I have the same Error on a fresh install of Joomla 5.2

**Comment by richard67** [comment]
The error message refers to a value not being given for a database column with name "value" in an "INSERT" SQL statement and that database column does not have a DEFAULT value in the database structure so the value HAS to be specified when inserting data.

It's very likely the "value" column of the "#__fields_values" table, and for that column we do not specify a default value by purpose here: https://github.com/joomla/joomla-cms/blob/5.2-dev/installation/sql/mysql/supports.sql#L226

The reason why we do not specify a default value is because that is not allowed on MySQL 8, see here: https://dev.mysql.com/doc/refman/8.4/en/blob.html

> BLOB and TEXT columns cannot have DEFAULT values. 

The "TEXT" refers to data types "TINYTEXT", "TEXT", "MEDIUMTEXT", and "LONGTEXT", so for CHAR or VARCHAR columns we still can use DEFAULT values.

Even if you could change the database to have a DEFAULT value for such a column when you are on MariaDB, we cannot do that because we do not have different data structures for MySQL and MariaDB.

So the database is as it should be, and the error must be in some PHP code which does the "INSERT" into that table without specifying a value for that column (even NULL would be ok as value).

@Fedik As you know much about our subforms: Do you have an idea where that could go wrong?

**Comment by Fedik** [comment]
It is more likely after we allowed the nested form for Subform Custom field https://github.com/joomla/joomla-cms/pull/43204

The Subform itself has an issue with handling nested form which have a default value or `min` attribute, https://github.com/joomla/joomla-cms/issues/43652

Make sure your nested subform does not have these attributes.

**Comment by coolcat-creations** [comment]
Closing again since its an issue with jfilters.
