### ISSUE TITLE
[5.2] New Articles Module - Character limit of introtext is wrong

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#44183]
### Steps to reproduce the issue

![Image](https://github.com/user-attachments/assets/ae287406-1b41-40f3-bcb8-8846146481dd)

Display Options -> Introtext Limit - set it to 5

### Expected result
The introtext should be cut after 5 characters, followed by the three points

### Actual result
Although there is introtext, in some cases no characters are shown

![Image](https://github.com/user-attachments/assets/317cf71e-7473-4aaa-95f7-3ea4142f7d5f)

### System information (as much as possible)

Joomla 5.2rc1, PHP 8.2

### Additional comments
There is HTML Text in front of the text

**Comment by bembelimen** [comment]
If I do:
![Image](https://github.com/user-attachments/assets/cdf4cdeb-e991-4e13-aab5-f1af3714bc17)

I get:
![Image](https://github.com/user-attachments/assets/f1b2cc48-cbd3-40be-888d-78fb9fae68d0)

So more characters than expected.

**Comment by Quy** [comment]
Fixed per #44179 pending merge. Thanks for the report.

**Comment by Quy** [comment]
Partial fix per #44179 except for `...`.

**Comment by chmst** [comment]
One problem arises when the text limit ist too small. Then the truncate method cannot find a space in the text and offset is empty. No text is displayed at all. 

If the limit for the introtext is big enough so that at least one space is in the truncated text, then it works. Not the exact number of characters, but near enough for human reading. 
A quick solution could be: 
Add a description to the label of text-limit that the number is not exact value but varies with spaces between words.  
Add a rule that the text-limit must be >= 50 then probably every language has at least one space in the text. In real life it does not make sense to show only 6 characters of an intro text.

**Comment by brianteeman** [comment]
Does the readmore limit behave differently here to its other uses elsewhere? I suspect not

**Comment by Quy** [comment]
Please test PR #44189. Thanks for the report.

**Comment by chmst** [comment]
> Does the readmore limit behave differently here to its other uses elsewhere? I suspect not

It is the same method, probably in real life nobody sets limit so small as we did in these tests. I can test tomorrow with readmore in other situations.
