### ISSUE TITLE
Show tags in the article list

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44528]
### Is your feature request related to a problem? Please describe.
The article list shows the title, status, author... as well as the current and parent category and the notes. This selection is nice, comes from the old days (j1.5?), but I don't have the option to show tags.

### Describe the solution you'd like
Configuration options for the display in the admin:
- Show category: yes/no
- Show parent category: yes/no
- Show notes: yes/no
- Show alias: yes/no
- Show tags: yes/no

### Additional context
It would be nice to have the same options available for the article lists when configuring an admin menu item...

**Comment by Hackwar** [comment]
Hello @hytsch, thank you for opening this ticket. Unfortunately I don't think we will go into that direction. Joomla already has an awfull amount of parameters everywhere and we are rather looking at reducing than extending that number. A display like you are asking for is easily done with a template override. Because of that, I'm going to close this ticket.
