### ISSUE TITLE
custom validation issues arising in the joomla! administrator after the release of joomla 3.3.3

### ISSUE THREAD

**Issue by deepanshu-jha** [joomla/joomla-cms#4736]
The custom validation rules for the form fields are not working as expected soon after the release of joomla! 3.3.3 & are throwing several errors in the console. The same set of handlers & syntax worked fine untill the joomla! 3.2.x versions. The successive versions after the release of 3.3.3 are also facing the similar problems. I tried looking into the issue & found that there is a drastic change in the file 'validate.js'(located in media\system\js) in 3.3.3 & above versions. And these changes have led to following problems:

-> The joomla! docs provide the syntax to write custom validation rules which work properly only untill 3.2.x versions.So, there is a need to re-write the documentation for the same.

-> The components & other utilities in joomla! administrator which are using custom form validation rules will have to re-work on the validation rules.

P.S. - May be this issue has something to do with the deprecation of mootools liabrary & gradually shifting towards jQuery as the file validate.js surely reflects it after 3.3.3 when compared with earlier versions.    

#### Steps to reproduce the issue

create a validation rule using document.formvalidator.setHandler

#### Expected result

It should work fine with joomla! 3.3.3 & successive versions. 

#### Actual result

It works properly only untill joomla! 3.2.x.

**Comment by vdespa** [comment]
Hi, the issue is a bit old and there are currently no update to it. Please check the documentation and create a new issues if this does not work in Joomla 3.4 or later as stated in the documentation: https://docs.joomla.org/Client-side_form_validation. Thanks for your understanding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4736">issues.joomla.org/joomla-cms/4736</a>.</sub>

**Comment by vdespa** [comment]
Set to "closed" on behalf of @vdespa by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4736">issues.joomla.org/joomla-cms/4736</a>
