### ISSUE TITLE
Change AJAX component for administrator modules functionality

### ISSUE THREAD

**Issue by kirapwn** [joomla/joomla-cms#4949]
#### Steps to reproduce the issue
Try to create module AJAX request for administrator app

#### Expected result
Run AJAX on admin module

#### Actual result
Looks only for site modules, using include in admin

#### Additional comments
The class should be refactored to add admin AJAX module support and to use Joomla! loader

**Comment by brianteeman** [comment]
It has been over a year since the last comment on this and with no code to evaluate I am closing this. It can always be reopened if in the future someone wants to propose some code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4949">issues.joomla.org/joomla-cms/4949</a>.</sub>
