### ISSUE TITLE
Pagination in frontend and backend work differently

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#5349]
Right now, the pagination of lists in the frontend and backend work differently. The backend relies on a form that has a hidden value "limitstart" and which stores this value in the session. That means, that you get returned to the same page of the article list you were on before you for example edited an article. I would like to propose to change the redirects in the Joomla backend to append the limitstart value to the URL and thus on the page to be displayed not relie on session data.

**Comment by brianteeman** [comment]
It has now been a year since this was posted with no further interest so I am closing it. If code is submitted then it can always be looked at again at that time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5349">issues.joomla.org/joomla-cms/5349</a>.</sub>
