### ISSUE TITLE
IE9 problem with placeholder in Email field - maybe html5fallback.js

### ISSUE THREAD

**Issue by fdesanto** [joomla/joomla-cms#5411]
#### Steps to reproduce the issue
Build a form with Joomla Jform API and add email field with placeholder, if placeholder not is a email the field is not validate if empty.

#### Expected result
if field is empty and not required the validation of email field should be ok

#### Actual result
empty email field is not validated

#### Additional comments
This happen only on IE9

**Comment by ggppdk** [comment]
In IE8 and IE9
  form.elements also contains function names
(code is supposed to take care of this ?? but it does not)


After calling  (exists in 2 places inside the file)
   var self = elem.form.H5Form;

We need to test if  "self"  is an object aka a form element, and do this:
   if (typeof self != 'object') return true;


The return true is needed so that function
  validateField(...)
will work properly

Tested fix, i will make a PR soon

**Comment by roland-d** [comment]
Closing this issue because a fix has been proposed in #5935 Thanks everybody.
