### ISSUE TITLE
RSS feed viewer crashes because of wrong RSS feed date

### ISSUE THREAD

**Issue by plappermaul** [joomla/joomla-cms#5419]
1) create an RSS feed page within Joomla 3.3.6

2) link to http://www.stotax-first.de/servlet/de.wmc.stv.xsearchips.stotax.Servlet?page=rss&bereich=arbeitsrecht

3) show page on webpage

4) side will crash with error "0 - DateTime::__construct(): Failed to parse time string (Fr, 12 Dez 2014 13:5:0) at position 0 (F): The timezone could not be found in the database"

Analysis shows that the feed provides a national (german) pubDate tag:

...
<guid>80082</guid>
<pubDate>Fr, 12 Dez 2014 13:5:0</pubDate>
</item>
...

source code that fills this data without any checks into the JDate constructor is

a) libraries/joomla/feed/entry.php line 76
 // Ensure that setting a date always sets a JDate instance.
 if ((($name == 'updatedDate') || ($name == 'publishedDate')) && !($value instanceof JDate))
 {
   $value = new JDate($value);
 }

b) libraries/joomla/feed/feed.php line 81
 // Ensure that setting a date always sets a JDate instance.
 if ((($name == 'updatedDate') || ($name == 'publishedDate')) && !($value instanceof JDate))
 {
   $value = new JDate($value);
 }

Is there any chance to mitigate the error?

**Comment by brianteeman** [comment]
I can confirm this issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5419">issues.joomla.org/joomla-cms/5419</a>.</sub>

**Comment by brianteeman** [comment]
I took another look at this and the issue is not with Joomla but with the feed itself being invalid 
see
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.stotax-first.de%2Fservlet%2Fde.wmc.stv.xsearchips.stotax.Servlet%3Fpage%3Drss%26bereich%3Darbeitsrecht

http://feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.stotax-first.de%2Fservlet%2Fde.wmc.stv.xsearchips.stotax.Servlet%3Fpage%3Drss%26bereich%3Darbeitsrecht<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5419">issues.joomla.org/joomla-cms/5419</a>.</sub>
