### ISSUE TITLE
[RFC] (In)Consistency in Isis UX

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#5522]
In Isis there is an inconsistency in UX interface: for most components (e.g. com_content) we now have the "Search Tools" above the items lists, but for others (e.g. com_newsfeeds) we still have the "Filter:" in the sidebar. See below:

![articles](https://cloud.githubusercontent.com/assets/552475/5554621/1e8aeb2c-8c68-11e4-8b1d-81e249623642.PNG)

![newsfeeds](https://cloud.githubusercontent.com/assets/552475/5554622/247099f6-8c68-11e4-87b7-330ba76d0e50.PNG)

Both solutions have their merits, but, IMHO, thanks to the renewed implementation of the sidebar, having the "Search Tools" in the sidebar makes more sense and represent a better usage of the available "real estate". I also find that having the various filtering fields stacked and grouped makes easier to check at first glance what we are searching/filtering for.

I have think to this only in terms of "visual" and UX and I haven't yet looked at the code, but being both the sidebar and the searchtools implemented through layouts, I think it would not be so difficult to to "merge" the two of them.

What do you think?

**Comment by tottello** [comment]
Everything on left is better, because now you can hide sidebar - (before that 'search tools' was ok)

Sidebar should have other icon imho, because 'x' icon is more for closing for good.

IMHO word 'select' in every select tag is not necessary. I always have to read more to find what I'm looking for.

![sidebar](https://cloud.githubusercontent.com/assets/8938743/5690564/8fe7cbb0-9892-11e4-8d96-e533c77a2877.jpg)

**Comment by richard67** [comment]
@tottello If the sorting section of the side bar would be labelled with "Order by:", as the filtering section is with "Filter by:", and it would also have a button to hide it at its top right corner, as the other 2 sections above have, then the side bar shown on the screenshot above would be closer to perfect ;-)

@all The above screenshot
+ my suggestions @tottello
+ rename of "Featured" button to "Feauture" and ading of "Unfeature" button as done with recent PRs
+ a new button for "Unarchive"
+ a new list view "Archived Articles" as we have for "Featured Articles"
+ consistent ordering e.g. of sort and filter options and displayed columns in the Articles, Feautred Articles and Archived Articles lists
=> Perfect in my opionion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5522">issues.joomla.org/joomla-cms/5522</a>.</sub>

**Comment by tottello** [comment]
I updated the view. Another suggestion is to change color for current menu item on left. (for me current - long blue - version is little bit too much eye catching.
Two versions of current item background: white and gray.
![sidebar_gray](https://cloud.githubusercontent.com/assets/8938743/5713235/41d2c22a-9aba-11e4-9d34-72d0c170f498.jpg)
![sidebar_white](https://cloud.githubusercontent.com/assets/8938743/5713339/4bf69078-9abb-11e4-912b-3b13651b54fb.jpg)

**Comment by brianteeman** [comment]
Personally I really dont like this removal of the search tools back to the
side from above the content where to me it is more logical

On 12 January 2015 at 23:32, tottello <notifications@github.com> wrote:

> I updated the view. Another suggestion is to change color for current menu
> item on left. (for me current - long blue - version is little bit too much
> eye catching.
> Two versions of current item background: white and gray.
> [image: sidebar_gray]
> <https://cloud.githubusercontent.com/assets/8938743/5713235/41d2c22a-9aba-11e4-9d34-72d0c170f498.jpg>
> [image: sidebar_white]
> <https://cloud.githubusercontent.com/assets/8938743/5713339/4bf69078-9abb-11e4-912b-3b13651b54fb.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5522#issuecomment-69668358>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by tottello** [comment]
Still something should be done in other components

**Comment by brianteeman** [comment]
I agree - they should all use the search tools like in com_content as was originally proposed by the UX group

**Comment by Hackwar** [comment]
And I would ask to re-evaluate that decision, especially after working with com_content a lot more recently and finding the search tools to be not very usable, to state it mildly.

**Comment by brianteeman** [comment]
I 100% disagree - what is it you dont like - for me what I like is that they are positioned where i expect search tools to be - by the search and that they are above the columns that I am going to be filtering

**Comment by richard67** [comment]
We should have a voting tool for such decisions so the community can vote with 1 click - just to see what they all think about it.

**Comment by JoomliC** [comment]
The issue today is no consistency, an known issue, recently debated when we were working on the sidebar show/hide.
In the sidebar or on the top? There are pros and cons, and eveyone is right!
Just the goal to achive is too have all (submenus, search tools, ordering...) in the same place, i mean if all on the top, no "sidebar", if sidebar, no buttons on the top.

:+1: @totello's proposal (already a long discussion in the sidebar PR) to have all in the sidebar is a good one.
:+1: @brianteeman request to keep search tools button is a good one (and work done on search button is a good one, with possible little improvement).

Why not a switch button ?
Having search separated from search tools button, and having things on left in the same time as things on top, that's where there's an issue.

It's really possible to add all to the "sidebar" container and have a 2-display-type switch button:
- one to have all in sidebar on the left (or right on RTL)
- one with all (submenus included as a dropdown like search tools button) on the top (and could be used for the 2 options on small devices).
The user could have the choice, and change this choice when he needs.

@richard67 I'm sure that with a voting system, it will be almost a 50/50 results, because the 2 ones are good, all depends on the way you use and manage a joomla admin. ;-)

**Comment by nternetinspired** [comment]
I agree that there should be consistency throughout, and I think we can all agree on that. Good UX is built largely upon consistency and expectation.

However, whilst I do think that there are significantl usability improvements that can be made to com_content search tools I do think that they are in the right place. 

Filters belong at the top of the items they are filtering. Like headings for table columns, they belong above the list of items they act upon.

Given free reign over the admin UI the first thing I would do is to remove the sidebar completely. The sidebar complicates UX substantially and is a significant UI design complication. Sidebars were a common design feature in a pre-responsive world, but the world moved on. We're no longer designing for desktops, or even mobile for that matter.

Either primary navigation is in a sidebar, or it is in a top bar. It should never, ever, be in both.

**Comment by brianteeman** [comment]
+10

On 16 January 2015 at 00:28, Seth Warburton <notifications@github.com>
wrote:

> I agree that there should be consistency throughout, and I think we can
> all agree on that. Good UX is built largely upon consistency and
> expectation.
>
> However, whilst I do think that there are significantl usability
> improvements that can be made to com_content search tools I do think that
> they are in the right place.
>
> Filters belong at the top of the items they are filtering. Like headings
> for table columns, they belong above the list of items they act upon.
>
> Given free reign over the admin UI the first thing I would do is to remove
> the sidebar completely. The sidebar complicates UX substantially and is a
> significant UI design complication. Sidebars were a common design feature
> in a pre-responsive world, but the world moved on. We're no longer
> designing for desktops, or even mobile for that matter.
>
> Either primary navigation is in a sidebar, or it is in a top bar. It
> should never, ever, be in both.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5522#issuecomment-70189150>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
Having the searchtools on top was a decision made with Joomla 3.2 (I think). Reverting that now would confuse users and that is certainly wrong.
I also think it's the right place and much better than what we had before in the side bar. I still remember that user were unable to spot them there since it's wasn't an intuitive place.

I agree that we need consistency. But for me that means adding searchtools to the other extensions. Not reverting them to the sidebar.

As for voting: Since we don't have a way to request votes from a relevant part of our users, it would not give us a true result.
We have to build on the feedback from UI/UX experts, which resulted in what we have now.

Like Chris stated long ago: If we want to go back to the sidebar, there should be strong points based on UX testing. Not because some developer thinks it looks prettier there.
Back it up with links to such tests or prominent example where it is used that way (like Google Search which uses search tools on top).

**Comment by Bakual** [comment]
As for a toggle: There is a big NO from me to having yet another stupid toggle.

**Comment by Hackwar** [comment]
I think we can all agree that we want consistency and that we don't want to have a toggle/switch/parameter/whatever is also pretty much accepted.

@brianteeman What I don't like is, that right now the searchtools are hidden by default. People will not spot those as much as they didn't spot them in the sidebar in the past. The button for the searchtools is simply not visible enough. In com_content it is not the first element in the first row and "column" above the list table. It is also not the last element above the list table. I simply can't click on something to load the list view and already position my eyes on the spot where I think that button will be, because that position is not consistent. If it were in one of the corners, that would make that aspect better.
However that brings me to my bigger issue: By having the filters hidden by default, I have to do at least one mor click in order to set a filter and that is something that I don't like. 

Those are the two things that bug me the most right now: Difficult to spot and requires more clicks than in the sidebar.

There are however more things that I think are wrong here. In the specific implementation in com_content, there are filters where I question their existence. If you don't have a multi-lingual site, the language filter does not make sense. For a site that does not use tags, the tags filter does not make sense. Quite frankly, as a simply user I would not understand what "Select max levels" means as a filter dropdown.

I can understand that the right place for filters is above the list and would simply believe the UX experts here. But I'm saying that our system right now is less usable, at least for me, than the sidebar filters.

**Comment by nternetinspired** [comment]
> As for a toggle: There is a big NO from me to having yet another stupid toggle.

+100

> If you don't have a multi-lingual site, the language filter does not make sense. For a site that does not use tags, the tags filter does not make sense. Quite frankly, as a simply user I would not understand what "Select max levels" means as a filter dropdown.

Agree, 100%. We should never show irrelevant options. Personally, I don't see how max-levels is ever useful, I've certainly never used before, but maybe that's just me.

**Comment by brianteeman** [comment]
As for the language filters the UX sprint also submitted a PR at the same
time as search tools to do exactly that but it was not accepted

**Comment by Hackwar** [comment]
@nternetinspired It took me some time, but I guess the idea is to show articles from a category and its children up to a certain level. I can see the use for that, but I would rather expect a toggle button that is visually grouped with the category dropdown instead of the current additional dropdown.

I also wanted to make clear that I have no intent of just bitching around about all that is wrong. I am looking for ways to improve this and see my statement above as a means to provide you some input what I think does not work. So let me try to give you some ideas on how we could improve this:

1. Lets remove stuff like language from the list view when the site is not multi-language. It would also be interesting to have this removed from the actual edit view. Or is there another use for the language in a mono-language site?
2. Remove the "select max levels" filter by a toggle that is appended to the category dropdown to either display or hide the articles from child-categories. Please notice that bootstrap currently does not seem to support this on select boxes. Since we are using chosen everywhere, would that solve that issue?
3. Add a method to a language class that takes a query and optionally a table name and an alias, that adds selecting the right language based on if the site is multi language or not and if not, simply returns * all the time. That way we stay backwards compatible and have a consistent state in both mono- and multi-language sites.

I think in general we need a way to disable options altogether. If my site does not need the timed publishing feature, I can disable that globally and I have 2 form elements less in my article edit view and 4 WHERE clauses less in my queries. Disabling the print/mail icons globally would also remove another 3 form elements from my system. As I wrote earlier, our edit screens are too complex and it would be good to slim them down. For example, we have around 105 form elements (depending on associations, etc.) on the article edit screen, excluding the editor itself. I'd say that we would have to be able to cut that by half and it would still be a lot. Please be reminded that I'm not asking to remove functionality here, but to allow to disable features globally, so that they don't show up each time I work on a content item.

**Comment by brianteeman** [comment]
Re points 1 and 3
We tried and it was not accepted. Coincidentally I am planning on
resubmitting that next week and have been checking the code with
@phproberto only yesterday.

Re point 2
I am not sure I understand

**Comment by Hackwar** [comment]
Re 2: In com_content you have a filter for the category. Next to that filter is another filter that allows you to select a level of child-categories from that first category. This most likely simply lets you display the articles from that category and its child-categories up to a certain level. I think that such a filter is useless for 99.999% of our users and they would instead already be helped with a switch that either does or does not display the articles from child-categories.

Now Bootstrap allows you to append controls to form elements, so that they are visually grouped. For example the button sticking directly to the text input. While this works great for all form elements, the select element is excluded from that, at least in BS2, according to their docs. The question now was, if it might still work since we use chosen, which replaces the select with a more complex HTML structure, but which might work correctly with that append thingy from BS. In any case, we simply have to test this. :smile:

**Comment by brianteeman** [comment]
Right the code and it can be tested :)

**Comment by nternetinspired** [comment]
> I think that such a filter is useless for 99.999% of our users…

I agree, and I think we need to take a long hard look at options like this and balance any potential utility they have against the UX benefits of a cleaner, more intuitive, UI.

A user-friendly UI does not have 1001 options. It's that simple. I *am* in favour of completely removing the items that .001% of people may use but that damage the UX of the 99.999%.

**Comment by infograf768** [comment]
Concerning the language filter: if I remember well, it was decided to keep it to let users know Joomla has a multilingual functionnality. 
Someone may very well start using a monolanguage site, add content languages and prepare all to change the site to be multilingual (except the home pages until the last minute), WITHOUT enabling yet the language filter plugin.
I am therefore not in favor of hiding the field.

**Comment by nternetinspired** [comment]
> Concerning the language filter: if I remember well, it was decided to keep it to let users know Joomla has a multilingual functionnality. 
Someone may very well start using a monolanguage site, add content languages and prepare all to change the site to be multilingual

The installer prompts for the installation of additional languages, letting the user know this is possible: 

![screen shot 2015-01-16 at 11 07 09](https://cloud.githubusercontent.com/assets/1090182/5775288/f389220e-9d6f-11e4-901d-a877774c9212.png)

Couldn't we hide language filter options until additional languages are installed?

**Comment by Hackwar** [comment]
@infograf768 I see your concern and would conter that with a request to have a tutorial system in the core and/or a guiding system, where you can select different things like "I want to create a multi-language site" or "I want to have SEF URLs" and Joomla guides your through the process step by step. We could use something like Amberjack2 for this: http://amberjack2.org/

Saying all this: It could be part of a greater strategy to slim down, speed up and improve the Joomla UI.

**Comment by infograf768** [comment]
>The installer prompts for the installation of additional languages, letting the user know this is possible: 

Indeed, this did not exist when we discussed the issue.

>Couldn't we hide language filter options until additional languages are installed?

Additional languages as such can be used in a monolanguage site.
Additional "Content Languages" may not, except that some distros released by language communities do include both en-GB and xx-XX AND add their related "Content Language".
Therefore, if we were conditionning the display of the language field to the existence of multiple items in the _languages table, we would not act right.

Let's keep the language field in the 3.x series.
IMHO, the whole multilingual system should be reviewed for 4.0. 
For example, I think we could have a switch in the Global Configuration plus regroup many aspect of multilingual (including managing associations and editing associated items) in a single core component.

**Comment by Hackwar** [comment]
@infograf768 I don't think it is wise to postpone changes to any of our systems to 4.0. As far as I can see it, the move from 3.x to 4.0 will in 90% of the cases be simply the point where we drop backwards compatibility for old stuff. But the new stuff has to be already in place. This covers routing, language stuff, MVC classes, etc.

**Comment by infograf768** [comment]
As long as we are B/C, I do not think anybody, including myself, will oppose to evolution.

**Comment by JoomliC** [comment]
After reading all your comments, with so different opinions, but with full of good suggestions and ideas, i think Joomla as implicated volunteers, but Joomla needs to have more feedback and testing of UX from end users, not developer or beginner.

We have Joomla! events, where many active contributors (developers, testers, advanced users...) are attending.
Why not create a Joomla! UX Day event, open to public with limited places but free entry, where a end user comes and will be ask to achieve different tasks (create an article, search for something...), where a skilled user checks the way a user succeeds or not, the difficulties he had, what he achieved with no issue, and what he was searching too long?

:+1: for Consistency
:+1: for simplicity / flexibility / usuability for ALL users (not only skilled users)

**Comment by tottello** [comment]
Sure thing for me is:
 - eliminate word "Select" from filters
 - show filters only when they can improve searching (dont show Language filter And Language column if site is not multilangual)

What I suppose is good UX will be something different for different users. For someone who is starting using Joomla a lot of visible options could be overwhelming. Even for more advanced users in simple sites there is no need tu put all options visible. But it should be an option to do that.

If we assume that is better to hide to many options (and only some users can reach them by some toggle - like 'Search tools' or other system option) than why not to hide propably all buttons beside "New"? 

Sidebar just as a another menu is not a good idea. For me other menu items could be below Top Bar. 

Some preview to make discussion even more interesting ;-)

![sidebar_top](https://cloud.githubusercontent.com/assets/8938743/5791468/91cff538-9ed7-11e4-80a5-81adb6c0e738.jpg)
