### ISSUE TITLE
mootools-more.js conflicts with Bootstrap carousels

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#5527]
This is a re-opening of https://github.com/joomla/joomla-cms/issues/475

This has recently been re-discovered in the joomla-dev-general Google Group/Mailing list where a developer reported having issues with a BS-based slideshow module he developed, and thus is still a current and valid issue.

**Comment by nternetinspired** [comment]
Mootools-more and Boostrap are incompatible. End of story.

Neither libraries have attempted any sort of fix (in fact both refused to do so) so neither should we.

**Comment by SergioCrisostomo** [comment]
Just in case it can be usefull there is a UI library using MooTools based on Bootstrap: https://github.com/Behavior-UI/behavior-ui

**Comment by pinta83** [comment]
> ?=`...This has recently been re-discovered in the joomla-dev-general Google Group/Mailing ...`

Rediscovered????? Are you kidding me ?

It's never been fixed, altough u have a fix in [https://github.com/joomla/joomla-cms/issues/475](#475)

**Comment by brianteeman** [comment]
@pinta83 you are commenting on a closed issue that no one will see

**Comment by pinta83** [comment]
Whatever, no one cares about it anywayz......

**Comment by nternetinspired** [comment]
No one should be using Mootools + Bootstrap(jQuery) at the same time. 

Why would Joomla want support that when both Mootools or Bootstrap projects have said it shouldn't be done??

**Comment by mbabker** [comment]
> Why would Joomla want support that when both Mootools or Bootstrap projects have said it shouldn't be done??

Because when 3.0 released Joomla was still heavily dependent on MooTools for its JavaScript API.  It's less of an issue today but there are still extensions and a few core systems requiring MooTools.

Considering Joomla's already forked and hacked away at Bootstrap (without documentation, ever tried implementing event handlers on some of Bootstrap's hide events and wonder WTF it doesn't work?), at this point Joomla has accepted full responsibility for maintaining the Bootstrap JavaScript APIs because it wanted to create a MooTools and jQuery/Bootstrap friendly environment so since the project has taken it upon itself to create said fork it should resolve whatever incompatibility issues exist or whatever bugs have been introduced by creating said fork.
