### ISSUE TITLE
UI issues since addition of unfeature

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5600]
Ref /index.php?option=com_content&view=articles

Since #5485  was committed it is now no longer possible to have a single row for the toolbaar in any resolution below 1136px
Before #5485  was committed it was possible to still have a single row for the toolbar all the way down to 1019px

(exact px as reported by chrome on OSX they might vary slightly on different browsers)

I would like to propose that this extra button is removed from the article view (it is already present for the featured view and the rename from remove to unfeature that was also made in #5511  is a good addition)

Finally if you really insist on adding this useless button then shouldnt we also have a button for unarchive

**Comment by infograf768** [comment]
A difference of a hundred pixels does not justify taking off that nice improvement.
Many languages already got 2 rows at this size before #5485.

Concerning Unarchive, we can filter by Archive to change the display, which was not possible for Featured in that Manager. Also, that function is very rarely used, contrary to Featured/Unfeatured.

**Comment by brianteeman** [comment]
> A difference of a hundred pixels does not justify taking off that nice improvement.  

Is it really an improvement. The OP was mistaken in thinking it wasnt possible to unfeature multiple items at once. Thats why he made the PR. It is possible using the feature manager and now that the toolbar and another bug has fixed in the feature manager it works perfectly

>  Many languages already got 2 rows at this size before #5485.  

My concern is only for the default en-GB

> Concerning Unarchive, we can filter by Archive to change the display, which was not possible for Featured in that Manager.

There is no need to filter as we have a permanent filter for featured items. This doesn't change the fact that there is no unarchive toolbar button anywhere. I mention this just as an example that we do not always have buttons for all actions


> Also, that function is very rarely used, contrary to Featured/Unfeatured.

That is a personal statement and not one that can be backed up with statistics

**Comment by richard67** [comment]
If it will be decided to remove the "Unfeature" button introduced with #5485 for the articles view, then please keep in mind that it would **not** be ok just to revert that PR, because the changes in the 5 CSS files on administrator/templates/hathor/css/ are needed also for the "Unfeature" button in the featured articles view, which has been renamed from "Remove" with PR #5511 . Therefore in this case only the change in administrator/components/com_content/views/articles/view.html.php has to be reverted.

Regarding my opinion on this issue here: infograf768 said it all, see above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5600">issues.joomla.org/joomla-cms/5600</a>.</sub>

**Comment by infograf768** [comment]
>My concern is only for the default en-GB

This does not deserve any comment except that it is sad to read that here.
