### ISSUE TITLE
update option - Currently configured (no change)

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-cms#5614]
3.4 site configured to use Testing server.

What is the option "Currently configured (no change)" for please? I assumed it could be chosen if I looked at the options and decided not to change. If this isn't so, what is it supposed to do?

Message if I choose that option:

![update-warning-message](https://cloud.githubusercontent.com/assets/736887/5607005/17a177e2-9440-11e4-984c-8b788ddd6c06.PNG)

Thanks from Hils

**Comment by Bakual** [comment]
From what I remember it will not show you an update at all. It will stay on the version you have installed.
But I would have to check to be sure :smile:

**Comment by Hils** [comment]
Thanks for checking Thomas. That is what I would have expected but I wouldn't have expected that rather scary "You are not connected..." message - is that right?

**Comment by Bakual** [comment]
I just checked and it's indeed the case. You will be disconnected from an update stream, essentially disabling the Joomla Update component and you will not get any update at all for Joomla as long as you have that setting selected.

So the message in fact should be even more scary :smile: 
You should only choose this if the server runs on an isolated network where it couldn't connect to the update stream anyway. Other than that I don't see any reason for that setting.

**Comment by mbabker** [comment]
I still say everyone's trying to force the option to do something it wasn't designed to do.  If you read the code from the first release it was included (2.5.4), the method [applyUpdateSite](https://github.com/joomla/joomla-cms/blob/2.5.4/administrator/components/com_joomlaupdate/models/default.php#L32-L96) method specifically checked for this "nochange" option and by the way the code reads, made zero changes to the update site configuration.  Apparently that wasn't clear enough as [in current staging](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/models/default.php#L30-L96) the method resets the update site option.  But, that's a choice other people seem to agree with so I'll butt out from here; my main point is that option's being screwed around with in ways it wasn't intended to be.

**Comment by Hils** [comment]
But it says (no change) yet change does happen. It doesn't leave me in the state I arrived in eg in my case, on the test server. So when/why would that option be used? The message perhaps should be changed to describe that use?

**Comment by Hils** [comment]
...and if it is just a 'don't change what I am using at the moment' choice, what is the point when there is the usual save button available at the top.

**Comment by sovainfo** [comment]
Considering it is pointing to an update server, it should have been 'None'. Meaning it shouldn't use any update server. Which results in not checking whether there are updates.

**Comment by richard67** [comment]
The update option "Currently configured (no change)" shoud have been removed with the merge of PR #5547 in current staging, or not?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5614">issues.joomla.org/joomla-cms/5614</a>.</sub>

**Comment by sovainfo** [comment]
No, it is not removed. The functionality was changed and for some strange reason accepted!

**Comment by Hils** [comment]
So are this issue options? :

1. Leave "Currently configured (no change)" as a server option but make the label more understandable and the view that follows more explanatory. (At the moment it makes no sense and giving a warning after a completed action doesn't seem correct - see screen shot above).

2. Remove this option as (no change) is incorrect and a normal user wouldn't understand it or use it. (I am assuming that if it is no longer an option it won't make a difference and really isn't required to work eg offline).

**Comment by mbabker** [comment]
Apparently the option was deleted and the behavior for its saved value
changed for reasons beyond my understanding.  Right or wrong, the text for
the option and the use I demonstrated in the code shows exactly what that
option should have done; made no changes whatsoever.  Apparently the option
was disabling the update system completely.  So instead of fixing that bug,
we just remove the option completely and make a B/C breaking change to the
value's handling that forces Joomla to make a change to the update URL.
 *shrug* this is why I try to not make decisions on PRs anymore

**Comment by Hils** [comment]
So is it wrong? Looks like people agree it is! So we need a decision as to what happens now - nothing or 1 or 2 or something else?

**Comment by Bakual** [comment]
> the code shows exactly what that option should have done; made no changes whatsoever

I never really understood the purpose of the option myself. Imho disabling the Joomla Updater makes most sense to me.
Why would we need an option to make no changes when the user as well just can click the cancel button of the form? But then, we have a lot of funny code in our CMS :smile:

**Comment by infograf768** [comment]
+1 @Bakual 
anyone for a patch?

**Comment by richard67** [comment]
I still do not understand what you are talking about.
After a clean install of **latest staging** there is no option value "Currently configured (no change)":
![screen shot 2015-01-05 at 07 03 36](http://issues.joomla.org/uploads/1/45d5322f278d5d69131c46e4ea30ff19.png)
Any previously adjusted value different to the available values will be set to "Default" when upgrading a Joomla <= 3.3.6.
So what do we need a patch for?
This issue here is obsolete, or I do not understand something wrong?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5614">issues.joomla.org/joomla-cms/5614</a>.</sub>

**Comment by Bakual** [comment]
You are right. My testing server was outdated, probably because our master is behind (Jenkins is broken atm). Once updated to staging, the issue no longer exists.

**Comment by infograf768** [comment]
oops. closing now.

**Comment by Hils** [comment]
Excellent - thank you everyone :)
