### ISSUE TITLE
Regression "Create New User:: error message order"

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5625]
-Go to create new user form view
-Do not enter any value click on save button
-Check the error message order
![screen shot 2015-01-06 at 03 46 39](http://issues.joomla.org/uploads/1/b0b1be757ac95ea31165ee9ec7328414.png)

**Comment by brianteeman** [comment]
This is a regression - it works perfectly in Joomla 3.3.6

Because it is a regression I am going to raise the level to medium as "perhaps" the cause effects other areas.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5625">issues.joomla.org/joomla-cms/5625</a>.</sub>

**Comment by brianteeman** [comment]
I can no longer replicate this issue. It must have been resolved elsewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5625">issues.joomla.org/joomla-cms/5625</a>.</sub>
