### ISSUE TITLE
Inconsistency in text format for the filters.Refer the snap

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5657]
#### Steps to reproduce the issue
1. Go to the article manager. 
2. Click on Search tool. See the difference between the second word's first letter of all filters 
3. Also check the filter name "**Sort Table By"**

#### Expected result
1. Filter name It should have the same consistent 
2. All second word's, first letter should be capitalized so that it will look consistent for all filters
![screen shot 2015-01-10 at 01 01 14](http://issues.joomla.org/uploads/1/e8f43d6cf81835b89306ed42ccdb0998.png)

#### Actual result
1. Some filters seconds word's first letter are different see the snap.

**Comment by brianteeman** [comment]
I havent checked but This should be resolved by #5615
Steps to reproduce the issue

1.Go to the article manager.
2. Click on Search tool. See the difference between the second word's first
letter of all filters
3. Also check the filter name Sort Table By
Expected result

   1. It should have the same consistent
   2. All second word's first letter should be capitalized so that it will
   look consistent for all filters [image: screen shot 2015-01-10 at 01 01
   14]
   <https://camo.githubusercontent.com/18afe42c40124bba0727c292c3af6b58cc52939d/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f65386634336436636638313833356238393330366564343263636462303939382e706e67>
   #### Actual result
   3. Some filters seconds words first letter are different see the snap.

System information (as much as possible) Additional comments

—
Reply to this email directly or view it on GitHub
<https://github.com/joomla/joomla-cms/issues/5657>.

**Comment by uthorat** [comment]
Thanks for the feedback. :)
I checked the #5657 but did not find this issue.
Please check once from your side and make it done.

Warm regards,
Umesh Thorat

**Comment by brianteeman** [comment]
Sorry I was checking from my phone. This is indeed not changed.

I will raise this with the WG

On 10 January 2015 at 09:57, umesh <notifications@github.com> wrote:

> Thanks for the feedback. :)
> I checked the #5657 <https://github.com/joomla/joomla-cms/issues/5657>
> but did not find this issue.
> Please check once from your side and make it done.
>
> Warm regards,
> Umesh Thorat
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5657#issuecomment-69450390>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uthorat** [comment]
Thanks  @brianteeman :smiley: 
To give an prompt action :)


Warm Regards,
Umesh Thorat<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5657">issues.joomla.org/joomla-cms/5657</a>.</sub>

**Comment by brianteeman** [comment]
See #6869<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5657">issues.joomla.org/joomla-cms/5657</a>.</sub>
