### ISSUE TITLE
Protostar menu don't support more than 2 levels on position-8

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#5676]
#### Steps to reproduce the issue

- install Joomla 3.3.6 or staging with testing sampledata
- move the module `A deep Menu` from position `position-7` to `position-8` 

#### Expected result

protostar also support on `position-8` more than one level

#### Actual result

protostar only support on `position-8` one/two level

##### `position-8`
![screen shot 2015-01-11 at 13 20 44](http://issues.joomla.org/uploads/1/bf9f3a9b7a7964b5eadbf6a18a7fb69c.jpg)
##### `position-7`
![screen shot 2015-01-11 at 13 20 44](http://issues.joomla.org/uploads/1/ec878c6fe12001223691612cff4a4061.jpg)

#### Joomla Bugs Reference

http://www.joomla-bugs.de/forum/index.php/topic,636.0.html

**Comment by brianteeman** [comment]
Are you saying it is missing the | in the styling? Because the menu items display correctly as far as i can tell<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5676">issues.joomla.org/joomla-cms/5676</a>.</sub>

**Comment by brianteeman** [comment]
If thats what you are saying then thats just a matter of template style and expected behaviour

the | in the style is coming from the id `aside` which position 7 is in whereas position 8 is in id `sidebar`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5676">issues.joomla.org/joomla-cms/5676</a>.</sub>

**Comment by zero-24** [comment]
Yes this missing `|`; So we don't support more than 2 levels (with styling) for position-8?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5676">issues.joomla.org/joomla-cms/5676</a>.</sub>

**Comment by brianteeman** [comment]
The levels ARE there it is just the styling.I suspect looking at the reason
for the missing styles that this will be true in many module positions

On 12 January 2015 at 07:22, zero-24 <notifications@github.com> wrote:

> Yes this missing |; So we don't support more than 2 levels (with styling)
> for position-8?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/5676
> <http://issues.joomla.org/tracker/joomla-cms/5676>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5676#issuecomment-69535965>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
My feeling is that this should be closed as expected behaviour as it is a styling choice made in the template and not really a code issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5676">issues.joomla.org/joomla-cms/5676</a>.</sub>

**Comment by zero-24** [comment]
Closing as `Expected Behavior` as per comment by @brianteeman Thanks for have a look into it :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5676">issues.joomla.org/joomla-cms/5676</a>.</sub>
