### ISSUE TITLE
TypeError: Class is not a constructor in autocompleter.js

### ISSUE THREAD

**Issue by ronniee** [joomla/joomla-cms#5693]
Hi,

I have enabled Smart Search in Joomla 3.3.6 following this tutorial https://docs.joomla.org/Smart_Search_quickstart_guide. But, auto-suggestion does not show up. In browser console, there are errors **TypeError: Class is not a constructor** in autocompleter.js

I have checked media\com_finder\js\autocompleter.js, it seems autocompleter.js is not changed at all while indexer.js is changed completely in joomla latest release. You can check the error here http://taxibookingpro.com.

I don't know what I am doing wrong, please help.

Thanks in advance

**Comment by chrisdavenport** [comment]
On your website the JavaScript which calls the autocompleter does not appear to be waiting for the autocompleter itself to finish loading.  Compare with this: https://github.com/joomla/joomla-cms/blob/staging/modules/mod_finder/tmpl/default.php

Perhaps you have a layout override for mod_finder that needs updating?

Instead of
    jQuery(function($)

you should have
   jQuery(document).ready(function()

or something like that.

**Comment by apachesep** [comment]
Dear 
I have migrated the com_finder / mod_finder from mootools to jquery. first it works. thanks
but there is an issue. my language is Chinese. I type Chinese into input element(one Chinese char only). the autocomplete cannot work normally. suggestion is disappeared. English and number are work very well. I check the outcome of ajax call. there are data from server and the format is correct and charset is correct as well. my Joomla is 3.3.6.

Dose jquery-autocomplete supports CJK? This is my question. How I can overcome this issue.
Thanks

Martin

**Comment by apachesep** [comment]
Dear 
Again
I try to narrow the problem.

a. i try to verify the outcome of ajax. English / number / chinese are OK.

It means I can get objects of suggestions and query in English and Chinese
onSearchComplete: function (query, suggestions) {
	console.log(query);
	console.log(suggestions);
},


b. I try to format the result before it s displayed
English / number OK.
Chinese is not OK. It means I cannot get objects. it is [](empty array).

formatResult: function (suggestion, currentValue) {
	console.log(suggestion);
	console.log(currentValue);
}

MARTIN

**Comment by chrisdavenport** [comment]
Thank you for reporting this problem.  There are known issues regarding Chinese in the current release.  I'm not sufficiently knowledgeable about Chinese to confidently address these issues on my own, but if you can work with me to fix and test the issues then we can improve Chinese support for everyone.  I'm closing this issue because it is not clearly defined enough to identify the problem.  Please contact me on chris.davenport at joomla.org if you can help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5693">issues.joomla.org/joomla-cms/5693</a>.</sub>

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5693">issues.joomla.org/joomla-cms/5693</a>
