### ISSUE TITLE
Don't allow the multiple selection for edit. Give the alert box about select only one record

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5703]
#### Steps to reproduce the issue
1. Go to the any list view ( lets say in article list view)
2. Select multiple articles and click on edit
3. It choose the very first article

#### Expected result
Should have alert box showing the notice about select only one record for edit

#### Actual result
No alert box is present. Edit the very first record![screen shot 2015-01-13 at 01 26 45](http://issues.joomla.org/uploads/1/65b554c489996d802ad3be34cba807b3.png)

**Comment by zero-24** [comment]
confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5703">issues.joomla.org/joomla-cms/5703</a>.</sub>

**Comment by dgt41** [comment]
Its easier if we remove the edit button altogether 😜

**Comment by uthorat** [comment]
Nice thought :+1:  
But is it safe ? Because as per your thinking we are directly use link for edit the article.

**Comment by Fedik** [comment]
do not bother people with useless alerts, 
I more liked @dgt41 idea

**Comment by dgt41** [comment]
@uthorat This can be easily solved if we add the edit option in every item in the respective drop down:
![screen shot 2015-01-17 at 6 21 15](https://cloud.githubusercontent.com/assets/3889375/5789492/c06a396a-9e75-11e4-8e9b-de13e9a08be7.png)

Taking this idea even further I will suggest a new layout for the buttons on the toolbar:
New, Commands, Help, Options
where Commands is a dropdown (on hover!) that reveals: Publish, Unpublished, Feature, Unfeature, Archive, Unarchive, Trash and batch
This way we ALWAYS get a small number of buttons that can easily render even in mobile

Also in the column Status of the list instead of two small buttons and a dropdown we can introduce again a dropdown with all the commands

**Comment by uthorat** [comment]
@dgt41 looks great !!!!
No confusion now ;)

I agree with the @dgt41
