### ISSUE TITLE
Users -> user notes -> Is time field is needed in table view.

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5706]
#### Steps to reproduce the issue
1. Go to the user-> user notes
2. Check the list of user notes

#### Expected result
Time field is not needed.
If is time field is needed then show it correctly.

#### Actual result
Time field is shown 00:00:00![screen shot 2015-01-13 at 05 43 40](http://issues.joomla.org/uploads/1/84cec1ac19955daf865ff5d8d0e23c6d.png)

**Comment by brianteeman** [comment]
Well spotted - there are a few bugs here

The field you set the review date in is labelled Review Time
You can not set the time only the date which is why in the list view
(correctly labelled Date) you see 00:00 as the time

The field name needs to be changed to Review Date
And the list view needs to be changed to only space the date not the date
and time

**Comment by uthorat** [comment]
Yes ,The label issue also spotted but its resolved on #5534

**Comment by brianteeman** [comment]
Thats what happens when I dont check on staging ;)

On 13 January 2015 at 14:07, umesh <notifications@github.com> wrote:

> Yes ,The label issue also spotted but its resolved on #5534
> <https://github.com/joomla/joomla-cms/pull/5534>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5706#issuecomment-69748321>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
See #5714 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5706">issues.joomla.org/joomla-cms/5706</a>.</sub>
