### ISSUE TITLE
Extension Manager: Update :: Hide 'Filter' & 'records per page drop-down' option, If there is no update available

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5779]
-Unnecessarily Filter & records per page drop down is placed, when there is no update available

![screen shot 2015-01-17 at 03 14 39](http://issues.joomla.org/uploads/1/6b7f8a163d27f1ed275d1f7a7f2e8090.png)

**Comment by brianteeman** [comment]
I am closing this as it the current expected behaviour in Joomla that options, buttons and filters are always visible and not enabled or disabled depending on their context.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5779">issues.joomla.org/joomla-cms/5779</a>.</sub>
