### ISSUE TITLE
Extension Manager: Discover :: Unnecesarily records per page button & filter option are placed, when there is no discovered extension

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5780]
-Hide the 'records per page button' & 'filter' option, If there is nothing

![screen shot 2015-01-17 at 03 17 36](http://issues.joomla.org/uploads/1/4776cdcd0c96373bc4eec34450450976.png)

**Comment by brianteeman** [comment]
We dont do that anywhere else do we?

On 17 January 2015 at 09:19, Aasim Ali <notifications@github.com> wrote:

> -Hide the 'records per page button' & 'filter' option, If there is nothing
>
> [image: screen shot 2015-01-17 at 03 17 36]
> <https://camo.githubusercontent.com/5d490bf329adf061efec04b5c6776c95945e04df/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f34373736636463643063393633373362633465656333343435303435303937362e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5780>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aasimali** [comment]
@brianteeman 
Yes! we haven't done that anywhere but introducing this will be a nice thing as per tester points of view.

**Comment by Bakual** [comment]
The list limit would be possible easy, but the filters would need some thoughts.
You could only hide the filters if no filter is active and there is no result. As soon as a filter is active, you may get an empty list because of the applied filters, and you need to be able to reset/change them.

Imho it would make the code checks quite complicate to achieve almost nothing.
Imho, it's fine to have the UI elements always visible to avoid confusion and have a consistent UI.

**Comment by brianteeman** [comment]
Closing this for the reasons stated above by @bakual <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5780">issues.joomla.org/joomla-cms/5780</a>.</sub>
