### ISSUE TITLE
Extension Manager: Install>Upload & Install Joomla Extension :: Message is not usable, when, Joomla is unable to find package (Message text should be 'red')

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5786]
Go to 'Extension Manager: Install'
Select 'Upload & Install Joomla Extension' tab
Upload unsupported format (exapmle: .jpg,.txt etx)
It will display a message, Which is not usable

![screen shot 2015-01-17 at 04 56 45](http://issues.joomla.org/uploads/1/a14b6032d1f14c31b6404548da85f0bd.png)

**Comment by vdespa** [comment]
Is it possible to provide such an extension which generates this error? It will help fixing the issue. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5786">issues.joomla.org/joomla-cms/5786</a>.</sub>

**Comment by infograf768** [comment]
@vdespa 
Just browse to a .jpeg file instead of a .zip.

The issue comes from the use of this code:
`$app->setUserState('com_installer.message', JText::_('COM_INSTALLER_UNABLE_TO_FIND_INSTALL_PACKAGE'));
`
instead of using a simple `$msg = `

in ROOT/administrator/components/com_installer/models/install.php line 147

No idea why we use that here.

**Comment by zero-24** [comment]
closing as we have a PR here: https://github.com/joomla/joomla-cms/pull/5809<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5786">issues.joomla.org/joomla-cms/5786</a>.</sub>
