### ISSUE TITLE
Downscale images on uploading

### ISSUE THREAD

**Issue by kairoen** [joomla/joomla-cms#5797]
Joomla 3.4 should have an option to downscale all images to a maxsize, set in general settings in Joomla. Image handling is one of the worst issues with Joomla, according to my clients. A user doesn't understand why he/she can't upload a images that is 3000-4000 pixels wide, and all uploads through Images Manager or "Images and links" tab in content, should downscale all images to a maxsize. Or at least have an option to activate this feature, and set max image size.

If this feature will be available, the Joomla sites will not use large images, that cause the site to load slower, penalty for search optimalization and so on.

**Comment by Kubik-Rubik** [comment]
We will have a complete new Media Manager in one of the coming Joomla! versions (not in 3.4 since it needs more tests): https://github.com/joomla/joomla-cms/pull/3839

Please check this PR and request this feature there if needed.

In the meantime you can use a small plugin that I wrote exactly for this purpose: http://joomla-extensions.kubik-rubik.de/downloads/eir-easy-image-resizer/joomla-3

I will close this issue, please use the referred PR for further comments.
