### ISSUE TITLE
You can enter to the articles from anywhere

### ISSUE THREAD

**Issue by luisorozoli** [joomla/joomla-cms#5848]
Reproduce the issue:

1. Enable SEF URLs
2. Create a test article 
3. Click on sample sites
4. Modify the url to add at the end the article id like:
http://localhost/jcms3x/sample-sites/74

Expected result: You cannot access to this article
Result: The article is shown

If you have an article with alias "testing-article" and the ID of this article is 74.
And someone connects you as "http://localhost/jcms3x/sample-sites/74-enlarge-your-penis" item is displayed correctly. That is bad :(

**Comment by phproberto** [comment]
There are 2 issues:

* You can access an article from anywhere
* You can access an article with any alias because only the id is checked

Related to the alias issue:
https://github.com/joomla/joomla-cms/pull/472
https://github.com/joomla/joomla-cms/pull/505

Old issue tracker:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=29428

**Comment by zero-24** [comment]
@luisorozoli This is a known issue. Maybe this will be fixed with the router changes @Hackwar ?

**Comment by Hackwar** [comment]
This is indeed known and my stuff fixes it (or is going to fix it in the longterm), but it requires that people review/test my PRs regarding this (#5444) and the PLT agrees to merge this into 3.4.

**Comment by zero-24** [comment]
Thank you for your feedback @Hackwar So i'm closing here as `Known Issue`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5848">issues.joomla.org/joomla-cms/5848</a>.</sub>
