### ISSUE TITLE
Post Installation Data - reverse order

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5896]
The post installation messages are displayed with an order of 
`ORDER BY "postinstall_message_id" ASC `

This means that the newer messages are always at the bottom

**Comment by brianteeman** [comment]
@nikosdion I wouldnt want to touch your code ;) hint hint<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5896">issues.joomla.org/joomla-cms/5896</a>.</sub>

**Comment by nikosdion** [comment]
This is *intentional*, not a bug. The older messages need to be displayed FIRST because they were added FIRST. It is a FIFO buffer. When you've read a message you can either hide it (using the Hide button) or act upon it by clicking the other button (the label is up to the developer). It makes no sense whatsoever to show messages in the reverse order. In a new Joomla! installation you think it'd make more sense to be shown a message about upgrading your passwords to bcrypt and then shown a welcome to Joomla! message (as you propose) or vice versa (as I've implemented it)?

**Comment by brianteeman** [comment]
I see what you are saying and it is logical - except in this common scenario

User has built 10 sites with 3.3 - they are familiar with the messages so
when they build their next site they dont read any more and just click hide
on all of them or just ignore it completely

Now when they install 3.4 they see the exact same messages - the new ones
are below the fold. Assume that there is nothing new and just ignore them
all or blindly hide all the messages. They dont notice that there is a new
message introduced for 3.4 so the aim of the messages is lost.

Our brains recognise familiar patterns and act based on those patterns.

On 30 January 2015 at 09:41, Nicholas K. Dionysopoulos <
notifications@github.com> wrote:

> This is *intentional*, not a bug. The older messages need to be displayed
> FIRST because they were added FIRST. It is a FIFO buffer. When you've read
> a message you can either hide it (using the Hide button) or act upon it by
> clicking the other button (the label is up to the developer). It makes no
> sense whatsoever to show messages in the reverse order. In a new Joomla!
> installation you think it'd make more sense to be shown a message about
> upgrading your passwords to bcrypt and then shown a welcome to Joomla!
> message (as you propose) or vice versa (as I've implemented it)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5896#issuecomment-72176540>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nikosdion** [comment]
So you have a way to read the user's mind and tell my code which messages this person is familiar with? Because both methods have obvious problems for a different demographic: mine for the power user who had built dozens of sites, yours for the new user. We can't cater for both and the one which really needs to read the messages is the newcomer. 

Moreover the person who has built dozen of sites will also update at least one of his J 3.2 or 3.3 sites to 3.4. Therefore he will see the new message and figure out it applies to all sites. 

So from where I am standing it makes more sense to leave it as it is now.=

**Comment by brianteeman** [comment]
Not worth a long debate

On 30 January 2015 at 09:59, Nicholas K. Dionysopoulos <
notifications@github.com> wrote:

> So you have a way to read the user's mind and tell my code which messages
> this person is familiar with? Because both methods have obvious problems
> for a different demographic: mine for the power user who had built dozens
> of sites, yours for the new user. We can't cater for both and the one which
> really needs to read the messages is the newcomer.
>
> Moreover the person who has built dozen of sites will also update at least
> one of his J 3.2 or 3.3 sites to 3.4. Therefore he will see the new message
> and figure out it applies to all sites.
>
> So from where I am standing it makes more sense to leave it as it is now.=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5896#issuecomment-72178513>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
