### ISSUE TITLE
Sidebar and messages in Debug Mode

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5928]
When messages are displayed in a manager view there is a period where the message is full screen before the sidebar is drawn on screen.

Hard to explain so I made a video
https://www.dropbox.com/s/t3a4pwlqd54qgsg/sidebarbeta1.mp4?dl=0

**Comment by brianteeman** [comment]
Just discovered that this is ONLY with debug on<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5928">issues.joomla.org/joomla-cms/5928</a>.</sub>

**Comment by dgt41** [comment]
@brianteeman Ajaxifying the debug output will solve a lot of problems, the question is who’s up for it? 😉

**Comment by brianteeman** [comment]
Updated the title to show this is only in debug mode<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5928">issues.joomla.org/joomla-cms/5928</a>.</sub>

**Comment by ggppdk** [comment]
I can offer some insight to this,

it is not in Debug Mode only, it is everywhere but it depends on Javascript workload placed on the browser.
It will happen on all pages that place "enough" "document ready" JS workload on the browser


The debug console places a small to very large Javascript workload on the browser
(e.g. if you have >1000  DB queries you can see Javascript timeouts due to Debug console JS) 

So because of the little extra (usually) workload placed by debug console, some browsers (e.g. chrome) takes a little extra time to add the CSS class to the sideBar (done by the backend template JS):
(in our case):
j-sidebar-hidden
(also some CSS classes for the content container)


I think (not sure), there is no other clean solution, other than --every view-- checking the sidebar visibility cookie and adding CSS class (an):
j-sidebar-hidden

the above is rather easy to do but it has to be done by every component on every view

Alternative, is to make default CSS in the template the sidebar initially hidden, but i don't think that this is better, of course other solutions maybe there, that i am not aware of
