### ISSUE TITLE
Email cloaking plugin malfunctions on adresses with parameters (cc, subject, ...)

### ISSUE THREAD

**Issue by mattixittam** [joomla/joomla-cms#5944]
#### Steps to reproduce the issue
- Make a new article
- Add a mailto link like this: 
`<a href="mailto:test@test.com?cc=test2@test2.com&subject=ThisIsASubject">link</a>`
- View it in the frontend with the email cloaking plugin active
- Inspect the page with firebug, chrome inspector or similar and find the decloaked link

#### Expected result
`<a href="mailto:test@test.com?cc=test2@test2.com&subject=ThisIsASubject">link</a>`

#### Actual result
`<a href="mailto:test@test.com?cc=test2">link</a>`

#### System information (as much as possible)
Joomla 3.3.6, php 5.3.27, mysql 5.5.31

#### Additional comments
Judging from some bug reports I found from 2010 and on, this bug is present in joomla 1.5, 2.5 and 3 on all configurations.

**Comment by pe7er** [comment]
I am able to reproduce this behavior on Joomla! 3.6.0-dev with the Content Plugin "Email Cloaking" ON.

I looked at the plugin code plugins/content/emailcloak/emailcloak.php
The email cloaking plugin only accepts one email address + a subject.

**Comment by brianteeman** [comment]
Hi this issue was created sometime ago but you have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5944">issues.joomla.org/joomla-cms/5944</a>.</sub>
