### ISSUE TITLE
ajax_com add check for plugin

### ISSUE THREAD

**Issue by jschmi01** [joomla/joomla-cms#5951]
For plugin there should be a similar checking done for plugin as for module. 
I used this sample code in ajax.php: 
<pre>
..
elseif ($input->get('plugin'))
{
	$plugin = $input->get('plugin');
	if (JPluginHelper::importPlugin('ajax', $plugin))
	{
		$dispatcher = JEventDispatcher::getInstance();
		$plugin = ucfirst($plugin);
		
		try
		{
			$results = $dispatcher->trigger('onAjax' . $plugin);
		}
		catch (Exception $e)
		{
			$results = $e;
		}
	}
	else
		$results = new LogicException(JText::sprintf('COM_AJAX_PLUGIN_NOT_ACCESSIBLE', $plugin), 404);
}
...
</pre>

**Comment by Bakual** [comment]
I'm not sure what you mean. `com_ajax` supports also plugins. The only restriction so far is that they have to be in the specific ajax plugin group.
This restriction will be removed with 3.4.0.
For more details see https://github.com/joomla/joomla-cms/pull/3938

If that is not what you meant, please be more descriptive and if possible create a PR (since you already seem to have some code)

**Comment by wilsonge** [comment]
He's saying that we should throw a logic exception if no plugin exists with the given name comparing the sample code to the code in 3.3.6

**Comment by wilsonge** [comment]
The event will still start with onAjax

**Comment by jschmi01** [comment]
Ok - thanks!  tested my system-plugin with using &group=system - works perfectly

**Comment by zero-24** [comment]
Thanks for the update @jschmi01 so I'm closing here. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5951">issues.joomla.org/joomla-cms/5951</a>.</sub>
