### ISSUE TITLE
Error message installing a library using "discover"

### ISSUE THREAD

**Issue by demis-palma** [joomla/joomla-cms#6015]
When installing a library using the "discover" function, it returns:
JFolder: :files: Path is not a folder. Path: /var/www/joomla/3.4/libraries/3.4
JFolder: :files: Path is not a folder. Path: /var/www/joomla/3.4/libraries/3.4
JInstaller: :Install: Can't find XML setup file.

The problem is located in JInstallerAdapterLibrary::getElement()
where $this->parent->getPath('manifest') evaluates to null.
As a consequence, $manifestPath contains the libraries directory, rather than the name of the xml library file.
The subsequent statement which is supposed to get the file name of the xml without the .xml extension returns the name of the libraries directory instead.
$element = preg_replace('/.xml/', '', basename($manifestPath));

== Replicate the problem ==
Just install a library using discover feature.

**Comment by wilsonge** [comment]
@mbabker One for you to look at

**Comment by mbabker** [comment]
The error is happening in `loadLanguage` because none of the paths are set at that point (the `prepareDiscoverInstall` doesn't get called to register paths until after the `loadLanguage` call).  So, need to do some tweaking here.

**Comment by pl71** [comment]
Something similar when installing and removing extensions of type='file'.
Installer (after J!3.4) writes in DB -> table '_extensions' -> column 'element' the value of tag <name> instead of the manifest file name as before.
(Column 'name' is also populated with tag <name> from manifest file.)

The problem comes when you try to remove this extension.
Joomla is looking for manifest file named 'value-of-the-element-field.xml', and throws error since there is no such file.
Is that a new approach in JInstaller, or simply a bug?
I wanted to make a new ticket here, but found this very similar issue.
Hope somebody answer here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6015">issues.joomla.org/joomla-cms/6015</a>.</sub>

**Comment by Flimm** [comment]
+1

**Comment by brianteeman** [comment]
@mbabker reminder as @wilsonge tagged you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6015">issues.joomla.org/joomla-cms/6015</a>.</sub>

**Comment by mbabker** [comment]
If it's decided the continued standardization of JInstallerAdapter paths
isn't breaking anymore B/C (the changes in 3.4 did so), I can work on
finishing it probably for 3.6.  Otherwise, not fixable before 4.0.

**Comment by brianteeman** [comment]
Set to Needs Review based on @mbabker question above <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6015">issues.joomla.org/joomla-cms/6015</a>.</sub>

**Comment by roland-d** [comment]
@demis-palma Thank you for creating this. At this time it can not be accepted as it would break our backwards compatibility promise but I am marking this to be re-evaluated for Version 4 which is the next release where we can make these breaking changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6015">issues.joomla.org/joomla-cms/6015</a>.</sub>

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/16343 is the first round of refactoring in the adapters for 4.0. 
 There will probably be one or two additional iterations to get everything buttoned up finally.

**Comment by brianteeman** [comment]
Closed so we just have one place see #16343
