### ISSUE TITLE
Strict Standards: Declaration of JCacheControllerView::get()

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#6119]
#### Steps to reproduce the issue
- Set site error reporting to 'maximum'.
- Site configuration cache to 'On - conservative'
- Cache plugin off

#### Expected result
No errors

#### Actual result
Error message appears:

Strict Standards: Declaration of JCacheControllerView::get() should be compatible with JCacheController::get($id, $group = NULL) in .../public_html/nieuw/libraries/loader.php on line 354 

#### System information (as much as possible)
Joomla 2.5.28 and Joomla 3.3.6 (after upgrade)
Apache/2
cgi-fcgi
MySQL 5.5.41 
PHP 5.4.37

#### Additional comments
Turning the caching off makes the message disappear.

**Comment by Bakual** [comment]
I can't make much sense out of the error message because it looks like from an old 2.5.x installation and not from 3.3.6.

However I can confirm there is an issue in our method declarations:
`JCacheControllerView::get($view, $method = 'display', $id = false, $wrkarounds = true)`
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/controller/view.php#L31
vs
`JCacheController::get($id, $group = null)`
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/controller.php#L177

**Comment by jjnxpct** [comment]
Hi! Sorry, I think I made a mistake. This error shows up only on the 2.5 site and no longer after an upgrade of that site to 3.3.6. Maybe there was some cache left in the browser that confused me ;-)
