### ISSUE TITLE
JObject is missing the bind() method

### ISSUE THREAD

**Issue by BuenGenio** [joomla/joomla-cms#6125]
It's often really useful to be able to bind an associative array, or another object, to an instance of JObject (or inheriting class). Can we add this please? Happy to do the work...

**Comment by Bakual** [comment]
JObject is actually deprecated. I'm wondering how much sense it makes to add things to it.

**Comment by BuenGenio** [comment]
Not much, if it's deprecated, does it? ;)

What's replacing it? What's the location of up-to-date documentation so I don't look like a fool next time? :)

Thanks

**Comment by Bakual** [comment]
It is officially deprecated with Joomla 3.4.0. You're not to blame for not knowing it :smile: 

There is no class to replace it. JObject is a historic class which isn't really needed anymore with current PHP versions.

The error handling should instead be done using exceptions. Other than that it only contains some setter and getter methods. Either create own set/get methods in your class or use for example our Registry class if you need more advanced property handling.

**Comment by elkuku** [comment]
Check out the JRegistry class for that matter.

**Comment by mbabker** [comment]
> What's replacing it? What's the location of up-to-date documentation so I don't look like a fool next time? :)

FWIW we typically update api.joomla.org with each release.  I'm actually working on getting the updated content together with a couple of minor template updates, so that content should roll out either over the weekend or on Monday.  And like @Bakual said, 3.4 is the first release it's deprecated in, so without following the GitHub merges, it's easy to miss things in upcoming releases.

**Comment by BuenGenio** [comment]
The reason I may sound a bit edgy, is because since J! 3.x I've sometimes struggled to find clear or up to date documentation (with examples, which helps tremendously!) on how to use certain parts of the API. 

Joomla Framework, is even a darker area, despite the fact I've tried (unsuccessfully) so far to get it bootstrapped as a foundation for my new projects - mostly because of the lack of decent documentation on it. 

Had I had more time to do it myself - I certainly would... alas, I'm not in that position. 

Perhaps I went off on an off-topicky limb, but maybe this can be relayed to the relevant parties in the hope that Joomla may be picked up quicker and more readily by the masses.... ( should this be another bug report? :))

**Comment by vdespa** [comment]
Considering that JObject is deprecated, adding new features to it make little sense (as already mentioned). Since there is no visible progress, I am closing this issue for the moment. If there is any opposition to closing this, just leave a comment. Thanks :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6125">issues.joomla.org/joomla-cms/6125</a>.</sub>
