### ISSUE TITLE
Multilanguage doesnt work at 3.4.0

### ISSUE THREAD

**Issue by sketch-media** [joomla/joomla-cms#6169]
#### Steps to reproduce the issue

Joomla! Update 3.3.6 to 3.4 on a website with 2 languages.

#### Expected result

Joomla! update to 3.4.0

#### Actual result

On active languagefilter - FE doesnt show www.domain.com/de
It redirects to www.domain.com// and generates the error TOO_MANY_REDIRECTS

Deactivating the languagefilter solved the issue, without multilanguage options logically.

#### Additional comments

Following trails failed:

Setting all extensions enabled = 0 where extension_id > 9999
Disabling all SEO URLs, Disabling .htaccess file
Changing FE-Template to protostar

**Comment by infograf768** [comment]
Multilanguage works well here.
Too may redirects is usually due to a 3rd party extension which is incompatible with multilanguage.

**Comment by infograf768** [comment]
Make sure each Content Language access is set to Public

**Comment by t0ben** [comment]
Seems to be a quite common issue.
See : http://forum.joomla.org/viewtopic.php?f=710&t=874585

Fixed by saving each language again the language selector - content.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6169">issues.joomla.org/joomla-cms/6169</a>.</sub>

**Comment by Hackwar** [comment]
This has also been already fixed in #6172  Closing this one.
