### ISSUE TITLE
insecure "Install from Web"

### ISSUE THREAD

**Issue by AndreSchwarzer** [joomla/joomla-cms#6197]
From the beginning the "Install From Web" is connected just over HTTP (http://appscdn.joomla.org/webapps/index.php ...)!

Please get this fixed ASAP.

I hoped that it'd have been fixed in version 3.4.

Thanks.

**Comment by brianteeman** [comment]
If you look you will see that this is currently disabled.

On 26 February 2015 at 10:44, André Schwarzer <notifications@github.com>
wrote:

> From the beginning the "Install From Web" is connected just over HTTP (
> http://appscdn.joomla.org/webapps/index.php ...)!
>
> Please get this fixed ASAP.
>
> I hoped that it'd have been fixed in version 3.4.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6197>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
@AndreSchwarzer it will be fixed with the next release of the webinstaller plugin. That will come if the Server side work with the new JED.

IF you Need the fix now please see here: https://github.com/joomla-extensions/install-from-web-client/pull/3.diff

But as Brian writes the Feature is disabled until other issues are fixed :smile:

**Comment by AndreSchwarzer** [comment]
thx
