### ISSUE TITLE
Menus with Falang does not translate

### ISSUE THREAD

**Issue by Agustin-Pantoja** [joomla/joomla-cms#6198]
Menus in other languages created with Falang do not translate after the update. Is there any way to revert the update?

**Comment by rdeutz** [comment]
Could you please give more information about your problem.

**Comment by efEris** [comment]
I have the same problem with jDiction, the reason is that the languagefilter plugin changes the load order.
It loads the Menü table before Joomla knows the current language.

I think reason for this is in Line 58 in languagefilter.php
```
$router = $this->app->getRouter();
```
This triggers a query on the #__menu table.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6198">issues.joomla.org/joomla-cms/6198</a>.</sub>

**Comment by Agustin-Pantoja** [comment]
I have a website in several languages. So far it was working fine, but now after the update to Joomla 3.4.0 when I change the language of the website clicking on the language selector, it does change the language of the articles, but it does not change the language of the menu and module items.

**Comment by richard67** [comment]
@Hackwar sounds as if this was something for you ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6198">issues.joomla.org/joomla-cms/6198</a>.</sub>

**Comment by infograf768** [comment]
See http://www.faboba.com/en/composants/falang/documentation.html

>2015/02/25  Due to a change in joomla 3.4.0 , falang 1.4.5 and previous are not working for this version. A new Falang version 1.4.6 was launched the 2015/02/25. This update don't work in all cases . You don't need to upgrade still you don't use Joomla 3.4.0 You can wait the next major release Falang 2.0 before next week or a new fix 1.4.7.

**Comment by efEris** [comment]
I released jdiction 1.4.0 yesterday that worksaround that Problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6198">issues.joomla.org/joomla-cms/6198</a>.</sub>

**Comment by Agustin-Pantoja** [comment]
Thank you for the answers, that was fast!

**Comment by vdespa** [comment]
@Agustin-Pantoja The issue seems to be fixed? I will close the issue. Please reply if you do not agree. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6198">issues.joomla.org/joomla-cms/6198</a>.</sub>

**Comment by Syazwannie** [comment]
Hi all, all my item menus not translated by falang but others (banner, articles, modules) is okay. Only my menus not translated. Its happened after i upgrade joomla to 3.6.5. Can somebody help me. I dunno which folder that make my menu not translated. Im using the latest Falang 2.8.3. Hope for the answers becoz joomla latest version is 3.7.1. Thanks =)

**Comment by brianteeman** [comment]
@Syazwannie commenting on an issue that was closed 2 years ago - will mean that hardly anyone will see it. If you have an issue with falang you should contact them directly - this issue tracker is for issues with the joomla code

**Comment by Syazwannie** [comment]
@brianteenman, ouhh ok... sorry
