### ISSUE TITLE
Joomla 3.4 extremely slow

### ISSUE THREAD

**Issue by ericsson77** [joomla/joomla-cms#6201]
#### Steps to reproduce the issue
1. Install Joomla 3.4
2. Get MySQLi/MySQL up and running
3. Debug some simple sites/empty templates.
#### Expected result
Somewhat reasonable queries

#### Actual result
![queries](http://oi58.tinypic.com/2ikay6o.jpg "Queries")

#### System information (as much as possible)
Fresh Joomla 3.4 setup, only site currently hosted.

#### Additional comments
I am not a developer deeply involved in the inner workings of MySQL or how Joomla process queries but when a development site, with little to no content, takes well over 1 minute per page to load, then something is wrong :)

I re-installed 3.4 twice and tried with a fresh start, still the same thing and also contacted my host provider to confirm that the servers were running as they should. Replacing the $query->where('(a.publish_up >= DATE_SUB(NOW(), INTERVAL 1 YEAR))'); code as someone suggested did nothing to speed things up. Don't know if this is a specific bug for 3.4 or not but with 3.3 everything worked fine and speedy.

**Comment by Fedik** [comment]
On first look it something on component level, on the page where you made screenshot,

but current info not enough, I think would be good to see the query debug,

**Comment by mbabker** [comment]
In terms of modules, the RocketTheme menu is somewhat slow and that component needs some performance attention (the dispatch metric would also include any plugins running in the component).  Knowing what extensions are in use here would help too.  If it's a core component, an idea about the size of the data on the site could help also.

**Comment by ggppdk** [comment]
Probably it is that component code and modules are using heavily 
--> 1 or more Joomla API function which has/have degraded performance in J3.4 ?

-- we cannot know without running XDEBUG or ZEND Studio on the website, everything else is guessing

**Comment by brianteeman** [comment]
Please retest without the roknav menu and report back. That way you can test if @mbabker is correct (fairly sure he is) but then you will be able to see for yourself<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6201">issues.joomla.org/joomla-cms/6201</a>.</sub>

**Comment by emeyer444** [comment]
I did have a problem witgh this. What I did was manually:
* turn off mootools scripts
* tuirn off jquery scripts
* turn off bootrap
* disable chosen.css manually because it still loads anyway
* create template overrides for all components and modules in use tooltips
* use echo or better rather than psuhing and popping <php ?>
* replace all language string searches with hardcoded text to stop enormous searches (at least 25% improvmeent in server response time
* remove all whitespace from generated code
* perform compression on scripts and css files with htaccess directives, disable joomla gzip compression
* rewrite windowing software in a javascript routine less than 8K B total for front end
* persuaded isp vendo to support fastcgi

Got time from 8 seconds load for uncached page to 1 second.

**Comment by emeyer444** [comment]
Oh, that being said, almost all the performance issues could be fixed with template overrides,and the core is much better.And It only took a month to do.

**Comment by dgt41** [comment]
> rewrote windowing software in a javascript routine less than 8KB total for front end that does almost everything mootools, jquery, and bootrap did.

@emeyer444 would you share that?
