### ISSUE TITLE
White screen of dead

### ISSUE THREAD

**Issue by Richardnet** [joomla/joomla-cms#6223]
#### Steps to reproduce the issue
Working on website and wait a view sec then out log out then re login and then get the white screen with blue bar.

#### Expected result

Normal admin screen.

#### Actual result

White screen and no working options

[screen shot 2015-02-27 at 14 19 10](http://issues.joomla.org/uploads/1/6ee2888e5d52407478bfec018c89ca63.jpg)

#### System information (as much as possible)

running on a pcextreme rack server with new php version out side of my control and a 1 year contract

#### Additional comments
Host running on: PHP5.5, Apache 4.2, the database is running on mysql 
Error happens on any version of Joomla inc 3.4/3.3/3.2/3.1/3.0

**Comment by Bakual** [comment]
Make sure you enable error reporting on development or maximum. That should likely get you an error message there.

**Comment by roland-d** [comment]
I doubt it is a WSOD (White Screen Of Death) because the page is fully rendered, notice the copyright footer. Could it be that the admin template has been modified and that results in this issue?

Perhaps some kind of caching may be at play here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6223">issues.joomla.org/joomla-cms/6223</a>.</sub>

**Comment by Richardnet** [comment]
Basic admin commands to check the online log on Joomla is down on [screen shot 2015-02-27 at 14 19 10](http://issues.joomla.org/uploads/1/6ee2888e5d52407478bfec018c89ca63.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6223">issues.joomla.org/joomla-cms/6223</a>.</sub>

**Comment by Richardnet** [comment]
Browser and server cache is clear and i use basic theme that came with the install.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6223">issues.joomla.org/joomla-cms/6223</a>.</sub>

**Comment by roland-d** [comment]
@Richardnet You solved the problem?

**Comment by elkuku** [comment]
Must be the new PHP version ...

**Comment by Richardnet** [comment]
I don't know it always happens to my website and yes i want a easy fix or a workaround that you can click on your admin screen

**Comment by brianteeman** [comment]
A WSOD is a php error message in disguise and as @roland-d says you would normally expect it to be completely white and not with some parts being rendered.

Having said that please enable full php error reporting to see if that reveals anything. If you dont know how to do that see https://www.phil-taylor.com/2009/01/12/a-blank-white-page-is-still-an-error-page/

**Comment by Richardnet** [comment]
i can't understand the part off Global configuration and enable Error Reporting to Maximum or the config file:

ini_set( 'display_errors', true ); 
error_reporting( E_ALL );

When i got the error log i will post it.

**Comment by roland-d** [comment]
Lowering priority because it happens for a single user. Once more reports come in we can revisit the priority.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6223">issues.joomla.org/joomla-cms/6223</a>.</sub>

**Comment by PhilETaylor** [comment]
He said the ```Error happens on any version of Joomla inc 3.4/3.3/3.2/3.1/3.0``` therefore I would conclude this is a misconfigured server and not a Joomla issue. 

I'm going to guess its a Mysql issue or output buffering issue.

**Comment by JoomliC** [comment]
Or IE in compatibility mode ?
Do you have tested with Firefox or Chrome ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6223">issues.joomla.org/joomla-cms/6223</a>.</sub>

**Comment by PhilETaylor** [comment]
@JoomliC Did you even bother reading the opening post? Or looking at the screenshot which clearly shows a shot of Chrome on Windows? 

This is NOT an IE Compat issue. 

I'll happily look into this on his server for FREE so that we can quickly get an understanding of whats happening and quickly close this - or turn our attention to any real Joomla issue found.

If you would like that please email me personally on phil@phil-taylor.com 

Note - I'll not be offering this as a paid service - I would just like to get this issue resolved or closed if its just a crappy server/user issue.

**Comment by Richardnet** [comment]
I check on 3 PC and i agree its a host problem with the PHP 5.5 bud i can't trigger the error.

i will close it.

**Comment by JoomliC** [comment]
@PhilETaylor : 
<blockquote>Did you even bother reading the opening post?</blockquote>
YES!
Of course, i could have not well read the topic, but i'm sorry: nowhere someone told us which browser version.
<blockquote>Or looking at the screenshot which clearly shows a shot of Chrome on Windows? </blockquote>
YES!
I have answered using my mobile, on issue tracker site, and when zooming with my thin fingers, i saw that IE was opened.
Sorry i didn't see it was Chrome "active" on the hidden right when i zoomed (and not a windows user specialist!)
<blockquote>This is NOT an IE Compat issue.</blockquote>
Please, don't SHOUT! i can hear (read) you! ;-)
My message was short (phone answer), and was meant to know if it was maybe the same issue as another user reported me... was very similar. But it seems not.
So best regards, and see you maybe in Prague!
Cyril

**Comment by Malequin57** [comment]
I got a white screen with the I'm dead message after I restore the files from a backup two 5 days ago. can you help?

**Comment by brianteeman** [comment]
@Malequin57 please use the forum for support https://forum.joomla.org
