### ISSUE TITLE
Joomla 3.4.0 overwrites an existing composer autoloader

### ISSUE THREAD

**Issue by HermanPeeren** [joomla/joomla-cms#6260]
#### Steps to reproduce the issue
When an installed extension uses a library that is installed via composer into /libraries/vendor, then an upgrade to Joomla 3.4.0 overwrites autoload.php and the /composer folder. The earlier installed extension doesn't work anymore.

#### Expected result
When updating Joomla an existing library that is installed with composer should still work.

**Comment by mbabker** [comment]
We aren't yet at a point where this is a feasible workflow.  We aren't shipping the composer.json or composer.lock files with production packages and when we run updates for core, these files get regenerated for the core dependencies.  I'm not sure what we can do short of pulling the full Composer API in as a dependency right now.

My workaround in the first extension I integrated Composer into is to just ship the extension with its own /vendor directory and Composer autoloader and load that within the extension (since the extension doesn't have any external uses like plugins where the objects may need to be present I can safely not merge this data to the base autoloader).

**Comment by HermanPeeren** [comment]
Yes, I'll change my Composer stuff, although it was working for some years now. Should have tested this 3.4 update first on a non-production server. Bummer. 

I assume Joomla 3.4 uses this and it is not just for future use, so it would probably break something in Joomla if I would overwrite those files with my old ones. I'll try, but if you can tgell it, it saves me some trouble to try. Thanks for the reaction anyway.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6260">issues.joomla.org/joomla-cms/6260</a>.</sub>

**Comment by HermanPeeren** [comment]
I'll make my own folder in /libraries and put my /vendor and other composer stuff in that. But I have the feeling it is the opposite of what the intention of composer was.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6260">issues.joomla.org/joomla-cms/6260</a>.</sub>

**Comment by HermanPeeren** [comment]
Issue can be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6260">issues.joomla.org/joomla-cms/6260</a>.</sub>

**Comment by mbabker** [comment]
Eventually the intent is to make that integratable with extensions.  Just not quite there yet.
