### ISSUE TITLE
com_tags Joomla 3.4 - do not work any settings in menu item

### ISSUE THREAD

**Issue by goshalviv** [joomla/joomla-cms#6329]
Create menu item.
Set type of menu item com_tags (view: "tag")
Change any settings, for exapmple, show image for tag and for element.
Any settings do not work. Work only global settings on component options.

**Comment by Harmageddon** [comment]
Thank you for your report! This bug is already fixed in the current staging branch on GitHub and will be fixed in the next release, which is 3.4.1. See Issue #6354.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6329">issues.joomla.org/joomla-cms/6329</a>.</sub>
