### ISSUE TITLE
Changing language setting in installer deletes content in form fields

### ISSUE THREAD

**Issue by Bodge-IT** [joomla/joomla-cms#6388]
#### Steps to reproduce the issue
Load installer
In configuration page 1, enter details into form
The change language selection

#### Expected result
Content entered into form fields remains

#### Actual result
Content entered into form fields is deleted

#### System information (as much as possible)
Standard Joomla 3.4 installer package
Run on WAMP server

#### Additional comments
This was noticed because of issue #6387.  I expected it to be English(UK) and only noticed it was English(Australia) just before I pressed 'Next'.  When I tried to change the language, all my entered details were lost.  Annoyance factor!

**Comment by brianteeman** [comment]
I am going to confirm this as an issue but I am not sure if it can ever be fixed with the current installer<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6388">issues.joomla.org/joomla-cms/6388</a>.</sub>

**Comment by Bodge-IT** [comment]
No problem, was merely a minor annoyance.
Most will change language first and then fill in form.

Cheers
Gary

**Comment by brianteeman** [comment]
Most will never change language as the browser will correctly select the
required language ;)

On 11 March 2015 at 10:26, Gary Barclay <notifications@github.com> wrote:

> No problem, was merely a minor annoyance.
> Most will change language first and then fill in form.
>
> Cheers
> Gary
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6388#issuecomment-78238225>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bodge-IT** [comment]
Hah! Don’t count on that…I’m IT born and bred for 30 years.
My FF has had that setting since install!

Funnily enough this shows up in GAnalytics too.

Even for sites which are mostly accessed by UK users, the browser language often shows more en-us or other English variants.

Anyway, off to boil my head
Cheers
Gary

**Comment by mbabker** [comment]
FWIW the rest of the application stores POST'ed form data into the session in case an error condition comes up and we redirect back to the form so data isn't lost.  We don't have that luxury in the installer and since the language change is one of the few installer pieces that appears to force a page refresh (instead of an AJAX action like most everything else), it's indeed one of those edge cases for a day when you're snowed into your home.
