### ISSUE TITLE
Transliterate does not use the correct language

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#6421]
1. Create a page with english and russian content language
2. set the (backend) language to english
3. create a russian text with a russian title (e.g. "Главная") (language == russian)
4. Save
5. Expected result for alias: "glavnaya", Current result: the current date

Problem: $this->alias = JApplication::stringURLSafe($this->alias); does always use the current language and not the language of the article/menu/item itself

**Comment by infograf768** [comment]
One solution is to use the Global configuration Unicode Alias parameter in order to normalize all aliases.
Otherwise, indeed, it is the xx-XX.localise.php transliterate method of the current language which is used.
Related issues:
A user could be in this situation: a new content language is created before the related language pack is created/installed. In this case, there is no xx-XX.localise.php with its specific transliteration.
Also, before saving an item (article or menu item), the language the item is assigned to is not known. Therefore the alias would be automatically created without knowing the custom transliteration to apply from that language.

**Comment by bembelimen** [comment]
Hello,
you have a valid point here, but I think, if we use the default/current language als fallback, we should be save here:
1. check if content language exists
2. otherwise use current language

or we could enforce, that the language have to exist, when we create a content language

**Comment by infograf768** [comment]
>or we could enforce, that the language have to exist, when we create a content language

Nothing is written in stone, but that was the way Andrew Eddie saw it in the 1.6 pre-release times, i.e. to be able to create a Content Language before getting a language pack.

**Comment by brianteeman** [comment]
Based on the comments above by @infograf768 I am closing this as the expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6421">issues.joomla.org/joomla-cms/6421</a>.</sub>
