### ISSUE TITLE
Add Delete function to update sites manager

### ISSUE THREAD

**Issue by MyDadisDead** [joomla/joomla-cms#6423]
#### Steps to reproduce the issue
Currently the update manager identifies sites which don't work by deactivating them.
It would be useful if the possibility existed to delete these sites which don't function correctly, by adding a delete button which removes that particular Line in the table.

#### Expected result
Delete non-functioning update sites from database list

**Comment by brianteeman** [comment]
Why would you want to do that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6423">issues.joomla.org/joomla-cms/6423</a>.</sub>

**Comment by MyDadisDead** [comment]
When an error is built into the update link - which I've come across a few times - or when there are duplicates of the site - which I've also found - it's just irritating to keep getting a message about deactivated sites. Usually I go  into the database and remove those lines. Having an option to do this from the manager interface would be neat.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6423">issues.joomla.org/joomla-cms/6423</a>.</sub>

**Comment by Bakual** [comment]
@nikosdion Was there a reason you didn't add that in your original PR? Beside to reduce support requests from stupid users who deleted their updatesites? :smile:

**Comment by brianteeman** [comment]
If a stupid user deletes a site can they add it back?

You cant fix stupid but you ca try to reduce the pain for the rest of us
when we are asked to fix it

**Comment by MyDadisDead** [comment]
Isn't it the case that each install/update of a component also updates the update site details?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6423">issues.joomla.org/joomla-cms/6423</a>.</sub>

**Comment by nikosdion** [comment]
I am adamant that deleting update sites *MUST NOT* be allowed. It is very easy for a user to remove an update site and they'd have no idea how bas is what they did. Result: user thinks the bad developer broke their site.

It's also outright impossible to add it back without reinstalling the component. Problem: they will try to uninstall and reinstall the component, obliterating their content / settings, blaming the bad developer for breaking their site.

If they remove a core update site (Joomla! update, languages, ...) there is no way to add it back without directly editing the database. Problem: user thinks Joomla! is a bad CMS which can only be used by developers because of that "developer stuff" we ask them to do.

It's our job as developers to make screwing up difficult. By not including a delete option I did exactly that. As the feature is right now the worst they can do is disable an update site which they can re-enable in the same easy way. The user may be a tad miffed but he won't be disappointed with Joomla! or the extension developer. It's pretty much the same reason you can't take your keys off the ignition and lock the driving wheel while the car is moving.

**Comment by MyDadisDead** [comment]
Glad to see you joining in, Nik. I understand your concerns, however the problem I refer to, still exists. Perhaps you can up with a workable solution?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6423">issues.joomla.org/joomla-cms/6423</a>.</sub>

**Comment by sovainfo** [comment]
The current attitude seems to be to treat Super User as Super Looser. Offended Super Users will use phpMyAdmin to remove them!

**Comment by nikosdion** [comment]
There is no problem, actually. If you really, REALLY want to delete an update site and risk screwing up your site feel free to edit your database.

And because me being subtle didn't work, let me retry without a hint of subtlety.

I will not add or even agree to the addition of an *ill-thought* feature which will result in users utterly screwing up their sites, making them think Joomla! is a badly written CMS and increasing the support load to third party developers. You will see that every single one of the problems arising from the inclusion of a Delete button is far greater than the benefits in the extremely rare case of a broken update site (which is disabled either automatically or manually, therefore no longer causing any problem to your site). After all, for the last 5 years you didn't even have the option to manage update sites and you were none the wiser about the broken update sites!

In the end of the day, use phpMyAdmin. But as you said, these broken update sites will come back as soon as you upgrade the extension shipping with them. The best course of action is to notify its developer to either fix the update site itself or add three lines of code in their extension's post-installation code to remove the broken update sites on the next update. Pro tip: the FOF version included with Joomla! 3.4 does have the necessary code to create afresh the update sites of an extension, removing old and broken ones and add the new and correct ones. So why exactly you think we need to allow users to screw up their site instead of having developers do the work shall remain a mystery...

**Comment by MyDadisDead** [comment]
OK - thanks for making that clear, Nik.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6423">issues.joomla.org/joomla-cms/6423</a>.</sub>

**Comment by Bakual** [comment]
Based on the feedback I'm going to close this issue.
Thanks all!

**Comment by sovainfo** [comment]
Agree with the fact there is no need for this functionality. Consider an update site being disabled good enough. Don't consider removing update servers a serious problem either, compaired to the ease Loosers apply the update to a llive site without backup from the apply button!

With Extension manager->Manage->Uninstall you are doing exact the same thing, even worse, as you yourself mentioned. Is that going to be removed as well?

Wonder why you think fixing the developer mistakes is screwing up the site. When I decide it is needed to remove an update server, some developer screwed up, not me! 
Removing it would make sure I don't screw up MY SITE because an extension developer screwed up. That is why I am the Super User of the site. Once made sure everything is ok, an update might be in order and the update server might stay enabled. 

Today, there are still extensions not providing an update server. Which means they need to be checked manually. Don't see a problem adding the extension to that list. This information is very hard to get out of the system. Nothing against using the update servers of extensions, but claiming that removing them screws up the site is beyond me. Wished Joomla provided decent support for migrating, current implementation fails miserably.

**Comment by nikosdion** [comment]
I can add the 5 lines of code. But provide me with a billing address to send you the expenses of additional support required for such a moronic feature. Then the question of why removing update sites is wrong will not be beyond you, it will be scorching a massive hole in your pocket. OK? We have a deal?

**Comment by sovainfo** [comment]
Suggest you read more carefully: "Agree with the fact there is no need for this functionality. Consider an update site being disabled good enough."

**Comment by nikosdion** [comment]
I read that. Then I read your last paragraph which is in stark contrast with the first. Make up your mind? :)

**Comment by sovainfo** [comment]
The last paragraph shoots a hole in your argument for not delivering this. Your claim that providing it would screw up the site.

But, it seems you are open to discussion, so I have no further interest to discuss this.

**Comment by nikosdion** [comment]
There is a hole there, but not in my argument. Unless you consider unnecessary support requests and leaving Joomla! itself without SECURITY updates a no biggie...

Not to mention that the reason many developers are still not using the J extensions update feature is because it used to perform erratically. The update site being disabled was bad already: we had to check if it's enabled in every page load to ensure updates, screwing performance. Alternatively we had to put up with people telling us how incompetent we are for not providing updates - sorry, not our fault that J screwed up. If we now allow users to disable update sites I can see no reason why any dev should continue using J extensions update instead of rolling their own solution and a system plugin to fetch updates and notify the user, like we did back in J 1.5. The latter requires far less resources to implement, support and maintain as experience shows (I have the numbers to prove it, too).
