### ISSUE TITLE
Senseless copyright updates gain nothing and waste everyone's time

### ISSUE THREAD

**Issue by Paladin** [joomla/joomla-cms#6590]
After updating 32 branches in 14 separate repos I have to ask:

Can we stop with the senseless copyright updates already?

1) Changing the copyright date on a file that has no other changes is purposeless. It hasn't been changed, there's no need to change the copyright.

2) Even if doing so would magically extend the copyright date of the file (something I'm not at all convinced of -- republishing a book's text unchanged doesn't advance the copyright date, after all ---  but let's assume it's true for the moment) the length of copyright protection terms worldwide is such that the original copyright of Joomla 1.0.0 will still be effectively protecting the software long after the code's useful life has ended (not to mention most of our lives as well).

3) So while it effectively gains us nothing at all in legal protection, it costs us time, of which the time to do it, commit it and push it is the least significant. There is the time it takes every developer with multiple branches to go back and rebase every feature, bugfix, and development branch of the code they currently have active to ensure they can avoid merge conflicts later on when ready to push the changes back up. And some of us maintain production website code in repos as well, to enable rapid deployments (as well as rollbacks of changes) to multiple servers, where it makes us spend more time gathering in and pushing code files and updating branches there.

4) Plus it wastes bandwidth for people to download a crap-ton of files in a website update simply because someone changed the copyright date.

By all means, change the copyright date when other changes are made to the file; that's when it *should* happen and when it's legally effective. But it's a waste of *everyone's* time, energy, and bandwidth to make *only* copyright date changes to a file.

**Comment by brianteeman** [comment]
It takes about as much time as I wasted reading this and writing the reply

On 26 March 2015 at 14:38, Arlen Walker <notifications@github.com> wrote:

> After updating 32 branches in 14 separate repos I have to ask:
>
> Can we stop with the senseless copyright updates already?
>
> 1) Changing the copyright date on a file that has no other changes is
> purposeless. It hasn't been changed, there's no need to change the
> copyright.
>
> 2) Even if doing so would magically extend the copyright date of the file
> (something I'm not at all convinced of -- republishing a book's text
> unchanged doesn't advance the copyright date, after all --- but let's
> assume it's true for the moment) the length of copyright protection terms
> worldwide is such that the original copyright of Joomla 1.0.0 will still be
> effectively protecting the software long after the code's useful life has
> ended (not to mention most of our lives as well).
>
> 3) So while it effectively gains us nothing at all in legal protection, it
> costs us time, of which the time to do it, commit it and push it is the
> least significant. There is the time it takes every developer with multiple
> branches to go back and rebase every feature, bugfix, and development
> branch of the code they currently have active to ensure they can avoid
> merge conflicts later on when ready to push the changes back up. And some
> of us maintain production website code in repos as well, to enable rapid
> deployments (as well as rollbacks of changes) to multiple servers, where it
> makes us spend more time gathering in and pushing code files and updating
> branches there.
>
> 4) Plus it wastes bandwidth for people to download a crap-ton of files in
> a website update simply because someone changed the copyright date.
>
> By all means, change the copyright date when other changes are made to the
> file; that's when it *should* happen and when it's legally effective. But
> it's a waste of *everyone's* time, energy, and bandwidth to make *only*
> copyright date changes to a file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6590>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
I kinda agree here.  We have a blanket copyright statement on most every file, `Copyright (C) 2005 - 2015 Open Source Matters, Inc.`.  This gives the impression all code has a copyright claim going back to 2005 (at least to me), and I think we'd be hard pressed to find existing classes or files in our current repo that may be able to make this claim.  I don't mind updating copyright dates, but I think they should be accurate.

**Comment by Paladin** [comment]
Well, Brian, the quick question to help me understand why it took so little time for you is: How many repos and branches did you have to update and rebase to keep your work current?

**Comment by Bakual** [comment]
There will be no merge conflicts at all from copyright changes since you very unlikely will do changes in the same line. (if you did, you did something wrong).
Thus you don't need to rebase/merge your branches only because of the copyright changes. It would still merge fine.
I don't see a real issue here.

The bandwidth isn't really a concern as well nowadays. It's not like we're talking gigabits here.

I tend to agree with Michael that the copyright should be accurate, but then it could become a real issue to find when the copyright actually started for each file. I don't think it's worth that effort.
I think it's worth more to have a standard header across all files, which can also be updated/changed very easy.

What I wonder is if the copyright message could be changed to something like "since 2005". Then it wouldn't need to be updated. But I have no clue about legal implications here.

**Comment by orware** [comment]
This discussion had some useful info which seems to indicate it's not really required:
https://github.com/ginatrapani/todo.txt-ios/issues/166

This sounds to me though like the exact thing OSM should be able to assist with since they have the connection with the Software Freedom Law Center (if I'm remembering correctly) and would be able to give us a clear cut Yes/No answer about whether it's required or not for us to enforce any sort of Joomla copyright on the code written for the project:
https://www.softwarefreedom.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6590">issues.joomla.org/joomla-cms/6590</a>.</sub>

**Comment by Bakual** [comment]
Feel free to approach someone from OSM and ask them to check that.
Till we have an answer, I'm going to close this issue.
