### ISSUE TITLE
On module or plugin edit mode admin-logo is unaccessible

### ISSUE THREAD

**Issue by Sarge2013** [joomla/joomla-cms#6597]
Hello, I use latest 3.4.1
I've noted on admin backend that in edit mode of a plugin or module - I can't click on admin-logo what is in top left corner of the admin menu.
Previously in 3.3.6 this click was possible and it was convenient when necessary open a new browser window right from module/plugin edit mode.
Thanks for your attention !

**Comment by zero-24** [comment]
@Sarge2013 This is expected behavior to not leave the configuration of en plugin or module without safing. The same behavior you have if you open a article.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6597">issues.joomla.org/joomla-cms/6597</a>.</sub>
