### ISSUE TITLE
Joomla help system with components

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#6627]
#### Steps to reproduce the issue
There seems to be no way to add a local help for the configuration of a component. I do not see any external component who provides something like that. Did try JCE and Kunena. All with the same result. Choosing a component from the component menu in backend and clicking on Options and there the help button shows a screen like in the attached picture. Is that only possible with the standard Joomla components?

#### Expected result
Showing a help screen for component options from a local help file

#### Actual result

a default window with the message, that there is no text in this page.

#### System information (as much as possible)
Joomla 3.4.1

#### Additional comments
![screen shot 2015-04-01 at 05 30 32](http://issues.joomla.org/uploads/1/837e9cac9d85f5f8bfdf4f797a80bce6.png)

**Comment by brianteeman** [comment]
No it is only for the core of Joomla. For an explanation on how it works see
https://docs.joomla.org/Help_system/How_the_help_system_works

On 1 April 2015 at 11:30, franzpeter <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> There seems to be no way to add a local help for the configuration of a
> component. I do not see any external component who provides something like
> that. Did try JCE and Kunena. All with the same result. Choosing a
> component from the component menu in backend and clicking on Options and
> there the help button shows a screen like in the attached picture. Is that
> only possible with the standard Joomla components?
> Expected result
>
> Showing a help screen for component options from a local help file
> Actual result
>
> a default window with the message, that there is no text in this page.
> System information (as much as possible)
>
> Joomla 3.4.1
> Additional comments
>
> [image: screen shot 2015-04-01 at 05 30 32]
> <https://camo.githubusercontent.com/cbe2a0c38043491a77aa76a060baf81b96f2bf04/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f38333765396361633964383566356638626664663466373937613830626365362e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6627>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
You should be able to point to a custom location by passing the right params.  Take a look at [JToolbarHelper::help()](https://github.com/joomla/joomla-cms/blob/3.4.1/administrator/includes/toolbar.php#L117-L135)

**Comment by franzpeter** [comment]
Thanks for answering. Michael, I will try it with your provided link. I do not know that such an option exists.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6627">issues.joomla.org/joomla-cms/6627</a>.</sub>

**Comment by chrisdavenport** [comment]
This is probably the page you most need to read: https://docs.joomla.org/Help_system/Adding_a_help_button_to_the_toolbar

The help system was actually designed to be very flexible.  The intention was that it should support third-party extensions using a wide variety of potential methods of hosting help files, both local and remote.  The way the Joomla core extensions do it is by no means the only way possible.

**Comment by brianteeman** [comment]
Thanks chris I missed that page.


Can this be closed now as asked and answered?

**Comment by chrisdavenport** [comment]
Yes, I think so.

**Comment by kainhofer** [comment]
Chris, I think you misunderstood the original request: The issue is not how third-party components can implement a help button in general (which I agree is nicely described in the links you posted). 

The issue is that in J3 **third-party components** have their **configuration page** shown in the **com_config component**, and this component does not provide any way to offer help pages from servers different from the default help server. So if you go to the configuration page of e.g. Kunena or VirtueMart, then the help button in the com_config component will try to use the JHELP_COMPONENTS_com_kunena_OPTIONS or JHELP_COMPONENTS_com_virtuemart_OPTIONS help keys on the Joomla server.

The corresponding code is in administrator/components/com_config/view/component/html.php, function ConfigViewComponentHtml::addToolbar:

```php
    protected function addToolbar()
    {
        [...]
        JToolbarHelper::divider();
        JToolbarHelper::help('JHELP_COMPONENTS_' . $this->currentComponent . '_OPTIONS');
    }
```

This will always try to load the help page from the **default Joomla help server**, even for third-party applications (which do not have any help pages on the joomla servers, of course).  Those third-party components thus do not have any way to provide help pages for the configuration page on their own servers.

For third-party components, the com_config component needs to be made more flexible to allow help pages on other servers, too... That is the real issue here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6627">issues.joomla.org/joomla-cms/6627</a>.</sub>

**Comment by Bakual** [comment]
Reopening based on the explanation of @kainhofer

**Comment by chrisdavenport** [comment]
Ahh, okay.  In that case it's definitely a bug (in com_config).

At a quick glance I'd say that instead of inserting the component name into the key reference it should be passed as the 4th argument to JToolbarHelper::help().  Maybe something like

    JToolbarHelper::help('JHELP_COMPONENTS_OPTIONS', true, null, $this->currentComponent);

Extension developers should then store the help URL (actually a URL template) in the "helpURL" parameter in component parameters.  The help URL can contain substitution codes and if the above code were to be used, {keyref} would be replaced by "JHELP_COMPONENTS_OPTIONS".

**Comment by zero-24** [comment]
@chrisdavenport @kainhofer @franzpeter this: https://github.com/joomla/joomla-cms/pull/6639 try to fix the issue based on @chrisdavenport 's idea. I hope you can test it. Thanks :+1:

**Comment by franzpeter** [comment]
Did test with the provided code from chrisdavenport and it works as expected. Exchanging in administrator/components/com_config/view/component/html.php the old code at line 90 with that: 		JToolbarHelper::help('JHELP_COMPONENTS_' . strtoupper($this->currentComponent) . '_OPTIONS', true, null, $this->currentComponent);
did solve the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6627">issues.joomla.org/joomla-cms/6627</a>.</sub>

**Comment by franzpeter** [comment]
I think we can close that issue as solved with the solution provided here: issue 6639<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6627">issues.joomla.org/joomla-cms/6627</a>.</sub>
