### ISSUE TITLE
Media Manager -> Provide the links on path

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#6628]
#### Steps to reproduce the issue
1. Go to the media manager.
2. Navigate the folders.

#### Expected result
Should provide the links, so that we easily navigate back on home/subfolders

#### Actual result
Only path present
![screen shot 2015-04-01 at 06 11 21](http://issues.joomla.org/uploads/1/f8ab2509126e28f1eab261db5be375bc.png)

**Comment by brianteeman** [comment]
I am closing this at this time as there has been no interest in making this change. Probably because the functionality requested is already available in the navigation tree.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6628">issues.joomla.org/joomla-cms/6628</a>.</sub>
