### ISSUE TITLE
Batch copy language does not work

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#6642]
#### Steps to reproduce the issue
Select one or more articles
Select Batch from the toolbar
Select a different language (eg English instead of ALL)
Select Copy
Select Process

#### Expected result
A Copy of the article is created in the new language

#### Actual result
The article is moved to the new language

#### System information (as much as possible)
Joomla 3.4.1

**Comment by infograf768** [comment]
I can't replicate here;

here are the correct settings (Read the tip on top):

![screen shot 2015-04-03 at 05 05 07](http://issues.joomla.org/uploads/1/2f76b24ecf96758a9db5d1ce484c6905.png)


Here is the original:

![screen shot 2015-04-03 at 05 06 29](http://issues.joomla.org/uploads/1/506e5eb4d205cfbfe5e295e37b1d09d2.png)

Here is the result:

![screen shot 2015-04-03 at 05 06 56](http://issues.joomla.org/uploads/1/081530e0a2f026e6e46e890d43088f4b.png)



The original stays the same.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6642">issues.joomla.org/joomla-cms/6642</a>.</sub>

**Comment by infograf768** [comment]
we may need to change slightly the tip as it can be confusing: if a category is NOT chosen, the action (whether one choses Copy or Move) will be applied to the existing item.

**Comment by brianteeman** [comment]
You didnt follow my steps to reproduce!!

Why do we even need to chose a category - that requirement makes no sense
to me at all

The information says
Otherwise all actions are applied to the selected articles

Thats not correct as the selected article is not copied but moved

On 3 April 2015 at 11:17, infograf768 <notifications@github.com> wrote:

> we may need to change slightly the tip as it can be confusing: if a
> category is NOT chosen, the action (whether one choses Copy or Move) will
> be applied to the existing item.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6642#issuecomment-89246654>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
This is why I wrote:
>we may need to change slightly the tip as it can be confusing: if a category is NOT chosen, the actions (whether one choses Copy or Move) will be applied to the existing item

 i.e. there will be no Copy or Move. 

the actions are : Change language, Set access level and Add tags

**Comment by infograf768** [comment]
Let me precise again: an item can't be "moved" to a new language...

An item language can be "changed", which is quite different.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6642">issues.joomla.org/joomla-cms/6642</a>.</sub>

**Comment by brianteeman** [comment]
So not only is the tip completely wrong but this is a real problem

The correct behaviour for Joomla therefore if you are following the steps I mentioned in the first post is NOT to move the items but to inform the user that it is not possible to copy the item. It is never correct to do something that the user has not selected. If it is not possible that is OK but it is not ok to just go ahead and do something completely different to what the user requested.

It is perfectly normal in Joomla for the user to be told that the action they have requested cannot be performed. I cannot think of anywhere in Joomla where Joomla decides that the user is stupid and just goes ahead and does something that the user did not request. (Especially when it is not something that can be easily undone - although that is irrelevant)

## We must never do something to a users web site that they did not request - that should be a fundamental contract with the user.

**Comment by infograf768** [comment]
We can copy the items from any category to a unique category and that has worked since 1.6.

For example: let's choose 3 items from a specific category: we can copy them to the same category AND change the language. 

![screen shot 2015-04-03 at 10 27 44](http://issues.joomla.org/uploads/1/d727fc6e94c4bf1dea63d9638e83fc27.png)



As far as I remember, when Michael @mbabker implemented these batch functions, he had no solution to hide Copy and Move when a category was not chosen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6642">issues.joomla.org/joomla-cms/6642</a>.</sub>

**Comment by mbabker** [comment]
The batch UI is horrible and the code probably not much better.  But as is, the behavior is accurate.  The copy/move radio options only work when you've chosen a category.  Should those radio options work beyond that?  Yes, IMO.  Until we reach that point, we should do something to make sure it is crystal clear that the category selector and radio options work hand-in-hand and those options are not used by any other batch selectors.

**Comment by mbabker** [comment]
At least with 2.5 it was a bit more clear the radios only applied to the category selector.  But, this has basically been an issue since the day it was implemented.

![screen shot 2015-04-03 at 11 49 36 am](https://cloud.githubusercontent.com/assets/368545/6984499/a012ba30-d9f7-11e4-837f-ab4f6e4fe10e.png)

**Comment by Bakual** [comment]
It has indeed always be the case that copy/move is tied to the category. The tip also describes the supposed behavior. And it even makes sense to a degree, since when you want to copy an item, you need to tell Joomla if it should be copied within the existing category or to another one.

I think the issue is because the modals got redesigned about a year ago. PR was https://github.com/joomla/joomla-cms/pull/2844.
If memory serves me right, we had the 2.5 style before where the options were below eachother. Now we have a two column layout which may make it less clear that copy/move is tied to the category. I may be wrong of course.

Maye it can be improved by just adding a small border around the category/copy/move select/buttons? Or the tip could be reworded better?

**Comment by bertmert** [comment]
> Maye it can be improved by just adding a small border around the category/copy/move select/buttons?

Why not disable/hide radio button Copy by JQuery if no category selected?
Something like this
https://github.com/bertmert/joomla-cms/commit/a0cffec8287015f2e2b09c1bd26c2d966989e818

**Comment by Bakual** [comment]
I'm not a big fan of hiding UI elements because you don't see what would be possible. Eg you have no clue that you can copy items until you select a category. But I'm not a UI expert by far.

**Comment by brianteeman** [comment]
The correct thing to do is NOT to move them when you asked to copy and to
give an error message explaining why they have not been copied.

On 7 April 2015 at 07:45, Thomas Hunziker <notifications@github.com> wrote:

> I'm not a big fan of hiding UI elements because you don't see what would
> be possible. Eg you have no clue that you can copy items until you select a
> category. But I'm not a UI expert by far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6642#issuecomment-90399431>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
The thing is that they aren't moved either when you don't select a category. They are only changed to a different language/author/viewlevel/whatever. Copy/Move is related to the category.
Since the radio is by default active (I think with "move"), you couldn't detect if the user forgot to select a category or if he just wanted to change the existing item.
Also, you may want to change properties from items from different categories without actually moving or copy them, eg leave the category as it is.

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/issues/6642#issuecomment-90399431

Could be greyed and tip updated?

**Comment by mbabker** [comment]
> The correct thing to do is NOT to move them when you asked to copy and to
> give an error message explaining why they have not been copied.

The only thing with that suggestion at the moment is then we're displaying an error message on every operation that doesn't have a category selected for copy/move.  In truth, that message wouldn't be anymore helpful than the poorly worded "help text" in the batch modal.

Like I hinted to above, copy/move ONLY applies to category selections; that's the way it was implemented for com_categories during 1.6 development and expanded for com_content in 1.7 and other managers in 2.5.  Looking back that was probably a terrible decision, but that's the one that was made and that's how the code has behaved for years.

In all honesty, the batch workflow needs to be reworked ground up because there are a lot of not-so-optimal things in the code and UI.  Copying an article with a new language should be possible, but our code flow has absolutely no way right now to figure out how to accomplish that.

**Comment by Bakual** [comment]
> Copying an article with a new language should be possible, but our code flow has absolutely no way right now to figure out how to accomplish that.

Copying an article to a new language works fine, as long as you select a category where you want to copy it to. :smile: 
Otherwise it will just change the language from the selected article. As explained (badly) in the tip.
So the real fix is to improve the tip.

The behavior itself isn't bad actually. It's very flexible. Just the UI around it sucks.

**Comment by mbabker** [comment]
The text on the tip will only make it more clear to a user what can be done with what combination of options.  It does not fix broken code logic.  Why can't I select a group of articles, click batch, set a language, and copy them without having to change the category selection?  Our code is already smart enough to handle the duplicated aliases this would cause within the same category.  If these articles are all spread across different categories, right now I would either have to process them one-by-one or copy them all to a single category, whereas if the copy option worked without a coupling to the category selector, all the articles could be copied within their respective categories just fine.

**Comment by Bakual** [comment]
True. But I don't think it's not something we can fix due to the way batch works currently.
I agree with you that the batch stuff would need a massive redo. I don't think it's worth the effort in 3.x (due to keeping B/C and stuff), but certainly something to improve for 4.0.

In 3.x the best we can do is likely improve the UI and tip.

**Comment by bertmert** [comment]
https://github.com/joomla/joomla-cms/issues/6642#issuecomment-90399431
https://github.com/joomla/joomla-cms/issues/6642#issuecomment-90502814

Not to be misunderstood. My JQuery should be just a temporary less-then-ideal solution for the status quo, not for the whole issue; to make clear at first view that copy is not possible without a cat selection. I've removed hide/show now and JS just disables the Copy radio. There should be some "more spectacular action" when changing category. Could also be changing label text/color or similiar. A Move could become an Apply or Change.

I'm not new to Joomla but whenever I start a batch (not so often) I first make a test because I'm not sure what will happen with my items. Even if there's a hint above the form. At the moment I see that German translations for Batch tip are completely confusing, BTW.

**Comment by brianteeman** [comment]
Please see #7371<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6642">issues.joomla.org/joomla-cms/6642</a>.</sub>
