### ISSUE TITLE
Module Manager: Modules:: There should a button to reset all the filter in one click

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#6656]
- Go to Plugin Manager: Plugins / Module Manager: Modules
- Apply All the available filters
- There should be a **RESET FILTERS** button to reset all the filters in just one click

_Problem: Now user needs to reset all the filter one by one, which very time consuming_![screen shot 2015-04-04 at 04 59 01](http://issues.joomla.org/uploads/1/9bfcdd0252abe8b40b01ac554ddf3500.png)

**Expected: Add RESET FILTERS button to reset all the filters in just one click**

**Comment by bertmert** [comment]
I've started a PR. My target is to integrate the searchtool bar like in com_content articles. There's a Clear button.

**Comment by bertmert** [comment]
@aasimali First steps are done. If you want to test you'll find new and changed files here:
https://github.com/joomla/joomla-cms/compare/staging...bertmert:patch-8

- To be discussed: Maybe it would be better to move the Client filter back to sidebar. Otherwise search tools never close after Clear (compare with Articles Manager!). I have no preference.
- New sorting fields like in Articles Manager will follow.

Status quo:
![modules-searchtools](https://cloud.githubusercontent.com/assets/11038612/6996076/842a5830-db70-11e4-8984-92c136870030.jpg)

To do:
![modules-searchtools-articles-sort](https://cloud.githubusercontent.com/assets/11038612/6996079/8edbc93a-db70-11e4-9192-2df3ca4bccdc.jpg)

**Comment by Bakual** [comment]
The "Site/Administrator" select is a bit a special case because you have one of it active all the time. YOu don't have a "select location" entry. I think you could as well do it as a submenu (it used to be, or not?).
It certainly doesn't play nice together with SearchTools. Or is there a way to ignore that for the "popup" of the Search Tools? @phproberto

**Comment by phproberto** [comment]
That need to be a static filter (changeable by users but always with a value). You can check how it's done in the menu manager which uses an override of the searchtools layout to display the static filter before the search box.

**Comment by bertmert** [comment]
@aasimali 
Here is my Pull Request FOR MODULES only. Please help testing!
https://github.com/joomla/joomla-cms/pull/6682

I don't have time for Plugins Manager. Maybe you should better close this issue and open a new one, just for Plugin Manager(?)

@Bakual @phproberto Thank you for your hints!

@phproberto Maybe this is a chance to test your PR https://github.com/joomla/joomla-cms/pull/6677 ?

**Comment by aasimali** [comment]
Hi @bertmert 

-I have applied a patch (#6682) and done the basic testing on my existing testing site.
-Tested On Joomla 3.4.1

-I found something, That you must check. Please refer screenshots.

![ui issue](https://cloud.githubusercontent.com/assets/10045599/7020368/fe8d6ef2-dd35-11e4-88f6-5ea61a7cbe01.png)
![suggestion](https://cloud.githubusercontent.com/assets/10045599/7020372/045627c0-dd36-11e4-857d-2f8d9e36dc10.png)

**Comment by bertmert** [comment]
@aasimali 
Please open new issues *one for each* of your further requests. 

I used the "instruments" that come from Joomla Core. Styling is the same like in other list views.

- E.g. Clear button for Search only. It's easy to add one in a /layouts/ override inside the /html/ folder of the template or in a custom component for all list views in backend.
But it should be discussed separately if this is wanted globally in CoreCode.

- E.g. "Looks weird for long terms". would be a global LESS/CSS change that was not part of my PR. It's normal bahaviour to have fixed widths for the bootstrapped select/chosen boxes. I've tried lots of (bad) solutions in my custom components. Results are more weird than status quo ;-)

Should also be discussed separately if this is wanted globally in CoreCode.

On the other hand you can easily implement custom CSS by creating e.g.
/administrator/templates/isis/css/custom.css
and change styling of HTML elements like you need it.

- "Rename the buttons". You can create your own labeling via
Extensions > Languages > Overrides.
Or open a new issue.

I would be happy if you would confirm my PR as "tested successfully" if no other issues concerning functionality occured. Thank you.

**Comment by aasimali** [comment]
@bertmert 

I confirmed that, your PR ( #6682) working as expected. 

One thing, I would like to share with you is, I am not a technical guy, I can not override anything and whatever suggestion/Bug I give/report to Joomla, They are purely at Global level :smiley: 

However, I will open a new issues for the above reported issues Once I get time.

Thank you.

**Comment by brianteeman** [comment]
Closing as the PR has been merged

**Comment by bertmert** [comment]
@aasimali Please reopen your issue here!
(My PR has been removed and I will not start a rework as long template Hathor needs a different  and obscure handling.)

**Comment by bertmert** [comment]
See and test new PR. Also for this issue here.
https://github.com/joomla/joomla-cms/issues/6958

**Comment by zero-24** [comment]
Thanks @bertmert i'm closing in favor of your PR :smile:
