### ISSUE TITLE
Field attribute showon with target field in other group

### ISSUE THREAD

**Issue by piotr-cz** [joomla/joomla-cms#6744]
There's a problem when `showon` attribute is applied to field inside a group, but target field is not within it.

```XML
<fieldset>
     <field
        name="has_full_image"
        type="radio"
    >
        <option value="yes">JYES</option>
        <option value="no">JNO</option>
    </field>
</fieldset>
<fields name="images">
    <field
        name="image_fulltext"
        showon="has_full_image:yes"
    />
</fields>
```

because the attached rel attribute is generating id from the source field:
```HTML
<div class="control-group  showon_yes"  rel="showon_jform[images][has_full_image]">
...
</div>
```

Dirty workaround is to place both field withing same group

**Comment by Fedik** [comment]
some time ago I had idea change to:
```xml
<fieldset>
<fields name="options">
     <field type="radio" >
        <option value="yes">JYES</option>
        <option value="no">JNO</option>
    </field>
</fields>
</fieldset>
<fields name="images">
    <field
        name="image_fulltext"
        showon="options.has_full_image:yes"
    />
</fields>
```
```html
<div class="control-group"  
  data-showon-field="has_full_image" 
  data-showon-value="yes" 
  data-showon-form-control="showon_jform[options]">
...
</div>
```

so in script we can take all fields with name `[has_full_image]` and filter out only the fields that under group `showon_jform[options]` ... in theory such thing can work on repeatable field also .... 
but just a theory :smile:

**Comment by obsidev** [comment]
Hi,

In fact, it is why I was talking about in that thread: https://github.com/joomla/joomla-cms/pull/3379#issuecomment-93838103
And it could be made by a simple modification: https://github.com/joomla/joomla-cms/commit/1b30841510b681ba2adab0a37f9bf82b13c1869c

Regards,

**Comment by photodude** [comment]
I have also found showon fails to work in repeatable fields even when all of the references are in the same repeatable grouping. I've included the showon/repeatable failure as a note in issue #6882

@Fedik your "working theory" seems like a better overall implementation than the current "let's add an 'id' to the field rel for showon" implementation (although I think you have some typo's in your example, i.e. field rather than fields, etc). I've been learning more about object oriented programming concepts recently, I wonder what would be the best way to set up things like showon to function with object references to fields rather than as a procedural item increment reference to the fields? To me (with my very limited experience with javascript and javascript objects and connecting those JS objects to PHP and PHP objects) your method makes more sense to me and seems to be closer to an object implementation. 

I also wonder if this could be propperly implemented so entire fieldsets could have showon references.

**Comment by jawadakr** [comment]
it seems that its not working with modules on front end as well. however same module fields are working fine with showon attribute.

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6744">issues.joomla.org/joomla-cms/6744</a>.</sub>
