### ISSUE TITLE
if cache enabled and before contact page loaded via HTTP and then contact page loaded via HTTPS - reCaptcha not work!

### ISSUE THREAD

**Issue by remotehelp** [joomla/joomla-cms#6807]
if cache enabled and before contact page loaded via HTTP and then contact page loaded via HTTPS - reCaptcha not work! Because loaded via HTTP, script (http://www.google.com/recaptcha/api/js/recaptcha_ajax.js) on HTTPS contact page blocked in browser by default as unsafe...

maybe in /plugins/captcha/recaptcha/recaptcha.php use just "https://www.google.com/recaptcha/api/js/recaptcha_ajax.js" instead:
>$file = $app->isSSLConnection() ? 'https' : 'http';
>$file .= '://www.google.com/recaptcha/api/js/recaptcha_ajax.js';

?

**Comment by zero-24** [comment]
@remotehelp can you try your solution and send a PR with your changes?

If you need help by the PR see: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6807">issues.joomla.org/joomla-cms/6807</a>.</sub>

**Comment by brianteeman** [comment]
@nikosdion as you wrote the recapthca plugin do you have any thoughts on this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6807">issues.joomla.org/joomla-cms/6807</a>.</sub>

**Comment by nikosdion** [comment]
Good morning. I'm afraid I didn't write this plugin :( The plugin was written by @nonumber. It eventually became out of sync with the Joomla! development branch because it took too long to be merged. Since Peter had no time to make the code mergeable, the deadline for the release was looming and I had half a day to spare I stepped in and made the barely minimum changes to make the reCAPTCHA plugin mergeable into the staging branch. I have no idea how the plugin really works.

**Comment by brianteeman** [comment]
ah - my memory failed me @nikosdion

@nonumber any thoughts on this issue?

**Comment by zero-24** [comment]
Closing as we have a PR here: #7237 by @OctavianC Thanks :smile:
