### ISSUE TITLE
Category Manager: Add A New Articles Category :: If the category is trashed and we create another category with the same name & alias, It  should show a proper message

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#6823]
**Real world scenario;**

Admin-1

- He goes to Category Manager: Add A New Articles Category
- He creates a category with the name **Men's wear**
- He trashed it, Because he don't wanna use it

Admin-2

- He goes to Category Manager: Add A New Articles Category
- He creates a category with the  same name **Men's wear**
- He gets an error message ' a category has the same alias'
- But when he goes to category list view, he is unable to find any category with that alias because that category is in trash box. So, He gets confused. needs a proper message, so that he can get to know, the category with same alias is already there in trash box![screen shot 2015-04-23 at 02 02 27](http://issues.joomla.org/uploads/1/8b20353d4a30f2cd9ad7ec27d4f99e2d.png)

**Comment by franzpeter** [comment]
What should it show as proper message. Did you trash the category and then delete it or did you trash it only. If you trash and do not delete, the category is still inside the database. It is just set to trashed. If you want to erase it you need to use the search tools inside the category manager and inside the dropdown - Select Status - choose trashed as status. You will see here that the category is still there. If so choose the category and click on Empty Trash. You can now create a new one with same name and that message will not show up.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6823">issues.joomla.org/joomla-cms/6823</a>.</sub>

**Comment by aasimali** [comment]
@franzpeter 
I know Joomla very well, I know trash/empty trash and all in very much deep. My suggestion was for the million of other users, who could face that issue.

**Comment by gaelicwinter** [comment]
I and my less-than-knowledgeable admin clients get frustrated by this.
Changing the message to

a Trashed category has the same alias and must be deleted first.

or

a Published category has the same alias.

would be extremely helpful and would increase Joomla's uptake by
non-technical people.

Cheers
Paul

On Thursday, April 23, 2015, Aasim Ali <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> @franzpeter <https://github.com/franzpeter>
> I know Joomla very well, I know trash/empty trash and all in very much
> deep. My suggestion was for the million of other users, who could face that
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6823#issuecomment-95810930>.
>


-- 
=============================================

**Comment by Bakual** [comment]
I wouldn't make different messages depending on the publish state of the existing category. But it may be indeed helpful to improve the message so it gives a hint to check the trashed items.
@brianteeman What do you think?

**Comment by brianteeman** [comment]
I don't have a computer at the moment (finally getting ti repaired) I will
try to remember to take a look next week when I get it back but if I don't
comment please remind me. With age comes wisdom but also a lack of memory

**Comment by inesrosas** [comment]
Hi Brian and issue tracker friends.  It's the first time I post, so forgive me if I violate any rules. I just want 2 things:

1.  To agree with this post in that the more descriptive error message would be helpful for newbs.  It took me a little while to figure out that the trashed things remain and the trash must be emptied in order to re-use the aliases.
2.  I also want to add a related issue (wasn't sure whether to poste to this thread or open a new one...)  I'm using joomla 3.4.1 in an xampp server and I cannot empty the trashed categories from the Category Manager Trash. I select all the trashed categories, then click on empty trash, but nothing happens.  No success message, no error message, nothing. The screen just blinks and the trashed categories remain visible. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6823">issues.joomla.org/joomla-cms/6823</a>.</sub>

**Comment by brianteeman** [comment]
Please see #6863

@inesrosas please create a new issue for your second point<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6823">issues.joomla.org/joomla-cms/6823</a>.</sub>
