### ISSUE TITLE
Don't load joomla js on the frontend.

### ISSUE THREAD

**Issue by Mech7** [joomla/joomla-cms#6899]
It's a bit annoying the joomla by default loads it's own jquery and plugins on the frontend.
For every website now we need to remove it in the template it would be nice if there was a setting to stop loading all joomla js in the frontend.

Also it would be a nice improvement if the js is rendered seperatly so we can decide in the template where it is rendered so we can load the js in the bottom instead of the head.

**Comment by Fedik** [comment]
> joomla by default loads it's own jquery and plugins on the frontend

in most cases joomla load it only when it requested by template/layout or extension logic,
this is valid behavior I think

> load the js in the bottom instead of the head

this is old topic :smile: 
of course there some advantages and disadvantages,
but because existing disadvantages could break a lot 3pt extensions, such feature not possible in near future ....
maybe some day in far future in the galaxy far away ... :smile:

**Comment by Bakual** [comment]
Joomla by itself doesn't load any JavaScript. It's all loaded by the extensions.
If the extension is coded properly, a template can override the layout and change it to no longer load the JavaScript.
Also if the extensions all properly load the assets from the media folder, those could be overriden in a template as well.

Closing this issue as not core related as it comes most likely from extensions.
