### ISSUE TITLE
RFC: Menu Manager: Menu Items - [create an "All menus" dropdown option]

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#6912]
If you have multiple Menus, finding an Menu Item can be very time consuming.

#### Steps to reproduce the issue
Open the "Menu Manager: Menu Items" (in the back-end: Menus > "Main Menu")
The Menu Manager has an option to search for menu items (e.g. on menu title, or with "Search Tools" also for extra options like Access, Status, Language).

However, the Menu Manager only search in the current selected menu (in this case "Main Menu"). Sometimes people use more than one Menu and searching for a menu item in any of the menus can take a lot of time.

#### Request For Change 
IMHO it would be great to have an extra selection option in the "Menu Selection" to search in  "All Menus".
That way it would be easier to find a menu item when using multiple Menus.

**Comment by brianteeman** [comment]
It would be useful for search but not for much else. To be useful it would need to have a column to display which menu it is in (think the category column in article manager). Otherwise a site with multiple menu items with the same name across multiple menus will be impossible to differentiate.
If it is really an issue then it can be resolved already by using the frontend menu edit links. That ensures that you select the correct menu.
The more complex the site the harder it gets.
This is really a site design issue especially when people dont give menus meaningful names<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6912">issues.joomla.org/joomla-cms/6912</a>.</sub>

**Comment by ggppdk** [comment]
I agree it is time consuming to search for menu items, even if a site has e.g. 5 menus

e.g. imagine if there was same limitation in article manager
- meaning if you had to select a category before being able to list articles

i understand that the reason behind this is the tree stucture of menus ?

but being able to search in all menus by alias/name/id would be a welcome improvement
of course a new column to show the menu of the item would be needed, and no tree structure would be displayed if no menu is selected

**Comment by dkanchev** [comment]
@pe7er I think that it will be useful for search but in terms of performance it could cause some issues if you have many menus. If this is going to be implemented the results page with all items has to be modified as well, so that results will be dynamically loaded from a cached object.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6912">issues.joomla.org/joomla-cms/6912</a>.</sub>

**Comment by brianteeman** [comment]
@pe7er have you thought any more on this or shall we close it.

As I said before I can see the value for the search filter but I dont think we can do that without adding a column in the list view itself as well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6912">issues.joomla.org/joomla-cms/6912</a>.</sub>

**Comment by infograf768** [comment]
I have created a PR for this. I did not remark a big impact on performance (anyway it is back-end)
Please test
https://github.com/joomla/joomla-cms/pull/8411

**Comment by brianteeman** [comment]
closed as there is a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6912">issues.joomla.org/joomla-cms/6912</a>.</sub>
