### ISSUE TITLE
bug: tooltip help texts on admin dissapers  intermittent

### ISSUE THREAD

**Issue by AbeAlpha** [joomla/joomla-cms#6981]
#### Steps to reproduce the issue
the tooltips of admin panel on mouse over sometimes dissapers and somtimen is hard to get back for read, have to click outside and over text other time. i solve this isue with this short code.
This happen for the space of chars

#### Expected result
.control-label .hasTooltip {
    background-color: transparent;
    cursor: text;}

#### Actual result
i solve for my self, maybe urs will fix this

#### System information (as much as possible)
j3.4.1 w7 localhost xampp 563 clean install

#### Additional comments
Tanks for do liberty on this world!

PD: This is other code that for me, admin panel works better.

#sbox-window{
width:95%!important;
height:95%!important;
left: 1.5% !important;
top: 2% !important;
position:fixed!important;}

#sbox-content > iframe:nth-child(1){
width: 99%;
height: 100%;}

.header{
position:fixed;
top:16px;
width:100%;
margin-left:27px;
padding:0px;
background-color: transparent;z-index:1000;
border-top:0px solid #000;}

#status{
box-shadow:none;}

.page-title{
z-index:2031;color:#f00;font-size: 8px;}
@media (max-width:767px){.page-title{display:none !important}}

**Comment by creative3d** [comment]
Hello, I want to add a little. I've been experiencing this issue since J 3.0 (J 2.5 and below was fine!), wrote on joomlacode org once, but they ignored the issue. For better view, install the plugin Tooltips from NoNumber, and try to "play" with tooltips over different objects (texts, images etc). It depends a little bit on the speed of going in and out of a tooltip. Since it's kind of very old bug, I want to see that it has at least medium priority and it's going to be fixed, is it? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>

**Comment by brianteeman** [comment]
If it is an issue only seen when using an extension then perhaps the issue is with the extension?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>

**Comment by creative3d** [comment]
No, no, that's for sure related to Joomla. The author of this topic wrote that it appeared in admin panel when hints ("help texts") are used.
The extenstion Tooltips from NoNumber is using these hints. I wrote about it to NoNumber, they answered that it's some kind of "a speed issue in jQuery/Bootstrap. Not much I can do about it." And with the extension it's just easier to see the issue...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>

**Comment by creative3d** [comment]
For testing: [tooltest.txt](https://issues.joomla.org/uploads/1/65b19c5b2e7c1acd453e1c62561faee6.txt) 
It a table with tooltips, put it in a joomla article (NoNumber tooltips installed), try going in and out of ONE tooltip, fast, until it stops working at all. When it stops working (you don't see your tooltip or it blinks and dissappears instead of showing), you can mouse over another tooltip, this action fixes the problem. Hope explained well...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>

**Comment by brianteeman** [comment]
@creative3d based on the answer you received form NoNumber there is nothing joomla can do about it either as they are external libraries.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>

**Comment by creative3d** [comment]
First of all, NoNumber could be wrong, they didn't do anything, secondly, it worked before 3.0, if it's a library problem, then it should be reported somewhere else. A lot of functionality on my site depends on these hints, and they don't work properly. And again one person had a quick look and decided to close the issue without solving it. That's not fare. Let someone look at it properly, let someone decide where the issue comes from and how to solve it, not just close it!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>

**Comment by brianteeman** [comment]
If NoNumber says the problem is not in the joomla core but in an external
library then I 100% trust his assessment

First of all, NoNumber could be wrong, they didn't do anything, secondly,
it worked before 3.0, if it's a library problem, then it should be reported
somewhere else. A lot of functionality on my site depends on these hints,
and they don't work properly. And again one person had a quick look and
decided to close the issue without solving it. That's not fare. Let someone
look at it properly, let someone decide where the issue comes from and how
to solve it, not just close it!
------------------------------
This comment was created with the J!Tracker Application
<https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6981
<https://issues.joomla.org/tracker/joomla-cms/6981>.

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHub
<https://github.com/joomla/joomla-cms/issues/6981#issuecomment-218427962>

**Comment by creative3d** [comment]
If the problem is in an external library, this library should be found and fixed somehow, don't you think so? I'm not a developer, so I can't do much here, especially when everybody says that's it is not their problem and closes topics. It's related to joomla, joomla uses it, joomla uses libraries with bugs, so we are all going to just ignore it, aren't we?
Have you reproduced the issue? Do you want me to create an issue here? What category?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>

**Comment by mbabker** [comment]
If the issue exists in a third party library, then someone should report it to the library, but it isn't Joomla's job to filter issue reports and forward reports to third party teams.  In the case of Bootstrap, they're probably going to ignore it unless it's a bug in 3.3 or the 4.0 dev branch so that leaves core hacking their library if it's a bug with Bootstrap 2.3.  Either way, it's not a "well it's broken in Joomla so Joomla must find a way to fix it" scenario.

**Comment by creative3d** [comment]
I'm not asking core hacking, it's just first of all, we don't know the cause of the issue yet, only assumptions, secondly, if joomla team can't do anything, then we need to report in the place that can do something. Right now if I stop writing, I see that everybody will forget about it immediately :) That's not good...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6981">issues.joomla.org/joomla-cms/6981</a>.</sub>
