### ISSUE TITLE
Menu Manager > Menu Item Type > articles with given TAG not only as LIST but also as BLOG

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#7020]
#### Steps to reproduce the issue
Tags are quite recent in Joomla and are an interesting feature.
However, the Menu Types in Menu Manager only propose to show the articles with a given Tag _in the form of a LIST_.
It would be very useful to have an extra Menu Item Type : showing the articles with a given Tag _in the form of a BLOG_.
![screen shot 2015-05-23 at 13 15 29](http://issues.joomla.org/uploads/1/751a91944ac2ae54f3cf6c506e555e8c.png)

**Comment by bertmert** [comment]
@woluweb 
Do you want to test this PR https://github.com/joomla/joomla-cms/pull/6792 ?
It's related to your feature request because without it it's not possible to display images e.g. of categories (https://github.com/joomla/joomla-cms/issues/6331), other items than articles and so on.
Detailed test instructions: https://github.com/joomla/joomla-cms/pull/6792#issuecomment-104980292

Testing it successfully would be a step forward.

**Comment by brianteeman** [comment]
please see #10242<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7020">issues.joomla.org/joomla-cms/7020</a>.</sub>

**Comment by smz** [comment]
... and  #10346

IMHO, nor #10242 nor #10346 are a **true** solution to what you (_and apaprently many others_) are requesting, but maybe we are converging on a solution and, most important, contributing to raise the awareness about how much needed this is...

@woluweb You might also be interested in reading the Google Group thread (https://groups.google.com/forum/#!msg/joomla-dev-cms/YVwuuNYHFUQ/hHs7_kaFAgAJ) **if you have a week of spare time**...  :smile:
