### ISSUE TITLE
SQL error with Article Manager

### ISSUE THREAD

**Issue by dbegit** [joomla/joomla-cms#7036]
#### Steps to reproduce the issue
Content->Article Manager->New->Save

#### Expected result
no SQL error.

#### Actual result
Error

Save failed with the following error: SQL=INSERT INTO "gqcy4_content" ("title","alias","introtext","fulltext","state","catid","created","created_by","modified","publish_up","publish_down","images","urls","attribs","version","access","metadata","featured","language") VALUES ('plan du site','plan-du-site','

plan du site
','',1,2,'2015-05-26 00:33:24',919,'2015-05-26 00:33:24','2015-05-26 00:33:24','1970-01-01 00:00:00','{}','{}','{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":"","show_publishing_options":"","show_article_options":"","show_urls_images_backend":"","show_urls_images_frontend":""}',1,1,'{}',1,'*') RETURNING id

#### System information (as much as possible)
Joomla! 3.4.1
PHP 5.6.8
Postgresql 8.4.20

**Comment by BuddhiEash** [comment]
Hi is this only occurs with Postgresql?Because with MySQL it works fine it seems.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7036">issues.joomla.org/joomla-cms/7036</a>.</sub>

**Comment by brianteeman** [comment]
I can not replicate this with current staging and postgres 9.3.5
Either this is an issue already fixed in staging or it is specific to that old version of postgres

Please download the current staging version of Joomla from here https://github.com/joomla/joomla-cms/archive/staging.zip and retest and post back<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7036">issues.joomla.org/joomla-cms/7036</a>.</sub>

**Comment by BuddhiEash** [comment]
Thanks for the clarification brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7036">issues.joomla.org/joomla-cms/7036</a>.</sub>

**Comment by brianteeman** [comment]
Can you please confirm that you are still having this issue with the current staging version? If not then we can close this issue

**Comment by brianteeman** [comment]
This looks like it could be another issue that ONLY exists in old unsupported versions of postrges and we need to review if we should simply increase the system requirements. Setting to needs review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7036">issues.joomla.org/joomla-cms/7036</a>.</sub>

**Comment by Kubik-Rubik** [comment]
This is a known issue which cannot be resolved in this version of Joomla!. As it is specifically related to using a very old release of the database software on your server the only remedy is to update that to the latest release.

I will close this issue. Thank you!
