### ISSUE TITLE
Any User Manager:Edit User Changes Requires Password Confirmation

### ISSUE THREAD

**Issue by mrmonteith** [joomla/joomla-cms#7054]
#### Steps to reproduce the issue
1. User - User Manager
2. Click on the user to edit
3. Go for instance to Assigned User Groups and make a change and try to save

#### Expected result
Should save the update

#### Actual result
Warning
Invalid field: Confirm Password

#### System information (as much as possible)
Setting 	Value
PHP Built On 	Windows NT 4648DS 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
Database Version 	5.6.21
Database Collation 	latin1_swedish_ci
PHP Version 	        5.6.3
Web Server 	        Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	       Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0 

#### Additional comments
If the user is already registered and if they changed their password you're not going to know what the password confirmation is.  If you're an administrator you shouldn't have to be touching their password field to update.  Otherwise every time you update something on a user you'll end up changing their password.

**Comment by infograf768** [comment]
Using staging, and as a superuser, I changed some parameters for a registered user without being asked for a password. Saved OK. 

Note: `Database Collation latin1_swedish_ci` is not good. You should correct your database collation to `utf8_general_ci`

**Comment by mrmonteith** [comment]
Guess that's something I need to learn is what Staging is and how to use it. 
BTW, thanks. I did change the database to utf8_general_ci.  All the tables were right.
It's pretty much proof of concept right now but looks like Joomla will do what I want with our
internal site. Guess it's time to do some heavy reading.  It will cure any insomnia I'm sure.  Thanks

**Comment by wilsonge** [comment]
Staging is the latest development version of Joomla. Joomla has 4 branches on github going generally (as you can see: https://github.com/joomla/joomla-cms/branches) staging is the stage which is what we add all our bug fixes to. Master is generally the same as staging however code is only pushed there once all the unit tests and code style checks have passed. 2.5 contained the 2.5 branch when we were maintaining it. Finally 3.5-dev contains the features that we are merging in anticipation of Joomla 3.5. Generally you don't want to use Joomla's branches as this is cutting edge code which you should use for testing rather than for production websites.

Joomla's documentation is often cited as a weaker area and is something we are working hard on. So if you do start looking around at it and have any feedback or questions you don't feel are answered on there (you should be able to see my email address on my github profile)

Can I just confirm though did changing the database collation fix things for you? If so I'll close this issue!

**Comment by colivier** [comment]
I have exactly the same issue. When I try to change and save an user in the backend and I can't do it because I receive an alert

Invalid field: Confirm Password

I tried also in the profil of the user in the frontend and it is the same issue, the confirm password is asked

I use the Joomla version 3.4.1

**Comment by infograf768** [comment]
Hmm...
In my test above, as superuser, I tested changing a registered user parameters and I had no issues.
In that case both the password field and the confirm password field were empty.

BUT, if I try to modify my superuser account itself, I am asked for confirm password indeed as the password field is automatically filled with the existing password, but the confirm password field is empty.

Then I tested this with different browsers:
I do have the issue in Firefox, not in Chrome or Safari (Macintosh) 

As you can see, there is no asterisque (*) next to these fields (backend) and `autocomplete="off"` is set for both fields... 
It means they are not compulsory when editing an existing user.

**Comment by infograf768** [comment]
See:
http://stackoverflow.com/questions/17781077/autocomplete-off-is-not-working-on-firefox

**Comment by infograf768** [comment]
Here is a PR which should fix the issue.
https://github.com/joomla/joomla-cms/pull/7094

Please test.

We can close this issue.

**Comment by colivier** [comment]
Effectively I was using FF and I had the issue with this browser. So I tested on Chrome and it was ok

Thank you very much for your PR for FF, I will test it.

**Comment by ggppdk** [comment]
Tested on firefox 42+, the workaround to prevent firefox autocompleting the password field, does not seem to work anymore.

A JS solution:
```
	jQuery(document).ready(function() {
		jQuery('input[type=password]').each(function() {
			jQuery(this).val('');
		});
	});
```
the bad with the above is that
-  if someone tries to load a "new" password into the form then it will be cleared, i don't know of such a case, but maybe theres is ?

but this seems to work, and should introduce a new bug, like the JS above,
replace:
```
<?php // Disables autocomplete ?> <input type="text" style="display:none">
```
with:
```
<?php // Disables autocomplete ?> <input type="password" style="display:none">
```

**Comment by cdekok** [comment]
Yup have the same issue on firefox :-1: not fixed yet..

**Comment by brianteeman** [comment]
Please test on current staging release
