### ISSUE TITLE
Simple RSS feed has stopped rendering xml file data on webpage

### ISSUE THREAD

**Issue by kero1984** [joomla/joomla-cms#7142]
#### Expected result
XML data from an RSS feed is updating as it should, it normaly then renders the xml data onto a our homepage.

#### Actual result
XML data from an RSS feed is updating as it should, it normaly then renders the xml data onto a our homepage but it is just keeps coming up blank.

#### System information (as much as possible)
Running windeos server 2003 STD
Site - The Nexus
Running Joomla 1.5.20
Module name - mod_jw_srfr
#### Expected result
XML data from an RSS feed is updating as it should, it normally then renders the xml data onto our homepage.

#### Actual result
XML data from an RSS feed is updating as it should, it normally then renders the xml data onto our homepage but it is just keeps coming up blank.

#### System information (as much as possible)
Running windows server 2003 STD
Site - The Nexus
Running Joomla 1.5.20
Module name - mod_jw_srfr

#### Additional comments
I am not the most knowledgeable person when it comes to working with joomla, but i have a good understanding of the workings of our site.

#### Additional comments
I am not the most knowledgebal person when it comes to working with joomla, but i have a good understanding of the workings of our site.

Ive cleared out the cache for the module, restarted services used to pull in the data to the XML file, change the link in the module to another XML document, disabled/enabled the module, disabled/enabled the site. all of the above have not worked for me.

**Comment by zero-24** [comment]
@kero1984 

>Running Joomla 1.5.20

This is a very old Version of Joomla (18 July 2010) with known security issues. Please update at least now to 1.5.26 (download: http://joomlacode.org/gf/project/joomla/frs/?action=FrsReleaseBrowse&frs_package_id=6311)

After this please apply this hotfix: 
http://joomlacode.org/gf/download/trackeritem/31626/83528/UploadFix15v3.zip
see: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31626

Than please start planning a migration to 3.4.1

This is a migration component that can manage that: http://redcomponent.com/redcomponent/redmigrator
http://redcomponent.com/redcomponent/redmigrator/redmigrator-component

>Module name - mod_jw_srfr

If you successful migrated from 1.5 to 3.4 you can try this version of the external extension: http://www.joomlaworks.net/extensions/free/simple-rss-feed-reader
This is the last version that works with the current Joomla Version.

I'm going to close this now as you use a very old version of Joomla and the issue is not in the Joomla core rather in a external extension. Thanks

**Comment by kero1984** [comment]
I have one last quick question on this, would it be that the older version of the RSS module is not compatiable with Rss2.0? I think the site i was recieving the updates from upgraded there RSS Feed to that lately.

Thanks for your reply we will have to do a feasibility on upgrading the server as we are ceasing operations later this year.

Regards,
Kierán

**Comment by zero-24** [comment]
>would it be that the older version of the RSS module is not compatiable with Rss2.0?

maybe. I don't know this old version. If you are on 3.4 and the last version of the extension you can ask the extension developer.
