### ISSUE TITLE
wrong options applied to Single Article

### ISSUE THREAD

**Issue by Nzara** [joomla/joomla-cms#7343]
### Back End
* Set Global configuration
 * Global Configuration - Site - SEO Settings - Search Engine Friendly URLs : **Yes**
 * Global Configuration - Articles -  Show Title	: **Show**
* Create Articles
  1. 
    * Title: **Title-A**
    * Content: **Content-A**
    * Options - Show Title: **Use Global**
  2. 
    * Title: **Title-C**
    * Content: **Content-C**
    * Options - Show Title: **Use Global**
  3. 
    * Title: **Title-B**
    * Content: **Content-B** 
    * use Button *Article* to insert a link to Article 'Title-C' displayed as *Link-to-C*
    * Options - Show Title: **Use Global**
* Create Menu
 1. 
    * Title: **Home**
    * Menu Item Type: **Single Article**
    * Select Article: *Title-A*
    * Default Page: **Yes**
    * Show Page Heading: **Show**
    * Options - Show Title: **Hide**
  2. 
    * Title: **Menu-B**
    * Menu Item Type: **Single Article**
    * Select Article: *Title-B*
    * Default Page: **No**
    * Page Display - Show Title: **Show**

### Front End
* Navigate
  1. Select **Menu-B**
  2. Follow **Link-to-C**

## Expected Result
**Title-C**
Details ....
Content-C
## Actual Result
**Home**
Details ...
Content-C

## Additional comments
It seems, the options of menu *Home* are applied when displaying article *Title-C*

**Comment by richard67** [comment]
if you set show title for the page display to yes, then by default the menu item title is taken for the H1 header, and so it is ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7343">issues.joomla.org/joomla-cms/7343</a>.</sub>

**Comment by Nzara** [comment]
@richard67: maybe my description is not clear enough. Let me try to clarify:
Click on menu 'home' displays H1 'home' ... 'Content-A' - that is OK
Click on menu 'menu-B', than follow link-to-C displays H1 'home' ... 'Content-C' -- that mixes up menu item home with the with article 'title-C'<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7343">issues.joomla.org/joomla-cms/7343</a>.</sub>

**Comment by Bakual** [comment]
Joomla tries to guess a matching menu item for that article-c. This is correct. If there is no menu item specific to that article and no menu item to its category, then it tries to find another one from com_content I guess (would have to check exact logic). In your case it seems to take the home one.
Since the article doesn't specify params, the ones from the menu item are used. That seems to be correct as well.

You could probably fix your issue by creating a "shadow" menu item for that article.

**Comment by joo7** [comment]
This is imho a confusing logic in Joomla since 1.5 or earlier.

Maybe instead of using "title" everywhere 
we use more selfexplaining "page-title, menu-title, article-titel, category-title, block-title..."

and a new global configuration item "page-title" (or combine with configuration setting "site-title"): 
 - use article-titel as page-title when no matching menu item is specified
 - use category-titel as page-title when no matching menu item is specified
 - guess title as page-title when no matching menu item is specified (old behavior - default for update ;)

like this we can get rid of many hidden menu items :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7343">issues.joomla.org/joomla-cms/7343</a>.</sub>

**Comment by Bakual** [comment]
I don't understand. It's not per se about titles. It's about parameters. The title is just one of many parameters.

**Comment by Nzara** [comment]
@Bakual: Thank you for this explanation. Unfortunately i  did not take into account the possibility of such an logic before creating this issue. I must have missed relevant the parts of documentation. I expected joomla to calculate effective params from the globals and the article params only, if the article is not explicitly governed by an menu item.
Thanks also for the hint to solve my issue. However, I have to find something else because i have many of such articles and users will create new ones occasionally. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7343">issues.joomla.org/joomla-cms/7343</a>.</sub>

**Comment by smz** [comment]
If all those articles share a common category a menu entry for that category in a shadow (*hidden, not published*) menu hierarchy would probably solve your issue...

**Comment by joo7** [comment]
In that case all articles
        without menu item will have the same page-title of that
        category.
        we need article-title
        = page-title
        (my site has 180 hidden menu items
            because of this issue :)
        I guess this is a feature request and no issue/bug.
        No need learning concept of hidden menues = Better user experience for new joomla-users
            :)
        
        
      
    Am 07.07.2015 um 15:20 schrieb Sergio
      Manzi:
    
    
      If all those articles share a common category a menu entry for
        that category in a shadow (hidden, not published) menu
        hierarchy would probably solve your issue...
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by joo7** [comment]
looks like there is a github issue, giving out full name via email + 
strange linebreaks - sorry for that...

**Comment by smz** [comment]
@joo7 No problems for me: I'm not hiding my name! :smile:

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7343">issues.joomla.org/joomla-cms/7343</a>.</sub>
