### ISSUE TITLE
Upgrades from 2.5 broken due to missing web links component

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#7480]
#### Steps to reproduce the issue
Take a Joomla 2.5 web site and use the update component to update it to the latest release (3.4.3) (It will be easier to test if you use the default sample data as that includes some weblinks)

#### Expected result
Joomla and all its components are updated

#### Actual result
Everything is updated except for weblinks as this is not part of the update package. There is no notification to the user that weblinks has not been updated.

Try to use the weblinks component in the back end and it results in

### back end after upgrade

![screen shot 2015-07-20 at 10 44 00](http://issues.joomla.org/uploads/1/8e549fcdcde18df84a2dadb94a84cfce.png)

#### Additional comments

The roadmap states
> Any existing CMS installations when upgrading will not lose existing extensions.

The update component uses https://github.com/joomla/joomla-cms/releases/download/3.4.3/Joomla_3.4.3-Stable-Update_Package.zip which does not include com_weblinks

**Comment by rdeutz** [comment]
looked back to 3.4.0 the weblinks component is missing since then or maybe longer, not that this is a big change for the issue at hand but looks odd that we need so long to find out. Anyone tried only to upgrade to 3.4.0 ?

**Comment by mbabker** [comment]
There's a few ways to look at this, and though it may start to sound like
I'm swaying toward an "expected behavior won't fix" stance, it really isn't
my intent.

So yes, weblinks itself is not updated.  Technically, the roadmap statement
about not losing existing extensions is valid; weblinks itself is untouched
on the pre-3.3 to 3.4 upgrade path.  It must be updated as any other
extension would upon arrival to the 3.4 environment.

Unfortunately, we have a really not optimal update system.  It would be
possible to trigger an update for the newly installed package in our
install script.  However, since we do not have a mechanism to catch the
pre-update version of the CMS, it will run on all updates no matter what; a
CMS update will force a weblinks (and other decoupled extension) update at
each release.  IMO this isn't very optimal.

To include weblinks in update packages bringing folks up to 3.4+ from 3.3-,
our scripts would have to be smart enough to download the weblinks stable
package and extract it into the packaging workspace correctly.  That's
probably the easier thing in this.  The tricky part is wiring up our
updater to trigger weblinks (and other extension) scheme updates.  To me,
this behavior goes against the spirit of decoupling and Modularizing the
platform.  Actually, both of my thoughts about things that can be done to
improve the UX around this would put more strain on our update platform; it
would have to be done very carefully if we tried it.

With the state we are in right now, there aren't many "good" options.  Do
we have the CMS update component trigger decoupled extension updates (in
which case I'll bluntly ask why bother decoupling the stuff when it can't
be managed in a decoupled manner)?  Do we accept this behavior and treat
decoupled extension updates in the way we would third party extensions?

Just my shooting from the hip thinking, but that's my first thoughts on the
less-than-optimal situation we're in with the first less-than-optimal
solutions I have.

**Comment by brianteeman** [comment]
> looked back to 3.4.0 the weblinks component is missing since then or maybe longer, not that this is a big change for the issue at hand but looks odd that we need so long to find out. Anyone tried only to upgrade to 3.4.0 ?

Possibly because the frontend still works for weblinks and possibly because few people use it. I noticed some people on the forum talking about doing manual upgrades from 2.5 to 3.2 so that they would get com_weblinks which is why I checked.

And no com_weblinks has not been part of an update package since it was decoupled.

>  (in which case I'll bluntly ask why bother decoupling the stuff when it can't be managed in a decoupled manner)?

If this situation cant be changed then I'm afraid you are correct and we have gone from "one click" updates to breaking peoples sites all over again

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7480">issues.joomla.org/joomla-cms/7480</a>.</sub>

**Comment by mbabker** [comment]
I don't think we have our behavior of "one click updates" defined as far as
decoupled extensions go.  If the expectation is that updating the CMS via
the component updates core extensions, in package or standalone, then the
exercise of decoupling is a futile effort and we should instead concentrate
on making sure core stuff can't be accidentally (or
purposefully) uninstalled.  If we elect to not have the CMS update core
extensions as well, how do we communicate this intended design pattern and
what the user expectations are (i.e. One click is only for "core CMS" and
all updates are more like 4 or 5 clicks)?

Answers, I don't have, but hopefully it gives someone some food for thought
in coming up with a plan.

**Comment by Bakual** [comment]
I haven't tested the update from 2.5 yet, but there should be an updateserver available for weblinks after you updated to 3.4.3. If that is not the case, then that needs to be fixed.
That updatestream should show an update for com_weblinks after you updated to 3.4.3. If that is not the case, then that is a bug.

However updating to 3.4.3 and expect to have weblinks in the current version as well is not expected behavior. It should show an extension update for weblinks which has to be run independant from the CMS update like any other extension. That would be the expected behavior for me.

**Comment by brianteeman** [comment]
Please test it and see yourself

On 23 July 2015 at 09:26, Thomas Hunziker <notifications@github.com> wrote:

> I haven't tested the update from 2.5 yet, but there should be an
> updateserver available for weblinks after you updated to 3.4.3. If that is
> not the case, then that needs to be fixed.
> That updatestream should show an update for com_weblinks after you updated
> to 3.4.3. If that is not the case, then that is a bug.
>
> However updating to 3.4.3 and expect to have weblinks in the current
> version as well is not expected behavior. It should show an extension
> update for weblinks which has to be run independant from the CMS update
> like any other extension. That would be the expected behavior for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7480#issuecomment-124020454>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
Just tested. All is actually right in the CMS. The issue is coming from the weblinks manifest. (https://github.com/joomla-extensions/weblinks/commits/master/manifest.xml)
The last commit to this file is from @wilsonge and I have no clue why he did that. It invalidates the manifest and thus there is never an update shown for weblinks.

From the commit message I guess he wanted to revert another PR, but reverted the wrong commit?
George? Any insight? :smile:

**Comment by wilsonge** [comment]
The reversion was intentional - I just referenced the wrong PR. Full explanation here: https://github.com/joomla-extensions/weblinks/pull/29

**Comment by brianteeman** [comment]
Either way it means that people who upgrade from 2.5 are left with a broken
weblinks as per the original post without any notification they need to
update the component. And they cant update it from "install from the web"
either as that is broken as well

On 23 July 2015 at 12:56, George Wilson <notifications@github.com> wrote:

> The reversion was intentional - I just referenced the wrong PR. Full
> explanation here: joomla-extensions/weblinks#29
> <https://github.com/joomla-extensions/weblinks/pull/29>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7480#issuecomment-124073566>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
@wilsonge What is the stopper to release the fixed weblinks then? The issue mentioned in the PR has been solved since two months :smile:

**Comment by wilsonge** [comment]
Getting agreement on how to release core supported stuff really - me and Jess were going to sit down in Prague - but for a variety of reasons we've not found the time to sit down together yet

**Comment by brianteeman** [comment]
Well the situation right now is that it is breaking users sites etc. Please
make this a high priority to resolve - it shouldnt take more than a few
minutes surely to resolve

On 23 July 2015 at 13:58, George Wilson <notifications@github.com> wrote:

> Getting agreement on how to release core supported stuff really - me and
> Jess were going to sit down in Prague - but for a variety of reasons we've
> not found the time to sit down together yet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7480#issuecomment-124087218>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
Just release the thing. We don't need a stinky process for releasing such a small extension :-)

**Comment by mbabker** [comment]
:+1:

Seriously, tag and bag it.  Throw a tweet out linking to the releases page.  Have a nice day.  Y'all can make a "formal" procedure later on.  I'd just do it, but I once again don't have Phing installed because of how I manage my Homebrew PHP setup.

**Comment by rdeutz** [comment]
If you need someone to hit phing on the command line, I can do that :-)

**Comment by mbabker** [comment]
I've got it installed, look for more from me in a moment :wink:

**Comment by mbabker** [comment]
https://github.com/joomla-extensions/weblinks/pull/78

**Comment by Bakual** [comment]
@brianteeman Can you check if it works now? Weblinks 3.4.1 is released and you should see an update now.

**Comment by brianteeman** [comment]
Yes that resolves it. As soon as you do the Joomla update and return to the admin control panel you get the notification of an extension to update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7480">issues.joomla.org/joomla-cms/7480</a>.</sub>

**Comment by brianteeman** [comment]
This has now been resolved with the release of weblinks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7480">issues.joomla.org/joomla-cms/7480</a>.</sub>

**Comment by Bakual** [comment]
Cool, thanks!
