### ISSUE TITLE
Featured layout orders by category not date

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#7482]
#### Steps to reproduce the issue

create mixed date articles with article ordering NOT by date.  So that the latest article won't have a higher article id then others.
display by multi category and make the latest featured article NOT the first category.
tell it to display by date.
it will display by category instead.
set options globally and it will display correctly.  See images for examples
These fail
![screen shot 2015-07-20 at 13 34 10](http://issues.joomla.org/uploads/1/dcb8756e6ce74c0b7dfcedfbd036f610.jpg)
![screen shot 2015-07-20 at 13 34 11](http://issues.joomla.org/uploads/1/d6bf32c4378b89147e151779c5461ccb.jpg)

this one works
![screen shot 2015-07-20 at 13 34 13](http://issues.joomla.org/uploads/1/a9ff5fa37981eb6b02274f20d69796a2.jpg)
#### Additional comments

**Comment by brianteeman** [comment]
I am confused because the first two screenshots both show sort by category order<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7482">issues.joomla.org/joomla-cms/7482</a>.</sub>

**Comment by Bakual** [comment]
As it has been resolved in the JBS chat, I'm going to close this here.
