### ISSUE TITLE
Wrong itemprop in the Featured Articles Blog Layout

### ISSUE THREAD

**Issue by pyberg** [joomla/joomla-cms#7669]
#### Steps to reproduce the issue
Featured Articles Menu Item Type
/templates/lmk/html/com_content/featured/default-item.php, line 26:

#### Expected result
h2 class="item-title" itemprop="headline"

#### Actual result
h2 class="item-title" itemprop="name"

#### Additional comments

Google wants the itemprop to be "headline"

**Comment by infograf768** [comment]
I guess you are right as it is a h2
In core : ROOT/components/com_content/views/featured/tmpl/default_item.php

I can see this in other parts of code in core like 
ROOT/layouts/joomla/content/blog_style_default_item_title.php

etc.
We have 13 itemprop="name" and a few of them are concerned.

**Comment by bertmert** [comment]
To be discussed, please:
Question for me is (because not only Google rules) if these itemprops in com_content should be changed into

```
itemprop="headline name"
```

or just
```
itemprop="headline"
```
Both are OK and allowed.
Shema org Articles defines "name" as "name of the item".

(I use name as a leading subpart inside headline but that's not the question here)

References
http://schema.org/Article
https://developers.google.com/structured-data/rich-snippets/articles

**Comment by pyberg** [comment]
New post about the issue

[url]http://forum.joomla.org/viewtopic.php?f=706&t=895734&p=3334312#p3334312[/url]

**Comment by bertmert** [comment]
I'm just waiting for an answer before I start a new Pull Reuest ;-)

```
I use name as a leading subpart inside headline but that's not the question here. Edit->or is it? itemprop name directly for the pure title, headline for the H tag including link etc.
```

**Comment by joo7** [comment]
just itemprop="headline":

because it is the headline (h2) of the item (blogpost/article/etc.) and it can be but does not have to be the name of this item (blogpost/article/etc.) 

and searchengineoptimizers in times of voice-search (siri/hellogoogle/etc.) might be happy to give an item a different name and headline

and we will get b/c issues if the h2 headline is now both and we might want to separate them later...

**Comment by conconnl** [comment]
I agree with @joo7
If you create the PR, we can test it for you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7669">issues.joomla.org/joomla-cms/7669</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR for testing see #11410<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7669">issues.joomla.org/joomla-cms/7669</a>.</sub>
