### ISSUE TITLE
Cache Handling - Administrator

### ISSUE THREAD

**Issue by RalfF1** [joomla/joomla-cms#7779]
#### Steps to reproduce the issue
1. When deactivating Cache in Configuration - System the cache folder in /administrator will be deleted
2. File-Storage isn't longer available
3. After activating Cache (Normal/Exteded) will not affect the "File" storage posibilites (no File-Cache) and the cache folder in /administrator will not be created.

Tested this on a webserver with difficult right system (onwer ftp or php user)
Not shure whether this issue can be reproduced in other environments.

**Comment by brianteeman** [comment]
After so long without any other comments or reports of this I am sorry to say that this must be (as you suspected) due to your odd server configuration which is beyond our control.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7779">issues.joomla.org/joomla-cms/7779</a>.</sub>
