### ISSUE TITLE
Joomla 3.4.3 and 3.4.4 RC does not accept two bytes code characters in editing page TAG

### ISSUE THREAD

**Issue by goyat** [joomla/joomla-cms#7807]
#### Steps to reproduce the issue
Just go to a new editing page and write two bytes code characters like Japanese 今日　
You would see the input Japanese 今日　is not permitted as the tag.

#### Actual result
It should be accepted as the tag word.

#### System information (as much as possible)
Joomla 3.4.3 and 3.4.4 RC
MySQL 5.5
PHP   5.4

**Comment by gwsdesk** [comment]
This I can confirm. It only accepts 3 digits at present. This should be changed since in many languages 2 digits are used in words so these should be able to get tagged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7807">issues.joomla.org/joomla-cms/7807</a>.</sub>

**Comment by gwsdesk** [comment]
correction: You can set the number of digits in the Globals of the Tags component. Per default set to 3 digits but if you set it to 2 digits you can create a Tag with 2 digits. I just created the Tag "Pa" and added that to an article and accepted<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7807">issues.joomla.org/joomla-cms/7807</a>.</sub>

**Comment by goyat** [comment]
Thank you for your advice. I have confirmed TAG accepting two bites code by changing 3 digits to 2 digits.
Norito<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7807">issues.joomla.org/joomla-cms/7807</a>.</sub>
