### ISSUE TITLE
Banners do not work if meta search is active.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#7958]
![meta](https://cloud.githubusercontent.com/assets/1850089/10086913/a2b49106-62d6-11e5-846e-c2c37fa8788f.jpg)

**Comment by rgblogs** [comment]
On my site, it is working.

Add same Meta tag in banner and in article, create a menu item to article, publish banner module, it is working<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7958">issues.joomla.org/joomla-cms/7958</a>.</sub>

**Comment by brianteeman** [comment]
Closing due to lack of information<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7958">issues.joomla.org/joomla-cms/7958</a>.</sub>

**Comment by SeoPro24** [comment]
Hello,

i have exact the same problem like N6REJ had.

1. 
I create a banner http://take.ms/ib4OY
Banner details: http://take.ms/VR0cz
Publishing details: http://take.ms/lOI23

2. I was publish the banners module and was enable in the module the meta recognition.
http://take.ms/GbDhC

3. I was use the same keyword(s) in the article where the banner should appear as well on the right column. 

But it does not appear. 
The banner only appear if i disable the "Search by Meta Keyword" but this scenario is not so well since i want only to use one module to publish all banners accordingly the respective article.

Joomla! 3.6.4 is used.

Thank you to fix this bug!


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7958">issues.joomla.org/tracker/joomla-cms/7958</a>.</sub>
