### ISSUE TITLE
Template assignation issue with function "includeRelativeFiles" - JFactory::getApplication()->getTemplate()

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#7966]
#### Steps to reproduce the issue
- set a template as default
- set another template assigned on a specific page
- use the function JHtml::_('jquery.framework'); in a plugin or else on this page
- the assigned template will not be shown, the default template is used. 
- unpublish the plugin or comment the line, the assigned template is used 

#### Expected result
- the assigned template shall be used on the specific page

#### Actual result
- assigned template not used, the default one is used instead

#### Additional comments
I have found the problem in the file
libraries\cms\html\html.php
in the function "includeRelativeFiles"

It searches for the template with "$template = JFactory::getApplication()->getTemplate();" and it seems that it returns the default template

In fact the problem may be more in the getTemplate() function, I have not investigated more for now...

**Comment by brianteeman** [comment]
@ced1870 It has been almost a year since you raised this as an Urgent issue. There has been no response at all to even confirm the issue. Maybe that is because it is no longer a valid issue or because your instructions are not clear. 

Please can you update this issue or it will be closed in a few weeks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7966">issues.joomla.org/joomla-cms/7966</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this at this time as stated above. It can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7966">issues.joomla.org/joomla-cms/7966</a>.</sub>
