### ISSUE TITLE
Newsfeeds List Layout Filter Feed

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#8013]
#### Steps to reproduce the issue

Navigate to Joomla Backend -> Components -> Newsfeeds -> Options -> List Layout

#### Expected result

In filter field, Hide should be red color.![screen shot 2015-10-04 at 10 59 42](http://issues.joomla.org/uploads/1/4297f4e8b42d3feeb95734c7effff987.png)

**Comment by infograf768** [comment]
The issue here is that the "Hide" option value is "hide" instead of "0"
```
<field
			name="filter_field"
			type="radio"
			class="btn-group btn-group-yesno"
			default="1"
			description="JGLOBAL_FILTER_FIELD_DESC"
			label="JGLOBAL_FILTER_FIELD_LABEL"
			>
				<option value="1">JSHOW</option>
				<option value="hide">JHIDE</option>
		</field>
```
same issue in other core components as com_contact and com_content.
Changing the value in the xml would not be enough, i.e. we would need to change quite a few view files to not use anymore a code similar to
`<?php if ($this->params->get('filter_field') != 'hide') : ?>`
To be B/C we would have to change this to something like
`<?php if ($this->params->get('filter_field') != 'hide' || $this->params->get('filter_field') != '0') : ?>`

**Comment by alikon** [comment]
may i have some test on #8014
@infograf768 hope is B/C

**Comment by infograf768** [comment]
I think that all components should be corrected too, not only newsfeeds

**Comment by alikon** [comment]
i'll give it a look ...

**Comment by zero-24** [comment]
Closing as we have serveral pulls ;) Thanks.
