### ISSUE TITLE
Module not shown in the desired position.

### ISSUE THREAD

**Issue by adriannx** [joomla/joomla-cms#8027]
I have a problem with the positions of the modules, especially the sidebar position.
I chose the sidebar position for a module to be displayed throughout the site. Upon entering the menus or categories of items, there are areas shown as it should, but there are also areas where it is not shown in your chosen position, shown in the footer or bottom position, what happens?

Could someone please help me, I think it's a problem of my joomla since tried several templates and all are equal.

Image:

![8885](https://cloud.githubusercontent.com/assets/5619504/10326648/4a3777b4-6c63-11e5-804b-e30b2dc7ea36.PNG)

As it should be displayed:

![886](https://cloud.githubusercontent.com/assets/5619504/10326652/606c12a6-6c63-11e5-85ec-d91a4b3af31a.PNG)

Help please!

Regards!

**Comment by justinherrin** [comment]
Based on the first image you posted, it looks like something is expanding too wide causing the columns to break and create two rows instead of just one. There are a lot of areas that could cause this... settings in the template, settings of the modules you have assigned to the sidebar, something in your main content column that is "too wide", etc.

This might be a better forum question rather than an official bug/feature request report: http://forum.joomla.org/ have you posted for assistance over there yet?

**Comment by adriannx** [comment]
Hello justinherrin, thanks for reply.

I posted on the official joomla forum, but unfortunately not receive a response. 
As for the joomla template, I used various templates and the same thing happens.

Regards!

**Comment by N6REJ** [comment]
definetly not a core issue.. if you want you can contact me directly and 
I'll see if I can figure it out pretty quickly.  99% its either the 
template, or the extension layout.
Bear

**Comment by adriannx** [comment]
Yeah i have solved this inssue, Is a bug on com_content.

Regards!

**Comment by zero-24** [comment]
If it is a com_content issue we are happy to fix it so it don't get removed on the next update for you. Therfor you Need to tell us your fix or send it as pull request. Thanks

**Comment by adriannx** [comment]
When publishing an article with pictures, the box content is not respected, which is why the module was going elsewhere.
To be honest I did not find solution, simply stop using the Joomla Article Manager has a default. I' using a extension called easyblog. With EasyBlog I have no problem.

Regards!
