### ISSUE TITLE
Popular Tags module does not honor Tag List menu item urls

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-cms#8084]
#### Steps to reproduce the issue
Add some tags to your articles, enable the Popular Tags module. Now create a menu item and choose Tags>List of all Tags.
#### Expected result
Clicking on a tag from the Popular Tags module should lead to the same url you get by clicking on a tag in the Tags List menu item page.

#### Actual result
Clicking on tags in the page created by the menu item gives you urls like this:
domainname.com/tags/id-tagname

Clicking on tags in the Popular Tags module gives you urls like this:
domainname.com/component/tags/tag/id-tagname

This happens even when the Tags List menu item exists.

As a result of this, Modules connected to the Tags List menu item DO NOT APPEAR when clicking a tag in the Popular Tags module, you get a page with no modules on it at all.

Update (after more testing):
The correct behavior works in only one case: If you're on the Tags List page that's linked from a menu item, and the Popular Tags module is visible on that page, then the urls in the Popular Tags module are correct and work like this /tags/id-tagname

But if you're on any OTHER page of the site and you click on a link in the Popular Tags module, you still get /component/tags/tag/id-tagname.

#### System information (as much as possible)
Tested in my site, as well as a brand new 3.4.4 install using the Blog sample content.

#### Additional comments
This can cause lots of issues with new users who are already trying to understand how aliases and modules work, and of course it can give google two sets of tag pages.

**Comment by brianpeat** [comment]
Crap, it looks like this might be a template issue. I tested it in a stock install and thought for sure it was broken, now it looks like it's working. I'm going to do one more test and then I may cancel this one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8084">issues.joomla.org/joomla-cms/8084</a>.</sub>

**Comment by brianpeat** [comment]
Okay, I've tested again.

It works in only one case: If you're on the Tags List page that's linked from a menu item, and the Popular Tags module is visible on that page, then the urls in the Popular Tags module are correct and work like this /tags/id-tagname

But if you're on any OTHER page of the site and you click on a link in the Popular Tags module, you still get /component/tags/tag/id-tagname.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8084">issues.joomla.org/joomla-cms/8084</a>.</sub>

**Comment by brianteeman** [comment]
I know this is odd but this is the expected behaviour as Tags doesnt work the same as other components and in this case joomla is using the best match itemid for the content item and not the tags component<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8084">issues.joomla.org/joomla-cms/8084</a>.</sub>

**Comment by brianpeat** [comment]
So...instead of fixing it and making it better, we leave it so it generates 2 sets of urls, forcing people to use things like Advanced Module manager and/or htaccess forwards to fix the issue.

I thought the goal here was to make Joomla better, not leave things half broken. To me the tags system feels tacked on and not all that useful without a lot of extra work. Why not work to making it even more integrated and useful?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8084">issues.joomla.org/joomla-cms/8084</a>.</sub>

**Comment by brianteeman** [comment]
You cannot fix something that is not broken. It is working the way it is
supposed to work which unfortunately is not the way you want it to work.

**Comment by brianpeat** [comment]
I guess the problem I have is, some things really don't make sense but when I suggest something, the response is, it's supposed to work that way. The problem with that is, we'll never make anything better if we think that way. The way it is now, if someone creates a menu item for the tags, the module generates a second set of urls for the same exact content. It really shouldn't do that, it's bad practice. I'm suggesting we fix that instead of leaving it the way it is. Why can't we seek to make the darn thing BETTER? that's all I'm asking.

**Comment by brianteeman** [comment]
If someone wants to completely rewrite the tags system AND make it 100%
backwards compatible then it will be more than welcome.

**Comment by mbabker** [comment]
There's a lot of bad history with tags and it's a sore subject for many.  Long and short, there are a lot of sub-par things with it and short of a total rewrite you're not going to get most of them fixed.

And it's not just a tags issue, but rather Joomla routing in general.  In theory this will work right on a com_tags based page, but not on another component.  That's why we have all these route helper classes sadly; to generate routes cross-component you have to use those (I hit it too with components we have on the dev site, https://github.com/joomla-projects/com_code/issues/19).

Maybe the new router addresses some of it, but what you're seeing is really "expected behavior", for better or worse.
