### ISSUE TITLE
GMail authentication requires setting "Allow access for less secure apps" to work

### ISSUE THREAD

**Issue by jdiamondNYDI** [joomla/joomla-cms#8158]
#### Steps to reproduce the issue

When GMail Authentication plugin is enabled, users in our Google Apps domain must set "Allow access for less secure apps" in order for the plugin to work for their logins.

#### Expected result

It should not be necessary to set "Allow access for less secure apps" in order for the GMail Authentication plugin to work.

#### Actual result

Users must set "Allow access for less secure apps" (https://www.google.com/settings/security/lesssecureapps) in order for the plugin to work for their logins.

#### System information (as much as possible)

PHP Built On	Linux prime.noobisprime.com 2.6.32-042stab108.2 #1 SMP Tue May 12 18:07:50 MSK 2015 x86_64
Database Version	5.5.45-cll
Database Collation	latin1_swedish_ci
PHP Version	5.4.21
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
		
Authentication - Gmail Version: 3.0.0

**Comment by vdespa** [comment]
This is not really a bug. The Gmail Authentication plugin is quite old in the Joomla code base and the authentication method used is old and outdated as well.

Since July 2014 Google is considering this authentication method as less secure and is disabled by default. 

The proper solution would be to look into more current authentication methods for Gmail / Google Accounts and to replace the plugin.

Hope this makes sense.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8158">issues.joomla.org/joomla-cms/8158</a>.</sub>

**Comment by vdespa** [comment]
Set to "closed" on behalf of @vdespa by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8158">issues.joomla.org/joomla-cms/8158</a>
