### ISSUE TITLE
PHP7 Incompatibility with in registry/json.php with strings

### ISSUE THREAD

**Issue by lutel** [joomla/joomla-cms#8194]
I know this issue has been raised and fixed by @wilsonge in 3.5 tree, i couldn't post on that topic as it was closed. @wilsonge - could you backport this fix for PHP7 to 3.4 tree as well?

**Comment by zero-24** [comment]
The last plane i know is that the next update is to 3.5.0 (expected a sec update) so there is no backport needed i guess ;)

**Comment by lutel** [comment]
Ok thank you :)

**Comment by wilsonge** [comment]
As it was technically a b/c break (because people could theoretically be type hinting `JString` against the framework `String` class) we chose to put it in 3.5 (as they are all static methods the chances are so so low but we couldn't take the risk). Either way as @zero-24 says because of the security release that we were forced to do we've had to abandon plans for another 3.4 release because of the published dates for 3.5 coming up (first beta 4th November)
