### ISSUE TITLE
Magic Hash Vulnerability

### ISSUE THREAD

**Issue by paragonie-scott** [joomla/joomla-cms#8326]
https://github.com/joomla/joomla-cms/blob/ec8a72f4cd0519786b9001dd3dd593131e7d32d2/libraries/joomla/crypt/password/simple.php#L151

You're using the non-strict equality operator to compare hashes...

http://blog.astrumfutura.com/2015/05/phps-magic-hash-vulnerability-or-beware-of-type-juggling/

cc @padraic @ircmaxell @enygma

**Comment by paragonie-scott** [comment]
Another suggestion: use a timing safe comparison.

(Also: [make this use `hash_equals()`](https://github.com/joomla/joomla-cms/blob/master/libraries/joomla/crypt/crypt.php#L256-L288) in PHP 5.6+.)

**Comment by mbabker** [comment]
There was a pull request for that at one point (https://github.com/joomla/joomla-cms/pull/4206 then https://github.com/joomla/joomla-cms/pull/7754) but in pretty typical manner around these parts it was over the head of most folks testing/reviewing patches and ended up abandoned/closed.

**Comment by beat** [comment]
:+1: From code review standpoint, the referred commit as well as follow-up commits seem to address this issue properly.

Btw, Joomla upgrades the stored password hash at each login if needed. Thus, this issue can only occur on a very old account that has not been logged in for a very long time, or on a very old unmaintained Joomla installation (one of these has to be older than around 3 years so that the password hasn't been upgraded at a login with a recent Joomla version yet for that compare case to occur).
