### ISSUE TITLE
Database date issue

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#8332]
Ref : Joomla! 3.5.0 Beta 1 (11/08 dld)
#### Steps to reproduce the issue
Clean install of this version

#### Expected result
As always, checking the DB (Database->Fix), getting this :![screen shot 2015-11-08 at 05 12 39](https://issues.joomla.org/uploads/1/f79baefe6b0f3d97e55b270a06abe80a.jpg)
Fix OK.

#### But ...
Rereading carefully the message, I noticed this, that doesn't fit :
(last line) from file 3.5.0-2015-07-01.sql

I checked the files : 
culprit here ->  /administrator/components/com_installer/models/database.php
line 273

**Comment by zero-24** [comment]
Can You try https://github.com/joomla/joomla-cms/pull/8268

**Comment by ghazal** [comment]
Looks like it fixed the "fix".
But I am still wondering about the call to 3.5.0-2015-07-01.sql in database.php.
l will check further and get back to you if I encounter other pb.

**Comment by brianteeman** [comment]
As this has been fixed by #8268 and there has been no further comment about other problems I am closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8332">issues.joomla.org/joomla-cms/8332</a>.</sub>
