### ISSUE TITLE
Add the ability to use a custom.css with Protostar. (#4211)

### ISSUE THREAD

**Issue by haya1300** [joomla/joomla-cms#8357]
#### Steps to reproduce the issue

Make a new site with custom.css made changes in de Protostar template
Make in the index.php the following changes: 

// Add Stylesheets
$doc->addStyleSheet('templates/'.$this->template.'/css/template.css');

Just below these two lines, add the following:

$doc->addStyleSheet('templates/'.$this->template.'/css/custom.css');

Make in de css folder a new file named: custom.css and put there the new css declarations
This is the way I have learned to make template overrides

#### Actual result

Then after upgrading to 3.5 all change are gone.

#### System information (as much as possible)

Database versie 	5.6.21 
PHP versie 	5.6.3
Webserver 	Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
WebServer naar PHP interface 	apache2handler
Joomla! versie 	Joomla! 3.5.0-beta Beta [ Ember ] 06-November-2015 24:00 GMT
Joomla! Platform versie 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

#### Additional comments

To fix the problem go to the index.php file from the template and change the user.css to custom.css (twice)
So I prefer to use custom.css instead user.css

**Comment by brianteeman** [comment]
It is expected behaviour that any changes made to a core file will be lost
when an upgrade is performed.

On 9 November 2015 at 11:34, haya1300 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Make a new site with custom.css made changes in de Protostar template
> Make in the index.php the following changes:
>
> // Add Stylesheets
> $doc->addStyleSheet('templates/'.$this->template.'/css/template.css');
>
> Just below these two lines, add the following:
>
> $doc->addStyleSheet('templates/'.$this->template.'/css/custom.css');
>
> Make in de css folder a new file named: custom.css and put there the new
> css declarations
> This is the way I have learned to make template overrides
> Actual result
>
> Then after upgrading to 3.5 all change are gone.
> System information (as much as possible)
>
> Database versie 5.6.21
> PHP versie 5.6.3
> Webserver Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
> WebServer naar PHP interface apache2handler
> Joomla! versie Joomla! 3.5.0-beta Beta [ Ember ] 06-November-2015 24:00 GMT
> Joomla! Platform versie Joomla Platform 13.1.0 Stable [ Curiosity ]
> 24-Apr-2013 00:00 GMT
> Additional comments
>
> To fix the problem go to the index.php file from the template and change
> the user.css to custom.css (twice)
> So I prefer to use custom.css instead user.css
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8357>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
@haya1300 

We have a user.css here: https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/index.php#L48-L54 that dues the same as custom.css ;) We need to use the user.css and can't use the custom.css as there are places we use custom.css for changes to the TinyMCE as pointed out by @infograf768 

Feel free to copy your template (there is a easy way in the Backend Template manger) and change everything you want. This copy is also not affected by any future update. (so a update will never change anything you changed)

Docu can be found here: https://docs.joomla.org/J3.x:Modifying_a_Joomla!_Template#Copy_the_Template

Thanks for understanding I'm going to close this issue now as `Expected Behavior` :smile:
