### ISSUE TITLE
EditorsTinyMCE  popup/modal styles not properly styled

### ISSUE THREAD

**Issue by shamsbd71** [joomla/joomla-cms#8427]
#### Steps to reproduce the issue
Install the new Joomla 3.5 beta with sample data installed. after login to admin navigate to Article manager and edit any article. now you have new TinyMCE editor in article description. it looks good but if you click on 
1. **Module**
2. **Article**
3. **Image**

the un-styled view comes here.

#### Expected result
1. popup can be look like the as the bootstrap modal used by joomla in all other places
or
2. at least it should contain the same margin/padding in all the places used for consistency

#### Actual result
the popup opens is missing proper distance and styles in padding or margin.

#### System information (as much as possible)
Windows10 OS and Wamp with php 5.5.
![screen shot 2015-11-14 at 00 56 43](https://issues.joomla.org/uploads/1/78d615aba476b1e6fddc0d58f46b1ce6.png)

**Comment by roland-d** [comment]
@shamsbd71 Thank you for your contribution. I am closing this issue as we are already working on it in #8366 but as it turns out, it's not that easy to fix :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8427">issues.joomla.org/joomla-cms/8427</a>.</sub>
