### ISSUE TITLE
Error when installing an extensin - JLIB_FILESYSTEM_ERROR_WARNFS_ERR03 - False positive?

### ISSUE THREAD

**Issue by gilles008** [joomla/joomla-cms#8453]
#### Steps to reproduce the issue
Using J! 3.4.5, use extension manager to install the plugin [BT Social Sharing Plugin](http://bowthemes.com/joomla-extensions/bt-social-share-plugin.html "http://bowthemes.com/joomla-extensions/bt-social-share-plugin.html").

#### Expected result
Successful installation

#### Actual result
Error: JLIB_FILESYSTEM_ERROR_WARNFS_ERR03

#### System information (as much as possible)
If  I upload the unzipped install files to the temp folder and install from this repository, the installation is successful.

**Comment by brianteeman** [comment]
For those that dont know what the ERR03 message is 
JLIB_FILESYSTEM_ERROR_WARNFS_ERR03="Warning: File %s not uploaded for security reasons!"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8453">issues.joomla.org/joomla-cms/8453</a>.</sub>

**Comment by bertmert** [comment]
Tested with 3.5.0 beta staging 2015-11-13, PHP 5.6, and cannot confirm

**Comment by gilles008** [comment]
Thanks. As I mentioned, I was on the current Joomla stable release 3.4.5.
In such a case, should we simply wait for J! 3.5?

**Comment by berlanda** [comment]
I had the same problem when I tried to upload a pdf file using the media manager. I send the file and I did not receive any warning, and the file simply do not upload. I noticed that the error depends on the pdf file uploaded, and it occurs due to the method isSafeFile() (class JFilterInput - libraries/joomla/filter/input.php), called within the method get() of the class JInputFiles (libraries/joomla/input/files.php, line 83).

The task upload(), from the media manager backend controller file.php, calls the method JInputFiles::get() through an object on the line 45 ($this->input->files->get).

Why it occurs? It occurs due to the forbidden extensions scan inside file contents, within the JFilterInput::isSafeFile(), from the line 459. In my case, when I saw the variable $data output (declared on line 467) from my pdf file, I found the string ".py" inside the pdf file code, one of the extensions verified by default, inside file contents. Important: the string was not inside the pdf file text.

I understood the importance of the method JFilterInput::isSafeFile(), but the search of simple extensions inside file content, being confused with the pdf file code, can cause problems that most users will not identify the reason.

I posted here because I think that this issue is related. I will open other issue, if you don't mind.

**Comment by bertmert** [comment]
Reason is a correct bugfix in Joomla 3.4.5. Before this fix some checks while uploading were ignored.
This method should be called with correct parameters by the uploading components.
```
JFile::upload($src, $dest, $use_streams = false, $allow_unsafe = false, $safeFileOptions = array())
```
e.g. JCE editor had a similiar issue while uploading addon packages with language files in it named like *en-GB.**pl**g_xyz_*. They were identified as maybe PERL files. Found inside a ZIP file before(!) unpacking it. After setting $allow_unsafe to true the issue was fixed for JCE.

**Comment by gilles008** [comment]
Thanks Bermert. Pargon my ignorance, I'm new to Github.

I'm not understanding. Is a bug confirmed? Is there a fix?

**Comment by bertmert** [comment]
@gilles008 
I just wanted to post additional informations to post of @berlanda  because me and a friend made some investigations then! No resaon for you to say pardon!

> I'm not understanding. Is a bug confirmed? Is there a fix?

I personally don't want to decide if it's a ""bug"" and if core components (and others) should use method upload() less secure by passing other parameters. I think sometimes there are confusing false positives.

>  As I mentioned, I was on the current Joomla stable release 3.4.5 In such a case, should we simply wait for J! 3.5?

The best way to decide this would be to install 3.5.0 beta on same server and identical settings, PHP and so on as a subdomain and test it. I don't have a J3.4.5 at the moment where I coud test it.

**Comment by brianteeman** [comment]
Hi

I am closing this issue as it is over a year old and unfortunately with this type of thing there can always be false positives. However we have had no other reports so its obviously not happening often.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8453">issues.joomla.org/tracker/joomla-cms/8453</a>.</sub>
