### ISSUE TITLE
ACL - Ajaxifying should update all assets

### ISSUE THREAD

**Issue by Kubik-Rubik** [joomla/joomla-cms#8616]
#### Steps to reproduce the issue

Change ACL settings in the global configuration, only changed asset is updated but not all other. All changes are only visible if your refresh the page.

#### Expected result

All assets are displayed properly.

#### Actual result

Only changed asset is updated.

#### System information (as much as possible)

Joomla! 3.5 Beta 1

#### Additional comments

PR that introduced "Ajaxifying" - https://issues.joomla.org/tracker/joomla-cms/8132

**Comment by alikon** [comment]
i can confirm the issue on the current staging
you need to save before to see all the info updated

**Comment by brianteeman** [comment]
@Kubik-Rubik @roland-d shall we close it then?

**Comment by roland-d** [comment]
Closing as this is expected behavior. We have a message informing user a page refresh is needed to see all updated information.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8616">issues.joomla.org/joomla-cms/8616</a>.</sub>
