### ISSUE TITLE
3.5.0 Beta. New module after administrator selection shows frontend modules

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8621]
I' ve installed staging of today.

After installation I didn't open any list views (components).
Just configuration. 
Installed patch tester, and a small backend module. 
Afterwards I opened modules manager. 
Selected "Administrator" in Client filter field: 
Page reload and Administrator modules are displayed.
Clicked "New".
The page for selecting modules shows frontend modules.
Clicked Cancel. Filter still shows "Administrator".

Tried a lot (changing filters, client, ordering) but always frontend modules after New.
Firefox and Chrome.

**Comment by Bakual** [comment]
Confirmed. And it's likely related to the Search Tools implementation

**Comment by bertmert** [comment]
Just found out that when I change

```
$clientId = $app->getUserState('com_modules.modules.filter.client_id', 0);
```

to

```
$clientId = $app->getUserState('com_modules.modules.filter.client_id', 1);
```

in models/select.php::populateState(...)

I only see backend modules.

**Comment by Bakual** [comment]
I think it's related to the change in https://github.com/joomla/joomla-cms/pull/6958.
There, the userstate name of the client_id changed from `$this->context . '.filter.client_id'` to `$this->context . '.client_id'`

Changing the line you mentioned to `$clientId = $app->getUserState('com_modules.modules.client_id', 1);` seems to fix it.

**Comment by sovainfo** [comment]
From code reviiew perspective don't consider that the riight fix.

As @Bakual mentioned there is a change in name of variable. So, instead of changing the default value when variable not found, make sure you look for the correct varable!

That would make sure the setting is respected (as intended) instead of ignoring it and only show an arbitrary choice (frontend or backend, depending on 0 or 1). Obviously, when the filter is not set showing frontend is fine with me. Don't see a reason to change that!

**Comment by bertmert** [comment]
Reason for removing .filter and filter_ was as I remember that client_id is not part of
<fields name="filter"
in filter_modules.xml. (see menu manger, too).

Will there be conflicts in the backround when just adding *.filter*  in model codes where it's missing?

**Comment by bertmert** [comment]
See PR https://github.com/joomla/joomla-cms/pull/8626.
The simple way (that I understand).
