### ISSUE TITLE
#__updates table dropping

### ISSUE THREAD

**Issue by jgrebele** [joomla/joomla-cms#8644]
Folks,

I'm running into a strange problem.  Occasionally, my Joomla 3.4.5 instance becomes non-responsive.  When the server finally comes back, the #__updates table is there without any columns.  I drop the table and then attempt to rebuild it using the SQL Create Table that is in the Joomla 3.4.5 core files.  Specifically, installation/joomla.sql.  I take the SQL code for the #__updates table out of joomla.sql and attempt to run it through MySQL Workbench and phpmyadmin.  Neither works and returns a message, "Cannot create table (errno: -1)".  If I remove the parameters ENGINE=... from the SQL code, the table creates fine.

Has anyone else encountered this issue?  Any thoughts on why this may be happening and how to prevent it in the future?

Thanks,
Joe
IT Manager
NPHIC

**Comment by sovainfo** [comment]
This is the wrong place for reporting your issue. It should be done on forum.joomla.org. When doing so do mention proper detai­ls about your infrastructure. Your version of MySQL server is of interest ( not the client library) and the support of ENGINES.

You might even try MySQL boards, it doesn't seem to be Joomla related.
Feel free to report here again when it turns out something to be improved in Joomla. Unlikely, but not impossible.
