### ISSUE TITLE
LDAP (ActiveDirectory) Logins Generating Notice In PHP Error Log "Uninitialized string offset: 0 in \joomla\user\helper.php on line 341"

### ISSUE THREAD

**Issue by garrett02** [joomla/joomla-cms#8685]
#### Steps to reproduce the issue
Login with Active Directory LDAP Authentication to joomla site.

#### Expected result
Login Successful

#### Actual result
Login Successful, however PHP Error Generated as follows for each successful/unsuccessful login attempt:
"Uninitialized string offset: 0 in ............\libraries\joomla\user\helper.php on line 341"

#### System information (as much as possible)
PHP 5.6 w/ IIS 8.5 on Win 2012 r2, Active Directory, Joomla 3.4.5

#### Additional comments
At the request of the poster who helped me solve this, I am posting as an issue. By changing the order of authentication plugins such that LDAP was placed before Joomla!, I was able to mitigate this error from occurring.
http://forum.joomla.org/viewtopic.php?f=708&t=902366

**Comment by anabarcellos** [comment]
@garrett02 Same issue here. 
I use the same LDAP configuration in dozens of sites and just one of them had this problem. It was in Joomla 2.5.28. Updated to 3.5.1 but the issue was still there. I solved it changing the order of authentication plugins as suggested in the forum post that you shared (thank you). 

SLES11 - PHP 5.3     <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8685">issues.joomla.org/joomla-cms/8685</a>.</sub>

**Comment by brianteeman** [comment]
Removed IIS tag as second post shows it is not server related<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8685">issues.joomla.org/joomla-cms/8685</a>.</sub>

**Comment by rvbgnu** [comment]
Hi @garrett02 is this issue still relevant? Or is the mention of the solution in the forum enough?
@nibra

**Comment by franz-wohlkoenig** [comment]
set Status on "Information Required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8685">issues.joomla.org/tracker/joomla-cms/8685</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 23th July 2017.

**Comment by garrett02** [comment]
I think the mention of solution in the forum is sufficient for most.

**Comment by franz-wohlkoenig** [comment]
thanks for Info, @garrett02, can you please close this Issue?
