### ISSUE TITLE
Possible mistake in JApplicationCms class

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#8703]
The **initialiseApp** method of  **JApplicationCms** class has this command (https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/cms.php#L630)

```php
$this->config = JFactory::getConfig();
```

I think it is a mistake because it will reset all the config data which is initialized before in **JApplicationWeb** using **$this->set** method (JApplicationCms extends JApplicationWeb). For example, with the above command, the entire code in this method is useless https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/web.php#L1103-L1191

I tried to remove the mentioned line of code and my local site still works well. Plus, we can now accessing to configuration data intialized in **JApplicationWeb** with these sample code:

```php
$app = JFactory::getApplication();

echo $app->get('execution.datetime');
echo $app->get('uri.request');
echo $app->get('uri.base.full');
```
Before these commands return empty.

**Comment by mbabker** [comment]
Busted as it is, that's intentional.  There was an attempt to merge both the local config and the config that gets generated when instantiating JApplicationWeb instances but that broke stuff too.  So the preference was to keep only the local config.  See https://github.com/joomla/joomla-cms/commit/9445d5e9eaccce6bd9f932c7f80e9e62aa4d2af7 and relevant links/issues.
