### ISSUE TITLE
joomla+postgresql installation: error with uppercase(s) in table names

### ISSUE THREAD

**Issue by databeille** [joomla/joomla-cms#8713]
Good day,

After many successful joomla+postgresql installations, I ran today with a "bug".

When table names have uppercases, in prefix for example, installation script fails to succeed.

It seems the problem could be fixed by double-quoting all table names.

Then instead of<pre>SELECT * FROM #__extensions WHERE extension_id = '1';</pre>
SQL should be <pre>SELECT * FROM "#__extensions" WHERE extension_id = '1';</pre>

By the way, sequences are also affected.

To fix this, all queries should use <strong>$db->quoteName()</strong> to write proper SQL.
<pre>$query->clear()
->select('*')
->from($db->quoteName('#__extensions'));
$db->setQuery($query);</pre>

A workaround could be to force lowercases on prefix.

Joomla 3.4.6 + CentOS 6.7 x68_64 + PSQL 3.9.10 + PHP 5.4.45

**Comment by brianteeman** [comment]
I ca confirm that the current staging ill not install if a database prefix is selected that is uppercase<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8713">issues.joomla.org/joomla-cms/8713</a>.</sub>

**Comment by alikon** [comment]
yes i confirm too, but considering the amount of work needed to let UPPERCASE table prefix work,  i will be in favour  to force lower case  in the table prefix  if postgresql was selected, any comments ?

**Comment by brianteeman** [comment]
Due to the low volume of pgsql users and the limited possibility of this issue occurring I would go for the quick option<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8713">issues.joomla.org/joomla-cms/8713</a>.</sub>

**Comment by sovainfo** [comment]
Agree with @brianteeman, so this issue can be closed!
There are not that many users implementing on pgsql, even fewer making the mistake to use uppercase in the prefix. So, just document it. Nothing to be done in the software!

When you want to change something in the software suggest to make sure the ->from method puts the quotes there when they are missing instead of only using lowercase prefix.

Obviously the bad code using ->quoteName or ->qn can be removed from any ->from after that.
Maybe those functions can even be deprecated or made internal. Would consider that a far better OOD implementation, removing yet another rookie mistake!

**Comment by brianteeman** [comment]
Disagree it can be closed if it can be fixed.

**Comment by mbabker** [comment]
Care to explain how it's a mistake to use uppercase prefixes?  From what I've read, it's acceptable on all database engines to use uppercase characters in the names of identifiers, but in the case of PostgreSQL since it defaults to treating identifiers as all lowercase values it requires quoting to use uppercase characters.

**Comment by sovainfo** [comment]
The fact you can do it, doesn't make it the right decision. Regardless of how you think about case sensitivity it is probably reason no 1 for problems. Sticking with lowercase saves you from a lot of problems in a case sensitive environment. Expect most implementations of Joomla on pgsql to be on the unix platform by people with above average IT knowledge. They probably know to avoid these situations. Probably the reason this reported only now.

Agree again with @brianteeman, it shouldn't be closed if you want to do the right thing. Quoting table names and attribute names should be enforced and something done by the appropriate driver. And not be left to an extension developer as it is done currently. 

Care to explain the poor current implementation?

**Comment by mbabker** [comment]
If I wrote the current implementation I might be able to explain it; alas, I'm just someone using it with all its nuisances :wink: 

I agree folks SHOULD be using lowercase identifiers (table and column names), but it's not a strict requirement in any database engine so I'd disagree with Joomla making it one in its DBAL.  Could it be handled better?  Absolutely.  But frankly, in its current form I wouldn't want to trust the API to do any form of query manipulation beyond assembling the data it's given into an executable SQL query string.  Even something like Doctrine doesn't automatically quote everything, but it does have ways to enforce quoting in different scenarios and I think handles some quoting of reserved platform keywords no matter what.

**Comment by alikon** [comment]
i've proposed my quick&dirty workaround #8856
