### ISSUE TITLE
3.4.7 - not able to add menu item after update from 3.4.5

### ISSUE THREAD

**Issue by XtremXpert** [joomla/joomla-cms#8769]
to recreate I have build a docker

docker run --name doc --link xtremsql:db -d xtremxpert/docker-joomla:debian

Then complete installation.  Go on menu manager, add an item

Then update to 3.4.7 and try again.  The pop up to select type of item open but dont return value when closed

**Comment by brianteeman** [comment]
Logout after updating. When you log back in it will be fine

**Comment by brianteeman** [comment]
@XtremXpert can you confirm if this is now resolved by logging in and out<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8769">issues.joomla.org/joomla-cms/8769</a>.</sub>

**Comment by PhilETaylor** [comment]
A 3.4.8 Release Candidate Package (https://github.com/joomla/joomla-cms/releases/tag/3.4.8-rc) has been released for testing. Some of these issues are not reliable - so just give it a try and see if you come across any issues :)

**Comment by 810** [comment]
on the rc, I don't have this issue.

**Comment by PhilETaylor** [comment]
I have run this docker image - could not find a mysql server installed in it! Looking at the docker configuration file https://hub.docker.com/r/xtremxpert/docker-joomla/~/dockerfile/ I see you are downloading a stock Joomla 3.4.5 and then you say you are upgrading it.

Therefore the docker complexity to this GH Issue is overhead - we are already aware of the issues in 3.4.7 and those are reported already to be fixed in 3.4.8 but I have taken the time to review your docker, but I don't see any advantage to spending more time installing mysql to the container in order to test your reported bug as I believe it has already been addressed in Joomla 3.4.8.

I see @Kubik-Rubik has already closed the issue anyway now - so please test Joomla 3.4.8 RC and report back if your issues are not resolved.
