### ISSUE TITLE
[bug] emptying trash doesn't delete ucm_content

### ISSUE THREAD

**Issue by sandrodz** [joomla/joomla-cms#8770]
To reproduce:
1. create article with tags (webadmin)
2. confirm its in ucm_content table (mysql)
3. trash article in article manager (webadmin)
4. confirm ucm_content state is -2 (mysql)
5. go back to article manager and clear trash (webadmin)
6. check back ucm_content to confirm that row was not removed, its left there hanging -2 (mysql)

I've used article model to delete 100,000 articles from DB. Now I've 27,000 rows in ucm_content stuck without original article. What do I do?

**Comment by brianteeman** [comment]
Tested with current staging as per the instructions and I can not replicate this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8770">issues.joomla.org/joomla-cms/8770</a>.</sub>

**Comment by esedic** [comment]
I've tested this because I had problems my self with deleted tags leaving records in assets & UCM tables.

This is how I was testing:
1. Create an article and create a tag inside article form. Save article.
2. New database records are visible in tables #_assets, #_contentitem_tag_map, #_tags, #_ucm_base and #_ucm_content.
3a. Remove tags from article, records in database are being removed properly.
3b. Delete tags from com_tags component view. Empty trash. Database records are not removed from tables #_assets, #_ucm_base and #_ucm_content.

If I delete tags and empty trash from com_tags component view, I would expect all database relations to previously tagged articles would be removed. 

I have also reproduced issue @sandrodz mentioned.
These are my observations:
1. When you create an article and assign a tag to it, you get two records in #_assets table. One record  has `name` = #__ucm_content.100, other record has `name` = com_content.article.100 (100 is article id).
If you delete article and empty trash, record with #__ucm_content.100 is not removed.
2. Records from #_contentitem_tag_map table are properly removed
3. Records from #_ucm_base and #_ucm_content tables are not removed.

I'm in the process of upgrading old Joomla 1.5 site with 200k+ articles and 4000k+ tags (discontinued 3rd party extension) and I'm on the edge of madness, because it's so complicated to import tags manually. Currently UCM is IMHO half baked solution. It is my first time to use com_tags in this scope and it seemed like a great native solution. Even 3rd party tagging extensions seemed far weaker in terms of usability and integration with CMS.

**Comment by brianteeman** [comment]
>  Currently UCM is IMHO half baked solution.

Pretty sure no one will really disagree with you on that

On 17 February 2016 at 14:13, Elvis Sedic <notifications@github.com> wrote:

> I've tested this because I had problems my self with deleted tags leaving
> records in assets & UCM tables.
>
> This is how I was testing:
> 1. Create an article and create a tag inside article form. Save article.
> 2. New database records are visible in tables #_assets,
> #_contentitem_tag_map, #_tags, #_ucm_base and #_ucm_content.
> 3a. Remove tags from article, records in database are being removed
> properly.
> 3b. Delete tags from com_tags component view. Empty trash. Database
> records are not removed from tables #_assets, #_ucm_base and #_ucm_content.
>
> If I delete tags and empty trash from com_tags component view, I would
> expect all database relations to previously tagged articles would be
> removed.
>
> I have also reproduced issue @sandrodz <https://github.com/sandrodz>
> mentioned.
> These are my observations:
> 1. When you create an article and assign a tag to it, you get two records
> in #_assets table. One record has name = #__ucm_content.100, other record
> has name = com_content.article.100 (100 is article id).
> If you delete article and empty trash, record with #__ucm_content.100 is
> not removed.
> 2. Records from #_contentitem_tag_map table are properly removed
> 3. Records from #_ucm_base and #_ucm_content tables are not removed.
>
> I'm in the process of upgrading old Joomla 1.5 site with 200k+ articles
> and 4000k+ tags (discontinued 3rd party extension) and I'm on the edge of
> madness, because it's so complicated to import tags manually. Currently UCM
> is IMHO half baked solution. It is my first time to use com_tags in this
> scope and it seemed like a great native solution. Even 3rd party tagging
> extensions seemed far weaker in terms of usability and integration with CMS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8770#issuecomment-185222297>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by roland-d** [comment]
Pull requests #13583 and #13584 to solve these issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8770">issues.joomla.org/tracker/joomla-cms/8770</a>.</sub>
