### ISSUE TITLE
Update from Joomla 3.2.0 to 3.4.8 using Joomla Update Component not able to download package.

### ISSUE THREAD

**Issue by sglomski** [joomla/joomla-cms#8785]
#### Steps to reproduce the issue

1. Access Joommla Administrator
2. Navigate to Joomla Update Component
3. Select "Write the files directly"
4. Click Install the Update.

#### Expected result

The update successfully processes.

#### Actual result

The screen briefly displays: "Downloading update file.  Please wait."
Then screen updates to display: "Updating your Joomla! files. Please wait ..." with a spinning icon.  This displays indefinitely.

#### System information (as much as possible)

Apache Version	2.2.26
PHP Version	5.3.28
MySQL Version	5.6.27
Operating System	linux

**Comment by sovainfo** [comment]
Suggest you take your infrastructure problem to forum.joomla.org. There they can help you to fix it.
In the unlikely case it turns out a bug in Joomla or Joomla can be improved to deal with circumstances like yours, 
you can return here and report those details.

Suggest to close this.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8785">issues.joomla.org/joomla-cms/8785</a>.</sub>
