### ISSUE TITLE
Syntax errors in file /com_admin/sql/updates/mysql/3.4.0-2014-09-16.sql

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-cms#8786]
IMHO file https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.4.0-2014-09-16.sql contains MySQL syntax errors :
is
````SQL
ALTER TABLE `#__redirect_links` ADD header smallint(3) NOT NULL DEFAULT 301;
ALTER TABLE `#__redirect_links` MODIFY new_url varchar(255);
````
should be
````sql
ALTER TABLE `#__redirect_links` ADD `header` smallint(3) NOT NULL DEFAULT 301;
ALTER TABLE `#__redirect_links` MODIFY `new_url` varchar(255);
````
related: https://github.com/joomla/joomla-cms/issues/6333

CC: @wilsonge

**Comment by wilsonge** [comment]
Sounds good to me - can you do a PR for this - see https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Else ping me again next week when I'll have time to do it myself (I'll try and remember but got a lot going on at the moment with holidays + family stuff)

**Comment by wojsmol** [comment]
PR https://github.com/joomla/joomla-cms/pull/8788

**Comment by ggppdk** [comment]
These will not yield a syntax error,
only 
- reserved words and 
- column names with special characters (e.g. space) or UTF encodings
are required to be quoted,

of course it is better to quote the column names

- furthermore i tested and it seems that the class JSchemaChangeitemMysql, can handle non-quoted column names

Real reason is:
that JSchemaChangeitemMysql cannot handle
```
... ADD `columnname` ...
```
please update your PR to make it like:
```
... ADD COLUMN `columnname`  ...
```

**Comment by wojsmol** [comment]
@ggppdk PR fixed https://github.com/joomla/joomla-cms/pull/8788

**Comment by Bakual** [comment]
Closing as we have a PR
