### ISSUE TITLE
Title links of articles are not clickable for public in blog view if the content is restricted to registered

### ISSUE THREAD

**Issue by hakanara** [joomla/joomla-cms#8790]
I followed all the steps of "Editing Restricting access to Articles individually" as stated here:
https://docs.joomla.org/Restricting_access_to_%22read_more%22

As a result, in the blog view, the article titles are not clickable although the opposite is selected in the menu settings. (Administrator -> Menu of the blogged category -> Options -> Linked titles -> Yes)

But when I login, the titles are clickable. I copy the link when I am logged in, I log out and paste the link to the browser, I access to the page where the first half of the text before "read me" is displayed. So actually the link works. So why can not I make it clickable from the menu settings?

Logically, if the link shows the first part of the restricted content (the part before read more) when pasted it into the browser, it should be clickable in the blog view. As far as I remember, it was clickable before.

(On top, I think because of these settings, when I use a sitemap component (like OSmap) the links are not shown on the sitemap.)

For the search engines to follow the first part of the content, I propose the links to be clickable on the blog layout if the opposite is not set in the menu settings.

**Comment by sovainfo** [comment]
Recall that to be a known bug, no solution provided.
Suggest to use globally instead of the menu item (individually).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8790">issues.joomla.org/joomla-cms/8790</a>.</sub>

**Comment by hakanara** [comment]
Thank you, can you elaborate your suggestion please? What does "use globally" mean?

**Comment by sovainfo** [comment]
No, the document you referred to mentions 1. individually and 2. global.
You mentioned you opted for 1 indivually.
2. global is at the component level.

**Comment by hakanara** [comment]
There is no change. The title links are still unclickable. I tried many different combinations. Does it work for you if you do it as the 2nd option?

**Comment by sovainfo** [comment]
Don't know, not using that functionality.

**Comment by creativeprogramming** [comment]
Check if making this change can solves issue: https://github.com/joomla/joomla-cms/compare/staging...creativeprogramming:patch-3

**Comment by hakanara** [comment]
Yes it worked @creativeprogramming Grazie mille. So are you going to add the new parameters now? Joomla team rocks :-)

**Comment by creativeprogramming** [comment]
@hakanara no, I'm a Joomla user like you, not Joomla team, i provided just some 'inspiration' to the team to locate where the issue is, and the 'TODO:' i wrote is part of this inspiration, let's hope someone in the team will take this, there are also other views to fix in the same way and i think adding a parameter is a good thing, anyway they may also simply remove the $params->get('access-view')' as it's unneeded for security as in the item view, like you stated, is instead used just to hide the 'fulltext' but not to prevent access to the URL, so having links to it should not be prevented

**Comment by hakanara** [comment]
Actually there is already a parameter for this (Show title with links or something like this) So if the article is blocked by access restrictions, maybe there would be no need for hiding the link of the article. Let the developers discuss it.

**Comment by hakanara** [comment]
@creativeprogramming You gave me an idea. I copied the modifed file to the html folder of the template and it works. Thank you. Hopefully, Joomla developers will respond to this :-)

**Comment by sovainfo** [comment]
Unfortunately that is not the way it works here. Without a PR with the suggested code change nothing is going to happen. You might be lucky and find someone that produces the PR. Doubt that very much because both solutions provided by @creativeprogramming are not of the quality to be applied to core.

Advice against using the modified code even as an template override. It is clear that you don't understand the meaning of the setting access-view. Removing that condition indeed gets you the linked title, only for more situations than you want. Obviously you need to restrict it to the situation at hand. Which is when you configured to show the teaser.

So, the condition would be:
if ($params->get('link_titles') && ($params->get('access-view') || $params->get('show_noauth', '0') == '1'))

**Comment by hakanara** [comment]
@sovainfo , thank you very much. Your recommendation also worked for me. I managed to solve the situation with the template override. I know that the developers should agree on a solution and the code should be added to the package with a PR. I don't want to create many discussions, but your recommendation in the last message could be implemented to the core, right?

**Comment by sovainfo** [comment]
Created #8827 
Please mention your test result using issues.joomla.org on #8827 

With thanks to @creativeprogramming for pointing to the troubled code.

Suggest to close this issue, as there is a PR.

**Comment by hakanara** [comment]
@sovainfo Thank you very much. Great team here. 

I have tested all the combinations (authorized links = yes/no, clickable links = yes/no, and acess rights = registered) and it worked as expected. So I close the issue now.
