### ISSUE TITLE
Categories for modules

### ISSUE THREAD

**Issue by calebelt** [joomla/joomla-cms#8806]
Please make a Categories for modules. As for the articles.

**Comment by creativeprogramming** [comment]
Can you better describe why you need that to help understand how this can help everybody?

**Comment by photodude** [comment]
Can you explain why this would be helpful?
What problem are you facing that this change would solve?

For myself I'm unsure that adding categories to modules would be of any benifit outside of administrative book keeping. I use the module "notes" field to track my module grouping. It works because "notes" are included in the search filter.

**Comment by calebelt** [comment]
When the site a lot of modules, the use of filters does not save the situation. For example, on one of my sites more than 200 modules. There are the same type but in different positions. It would be very convenient to expand the modules by category. It is much more convenient to click once on the category than to remember what position the module, or as it is called.

**Comment by brianteeman** [comment]
if you want to do this then there are extensions available on the JED http://extensions.joomla.org that will do this.
