### ISSUE TITLE
404 error if any parent menu elements name is "joomla"

### ISSUE THREAD

**Issue by csbalazs** [joomla/joomla-cms#8853]
In the past it worked, but now I get 404 error if either parent menu elements has a "joomla" alias.

e.g.
http://zotius.hu/joomla/komponensek.html
http://joomlacms.hu/joomla/joomla-mvc

PHP Built On	Linux www11 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64
Database Version	5.5.31-0+wheezy1
Database Collation	utf8_general_ci
PHP Version	5.4.36-0+deb7u3
Web Server	Apache/2.2.22 (Debian)
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by justinherrin** [comment]
I can not recreate this report. Having "joomla" in my URLs works just fine for me. Perhaps you have something in your .htaccess file that is preventing you from having "joomla" in your SEF URLs.

**Comment by csbalazs** [comment]
If I use the original htacces file the problem still exists.
And one more thing, if I enable the Language Filter plugin then the url get a language tag, the url is works.

e.g.
http://zotius.hu/joomla/komponensek.html - not works
http://zotius.hu/hu/joomla/komponensek.html - works (+language filter)

**Comment by bertmert** [comment]
Is there a folder /joomla/ inside Joomla-DocRoot?

**Comment by csbalazs** [comment]
Nothing.

**Comment by ggppdk** [comment]
The 404 page that you get is not coming from your joomla installation
- instead it seems to be you web-server / isp 404 not found page

Can you check your webserver configuration for a sub-domain 'joomla' ?

**Comment by csbalazs** [comment]
I checked in joomlacms.hu admin panel and I didn't found any subdomain config.
I tried it on 4 different sites and (different joomla versions) and this problem stilll exists on 3 site.

**Comment by ggppdk** [comment]
Can you go to Joomla root folder

- check if you have a file: joomla.xml
and rename it to __joomla.xml

**Comment by justinherrin** [comment]
Personally this sounds like a forum discussion rather than a "issue" with Joomla's core. http://forum.joomla.org/

**Comment by csbalazs** [comment]
ggppdk, it's very interesting, if I rename the joomla.xml, that the urls work. What can cause the problem?

**Comment by ggppdk** [comment]
It must be some rule in the configuration of server that is effecting all your sites, it checks for if *.xml file exists and rewrites url to be:

http://joomlacms.hu/joomla.xml/joomla-mvc

you can test the effect with other xml files too
About:
> Personally this sounds like a forum discussion rather than a "issue" with Joomla's core. 
this is not an issue it can be closed

**Comment by csbalazs** [comment]
I don't agree with you! An XML file is part of the base system that is untested in all server configurations. Why is this necessary?

**Comment by ggppdk** [comment]
1. joomla index.php is never reached and **that is not because of Joomla default .htaccess file**
2. about joomla.xml file it is removed together with the installation folder, maybe some upgrade was interrupted or you manually extracted upgrade files,

- but having the file in root folder causes no problems because of joomla itself, 
- and furthermore **the filename itself is totally irrelevant** the issue is with somename.xml and urls /somename/... and your server configuration seems to be doing this and not Joomla's .htaccess

> I don't agree with you! An XML file is part of the base system that is untested in all server configurations

- i don't understand -how- this server configuration can be supported, maybe add some rule to cancel the rule that your web-server is using ? a more expert than me should say
- further more i do not know if this is common / needed / important server configuration, in order for someone to spend time on it

**Comment by csbalazs** [comment]
This is not so good! Anyone add xy.xml to the Joomla! core without he would have been extensively tested. Who knows whom not even the url? In my opinion, after that the minimum is extended to the Joomla! wiki with solution, or get out this file the Joomla! core. Someone writes exactly how can I configure the server, beacause this is not the good solution to rename xml file after every updates.

**Comment by brianteeman** [comment]
The problem is YOUR server being badly configured. The problem is NOT
joomla!!

**Comment by mbabker** [comment]
1) The only time you'd have a joomla.xml at your site's root is if an
update failed part of the way through the process (before the point the
manifest is moved to the right place) or you've extracted an update package
over your existing site.  The XML file is placed at the site root in these
packages to allow updates to be processed.

2) Even with this file in the root, Joomla functions correctly on a
properly configured server.  A route containing /joomla without the
extension would be pushed into Joomla and the internal URI handled by
.htaccess if enabled.

3) The scenario you've hit indicates a bad configuration somewhere.  I
can't say where on the server it would be, but something is causing the
route to be matched incorrectly to that file.

**Comment by csbalazs** [comment]
The same server, but on one side and the other side does not operate.
 
(212.108.220.8)
1. http://joomlabs.hu/joomla/joomla-tanácsadás (working)
2. http://kulfoldnet.hu/joomla/mi-a-külföldnet (not working)

(212.108.220.16)
3. http://joomlacms.hu/joomla/joomla-mvc (not working)
4. http://zotius.hu/joomla/magyar-nyelvi-fájlok.html (not working)

What is important In the past it worked. In the server was not set to anything for month.

I have still not clear how it can affect a xml file to the url generate.

SEO setting in all site:
Search Engine Friendly URLs : Yes
Use URL rewriting: Yes
Adds Suffix to URL: No
Unicode Aliases Yes
+ original .htacces file

And one more thing, the system administrator say: He always get this error, if I get this url: http://kulfoldnet.hu/joomla/mi-a-külföldnet
File does not exist: /var/www/virtual/kulfoldnet.hu/htdocs/joomla.xml/mi-a-k\xc3\xbclf\xc3\xb6ldnet

**Comment by Fedik** [comment]
@csbalazs for test: all link where you have `/joomla` try load as `index.php/joomla/...` .. 

Example: 
`http://joomlacms.hu/joomla/joomla-mvc` 
become 
`http://joomlacms.hu/index.php/joomla/joomla-mvc`

works, right?
That means you have problem before Joomla actually start doing any job.
Search your problem in server setup, I think there a problem with Apache rewrite

**Comment by csbalazs** [comment]
Fedik, all other url works, except the menu elements which have a "joomla" alias.

**Comment by mbabker** [comment]
The key is in what you posted a bit ago:

> File does not exist: /var/www/virtual/kulfoldnet.hu/htdocs/joomla.xml/mi-a-k\xc3\xbclf\xc3\xb6ldnet

For whatever reason (bad .htaccess configuration or bad server-side Apache configuration as examples) something is translating your URLs prefixed with `/joomla` internally to `/joomla.xml/` which is causing Apache to look for a physical file.  The 404 error you're getting, as pointed out earlier, is coming from the server, not Joomla (http://joomlacms.hu/joomla-mvc goes to Joomla's 404 page, just as a validation that stuff is getting handled correctly for that case).

Either way, you've got a server specific configuration issue on your hands.  Your issue is NOT a bug with the Joomla distribution.

**Comment by brianteeman** [comment]
Closed d as not  a joomla issue

**Comment by Zotius** [comment]
Hey! Closing is not the solution the problem, but also must repair.

**Comment by MATsxm** [comment]
@Zotius as it is **NOT a bug** and that here is the Issue section for the Joomla! CMS, it must be closed.
If you want to go further:
http://forum.joomla.org/
https://docs.joomla.org/Main_Page
are the places to...
Thanks

**Comment by ggppdk** [comment]
@Zotius

- most important please spend time reading the answers
- things have been explained in detail -**more than once** so you could have missed it-,
- please appreciate the time of people answering for something that was not a Joomla issue in the first place

> Hey! Closing is not the solution the problem, but also must repair.

you mean let issue be open until you fix / modify your server configuration ?

- **Joomla index.php is never reached**
- the 404 error is not generated by Joomla 
IF YOU DELETE JOOMLA and type this url you will still get the same error page
**it is generated by the web server** and **because of web server config**
- **Use some other non-found url to see how the 404 error page from Joomla** (for your website) looks like
-  **Every solution is done at a proper place )) and proper place is server configuration**. Nobody is stopping you from doing the solution. 

I am sure that moderators will re-open this if you provide some **solid** proof of something different

Furthermore if you do not want to fix / modify your server configuration,
then you can delete joomla.xml from root folder, 
- it is not required to be there after upgrade is done *and upgrading via Joomla web-interface to J3.4.8 does not leave the joomla.xml file there*  but that the file is not relevant, what is relevant is your server configuration

@Zotius @csbalazs 
You even you got free help and a "quick" solution, **for something that was not a joomla issue**, which was posted in wrong place, without first posting here:
http://forum.joomla.org/
which is the correct place for posting issues when not having proof or some reasonable suspission that are Joomla bugs
