### ISSUE TITLE
Registration model doesn't create correct messages on failed registration email

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#8900]
Testing instructions:

1. Enter wrong email settings in global config
2. Register a user in frontend assuming that user activation is required.
3. See COM_USERS_REGISTRATION_SEND_MAIL_FAILED message
4. Load /administrator/index.php?option=com_messages  - no messages.
5. Check #__messages table - see empty `user_id_from` and `user_id_to` data.

Issue origin:

`UsersModelRegistration` loads users to send messages to via 

    ->select($db->quoteName(array('name', 'email', 'sendEmail', 'id'))) 
    ...
    $sendEmail = $db->loadColumn();

Next they are iterated via

    foreach ($sendEmail as $userid)

Hence email address to stored and converted to 0

Fix:

Change 
`->select($db->quoteName(array('name', 'email', 'sendEmail', 'id'))) `
to
`->select($db->quoteName('id')) `

**Comment by brianteeman** [comment]
Can you please check this in latest staging as there have been a lot of changes to mail since this report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8900">issues.joomla.org/joomla-cms/8900</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR #9885<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8900">issues.joomla.org/joomla-cms/8900</a>.</sub>
