### ISSUE TITLE
Lot of [warning] entries in error.log

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#8910]
#### Steps to reproduce the issue

I noticed bunch of such warnings in the error.log:

[Wed Nov 11 05:08:01 2015] [warn] [client 55.30.128.181] mod_fcgid: stderr: PHP Strict Standards:  Non-static method JApplicationCms::getMenu() should not be called statically, assuming $this from incompatible context in /var/www/web/libraries/cms/application/site.php on line 272

#### Expected result
Would be nice to fix the code to avoid such warnings...

#### System information (as much as possible)
Joomla 3.4.8
PHP 5.4.45
Apache + cgi-fcgi

#### Additional comments
It's not a bug, but would be nice to keep the code clean.

**Comment by bertmert** [comment]
I only see this messages in combination with buggy 3rd party extensions using soemthing like:
```
$app = JFactory::getApplication();
$app::getMenu();
```
instead of
```
$app = JFactory::getApplication();
$app->getMenu();
```
The extensions should be fixed, not Joomla I think

**Comment by Sulpher** [comment]
Hello @bertmert,
Thanks for your answer. Yes, there are lot of 3rd party extensions. I'll try to determine which exactly  extension have such incorrect code...

**Comment by bertmert** [comment]
Normally you should see it one line before the posted message in error_log.

**Comment by brianteeman** [comment]
I am closing this at this time as it appears to be an extension/template issue and not a joomla core issue. It can always be reopened if found to be otherwise<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8910">issues.joomla.org/joomla-cms/8910</a>.</sub>
