### ISSUE TITLE
Unable to set radio buttons as readonly when using Joomla-specified class

### ISSUE THREAD

**Issue by mhaddy** [joomla/joomla-cms#8996]
#### Steps to reproduce the issue

Originally described in this [Google Groups thread](https://groups.google.com/forum/#!topic/joomla-dev-general/86RBr5lqcjw), when the btn-group btn-group-yesno class is specified for form field type="radio" along with readonly="true", the fields are still editable by the user. Removing this class makes the fields readonly again.
#### Expected result

Radio buttons to be read only when the readonly="true" attribute is specified.
#### Actual result

Radio buttons are editable by user.
#### System information (as much as possible)

Tested in Chrome 64-bit v.48 on El Capitan.

**Comment by ggppdk** [comment]
With latest staging  
if bootstrap class btn-group is added

neither of these work
disabled="true"     (all <input> are disabled but all <label> are clickable)
readonly="true"    (all but 1 <input> are disabled but all <label> are clickable)

i will make a PR (since i already have the code for it),
(together with a few others PRs when i find time) if anyone wants else wants to fix this now please do

**Comment by flash1452** [comment]
@mhaddy Can you please specify exactly which radio buttons do u want to behave as read-only.Can you provide any screenshot or file name????

**Comment by mhaddy** [comment]
@flash1452 Do you need more information than what is provided here? https://groups.google.com/d/msg/joomla-dev-general/86RBr5lqcjw/CHcrgiSBBQAJ

**Comment by franz-wohlkoenig** [comment]
@ggppdk is a PR coming to test?

**Comment by brianteeman** [comment]
Closing this as we have two PR to resolve it #10969 and #12039
