### ISSUE TITLE
REGRESION - session time out

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9016]
In 3.4.6 and below when a session timed out and you were forced to log back in to joomla you were returned to the page you were on when the session timed out. This is no longer possible.

I forget now which release this feature was added but it was very popular when it was added

**Comment by Twincarb** [comment]
Having the option of being able to select if a user who's session has timed out is redirected to the normal entry point vs able to resume at the last location would be good.
In my scenario it would ensure users always enter at the entry point rather than a page they have bookmarked on the inside.

**Comment by infograf768** [comment]
@brianteeman
I tested here after deleting ALL older session cookies and it works fine.
Deleting these cookies also solved the double login issue I had here:
https://github.com/joomla/joomla-cms/pull/9011#issuecomment-176655078

Can you try that?

**Comment by infograf768** [comment]
In fact I still get the double logging at random.

**Comment by andrepereiradasilva** [comment]
@brianteeman @infograf768

The problem is not in the redirect itself. And i can confirm it happens also in latest staging.

When the session expires for timeout you're redirect to the admin login page but maintaining the same URI (ex: administrator/index.php?option=com_content), and this is correct.

The problem is when you make the first login attempt, it will not work and with that you're redirect to admin login page URI (/administrator/index.php), after your second login attempt you will be redirected to the control panel, and this is correct because you were in (/administrator/index.php) page before.

To see what i mean do the following test:

1. Go to global config and change session time to 1 (to test faster).
2. Go to Content -> Articles backend page (/administrator/index.php?option=com_content URI) and wait for some time (2 minutes for instance) to let the session expire.
3. Refresh the page, you go to the admin panel, but note you're still in /administrator/index.php?option=com_content URI.
4. Try to login with your credentials, you can't, it gives "Warning | Your session has expired. Please log in again.". Note the URI has change to just /administrator/index.php
5. Try to login with your credentials, you can, but you're not redirected to the page you were

Now try this:
1. Log out from the backend using the logout button.
2. Change the URI to /administrator/index.php?option=com_content, you will still get the admin login page
3. Login normally and you'll be redirected to the articles list view page.

So, there are two problems at play here:
1. When the session expires, Joomla admin login does not recognizes the first login. I have no idea wht, maybe some session expert can check this.
2. On login failure Joomla admin login shouldn't redirect to /administrator/index.php (should preserve the current URI). This happens because the URI is hardcoded is admin mod_login, see https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_login/tmpl/default.php#L17

Related issue https://github.com/joomla/joomla-cms/issues/9309

**Comment by brianteeman** [comment]
Related issue #8851 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9016">issues.joomla.org/joomla-cms/9016</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think is the same issue as detailed explained in my comment above

**Comment by wilsonge** [comment]
Please try https://github.com/joomla/joomla-cms/pull/9619
