### ISSUE TITLE
Error on updating to 3.5B2 

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#9073]
The following was displayed on "updating" from 3.4.8 to 3.5.0B2
```
Warning
Duplicate entry 'http://[site]/administrator/
Notice:' for key 'idx_link_old' SQL=ALTER TABLE `#__redirect_links`
DROP KEY `idx_link_old`,
ADD UNIQUE KEY `idx_link_old` (`old_url`(191));

Error
Error installing file
```

Database fix shows more issues after the install error (note: version does now show 3.5.0-beta2)
```
Database schema version (3.4.0-2015-02-26) does not match CMS version (3.5.0-2015-11-05).
Table '#__updates' does not have column 'version' with type 'varchar(32)'. (From file 3.2.2-2014-01-18.sql.)
Table '#__session' does not have column 'session_id' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__user_keys' does not have column 'series' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__banners' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__categories' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__contact_details' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__content' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__menu' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__newsfeeds' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__tags' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__ucm_content' does not have column 'core_alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table '#__contentitem_tag_map' should not have index 'idx_tag'. (From file 3.5.0-2015-10-26.sql.)
Table '#__contentitem_tag_map' should not have index 'idx_type'. (From file 3.5.0-2015-10-26.sql.)****
```
after fix,
```
Table '#__user_profiles' does not have column 'profile_value' with type 'TEXT'. (From file 3.3.4-2014-08-03.sql.)
```
Successful database fix after second attempt

**Comment by richard67** [comment]
@photodude Could this be related to problems with detecting utf8mb4 capabilities of the database (see PR #9045)? Does the problem also occur when updating from 3.4.8 to 3.5.0 Beta 2 using an update container patched with PR #9045?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9073">issues.joomla.org/joomla-cms/9073</a>.</sub>

**Comment by photodude** [comment]
@richard67 this doesn't seem related to utf8mb4 to me, 

Error still occurs when updating from 3.4.8 patched with PR #9045 to 3.5.0 Beta 2

**Comment by richard67** [comment]
@photodude Well I thought because I remembered that the SQL statement "SQL=ALTER TABLE `#__redirect_links` DROP KEY `idx_link_old`, ADD UNIQUE KEY `idx_link_old` (`old_url`(191));" from the first warning comes from file administrator/components/com_admin/sql/updates/mysql/3.5.0-2015-07-01.sql, which is the one where these alter table statements related to the changes for utf8mb4 are located.

PR #9045 only implements a part of the bigger PR #8472, and with that one (#8472) i am pretty sure that the problem you found was already solved but it was somehow decided by PLT or whomever not to merge #8472 but drop severla new ones, of which #9045 is one.

If you want I can provide a patched beta 2 update container containing #8472 merged into the beta 2, so you could test this. Or at least you can find a solution for your own, new PR in #8472.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9073">issues.joomla.org/joomla-cms/9073</a>.</sub>

**Comment by photodude** [comment]
@richard67 I'm not sure I understood, did you mean that the patch needed to be applied to install package for 3.5B2?

**Comment by richard67** [comment]
@photodude Yes, #8472 (an so also #9045) merged into the Joomla_3.5.0-beta2-Beta-Update_Package.zip, you could find that on [http://test5.richard-fath.de/Joomla_3.5.0-beta2-Beta-Update_Package_utf8mb4_fix9.zip](http://test5.richard-fath.de/Joomla_3.5.0-beta2-Beta-Update_Package_utf8mb4_fix9.zip "http://test5.richard-fath.de/Joomla_3.5.0-beta2-Beta-Update_Package_utf8mb4_fix9.zip"). Or you can use [http://test5.richard-fath.de/list_test**2**.xml](http://test5.richard-fath.de/list_test2.xml "http://test5.richard-fath.de/list_test2.xml") as custom URL for the Joomla Updater. Note that in this case you have to use http as shown here, not https like with a standard Joomla update URL.

With this package I had no issues upgrading from 3.4.8 to 3.5.0 Beta 2, regardless if the database supported utf8mb4 or not.

... but #8472 was a big thing with many other changes which maybe will not go into 3.5, see [https://groups.google.com/d/msg/joomla-dev-cms/aN0x7unCFog/8_1TdV2WAwAJ](https://groups.google.com/d/msg/joomla-dev-cms/aN0x7unCFog/8_1TdV2WAwAJ "https://groups.google.com/d/msg/joomla-dev-cms/aN0x7unCFog/8_1TdV2WAwAJ"), so maybe it is better to solve this and only this problem here with a new PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9073">issues.joomla.org/joomla-cms/9073</a>.</sub>

**Comment by richard67** [comment]
@photodude  Sorry, wrong link to discussion item, I meant [https://groups.google.com/d/msg/joomla-dev-cms/aN0x7unCFog/cLmOBK8CCAAJ](https://groups.google.com/d/msg/joomla-dev-cms/aN0x7unCFog/cLmOBK8CCAAJ "https://groups.google.com/d/msg/joomla-dev-cms/aN0x7unCFog/cLmOBK8CCAAJ"). But there was also another one in the mailing lists which I do not remember now, where they (someone from PLT or a maintainer) said they will split it up into several single PRs before Beta 3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9073">issues.joomla.org/joomla-cms/9073</a>.</sub>

**Comment by richard67** [comment]
@photodude Ah, I found it, was not in the mailing list but in the discussion of the PR: [https://github.com/joomla/joomla-cms/pull/8472#issuecomment-176129413](https://github.com/joomla/joomla-cms/pull/8472#issuecomment-176129413 "https://github.com/joomla/joomla-cms/pull/8472#issuecomment-176129413") ... seems nothing happened since then.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9073">issues.joomla.org/joomla-cms/9073</a>.</sub>

**Comment by photodude** [comment]
@richard67 I tested updating from 3.4.8 with a 3.5.0B2 upgrade package patched with PR #9045 (reverse of how I previously tested it.

Same issue, still getting the error.

Tested with your patched package for the upgrade, same issue.

**Comment by wilsonge** [comment]
Don't stress people :p this is all utf8mb4 related. Me and @roland-d are working on this and will have a PR to hopefully fix this stuff soon. Closing for now

**Comment by photodude** [comment]
Thanks @wilsonge I look forward to seeing the PR to fix this issue.
