### ISSUE TITLE
When tick all the check box of one page and move to next page,It will uncheck all the items of previous page

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#9109]
After moving to next page,layman wont get that all the work he /she has been doing are undo.

**Comment by N6REJ** [comment]
This is as designed to do all the boxes, simple set your view filter to 
"all"
Bear

**Comment by jaisheela** [comment]
What's the need of pagination,If i have to set the filter to ALL ,With the thousands of data,page takes time to load,

**Comment by richard67** [comment]
Well if it would not be like this, the user might accidently delete things which he cannot see because on a different page than the actual one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9109">issues.joomla.org/joomla-cms/9109</a>.</sub>

**Comment by brianteeman** [comment]
I understand your comment but the reason stated above for not doing this is much greater than the use case you described. This is now closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9109">issues.joomla.org/joomla-cms/9109</a>.</sub>

**Comment by jaisheela** [comment]
I do agree your point,But in joomla trashing is of tw steps,
At first you need to trash and then empty trash,he /she can recover.

**Comment by brianteeman** [comment]
Not everywhere

**Comment by richard67** [comment]
@jaisheela Is it really faster to go through lots of data page by page and checking all items on a page and at the end then push a button (e.g. trash) than it is to switch paging to "All" and wait until all shown, then check them all and delete them?

I don't really think so.

Maybe it "feels" as is if it was faster because you see each page sooner and you can click on something soon each time instead of waiting one longer time until all loaded on 1 page, but at the end you had much more to click, and wait time in total plus time needed for all these clicks is fore sure longer than waiting 1 time for a page displaying all.

And if it is not like this, if showing all takes too long compaged to e.g. showing 20 times a page with 1/20 of all items per page, e.g. 30 or 50, then this is the bug, and this has to be solved by speeding it up.

So I really do not see the sense in your use case.
