### ISSUE TITLE
[Regression] Tooltips not visible in batch modal

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9363]
#### Steps to reproduce the issue
Joomla 3.5RC
In article manager select multiple articles and then batch
Hover over the two top items and you will see the tooltip is hidden below the title
![screen shot 2016-03-10 at 10 06 13](https://issues.joomla.org/uploads/1/dba89ff4bccd19f69cdf61cf15302616.png)

**Comment by brianteeman** [comment]
The same problem is true in the other batch views but I assume its the same code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9363">issues.joomla.org/joomla-cms/9363</a>.</sub>

**Comment by MATsxm** [comment]
Able to reproduce on 3.5rc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9363">issues.joomla.org/joomla-cms/9363</a>.</sub>

**Comment by muhakh** [comment]
I'm able to reproduce it too.

**Comment by andrepereiradasilva** [comment]
+1 reproducing it

**Comment by Bakual** [comment]
It's caused by https://github.com/joomla/joomla-cms/pull/9140

**Comment by brianteeman** [comment]
Which was the main role of that pr :(

**Comment by brianteeman** [comment]
Setting to needs review so  maintainer ( @wilsonge et al) can make a decision if the PR should be reverted<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9363">issues.joomla.org/joomla-cms/9363</a>.</sub>

**Comment by wilsonge** [comment]
What's the feeling here - which is least usable :(

**Comment by Bakual** [comment]
Personally I would revert that single rule.
Currently, the tooltips are useless on any device as they do not show.
When we revert, some modals become unusable for devices with very small screens. But honestly, when I tried with resizing the buttons became unusuable (below screen) before the body was to small. The scrolling didn't help there because the buttons stay below the screen. Thus I doubt that line really solves anything.
Also it shows ugly scroll bars for me even if the window is big enough to show everything.

**Comment by infograf768** [comment]
Taking off that rule does not solve the tooltips issue here.

**Comment by infograf768** [comment]
In fact, reverting all PR https://github.com/joomla/joomla-cms/pull/9140 does not get the tooltips back here.
Macintosh, Firefox, Chrome, Safari

**Comment by Bakual** [comment]
You're sure you cleared browser cache?

**Comment by infograf768** [comment]
tested on the 3 browsers, caches deleted indeed.

**Comment by Bakual** [comment]
Strange.

**Comment by JoomliC** [comment]
I've created the PR to fix scrolling on webkit mobile browser to prevent a regression with new usage of BS modal to replace mootools old one.
The scrolling fix is not a nice hack but it's an known issue in BS2 and BS3 (due to webkit touch with no effect inside BS modals).

Great you've found this issue with tooltip, and thanks! (i didn't notice it when working on PR to fix scrolling).

I will open a PR to fix this tooltip issue in modals in arround 1 hour.

The reason is the layout language for batch, the container set for tooltip is wrong.
It is set to <pre>.modal-body</pre>, but should be set to <pre>.modal</pre>

<blockquote>
 Also it shows ugly scroll bars for me even if the window is big enough to show everything.
</blockquote>
Not directly related to my PR on scoll fix, but to the padding set for modal-body.
Will try to fix it in the same time as fixing the tooltip. Your test would be welcome! ;-)

<blockquote>
The scrolling didn't help there because the buttons stay below the screen. Thus I doubt that line really solves anything.
</blockquote>
You mean resizing to a bery low height on a desktop device ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9363">issues.joomla.org/joomla-cms/9363</a>.</sub>

**Comment by JoomliC** [comment]
I have created the PR for tooltip fix in batch modal.

@Bakual still working on a way to add scroll only when needed (but even if working well on desktop, still an issue on my iOS phone...) and not having to set the <code>overflow-y: auto !important</code> in css ;-)

I think we can close here, as a PR ;-)

**Comment by brianteeman** [comment]
Closed

**Comment by infograf768** [comment]
@Bakual 
Looks like I was testing on the wrong test site. Apologies.
