### ISSUE TITLE
[regression] com_joomlaupdate throws Notice: Undefined property: JUpdate::$downloadurl

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#9392]
#### Steps to reproduce the issue

1. Install last staging / Nightly build: https://developer.joomla.org/cms-packages/
2. switch the core update URL to "Test"
3. go to com_joomlaupdate

#### Expected result

It shows the update to 3.5-rc

#### Actual result

It thows errors see:
![screen shot 2016-03-12 at 12 12 21](https://issues.joomla.org/uploads/1/36552620bc958d39999413f2dc919e61.jpg)

#### System information (as much as possible)

staging
PHP7

#### Additional comments

It works on a 3.4.8 site so something is broken between 3.4.8 and 3.5-rc

**Comment by brianteeman** [comment]
Can not confirm on either RC or staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9392">issues.joomla.org/joomla-cms/9392</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i confirm if you use this package https://developer.joomla.org/cms-packages/Joomla_3.5.0-beta6-dev-Beta-Full_Package.zip

**Comment by andrepereiradasilva** [comment]
but i think this is because the test joomla update xml is not updated. It still says `3.5.0-beta5` and it should be `3.5.0-rc` and for version `3.[34]` when it should be 3.5 `3.[345]`.
See https://update.joomla.org/core/teststs/extension_sts.xml

@wilsonge @mbabker can you check?

Anyway it should not find the update in that case.

**Comment by mbabker** [comment]
3.5 is probably purposefully left out since you can't update between
beta/RC releases.

**Comment by andrepereiradasilva** [comment]
> you can't update between beta/RC releases.

@mbabker i've been doing that in 3.5.0 betas (i think)

Also don't know why you should't ...
From a beta/rc to a stable i understand you can't, but from beta 1 to beta 2 ... i think you should.

**Comment by mbabker** [comment]
Usually the thing that breaks this if you don't know what you're doing is
the database update later.  If you edit an old schema file between betas
then the only way to get back in sync is with the Fix button.  So the
marketing message is beta upgrades are unsupported.

**Comment by andrepereiradasilva** [comment]
ok i see

**Comment by andrepereiradasilva** [comment]
this is some kind of bug in the updater, not related to any version in particular.

if, for instance, we put `<php_minimum>9.9.99</php_minimum>` on a valid update or even `<targetplatform name="joomla" version="9.9" />` on a valid update that error will appear instead of saying there are no updates.

In other words if the current joomla version doesn't fill some requirements of the update this error will appear.

This happens in latest staging (if you read a custom xml with an higher version) and in older versions too (i tested 3.4.8).

So it's seems this is a bug not a regression.

**Comment by wilsonge** [comment]
OK So i added a extra line in the stream for nic (https://github.com/joomla/update.joomla.org/commit/85e42c01d9df80882e99b2af0a11439077ca2e85) to help him test a Joomla Update feature he's writing. So it's my bad not updating the extension_sts file as well I guess!

**Comment by andrepereiradasilva** [comment]
Actually this allows to found a problem in the joomla update. :)
See this PR i made https://github.com/joomla/joomla-cms/pull/9401 i tried to explain the problem.

**Comment by zero-24** [comment]
closing as we have a PR.
