### ISSUE TITLE
J! 3.5.0 RC2 + RC3 Update package: where is the xml file?

### ISSUE THREAD

**Issue by Hoffi1** [joomla/joomla-cms#9441]
#### Steps to reproduce the issue
Download the RC2 or RC3 Update zip and try to install it on any Joomla site using Extension Manager

#### Expected result
It will update to RC2 or RC3

#### Actual result
Warning: JInstaller::Install: Can't find XML setup file.
Error: Unable to find install package

#### System information (as much as possible)
n/a

#### Additional comments
There is really no joomla.xml file within update package (at least zip)
On rc(1) package one was there.

**Comment by richard67** [comment]
As far as I know the xml file has been moved by purpose because updating via Extension Installer is not supported anymore.

This has been done with RC 2 as far as I remember.

There is another way to update with downloaded zip: put the zip into your Joomla!'s tmp folder and then in Joomla! Update component's options, change the update channel to the desired level, e.g. Testing for latest Release Candidate 3, and then the zip will be found.

But I am not sure if this works for updating form a Beta or RC to a newer Beta or RC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9441">issues.joomla.org/joomla-cms/9441</a>.</sub>

**Comment by bertmert** [comment]
Known: https://github.com/joomla/joomla-cms/issues/9430

**Comment by Hoffi1** [comment]
I don't understand you guys. Wjy not keeping things simple? Why moving to this complicated mechanism instead of simply upload and install the zip?

btw: Copying the zip to sites tmp folder doesn't work in any way. Maybe because there is no way to select the tmp folder as update channel.
Maybe you expect every computer must have a connection to your server - but my development machine will NEVER have such a connection. So at the moment it seems I can't update Joomla anymore. Then I can stop any work with and for Joomla...

**Comment by richard67** [comment]
> btw: Copying the zip to sites tmp folder doesn't work in any way. Maybe because there is no way to select the tmp folder as update channel.

I did not say set update channel to tmp folder, I said set update channel what fits to your version and the version you want to install, and have put the zip before into the tmp folder.

Did you try that? If not, how can you say then it does not work in any way???

**Comment by richard67** [comment]
P.S.: And if that does not work you still can use the former 3rd method (now 2nd), to unpack the zip into a new Joomla! folder, put in your old configuration.php so it connects to the old database, login at backend and then run the database fixer. So what?

**Comment by mbabker** [comment]
> I don't understand you guys. Wjy not keeping things simple? Why moving to this complicated mechanism instead of simply upload and install the zip?

It's been explained elsewhere but summing up the high level technical reasoning again.  The Extension Manager's purpose for updating extensions is great, those extensions aren't loaded into memory or being used to process the extensions' updates.  With the core platform, when you're updating the whole CMS in that way you're running the full update on the old CMS version's code which is unreliable, especially if the update relies on code in the new version.  The update component circumnavigates this by extracting all the files in a script that runs isolated from the CMS application then calls back into the API to finish the update (all running on the new version's code).  This is why the 2.5 to 3.x update instructions have generally included disabling certain plugins (because those plugins run expecting the new version features but that isn't the case when coming from 2.5 with the Extension Manager upgrade path).  Until now, it's worked but caused some headaches.  The 3.5 update requires changes that with the Extension Manager way things would fail miserably.

**Comment by MATsxm** [comment]
Also for the updating process, please take a look here:
https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5

**Comment by Hoffi1** [comment]
@richard67 Seems we talk about different Joomlas.
On Installer Options I can set the Minimum Stability e.g. to Release Candidate or Development (which I tried). On Joomla! Update Options I can set The Update Channel to Default, Joomla! Next, Testing, or Custom URL. No one accepts the zip in tmp folder - including the crazy try with (site-url)/tmp. Other Options I don't see anywhere.
And your last suggest I will friendly interprete as a joke. I've more than a dozen sites with a lot of additional extensions installed for development and tests I will update from time to time. Do you really suggest I should practically setup new sites on every new Joomla version instead of simply select a zip and click "Upload & Install"?

@mbabker Thanks for your understnadable explanation. But at the moment I have no method to update a site to J! 3.5.0RC3++. I always get "No updates available" in Joomla! Update. (also with "Custom URL" where I see the zip in my browser)

**Comment by Hoffi1** [comment]
Thanks @MATsxm So because I don't have a connection I must do all these complicated manual steps. Why can't the Joomla! Update component provide a "Upload and Update" button like the Extension Manager? Then it would get the package from me instead from a server but can further do all the other great job the same way?

**Comment by mbabker** [comment]
The URL has to point to an XML manifest, it does not point to a ZIP file.  Right now it also is dependent on being able to fetch that remote XML file to even use the tmp workaround.  I looked at possibly writing a plugin to fake this but so far the only way I can accomplish it is with a core hack.  I'll think on this some more to see how comfortable I am with it.

**Comment by Hoffi1** [comment]
Hm... "cloning" your server by providing xml, zip etc. on a local site in correct form could be an alternative. Something like downloading all files required and uploading them locally on each new Joomla version. Then using "Custom URL" to connect this local url.
This could be nearly as easy as simple zip Upload and Install. :smile:

**Comment by mbabker** [comment]
The update server's XML schema is [here on GitHub](https://github.com/joomla/update.joomla.org) so really it's a matter of copying the relevant files and changing the URL references to point to something that's accessible in your local environment.  It is a bit of extra work compared to just clicking a couple buttons in the Extension Manager but functionally reaches the same end state.

**Comment by richard67** [comment]
That's what I use for testing since weeks, and it is really not much work.

**Comment by Hoffi1** [comment]
Sounds good, thanks. Today is too late for me but will try it tomorrow.
And as more local sites I have to update as less extra work I have - relatively.
Thank you all. :+1:

**Comment by Bakual** [comment]
Please also note that you can set a (authenticated) proxy server in the global configuration so Joomla can connect outside an intranet. This works for all connections which use the JHTTP class. Fetching the XML is possible this way. I know there was a PR to change the actual download of the zip to use that class as well, but I don't remember if it has been merged yet. If it's merged, then updates using that proxy server should work.

**Comment by zero-24** [comment]
@bakual no it is not merged see: https://github.com/joomla/joomla-cms/pull/8645

**Comment by Hoffi1** [comment]
@Bakual Thanks. Does this proxy needs direct access to internet and the local network? Then it's not for me because I don't have such a machine inbetween. Do you have a link where I could get more information?

**Comment by Bakual** [comment]
@zero-24 Now that the AmazonS3 is fixed (for quite some time actually) it should be fine to be merged.But @wilsonge set the milestone to 3.5.1. So hopefully we get it into that release then.

@Hoffi1 Yes, that would be the purpose of such a proxy. We have this in our company network and all traffic from within the network has to go through that proxy (authenticated) or it gets refused.
Usually, any network has such a firewall/proxy system, except if you have a network which is completely disconnected from the internet for some reason.

**Comment by Hoffi1** [comment]
Thanks @Bakual. The latter one is my test network. :wink:

**Comment by wilsonge** [comment]
Please see https://github.com/joomla/joomla-cms/pull/9469 for manual installations through Joomla Update :)
