### ISSUE TITLE
RC4 cannot Update RC2

### ISSUE THREAD

**Issue by sentixGmbH** [joomla/joomla-cms#9445]
#### Steps to reproduce the issue

Fresh installation of RC2 and the update RC4 with Extension Manager

#### Expected result

Update should work successfully

#### Actual result

Error messages:

Warning
JInstaller: :Install: Can't find XML setup file.

Error
Unable to find install package

#### System information (as much as possible)

PHP 7.0.4
J 3.5 RC2
Windows 2012 R2

#### Additional comments

I am not sure whether this behavior is intended due to RC status

**Comment by andrepereiradasilva** [comment]
@brianteeman same as https://github.com/joomla/joomla-cms/issues/9441?

**Comment by brianteeman** [comment]
yes

On 16 March 2016 at 12:09, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> same as #9441
> <https://github.com/joomla/joomla-cms/issues/9441>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9445#issuecomment-197288584>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
We are removing support for upgrading Joomla through Extension Manager. There is very good reasoning for this which has been explained elsewhere but summing up the high level technical reasoning again:

The Extension Manager's purpose for updating extensions is great, those extensions aren't loaded into memory or being used to process the extensions' updates. With the core platform, when you're updating the whole CMS in that way you're running the full update on the old CMS version's code which is unreliable, especially if the update relies on code in the new version. The update component circumnavigates this by extracting all the files in a script that runs isolated from the CMS application then calls back into the API to finish the update (all running on the new version's code). This is why the 2.5 to 3.x update instructions have generally included disabling certain plugins (because those plugins run expecting the new version features but that isn't the case when coming from 2.5 with the Extension Manager upgrade path). Until now, it's worked but caused some headaches. The 3.5 update requires changes that with the Extension Manager way things would fail miserably.

We are currently working on better ways to upgrade Joomla if your don't have any internet connection. But for now we strongly recommend updating through Joomla Update or via the old 1.5 approach which has all been documented fully at https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5

**Comment by sentixGmbH** [comment]
Thanks for your comprehensive answer. I overlooked this.
