### ISSUE TITLE
Unable to install new component with database tables during upgrade package  installation

### ISSUE THREAD

**Issue by ZhukDmitry** [joomla/joomla-cms#9585]
#### Steps to reproduce the issue
Create two package versions, for example
PKGv1 - contains only plugin
PKGv2 - contains plugin and component with its database table and table updates 

1 - Install PKGv1
2 - Install PKGv2

#### Expected result
I expect that package PKGv2 will upgrade v1 and new component will be installed

#### Actual result
In real time upgrade installation tries to execute SQL scripts in \admin\sql\updates folder, and there is no correctly component installation, you've got the error about "table does not exist"

#### System information (as much as possible)
Last check was:
Database Version 	5.5.46-0ubuntu0.14.04.2
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.19
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

#### Additional comments
But if you initially install PKGv2 (with component), it is installed correctly, and processed updates correctly, for example  PKGv3 (with component's table changes)
I just want to say, that if in initial installation of package there were not all extensions with it's database tables you can't install upgrade package with new extensions with tables

**Comment by brianteeman** [comment]
Without seeing the code it is impossible to say but it sounds like an issue in your code and not the core of Joomla so I am closing this here. 

You will be better asking this question on the mailing list specifically or extension development https://groups.google.com/forum/#!forum/joomla-dev-general

**Comment by ZhukDmitry** [comment]
What code?
It is just packages, without any installation code. Extensions and manifest file.

**Comment by brianteeman** [comment]
Please use the mailing list as I suggested

On 25 March 2016 at 10:28, ZhukDmitry <notifications@github.com> wrote:

> What code?
> It is just packages, without any installation code. Extensions and
> manifest file.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9585#issuecomment-201232202>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
This is a bug.

`JInstallerAdapterPackage::copyBaseFiles()` triggers a new `JInstaller` instance for each extension in the package based on whatever route the package installation is using (which would only be install or update since discover_install is unsupported for packages).  In none of the adapters does the route get switched from update to install if the update path is triggered and the extension is not installed.

**Comment by waveywhite** [comment]
I've having a similar problem. Is this due to this problem or a new bug?

1. Installed a package with a single component but lots of modules & plugins. Updates to this work fine.
2. Added a new component to the package and installed.
3. The new component's code was installed but the database schema wasn't applied
4. Uninstall just the new component
5. Install the new component separately and it installs fine, along with the database schema.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9585">issues.joomla.org/joomla-cms/9585</a>.</sub>

**Comment by mbabker** [comment]
It hasn't changed since my comment from March.

**Comment by waveywhite** [comment]
We use packages for rolling out changes to some major websites, it's definitely a plus for Joomla when managing large sites. If someone were to fix this problem it would be much appreciated.

**Comment by mbabker** [comment]
This is completely untested on my part but logically https://github.com/joomla/joomla-cms/pull/11075 should do the trick.

**Comment by brianteeman** [comment]
Closing as we have a PR for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9585">issues.joomla.org/joomla-cms/9585</a>.</sub>

**Comment by waveywhite** [comment]
Many thanks @mbabker and @brianteeman
