### ISSUE TITLE
Clear Cache on Update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9626]
We have had quite a few reports of issues (here and on the forum) after updating that are caused by cache as it caches admin as well as site components - especially with the Page Cache plugin

If the joomla update process cleared the cache it would resolve this once and for all

**Comment by zero-24** [comment]
Hmm i'm not sure can joomla clear the browser cache of an client? I guess the only thing we can do is to have at the end of every assest a version string that comes from the joomlaversion or the MD5CHECKSUM file that handel this version string.

**Comment by brianteeman** [comment]
Not talking about the browser cache but the joomla cache files /cache

**Comment by zero-24** [comment]
Ah ok. This should be possible. Maybe in the script.php i can have a look later

**Comment by brianteeman** [comment]
See #9568 for examples of some issues caused because of joomla cache<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9626">issues.joomla.org/joomla-cms/9626</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Related, clear opcache/apcu cache also needs to be clear on update
https://github.com/joomla/joomla-cms/issues/9515

**Comment by zero-24** [comment]
@brianteeman see: https://github.com/joomla/joomla-cms/pull/9628

@andrepereiradasilva i have no idea how opcache / apcu works or how to test that it works. ;)

**Comment by andrepereiradasilva** [comment]
@zero-24 see https://github.com/joomla/joomla-cms/issues/9515#issuecomment-200232556

The problem in opcache is reggarding `opcache.revalidate_freq` php ini configuration, by default this is set to "2" (see http://php.net/manual/en/opcache.configuration.php).

Which mean that servers with opcache only check the timestamps of the php files (to check if there are any changes and the opcache php files needed to be updated) after 2 seconds, which on very fast disks (ex: SSD) can be high.

This means, if the opcache is not cleaned, after the update, joomla could still be reading old joomla pre-update php files from the opcache cache php files. And this could gives problems on update (as described in https://github.com/joomla/joomla-cms/issues/9515): blank pages, php errors, etc.

It seems the same problem is valid for other php caching mecanism (ex: apc).

See https://github.com/joomla/joomla-cms/issues/9515#issuecomment-200232556 for a proposed solution

PS: to test this behaviour it's easier to put a `opcache.revalidate_freq` to a higher timer (like 30 seconds for instance). `opcache.revalidate_freq = 30`

**Comment by sonvnn** [comment]
@brianteeman I updated my site from Joomla 3.5.0 to Joomla 3.5.1 and this problem still happen. I tried remove all Joomla Cache file but no better. 
1 - Login first time is successful. 
2 - Logout and re-login. I get notice "The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.".

Solution: Disable Plugin - Joomla Cache.

**Comment by tgetgood13** [comment]
I am getting the same issue as described by sonvnn.

Is Disabling Joomla Page Cache an actual solution?
This isn't a 3rd party plugin, so any update to the core should be compatible with it, no?

My solution which seems to be holding at the moment, is to exclude the behind login URLs from the Page Cache so that we can still take advantage of Page Caching.

**Comment by lizakudro** [comment]
Joomla version, 3.5.1. 
Reg Issue: "The most recent request was denied because it contained an invalid security token. Please refresh the page and try again."
Agree with tgetgood13. Adding Log In, Log Out to "Exclude Menu Items" In System-Page Cache plugin settings fixed the token issue for me. Before that I had to delete entries from _session table, after which users were able to login, but not able to re-login after they  Log out.

![cache](https://cloud.githubusercontent.com/assets/19576672/15550782/a528e33a-2278-11e6-81cd-e2cc06275c35.png)

**Comment by labsektor** [comment]
Found something.
Akeeba backup making problems for me. 
1. Make backup
2. Turn off System - Backup on update
3. Update
4. Turn on System - Backup on update
