### ISSUE TITLE
Joomla 3.5 Admin Problem

### ISSUE THREAD

**Issue by edwimmer** [joomla/joomla-cms#9693]
Just upgraded to 3.5, now I can only see active position items under the "Select Position" drop down menu, all other positions are gone. See attached screen shot. HELP!![screen shot 2016-03-31 at 20 50 28](https://issues.joomla.org/uploads/1/bf8d1ef0b652f083f03c74060dcb2d9c.png)

**Comment by MATsxm** [comment]
Maybe I'm wrong or missing something but looking at the screenshot, this is the "Search Tools" then my question is: why would you search a module for a position where there's NO module?
The result would be NULL anyway?

**Comment by SharkyKZ** [comment]
It's meant to be like that since 1.x, if I'm not mistaken. Whatever you had before 3.5 was wrong.

**Comment by brianteeman** [comment]
That is a filter so it is only going to show you the in-use positions as anything else would produce no results<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9693">issues.joomla.org/joomla-cms/9693</a>.</sub>

**Comment by brianteeman** [comment]
I just checked to be 100% certain and this select filter has only shown the positions in use since at least joomla 2.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9693">issues.joomla.org/joomla-cms/9693</a>.</sub>

**Comment by SharkyKZ** [comment]
Just to clarify, are you getting this only in the module list or also when assigning a module position while editing the module?
