### ISSUE TITLE
Editor field type does not recognize sizing

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9716]
#### Steps to reproduce the issue

Create a form field such as ....
				<field
					name="copyrightText"
					class=""
					showon="copyright:1"
					type="editor"
					default=""
					cols="2"
					rows="4"
					width="300px"
					height="300px"
					label="TPL_SERENITY_COPYRIGHT_TEXT_LABEL"
					editor="tinymce"
					filter="safehtml"
				/>
view field in admin.

#### Expected result
Editor size limited to that specified

#### Actual result
with tinymce its full width and 650px height.
with JCE its 615px by 586px
have cols, rows, height, width has no influence.

#### System information (as much as possible)

[systeminfo-2016-04-03T01-19-33+00-00.txt](https://github.com/joomla/joomla-cms/files/201126/systeminfo-2016-04-03T01-19-33.00-00.txt)

**Comment by brianteeman** [comment]
This has been reported before - cant find it right now but basically if i remember correctly it is because you are using a bootstrap template so if you have to use bootstrap markup for sizes. If you are using a non-bootstrap template then it works correctly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9716">issues.joomla.org/joomla-cms/9716</a>.</sub>

**Comment by ggppdk** [comment]
https://github.com/joomla/joomla-cms/issues/5820
https://github.com/joomla/joomla-cms/pull/8106
https://github.com/joomla/joomla-cms/pull/8591

**Comment by N6REJ** [comment]
This is in admin (isis) so I'm not sure how the front end template would 
matter
Bear

**Comment by N6REJ** [comment]
ok, so we've had 3 issues raised for it with no solution?
Bear

**Comment by brianteeman** [comment]
Closing as a duplicate report. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9716">issues.joomla.org/joomla-cms/9716</a>.</sub>
