### ISSUE TITLE
Error 1064

### ISSUE THREAD

**Issue by triinuke** [joomla/joomla-cms#9719]
I wanted to upgrade joomla 3.4.8 to 3.5.0.
I did backup and then upgrade.
After upgrade I can not add new articles, all new article gives Error 1064.
Then I want put back 3.4.8 backup, but joomla not overwrite the files. He shows that he restored 3.4.8, But if I'm going to administrator->joomla help it shows 3.5.

And still I can not add new articles, all new article gives Error 1064.

Can anybody help?

**Comment by ggppdk** [comment]
Hello, probably this is not a joomla issue,
and because this is not an identified issue, 
- for asking "help", it is better to post here:

http://forum.joomla.org/

Error "1064" sounds like "Mysql syntax error 1064", and it is of no usefulness without the full error message:
**we need the SQL error message** (if you do not see it already, then go to Joomla Global configuration and enable "debug system" and "error reporting")

Also 
- you need to mention PHP / MySQL version numbers  (Got System/System Information)
- it sound likes either the DB tables were not upgraded or you have some **3rd party extension that needs to be updated to work with J3.5.0**

e.g. 3rd party extensions that add extra options / fields to the article form
**you need to update them if you have not done already**

1. Re-extract the J3.5.0 zip package into your joomla root folder (and delete "installation" folder)
2. Go to Backend menu:
Extensions/Database/Fix  (to make sure that all DB tables were updated)
3. Update your all your extensions
4. if the problem persists , get the SQL error message and post it here but also here:
http://forum.joomla.org/  
as this is not a support forum

- if inside the SQL error you can identify a (table) name that reminds you of a 3rd party extension, report the error to the web-site of the author of the 3rd party extension
