### ISSUE TITLE
No updatenotification mail with cachetimeout = 0

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#9789]
We wondered that we didn't get any email concerning update 3.5.0=>3.5.1 from plugin updatenotification.php (until today). Several sites and providers.
We checked email configurations, SuperUser settings and so on. All fine.
After some investigations we found out that for all these Joomlas cachetimeout is set to 0 (administrator/index.php?option=com_installer&view=update > Options button > Updates Caching (in hours)). Maybe the reason?
While debugging the plugin we saw that line https://github.com/joomla/joomla-cms/blob/staging/plugins/system/updatenotification/updatenotification.php#L115 (findUpdates(...)) always returns false.
We changed setting cachetimeout to 1 in two sites (absolutely identical configuration, same provider, same server, same email). 1 has sent an update notification meanwhile. The other one not.
For the first one we deleted JCH-Cache and Page-Cache. Don't know if this is anyhow related.

**Comment by brianteeman** [comment]
I wonder why it was set to 0 the default is 6

**Comment by bertmert** [comment]
Because we have set it to 0.

**Comment by brianteeman** [comment]
Well then I would say it is working a intended

On 7 April 2016 at 18:21, bertmert <notifications@github.com> wrote:

> Because we have set it to 0.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9789#issuecomment-207005760>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
Cachetimeout of 0 has a special meaning in JUpdater. It means constantly refresh the update information every time you check. So it is actually a valid value. The problem is that we also perform a internal check 

https://github.com/joomla/joomla-cms/blob/staging/plugins/system/updatenotification/updatenotification.php#L115 

in the update notification plugin that will fail (0 will never be greater than the last run time vs the current time) - so the plugin won't run. I guess we need an edge case for the cache time being =< 0

**Comment by zero-24** [comment]
@wilsonge 

> I guess we need an edge case for the cache time being =< 0

This would mean we send a mail per site request is that really we want? I think we should add a postinstall message that inform the users about that?

see: https://github.com/joomla/joomla-cms/pull/11631
