### ISSUE TITLE
Hidden tooltip

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9832]
#### Steps to reproduce the issue
Go to Components>Messaging and select My settings from the toolbar

#### Expected result
Modal window with visible tooltips

#### Actual result
Modal window with top tooltip for "Lock Inbox" invisible

**Comment by MATsxm** [comment]
confirmed

**Comment by JoomliC** [comment]
Confirmed, and the reason is usage of hasTooltip class for label (container set to body), and inside BS modal, modalTooltip should be used and container set to modal.
But content of this modal is not a layout, but a component view loaded as an iframe: administrator/components/com_messages/views/config/tmpl/default.php
Similar to this issue, but was inside an existing layout: https://github.com/joomla/joomla-cms/pull/9379
(BS known setting for tooltip inside modals)

Don't know if this view should be a layout instead, or if an easy way to replace <code>hasTooltip</code> by <code>modalTooltip</code> when inside the modal, and using JForm renderField()...

**Comment by JoomliC** [comment]
@brianteeman i have opened a PR to fix issue with tooltip: https://github.com/joomla/joomla-cms/pull/9991
In the same time, after many testing with @andrepereiradasilva , it appears that many modals loading modal.php file inside iframe has the same possible issue (not always visible) but too, i've found many cases where there's missing a container div (related to one of the other issue you have opened), and some having other code styles issues.
For this reason, i will do a few PRs, to improve those modals, and have a homogeneous display of modal content when loading a components view (modal.php) inside iframe. ;-)
