### ISSUE TITLE
Select User field broken after 3.4.8 to 3.5.0 upgrade (works in clean install) - like #9545

### ISSUE THREAD

**Issue by pwust** [joomla/joomla-cms#9913]
#### Steps to reproduce the issue
In Back-end: edit Article, go to Tab "Publishing", go To "Created By", click on "Select User", select any user entry in the popup window "Select User"

#### Expected result
While on a Name, the Mouse cursor changes to "pointing hand", after clicking the name, the popup disappears, and the selected user is shown in "Created By".

#### Actual result
While on a Name, the Mouse cursor changes to "edit text beam", after clicking the name, nothing happens, and the user only can click on "Cancel" to close the popup, and no change of "Created By" field has happened.
Chrome Developer mode shows an error "Uncaught TypeError: window.parent.jSelectUser_jform_created_by_id is not a function"

#### System information (as much as possible)
Joomla! instance with problems has been first installed in March 2015 with the current Joomla! version by then (3.2.x I guess), and has been updated every time an update was published.

Config JSON of the problem system is attached as file "brokensite-systeminfo-2016-04-14T16-33-57+02-00.json.txt".
Screenshot of the moment of the problem is attached as file "brokensite-2016-04-14_16-41-01.png".
![screen shot 2016-04-14 at 10 06 37](https://issues.joomla.org/uploads/1/fa6b2eedfa0ae855c5f63ba74a9b6106.png)
#### Additional comments
This seems to be the same issue as reported in #9545, however I have not a single clue how to fix this, so any help would be great. My skills to fix it myself are very limited.

Another Joomla! instance that was installed in October 2015 (3.4.x I guess) does not show this problem at all.

Config JSON of that working system is attached as file "workingsite-systeminfo-2016-04-14T16-34-09+02-00.json.txt".
Screenshot of the similar moment is attached as file "workingsite-2016-04-14_16-40-43.png".![screen shot 2016-04-14 at 10 06 37](https://issues.joomla.org/uploads/1/2da3e7b4078a1cb1efef26562de20013.png)[workingsite-systeminfo-2016-04-14T16-34-09+02-00.json.txt](https://issues.joomla.org/uploads/1/0cc004d26778fe809c0ce3073498ea1a.txt)[brokensite-systeminfo-2016-04-14T16-33-57+02-00.json.txt](https://issues.joomla.org/uploads/1/6943be45997d98ae8096b28a6083740b.txt)

**Comment by brianteeman** [comment]
it was stated in that issue that it was caused by an extension

On 14 April 2016 at 16:11, Patric <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> In Back-end: edit Article, go to Tab "Publishing", go To "Created By",
> click on "Select User", select any user entry in the popup window "Select
> User"
> Expected result
>
> While on a Name, the Mouse cursor changes to "pointing hand", after
> clicking the name, the popup disappears, and the selected user is shown in
> "Created By".
> Actual result
>
> While on a Name, the Mouse cursor changes to "edit text beam", after
> clicking the name, nothing happens, and the user only can click on "Cancel"
> to close the popup, and no change of "Created By" field has happened.
> Chrome Developer mode shows an error "Uncaught TypeError:
> window.parent.jSelectUser_jform_created_by_id is not a function"
> System information (as much as possible)
>
> Joomla! instance with problems has been first installed in March 2015 with
> the current Joomla! version by then (3.2.x I guess), and has been updated
> every time an update was published.
>
> Config JSON of the problem system is attached as file
> "brokensite-systeminfo-2016-04-14T16-33-57+02-00.json.txt".
> Screenshot of the moment of the problem is attached as file
> "brokensite-2016-04-14_16-41-01.png".
> [image: screen shot 2016-04-14 at 10 06 37]
> <https://camo.githubusercontent.com/b78b2124715044e65c94242427d746ad00a1ce54/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f66613662326565646661306165383535633566363362613734613962363130362e706e67>
> Additional comments
>
> This seems to be the same issue as reported in #9545
> <https://github.com/joomla/joomla-cms/issues/9545>, however I have not a
> single clue how to fix this, so any help would be great. My skills to fix
> it myself are very limited.
>
> Another Joomla! instance that was installed in October 2015 (3.4.x I
> guess) does not show this problem at all.
>
> Config JSON of that working system is attached as file
> "workingsite-systeminfo-2016-04-14T16-34-09+02-00.json.txt".
> Screenshot of the similar moment is attached as file
> "workingsite-2016-04-14_16-40-43.png".[image: screen shot 2016-04-14 at
> 10 06 37]
> <https://camo.githubusercontent.com/09b3e89e0aa071175cbde1b3def2453f98d0b746/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f32646133653762343037386131636231656665663236353632646532303031332e706e67>
> workingsite-systeminfo-2016-04-14T16-34-09+02-00.json.txt
> <https://issues.joomla.org/uploads/1/0cc004d26778fe809c0ce3073498ea1a.txt>brokensite-systeminfo-2016-04-
> 14T16-33 -57+02-00.json.txt
> <https://issues.joomla.org/uploads/1/6943be45997d98ae8096b28a6083740b.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9913>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Please check your extensions. The other report of this behaviour stated it was caused by an extension and that would explain why you are not seeing the issue on a clean install<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9913">issues.joomla.org/joomla-cms/9913</a>.</sub>

**Comment by JoomliC** [comment]
@pwust yes, as Brian mentioned, mine issue was just due to a third party extension not updated.

Don't know exactly where your issue is (as i don't have the same code generated), but could be related to this PR:
https://github.com/joomla/joomla-cms/pull/9659

In the same time, if you have one site working, and not the other one, try to do a transfert of all 3.5.1 files, in case the issue was when upgrading Joomla, and not replacement of all files (i don't know yet if a Joomla issue in 3.5 upgrade, but seen already reported Joomla 3.5 sites not well working, due to not updated files (even if the version number was 3.5.1) and with 3.4 files...
What i would recommend you to do first:
- check updates, and update all your extensions
- if still the issue, so do an re-install using Method C here: https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5/en
Note: for this, use the full upgrade package to 3.5.1, and follow documentation for all the steps. This one package: https://github.com/joomla/joomla-cms/releases/download/3.5.1/Joomla_3.5.1-Stable-Update_Package.zip
- if the issue remain (after all cache browser and site cleaned), then try to apply the patch #9659 

Thank you to keep us informed if you solve the issue, and for which reason (extension update, joomla install, or patch success)!
Cyril<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9913">issues.joomla.org/joomla-cms/9913</a>.</sub>

**Comment by brianteeman** [comment]
@joomlic what was the extension<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9913">issues.joomla.org/joomla-cms/9913</a>.</sub>

**Comment by JoomliC** [comment]
@brianteeman unfortunately, i don't know, as i did a select all update.
And it was one of my test site where i did install dozen of extensions from JED, when searching for popular extensions having issue with mix-collation issue when join on language ;-)

**Comment by pwust** [comment]
Thanks for your comments. All extensions state that they are up to date. 
Interim result:
I just have completed @JoomliC 's recommendation by pushing the complete update package files onto the problem site, and following the manual update instructions, performed a complete "System -> Clear Cache" operation on the site, and finally cleared all possible caches that I could find on my client side.
Unfortunately, nothing has changed from my first post above.
I am now figuring out how to apply #9659 to the problem site. Keep posted...

**Comment by brianteeman** [comment]
Just because an extension is up to date does not mean they are bug free ;)
Also some extensions do NOT use the joomla updater so do not notify you of
new versions - you have to check directly on their web sites

On 15 April 2016 at 13:44, Patric <notifications@github.com> wrote:

> Thanks for your comments. All extensions state that they are up to date.
> Interim result:
> I just have completed @JoomliC <https://github.com/JoomliC> 's
> recommendation by pushing the complete update package files onto the
> problem site, and following the manual update instructions, performed a
> complete "System -> Clear Cache" operation on the site, and finally cleared
> all possible caches that I could find on my client side.
> Unfortunately, nothing has changed from my first post above.
> I am now figuring out how to apply #9659
> <https://github.com/joomla/joomla-cms/pull/9659> to the problem site.
> Keep posted...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9913#issuecomment-210449584>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by pwust** [comment]
@brianteeman - will do

**Comment by pwust** [comment]
Update 2: 
- [x] applied patch for #9659 
--> did not help either.
Now manually checking all Extensions, one by one...

**Comment by pwust** [comment]
- [x] applied patch from #9593 
Now I have a change as follows:
When changing the Administration template from "isis" to "hathor", I can successfully select a different user for "created by" field. Using "isis" template, it will still not work and behave as stated in my first post above.

**Comment by JoomliC** [comment]
@pwust so that it works with hathor with patch, it's expected behavior!
Isis is using a layout override for user field in <code>/administrator/templates/isis/html/layouts/joomla/form/field/user.php</code>

So your joomla site seems good, and issue seems not related to Joomla 3.5.1

Reading again your first message with screen shots, i realize you have mixed, i think, the 2 sites (as the second screen shot is the one with error, not the one working)...
And if you have all transfered 3.5.1 files again, for sure you have a third-party extension changing user field (override?) as the code with error is not the expected code on Isis admin template.

First check that you don't have overrides in Isis template for com_users <code>/administrator/templates/isis/html/com_users</code> (as seems old code loading from you site for modal content). If yes, remove it!

If not, then you have to check all not-joomla-core extensions, and/or search on http://forum.joomla.org in case someone has reported the same issue... related to an extension installed on your site...

Sorry, but won't be able to help you more, as seems not a Joomla issue...
What else ?... good luck!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9913">issues.joomla.org/joomla-cms/9913</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9913">issues.joomla.org/joomla-cms/9913</a>.</sub>

**Comment by pwust** [comment]
@JoomliC THANKS!!! There were in fact template overrides active for "isis" that blew up my stuff, since Oct 2015. No idea what I had done by then. Sorry to have kept all of you busy.

**Comment by JoomliC** [comment]
@pwust You're welcome.
Great you have found the issue! ;-)
