### ISSUE TITLE
Batch process menu items modal window truncates in Isis template

### ISSUE THREAD

**Issue by DonTregartha** [joomla/joomla-cms#9970]
#### Steps to reproduce the issue
Check a menu tem and click 'Batch' button

#### Expected result
A modal pop-up window that fits the screen area available

#### Actual result
Modal window is truncated on the vertical depth - drop downs in lower part of window are not visible.
See screen grab attached.
Appears to be the css class .modal-body 

#### System information (as much as possible)

See attached

#### Additional comments![screen shot 2016-04-18 at 06 25 53](https://issues.joomla.org/uploads/1/306ea891d9e672709248b304b263962e.png)

[systeminfo-2016-04-18T11_08_51+00_00.txt](https://issues.joomla.org/uploads/1/6cef37c82d4e37f4471d11738d9717fd.txt)

**Comment by franz-wohlkoenig** [comment]
Looks like https://github.com/joomla/joomla-cms/pull/9817#issuecomment-208032634

**Comment by andrepereiradasilva** [comment]
did you test in latest staging?

**Comment by DonTregartha** [comment]
No – just in the last release – Its a live site, but I mention it in case its not been spotted.
I’m temporarily adding a height value in the .modal-page class in Firebug on the couple of occasions I needed to access the window.


Don Tregartha • Creative Director
Tregartha Dinnie Ltd, Ibex House, 5 Keller Close, Kiln Farm, Milton Keynes, MK11 3LL
Tel: 01908 306 500 • www.tregartha-dinnie.co.uk<http://www.tregartha-dinnie.co.uk/>

**Comment by JoomliC** [comment]
@DonTregartha This issue is fixed for 3.5.2, and code is already merged in current staging : https://github.com/joomla/joomla-cms/pull/9817

There, the files change you can apply to get it working until 3.5.2 to be release: https://github.com/joomla/joomla-cms/pull/9817/files
(in admin, remove the lines for template.css as done in the PR, and replace main.php file by the one of the PR ;-) )

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9970">issues.joomla.org/joomla-cms/9970</a>.</sub>

**Comment by DonTregartha** [comment]
Thanks Cyril

Don

Don Tregartha • Creative Director
Tregartha Dinnie Ltd, Ibex House, 5 Keller Close, Kiln Farm, Milton Keynes, MK11 3LL
Tel: 01908 306 500 • www.tregartha-dinnie.co.uk<http://www.tregartha-dinnie.co.uk/>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9970">issues.joomla.org/joomla-cms/9970</a>.</sub>
