### ISSUE TITLE
Error when trying to access system information

### ISSUE THREAD

**Issue by SimonBloggs** [joomla/joomla-cms#9982]
#### Steps to reproduce the issue
After updating from 3.4.8 to 3.5.1 and fix the database
When trying to access Information pages (Menu System/System Information) I'm having the following error:
> An error has occured
1682 Native table 'performance_schema'.'session_variables' has the wrong structure SQL=SHOW VARIABLES LIKE "collation_database"
Return to Control Panel

#### System information (as much as possible)
These informtions are given by the Statistics module
> OS Linux w
PHP 5.6.20
MySQLi 5.7.11-log
Caching Disabled
GZip Disabled

#### Additional comments
Everything else seems to work well

Regards

**Comment by ggppdk** [comment]
Your database is partly corrupt due 
- e.g. due to software bug (database / filesystem bug)
- e.g. due to hardware error

This is not related to Joomla,
Joomla is just asking the database, something that is supposed to be working properly

e.g. if you search the web for the issue you will find pages like:
http://stackoverflow.com/questions/6288103/native-table-performance-schema-has-the-wrong-structure

Contact your web-hosting and ask them to fix this
