### ISSUE TITLE
404 @ http://support.kw.com/manuals/Agent_Website_Admin_Tool.pdf

### ISSUE THREAD

**Issue by code2web** [joomla/joomla-cms#9983]
#### Steps to reproduce the issue
1)login @ https://kw.onelogin.com/login 
2)navigate to home/agent website admin
3)click download here in section Need Help
  <a href="http://support.kw.com/manuals/Agent_Website_Admin_Tool.pdf" target="_blank" class="style1"><u>Click here</u></a>

#### Expected result
response to generate download function

#### Actual result

404

**Comment by ggppdk** [comment]
You have posted in the wrong place, this is issue tracker of Joomla CMS

to report here
- the issue must be caused by Joomla CMS
- you also need to provide some minimum proof that it is a bug, otherwise you should search / post to: http://forum.joomla.org/

about your issue, contact the owner of the service that you are using

**Comment by code2web** [comment]
Thank you! Not sure how I ended up on git!
